### ISSUE TITLE
TypeError: Cannot read property 'marked' of undefined

### ISSUE THREAD

**Issue by giuem** [hexojs/hexo#1049]
[error] HexoError: Process failed: about/index.md
TypeError: Cannot read property 'marked' of undefined
    at module.exports (d:\hexo\blog\node_modules\hexo-renderer-marked\lib\render
er.js:53:17)
    at c:\Users\Administrator\AppData\Roaming\npm\node_modules\hexo\lib\extend\r
enderer.js:78:38
    at b (domain.js:183:18)
    at Domain.run (domain.js:123:23)
    at store.(anonymous function) (c:\Users\Administrator\AppData\Roaming\npm\no
de_modules\hexo\lib\extend\renderer.js:77:9)
    at c:\Users\Administrator\AppData\Roaming\npm\node_modules\hexo\lib\core\ren
der.js:96:9
    at fn (c:\Users\Administrator\AppData\Roaming\npm\node_modules\hexo\node_mod
ules\async\lib\async.js:641:34)
    at Object._onImmediate (c:\Users\Administrator\AppData\Roaming\npm\node_modu
les\hexo\node_modules\async\lib\async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:345:15)

**Comment by Xuanwo** [comment]
maybe you need install marked

**Comment by giuem** [comment]
solve. #988
