### ISSUE TITLE
[error] HexoError: Process failed: _posts/Swift02.md

### ISSUE THREAD

**Issue by ronansparks** [hexojs/hexo#1052]
```
ReferenceError: match is not defined
    at Object.<anonymous> (/usr/local/lib/node_modules/hexo/lib/plugins/filter/external_link.js:25:46)
    at exports.each (/usr/local/lib/node_modules/hexo/node_modules/cheerio/lib/api/traversing.js:268:24)
    at module.exports (/usr/local/lib/node_modules/hexo/lib/plugins/filter/external_link.js:11:10)
    at /usr/local/lib/node_modules/hexo/lib/post/render.js:112:11
    at iterate (/usr/local/lib/node_modules/hexo/node_modules/async/lib/async.js:149:13)
    at Object.async.eachSeries (/usr/local/lib/node_modules/hexo/node_modules/async/lib/async.js:165:9)
    at /usr/local/lib/node_modules/hexo/lib/post/render.js:111:15
    at /usr/local/lib/node_modules/hexo/lib/extend/renderer.js:78:20
    at b (domain.js:183:18)
    at Domain.run (domain.js:123:23)
```

**Comment by tommy351** [comment]
What version of Hexo did you use?

**Comment by Xuanwo** [comment]
Hello? Can you provie more info?

**Comment by ronansparks** [comment]
Sorry, I  can't. I figure out it might be something wrong about symbol in my article, like <, >, or other symbol. @Xuanwo
