### ISSUE TITLE
ERROR Plugin load failed: hexo-renderer-stylus

### ISSUE THREAD

**Issue by natew** [hexojs/hexo#1057]
When running `npm install` I get:

```
npm ERR! cb() never called!
```

When running `hexo server`:

```
Error: Cannot find module 'sax'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/nw/projects/reapp/site/node_modules/hexo-renderer-stylus/node_modules/stylus/lib/functions/image.js:17:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/nw/projects/reapp/site/node_modules/hexo-renderer-stylus/node_modules/stylus/lib/functions/index.js:15:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/nw/projects/reapp/site/node_modules/hexo-renderer-stylus/node_modules/stylus/lib/visitor/evaluator.js:18:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

With node 0.12. Trying to re-install `hexo-renderer-stylus` also results in `cb() not called`.

**Comment by natew** [comment]
With iojs:

```
ERROR Plugin load failed: hexo-renderer-stylus
Error: Cannot find module 'sax'
    at Function.Module._resolveFilename (module.js:322:15)
    at Function.Module._load (module.js:264:25)
    at Module.require (module.js:351:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/Users/nw/projects/reapp/site/node_modules/hexo-renderer-stylus/node_modules/stylus/lib/functions/image.js:17:11)
    at Module._compile (module.js:446:26)
    at Object.Module._extensions..js (module.js:464:10)
    at Module.load (module.js:341:32)
    at Function.Module._load (module.js:296:12)
    at Module.require (module.js:351:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/Users/nw/projects/reapp/site/node_modules/hexo-renderer-stylus/node_modules/stylus/lib/functions/index.js:15:13)
    at Module._compile (module.js:446:26)
    at Object.Module._extensions..js (module.js:464:10)
    at Module.load (module.js:341:32)
    at Function.Module._load (module.js:296:12)
    at Module.require (module.js:351:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/Users/nw/projects/reapp/site/node_modules/hexo-renderer-stylus/node_modules/stylus/lib/visitor/evaluator.js:18:12)
    at Module._compile (module.js:446:26)
    at Object.Module._extensions..js (module.js:464:10)
    at Module.load (module.js:341:32)
```

**Comment by Xuanwo** [comment]
maybe you should run `npm install  hexo-renderer-stylus --save`

**Comment by natew** [comment]
That doesn't work, I get error: `npm ERR! cb() never called` with no npm-debug.log.

**Comment by Xuanwo** [comment]
I never see it = =.
try to reinstall nodejs&hexo.

**Comment by natew** [comment]
Tried to reinstall hexo globally and locally, still get this error. Using `hexo-3.0.0-rc.3`. Have you tried node v0.12?

```
➜  site  hexo server
ERROR Plugin load failed: hexo-renderer-stylus
Error: Cannot find module 'sax'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/nw/projects/reapp/site/node_modules/hexo-renderer-stylus/node_modules/stylus/lib/functions/image.js:17:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/nw/projects/reapp/site/node_modules/hexo-renderer-stylus/node_modules/stylus/lib/functions/index.js:15:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/nw/projects/reapp/site/node_modules/hexo-renderer-stylus/node_modules/stylus/lib/visitor/evaluator.js:18:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
INFO  Hexo is running at http://0.0.0.0:4000/. Press Ctrl+C to stop.
^CINFO  Farewell
➜  site  npm install --save hexo-renderer-stylus
npm ERR! cb() never called!
➜  site  node -v
v0.12.0
```

**Comment by Xuanwo** [comment]
Hello, I have a new idea here.
Maybe you can try this:
```
npm install hexo-renderer-marked@0.2 --save
npm install hexo-renderer-stylus@0.2 --save
npm install hexo-generator-feed@1 --save
npm install hexo-generator-sitemap@1 --save
```

**Comment by natew** [comment]
It worked for me on the latest versions a while back I forgot to close this. Thank you!

**Comment by pooii** [comment]
mark
