### ISSUE TITLE
v1.0.4 generate时报错

### ISSUE THREAD

**Issue by pharaohnie** [hexojs/hexo#106]
升级到1.0.4，post有400多篇，generate时报错如下：

```
Loading.

/Users/pharaohnie/test-hexo/node_modules/hexo/lib/plugins/processor/index.js:116
    if (err) throw new Error('File read error: ' + source);
                   ^
Error: File read error: /Users/pharaohnie/test-hexo/hexo/source/_posts/2012-10-16-jpegmini-lite-reset-counter.markdown
    at load (/Users/pharaohnie/test-hexo/node_modules/hexo/lib/plugins/processor/index.js:116:20)
    at module.exports.async.forEach.fs.exists.obj.read (/Users/pharaohnie/test-hexo/node_modules/hexo/lib/process.js:85:29)
    at fs.js:117:20
    at Object.oncomplete (fs.js:297:15)
```

**Comment by haobingwang** [comment]
Windows7 64bit，当文件数量超过 300，就会报错：RangeError: Maximum call stack size exceeded

相关信息如下：

```json
"hexo": {
    "version": "3.2.2"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-abbrlink": "^2.0.4",
    "hexo-deployer-rsync": "^0.1.2",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-json-content": "^2.1.2",
    "hexo-generator-recent": "^0.1.2",
    "hexo-generator-sitemap": "^1.1.2",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.2.0",
    "hexo-renderer-marked": "^0.2.10",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0"
  }
```

```
D:\Project\blog>hexo g
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/do
cs/troubleshooting.html
RangeError: Maximum call stack size exceeded
    at getOwnPropertySymbols (native)
    at getSymbols (D:\Project\blog\node_modules\hexo\node_modules\l
odash\lodash.js:6055:26)
    at baseGetAllKeys (D:\Project\blog\node_modules\hexo\node_modul
es\lodash\lodash.js:3064:59)
    at getAllKeys (D:\Project\blog\node_modules\hexo\node_modules\l
odash\lodash.js:5891:14)
    at baseClone (D:\Project\blog\node_modules\hexo\node_modules\lo
dash\lodash.js:2695:39)
    at Function.cloneDeep (D:\Project\blog\node_modules\hexo\node_m
odules\lodash\lodash.js:11102:14)
    at Model.findById (D:\Project\blog\node_modules\hexo\node_modul
es\warehouse\lib\model.js:122:16)
    at Model.find (D:\Project\blog\node_modules\hexo\node_modules\w
arehouse\lib\model.js:531:23)
    at null.<anonymous> (D:\Project\blog\node_modules\hexo\lib\mode
ls\category.js:46:28)
    at null.posts (D:\Project\blog\node_modules\hexo\node_modules\w
arehouse\lib\types\virtual.js:70:22)
    at null.<anonymous> (D:\Project\blog\node_modules\hexo\lib\mode
ls\category.js:56:16)
    at null.length (D:\Project\blog\node_modules\hexo\node_modules\
warehouse\lib\types\virtual.js:70:22)
    at isArrayLike (D:\Project\blog\node_modules\hexo\node_modules\
lodash\lodash.js:11347:45)
    at keys (D:\Project\blog\node_modules\hexo\node_modules\lodash\
lodash.js:13285:14)
    at baseGetAllKeys (D:\Project\blog\node_modules\hexo\node_modul
es\lodash\lodash.js:3063:20)
    at getAllKeys (D:\Project\blog\node_modules\hexo\node_modules\l
odash\lodash.js:5891:14)
    at baseClone (D:\Project\blog\node_modules\hexo\node_modules\lo
dash\lodash.js:2695:39)
    at D:\Project\blog\node_modules\hexo\node_modules\lodash\lodash
.js:2702:34
    at arrayEach (D:\Project\blog\node_modules\hexo\node_modules\lo
dash\lodash.js:537:11)
    at baseClone (D:\Project\blog\node_modules\hexo\node_modules\lo
dash\lodash.js:2696:7)
    at D:\Project\blog\node_modules\hexo\node_modules\lodash\lodash
.js:2702:34
    at arrayEach (D:\Project\blog\node_modules\hexo\node_modules\lo
dash\lodash.js:537:11)
    at baseClone (D:\Project\blog\node_modules\hexo\node_modules\lo
dash\lodash.js:2696:7)
    at D:\Project\blog\node_modules\hexo\node_modules\lodash\lodash
.js:2702:34
    at arrayEach (D:\Project\blog\node_modules\hexo\node_modules\lo
dash\lodash.js:537:11)
    at baseClone (D:\Project\blog\node_modules\hexo\node_modules\lo
dash\lodash.js:2696:7)
    at D:\Project\blog\node_modules\hexo\node_modules\lodash\lodash
.js:2702:34
    at arrayEach (D:\Project\blog\node_modules\hexo\node_modules\lo
dash\lodash.js:537:11)
    at baseClone (D:\Project\blog\node_modules\hexo\node_modules\lo
dash\lodash.js:2696:7)
    at D:\Project\blog\node_modules\hexo\node_modules\lodash\lodash
.js:2702:34
    at arrayEach (D:\Project\blog\node_modules\hexo\node_modules\lo
dash\lodash.js:537:11)
    at baseClone (D:\Project\blog\node_modules\hexo\node_modules\lo
dash\lodash.js:2696:7)
    at D:\Project\blog\node_modules\hexo\node_modules\lodash\lodash
.js:2702:34
    at arrayEach (D:\Project\blog\node_modules\hexo\node_modules\lo
dash\lodash.js:537:11)
    at baseClone (D:\Project\blog\node_modules\hexo\node_modules\lo
dash\lodash.js:2696:7)
    at D:\Project\blog\node_modules\hexo\node_modules\lodash\lodash
.js:2702:34
    at arrayEach (D:\Project\blog\node_modules\hexo\node_modules\lo
dash\lodash.js:537:11)
    at baseClone (D:\Project\blog\node_modules\hexo\node_modules\lo
dash\lodash.js:2696:7)
    at D:\Project\blog\node_modules\hexo\node_modules\lodash\lodash
.js:2702:34
    at arrayEach (D:\Project\blog\node_modules\hexo\node_modules\lo
dash\lodash.js:537:11)
    at baseClone (D:\Project\blog\node_modules\hexo\node_modules\lo
dash\lodash.js:2696:7)
    at D:\Project\blog\node_modules\hexo\node_modules\lodash\lodash
.js:2702:34
    at arrayEach (D:\Project\blog\node_modules\hexo\node_modules\lo
dash\lodash.js:537:11)
    at baseClone (D:\Project\blog\node_modules\hexo\node_modules\lo
dash\lodash.js:2696:7)
    at D:\Project\blog\node_modules\hexo\node_modules\lodash\lodash
.js:2702:34
    at arrayEach (D:\Project\blog\node_modules\hexo\node_modules\lo
dash\lodash.js:537:11)
    at baseClone (D:\Project\blog\node_modules\hexo\node_modules\lo
dash\lodash.js:2696:7)
    at D:\Project\blog\node_modules\hexo\node_modules\lodash\lodash
.js:2702:34
    at arrayEach (D:\Project\blog\node_modules\hexo\node_modules\lo
dash\lodash.js:537:11)
    at baseClone (D:\Project\blog\node_modules\hexo\node_modules\lo
dash\lodash.js:2696:7)
    at D:\Project\blog\node_modules\hexo\node_modules\lodash\lodash
.js:2702:34
    at arrayEach (D:\Project\blog\node_modules\hexo\node_modules\lo
dash\lodash.js:537:11)
FATAL Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
...
```
