### ISSUE TITLE
How do you limit the number of posts using lodash and swig?

### ISSUE THREAD

**Issue by rhewitt22** [hexojs/hexo#1066]
This gives an error:
```
<ul>
  {% for post in _.slice(site.posts, 0, 3) %}
  <li>
    <h2><a href="news/{{ url_for(post.path) }}">{{ post.title }}</a></h2>
    <p>{{ post.excerpt }}</p>
  </li>
  {% endfor %}
</ul>
```

```
Unhandled rejection Error: Unexpected number "0" on line 4.
    at Object.<anonymous> (/Applications/MAMP/htdocs/hexo-demo/node_modules/hexo/node_modules/swig/lib/tags/for.js:93:13)
    at Object.TokenParser.parseToken (/Applications/MAMP/htdocs/hexo-demo/node_modules/hexo/node_modules/swig/lib/parser.js:148:15)
    at /Applications/MAMP/htdocs/hexo-demo/node_modules/hexo/node_modules/swig/lib/parser.js:86:12
    at Object.exports.each (/Applications/MAMP/htdocs/hexo-demo/node_modules/hexo/node_modules/swig/lib/utils.js:45:11)
    at Object.TokenParser.parse (/Applications/MAMP/htdocs/hexo-demo/node_modules/hexo/node_modules/swig/lib/parser.js:76:11)
    at parseTag (/Applications/MAMP/htdocs/hexo-demo/node_modules/hexo/node_modules/swig/lib/parser.js:577:12)
    at /Applications/MAMP/htdocs/hexo-demo/node_modules/hexo/node_modules/swig/lib/parser.js:640:15
    at Object.exports.each (/Applications/MAMP/htdocs/hexo-demo/node_modules/hexo/node_modules/swig/lib/utils.js:45:11)
    at Object.exports.parse (/Applications/MAMP/htdocs/hexo-demo/node_modules/hexo/node_modules/swig/lib/parser.js:624:9)
    at parse (/Applications/MAMP/htdocs/hexo-demo/node_modules/hexo/node_modules/swig/lib/swig.js:354:19)
    at precompile (/Applications/MAMP/htdocs/hexo-demo/node_modules/hexo/node_modules/swig/lib/swig.js:486:23)
    at compile (/Applications/MAMP/htdocs/hexo-demo/node_modules/hexo/node_modules/swig/lib/swig.js:606:16)
    at Object.render (/Applications/MAMP/htdocs/hexo-demo/node_modules/hexo/node_modules/swig/lib/swig.js:525:17)
    at Hexo.swigRenderer (/Applications/MAMP/htdocs/hexo-demo/node_modules/hexo/lib/plugins/renderer/swig.js:21:15)
    at Hexo.tryCatcher (/Applications/MAMP/htdocs/hexo-demo/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
    at Hexo.<anonymous> (/Applications/MAMP/htdocs/hexo-demo/node_modules/hexo/node_modules/bluebird/js/main/method.js:15:34)
    at Promise.then.then.output (/Applications/MAMP/htdocs/hexo-demo/node_modules/hexo/lib/hexo/render.js:51:21)
    at tryCatcher (/Applications/MAMP/htdocs/hexo-demo/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/Applications/MAMP/htdocs/hexo-demo/node_modules/hexo/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/Applications/MAMP/htdocs/hexo-demo/node_modules/hexo/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromiseAtPostResolution (/Applications/MAMP/htdocs/hexo-demo/node_modules/hexo/node_modules/bluebird/js/main/promise.js:224:10)
    at Async._drainQueue (/Applications/MAMP/htdocs/hexo-demo/node_modules/hexo/node_modules/bluebird/js/main/async.js:84:12)
    at Async._drainQueues (/Applications/MAMP/htdocs/hexo-demo/node_modules/hexo/node_modules/bluebird/js/main/async.js:89:10)
    at Async.drainQueues (/Applications/MAMP/htdocs/hexo-demo/node_modules/hexo/node_modules/bluebird/js/main/async.js:14:14)
    at process._tickCallback (node.js:419:13)
```

**Comment by c0bra** [comment]
Does `site.posts.slice(0, 3` work?

**Comment by rhewitt22** [comment]
Thanks, but same error when using `site.posts.slice(0, 3)`.

**Comment by nisnaker** [comment]
@rhewitt22 
try this:
```swig
<ul>
  {% set posts = site.posts.sort('-date') %}
  {% for post in posts.slice('0', '3') %}
  <li>
    <h2><a href="news/{{ url_for(post.path) }}">{{ post.title }}</a></h2>
    <p>{{ post.excerpt }}</p>
  </li>
  {% endfor %}
</ul>
```
