### ISSUE TITLE
代码块中两个连续的花括号引起的解析错误

### ISSUE THREAD

**Issue by Eronana** [hexojs/hexo#1071]
我向往常一样,在文章中插入代码,然后生成时出现了错误
经过排查,我发现只要插入了这句代码,就会产生错误
\`\`\`C++
int bug[1][2]={{1,1}};
\`\`\`
这是合法的C++代码,但是却导致了解析错误
如果在```{{```之间加个空白字符,空格或回车,就可以避免这个错误发生,比如
\`\`\`C++
int bug[1][2]={ {1,1}};
\`\`\`
大概这只是一个小问题,而且不太容易遇到
错误详情
```
[error] HexoError: Process failed: _posts/A-bug-in-hexo.md
Error: Unexpected comma on line 2 in file /Users/Erona/Hexo/source/_posts/A-bug-in-hexo.md.
    at Object.exports.throwError (/usr/local/lib/node_modules/hexo/node_modules/swig/lib/utils.js:183:9)
    at Object.TokenParser.parseToken (/usr/local/lib/node_modules/hexo/node_modules/swig/lib/parser.js:258:15)
    at /usr/local/lib/node_modules/hexo/node_modules/swig/lib/parser.js:86:12
    at Object.exports.each (/usr/local/lib/node_modules/hexo/node_modules/swig/lib/utils.js:45:11)
    at Object.TokenParser.parse (/usr/local/lib/node_modules/hexo/node_modules/swig/lib/parser.js:76:11)
    at parseVariable (/usr/local/lib/node_modules/hexo/node_modules/swig/lib/parser.js:486:18)
    at /usr/local/lib/node_modules/hexo/node_modules/swig/lib/parser.js:633:15
    at Object.exports.each (/usr/local/lib/node_modules/hexo/node_modules/swig/lib/utils.js:45:11)
    at Object.exports.parse (/usr/local/lib/node_modules/hexo/node_modules/swig/lib/parser.js:622:9)
    at parse (/usr/local/lib/node_modules/hexo/node_modules/swig/lib/swig.js:343:19)
```

**Comment by iissnan** [comment]
[Raw](http://hexo.io/docs/tag-plugins.html#Raw)

**Comment by leesei** [comment]
{% raw %} can generally fix these kind of issue, but how to enable syntax highlighting in raw block?
