### ISSUE TITLE
无法正常渲染自定义的网页

### ISSUE THREAD

**Issue by twocucao** [hexojs/hexo#1084]
错误代码如下

Template render error: (unknown path) [Line 32, Column 38763]
  unknown block tag: \\s
    at Object.exports.withPrettyErrors (/home/micheal/SocialNetwork/Blog/node_modules/hexo/node_modules/nunjucks/src/lib.js:33:17)
    at Obj.extend.render (/home/micheal/SocialNetwork/Blog/node_modules/hexo/node_modules/nunjucks/src/environment.js:344:20)
    at Obj.extend.renderString (/home/micheal/SocialNetwork/Blog/node_modules/hexo/node_modules/nunjucks/src/environment.js:231:21)
    at /home/micheal/SocialNetwork/Blog/node_modules/hexo/lib/extend/tag.js:56:9
    at tryCatcher (/home/micheal/SocialNetwork/Blog/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._resolveFromResolver (/home/micheal/SocialNetwork/Blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:427:31)
    at new Promise (/home/micheal/SocialNetwork/Blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:53:37)
    at Tag.render (/home/micheal/SocialNetwork/Blog/node_modules/hexo/lib/extend/tag.js:55:10)
    at /home/micheal/SocialNetwork/Blog/node_modules/hexo/lib/hexo/post.js:320:16
    at tryCatcher (/home/micheal/SocialNetwork/Blog/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/home/micheal/SocialNetwork/Blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/home/micheal/SocialNetwork/Blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:530:18)
    at Async._drainQueue (/home/micheal/SocialNetwork/Blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:84:12)
    at Async._drainQueues (/home/micheal/SocialNetwork/Blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:89:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/micheal/SocialNetwork/Blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:14:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)

需要补充说明的是,我定义了三个文件夹,内置html文件,只有404的文件夹可以正常使用.

**Comment by jr0cket** [comment]
I get a `Template render error` the first time I tried my existing site with Hexo 3.  My site generates without error on Hexo 2.8, but on a new laptop with node 0.12, hexo-cli installed and using the default theme, I get the following error with hexo generate and hexo serve.

On a new empty project, hexo serve works correctly, so am assuming it is some of my content that the new version of Hexo (Nunchucks) does not like to parse.  Does that seem correct?  If so, any suggestions as to what to look for?

```
hexo generate 
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: (unknown path)
  TypeError: Cannot read property 'lineno' of null
    at Object.exports.withPrettyErrors (/home/jr0cket/projects/dev-docs/jr0cket.github.io-hexo/node_modules/hexo/node_modules/nunjucks/src/lib.js:33:17)
    at Obj.extend.render (/home/jr0cket/projects/dev-docs/jr0cket.github.io-hexo/node_modules/hexo/node_modules/nunjucks/src/environment.js:344:20)
    at Obj.extend.renderString (/home/jr0cket/projects/dev-docs/jr0cket.github.io-hexo/node_modules/hexo/node_modules/nunjucks/src/environment.js:231:21)
    at /home/jr0cket/projects/dev-docs/jr0cket.github.io-hexo/node_modules/hexo/lib/extend/tag.js:56:9
    at tryCatcher (/home/jr0cket/projects/dev-docs/jr0cket.github.io-hexo/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._resolveFromResolver (/home/jr0cket/projects/dev-docs/jr0cket.github.io-hexo/node_modules/hexo/node_modules/bluebird/js/main/promise.js:427:31)
    at new Promise (/home/jr0cket/projects/dev-docs/jr0cket.github.io-hexo/node_modules/hexo/node_modules/bluebird/js/main/promise.js:53:37)
    at Tag.render (/home/jr0cket/projects/dev-docs/jr0cket.github.io-hexo/node_modules/hexo/lib/extend/tag.js:55:10)
    at /home/jr0cket/projects/dev-docs/jr0cket.github.io-hexo/node_modules/hexo/lib/hexo/post.js:320:16
    at tryCatcher (/home/jr0cket/projects/dev-docs/jr0cket.github.io-hexo/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/home/jr0cket/projects/dev-docs/jr0cket.github.io-hexo/node_modules/hexo/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/home/jr0cket/projects/dev-docs/jr0cket.github.io-hexo/node_modules/hexo/node_modules/bluebird/js/main/promise.js:530:18)
    at Async._drainQueue (/home/jr0cket/projects/dev-docs/jr0cket.github.io-hexo/node_modules/hexo/node_modules/bluebird/js/main/async.js:84:12)
    at Async._drainQueues (/home/jr0cket/projects/dev-docs/jr0cket.github.io-hexo/node_modules/hexo/node_modules/bluebird/js/main/async.js:89:10)
    at Async.drainQueues (/home/jr0cket/projects/dev-docs/jr0cket.github.io-hexo/node_modules/hexo/node_modules/bluebird/js/main/async.js:14:14)
    at process._tickCallback (node.js:355:11)
```

My hexo / node setup:
```
hexo -v                                                                                                                                                 ⏎ 
hexo: 3.0.0
os: Linux 3.19.0-7-generic linux x64
http_parser: 2.3
node: 0.12.0
v8: 3.28.73
uv: 1.0.2
zlib: 1.2.8
modules: 14
openssl: 1.0.1l
```

**Comment by jr0cket** [comment]
Solved?

I had 4 posts with `{{ some text }}` in them,  this was removed.  I also discovered a few posts that did not close the `{% %}` notation correctly - I sometimes used a `)` instead of `%}` by accident!

It would seem that nunjucks is less forgiving than swig.  It a shame that the error output does not help find this fault by specifying which file caused the error.  I instead created a new project and copied posts over while running `hexo serve` to see when something failed.

I'll need to go through my posts and see which ones need fixing... fingers crossed...

**Comment by jr0cket** [comment]
My site now now runs via `hexo serve`.  I had some issues with `hexo generate`, that seems down to having categories & tags in pages.  Once removed, everything built, and built fast.

Thank you

**Comment by twocucao** [comment]
change your theme to version 3,here are some http://hexo.io/themes/

**Comment by likenow** [comment]
I also encountered the same problem，then I go to http://hexo.io/docs/troubleshooting.html#Escape_Contents
and the problem will has been solved.The key words is :You can wrap sensitive contents with raw tag plugin.
