### ISSUE TITLE
hexo g 命令执行失败

### ISSUE THREAD

**Issue by crystaldevil528** [hexojs/hexo#1085]
hexo: 2.8.3
os: Darwin 14.1.0 darwin x64
http_parser: 1.0
node: 0.10.36
v8: 3.14.5.9
ares: 1.9.0-DEV
uv: 0.10.30
zlib: 1.2.8
modules: 11
openssl: 1.0.1l
\-------------------------------
1、执行命令： hexo init ,进入目录后，npm install 
2、然后执行 hexo g 报错，错误如下：
-> hexo g
[error] HexoError: Process failed: _posts/hello-world.md
TypeError: Cannot read property 'config' of null
    at module.exports (/Users/evilgod528/Documents/Blog/hah/node_modules/hexo-renderer-marked/lib/renderer.js:55:10)
    at /Users/evilgod528/.nvm/v0.10.36/lib/node_modules/hexo/lib/extend/renderer.js:78:38
    at b (domain.js:183:18)
    at Domain.run (domain.js:123:23)
    at store.(anonymous function) (/Users/evilgod528/.nvm/v0.10.36/lib/node_modules/hexo/lib/extend/renderer.js:77:9)
    at /Users/evilgod528/.nvm/v0.10.36/lib/node_modules/hexo/lib/core/render.js:96:9
    at fn (/Users/evilgod528/.nvm/v0.10.36/lib/node_modules/hexo/node_modules/async/lib/async.js:641:34)
    at Object._onImmediate (/Users/evilgod528/.nvm/v0.10.36/lib/node_modules/hexo/node_modules/async/lib/async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:354:15)

**Comment by nantas** [comment]
like the error log indicates and the version guide on https://www.npmjs.com/package/hexo-renderer-marked
it's due to incompatible plugin version number.

change your plugin version specified in `package.json` like this:
```json
{
    "hexo-renderer-marked": "0.1",
    "hexo-renderer-stylus": "0.1"
}
```

will fix the issue.

**Comment by crystaldevil528** [comment]
原来如此，还真是这个问题，多谢了，这个问题昨天折腾半天

**Comment by JackGuoFranklin** [comment]
我也遇到了一样的问题。你们怎么解决的，我改变了 ，怎么还不行啊。

**Comment by hopefulnick** [comment]
The Versions in my `packsge.json` are as [https://www.npmjs.com/package/hexo-renderer-marked](url) says. But the error is still there.
