### ISSUE TITLE
使用nut主题的时候，报这个错误，请问是怎么回事儿？

### ISSUE THREAD

**Issue by Andimeo** [hexojs/hexo#1091]
```
E:\workspace\test\themes>hexo g
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/do
cs/troubleshooting.html
Error: tags/
    at maybeWrapAsError (E:\workspace\test\node_modules\hexo\node_modules\bluebi
rd\js\main\util.js:68:12)
    at E:\workspace\test\node_modules\hexo\node_modules\bluebird\js\main\promise
_resolver.js:41:50
    at Hexo.tagIndex (E:\workspace\test\themes\nut\scripts\extend.generator.js:1
0:3)
    at Hexo.tryCatcher (E:\workspace\test\node_modules\hexo\node_modules\bluebir
d\js\main\util.js:24:31)
    at Hexo.ret (eval at <anonymous> (E:\workspace\test\node_modules\hexo\node_m
odules\bluebird\js\main\promisify.js:154:12), <anonymous>:13:23)
    at Hexo.tryCatcher (E:\workspace\test\node_modules\hexo\node_modules\bluebir
d\js\main\util.js:24:31)
    at Hexo.<anonymous> (E:\workspace\test\node_modules\hexo\node_modules\bluebi
rd\js\main\method.js:15:34)
    at E:\workspace\test\node_modules\hexo\lib\hexo\index.js:325:24
    at tryCatcher (E:\workspace\test\node_modules\hexo\node_modules\bluebird\js\
main\util.js:24:31)
    at MappingPromiseArray._promiseFulfilled (E:\workspace\test\node_modules\hex
o\node_modules\bluebird\js\main\map.js:54:38)
    at MappingPromiseArray.init [as _init$] (E:\workspace\test\node_modules\hexo
\node_modules\bluebird\js\main\promise_array.js:92:18)
    at MappingPromiseArray.init (E:\workspace\test\node_modules\hexo\node_module
s\bluebird\js\main\map.js:27:23)
    at Async._drainQueue (E:\workspace\test\node_modules\hexo\node_modules\blueb
ird\js\main\async.js:84:12)
    at Async._drainQueues (E:\workspace\test\node_modules\hexo\node_modules\blue
bird\js\main\async.js:89:10)
    at Async.drainQueues (E:\workspace\test\node_modules\hexo\node_modules\blueb
ird\js\main\async.js:14:14)
    at process._tickCallback (node.js:419:13)
```

**Comment by Xuanwo** [comment]
你的hexo版本是？

**Comment by Andimeo** [comment]
$ hexo version
hexo: 3.0.0
os: Windows_NT 6.1.7601 win32 x64
http_parser: 1.0
node: 0.10.28
v8: 3.14.5.9
ares: 1.9.0-DEV
uv: 0.10.27
zlib: 1.2.3
modules: 11
openssl: 1.0.1g

$ cat package.json
{
  "hexo": {
    "version": "3.0.0"
  },
  "dependencies": {
    "hexo": "^3.0.0",
    "hexo-deployer-git": "0.0.3",
    "hexo-generator-archive": "^0.1.1",
    "hexo-generator-category": "^0.1.1",
    "hexo-generator-index": "^0.1.0",
    "hexo-generator-tag": "^0.1.0",
    "hexo-server": "^0.1.2",
    "lodash": "^2.4.1",
    "marked": "^0.3.3"
  }
}

**Comment by tommy351** [comment]
This theme doesn't support Hexo 3. You should contact the author to update it.

**Comment by Andimeo** [comment]
请问那支持这个主题的hexo版本是什么？我使用hexo2.8.3，发现css生成的不完全，比如style.css就没有生成。
