### ISSUE TITLE
"hexo server" not work

### ISSUE THREAD

**Issue by liudonghua123** [hexojs/hexo#1094]
I installed the latest hexo, and use pacman theme, but it seems had a lot of problems(see https://github.com/hexojs/hexo/issues/1059). And then I downgraded to 2.8.3 and tried again, but other errors occured as following.

```

npm uninstall hexo -g
npm install hexo@2.8.3 -g

E:\code\nodejs>
E:\code\nodejs>hexo init blog
[info] Copying data
[info] You are almost done! Don't forget to run `npm install` before you start blogging with Hexo!

E:\code\nodejs>cd blog

E:\code\nodejs\blog>npm install
hexo-renderer-ejs@0.1.0 node_modules\hexo-renderer-ejs
├── ejs@1.0.0
└── lodash@2.4.1

hexo-renderer-marked@0.2.5 node_modules\hexo-renderer-marked
├── object-assign@2.0.0
├── marked@0.3.3
├── strip-indent@1.0.1 (get-stdin@4.0.1)
└── hexo-util@0.1.6 (ent@2.2.0, bluebird@2.9.13, highlight.js@8.4.0)

hexo-renderer-stylus@0.2.2 node_modules\hexo-renderer-stylus
├── nib@1.1.0
└── stylus@0.49.3 (css-parse@1.7.0, mkdirp@0.3.5, sax@0.5.8, debug@2.1.2, source-map@0.1.43, glob@3.2.11)

E:\code\nodejs\blog>
E:\code\nodejs\blog>hexo server
[error] HexoError: Process failed: _posts/hello-world.md
TypeError: Cannot read property 'config' of null
    at module.exports (E:\code\nodejs\blog\node_modules\hexo-renderer-marked\lib\renderer.js:55:10)
    at C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\hexo\lib\extend\renderer.js:78:38
    at b (domain.js:183:18)
    at Domain.run (domain.js:123:23)
    at store.(anonymous function) (C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\hexo\lib\extend\renderer.js:77:9)
    at C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\hexo\lib\core\render.js:96:9
    at fn (C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\hexo\node_modules\async\lib\async.js:641:34)
    at Object._onImmediate (C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\hexo\node_modules\async\lib\async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:354:15)


E:\code\nodejs\blog>
E:\code\nodejs\blog>hexo version
hexo: 2.8.3
os: Windows_NT 6.2.9200 win32 x64
http_parser: 1.0
node: 0.10.35
v8: 3.14.5.9
ares: 1.9.0-DEV
uv: 0.10.30
zlib: 1.2.8
modules: 11
openssl: 1.0.1j

E:\code\nodejs\blog>
E:\code\nodejs\blog>node --version
v0.10.35

E:\code\nodejs\blog>npm --version
2.2.0

```

**Comment by tommy351** [comment]
For Hexo 2.x, you have to install `hexo-renderer-marked@0.1` and `hexo-renderer-stylus@0.1`.

**Comment by liudonghua123** [comment]
That's right! Thanks, now please close this issue.

**Comment by Xuanwo** [comment]
You can close this issue by yourself~
