### ISSUE TITLE
`hexo server` error when I change the config

### ISSUE THREAD

**Issue by breestealth** [hexojs/hexo#1099]
I change the config file to this one(just for the changed parts):

```
# Writing
new_post_name: :year:month:day.md # File name of new posts
```

In this way, when I add a new post, the post file name would be like this "20150310.md"

However, when I run `hexo server` I will got an error like this:

```
ERROR Process failed: _posts/20140130.md
ValidationError: `slug` is required!
    at SchemaTypeString.SchemaType.validate (/Users/xxxxx/Documents/blog/node_modules/hexo/node_modules/warehouse/lib/schematype.js:125:12)
    at SchemaTypeString.validate (/Users/xxxxx/Documents/blog/node_modules/hexo/node_modules/warehouse/lib/types/string.js:49:45)
    at Array.<anonymous> (/Users/xxxxx/Documents/blog/node_modules/hexo/node_modules/warehouse/lib/schema.js:198:23)
    at Schema._applySetters (/Users/xxxxx/Documents/blog/node_modules/hexo/node_modules/warehouse/lib/schema.js:369:19)
    at /Users/xxxxx/Documents/blog/node_modules/hexo/node_modules/warehouse/lib/model.js:229:24
    at tryCatcher (/Users/xxxxx/Documents/blog/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/Users/xxxxx/Documents/blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/Users/xxxxx/Documents/blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromiseAtPostResolution (/Users/xxxxx/Documents/blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:224:10)
    at Async._drainQueue (/Users/xxxxx/Documents/blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:84:12)
    at Async._drainQueues (/Users/xxxxx/Documents/blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:89:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/xxxxx/Documents/blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:14:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

I run `hexo clean` before every other command. So there would be nothing about the cache.

**Comment by Xuanwo** [comment]
@breestealth Hello, problem still exist?

**Comment by XieJunhua** [comment]
i also have this problem.And when i add a new post,and after hexo g d,could not synchronise to my github

**Comment by cjYao** [comment]
hello , this problem also exists.

**Comment by e29hz** [comment]
I alse have this problem. And I'm only new a post on my pc.

**Comment by souvenir13** [comment]
Hi, I also have this problem. and when I restore the new_post_name to ":titile.md", the error is gone. Maybe ":year:month:day.md" will name the file repeatedly? Do you resolve this problerm?

**Comment by QY-Y** [comment]
@souvenir13 Thanks! the problem disappeared after I changed back to ":titile.md"!

**Comment by Devil-C** [comment]
我改回titile.md也不报错了

**Comment by stevenjoezhang** [comment]
Reproduced in Hexo 4.2.0

**Comment by GoldAndRabbit** [comment]
> Hi, I also have this problem. and when I restore the new_post_name to ":titile.md", the error is gone. Maybe ":year:month:day.md" will name the file repeatedly? Do you resolve this problerm?

thanks
