### ISSUE TITLE
Markdown with code block {{}} breaks

### ISSUE THREAD

**Issue by natew** [hexojs/hexo#1109]
When I have a source/page.md that has a markdown code block (```) with the following:

```
'''
<Component animations={{
  self: ['fade', 'moveLeft'],
  button: 'moveRight'
}}>
'''
```

Because of the `{{` in the code it breaks the rendering. But this is valid code, so it should work.

I get this error:

```
Template render error: (unknown path) [Line 7, Column 7]
  expected variable end
    at Object.exports.withPrettyErrors (/Users/nw/projects/reapp/site/node_modules/hexo/node_modules/nunjucks/src/lib.js:33:17)
    at Obj.extend.render (/Users/nw/projects/reapp/site/node_modules/hexo/node_modules/nunjucks/src/environment.js:344:20)
    at Obj.extend.renderString (/Users/nw/projects/reapp/site/node_modules/hexo/node_modules/nunjucks/src/environment.js:231:21)
    at /Users/nw/projects/reapp/site/node_modules/hexo/lib/extend/tag.js:56:9
    at tryCatcher (/Users/nw/projects/reapp/site/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._resolveFromResolver (/Users/nw/projects/reapp/site/node_modules/hexo/node_modules/bluebird/js/main/promise.js:427:31)
    at new Promise (/Users/nw/projects/reapp/site/node_modules/hexo/node_modules/bluebird/js/main/promise.js:53:37)
    at Tag.render (/Users/nw/projects/reapp/site/node_modules/hexo/lib/extend/tag.js:55:10)
    at /Users/nw/projects/reapp/site/node_modules/hexo/lib/hexo/post.js:320:16
    at tryCatcher (/Users/nw/projects/reapp/site/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/Users/nw/projects/reapp/site/node_modules/hexo/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/Users/nw/projects/reapp/site/node_modules/hexo/node_modules/bluebird/js/main/promise.js:530:18)
    at Async._drainQueue (/Users/nw/projects/reapp/site/node_modules/hexo/node_modules/bluebird/js/main/async.js:84:12)
    at Async._drainQueues (/Users/nw/projects/reapp/site/node_modules/hexo/node_modules/bluebird/js/main/async.js:89:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/nw/projects/reapp/site/node_modules/hexo/node_modules/bluebird/js/main/async.js:14:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

If I don't use the `{{` or `}}` signs it works just fine. I'm using markdown-renderer-it.

**Comment by tommy351** [comment]
http://hexo.io/docs/troubleshooting.html#Escape_Contents
