### ISSUE TITLE
TypeError: Cannot read property 'sitemap' of undefined

### ISSUE THREAD

**Issue by sheldonrush** [hexojs/hexo#1115]
Dear Sirs,
When I want to install the plugin of hexo-generator-sitemap, but I got the error message. 
have any one can give me some suggestion ? 

hexo: 2.8.3
os: Linux 3.13.0-48-generic linux x64
http_parser: 1.0
node: 0.10.35
v8: 3.14.5.9
ares: 1.9.0-DEV
uv: 0.10.30
zlib: 1.2.8
modules: 11
openssl: 1.0.1j

BRs, 
Sheldon 

// hexo g 
[debug] 23:54:49.671 Processed: languages/zh-TW.yml (27ms)
[debug] 23:54:49.705 Generator: archive (28ms)
[debug] 23:54:49.715 Generator: category (10ms)
[debug] 23:54:49.724 Generator: home (8ms)
[debug] 23:54:49.724 Generator: page (0ms)
[debug] 23:54:49.745 Generator: post (21ms)
[debug] 23:54:49.766 Generator: tag (21ms)
[error] 23:54:49.790 TypeError: Cannot read property 'sitemap' of undefined

**Comment by sheldonrush** [comment]
TypeError: Cannot read property 'sitemap' of undefined
 22     at module.exports (/home/sheldon/git_hub/Blog/node_modules/hexo-generator-sitemap/lib/generator.js:25:17)
 23     at /usr/local/lib/node_modules/hexo/lib/theme/index.js:113:7
 24     at b (domain.js:183:18)
 25     at Domain.run (domain.js:123:23)                                                                                                              
 26     at async.each.called (/usr/local/lib/node_modules/hexo/lib/theme/index.js:112:7)
 27     at /usr/local/lib/node_modules/hexo/node_modules/async/lib/async.js:125:13
 28     at Array.forEach (native)
 29     at _each (/usr/local/lib/node_modules/hexo/node_modules/async/lib/async.js:46:24)
 30     at Object.async.each (/usr/local/lib/node_modules/hexo/node_modules/async/lib/async.js:124:9)
 31     at Theme._generate (/usr/local/lib/node_modules/hexo/lib/theme/index.js:104:9)
 32 [debug] 01:08:17.799 Generator: asset (30ms)[debug] 01:08:17.655 Processed: source/fancybox/jquery.fancybox.css (0ms)
 33 [debug] 01:08:17.655 Processed: source/fancybox/jquery.fancybox.pack.js (0ms)

**Comment by sheldonrush** [comment]
After update the version of HEXO to hexo: 3.0.0, everything is ok.
