### ISSUE TITLE
`hexo server` 遇到 `TypeError: Cannot read property 'config' of undefined`

### ISSUE THREAD

**Issue by dickeylth** [hexojs/hexo#1116]
```
~ ➤ hexo server --debug
[debug] 00:10:18.612 Config file loaded from ~/_config.yml
[debug] 00:10:18.619 Version info checked successfully
[debug] 00:10:18.647 Loading database.
[debug] 00:10:18.707 Processed: draft.md (2ms)
[debug] 00:10:18.708 Processed: page.md (2ms)
[debug] 00:10:18.709 Processed: photo.md (3ms)
[debug] 00:10:18.709 Processed: post.md (2ms)
[debug] 00:10:18.909 Plugin loaded successfully: hexo-deployer-git
[debug] 00:10:19.104 Plugin loaded successfully: hexo-deployer-heroku
[debug] 00:10:19.278 Plugin loaded successfully: hexo-deployer-openshift
[debug] 00:10:19.350 Plugin loaded successfully: hexo-deployer-rsync
[debug] 00:10:19.364 Plugin loaded successfully: hexo-generator-archive
[debug] 00:10:19.371 Plugin loaded successfully: hexo-generator-category
[debug] 00:10:19.376 Plugin loaded successfully: hexo-generator-index
[debug] 00:10:19.385 Plugin loaded successfully: hexo-generator-tag
[debug] 00:10:19.408 Plugin loaded successfully: hexo-renderer-ejs
[debug] 00:10:19.519 Plugin loaded successfully: hexo-renderer-marked
[debug] 00:10:19.797 Plugin loaded successfully: hexo-renderer-stylus
[debug] 00:10:19.955 Plugin loaded successfully: hexo-server
[debug] 00:10:19.961 Script load successfully: fancybox.js
[error] 00:10:19.962 TypeError: Cannot read property 'config' of undefined
TypeError: Cannot read property 'config' of undefined
    at module.exports (/  XXXX /node_modules/hexo-server/lib/server.js:13:20)
    at Domain.<anonymous> (/usr/local/lib/node_modules/hexo/lib/core/index.js:227:7)
    at Domain.run (domain.js:197:16)
    at Hexo.call (/usr/local/lib/node_modules/hexo/lib/core/index.js:226:7)
    at /usr/local/lib/node_modules/hexo/lib/init.js:64:10
    at /usr/local/lib/node_modules/hexo/node_modules/async/lib/async.js:157:25
    at /usr/local/lib/node_modules/hexo/node_modules/async/lib/async.js:254:17
    at /usr/local/lib/node_modules/hexo/node_modules/async/lib/async.js:157:25
    at /usr/local/lib/node_modules/hexo/node_modules/async/lib/async.js:251:21
    at /usr/local/lib/node_modules/hexo/node_modules/async/lib/async.js:615:34
    at /usr/local/lib/node_modules/hexo/lib/loaders/scripts.js:24:7
    at /usr/local/lib/node_modules/hexo/lib/util/file2.js:339:7
    at done (/usr/local/lib/node_modules/hexo/node_modules/async/lib/async.js:135:19)
    at /usr/local/lib/node_modules/hexo/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/hexo/lib/util/file2.js:335:11
    at FSReqWrap.oncomplete (evalmachine.<anonymous>:99:15)
```

date: "2015-03-16 00:10:19.966"
argv: node /usr/local/bin/hexo server --debug
os: Darwin 14.1.0 darwin x64
versions:
  http_parser: "2.3"
  node: 0.12.0
  v8: 3.28.73
  uv: 1.0.2
  zlib: 1.2.8
  modules: "14"
  openssl: 1.0.1l
  hexo: 2.8.3

**Comment by leesei** [comment]
Can you post your config?

**Comment by leesei** [comment]
Please open new issue if the problem persists with latest build.

**Comment by dong1819** [comment]
TypeError:标头中含有无效字符
在(serverresponse.setheader_http_outgoing.js:370:11)
在E:\\博客\hexo节点模块hexo-_\\lib\\服务器中间件route.js:27:11
在呼叫(e:\\\_hexo博客模块连接节点\\index.js：239：7)
在下一个(e:\\\_hexo博客模块连接节点\\index.js:183:5)
在E:\\博客\hexo节点模块hexo-_\\lib\\服务器中间件header.js:9:5
在呼叫(e:\\\_hexo博客模块连接节点\\index.js：239：7)
在下一个(e:\\\_hexo博客模块连接节点\\index.js:183:5)
function.handle（在E:\\\_hexo博客模块连接节点\\index.js:186:3)
server.app（在E:\\\_hexo博客模块连接节点\\index.js:51:37)
在(emittwoevents.js:106:13)
在(server.emitevents.js:191:7)
在(parseronincoming_http_server.js:562:12)
在(httpparser.parseronheaderscomplete_http_common.js:99:23)
