### ISSUE TITLE
hexo g命令erro

### ISSUE THREAD

**Issue by wubingwell** [hexojs/hexo#1117]
hexo: 2.8.3
os: Darwin 14.0.0 darwin x64
http_parser: 1.0
node: 0.10.36
v8: 3.14.5.9
ares: 1.9.0-DEV
uv: 0.10.30
zlib: 1.2.8
modules: 11
openssl: 1.0.1l
----------------------------------
 TypeError: Cannot read property 'feed' of undefined
TypeError: Cannot read property 'feed' of undefined
    at module.exports (/Users/Bing/Documents/hexo/node_modules/hexo-generator-feed/lib/generator.js:16:26)
    at /usr/local/lib/node_modules/hexo/lib/theme/index.js:113:7
    at b (domain.js:183:18)
    at Domain.run (domain.js:123:23)
    at async.each.called (/usr/local/lib/node_modules/hexo/lib/theme/index.js:112:7)
    at /usr/local/lib/node_modules/hexo/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/usr/local/lib/node_modules/hexo/node_modules/async/lib/async.js:46:24)
    at Object.async.each (/usr/local/lib/node_modules/hexo/node_modules/async/lib/async.js:124:9)
    at Theme._generate (/usr/local/lib/node_modules/hexo/lib/theme/index.js:104:9)

**Comment by leesei** [comment]
Can you post your repo?

**Comment by leesei** [comment]
Please open new issue if the problem persists with latest build.
