### ISSUE TITLE
Can't generate? It shows "TypeError: Cannot read property 'offset' of null"

### ISSUE THREAD

**Issue by goxofy** [hexojs/hexo#1130]
~/gaojinan » hexo generate
ERROR Process failed: _posts/A-test-blog.md
TypeError: Cannot read property 'offset' of null
    at Object.exports.timezone (/home/hellodog/gaojinan/node_modules/hexo/lib/plugins/processor/common.js:43:40)
    at /home/hellodog/gaojinan/node_modules/hexo/lib/plugins/processor/post.js:118:40
    at tryCatcher (/home/hellodog/gaojinan/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/home/hellodog/gaojinan/node_modules/hexo/node_modules/bluebird/js/main/promise.js:452:31)
    at Promise._settlePromiseAt (/home/hellodog/gaojinan/node_modules/hexo/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromises (/home/hellodog/gaojinan/node_modules/hexo/node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (/home/hellodog/gaojinan/node_modules/hexo/node_modules/bluebird/js/main/async.js:79:16)
    at Async._drainQueues (/home/hellodog/gaojinan/node_modules/hexo/node_modules/bluebird/js/main/async.js:89:10)
    at Async.drainQueues (/home/hellodog/gaojinan/node_modules/hexo/node_modules/bluebird/js/main/async.js:14:14)
    at process._tickCallback (node.js:355:11)
INFO  Files loaded in 1.06 s

**Comment by hanaarena** [comment]
I meet this error too,hava you resolved it? thx

**Comment by wkchen66** [comment]
Modify the _config.yml file in the timezone!!!!!!!!!!!!

**Comment by hanaarena** [comment]
yep,thx.I resolved this by modify the timezone config before.anyway thx:)

2015-05-17 15:28 GMT+08:00 wkchen <notifications@github.com>:

**Comment by xumeng** [comment]
Thanks you,
and here is timezone list:
[https://en.wikipedia.org/wiki/List_of_tz_database_time_zones](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)

**Comment by steven672** [comment]
Thanks, it is an timezone, issues,  I replaced some rondom correct timezone, issue resolved.`America/Los_Angeles`
