### ISSUE TITLE
Hexo generate error: ' TypeError: Cannot read property 'config' of null '.

### ISSUE THREAD

**Issue by sunaiwen** [hexojs/hexo#1142]
Is this causing by the upgrading of hexo-renderer-marked ?

When I run `hexo generate`, some error messages came out like this: 

```
[error] HexoError: Process failed: _posts/2014-07-03-zu-fang-zi.markdown
TypeError: Cannot read property 'config' of null
    at module.exports (/Users/sunaiwen/ffun/blog/node_modules/hexo-renderer-marked/lib/renderer.js:55:10)
    at /usr/local/lib/node_modules/hexo/lib/extend/renderer.js:78:38
    at b (domain.js:183:18)
    at Domain.run (domain.js:123:23)
    at store.(anonymous function) (/usr/local/lib/node_modules/hexo/lib/extend/renderer.js:77:9)
    at /usr/local/lib/node_modules/hexo/lib/core/render.js:96:9
    at fn (/usr/local/lib/node_modules/hexo/node_modules/async/lib/async.js:641:34)
    at Object._onImmediate (/usr/local/lib/node_modules/hexo/node_modules/async/lib/async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:336:15)
```

This is the Front-matter of one of my post:

```
layout: post
title: 工作一星期记
date: 2014-07-13 22:25:31 +0800
comments: true
published: true
categories:
- 说说
tags:
- 上班
---
```

**Comment by sunaiwen** [comment]
Fixed in hexo 3.0 though I don't know why.
