### ISSUE TITLE
TypeError: Cannot read property 'toLowerCase' of null

### ISSUE THREAD

**Issue by imruxin** [hexojs/hexo#1164]
```
hexo new "about git"

FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: Cannot read property 'toLowerCase' of null
    at Post.create (/Users/ruxin/website/ued/node_modules/hexo/lib/hexo/post.js:51:55)
    at Hexo.newConsole (/Users/ruxin/website/ued/node_modules/hexo/lib/plugins/console/new.js:43:20)
    at Hexo.tryCatcher (/Users/ruxin/website/ued/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
    at Hexo.<anonymous> (/Users/ruxin/website/ued/node_modules/hexo/node_modules/bluebird/js/main/method.js:15:34)
    at /Users/ruxin/website/ued/node_modules/hexo/lib/hexo/index.js:192:9
    at tryCatcher (/Users/ruxin/website/ued/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._resolveFromResolver (/Users/ruxin/website/ued/node_modules/hexo/node_modules/bluebird/js/main/promise.js:427:31)
    at new Promise (/Users/ruxin/website/ued/node_modules/hexo/node_modules/bluebird/js/main/promise.js:53:37)
    at Hexo.call (/Users/ruxin/website/ued/node_modules/hexo/lib/hexo/index.js:188:10)
    at runHexoCommand (/usr/local/lib/node_modules/hexo-cli/lib/index.js:58:17)
    at tryCatcher (/Users/ruxin/website/ued/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/Users/ruxin/website/ued/node_modules/hexo/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/Users/ruxin/website/ued/node_modules/hexo/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromises (/Users/ruxin/website/ued/node_modules/hexo/node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (/Users/ruxin/website/ued/node_modules/hexo/node_modules/bluebird/js/main/async.js:175:16)
    at Async._drainQueues (/Users/ruxin/website/ued/node_modules/hexo/node_modules/bluebird/js/main/async.js:185:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/ruxin/website/ued/node_modules/hexo/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

What's up ?

Thank you.

**Comment by Xuanwo** [comment]
version?
Is there a problem if you create a .md file in _post?

**Comment by imruxin** [comment]
@Xuanwo 
```
hexo: 3.0.1
os: Darwin 14.3.0 darwin x64
http_parser: 2.3
node: 0.12.0
v8: 3.28.73
uv: 1.0.2
zlib: 1.2.8
modules: 14
openssl: 1.0.1l
```
Creating a .md file in _post is error but copy .md then changing is ok.

**Comment by Xuanwo** [comment]
maybe you can't use space in filename?

**Comment by imruxin** [comment]
@Xuanwo 

```
hexo new test
hexo new test-test
hexo new "test"
```
it`s also error.

**Comment by leesei** [comment]
Have you tried with the latest code and dependencies?

**Comment by leesei** [comment]
Please open new issue if the problem persists with latest build.
