### ISSUE TITLE
hexo generate 出现错误

### ISSUE THREAD

**Issue by ghost** [hexojs/hexo#1192]
** 显示如下提示： **

>JS-YAML: can not read a block mapping entry; a multiline key may not be an implicit key at line 8, column 12:
  description:
                  ^

**Comment by Xuanwo** [comment]
你把md全文发出来看看呢

**Comment by shujuxw** [comment]
不好意思，由于我刚接触，不太理解你的意思，是哪一个 md 全文，我把遇到的问题详细描述一下,我在 Git Bash 里操作，在 命令 hexo g 之前都顺利，localhost:4000 也可以显示。但是输入 hexo g 之后出现了上面的提示。

**Comment by shujuxw** [comment]
不好意思，由于我刚接触，不太理解你的意思，是哪一个 md 全文，我把遇到的问题详细描述一下,我在 Git Bash 里操作，在 命令 hexo g 之前都顺利，localhost:4000 也可以显示。但是输入 hexo g 之后出现了上面的提示。

**Comment by Xuanwo** [comment]
额，这样吧，如果没有什么敏感内容的话，你可以把你的Hexo文件夹打包发给我，我本地进行一下测试。

**Comment by shujuxw** [comment]
好的，谢谢你，都这么晚了。我邮箱发给你。

**Comment by Xuanwo** [comment]
恩，好的。
嘛- -，学生党嘛，舍友在撸，我在刷同性交友。。。

**Comment by shujuxw** [comment]
哈哈，发到gmail被退信了，麻烦点这个链接下载，不着急的，麻烦了。http://dwz.cn/GxqXp

**Comment by Xuanwo** [comment]
醉了= =，我看看哈~

**Comment by frinda** [comment]
@Xuanwo 按你说的文档配置一篇没用啊。FATAL can not read a block mapping entry; a multiline key may not be an implicit                                                                                                                            key at line 9, column 7:
    author: Frinda
          ^
YAMLException: can not read a block mapping entry; a multiline key may not be an                                                                                                                            implicit key at line 9, column 7:
    author: Frinda
          ^
    at generateError (F:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:162:10)
    at throwError (F:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:168:9)
    at readBlockMapping (F:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1045                                                                                                                           :9)
    at composeNode (F:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1331:12)
    at readDocument (F:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1493:3)
    at loadDocuments (F:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1549:5)
    at Object.load (F:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1566:19)
    at Hexo.yamlHelper (F:\blog\node_modules\hexo\lib\plugins\renderer\yaml.js:7                                                                                                                           :15)
    at Hexo.tryCatcher (F:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (F:\blog\node_modules\bluebird\js\release\method.js:15:3                                                                                                                           4)
    at F:\blog\node_modules\hexo\lib\hexo\render.js:61:21
    at tryCatcher (F:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (F:\blog\node_modules\bluebird\js\relea                                                                                                                           se\promise.js:512:31)
    at Promise._settlePromise (F:\blog\node_modules\bluebird\js\release\promise.                                                                                                                           js:569:18)
    at Promise._settlePromise0 (F:\blog\node_modules\bluebird\js\release\promise                                                                                                                           .js:614:10)
    at Promise._settlePromises (F:\blog\node_modules\bluebird\js\release\promise                                                                                                                           .js:693:18)
    at Async._drainQueue (F:\blog\node_modules\bluebird\js\release\async.js:133:                                                                                                                           16)
    at Async._drainQueues (F:\blog\node_modules\bluebird\js\release\async.js:143                                                                                                                           :10)
    at Immediate.Async.drainQueues (F:\blog\node_modules\bluebird\js\release\asy                                                                                                                           nc.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)

**Comment by DeveloperZhuG** [comment]
格式不对， 比如需要空格隔开的地方，你却少了空格。

**Comment by yuaman** [comment]
良心啊！！！！昨晚折腾了一晚上，愣是不知道在哪儿！楼上的，牛！

**Comment by dytiz** [comment]
我遇到同样的问题，所有:后面价格空格就好了。
title:  Hexo

**Comment by aaeolus** [comment]
感谢dytiz

**Comment by Chiang97912** [comment]
我刚刚也遇到这个问题，我在这里补充一下，可能是是把英文的冒号打成了中文的冒号如果有人和我碰到相同的问题可以改成英文的冒号试试。

**Comment by ijiangtao** [comment]
## 我的类似踩坑经历

刚才，我在用 `hexo g` 命令生成下面这篇文章的时候：
> https://ijiangtao.github.io/2018/01/18/java/jse/java8/Java8-MethodReference/

反复出现如下错误：

`
ERROR Process failed: _posts/java/jse/java8/Java8-MethodReference.md
YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 8, column 5:
    tags: [jse,java,java8,MethodReference]
`

网上很多说法是，YUML语法要求key:后面需要加一个空格，然后再接上vlue，结果试了还是不行。

后来通过notepad++看了一下编码，确实是**TTF-8无BOM格式，文件编码正常。

后来把

tags: [jse,java,java8,MethodReference]
这一段配置删除以后，重新手输入才成功的。

总结下来，应该是字符的编码不符合标准造成编译器读取失败造成的。

为什么文件编码正确，字符编码却不对呢？

我想是因为我在其他富文本编辑器编辑过里面的部分内容，然后复制到md的，而被复制回来的字符已经被富文本编辑器“污染”了。

其实以前也遇到过类似的问题，比如读取被MS Excel编辑过的CSV，读到的内容无法正常编译，再比如从邮件里直接复制出来的SQL执行时，提示语法错误，虽然它们文件本身的字符是正确的，但是包含有不符合格式的字符，也是不行的。

希望上面的采坑记录对大家有所帮助。

**Comment by willxiang** [comment]
yml格式中，冒号后边得空格一下，不然会报错。。。

**Comment by txSangyj** [comment]
还有报下一行的错其实是上一行出问题了。。。

**Comment by Konfido** [comment]
还有中英文的空格是不一样的，得输入英文空格，而且有的行提醒错误，可能之前的行冒号后的空格输错～

**Comment by shawnyc** [comment]
确实要主要注意: 后面有没有空格，还要看看空格不是不英文空格

**Comment by daiyongtao** [comment]
多谢

**Comment by ZhuXiao0796** [comment]
多谢啊 这里推荐一下Sublime 可以高亮你的配置文件哦 有错误很容易就能看出来了

**Comment by Janene-Li** [comment]
请问出现这个错误怎么破啊。。想换个主题结果遇到了别人没遇到的问题。。哭了
$ hexo g
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError: Object.values is not a function
    at points.views.forEach.type (E:\application\hexo-blog\themes\next\scripts\events\lib\injects.js:72:46)
    at Array.forEach (native)
    at module.exports.hexo (E:\application\hexo-blog\themes\next\scripts\events\lib\injects.js:54:16)
    at Hexo.hexo.on (E:\application\hexo-blog\themes\next\scripts\events\index.js:9:27)
    at emitNone (events.js:86:13)
    at Hexo.emit (events.js:185:7)
    at Hexo._generate (E:\application\hexo-blog\node_modules\hexo\lib\hexo\index.js:399:8)
    at loadDatabase.then.then (E:\application\hexo-blog\node_modules\hexo\lib\hexo\index.js:249:22)
    at tryCatcher (E:\application\hexo-blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\application\hexo-blog\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (E:\application\hexo-blog\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (E:\application\hexo-blog\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (E:\application\hexo-blog\node_modules\bluebird\js\release\promise.js:699:18)
    at Promise._fulfill (E:\application\hexo-blog\node_modules\bluebird\js\release\promise.js:643:18)
    at PromiseArray._resolve (E:\application\hexo-blog\node_modules\bluebird\js\release\promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (E:\application\hexo-blog\node_modules\bluebird\js\release\promise_array.js:144:14)
    at Promise._settlePromise (E:\application\hexo-blog\node_modules\bluebird\js\release\promise.js:579:26)
    at Promise._settlePromise0 (E:\application\hexo-blog\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (E:\application\hexo-blog\node_modules\bluebird\js\release\promise.js:699:18)
    at _drainQueueStep (E:\application\hexo-blog\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (E:\application\hexo-blog\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (E:\application\hexo-blog\node_modules\bluebird\js\release\async.js:147:5)

**Comment by stevenjoezhang** [comment]
`Object.values`是 ES2017语法，需要将Node升级到7.0或以上版本。

**Comment by Janene-Li** [comment]
> `Object.values`是 ES2017语法，需要将Node升级到7.0或以上版本。

非常感谢！！

**Comment by kay6666** [comment]
有可能是别的冒号后边没有空格，，反正加空格就完了！nice

**Comment by wsuo** [comment]
解决了谢谢,价格空格就好了,不愧是最大的同性交友网站

**Comment by Janene-Li** [comment]
我是女生！




| |
enhanli_cs
|
|
邮箱：enhanli_cs@163.com
|

Signature is customized by Netease Mail Master

在2020年02月01日 21:27，王硕 写道：

解决了谢谢,价格空格就好了,不愧是最大的同性交友网站
