### ISSUE TITLE
body is undefined

### ISSUE THREAD

**Issue by zylqmjforever** [hexojs/hexo#1196]
hexo generate
INFO  Files loaded in 309 ms
INFO  Generated: js/scale.fix.js
INFO  Generated: js/moment.min.js
INFO  Generated: js/jquery.imagesloaded.min.js
INFO  Generated: js/gallery.js
INFO  Generated: fancybox/jquery.fancybox.pack.js
INFO  Generated: fancybox/jquery.fancybox.css
INFO  Generated: fancybox/fancybox_sprite.png
INFO  Generated: fancybox/fancybox_overlay.png
INFO  Generated: fancybox/fancybox_loading.gif
INFO  Generated: fancybox/blank.gif
INFO  Generated: css/style.css
INFO  Generated: css/images/checker.png
INFO  Generated: css/fonts/fontawesome-webfont.woff
INFO  Generated: css/fonts/fontawesome-webfont.ttf
INFO  Generated: css/fonts/fontawesome-webfont.svg
INFO  Generated: css/fonts/fontawesome-webfont.eot
INFO  Generated: css/fonts/FontAwesome.otf
Unhandled rejection ReferenceError: /Users/zylqmjforever/hexo/themes/modernist/layout/layout.ejs:5
    3|   <div class="wrapper">
    4|     <%- partial('_partial/header') %>
 >> 5|     <div class="content"><%- body %></div>
    6|   </div>
    7|   <footer id="footer"><%- partial('_partial/footer') %></footer>
    8|   <%- partial('_partial/after-footer') %>

body is not defined
    at eval (eval at <anonymous> (/Users/zylqmjforever/hexo/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:207)
    at eval (eval at <anonymous> (/Users/zylqmjforever/hexo/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:407)
    at /Users/zylqmjforever/hexo/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:255:15
    at Object.exports.render (/Users/zylqmjforever/hexo/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:293:13)
    at Hexo.<anonymous> (/Users/zylqmjforever/hexo/node_modules/hexo-renderer-ejs/index.js:5:14)
    at Hexo.tryCatcher (/Users/zylqmjforever/hexo/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
    at Hexo.<anonymous> (/Users/zylqmjforever/hexo/node_modules/hexo/node_modules/bluebird/js/main/method.js:15:34)
    at /Users/zylqmjforever/hexo/node_modules/hexo/lib/hexo/render.js:51:21
    at tryCatcher (/Users/zylqmjforever/hexo/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/Users/zylqmjforever/hexo/node_modules/hexo/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/Users/zylqmjforever/hexo/node_modules/hexo/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromiseAtPostResolution (/Users/zylqmjforever/hexo/node_modules/hexo/node_modules/bluebird/js/main/promise.js:224:10)
    at Async._drainQueue (/Users/zylqmjforever/hexo/node_modules/hexo/node_modules/bluebird/js/main/async.js:180:12)
    at Async._drainQueues (/Users/zylqmjforever/hexo/node_modules/hexo/node_modules/bluebird/js/main/async.js:185:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/zylqmjforever/hexo/node_modules/hexo/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)

**Comment by Xuanwo** [comment]
maybe you nedd to do `npm install hexo-render-ejs --save`

**Comment by ioshc** [comment]
hi, leesel , how did you resolved this problem?

**Comment by nathanielks** [comment]
@zylqmjforever I'm curious how you solved it as well!
