### ISSUE TITLE
Hexo Server Have Problem

### ISSUE THREAD

**Issue by laiyilong** [hexojs/hexo#1197]
ERROR /home/laiyilong/blog/node_modules/hexo/node_modules/lodash/index.js:2333
    /**
    ^^^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/laiyilong/blog/node_modules/hexo/node_modules/warehouse/lib/model.js:4:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/laiyilong/blog/node_modules/hexo/node_modules/warehouse/lib/database.js:6:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/laiyilong/blog/node_modules/hexo/lib/hexo/index.js:6:16)
Unhandled rejection TypeError: Cannot read property 'then' of undefined
    at /usr/lib/node_modules/hexo-cli/lib/index.js:82:21
    at tryCatcher (/usr/lib/node_modules/hexo-cli/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/hexo-cli/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/usr/lib/node_modules/hexo-cli/node_modules/bluebird/js/main/promise.js:530:18)
    at Async._drainQueue (/usr/lib/node_modules/hexo-cli/node_modules/bluebird/js/main/async.js:180:12)
    at Async._drainQueues (/usr/lib/node_modules/hexo-cli/node_modules/bluebird/js/main/async.js:185:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/hexo-cli/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
用的Archlinux,在生成的时候出现了这个问题,请问如何解决?谢谢

**Comment by Xuanwo** [comment]
直觉告诉我- -，你可能需要研究一下[这个](https://github.com/hexojs/hexo/wiki/Migrating-from-2.x-to-3.0)

**Comment by Xuanwo** [comment]
Hello, do you still have the problem?
