### ISSUE TITLE
新 clone 的代码执行 npm test 失败

### ISSUE THREAD

**Issue by lufeihaidao** [hexojs/hexo#1222]
新 clone 的代码执行 `npm test` 失败

```bash
[11:32:22] Using gulpfile ~/wwulfric/hexo/gulpfile.js
[11:32:22] Starting 'coverage'...
[11:32:23] Starting 'jshint'...
[11:32:25] Finished 'coverage' after 2.83 s
[11:32:25] Starting 'mocha'...
[11:32:25] Finished 'jshint' after 2.66 s

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^


Error: Cannot find module 'swig-extras'
    at Function.Module._resolveFilename (module.js:331:15)
    at Function.Module._load (module.js:273:25)


    at Module.require (module.js:357:17)
    at require (module.js:373:17)
    at Object.<anonymous> (/Users/haidao/wwulfric/hexo/lib/plugins/renderer/swig.js:9:113)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (/Users/haidao/wwulfric/hexo/node_modules/gulp-istanbul/node_modules/istanbul/lib/hook.js:100:20)
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)
    at Module.require (module.js:357:17)
    at require (module.js:373:17)
    at Suite.<anonymous> (/Users/haidao/wwulfric/hexo/test/scripts/renderers/swig.js:7:11)
    at context.describe.context.context (/Users/haidao/wwulfric/hexo/node_modules/mocha/lib/interfaces/bdd.js:49:10)
    at Object.<anonymous> (/Users/haidao/wwulfric/hexo/test/scripts/renderers/swig.js:6:1)
    at Module._compile (module.js:449:26)
    at Module._extensions..js (module.js:467:10)
    at Object.Module._extensions..js (/Users/haidao/wwulfric/hexo/node_modules/gulp-istanbul/node_modules/istanbul/lib/hook.js:102:13)
    at Module.load (module.js:349:32)
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

**Comment by lufeihaidao** [comment]
以上问题通过 `npm install swig-extra` 解决（package.json 需要加入这个 lib 吗），而后出现新的错误

```bash
[11:43:26] Using gulpfile ~/wwulfric/hexo/gulpfile.js
[11:43:26] Starting 'coverage'...
[11:43:26] Starting 'jshint'...
[11:43:29] Finished 'coverage' after 2.89 s
[11:43:29] Starting 'mocha'...
[11:43:29] Finished 'jshint' after 2.67 s


  Hexo
    Box
      Box
        ✓ constructor - add trailing "/" to the base path
        ✓ addProcessor() - no pattern
        ✓ addProcessor() - with regex
        ✓ addProcessor() - with pattern
        ✓ addProcessor() - no fn
        1) _loadFiles() - create
        2) _loadFiles() - update
Stacktrace (dead0000-dead0001) 0x2ca831604181 0x1f8f60004191:
==== JS stack trace =========================================

Security context: 0x2ca83160f3f1 <JS Object>#0#
    1: DefaultString [native runtime.js:394] (this=0x2ca831611261 <JS Object>#1#,a=0x2ca831604181 <the hole>)
    2: ToString [native runtime.js:333] (this=0x2ca831611261 <JS Object>#1#,a=0x2ca831604181 <the hole>)
    3: STRING_ADD_RIGHT(aka STRING_ADD_RIGHT) [native runtime.js:131] (this=0x2ca831604181 <the hole>,a=0x13b9faf046a9 <String[0]: >)
    5: safeToString(aka safeToString) [/Users/haidao/wwulfric/hexo/node_modules/bluebird/js/main/util.js:193] (this=0x2ca831604121 <undefined>,obj=0x2ca831604181 <the hole>)
    6: ensureErrorObject [/Users/haidao/wwulfric/hexo/node_modules/bluebird/js/main/util.js:226] (this=0x371184ab0db1 <an Object with map 0x2b74d4074901>#2#,value=0x2ca831604181 <the hole>)
    7: _rejectCallback [/Users/haidao/wwulfric/hexo/node_modules/bluebird/js/main/promise.js:416] (this=0x158fd84bb611 <a Promise with map 0x2b74d40611f1>#3#,reason=0x2ca831604181 <the hole>,synchronous=0x2ca831604161 <false>,shouldNotMarkOriginatingFromRejection=0x2ca831604141 <true>)
    8: _settlePromiseFromHandler [/Users/haidao/wwulfric/hexo/node_modules/bluebird/js/main/promise.js:460] (this=0x158fd84bb5c1 <a Promise with map 0x2b74d40611f1>#4#,handler=0x158fd84bb509 <JS Function (SharedFunctionInfo 0x2f51c6793a01)>#5#,receiver=0x371184ab3099 <an Object with map 0x1f8f60008319>#6#,value=0x158fd84bedc1 <JS Array[2]>#7#,promise=0x158fd84bb611 <a Promise with map 0x2b74d40611f1>#3#)
    9: _settlePromiseAt [/Users/haidao/wwulfric/hexo/node_modules/bluebird/js/main/promise.js:530] (this=0x158fd84bb5c1 <a Promise with map 0x2b74d40611f1>#4#,index=0)
   10: _settlePromises [/Users/haidao/wwulfric/hexo/node_modules/bluebird/js/main/promise.js:646] (this=0x158fd84bb5c1 <a Promise with map 0x2b74d40611f1>#4#)
   11: _drainQueue [/Users/haidao/wwulfric/hexo/node_modules/bluebird/js/main/async.js:79] (this=0x371184ab1299 <an Async with map 0x2b74d4076011>#8#,queue=0x371184ace419 <a Queue with map 0x2b74d4075ea9>#9#)
   12: _drainQueues [/Users/haidao/wwulfric/hexo/node_modules/bluebird/js/main/async.js:89] (this=0x371184ab1299 <an Async with map 0x2b74d4076011>#8#)
   13: /* anonymous */(aka /* anonymous */) [/Users/haidao/wwulfric/hexo/node_modules/bluebird/js/main/async.js:14] (this=0x2ca831604121 <undefined>)
   14: _tickDomainCallback [node.js:372] (this=0x704a760a539 <a process with map 0x1f8f600146d9>#10#)

==== Details ================================================

[1]: DefaultString [native runtime.js:394] (this=0x2ca831611261 <JS Object>#1#,a=0x2ca831604181 <the hole>) {
  // stack-allocated locals
  var b = 0x2ca831604121 <undefined>
  var c = 0x2ca831604121 <undefined>
  var d = 0x2ca831604121 <undefined>
  var e = 0x2ca831604121 <undefined>
  // expression stack (top to bottom)
  [05] : 0x13b9faf04ab9 <String[8]: toString>
  [04] : 0x2ca831604181 <the hole>
--------- s o u r c e   c o d e ---------
function DefaultString(a){?var b=a.toString;?if((%_ClassOf(b)==='Function')){?var c=%_CallFunction(a,b);?if(%IsPrimitive(c))return c;?}?var d=a.valueOf;?if((%_ClassOf(d)==='Function')){?var e=%_CallFunction(a,d);?if(%IsPrimitive(e))return e;?}?throw %MakeTypeError('cannot_convert_to_primitive',[]);?}
-----------------------------------------
}

[2]: ToString [native runtime.js:333] (this=0x2ca831611261 <JS Object>#1#,a=0x2ca831604181 <the hole>) {
  // expression stack (top to bottom)
  [04] : 0x2ca831604181 <the hole>
  [03] : 0x2ca831611261 <JS Object>#1#
  [02] : 0x2ca831614c49 <JS Function DefaultString (SharedFunctionInfo 0x2ca8316132d9)>#11#
  [01] : 0x2ca831611261 <JS Object>#1#
  [00] : 0x2ca8316147b9 <JS Function ToString (SharedFunctionInfo 0x2ca831612d39)>#12#
--------- s o u r c e   c o d e ---------
function ToString(a){?if((typeof(a)==='string'))return a;?if((typeof(a)==='number'))return %_NumberToString(a);?if((typeof(a)==='boolean'))return a?'true':'false';?if((typeof(a)==='undefined'))return'undefined';?if((typeof(a)==='symbol'))throw %MakeTypeError('symbol_to_string',[]);?return((a===null))?'null':%ToStrin...

-----------------------------------------
}

[3]: STRING_ADD_RIGHT(aka STRING_ADD_RIGHT) [native runtime.js:131] (this=0x2ca831604181 <the hole>,a=0x13b9faf046a9 <String[0]: >) {
  // stack-allocated locals
  var b = 0x2ca831604181 <the hole>
  // expression stack (top to bottom)
  [03] : 0x2ca831604181 <the hole>
  [02] : 0x2ca831611261 <JS Object>#1#
  [01] : 0x2ca8316147b9 <JS Function ToString (SharedFunctionInfo 0x2ca831612d39)>#12#
--------- s o u r c e   c o d e ---------
function STRING_ADD_RIGHT(a){?var b=this;?if(!(typeof(b)==='string')){?if((%_ClassOf(b)==='String')&&%_IsStringWrapperSafeForDefaultValueOf(b)){?b=%_ValueOf(b);?}else{?b=(typeof(b)==='number')??%_NumberToString(b)?:%ToString(%ToPrimitive(b,0));?}?}?return %_StringAdd(b,a);?}
-----------------------------------------
}

[5]: safeToString(aka safeToString) [/Users/haidao/wwulfric/hexo/node_modules/bluebird/js/main/util.js:193] (this=0x2ca831604121 <undefined>,obj=0x2ca831604181 <the hole>) {
  // expression stack (top to bottom)
--------- s o u r c e   c o d e ---------
function safeToString(obj) {?    try {?        return obj + "";?    } catch (e) {?        return "[no string representation]";?    }?}
-----------------------------------------
}

[6]: ensureErrorObject [/Users/haidao/wwulfric/hexo/node_modules/bluebird/js/main/util.js:226] (this=0x371184ab0db1 <an Object with map 0x2b74d4074901>#2#,value=0x2ca831604181 <the hole>) {
  // expression stack (top to bottom)
  [03] : 0x2ca831604181 <the hole>
  [02] : 0x2ca831604121 <undefined>
  [01] : 0x371184acdec9 <JS Function safeToString (SharedFunctionInfo 0x3fa77e9fe181)>#13#
  [00] : 0x2ca8316651d9 <JS Function Error (SharedFunctionInfo 0x2ca831632851)>#14#
--------- s o u r c e   c o d e ---------
function (value) {?            if (canAttachTrace(value)) return value;?            return new Error(safeToString(value));?        }
-----------------------------------------
}

[7]: _rejectCallback [/Users/haidao/wwulfric/hexo/node_modules/bluebird/js/main/promise.js:416] (this=0x158fd84bb611 <a Promise with map 0x2b74d40611f1>#3#,reason=0x2ca831604181 <the hole>,synchronous=0x2ca831604161 <false>,shouldNotMarkOriginatingFromRejection=0x2ca831604141 <true>) {
  // stack-allocated locals
  var trace = 0x2ca831604121 <undefined>
  var hasStack = 0x2ca831604121 <undefined>
  // expression stack (top to bottom)
  [04] : 0x2ca831604181 <the hole>
  [03] : 0x371184ab0db1 <an Object with map 0x2b74d4074901>#2#
  [02] : 0x371184acdfa1 <JS Function (SharedFunctionInfo 0x3fa77e9feb09)>#15#
--------- s o u r c e   c o d e ---------
function (reason, synchronous, shouldNotMarkOriginatingFromRejection) {?    if (!shouldNotMarkOriginatingFromRejection) {?        util.markAsOriginatingFromRejection(reason);?    }?    var trace = util.ensureErrorObject(reason);?    var hasStack = trace === reason;?    this._attachExtraTrace(trace, synchrono...

-----------------------------------------
}

[8]: _settlePromiseFromHandler [/Users/haidao/wwulfric/hexo/node_modules/bluebird/js/main/promise.js:460] (this=0x158fd84bb5c1 <a Promise with map 0x2b74d40611f1>#4#,handler=0x158fd84bb509 <JS Function (SharedFunctionInfo 0x2f51c6793a01)>#5#,receiver=0x371184ab3099 <an Object with map 0x1f8f60008319>#6#,value=0x158fd84bedc1 <JS Array[2]>#7#,promise=0x158fd84bb611 <a Promise with map 0x2b74d40611f1>#3#) {
  // stack-allocated locals
  var x = 0x371184ab2d61 <an Object with map 0x2b74d4074751>#16#
  var err = 0x2ca831604181 <the hole>
  // expression stack (top to bottom)
  [06] : 0x2ca831604141 <true>
  [05] : 0x2ca831604161 <false>
  [04] : 0x2ca831604181 <the hole>
  [03] : 0x158fd84bb611 <a Promise with map 0x2b74d40611f1>#3#
  [02] : 0x2baf8fcdd8e9 <JS Function Promise._rejectCallback (SharedFunctionInfo 0x3fa77e9fcad1)>#17#
--------- s o u r c e   c o d e ---------
function (?    handler, receiver, value, promise?) {?    if (promise._isRejected()) return;?    promise._pushContext();?    var x;?    if (receiver === APPLY && !this._isRejected()) {?        x = tryCatch(handler).apply(this._boundTo, value);?
[1]    88004 illegal hardware instruction  npm test
```

**Comment by lufeihaidao** [comment]
在 Ubuntu 下测试没问题，以上问题是在 mac 运行得到的
```bash
hexo: 2.8.3
os: Darwin 14.3.0 darwin x64
http_parser: 2.2
node: 0.11.13
v8: 3.25.30
uv: 0.11.25
zlib: 1.2.3
modules: 14
openssl: 1.0.1g
```

**Comment by Xuanwo** [comment]
Hexo目前只在Linux和Win下进行测试，Mac的情况不是很了解= =。

你可以试试看3.1.1能通过么？

**Comment by leesei** [comment]
能過
