### ISSUE TITLE
TypeError: Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by F1ReKing** [hexojs/hexo#1232]
at D:\hexo\node_modules\hexo\lib\hexo\load_config.js:35:28
    at tryCatcher (D:\hexo\node_modules\hexo\node_modules\bluebird\js\main\util.js:24:31)
    at Promise._settlePromiseFromHandler (D:\hexo\node_modules\hexo\node_modules\bluebird\js\main\promise.js:454:31)
    at Promise._settlePromiseAt (D:\hexo\node_modules\hexo\node_modules\bluebird\js\main\promise.js:530:18)
    at Async._drainQueue (D:\hexo\node_modules\hexo\node_modules\bluebird\js\main\async.js:180:12)
    at Async._drainQueues (D:\hexo\node_modules\hexo\node_modules\bluebird\js\main\async.js:185:10)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\hexo\node_modules\hexo\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)

**Comment by leesei** [comment]
Please describe what you're trying to do.

**Comment by F1ReKing** [comment]
It's ok , Thank you.

**Comment by thirtyyuan** [comment]
@F1ReKing Can you teach me how to solve the problem? thank u!

**Comment by ulisesantana** [comment]
I hace the same issue @thirtyyuan, did you fixed?
