### ISSUE TITLE
generate & host 均失败

### ISSUE THREAD

**Issue by lufeihaidao** [hexojs/hexo#1268]
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:905:11)
    at Object.afterWrite (net.js:721:19)
```

```
os: Linux 2.6.32-431.23.3.el6.x86_64 linux x64
http_parser: 2.0
node: 0.10.36
v8: 3.14.5.10
ares: 1.9.1
uv: 0.10.34
zlib: 1.2.3
modules: 11
openssl: 1.0.1e-fips
```

**Comment by Xuanwo** [comment]
- 删掉目录下的`db.json`
- 执行`hexo g`
- 执行`hexo d`

看看是不是依然有问题？

**Comment by lufeihaidao** [comment]
@Xuanwo 你好，后来我找到原因了，是因为 markdown 的 render 没有安装（我使用的是 pandoc）。这个原因还是从输出 `afterWrite` 猜到的，是不是因为错误输出不够细致？我觉得这样的错误应该是报错：找不到 markdown renderer 才对。

这个 issue close 吧

**Comment by Xuanwo** [comment]
根据官方的操作- -，并不会有这个报错，因为要执行`npm install`。

**Comment by liuqinh2s** [comment]
我也遇到了这个问题，我用的是 mac os x

**Comment by liuqinh2s** [comment]
我安装了hexo-render-pandoc，pandoc也安装好了，但还是报这个错
