### ISSUE TITLE
FtpSync上传文件报错

### ISSUE THREAD

**Issue by Witype** [hexojs/hexo#1270]
![Uploading pasted_image.jpg…]()

MKDIRs complete.
- /2015/05/14/long-text-test/index.html uploaded successfuly
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write ECONNRESET
    at exports._errnoException (util.js:746:11)
    at Socket._writeGeneric (net.js:690:26)
    at Socket._write (net.js:709:8)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at Socket.Writable.write (_stream_writable.js:217:11)
    at Socket.write (net.js:634:40)
    at Stream.method [as write] (F:\WorkFolder\witypeHexo\node_modules\hexo-dep
oyer-ftpsync\node_modules\ftpsync\node_modules\jsftp\node_modules\event-stream\
ode_modules\duplexer\index.js:47:39)
    at Ftp.send (F:\WorkFolder\witypeHexo\node_modules\hexo-deployer-ftpsync\no
e_modules\ftpsync\node_modules\jsftp\lib\jsftp.js:185:17)
    at Ftp.nextCmd (F:\WorkFolder\witypeHexo\node_modules\hexo-deployer-ftpsync
node_modules\ftpsync\node_modules\jsftp\lib\jsftp.js:194:10)
    at Ftp.parse (F:\WorkFolder\witypeHexo\node_modules\hexo-deployer-ftpsync\n
de_modules\ftpsync\node_modules\jsftp\lib\jsftp.js:262:8)
    at Ftp.parseResponse (F:\WorkFolder\witypeHexo\node_modules\hexo-deployer-f
psync\node_modules\ftpsync\node_modules\jsftp\lib\jsftp.js:173:8)
    at Stream.<anonymous> (F:\WorkFolder\witypeHexo\node_modules\hexo-deployer-
tpsync\node_modules\ftpsync\node_modules\jsftp\lib\jsftp.js:145:24)
    at Stream.emit (events.js:107:17)
    at ResponseParser.reemit (F:\WorkFolder\witypeHexo\node_modules\hexo-deploy
r-ftpsync\node_modules\ftpsync\node_modules\jsftp\node_modules\event-stream\nod
_modules\duplexer\index.js:70:25)
    at ResponseParser.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at ResponseParser.Readable.push (_stream_readable.js:126:10)
    at ResponseParser.Transform.push (_stream_transform.js:140:32)
    at ResponseParser.<anonymous> (F:\WorkFolder\witypeHexo\node_modules\hexo-d
ployer-ftpsync\node_modules\ftpsync\node_modules\jsftp\node_modules\ftp-respons
-parser\index.js:65:12)
    at Array.forEach (native)
    at ResponseParser._transform (F:\WorkFolder\witypeHexo\node_modules\hexo-de
loyer-ftpsync\node_modules\ftpsync\node_modules\jsftp\node_modules\ftp-response
parser\index.js:48:9)
    at ResponseParser.Transform._read (_stream_transform.js:179:10)
    at ResponseParser.Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at ResponseParser.Writable.write (_stream_writable.js:217:11)
    at Socket.ondata (_stream_readable.js:540:20)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)

**Comment by Nerom** [comment]
可能是异步执行的线程数比较多，超过连接数了，稍后我看下解决办法 发自网易邮箱大师 在2015年05月15日 15:23 ，WiType716写道： MKDIRs complete. /2015/05/14/long-text-test/index.html uploaded successfuly events.js:85 throw er; // Unhandled 'error' event ^ Error: write ECONNRESET at exports._errnoException (util.js:746:11) at Socket._writeGeneric (net.js:690:26) at Socket._write (net.js:709:8) at doWrite (_stream_writable.js:301:12) at writeOrBuffer (_stream_writable.js:288:5) at Socket.Writable.write (_stream_writable.js:217:11) at Socket.write (net.js:634:40) at Stream.method as write at Ftp.send (F:\WorkFolder\witypeHexo\node_modules\hexo-deployer-ftpsync\no e_modules\ftpsync\node_modules\jsftp\lib\jsftp.js:185:17) at Ftp.nextCmd (F:\WorkFolder\witypeHexo\node_modules\hexo-deployer-ftpsync node_modules\ftpsync\node_modules\jsftp\lib\jsftp.js:194:10) at Ftp.parse (F:\WorkFolder\witypeHexo\node_modules\hexo-deployer-ftpsync\n de_modules\ftpsync\node_modules\jsftp\lib\jsftp.js:262:8) at Ftp.parseResponse (F:\WorkFolder\witypeHexo\node_modules\hexo-deployer-f psync\node_modules\ftpsync\node_modules\jsftp\lib\jsftp.js:173:8) at Stream. (F:\WorkFolder\witypeHexo\node_modules\hexo-deployer- tpsync\node_modules\ftpsync\node_modules\jsftp\lib\jsftp.js:145:24) at Stream.emit (events.js:107:17) at ResponseParser.reemit (F:\WorkFolder\witypeHexo\node_modules\hexo-deploy r-ftpsync\node_modules\ftpsync\node_modules\jsftp\node_modules\event-stream\nod _modules\duplexer\index.js:70:25) at ResponseParser.emit (events.js:107:17) at readableAddChunk (_stream_readable.js:163:16) at ResponseParser.Readable.push (_stream_readable.js:126:10) at ResponseParser.Transform.push (_stream_transform.js:140:32) at ResponseParser. (F:\WorkFolder\witypeHexo\node_modules\hexo-d ployer-ftpsync\node_modules\ftpsync\node_modules\jsftp\node_modules\ftp-respons -parser\index.js:65:12) at Array.forEach (native) at ResponseParser._transform (F:\WorkFolder\witypeHexo\node_modules\hexo-de loyer-ftpsync\node_modules\ftpsync\node_modules\jsftp\node_modules\ftp-response parser\index.js:48:9) at ResponseParser.Transform._read (_stream_transform.js:179:10) at ResponseParser.Transform._write (_stream_transform.js:167:12) at doWrite (_stream_writable.js:301:12) at writeOrBuffer (_stream_writable.js:288:5) at ResponseParser.Writable.write (_stream_writable.js:217:11) at Socket.ondata (_stream_readable.js:540:20) at Socket.emit (events.js:107:17) at readableAddChunk (_stream_readable.js:163:16) at Socket.Readable.push (_stream_readable.js:126:10) at TCP.onread (net.js:538:20) — Reply to this email directly or view it on GitHub.

**Comment by Witype** [comment]
我使用的是www.net.com万网的虚拟主机，因为操作系统是Liunx，上传总是失败，但是把操作系统更换为win2008后一切正常，不知道这是hexo的问题还是万网的问题，已经给万网提交工单了，期待解决！

**Comment by Nerom** [comment]
也不是hexo的问题，是依赖的ftpsync模块的问题，万网主机上传不支持并发连接应该是，依赖的模块不能随便改，我试试联系作者解决吧，最近比较忙，见谅 发自网易邮箱大师 在2015年05月16日 14:05 ，WiType716写道： 我使用的是www.net.com万网的虚拟主机，因为操作系统是Liunx，上传总是失败，但是把操作系统更换为win2008后一切正常，不知道这是hexo的问题还是万网的问题，已经给万网提交工单了，期待解决！ — Reply to this email directly or view it on GitHub.

**Comment by Witype** [comment]
顺便问一下，因为万网会在网站的根目录创建一个目录aspnet_client，我将这个添加到ignore中，但是在文件上传的过程中会跳出错误。
Additions complete.
RMDIR failed.
RMDIRs failed.
Commit failed.
Commit complete.
RMDIRs complete.
- //aspnet_client/system_web/_0_30319 deleted successfuly
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/do
cs/troubleshooting.html
Error: 550 The system cannot find the file specified.
    at Ftp.parse (F:\WorkFolder\witypeHexo\node_modules\hexo-deployer-ftpsync\no
de_modules\ftpsync\node_modules\jsftp\lib\jsftp.js:256:11)

**Comment by leesei** [comment]
This issue was moved to hexojs/hexo-deployer-ftpsync#5
