### ISSUE TITLE
 Hi! `npm install hexo --no-optional` can not solve cannot find module DTraceProviderBindings

### ISSUE THREAD

**Issue by Lluvio** [hexojs/hexo#1274]
when i did `npm install hexo --no-optional`, but all command get these:

```
{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
```
```bash
Vennzi:blog Lluvio$ hexo -v
{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
hexo: 3.0.1
os: Darwin 14.3.0 darwin x64
http_parser: 2.3.0
node: 1.8.1
v8: 4.1.0.27
uv: 1.4.2
zlib: 1.2.8
ares: 1.10.0-DEV
modules: 43
openssl: 1.0.2a
```

**Comment by Xuanwo** [comment]
in 3.1.0 and up, you need `npm install hexo-cli -g` && `npm install hexo --save`

**Comment by chenyuxu** [comment]
is not work @Xuanwo

**Comment by willin** [comment]
```
[hexo-cli@*] installed at node_modules/.hexo-cli_npminstall/hexo-cli/1.0.1/hexo-cli (106 packages, use 3s, speed 178.68kB/s, json 619.85kB, tarball 0B)
excute post install scripts...
[spawn-sync@1.0.15] scripts.postinstall: "node postinstall" at ./.nvm/versions/node/v6.2.0/lib/node_modules/.hexo-cli_npminstall/spawn-sync/1.0.15/spawn-sync
[spawn-sync@1.0.15] scripts.postinstall success, use 58ms
[hexo-util@0.5.3] scripts.postinstall: "npm run build:highlight" at ./.nvm/versions/node/v6.2.0/lib/node_modules/.hexo-cli_npminstall/hexo-util/0.5.3/hexo-util

> hexo-util@0.5.3 build:highlight /Users/willin/.nvm/versions/node/v6.2.0/lib/node_modules/.hexo-cli_npminstall/hexo-util/0.5.3/hexo-util
> node scripts/build_highlight_alias.js > highlight_alias.json

[hexo-util@0.5.3] scripts.postinstall success, use 534ms
[dtrace-provider@0.6.0] scripts.install: "node scripts/install.js" at ./.nvm/versions/node/v6.2.0/lib/node_modules/.hexo-cli_npminstall/dtrace-provider/0.6.0/dtrace-provider
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at Object.<anonymous> (/Users/willin/.nvm/versions/node/v6.2.0/lib/node_modules/.hexo-cli_npminstall/dtrace-provider/0.6.0/dtrace-provider/scripts/install.js:19:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
[Error: Run "sh -c node scripts/install.js" error, exit code 1
    at ChildProcess.proc.on.code (/Users/willin/.nvm/versions/node/v6.2.0/lib/node_modules/cnpm/node_modules/runscript/index.js:67:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)@%s] optional error: %s
All packages installed (106 packages installed from npm registry, use 4s, speed 149.83kB/s, json 118(619.85kB), tarball 0B)
```

**Comment by willin** [comment]
```
hexo init blog
{ Error: Cannot find module './build/Release/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/willin/.nvm/versions/node/v6.2.0/lib/node_modules/.hexo-cli_npminstall/dtrace-provider/0.6.0/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/willin/.nvm/versions/node/v6.2.0/lib/node_modules/.hexo-cli_npminstall/bunyan/1.8.1/bunyan/lib/bunyan.js:79:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/default/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/willin/.nvm/versions/node/v6.2.0/lib/node_modules/.hexo-cli_npminstall/dtrace-provider/0.6.0/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/willin/.nvm/versions/node/v6.2.0/lib/node_modules/.hexo-cli_npminstall/bunyan/1.8.1/bunyan/lib/bunyan.js:79:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Debug/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/willin/.nvm/versions/node/v6.2.0/lib/node_modules/.hexo-cli_npminstall/dtrace-provider/0.6.0/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/willin/.nvm/versions/node/v6.2.0/lib/node_modules/.hexo-cli_npminstall/bunyan/1.8.1/bunyan/lib/bunyan.js:79:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32) code: 'MODULE_NOT_FOUND' }
INFO  Cloning hexo-starter to ~/Desktop/blog
Cloning into '/Users/willin/Desktop/blog'...
remote: Counting objects: 53, done.
remote: Total 53 (delta 0), reused 0 (delta 0), pack-reused 53
Unpacking objects: 100% (53/53), done.
Checking connectivity... done.
Submodule 'themes/landscape' (https://github.com/hexojs/hexo-theme-landscape.git) registered for path 'themes/landscape'
Cloning into 'themes/landscape'...
remote: Counting objects: 730, done.
remote: Total 730 (delta 0), reused 0 (delta 0), pack-reused 730
Receiving objects: 100% (730/730), 2.51 MiB | 313.00 KiB/s, done.
Resolving deltas: 100% (386/386), done.
Checking connectivity... done.
Submodule path 'themes/landscape': checked out 'decdc2d9956776cbe95420ae94bac87e22468d38'
INFO  Install dependencies
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN prefer global marked@0.3.5 should be installed with -g

> fsevents@1.0.12 install /Users/willin/Desktop/blog/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  COPY /Users/willin/Desktop/blog/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node
  TOUCH Release/obj.target/action_after_build.stamp

> dtrace-provider@0.6.0 install /Users/willin/Desktop/blog/node_modules/dtrace-provider
> node scripts/install.js


> spawn-sync@1.0.15 postinstall /Users/willin/Desktop/blog/node_modules/spawn-sync
> node postinstall


> hexo-util@0.5.3 postinstall /Users/willin/Desktop/blog/node_modules/hexo-util
> npm run build:highlight


> hexo-util@0.5.3 build:highlight /Users/willin/Desktop/blog/node_modules/hexo-util
> node scripts/build_highlight_alias.js > highlight_alias.json

hexo-site@0.0.0 /Users/willin/Desktop/blog
```

**Comment by willin** [comment]
```
hexo s
{ Error: Cannot find module './build/Release/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/willin/.nvm/versions/node/v6.2.0/lib/node_modules/.hexo-cli_npminstall/dtrace-provider/0.6.0/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/willin/.nvm/versions/node/v6.2.0/lib/node_modules/.hexo-cli_npminstall/bunyan/1.8.1/bunyan/lib/bunyan.js:79:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/default/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/willin/.nvm/versions/node/v6.2.0/lib/node_modules/.hexo-cli_npminstall/dtrace-provider/0.6.0/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/willin/.nvm/versions/node/v6.2.0/lib/node_modules/.hexo-cli_npminstall/bunyan/1.8.1/bunyan/lib/bunyan.js:79:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Debug/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/willin/.nvm/versions/node/v6.2.0/lib/node_modules/.hexo-cli_npminstall/dtrace-provider/0.6.0/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/willin/.nvm/versions/node/v6.2.0/lib/node_modules/.hexo-cli_npminstall/bunyan/1.8.1/bunyan/lib/bunyan.js:79:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32) code: 'MODULE_NOT_FOUND' }
INFO  Start processing
INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.
```

**Comment by lufeihaidao** [comment]
same issue

**Comment by Xuanwo** [comment]
`npm install hexo --save --no-optional` please.

**Comment by haaaiiimmm** [comment]
same issue..
`npm install hexo --save --no-optional` not works

**Comment by hkongm** [comment]
@Xuanwo  真的不行哦

```
[Error: Module version mismatch. Expected 46, got 48.]
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
FATAL Cannot find module '/Users/caichao/Code/git/blog/node_modules/hexo-generator-feed'
Error: Cannot find module '/Users/caichao/Code/git/blog/node_modules/hexo-generator-feed'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.require.resolve (internal/module.js:16:19)
    at /Users/caichao/Code/git/blog/node_modules/hexo/lib/hexo/load_plugins.js:52:24
    at tryCatcher (/Users/caichao/Code/git/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/Users/caichao/Code/git/blog/node_modules/hexo/node_modules/bluebird/js/release/map.js:57:38)
    at MappingPromiseArray.PromiseArray._iterate (/Users/caichao/Code/git/blog/node_modules/hexo/node_modules/bluebird/js/release/promise_array.js:113:31)
    at MappingPromiseArray.init (/Users/caichao/Code/git/blog/node_modules/hexo/node_modules/bluebird/js/release/promise_array.js:77:10)
    at new MappingPromiseArray (/Users/caichao/Code/git/blog/node_modules/hexo/node_modules/bluebird/js/release/map.js:25:10)
    at map (/Users/caichao/Code/git/blog/node_modules/hexo/node_modules/bluebird/js/release/map.js:152:12)
    at Promise.map (/Users/caichao/Code/git/blog/node_modules/hexo/node_modules/bluebird/js/release/map.js:156:12)
    at loadModules (/Users/caichao/Code/git/blog/node_modules/hexo/lib/hexo/load_plugins.js:51:30)
    at module.exports (/Users/caichao/Code/git/blog/node_modules/hexo/lib/hexo/load_plugins.js:12:5)
    at /Users/caichao/Code/git/blog/node_modules/hexo/lib/hexo/index.js:171:32
    at tryCatcher (/Users/caichao/Code/git/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/Users/caichao/Code/git/blog/node_modules/hexo/node_modules/bluebird/js/release/reduce.js:145:18)
    at Object.gotAccum (/Users/caichao/Code/git/blog/node_modules/hexo/node_modules/bluebird/js/release/reduce.js:134:25)
    at Object.tryCatcher (/Users/caichao/Code/git/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/caichao/Code/git/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/Users/caichao/Code/git/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Users/caichao/Code/git/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/caichao/Code/git/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:683:18)
    at Async._drainQueue (/Users/caichao/Code/git/blog/node_modules/hexo/node_modules/bluebird/js/release/async.js:138:16)

```

**Comment by Evlos** [comment]
@Xuanwo 

Before executing `npm install hexo --save --no-optional`:

```
{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
```

After executing `npm install hexo --save --no-optional`:

```
{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
```

**Comment by baiyulong** [comment]
npm install hexo --save --no-optional
