### ISSUE TITLE
when i was trying to deploy on git, i got this issue

### ISSUE THREAD

**Issue by JoshPAT** [hexojs/hexo#1280]
```
INFO  Deploying: git
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: undefined is not a function
    at Object.exports.parse (/Users/JoshPAT/Documents/my_blog/node_modules/hexo-deployer-git/node_modules/swig/lib/parser.js:438:19)
    at parse (/Users/JoshPAT/Documents/my_blog/node_modules/hexo-deployer-git/node_modules/swig/lib/swig.js:354:19)
    at Object.precompile (/Users/JoshPAT/Documents/my_blog/node_modules/hexo-deployer-git/node_modules/swig/lib/swig.js:486:23)
    at Object.compile (/Users/JoshPAT/Documents/my_blog/node_modules/hexo-deployer-git/node_modules/swig/lib/swig.js:606:16)
    at commitMessage (/Users/JoshPAT/Documents/my_blog/node_modules/hexo-deployer-git/lib/deployer.js:95:15)
    at Hexo.module.exports (/Users/JoshPAT/Documents/my_blog/node_modules/hexo-deployer-git/lib/deployer.js:21:17)
    at Hexo.tryCatcher (/Users/JoshPAT/Documents/my_blog/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
    at Hexo.<anonymous> (/Users/JoshPAT/Documents/my_blog/node_modules/hexo/node_modules/bluebird/js/main/method.js:15:34)
    at /Users/JoshPAT/Documents/my_blog/node_modules/hexo/lib/plugins/console/deploy.js:56:28
    at tryCatcher (/Users/JoshPAT/Documents/my_blog/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
    at ReductionPromiseArray._promiseFulfilled (/Users/JoshPAT/Documents/my_blog/node_modules/hexo/node_modules/bluebird/js/main/reduce.js:103:38)
    at ReductionPromiseArray.init [as _init$] (/Users/JoshPAT/Documents/my_blog/node_modules/hexo/node_modules/bluebird/js/main/promise_array.js:92:18)
    at Promise._settlePromiseAt (/Users/JoshPAT/Documents/my_blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:528:21)
    at Promise._settlePromises (/Users/JoshPAT/Documents/my_blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (/Users/JoshPAT/Documents/my_blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:177:16)
    at Async._drainQueues (/Users/JoshPAT/Documents/my_blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:187:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/JoshPAT/Documents/my_blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```
btw, I am using Mac OS 10.9.5...

**Comment by mrshyi** [comment]
Do u have sloved it ? I got the same problem.

**Comment by borisschapira** [comment]
Hi @JoshPAT, you may prefer to report this on https://github.com/hexojs/hexo-deployer-git/issues.

**Comment by Since1990** [comment]
Got the same problem too..

**Comment by leesei** [comment]
This issue was moved to hexojs/hexo-deployer-git#7
