### ISSUE TITLE
Error: template not found: template.html

### ISSUE THREAD

**Issue by kuanyui** [hexojs/hexo#1289]
```sh
[kuanyui@kuanyui-laptop:Blog/kuanyui.github.io]$ hexo --version                                                                                                                     (05-21 06:03)
hexo: 3.1.1
os: Linux 3.11.10-29-desktop linux x64
http_parser: 1.0
node: 0.10.29
v8: 3.14.5.9
ares: 1.9.0-DEV
uv: 0.10.27
zlib: 1.2.3
modules: 11
openssl: 1.0.1h
```

After `'hexo clean;hexo generate;hexo server --debug'`:

```sh
INFO  Deleted database.
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: template not found: template.html
    at null.<anonymous> (/home/kuanyui/Dropbox/Blog/kuanyui.github.io/node_modules/hexo/node_modules/nunjucks/src/environment.js:175:31)
    at next (/home/kuanyui/Dropbox/Blog/kuanyui.github.io/node_modules/hexo/node_modules/nunjucks/src/lib.js:203:13)
    at handle (/home/kuanyui/Dropbox/Blog/kuanyui.github.io/node_modules/hexo/node_modules/nunjucks/src/environment.js:157:25)
    at /home/kuanyui/Dropbox/Blog/kuanyui.github.io/node_modules/hexo/node_modules/nunjucks/src/environment.js:171:21
    at next (/home/kuanyui/Dropbox/Blog/kuanyui.github.io/node_modules/hexo/node_modules/nunjucks/src/lib.js:200:13)
    at Object.exports.asyncIter (/home/kuanyui/Dropbox/Blog/kuanyui.github.io/node_modules/hexo/node_modules/nunjucks/src/lib.js:207:5)
    at Obj.extend.getTemplate (/home/kuanyui/Dropbox/Blog/kuanyui.github.io/node_modules/hexo/node_modules/nunjucks/src/environment.js:150:17)
    at root [as rootRenderFunc] (eval at <anonymous> (/home/kuanyui/Dropbox/Blog/kuanyui.github.io/node_modules/hexo/node_modules/nunjucks/src/environment.js:450:24), <anonymous>:8:5)
    at null.<anonymous> (/home/kuanyui/Dropbox/Blog/kuanyui.github.io/node_modules/hexo/node_modules/nunjucks/src/environment.js:387:18)
    at Object.exports.withPrettyErrors (/home/kuanyui/Dropbox/Blog/kuanyui.github.io/node_modules/hexo/node_modules/nunjucks/src/lib.js:24:16)
    at Obj.extend.render (/home/kuanyui/Dropbox/Blog/kuanyui.github.io/node_modules/hexo/node_modules/nunjucks/src/environment.js:374:20)
    at Obj.extend.renderString (/home/kuanyui/Dropbox/Blog/kuanyui.github.io/node_modules/hexo/node_modules/nunjucks/src/environment.js:261:21)
    at /home/kuanyui/Dropbox/Blog/kuanyui.github.io/node_modules/hexo/lib/extend/tag.js:56:9
    at tryCatcher (/home/kuanyui/Dropbox/Blog/kuanyui.github.io/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._resolveFromResolver (/home/kuanyui/Dropbox/Blog/kuanyui.github.io/node_modules/hexo/node_modules/bluebird/js/main/promise.js:427:31)
    at new Promise (/home/kuanyui/Dropbox/Blog/kuanyui.github.io/node_modules/hexo/node_modules/bluebird/js/main/promise.js:53:37)
    at Tag.render (/home/kuanyui/Dropbox/Blog/kuanyui.github.io/node_modules/hexo/lib/extend/tag.js:55:10)
    at Object.tagFilter [as onRenderEnd] (/home/kuanyui/Dropbox/Blog/kuanyui.github.io/node_modules/hexo/lib/hexo/post.js:253:16)
    at Promise.then.then.then.output (/home/kuanyui/Dropbox/Blog/kuanyui.github.io/node_modules/hexo/lib/hexo/render.js:55:19)
    at tryCatcher (/home/kuanyui/Dropbox/Blog/kuanyui.github.io/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/home/kuanyui/Dropbox/Blog/kuanyui.github.io/node_modules/hexo/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/home/kuanyui/Dropbox/Blog/kuanyui.github.io/node_modules/hexo/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromises (/home/kuanyui/Dropbox/Blog/kuanyui.github.io/node_modules/hexo/node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (/home/kuanyui/Dropbox/Blog/kuanyui.github.io/node_modules/hexo/node_modules/bluebird/js/main/async.js:177:16)
    at Async._drainQueues (/home/kuanyui/Dropbox/Blog/kuanyui.github.io/node_modules/hexo/node_modules/bluebird/js/main/async.js:187:10)
    at Async.drainQueues (/home/kuanyui/Dropbox/Blog/kuanyui.github.io/node_modules/hexo/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickCallback (node.js:419:13)
```

I totally cannot understand why&how on earth does this error occur. I have version-controlled my Hexo repository; therefore, after this error happened, I checked if anything changed wrongly by myself, but cannot find any clue for this strange phenomenon...(Since the last time Hexo run without error, what I've done are modify my articles...)

**Comment by kuanyui** [comment]
Ok great, I found where the problem is: I wrote one line in one my article:

``` markdown
 - Now I know `{% include 'template.html' %}` is also available in Django's template
```

Sh... It's the second time be fool by `markd`. Any way to prevent the problems such as this?

**Comment by leesei** [comment]
Sadly no (at least ATM). Always remember your md will be preprocessed, it is turned into HTML anyway, isn't it?
