### ISSUE TITLE
Spurious errors? Does hexo-tag-asset-res work with 3.1.1?

### ISSUE THREAD

**Issue by Hunter-Github** [hexojs/hexo#1290]
During site generation the following error pops up (generation in fact goes OK, even on an empty newly created site!):

      ERROR Plugin load failed: hexo-tag-asset-res
        ReferenceError: hexo is not defined
            at Object.<anonymous> (blog/node_modules/hexo-tag-asset-res/lib/renderAsset.js:4:13)
            at Object.<anonymous> (blog/node_modules/hexo-tag-asset-res/lib/renderAsset.js:26:4)
            at Module._compile (module.js:460:26)
            at Object.Module._extensions..js (module.js:478:10)
            at Module.load (module.js:355:32)
            at Function.Module._load (module.js:310:12)
            at Module.require (module.js:365:17)
            at require (module.js:384:17)
            at Object.<anonymous> (blog/node_modules/hexo-tag-asset-res/lib/assetImageTag.js:4:17)
            at Object.<anonymous> (blog/node_modules/hexo-tag-asset-res/lib/assetImageTag.js:43:4)
            at Module._compile (module.js:460:26)
            at Object.Module._extensions..js (module.js:478:10)
            at Module.load (module.js:355:32)
            at Function.Module._load (module.js:310:12)
            at Module.require (module.js:365:17)
            at require (module.js:384:17)
            at Object.<anonymous> (blog/node_modules/hexo-tag-asset-res/lib/index.js:2:3)
            at Object.<anonymous> (blog/node_modules/hexo-tag-asset-res/lib/index.js:10:4)
            at Module._compile (module.js:460:26)
            at Object.Module._extensions..js (module.js:478:10)
            at Module.load (module.js:355:32)
            at Function.Module._load (module.js:310:12)
            at Module.require (module.js:365:17)
            at require (blog/node_modules/hexo/lib/hexo/index.js:213:21)
            at blog/node_modules/hexo-tag-asset-res/index.js:1:66
            at blog/node_modules/hexo/lib/hexo/index.js:229:12
            at tryCatcher (blog/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
            at Promise._settlePromiseFromHandler (blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:454:31)
            at Promise._settlePromiseAt (blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:530:18)
            at Promise._settlePromises (blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:646:14)
            at Async._drainQueue (blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:177:16)
            at Async._drainQueues (blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:187:10)
            at Immediate.Async.drainQueues [as _onImmediate] (blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:15:14)
            at processImmediate [as _immediateCallback] (timers.js:358:17)

**Comment by Hunter-Github** [comment]
node version 0.12.0 by the way (am waiting for the merge).

**Comment by Xuanwo** [comment]
Why open this issue in site?

**Comment by Hunter-Github** [comment]
Should we erase the hexo-tag-asset-res from the list of compatible plugins?

**Comment by jerryling315** [comment]
No body's replying

**Comment by rskumar** [comment]
I am getting same error, well because  I am on 3.x.
Is there any alternative to this plugin?

**Comment by jerryling315** [comment]
@rskumar I think you can just choose not to use it. And you can still have img in your blog.

**Comment by timnew** [comment]
`hexo-tag-asset-res` author here.
`hexo-tag-asset-res` is a temporary solution for Hexo 2.x, since then, Hexo doens't support `asset folder` yet.
And @tommy351 is busy on something big (named, Hexo 3 :smile_cat: ), so as a temporary solution, I wrote `hexo-tag-asset-res`.
But I do agree it should be obsoleted now. I gonna remove it from the plugin list.

@Xuanwo  please close this issue
