### ISSUE TITLE
I try to add paginator when pagination != 2, but I meet a error, who can help me?

### ISSUE THREAD

**Issue by Xuanwo** [hexojs/hexo#1318]
My insert like that:
https://github.com/Xuanwo/xuanwo.github.io/commit/86044f61f088e924d7689cf8b63d3694f30f14e5

But I meet an error like this:
```
Unhandled rejection SyntaxError: /home/travis/build/Xuanwo/xuanwo.github.io/themes/alpha/layout/archive.ejs:1
 >> 1| <%- partial('_partial/archive', {pagination: config.archive, index: true}) %>
Unexpected token ) in "/home/travis/build/Xuanwo/xuanwo.github.io/themes/alpha/layout/_partial/archive.ejs"
    at Object.Function (<anonymous>)
    at exports.compile (/home/travis/build/Xuanwo/xuanwo.github.io/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14)
    at Object.exports.render (/home/travis/build/Xuanwo/xuanwo.github.io/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:284:66)
    at Hexo.<anonymous> (/home/travis/build/Xuanwo/xuanwo.github.io/node_modules/hexo-renderer-ejs/index.js:5:14)
    at Render.renderSync (/home/travis/build/Xuanwo/xuanwo.github.io/node_modules/hexo/lib/hexo/render.js:87:23)
    at View.renderSync (/home/travis/build/Xuanwo/xuanwo.github.io/node_modules/hexo/lib/theme/view.js:50:29)
    at Object.partial (/home/travis/build/Xuanwo/xuanwo.github.io/node_modules/hexo/lib/plugins/helper/partial.js:42:19)
    at eval (eval at <anonymous> (/home/travis/build/Xuanwo/xuanwo.github.io/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:29:35)
    at eval (eval at <anonymous> (/home/travis/build/Xuanwo/xuanwo.github.io/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:29:116)
    at /home/travis/build/Xuanwo/xuanwo.github.io/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:255:15
    at Object.exports.render (/home/travis/build/Xuanwo/xuanwo.github.io/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:293:13)
    at Hexo.<anonymous> (/home/travis/build/Xuanwo/xuanwo.github.io/node_modules/hexo-renderer-ejs/index.js:5:14)
    at Hexo.tryCatcher (/home/travis/build/Xuanwo/xuanwo.github.io/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
    at Hexo.<anonymous> (/home/travis/build/Xuanwo/xuanwo.github.io/node_modules/hexo/node_modules/bluebird/js/main/method.js:15:34)
    at /home/travis/build/Xuanwo/xuanwo.github.io/node_modules/hexo/lib/hexo/render.js:51:21
    at tryCatcher (/home/travis/build/Xuanwo/xuanwo.github.io/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/home/travis/build/Xuanwo/xuanwo.github.io/node_modules/hexo/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/home/travis/build/Xuanwo/xuanwo.github.io/node_modules/hexo/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromiseAtPostResolution (/home/travis/build/Xuanwo/xuanwo.github.io/node_modules/hexo/node_modules/bluebird/js/main/promise.js:224:10)
    at Async._drainQueue (/home/travis/build/Xuanwo/xuanwo.github.io/node_modules/hexo/node_modules/bluebird/js/main/async.js:182:12)
    at Async._drainQueues (/home/travis/build/Xuanwo/xuanwo.github.io/node_modules/hexo/node_modules/bluebird/js/main/async.js:187:10)
    at Async.drainQueues (/home/travis/build/Xuanwo/xuanwo.github.io/node_modules/hexo/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickCallback (node.js:448:13)
```

So, - -, why?
Any help will be helpful.

This problem must be stupid, because I know nothing about js = =

**Comment by Johnwhite-leaf** [comment]
It seems you miss <% } %> before <div class="archive">  in themes/alpha/layout/_partial/archive.ejs
hope this can help you.

**Comment by Xuanwo** [comment]
@Johnwhite-leaf  It's right, thank you~
