### ISSUE TITLE
hexo-cli -g on windows installs or loads from the wrong directory

### ISSUE THREAD

**Issue by jorgt** [hexojs/hexo#1353]
Take these commands in my windows shell. It seems like hexo-cli is trying to load something out of the wrong folder. Unlike mocha (an example, see last command), it tries to load `hexo` module from the `Roaming` folder, but that's not where hexo-cli was installed. 

Any ideas?

```bash

thuijls@DOXIE-PC ~/node
$ npm install hexo-cli -g
npm WARN optional dep failed, continuing fsevents@0.3.6
c:\Program Files\nodejs\hexo -> c:\Program Files\nodejs\node_modules\hexo-cli\bin\hexo
hexo-cli@0.1.7 c:\Program Files\nodejs\node_modules\hexo-cli
├── abbrev@1.0.7
├── minimist@1.1.1
├── bluebird@2.9.30
├── tildify@1.1.0 (os-homedir@1.0.0)
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
└── hexo-fs@0.1.3 (escape-string-regexp@1.0.3, graceful-fs@3.0.8, chokidar@0.12.6)

thuijls@DOXIE-PC ~/node
$ npm list -g --depth=0
c:\Program Files\nodejs
├── hexo-cli@0.1.7
├── mocha@2.2.5
├── node@0.0.0
├── node-sass@3.2.0
├── npm@2.10.1
├── phonegap@5.0.0-0.28.1
├── spawn-sync@1.0.11
└── yo@1.4.7

thuijls@DOXIE-PC ~/node
$ hexo --version
module.js:338
    throw err;
          ^
Error: Cannot find module 'c:\Users\thuijls\AppData\Roaming\npm\node_modules\hexo-cli\bin\hexo'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

thuijls@DOXIE-PC ~/node
$ mocha --version
2.2.5
```

**Comment by jorgt** [comment]
I copied hexo-cli to roaming myself, then it worked.
