### ISSUE TITLE
Posts Generating problem at hexo 2.x to 3.1.1 Migrataion 

### ISSUE THREAD

**Issue by aungthurhahein** [hexojs/hexo#1371]
I tried to migrate from hexo 2x to 3.1.1 by following the guideline. Instead of working on my current blog folder, I initiate a new blog and copy theme and md files from _posts. The problem occurs when I tried  "$hexo generate". Am I missing something to update a plugin or else? 

```
Error: Object  has no method 'trim'
    at NunjucksBlock.NunjucksTag._parseArgs (/media/atrx/DATA/10.DropBoxSync/Dropbox/blog/atrx3/node_modules/hexo/lib/extend/tag.js:84:67)
    at NunjucksBlock.parse (/media/atrx/DATA/10.DropBoxSync/Dropbox/blog/atrx3/node_modules/hexo/lib/extend/tag.js:104:19)
    at Object.extend.parseStatement (/media/atrx/DATA/10.DropBoxSync/Dropbox/blog/atrx3/node_modules/hexo/node_modules/nunjucks/src/parser.js:540:36)
    at Object.extend.parseNodes (/media/atrx/DATA/10.DropBoxSync/Dropbox/blog/atrx3/node_modules/hexo/node_modules/nunjucks/src/parser.js:1151:30)
    at Object.extend.parseAsRoot (/media/atrx/DATA/10.DropBoxSync/Dropbox/blog/atrx3/node_modules/hexo/node_modules/nunjucks/src/parser.js:1177:42)
    at Object.module.exports.parse (/media/atrx/DATA/10.DropBoxSync/Dropbox/blog/atrx3/node_modules/hexo/node_modules/nunjucks/src/parser.js:1199:18)
    at Object.module.exports.compile (/media/atrx/DATA/10.DropBoxSync/Dropbox/blog/atrx3/node_modules/hexo/node_modules/nunjucks/src/compiler.js:1118:48)
    at Obj.extend._compile (/media/atrx/DATA/10.DropBoxSync/Dropbox/blog/atrx3/node_modules/hexo/node_modules/nunjucks/src/environment.js:444:35)
    at Obj.extend.compile (/media/atrx/DATA/10.DropBoxSync/Dropbox/blog/atrx3/node_modules/hexo/node_modules/nunjucks/src/environment.js:433:18)
    at null.<anonymous> (/media/atrx/DATA/10.DropBoxSync/Dropbox/blog/atrx3/node_modules/hexo/node_modules/nunjucks/src/environment.js:378:22)
    at Object.exports.withPrettyErrors (/media/atrx/DATA/10.DropBoxSync/Dropbox/blog/atrx3/node_modules/hexo/node_modules/nunjucks/src/lib.js:24:16)
    at Obj.extend.render (/media/atrx/DATA/10.DropBoxSync/Dropbox/blog/atrx3/node_modules/hexo/node_modules/nunjucks/src/environment.js:374:20)
    at Obj.extend.renderString (/media/atrx/DATA/10.DropBoxSync/Dropbox/blog/atrx3/node_modules/hexo/node_modules/nunjucks/src/environment.js:261:21)
    at /media/atrx/DATA/10.DropBoxSync/Dropbox/blog/atrx3/node_modules/hexo/lib/extend/tag.js:56:9
    at tryCatcher (/media/atrx/DATA/10.DropBoxSync/Dropbox/blog/atrx3/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._resolveFromResolver (/media/atrx/DATA/10.DropBoxSync/Dropbox/blog/atrx3/node_modules/hexo/node_modules/bluebird/js/main/promise.js:462:31)
    at new Promise (/media/atrx/DATA/10.DropBoxSync/Dropbox/blog/atrx3/node_modules/hexo/node_modules/bluebird/js/main/promise.js:69:37)
    at Tag.render (/media/atrx/DATA/10.DropBoxSync/Dropbox/blog/atrx3/node_modules/hexo/lib/extend/tag.js:55:10)
    at Object.tagFilter [as onRenderEnd] (/media/atrx/DATA/10.DropBoxSync/Dropbox/blog/atrx3/node_modules/hexo/lib/hexo/post.js:253:16)
    at Promise.then.then.then.output (/media/atrx/DATA/10.DropBoxSync/Dropbox/blog/atrx3/node_modules/hexo/lib/hexo/render.js:55:19)
    at tryCatcher (/media/atrx/DATA/10.DropBoxSync/Dropbox/blog/atrx3/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/media/atrx/DATA/10.DropBoxSync/Dropbox/blog/atrx3/node_modules/hexo/node_modules/bluebird/js/main/promise.js:489:31)
    at Promise._settlePromiseAt (/media/atrx/DATA/10.DropBoxSync/Dropbox/blog/atrx3/node_modules/hexo/node_modules/bluebird/js/main/promise.js:565:18)
    at Promise._settlePromises (/media/atrx/DATA/10.DropBoxSync/Dropbox/blog/atrx3/node_modules/hexo/node_modules/bluebird/js/main/promise.js:681:14)
    at Async._drainQueue (/media/atrx/DATA/10.DropBoxSync/Dropbox/blog/atrx3/node_modules/hexo/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/media/atrx/DATA/10.DropBoxSync/Dropbox/blog/atrx3/node_modules/hexo/node_modules/bluebird/js/main/async.js:133:10)
    at Async.drainQueues (/media/atrx/DATA/10.DropBoxSync/Dropbox/blog/atrx3/node_modules/hexo/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickCallback (node.js:419:13)
14:36:59.309 DEBUG Database saved

**Comment by Xuanwo** [comment]
use the default theme and try again and we will know witch part cause the problem

**Comment by aungthurhahein** [comment]
@Xuanwo Thanks for your suggestion. I tried with default theme,landscape and the error still resists. It happens when I put existing posts(markdown files) into source and generate.
This is my previous package.json content:
```
{
  "name": "hexo-site",
  "version": "2.6.1",
  "private": true,
  "dependencies": {
    "hexo-admin": "^0.1.3",
    "hexo-deployer-git": "0.0.4",
    "hexo-generator-archive": "^0.1.3",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.1.3",
    "hexo-generator-tag": "^0.1.2",
    "hexo-renderer-ejs": "*",
    "hexo-renderer-jade": "^0.1.0",
    "hexo-renderer-less": "^0.1.2",
    "hexo-renderer-marked": "*",
    "hexo-renderer-stylus": "*",
    "hexo-server": "^0.1.2"
  }
}
```

The following content is the new package.json file
```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.1.1"
  },
  "dependencies": {
    "hexo": "^3.1.1",
    "hexo-generator-archive": "^0.1.2",
    "hexo-generator-category": "^0.1.2",
    "hexo-generator-feed": "^1.0.2",
    "hexo-generator-index": "^0.1.2",
    "hexo-generator-sitemap": "^1.0.1",
    "hexo-generator-tag": "^0.1.2",
    "hexo-renderer-ejs": "^0.1.0",
    "hexo-renderer-haml": "^0.1.0",
    "hexo-renderer-jade": "^0.1.0",
    "hexo-renderer-marked": "^0.2.5",
    "hexo-renderer-stylus": "^0.2.3",
    "hexo-server": "^0.1.2"
  }
}

Is there any plugins I need to update to fix that error?

**Comment by Xuanwo** [comment]
can you paste one of your markdown?
maybe the way you use tag made the error

**Comment by aungthurhahein** [comment]
I use tags in 2 different way and it seems ok with hexo 2.x. 
```
==> VIM-as-IDE.md <==
title: 'VIM as IDE'
date: 2015-02-27 20:03:34
tags:
 - Personal
 - Programming
---
```

```
==> terminal-in-browser-with-butterfly-.md <==
title: Terminal in browser with Butterfly 
date: 2014-03-01 21:30:26
tags: Linux
---
