### ISSUE TITLE
Escaping {{ ?

### ISSUE THREAD

**Issue by rrshaban** [hexojs/hexo#1372]
I tried to write `{{ now('YYYY-MM-DD HH:mm:ss') }}` in a post and the server stopped refreshing with the following message: 

```
Unhandled rejection Template render error: Error: Unable to call `now`, which is undefined or falsey
    at Object.callWrap (/Users/razi/git/node/node_modules/hexo/node_modules/nunjucks/src/runtime.js:223:15)
    at root [as rootRenderFunc] (eval at <anonymous> (/Users/razi/git/node/node_modules/hexo/node_modules/nunjucks/src/environment.js:450:24), <anonymous>:8:67)
    at null.<anonymous> (/Users/razi/git/node/node_modules/hexo/node_modules/nunjucks/src/environment.js:387:18)
    at Object.exports.withPrettyErrors (/Users/razi/git/node/node_modules/hexo/node_modules/nunjucks/src/lib.js:24:16)
    at Obj.extend.render (/Users/razi/git/node/node_modules/hexo/node_modules/nunjucks/src/environment.js:374:20)
    at Obj.extend.renderString (/Users/razi/git/node/node_modules/hexo/node_modules/nunjucks/src/environment.js:261:21)
    at /Users/razi/git/node/node_modules/hexo/lib/extend/tag.js:56:9
    at tryCatcher (/Users/razi/git/node/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._resolveFromResolver (/Users/razi/git/node/node_modules/hexo/node_modules/bluebird/js/main/promise.js:462:31)
    at new Promise (/Users/razi/git/node/node_modules/hexo/node_modules/bluebird/js/main/promise.js:69:37)
    at Tag.render (/Users/razi/git/node/node_modules/hexo/lib/extend/tag.js:55:10)
    at Object.tagFilter [as onRenderEnd] (/Users/razi/git/node/node_modules/hexo/lib/hexo/post.js:253:16)
    at /Users/razi/git/node/node_modules/hexo/lib/hexo/render.js:55:19
    at tryCatcher (/Users/razi/git/node/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/Users/razi/git/node/node_modules/hexo/node_modules/bluebird/js/main/promise.js:489:31)
    at Promise._settlePromiseAt (/Users/razi/git/node/node_modules/hexo/node_modules/bluebird/js/main/promise.js:565:18)
    at Promise._settlePromises (/Users/razi/git/node/node_modules/hexo/node_modules/bluebird/js/main/promise.js:681:14)
    at Async._drainQueue (/Users/razi/git/node/node_modules/hexo/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/razi/git/node/node_modules/hexo/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/razi/git/node/node_modules/hexo/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```
The workaround I've found is using `{% raw %}{{ now('YYYY-MM-DD HH:mm:ss') }}{% endraw %}`, though I feel like I should be able to just escape the brackets `\{\{`.

**Comment by leesei** [comment]
You can use this in HTML
```html
&lbrace;&lbrace; code &rbrace;&rbrace;
```
or <code>```</code>
<pre>
```
{{ code }}
```
</pre>

But `\{\{` won't work, that's swig's issue.
Please close this issue.

**Comment by rrshaban** [comment]
Thanks for the tips!
