### ISSUE TITLE
hexo g error

### ISSUE THREAD

**Issue by victoryxs** [hexojs/hexo#1397]
error code is as following:
```
SyntaxError: Unexpected token ILLEGAL
    at Function (native)
    at Obj.extend._compile (/Users/victory/Documents/victoryxs.github.io/node_modules/hexo/node_modules/nunjucks/src/environment.js:450:24)
    at Obj.extend.compile (/Users/victory/Documents/victoryxs.github.io/node_modules/hexo/node_modules/nunjucks/src/environment.js:433:18)
    at null.<anonymous> (/Users/victory/Documents/victoryxs.github.io/node_modules/hexo/node_modules/nunjucks/src/environment.js:378:22)
    at Object.exports.withPrettyErrors (/Users/victory/Documents/victoryxs.github.io/node_modules/hexo/node_modules/nunjucks/src/lib.js:24:16)
    at Obj.extend.render (/Users/victory/Documents/victoryxs.github.io/node_modules/hexo/node_modules/nunjucks/src/environment.js:374:20)
    at Obj.extend.renderString (/Users/victory/Documents/victoryxs.github.io/node_modules/hexo/node_modules/nunjucks/src/environment.js:261:21)
    at /Users/victory/Documents/victoryxs.github.io/node_modules/hexo/lib/extend/tag.js:56:9
    at tryCatcher (/Users/victory/Documents/victoryxs.github.io/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._resolveFromResolver (/Users/victory/Documents/victoryxs.github.io/node_modules/hexo/node_modules/bluebird/js/main/promise.js:462:31)
    at new Promise (/Users/victory/Documents/victoryxs.github.io/node_modules/hexo/node_modules/bluebird/js/main/promise.js:69:37)
    at Tag.render (/Users/victory/Documents/victoryxs.github.io/node_modules/hexo/lib/extend/tag.js:55:10)
    at Object.tagFilter [as onRenderEnd] (/Users/victory/Documents/victoryxs.github.io/node_modules/hexo/lib/hexo/post.js:253:16)
    at /Users/victory/Documents/victoryxs.github.io/node_modules/hexo/lib/hexo/render.js:55:19
    at tryCatcher (/Users/victory/Documents/victoryxs.github.io/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/Users/victory/Documents/victoryxs.github.io/node_modules/hexo/node_modules/bluebird/js/main/promise.js:489:31)
    at Promise._settlePromiseAt (/Users/victory/Documents/victoryxs.github.io/node_modules/hexo/node_modules/bluebird/js/main/promise.js:565:18)
    at Promise._settlePromises (/Users/victory/Documents/victoryxs.github.io/node_modules/hexo/node_modules/bluebird/js/main/promise.js:681:14)
    at Async._drainQueue (/Users/victory/Documents/victoryxs.github.io/node_modules/hexo/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/victory/Documents/victoryxs.github.io/node_modules/hexo/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/victory/Documents/victoryxs.github.io/node_modules/hexo/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```

**Comment by victoryxs** [comment]
I have found the mistake. The format of markdown file is incorrect

**Comment by wendzhue** [comment]
@victoryxs I come across with the same error after I create two new posts as you did. Can you explain this issue in detail? Thanks.

**Comment by victoryxs** [comment]
when i post a new blog，i found this mistake. After
i check all, i copied the blog but didn't concern about the format of markdown, especially the newline format.Wish to help you.

**Comment by zgpeace** [comment]
Thx. It works for me. 
My markdown formate isn't suit for hexo.

**Comment by LionelCursor** [comment]
I have the same issue.

I don't know which document make it goes wrong.

So how can I solve it?
