### ISSUE TITLE
 当文章中出现{{ 符号时无法生成网页

### ISSUE THREAD

**Issue by Tomyail** [hexojs/hexo#1439]
如果内容中包含`{{`，运行generate命令会报如下错误：
```  
Template render error: unexpected token: <
    at Error.exports.TemplateError (/Users/lixuexin/blog/node_modules/hexo/node_modules/nunjucks/src/lib.js:51:19)
    at Object.extend.fail (/Users/lixuexin/blog/node_modules/hexo/node_modules/nunjucks/src/parser.js:64:15)
    at Object.extend.parsePrimary (/Users/lixuexin/blog/node_modules/hexo/node_modules/nunjucks/src/parser.js:947:18)
    at Object.extend.parseUnary (/Users/lixuexin/blog/node_modules/hexo/node_modules/nunjucks/src/parser.js:882:25)
    at Object.extend.parsePow (/Users/lixuexin/blog/node_modules/hexo/node_modules/nunjucks/src/parser.js:856:25)
    at Object.extend.parseMod (/Users/lixuexin/blog/node_modules/hexo/node_modules/nunjucks/src/parser.js:844:25)
    at Object.extend.parseFloorDiv (/Users/lixuexin/blog/node_modules/hexo/node_modules/nunjucks/src/parser.js:832:25)
    at Object.extend.parseDiv
```

**Comment by Xuanwo** [comment]
建议在两个{{之间加一个空格之类的或者使用html转义符
