### ISSUE TITLE
Deploy error!

### ISSUE THREAD

**Issue by Gracker** [hexojs/hexo#1445]
When i excute hexo deploy,I got this error:
```
remote: fatal: early EOF        
error: RPC failed; result=55, HTTP code = 200
error: unpack failed: index-pack abnormal exit
Everything up-to-date
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: remote: fatal: early EOF        
error: RPC failed; result=55, HTTP code = 200
error: unpack failed: index-pack abnormal exit
Everything up-to-date

    at ChildProcess.<anonymous> (/Users/gaojack/blog/node_modules/hexo-deployer-git/node_modules/hexo-util/lib/spawn.js:42:17)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:753:16)
    at Socket.<anonymous> (child_process.js:966:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
```

**Comment by Xuanwo** [comment]
`remote: fatal: early EOF  `

check your network, if you are update GFW, please use vpn or ss

**Comment by Xuanwo** [comment]
Any update?

**Comment by akmadsen** [comment]
I'll second that. GFW was my issue for this.

**Comment by leesei** [comment]
Please open new issue if the problem persists with latest build.
