### ISSUE TITLE
Access hexo helper inside scripts

### ISSUE THREAD

**Issue by angelathewebdev** [hexojs/hexo#1462]
I would like to access the internationalisation and url helper from my `script` file. Currently, I'm getting an error that says the function is not defined.

```
Unhandled rejection ReferenceError: /private/var/www/developer-docs/themes/docset/layout/layout.ejs:6
    4|         <%- partial('_partial/header', null, {cache: !config.relative_link}) %>
    5|         <div id="main-wrap">
 >> 6|             <%- partial('_widget/dashboard-nav', null, {cache: !config.relative_link}) %>
    7|             <section id="main">
    8|                 <%- body %>
    9|                 <%- partial('_partial/footer', null, {cache: !config.relative_link}) %>

/private/var/www/developer-docs/themes/docset/layout/_widget/dashboard-nav.ejs:3
    1| <aside id="sidebar">
    2|     <nav class="side-nav">
 >> 3|         <%- side_menu(theme.doc_menu) %>
    4|     </nav>
    5| </aside>

__ is not defined
```

this is the content of `scripts.js`

```
(function() {
    'use strict';

    var util = require('hexo-util');

    var buildMenu = function(isTop, menus) {
        var title;
        var result = '<ul class="' + (isTop ? 'top' : 'sub') + '-nav">';

        result += menus.map(function(menu) {
            if(typeof menu == 'string') {
                title = __('doc_menu.' + menu);
                return '<li><a href="' + url_for(util.slugize(title)) + '">' + title + '</a></li>'
            } else if(Object.prototype.toString.call(menu).indexOf('Array') > -1) {
                return buildMenu(false, menu);
            }
        });

        return result + '</ul>';
    };


    hexo.extend.helper.register('slugize', util.slugize);
    hexo.extend.helper.register('side_menu', buildMenu.bind(null, true));
})();
```

**Comment by angelathewebdev** [comment]
I tried to see if `hexo` variable has a global `helper` property, but it gives me back undefined.
Then, I tried to see if I can include the helper files inside the hexo package directly, but it seems like a naming conflict prevented this (the file uses `config` to look up the property, whereas inside the theme, only `site` is available).
So my temporary solution is to place the code inside the template file so it has direct access to the helpers. This is definitely not the best practice, nor would I do this unless its a last resort.

**Comment by angelathewebdev** [comment]
It seems like I've jumped to conclusion and thought the issue was temporary resolved. After restarting the hexo server, I'm getting the error message that 

`slugize is not defined`

Here is the code for rendering the menu

```
<aside id="sidebar">
    <nav class="side-nav">
        <%
            var buildMenu = function(isTop, menus) {
                var title;
                var result = '<ul class="' + (isTop ? 'top' : 'sub') + '-nav">';
                var current_title = page.title;

                result += menus.map(function(menu) {
                    if(typeof menu == 'string') {
                        title = __('doc_menu.' + menu);
                        return '<li class="' + current_title == title ? 'current' : '' + '"><a href="' + url_for(slugize(title)) + '">' + title + '</a></li>';
                    } else if(Object.prototype.toString.call(menu).indexOf('Array') > -1) {
                        title = __('doc_menu.' + menu[0]);
                        return '<li class="' + current_title == title ? 'current' : '' + '"><a href="' + url_for(slugize(title)) + '">' + title + '</a>' + buildMenu(false, menu.slice(1)) + '</li>';
                    }
                }).join('');

                return result + '</ul>';
            };
        %>
        <%- buildMenu(true, theme.doc_menu) %>
    </nav>
</aside>
```

and complete error stack is as follows

```
slugize is not defined
    at eval (eval at <anonymous> (/private/var/www/developer-docs/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:43:188)
    at Array.map (native)
    at buildMenu (eval at <anonymous> (/private/var/www/developer-docs/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:36:33)
    at eval (eval at <anonymous> (/private/var/www/developer-docs/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:49:55)
    at eval (eval at <anonymous> (/private/var/www/developer-docs/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:49:119)
    at /private/var/www/developer-docs/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:255:15
    at Object.exports.render (/private/var/www/developer-docs/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:293:13)
    at Hexo.<anonymous> (/private/var/www/developer-docs/node_modules/hexo-renderer-ejs/index.js:5:14)
    at Render.renderSync (/private/var/www/developer-docs/node_modules/hexo/lib/hexo/render.js:87:23)
    at View.renderSync (/private/var/www/developer-docs/node_modules/hexo/lib/theme/view.js:50:29)
    at Object.partial (/private/var/www/developer-docs/node_modules/hexo/lib/plugins/helper/partial.js:42:19)
    at eval (eval at <anonymous> (/private/var/www/developer-docs/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:275)
    at eval (eval at <anonymous> (/private/var/www/developer-docs/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:588)
    at /private/var/www/developer-docs/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:255:15
    at Object.exports.render (/private/var/www/developer-docs/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:293:13)
    at Hexo.<anonymous> (/private/var/www/developer-docs/node_modules/hexo-renderer-ejs/index.js:5:14)
    at Hexo.tryCatcher (/private/var/www/developer-docs/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at Hexo.<anonymous> (/private/var/www/developer-docs/node_modules/hexo/node_modules/bluebird/js/main/method.js:15:34)
    at /private/var/www/developer-docs/node_modules/hexo/lib/hexo/render.js:51:21
    at tryCatcher (/private/var/www/developer-docs/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/private/var/www/developer-docs/node_modules/hexo/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/private/var/www/developer-docs/node_modules/hexo/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromiseAtPostResolution (/private/var/www/developer-docs/node_modules/hexo/node_modules/bluebird/js/main/promise.js:244:10)
    at Async._drainQueue (/private/var/www/developer-docs/node_modules/hexo/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/private/var/www/developer-docs/node_modules/hexo/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/private/var/www/developer-docs/node_modules/hexo/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

**Comment by f213** [comment]
According to [helper.js](https://github.com/hexojs/hexo/blob/master/lib/extend/helper.js#L19), all helpers are stored in `hexo.extend.helper.store` array. May be you can call your helpers from there.

**Comment by Ziflin** [comment]
I wasn't able to get the value from the `hexo.extend.helper.store` to work. When I called `url_for( path )` it caused an error: Cannot read property 'config' of undefined ... as urlForHelper.
So what is the proper way to use helpers from other script files?

**Comment by chao1995** [comment]
@Ziflin 

> Cannot read property 'config' of undefined

If you look at `url_for.js`, there is a line `var config = this.config;` where `this` is referring to the global context where the global variable `config` is defined.

So basically instead using `hexo.extend.helper.store['url_for'](path)`, you need to 
* grab a reference to the global context using `var globalContext = this` when this is still referring to the global context. Using the script I am working on as an example to show where to place the line,
```javascript
function hierarchicalCategoryListHelper(...) {
    var globalContext = this; // you can start using globalContext below
}

hexo.extend.helper.register('hierarchicalCategoryList', function() {
    return hierarchicalCategoryListHelper(...);
});
```
* Then you can use `hexo.extend.helper.store['url_for'].call(globalContext, path)`, there should be no error.
