### ISSUE TITLE
升级到3.1.1报错

### ISSUE THREAD

**Issue by kingwrcy** [hexojs/hexo#1470]
已按照wiki的2.x升级3.x的方案全部做过一遍,执行任何命令都是找不到cuid

但是我在node_modules下看到是有cuid包的

ERROR Error: Cannot find module 'cuid'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/JerryWang/github/kingwrcy.github.io/node_modules/hexo/node_modules/warehouse/lib/types/cuid.js:5:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/JerryWang/github/kingwrcy.github.io/node_modules/hexo/node_modules/warehouse/lib/types/index.js:9:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/JerryWang/github/kingwrcy.github.io/node_modules/hexo/node_modules/warehouse/lib/schema.js:4:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
Unhandled rejection TypeError: Cannot read property 'then' of undefined
    at /usr/local/lib/node_modules/hexo-cli/lib/index.js:82:21
    at tryCatcher (/usr/local/lib/node_modules/hexo-cli/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/hexo-cli/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/hexo-cli/node_modules/bluebird/js/main/promise.js:577:18)
    at Async._drainQueue (/usr/local/lib/node_modules/hexo-cli/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/usr/local/lib/node_modules/hexo-cli/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/hexo-cli/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)

**Comment by cikichen** [comment]
我之前一直正常的，今天不知道怎么回事，运行一次`npm update`后，也报这个错误了

**Comment by kyangc** [comment]
+1

**Comment by tedlz123** [comment]
+1

**Comment by kingwrcy** [comment]
cuid包的问题,见[这里](https://github.com/ericelliott/cuid/issues/42)

1.rm -rf node_modules/guid
2.replace package.json cuid version from 1.3.0 to 1.2.4
3.npm install

**Comment by tommy351** [comment]
I have specify the cuid version in warehouse. This problem should be fixed now.
https://github.com/tommy351/warehouse/commit/2f9f07cacb6483d3c3594df5234f3851d3c31456

**Comment by tedlz123** [comment]
Using the npm source from Taobao (http://npm.taobao.org/) to install Hexo can solve this problem.
