### ISSUE TITLE
How to write html pages with hexo?

### ISSUE THREAD

**Issue by billryan** [hexojs/hexo#148]
Most of the time I use markdown as the default format and it works fine, but sometimes html files could be more powerful for specific purpose.  
When I try to create a html file under `source/819` folders and run `hexo generate`, it prompts the following errors.

```
Loading.

/usr/lib/node_modules/hexo/lib/plugins/processor/index.js:189
          if (err) throw new Error('Markdown render error: ' + source);
                         ^
Error: Markdown render error: /home/billryan/Dropbox/Documents/billryan.tk/source/819/index.html
    at /usr/lib/node_modules/hexo/lib/plugins/processor/index.js:189:26
    at Object.store.renderer.(anonymous function) [as html] (/usr/lib/node_modules/hexo/lib/extend.js:40:11)
    at /usr/lib/node_modules/hexo/lib/render.js:63:22
    at /usr/lib/node_modules/hexo/node_modules/async/lib/async.js:542:21
    at /usr/lib/node_modules/hexo/node_modules/async/lib/async.js:222:13
    at iterate (/usr/lib/node_modules/hexo/node_modules/async/lib/async.js:123:13)
    at process._tickCallback (node.js:415:13)
```

I wonder if Hexo can avoid rendering html files which are created by users themselves?
Thank you.

**Comment by alexblack** [comment]
DId you figure out a way to do this? Thanks!

**Comment by billryan** [comment]
@alexblack Try to add
```
layout: false
---
```
in the top of html files.
