### ISSUE TITLE
Install error on Mac

### ISSUE THREAD

**Issue by Jiezhi** [hexojs/hexo#1483]
OS X 10.10.5 with node(v0.12.7) and npm(v2.12.1) installed.

When I executed this cmd:
```shell
npm install -g hexo-cli
```

I got this:
```shell
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "hexo-cli" "-g"
npm ERR! node v0.12.7
npm ERR! npm  v2.12.1
npm ERR! path /usr/local/lib/node_modules/hexo-cli/.gitmodules
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, unlink '/usr/local/lib/node_modules/hexo-cli/.gitmodules'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, unlink '/usr/local/lib/node_modules/hexo-cli/.gitmodules']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/hexo-cli/.gitmodules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! error rolling back Error: EACCES, unlink '/usr/local/lib/node_modules/hexo-cli/.gitmodules'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EACCES, unlink '/usr/local/lib/node_modules/hexo-cli/.gitmodules']
npm ERR! error rolling back   errno: -13,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/hexo-cli/.gitmodules' }

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/npm-debug.log
```

below is the log file content:
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', 'hexo-cli', '-g' ]
2 info using npm@2.12.1
3 info using node@v0.12.7
4 verbose node symlink /usr/local/bin/node
5 verbose install initial load of /usr/local/lib/package.json
6 verbose readDependencies loading dependencies from /usr/local/lib/package.json
7 silly cache add args [ 'hexo-cli', null ]
8 verbose cache add spec hexo-cli
9 silly cache add parsed spec { raw: 'hexo-cli',
9 silly cache add   scope: null,
9 silly cache add   name: 'hexo-cli',
9 silly cache add   rawSpec: '',
9 silly cache add   spec: '*',
9 silly cache add   type: 'range' }
10 silly addNamed hexo-cli@*
11 verbose addNamed "*" is a valid semver range for hexo-cli
12 silly addNameRange { name: 'hexo-cli', range: '*', hasData: false }
13 silly mapToRegistry name hexo-cli
14 silly mapToRegistry using default registry
15 silly mapToRegistry registry https://registry.npmjs.org/
16 silly mapToRegistry uri https://registry.npmjs.org/hexo-cli
17 verbose addNameRange registry:https://registry.npmjs.org/hexo-cli not in flight; fetching
18 verbose request uri https://registry.npmjs.org/hexo-cli
19 verbose request no auth needed
20 info attempt registry request try #1 at 16:45:26
21 verbose request id 8c4f6b93ba84fe56
22 verbose etag "5CGU4M6EJQCMMS56JXQ5DH8CX"
23 http request GET https://registry.npmjs.org/hexo-cli
24 http 304 https://registry.npmjs.org/hexo-cli
25 silly get cb [ 304,
25 silly get   { date: 'Mon, 31 Aug 2015 08:45:26 GMT',
25 silly get     via: '1.1 varnish',
25 silly get     'cache-control': 'max-age=60',
25 silly get     etag: '"5CGU4M6EJQCMMS56JXQ5DH8CX"',
25 silly get     age: '18',
25 silly get     connection: 'keep-alive',
25 silly get     'x-served-by': 'cache-nrt6135-NRT',
25 silly get     'x-cache': 'HIT',
25 silly get     'x-cache-hits': '1',
25 silly get     'x-timer': 'S1441010726.803796,VS0,VE0',
25 silly get     vary: 'Accept' } ]
26 verbose etag https://registry.npmjs.org/hexo-cli from cache
27 verbose get saving hexo-cli to /Users/jiezhi/.npm/registry.npmjs.org/hexo-cli/.cache.json
28 silly addNameRange number 2 { name: 'hexo-cli', range: '*', hasData: true }
29 silly addNameRange versions [ 'hexo-cli',
29 silly addNameRange   [ '0.0.1',
29 silly addNameRange     '0.1.0',
29 silly addNameRange     '0.1.1',
29 silly addNameRange     '0.1.2',
29 silly addNameRange     '0.1.3',
29 silly addNameRange     '0.1.4',
29 silly addNameRange     '0.1.5',
29 silly addNameRange     '0.1.6',
29 silly addNameRange     '0.1.7',
29 silly addNameRange     '0.1.8' ] ]
30 silly addNamed hexo-cli@0.1.8
31 verbose addNamed "0.1.8" is a plain semver version for hexo-cli
32 silly cache afterAdd hexo-cli@0.1.8
33 verbose afterAdd /Users/jiezhi/.npm/hexo-cli/0.1.8/package/package.json not in flight; writing
34 verbose afterAdd /Users/jiezhi/.npm/hexo-cli/0.1.8/package/package.json written
35 silly install resolved [ { name: 'hexo-cli',
35 silly install resolved     version: '0.1.8',
35 silly install resolved     description: 'Command line interface for Hexo',
35 silly install resolved     main: 'lib/index',
35 silly install resolved     bin: { hexo: './bin/hexo' },
35 silly install resolved     scripts: { test: 'gulp test' },
35 silly install resolved     directories: { lib: './lib', bin: './bin' },
35 silly install resolved     engines: { node: '>= 0.10.0' },
35 silly install resolved     repository:
35 silly install resolved      { type: 'git',
35 silly install resolved        url: 'git+https://github.com/hexojs/hexo-cli.git' },
35 silly install resolved     homepage: 'http://hexo.io/',
35 silly install resolved     keywords: [ 'website', 'blog', 'cms', 'framework', 'hexo', 'cli' ],
35 silly install resolved     author:
35 silly install resolved      { name: 'Tommy Chen',
35 silly install resolved        email: 'tommy351@gmail.com',
35 silly install resolved        url: 'http://zespia.tw' },
35 silly install resolved     license: 'MIT',
35 silly install resolved     dependencies:
35 silly install resolved      { abbrev: '^1.0.5',
35 silly install resolved        bluebird: '^2.9.8',
35 silly install resolved        chalk: '^1.0.0',
35 silly install resolved        'hexo-fs': '^0.1.3',
35 silly install resolved        minimist: '^1.1.0',
35 silly install resolved        tildify: '^1.0.0' },
35 silly install resolved     devDependencies:
35 silly install resolved      { chai: '^1.9.1',
35 silly install resolved        coveralls: '^2.11.2',
35 silly install resolved        del: '^1.1.1',
35 silly install resolved        gulp: '^3.8.9',
35 silly install resolved        'gulp-istanbul': '^0.5.0',
35 silly install resolved        'gulp-jshint': '^1.8.6',
35 silly install resolved        'gulp-load-plugins': '^0.8.0',
35 silly install resolved        'gulp-mocha': '^2.0.0',
35 silly install resolved        'hexo-renderer-marked': '^0.2.3',
35 silly install resolved        'jshint-stylish': '^1.0.0',
35 silly install resolved        mocha: '^2.0.1',
35 silly install resolved        sinon: '^1.12.2' },
35 silly install resolved     gitHead: 'bccf86eba1831cf683c37ed78df88198f993f985',
35 silly install resolved     bugs: { url: 'https://github.com/hexojs/hexo-cli/issues' },
35 silly install resolved     _id: 'hexo-cli@0.1.8',
35 silly install resolved     _shasum: '17dcb7301f82f75568bb9125b2f79b2aca4b07b8',
35 silly install resolved     _from: 'hexo-cli@*',
35 silly install resolved     _npmVersion: '3.1.2',
35 silly install resolved     _nodeVersion: '0.12.7',
35 silly install resolved     _npmUser: { name: 'tommy351', email: 'tommy351@gmail.com' },
35 silly install resolved     maintainers: [ [Object] ],
35 silly install resolved     dist:
35 silly install resolved      { shasum: '17dcb7301f82f75568bb9125b2f79b2aca4b07b8',
35 silly install resolved        tarball: 'http://registry.npmjs.org/hexo-cli/-/hexo-cli-0.1.8.tgz' },
35 silly install resolved     _resolved: 'https://registry.npmjs.org/hexo-cli/-/hexo-cli-0.1.8.tgz',
35 silly install resolved     readme: 'ERROR: No README data found!' } ]
36 info install hexo-cli@0.1.8 into /usr/local/lib
37 info installOne hexo-cli@0.1.8
38 verbose installOne of hexo-cli to /usr/local/lib not in flight; installing
39 verbose lock using /Users/jiezhi/.npm/_locks/hexo-cli-d89d95637eeaa0d8.lock for /usr/local/lib/node_modules/hexo-cli
40 silly install write writing hexo-cli 0.1.8 to /usr/local/lib/node_modules/hexo-cli
41 verbose unbuild lib/node_modules/hexo-cli
42 info preuninstall hexo-cli@0.1.8
43 info uninstall hexo-cli@0.1.8
44 verbose unbuild rmStuff hexo-cli@0.1.8 from /usr/local/lib/node_modules
45 silly gentlyRm /usr/local/bin/hexo is being gently removed
46 silly gentlyRm verifying /usr/local is an npm working directory
47 silly gentlyRm containing path /usr/local is under npm's control, in /usr/local
48 silly gentlyRm deletion target /usr/local/bin/hexo is under /usr/local
49 verbose gentlyRm vacuuming from /usr/local/bin/hexo up to /usr/local
50 silly vacuum-fs removing /usr/local/bin/hexo
51 silly vacuum-fs quitting because other entries in /usr/local/bin
52 info postuninstall hexo-cli@0.1.8
53 silly gentlyRm /usr/local/lib/node_modules/hexo-cli is being purged from base /usr/local
54 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/hexo-cli
55 silly vacuum-fs purging /usr/local/lib/node_modules/hexo-cli
56 verbose unlock done using /Users/jiezhi/.npm/_locks/hexo-cli-d89d95637eeaa0d8.lock for /usr/local/lib/node_modules/hexo-cli
57 verbose stack Error: EACCES, unlink '/usr/local/lib/node_modules/hexo-cli/.gitmodules'
57 verbose stack     at Error (native)
58 verbose cwd /usr/local
59 error Darwin 14.5.0
60 error argv "node" "/usr/local/bin/npm" "install" "hexo-cli" "-g"
61 error node v0.12.7
62 error npm  v2.12.1
63 error path /usr/local/lib/node_modules/hexo-cli/.gitmodules
64 error code EACCES
65 error errno -13
66 error Error: EACCES, unlink '/usr/local/lib/node_modules/hexo-cli/.gitmodules'
66 error     at Error (native)
66 error  { [Error: EACCES, unlink '/usr/local/lib/node_modules/hexo-cli/.gitmodules']
66 error   errno: -13,
66 error   code: 'EACCES',
66 error   path: '/usr/local/lib/node_modules/hexo-cli/.gitmodules' }
67 error Please try running this command again as root/Administrator.
68 verbose exit [ -13, true ]
69 verbose unbuild lib/node_modules/hexo-cli
70 info preuninstall hexo-cli@0.1.8
71 info uninstall hexo-cli@0.1.8
72 verbose unbuild rmStuff hexo-cli@0.1.8 from /usr/local/lib/node_modules
73 silly gentlyRm /usr/local/bin/hexo is being gently removed
74 silly gentlyRm verifying /usr/local is an npm working directory
75 silly gentlyRm containing path /usr/local is under npm's control, in /usr/local
76 silly gentlyRm deletion target /usr/local/bin/hexo is under /usr/local
77 verbose gentlyRm vacuuming from /usr/local/bin/hexo up to /usr/local
78 info postuninstall hexo-cli@0.1.8
79 silly gentlyRm /usr/local/lib/node_modules/hexo-cli is being purged from base /usr/local
80 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/hexo-cli
81 silly vacuum-fs purging /usr/local/lib/node_modules/hexo-cli
82 error error rolling back Error: EACCES, unlink '/usr/local/lib/node_modules/hexo-cli/.gitmodules'
82 error error rolling back     at Error (native)
82 error error rolling back  { [Error: EACCES, unlink '/usr/local/lib/node_modules/hexo-cli/.gitmodules']
82 error error rolling back   errno: -13,
82 error error rolling back   code: 'EACCES',
82 error error rolling back   path: '/usr/local/lib/node_modules/hexo-cli/.gitmodules' }
```

**Comment by bestalign** [comment]
try to install with sudo

**Comment by Jiezhi** [comment]
when i install hexo with sudo, still show errors:
``` shell
> fsevents@0.3.8 install /usr/local/lib/node_modules/hexo-cli/node_modules/hexo-fs/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

gyp: /Users/jiezhi/.node-gyp/0.12.7/common.gypi not found (cwd: /usr/local/lib/node_modules/hexo-cli/node_modules/hexo-fs/node_modules/chokidar/node_modules/fsevents) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/hexo-cli/node_modules/hexo-fs/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm WARN optional dep failed, continuing fsevents@0.3.8
/usr/local/bin/hexo -> /usr/local/lib/node_modules/hexo-cli/bin/hexo
hexo-cli@0.1.8 /usr/local/lib/node_modules/hexo-cli
├── abbrev@1.0.7
├── minimist@1.2.0
├── bluebird@2.9.34
├── tildify@1.1.0 (os-homedir@1.0.1)
├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, has-ansi@2.0.0, strip-ansi@3.0.0)
└── hexo-fs@0.1.4 (escape-string-regexp@1.0.3, graceful-fs@4.1.2, chokidar@1.0.5)

```

any help?

**Comment by Xuanwo** [comment]
try `npm install hexo --no-optional`

**Comment by wangtao0921** [comment]
这个怎么解决

**Comment by zhangyee** [comment]
I resolved it with reinstalling the new version node 4.0 (npm 2.14.2). 

```console
yee-macbookair:node_modules yee$ sudo npm -g install hexo-cli
 
> fsevents@0.3.8 install /usr/local/lib/node_modules/hexo-cli/node_modules/hexo-fs/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

 WARN EACCES user "root" does not have permission to access the dev dir "/Users/yee/.node-gyp/4.0.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/hexo-cli/node_modules/hexo-fs/node_modules/chokidar/node_modules/fsevents/.node-gyp"
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
/usr/local/bin/hexo -> /usr/local/lib/node_modules/hexo-cli/bin/hexo
hexo-cli@0.1.8 /usr/local/lib/node_modules/hexo-cli
├── abbrev@1.0.7
├── minimist@1.2.0
├── bluebird@2.10.0
├── tildify@1.1.0 (os-homedir@1.0.1)
├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, has-ansi@2.0.0, strip-ansi@3.0.0)
└── hexo-fs@0.1.4 (escape-string-regexp@1.0.3, graceful-fs@4.1.2, chokidar@1.0.5)
```

**Comment by hilen** [comment]
try to 
```
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
```

then 
```
sudo npm -g install hexo-cli
```

**Comment by Jiezhi** [comment]
I've resolved too.But I don't know the exactly reason.Maybe just like @zhangyee said upside.

I just tried the [React Native](http://facebook.github.io/react-native/docs/getting-started.html), and follow the cmd:
```bash
vm install node && nvm alias default node
brew install watchman
brew install flow
```
And back to install hexo, it just worked!

**Comment by leesei** [comment]
The original issue is `npm install -g` needs sudo to write to `/usr/local/`.
If you use `nvm`, npm installs global to `~/.nvm/` (check with `npm root -g`).
