### ISSUE TITLE
FTPSync Failed

### ISSUE THREAD

**Issue by yy0c** [hexojs/hexo#1509]
```
Collection complete.

Consolidating
-------------------------------------------------------------
Mkdir:
[]

Rmdir:
[ '/logreport' ]

Add:
[]

Updates:
[]

Remove:
[ '/logreport/no_delete' ]

Consolidation complete.

Committing
-------------------------------------------------------------
Remove failed.
Removals failed.
Commit failed.
Commit complete.
/home/hiro/learning/gitdb/blog_hexo/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/node_modules/async/lib/async.js:43
            if (fn === null) throw new Error("Callback was already called.");
                             ^

Error: Callback was already called.
    at /home/hiro/learning/gitdb/blog_hexo/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/node_modules/async/lib/async.js:43:36
    at /home/hiro/learning/gitdb/blog_hexo/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/node_modules/async/lib/async.js:694:17
    at /home/hiro/learning/gitdb/blog_hexo/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/node_modules/async/lib/async.js:173:37
    at /home/hiro/learning/gitdb/blog_hexo/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/lib/ftpsync.js:277:7
    at /home/hiro/learning/gitdb/blog_hexo/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/node_modules/async/lib/async.js:697:13
    at /home/hiro/learning/gitdb/blog_hexo/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/node_modules/async/lib/async.js:52:16
    at /home/hiro/learning/gitdb/blog_hexo/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/node_modules/async/lib/async.js:267:21
    at /home/hiro/learning/gitdb/blog_hexo/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/node_modules/async/lib/async.js:44:16
    at /home/hiro/learning/gitdb/blog_hexo/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/node_modules/async/lib/async.js:694:17
    at /home/hiro/learning/gitdb/blog_hexo/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/node_modules/async/lib/async.js:173:37
    at /home/hiro/learning/gitdb/blog_hexo/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/lib/ftpsync.js:252:13
    at /home/hiro/learning/gitdb/blog_hexo/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/node_modules/async/lib/async.js:52:16
    at /home/hiro/learning/gitdb/blog_hexo/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/node_modules/async/lib/async.js:363:13
    at /home/hiro/learning/gitdb/blog_hexo/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/node_modules/async/lib/async.js:52:16
    at /home/hiro/learning/gitdb/blog_hexo/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/node_modules/async/lib/async.js:325:29
    at /home/hiro/learning/gitdb/blog_hexo/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/node_modules/async/lib/async.js:44:16
    at /home/hiro/learning/gitdb/blog_hexo/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/node_modules/async/lib/async.js:360:17
    at Object.callback (/home/hiro/learning/gitdb/blog_hexo/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/lib/ftpsync.js:491:9)
    at Ftp.parse (/home/hiro/learning/gitdb/blog_hexo/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/node_modules/jsftp/lib/jsftp.js:261:11)
    at Ftp.parseResponse (/home/hiro/learning/gitdb/blog_hexo/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/node_modules/jsftp/lib/jsftp.js:174:8)
    at Stream.<anonymous> (/home/hiro/learning/gitdb/blog_hexo/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/node_modules/jsftp/lib/jsftp.js:146:24)
    at emitOne (events.js:77:13)
    at Stream.emit (events.js:169:7)
    at ResponseParser.reemit (/home/hiro/learning/gitdb/blog_hexo/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/node_modules/jsftp/node_modules/event-stream/node_modules/duplexer/index.js:70:25)
    at emitOne (events.js:77:13)
    at ResponseParser.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at ResponseParser.Readable.push (_stream_readable.js:110:10)
    at ResponseParser.Transform.push (_stream_transform.js:128:32)
    at ResponseParser.<anonymous> (/home/hiro/learning/gitdb/blog_hexo/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/node_modules/jsftp/node_modules/ftp-response-parser/index.js:65:12)
    at Array.forEach (native)
    at ResponseParser._transform (/home/hiro/learning/gitdb/blog_hexo/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/node_modules/jsftp/node_modules/ftp-response-parser/index.js:48:9)
    at ResponseParser.Transform._read (_stream_transform.js:167:10)
    at ResponseParser.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at ResponseParser.Writable.write (_stream_writable.js:207:11)
    at Socket.ondata (_stream_readable.js:525:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```
在万网主机上部署的，设置应该是正确的。但是在部署的过程中出错了。
```
deploy:
 type: ftpsync
 host: hostname.my3w.com
 user: username
 pass: passwd
 remote: /htdocs
 port: 21
 ignore: /logreport
 connections: 1
 verbose: true
```

**Comment by leesei** [comment]
This issue was moved to hexojs/hexo-deployer-ftpsync#9
