### ISSUE TITLE
hexo 3.1.1 version, hexo generate error. the theme is persona-color

### ISSUE THREAD

**Issue by jingzhiMo** [hexojs/hexo#1517]
error message:

```
Unhandled rejection TypeError: E:\GitHub\hexo\themes\persona-color\layout\archiv
e.ejs:1
 >> 1| <%- partial('_partial/archive', {pagination: config.archive}) %>

E:\GitHub\hexo\themes\persona-color\layout\_partial\archive.ejs:20
    18| <% } else { %>
    19|   <div class="archive">
 >> 20|     <% page.each(function(item){ %>
    21|       <article class="<%= item.layout %>">
    22|         <div class="post-content">
    23|           <header>

undefined is not a function
    at eval (eval at <anonymous> (E:\GitHub\hexo\node_modules\hexo-renderer-ejs\
node_modules\ejs\lib\ejs.js:242:14), <anonymous>:38:658)
    at eval (eval at <anonymous> (E:\GitHub\hexo\node_modules\hexo-renderer-ejs\
node_modules\ejs\lib\ejs.js:242:14), <anonymous>:38:2137)
    at E:\GitHub\hexo\node_modules\hexo-renderer-ejs\node_modules\ejs\lib\ejs.js
:255:15
    at Object.exports.render (E:\GitHub\hexo\node_modules\hexo-renderer-ejs\node
_modules\ejs\lib\ejs.js:293:13)
    at Hexo.<anonymous> (E:\GitHub\hexo\node_modules\hexo-renderer-ejs\index.js:
5:14)
    at Render.renderSync (E:\GitHub\hexo\node_modules\hexo\lib\hexo\render.js:87
:23)
    at View.renderSync (E:\GitHub\hexo\node_modules\hexo\lib\theme\view.js:50:29
)
    at Object.partial (E:\GitHub\hexo\node_modules\hexo\lib\plugins\helper\parti
al.js:42:19)
    at eval (eval at <anonymous> (E:\GitHub\hexo\node_modules\hexo-renderer-ejs\
node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:35)
    at eval (eval at <anonymous> (E:\GitHub\hexo\node_modules\hexo-renderer-ejs\
node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:103)
    at E:\GitHub\hexo\node_modules\hexo-renderer-ejs\node_modules\ejs\lib\ejs.js
:255:15
    at Object.exports.render (E:\GitHub\hexo\node_modules\hexo-renderer-ejs\node
_modules\ejs\lib\ejs.js:293:13)
    at Hexo.<anonymous> (E:\GitHub\hexo\node_modules\hexo-renderer-ejs\index.js:
5:14)
    at Hexo.tryCatcher (E:\GitHub\hexo\node_modules\hexo\node_modules\bluebird\j
s\main\util.js:26:23)
    at Hexo.<anonymous> (E:\GitHub\hexo\node_modules\hexo\node_modules\bluebird\
js\main\method.js:15:34)
    at E:\GitHub\hexo\node_modules\hexo\lib\hexo\render.js:51:21
    at tryCatcher (E:\GitHub\hexo\node_modules\hexo\node_modules\bluebird\js\mai
n\util.js:26:23)
    at Promise._settlePromiseFromHandler (E:\GitHub\hexo\node_modules\hexo\node_
modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (E:\GitHub\hexo\node_modules\hexo\node_modules\b
luebird\js\main\promise.js:581:18)
    at Promise._settlePromiseAtPostResolution (E:\GitHub\hexo\node_modules\hexo\
node_modules\bluebird\js\main\promise.js:245:10)
    at Async._drainQueue (E:\GitHub\hexo\node_modules\hexo\node_modules\bluebird
\js\main\async.js:128:12)
    at Async._drainQueues (E:\GitHub\hexo\node_modules\hexo\node_modules\bluebir
d\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\GitHub\hexo\node_module
s\hexo\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```

= =!

**Comment by Enolak** [comment]
good job
