### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Macxim** [hexojs/hexo#1518]
When running `npm install -g hexo-cli`, I get the following.

```bash
❯❯ npm install -g hexo-cli  
 
> fsevents@0.3.8 install /Users/macxim/.nvm/versions/node/v0.12.7/lib/node_modules/hexo-cli/node_modules/hexo-fs/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
In file included from ../node_modules/nan/nan.h:23:
In file included from /Users/macxim/.node-gyp/0.12.7/deps/uv/include/uv.h:48:
/Users/macxim/.node-gyp/0.12.7/deps/uv/include/uv-errno.h:25:10: fatal error: 'errno.h' file not found
#include <errno.h>
         ^
1 error generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/macxim/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/Users/macxim/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/macxim/.nvm/versions/node/v0.12.7/lib/node_modules/hexo-cli/node_modules/hexo-fs/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm WARN optional dep failed, continuing fsevents@0.3.8
/Users/macxim/.nvm/versions/node/v0.12.7/bin/hexo -> /Users/macxim/.nvm/versions/node/v0.12.7/lib/node_modules/hexo-cli/bin/hexo
hexo-cli@0.1.8 /Users/macxim/.nvm/versions/node/v0.12.7/lib/node_modules/hexo-cli
├── abbrev@1.0.7
├── minimist@1.2.0
├── bluebird@2.10.1
├── tildify@1.1.1 (os-homedir@1.0.1)
├── chalk@1.1.1 (supports-color@2.0.0, escape-string-regexp@1.0.3, ansi-styles@2.1.0, has-ansi@2.0.0, strip-ansi@3.0.0)
└── hexo-fs@0.1.4 (escape-string-regexp@1.0.3, graceful-fs@4.1.2, chokidar@1.0.6)

```

I tried with `node -v v4.0.0` and `node -v v0.12.7`. Same results.
It looks related to `node-gyp`. I'll post it there.

**Comment by leesei** [comment]
Install compiler package (e.g. `build-essentials`) on your platform.

**Comment by Macxim** [comment]
FYI @leesei, here is the follow-up on my issue.
`npm install -g hexo-cli` works fine now but I'm still having issue with a simple `npm install`.

**Comment by leesei** [comment]
Please post the install log.

**Comment by Macxim** [comment]
Are you referring to this one?

```bash
❯ npm install             
\
> fsevents@0.3.8 install /Users/macxim/code/project.github.io/node_modules/hexo/node_modules/nunjucks/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
In file included from ../node_modules/nan/nan.h:23:
In file included from /Users/macxim/.node-gyp/0.12.7/deps/uv/include/uv.h:48:
/Users/macxim/.node-gyp/0.12.7/deps/uv/include/uv-errno.h:25:10: fatal error: 'errno.h' file not found
#include <errno.h>
         ^
1 error generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/macxim/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/Users/macxim/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/macxim/code/project.github.io/node_modules/hexo/node_modules/nunjucks/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 

> dtrace-provider@0.6.0 install /Users/macxim/code/project.github.io/node_modules/hexo/node_modules/bunyan/node_modules/dtrace-provider
> node scripts/install.js

---------------
Building dtrace-provider failed with exit code 1 and signal 0
re-run install with environment variable V set to see the build output
---------------
npm WARN optional dep failed, continuing fsevents@0.3.8

```

**Comment by leesei** [comment]
That's weird.
How could you successfully install `fsevents` for `hexo-cli` but failed for `hexo`?

**Comment by Macxim** [comment]
That's a good question. The errors I reported above are occurring on my computer at work.
I wasn't able to properly reproduce them on my personal computer.

However, I am getting *another* error:

```bash
❯ npm install
|
> fsevents@0.3.8 install /Users/macuser/Desktop/test/node_modules/hexo/node_modules/nunjucks/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/macuser/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/Users/macuser/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/macuser/Desktop/test/node_modules/hexo/node_modules/nunjucks/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 

> dtrace-provider@0.6.0 install /Users/macuser/Desktop/test/node_modules/hexo/node_modules/bunyan/node_modules/dtrace-provider
> node scripts/install.js

---------------
Building dtrace-provider failed with exit code 1 and signal 0
re-run install with environment variable V set to see the build output
---------------
npm WARN optional dep failed, continuing fsevents@0.3.8

> fsevents@1.0.0 install /Users/macuser/Desktop/test/node_modules/hexo-deployer-git/node_modules/hexo-fs/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/macuser/Desktop/test/node_modules/hexo-deployer-git/node_modules/hexo-fs/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v14-darwin-x64/fse.node" is installed via remote

> fsevents@1.0.0 install /Users/macuser/Desktop/test/node_modules/hexo/node_modules/hexo-fs/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/macuser/Desktop/test/node_modules/hexo/node_modules/hexo-fs/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v14-darwin-x64/fse.node" is installed via remote
hexo-generator-category@0.1.3 node_modules/hexo-generator-category
├── object-assign@2.1.1
└── hexo-pagination@0.0.2 (utils-merge@1.0.0)

hexo-generator-archive@0.1.3 node_modules/hexo-generator-archive
├── object-assign@2.1.1
└── hexo-pagination@0.0.2 (utils-merge@1.0.0)

hexo-generator-index@0.1.3 node_modules/hexo-generator-index
├── object-assign@2.1.1
└── hexo-pagination@0.0.2 (utils-merge@1.0.0)

hexo-generator-tag@0.1.2 node_modules/hexo-generator-tag
├── object-assign@2.1.1
└── hexo-pagination@0.0.2 (utils-merge@1.0.0)

hexo-server@0.1.2 node_modules/hexo-server
├── object-assign@2.1.1
├── open@0.0.5
├── mime@1.3.4
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
├── morgan@1.6.1 (basic-auth@1.0.3, on-headers@1.0.0, depd@1.0.1, on-finished@2.3.0, debug@2.2.0)
├── serve-static@1.10.0 (escape-html@1.0.2, parseurl@1.3.0, send@0.13.0)
├── connect@3.4.0 (utils-merge@1.0.0, parseurl@1.3.0, debug@2.2.0, finalhandler@0.4.0)
├── compression@1.5.2 (bytes@2.1.0, vary@1.0.1, on-headers@1.0.0, debug@2.2.0, compressible@2.0.5, accepts@1.2.13)
└── bluebird@2.10.1

hexo-renderer-ejs@0.1.0 node_modules/hexo-renderer-ejs
├── ejs@1.0.0
└── lodash@2.4.2

hexo-renderer-stylus@0.3.0 node_modules/hexo-renderer-stylus
├── stylus@0.52.4 (css-parse@1.7.0, debug@2.2.0, mkdirp@0.5.1, source-map@0.1.43, glob@3.2.11, sax@0.5.8)
└── nib@1.1.0 (stylus@0.49.3)

hexo-renderer-marked@0.2.5 node_modules/hexo-renderer-marked
├── object-assign@2.1.1
├── marked@0.3.5
├── strip-indent@1.0.1 (get-stdin@4.0.1)
└── hexo-util@0.1.7 (ent@2.2.0, bluebird@2.10.1, highlight.js@8.8.0)

hexo-deployer-git@0.0.4 node_modules/hexo-deployer-git
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
├── swig@1.4.2 (optimist@0.6.1, uglify-js@2.4.24)
├── hexo-util@0.1.7 (ent@2.2.0, bluebird@2.10.1, highlight.js@8.8.0)
├── moment@2.10.6
└── hexo-fs@0.1.4 (escape-string-regexp@1.0.3, graceful-fs@4.1.2, bluebird@2.10.1, chokidar@1.1.0)

hexo@3.1.1 node_modules/hexo
├── hexo-front-matter@0.2.2
├── pretty-hrtime@1.0.0
├── abbrev@1.0.7
├── titlecase@1.0.2
├── archy@1.0.0
├── text-table@0.2.0
├── strip-indent@1.0.1 (get-stdin@4.0.1)
├── tildify@1.1.1 (os-homedir@1.0.1)
├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, has-ansi@2.0.0, strip-ansi@3.0.0)
├── hexo-i18n@0.2.1 (sprintf-js@1.0.3)
├── minimatch@2.0.10 (brace-expansion@1.1.1)
├── through2@1.1.1 (xtend@4.0.0, readable-stream@1.1.13)
├── swig-extras@0.0.1 (markdown@0.5.0)
├── bluebird@2.10.1
├── js-yaml@3.4.2 (esprima@2.2.0, argparse@1.0.2)
├── warehouse@1.0.3 (graceful-fs@4.1.2, cuid@1.2.5, JSONStream@1.0.6)
├── cheerio@0.19.0 (dom-serializer@0.1.0, entities@1.1.1, css-select@1.0.0, htmlparser2@3.8.3)
├── hexo-cli@0.1.8 (minimist@1.2.0)
├── swig@1.4.2 (optimist@0.6.1, uglify-js@2.4.24)
├── hexo-util@0.1.7 (ent@2.2.0, highlight.js@8.8.0)
├── moment-timezone@0.3.1
├── lodash@3.10.1
├── moment@2.10.6
├── nunjucks@1.3.4 (optimist@0.6.1, chokidar@0.12.6)
├── bunyan@1.5.1 (safe-json-stringify@1.0.3, mv@2.1.1, dtrace-provider@0.6.0)
└── hexo-fs@0.1.4 (escape-string-regexp@1.0.3, graceful-fs@4.1.2, chokidar@1.1.0)
                                                                                
~/Desktop/test source  3m 25s
❯ hexo
{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
Usage: hexo <command>

Commands:
  clean     Removed generated files and cache.
  config    Get or set configurations.
  deploy    Deploy your website.
  generate  Generate static files.
  help      Get help on a command.
  init      Create a new Hexo folder.
  list      List the information of the site
  migrate   Migrate your site from other system to Hexo.
  new       Create a new post.
  publish   Moves a draft post from _drafts to _posts folder.
  render    Render files with renderer plugins.
  server    Start the server.
  version   Display version information.

Global Options:
  --config  Specify config file instead of using _config.yml
  --cwd     Specify the CWD
  --debug   Display all verbose messages in the terminal
  --draft   Display draft posts
  --safe    Disable all plugins and scripts
  --silent  Hide output on console

For more help, you can use 'hexo help [command]' for the detailed information
or you can check the docs: http://hexo.io/docs/
```

**Comment by leesei** [comment]
It's definitely your build tools causing the issue (and it's not a Hexo issue).
Try to follow the OSX instruction in: https://github.com/nodejs/node-gyp

**Comment by Macxim** [comment]
Yes, that was also the conclusion I came to. That's why I moved the issue there https://github.com/nodejs/node-gyp/issues/741.
Anyway, thanks for taking the time to look into it. I'll close then.
