### ISSUE TITLE
Template render error: Error: Unable to call `old`, which is undefined or falsey

### ISSUE THREAD

**Issue by wedojava** [hexojs/hexo#1534]
```
<input type="text" name="street" id="street" class="form-control" value="{{ old('street') }}" required/>
```

当我要发布的内容包含如上的代码时，必须要用`````符号来框起来，如果是用空4格的方式来表示上面的代码则会报错：

```
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: Error: Unable to call `old`, which is undefined or falsey
    at Object.callWrap (/Users/wedojava/git/Blog/node_modules/hexo/node_modules/nunjucks/src/runtime.js:223:15)
    at root [as rootRenderFunc] (eval at <anonymous> (/Users/wedojava/git/Blog/node_modules/hexo/node_modules/nunjucks/src/environment.js:450:24), <anonymous>:8:68)
```

**Comment by leesei** [comment]
因為`{{` 導致nunjucks 解析`old` 為tag plugin
你己有workaround

Tracked by #1510
