### ISSUE TITLE
deploy error...

### ISSUE THREAD

**Issue by shxian** [hexojs/hexo#1544]
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': Invalid argument
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/do                                                                                                                cs/troubleshooting.html
Error: bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': Invalid argument

    at ChildProcess.<anonymous> (E:\hexo\node_modules\hexo-deployer-git\node_mod                                                                                                                ules\hexo-util\lib\spawn.js:42:17)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1080:5)

**Comment by shxian** [comment]
I google and change https to git@ or ssh,but the problems bellow happens...


fatal: 'git@github.com/shxian/shxian.github.io.git' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: fatal: 'git@github.com/shxian/shxian.github.io.git' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

    at ChildProcess.<anonymous> (E:\hexo\node_modules\hexo-deployer-git\node_modules\hexo-util\lib\spawn.js:42:17)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Socket.<anonymous> (child_process.js:1176:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:476:12)

**Comment by Xuanwo** [comment]
your repo is empty, please create at least a readme file

**Comment by shxian** [comment]
could not work ..

**Comment by shxian** [comment]
update mygit and solve the problem,, FML
