### ISSUE TITLE
how to fix Error：Cannot find module 'node_modules/hexo-console-rename'

### ISSUE THREAD

**Issue by NewbMiao** [hexojs/hexo#1547]
### Error
$ hexo g

    FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
    Error: Cannot find module '/Users/root/Documents/blog/node_modules/hexo-console-rename'
        at Function.Module._resolveFilename (module.js:336:15)
        at Function.require.resolve (module.js:388:19)
        at /Users/root/Documents/blog/node_modules/hexo/lib/hexo/load_plugins.js:40:24
        at tryCatcher (/Users/root/Documents/blog/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
        at MappingPromiseArray._promiseFulfilled (/Users/root/Documents/blog/node_modules/hexo/node_modules/bluebird/js/main/map.js:56:38)
        at MappingPromiseArray.init [as _init$] (/Users/root/Documents/blog/node_modules/hexo/node_modules/bluebird/js/main/promise_array.js:92:18)
        at Promise._settlePromiseAt (/Users/root/Documents/blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:579:21)
        at Promise._settlePromises (/Users/root/Documents/blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:697:14)
        at Async._drainQueue (/Users/root/Documents/blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:123:16)
        at Async._drainQueues (/Users/root/Documents/blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:133:10)
        at Immediate.Async.drainQueues [as _onImmediate] (/Users/root/Documents/blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:15:14)
        at processImmediate [as _immediateCallback] (timers.js:358:17)

### here is my package.json

    {
      "name": "hexo-site",
      "version": "0.0.0",
      "private": true,
      "hexo": {
        "version": "3.1.1"
      },
      "dependencies": {
        "hexo": "^3.1.1",
        "hexo-clean-css": "0.0.2",
        "hexo-console-optimize": "0.0.5",
        "hexo-console-rename": "^3.0.0",
        "hexo-deployer-git": "0.0.4",
        "hexo-generator-archive": "^0.1.2",
        "hexo-generator-baidu-sitemap": "^0.1.1",
        "hexo-generator-category": "^0.1.2",
        "hexo-generator-feed": "^1.0.2",
        "hexo-generator-index": "^0.1.2",
        "hexo-generator-sitemap": "^1.0.1",
        "hexo-generator-tag": "^0.1.1",
        "hexo-html-minifier": "0.0.1",
        "hexo-migrator-rss": "^0.1.2",
        "hexo-renderer-ejs": "^0.1.0",
        "hexo-renderer-marked": "^0.2.4",
        "hexo-renderer-stylus": "^0.2.0",
        "hexo-server": "^0.1.2",
        "hexo-uglify": "0.0.3"
      }
    }

**Comment by NewbMiao** [comment]
i found it happens because lack of themes/*,thanks to i back up my theme，now it‘is ok。
and **i also remove useless plugin & change my package.json**
---
	{
	  "name": "hexo-site",
	  "version": "0.0.0",
	  "private": true,
	  "hexo": {
	    "version": "3.1.1"
	  },
	  "dependencies": {
	    "hexo": "^3.1.1",
	    "hexo-console-optimize": "0.0.5",
	    "hexo-deployer-git": "0.0.4",
	    "hexo-generator-archive": "^0.1.2",
	    "hexo-generator-baidu-sitemap": "^0.1.1",
	    "hexo-generator-category": "^0.1.2",
	    "hexo-generator-feed": "~1.0.3",
	    "hexo-generator-index": "^0.1.2",
	    "hexo-generator-tag": "^0.1.1",
	    "hexo-renderer-ejs": "^0.1.0",
	    "hexo-renderer-marked": "^0.2.4",
	    "hexo-renderer-stylus": "^0.2.0",
	    "hexo-server": "^0.1.2"
	  }
	}
