### ISSUE TITLE
hexo has no method 'init'

### ISSUE THREAD

**Issue by fakefish** [hexojs/hexo#1548]
hexo version is 3.1.1

```
// app.js
require('hexo').init({command: 'server -p 9000'});
```
when I use `node app.js` then 
```
TypeError: Object function Hexo(base, args){
  base = base || process.cwd();
  args = args || {};

  EventEmitter.call(this);

  this.base_dir = base + sep;
  this.public_dir = pathFn.join(base, 'public') + sep;
  this.source_dir = pathFn.join(base, 'source') + sep;
  this.plugin_dir = pathFn.join(base, 'node_modules') + sep;
  this.script_dir = pathFn.join(base, 'scripts') + sep;
  this.scaffold_dir = pathFn.join(base, 'scaffolds') + sep;
  this.theme_dir = pathFn.join(base, 'themes', defaultConfig.theme) + sep;
  this.theme_script_dir = pathFn.join(this.theme_dir, 'scripts') + sep;

  this.env = {
    args: args,
    debug: Boolean(args.debug),
    safe: Boolean(args.safe),
    silent: Boolean(args.silent),
    env: process.env.NODE_ENV || 'development',
    version: pkg.version,
    init: false
  };

  this.config_path = args.config ? pathFn.resolve(base, args.config)
                                 : pathFn.join(base, '_config.yml');

  this.extend = {
    console: new extend.Console(),
    deployer: new extend.Deployer(),
    filter: new extend.Filter(),
    generator: new extend.Generator(),
    helper: new extend.Helper(),
    migrator: new extend.Migrator(),
    processor: new extend.Processor(),
    renderer: new extend.Renderer(),
    tag: new extend.Tag()
  };

  this.config = _.clone(defaultConfig);

  this.log = createLogger(this.env);

  this.render = new Render(this);

  this.route = new Router();

  this.post = new Post(this);

  this.scaffold = new Scaffold(this);

  this._dbLoaded = false;

  this._isGenerating = false;

  this.database = new Database({
    version: dbVersion,
    path: pathFn.join(base, 'db.json')
  });

  registerModels(this);

  this.source = new Source(this);
  this.theme = new Theme(this);
  this.locals = new Locals(this);
  this._bindLocals();
} has no method 'init'
    at repl:1:17
    at REPLServer.self.eval (repl.js:110:21)
    at repl.js:249:20
    at REPLServer.self.eval (repl.js:122:7)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.EventEmitter.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
    at Interface._line (readline.js:531:8)
    at Interface._ttyWrite (readline.js:760:14)
    at ReadStream.onkeypress (readline.js:99:10)
    at ReadStream.EventEmitter.emit (events.js:98:17)
    at emitKey (readline.js:1095:12)
    at readline.js:1080:7
    at String.forEach (native)
    at emitKey (readline.js:1079:29)
    at ReadStream.onData (readline.js:840:14)

```
what's wrong?

**Comment by leesei** [comment]
You need to `new` a Hexo instance first, see
https://github.com/hexojs/hexo-cli/blob/master/lib/index.js

**Comment by LaureKamalandua** [comment]
@leesei the link is dead, do you still have the reference?

**Comment by leesei** [comment]
Updated link, just check the commit log and find the relevant tag at the time of comment.

**Comment by LaureKamalandua** [comment]
I don't get why someone just can't write a codesnippet to be helpful.
This guy was planning to write a daemon for hexo and this ticket is closed with a lousy reference.

**Comment by leesei** [comment]
@LaureKamalandua the OP's issue is because of not creating a Hexo instance, and the reference link teach how to do so. That's why it is closed with the link.

I see you have a clear need, why don't you open a new issue?

**Comment by LaureKamalandua** [comment]
https://github.com/hexojs/hexo/issues/1762

**Comment by anyexinglu** [comment]
把app.js里的代码改成：

var Hexo = require('hexo');

hexo = new Hexo(process.cwd(), {});
hexo.init().then(function () {
hexo.call('server', {});
});

然后blog> forever app.js 即可！
