### ISSUE TITLE
代碼段解釋錯誤

### ISSUE THREAD

**Issue by akar1nchan** [hexojs/hexo#1555]
#!/bin/bash
    # Find out current screen width and hight
    _COLUMNS=$(tput cols)
    # Set default message if ( input not provided
    _MESSAGE=" FBI Warining "
    # Calculate x and y coordinates so that we can display $MESSAGE
    # centered in the screen
    y=$(( ( $_COLUMNS - ${#_MESSAGE} )  / 2 ))
    spaces=$(printf "%-${y}s" " ")
    # Alright display message stored in $_MESSAGE
    echo " "
    echo -e "${spaces}\033[41;37;5m FBI WARNING \033[0m"
    echo " "
    echo "Federal Law provides severe civil and criminal penalties for the unauthorized reproduction, distribution, or exhibition of copyrighted motion pictures (Title 17, United States Code, Sections 501 and 508). The Federal Bureau of Investigation investigates allegations of criminal copyright infringement"]
    _COLUMNS=$(tput cols)
    _MESSAGE="(Title 17, United States Code, Section 506)."
    y=$(( ( $_COLUMNS - ${#_MESSAGE} )  / 2 ))
    spaces=$(printf "%-${y}s" " ")
    echo -e "${spaces}(Title 17, United States Code, Section 506)."
    echo " "

試過 markdown 的四個空格 或者是 pre  or  code 標籤

hexo g 均失敗

```
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: expected end of comment, got end of file
    at Tokenizer.nextToken (/Users/Akar1nchan/Dropbox/blog2/node_modules/hexo/node_modules/nunjucks/src/lexer.js:282:23)
    at Object.extend.nextToken (/Users/Akar1nchan/Dropbox/blog2/node_modules/hexo/node_modules/nunjucks/src/parser.js:32:27)
    at Object.extend.peekToken (/Users/Akar1nchan/Dropbox/blog2/node_modules/hexo/node_modules/nunjucks/src/parser.js:44:43)
    at Object.extend.parseNodes (/Users/Akar1nchan/Dropbox/blog2/node_modules/hexo/node_modules/nunjucks/src/parser.js:1124:38)
    at Object.extend.parseAsRoot (/Users/Akar1nchan/Dropbox/blog2/node_modules/hexo/node_modules/nunjucks/src/parser.js:1177:42)
    at Object.module.exports.parse (/Users/Akar1nchan/Dropbox/blog2/node_modules/hexo/node_modules/nunjucks/src/parser.js:1199:18)
    at Object.module.exports.compile (/Users/Akar1nchan/Dropbox/blog2/node_modules/hexo/node_modules/nunjucks/src/compiler.js:1118:48)
    at Obj.extend._compile (/Users/Akar1nchan/Dropbox/blog2/node_modules/hexo/node_modules/nunjucks/src/environment.js:444:35)
    at Obj.extend.compile (/Users/Akar1nchan/Dropbox/blog2/node_modules/hexo/node_modules/nunjucks/src/environment.js:433:18)
    at null.<anonymous> (/Users/Akar1nchan/Dropbox/blog2/node_modules/hexo/node_modules/nunjucks/src/environment.js:378:22)
    at Object.exports.withPrettyErrors (/Users/Akar1nchan/Dropbox/blog2/node_modules/hexo/node_modules/nunjucks/src/lib.js:24:16)
    at Obj.extend.render (/Users/Akar1nchan/Dropbox/blog2/node_modules/hexo/node_modules/nunjucks/src/environment.js:374:20)
    at Obj.extend.renderString (/Users/Akar1nchan/Dropbox/blog2/node_modules/hexo/node_modules/nunjucks/src/environment.js:261:21)
    at /Users/Akar1nchan/Dropbox/blog2/node_modules/hexo/lib/extend/tag.js:56:9
    at tryCatcher (/Users/Akar1nchan/Dropbox/blog2/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/Users/Akar1nchan/Dropbox/blog2/node_modules/hexo/node_modules/bluebird/js/main/promise.js:480:31)
    at new Promise (/Users/Akar1nchan/Dropbox/blog2/node_modules/hexo/node_modules/bluebird/js/main/promise.js:70:37)
    at Tag.render (/Users/Akar1nchan/Dropbox/blog2/node_modules/hexo/lib/extend/tag.js:55:10)
    at Object.tagFilter [as onRenderEnd] (/Users/Akar1nchan/Dropbox/blog2/node_modules/hexo/lib/hexo/post.js:253:16)
    at /Users/Akar1nchan/Dropbox/blog2/node_modules/hexo/lib/hexo/render.js:55:19
    at tryCatcher (/Users/Akar1nchan/Dropbox/blog2/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/Akar1nchan/Dropbox/blog2/node_modules/hexo/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/Akar1nchan/Dropbox/blog2/node_modules/hexo/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/Users/Akar1nchan/Dropbox/blog2/node_modules/hexo/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/Users/Akar1nchan/Dropbox/blog2/node_modules/hexo/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/Akar1nchan/Dropbox/blog2/node_modules/hexo/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/Akar1nchan/Dropbox/blog2/node_modules/hexo/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```

**Comment by Xuanwo** [comment]
{% raw %}或者三个反斜杠试试看呢？

这串代码有一些符号可能导致错误

**Comment by akar1nchan** [comment]
@Xuanwo 

{% raw %}
content
{% endraw %}


使用這個還是報錯哦。。

**Comment by Xuanwo** [comment]
https://travis-ci.org/Xuanwo/xuanwo.github.io/builds/87383085#L412
我可以正常生成静态网页啊。。。

这是我这次测试的commit记录：https://github.com/Xuanwo/xuanwo.github.io/compare/58989e2997b0...f3acd4dc45d9

**Comment by leesei** [comment]
@akar1nchan 你上載一下有問題的md 吧。

**Comment by leesei** [comment]
Please open new issue if the problem persists with latest version.

**Comment by wd** [comment]
`{#` 应该是这个引起的，我也遇到这个问题了。

hexo: 3.2.2
hexo-cli: 1.0.2
os: Darwin 15.6.0 darwin x64
http_parser: 2.7.0
node: 6.3.0
v8: 5.0.71.52
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h
