### ISSUE TITLE
Help me, anyone hanppent to this error report when I execute "hexo d" command?

### ISSUE THREAD

**Issue by Chiva-Zhao** [hexojs/hexo#1558]
**I install git in my win10 64bit pc**
and my hexo version info as following:

>D:\workspace\blog>hexo -v
>hexo: 3.1.1
>os: Windows_NT 10.0.10240 win32 x64
>http_parser: 2.5.0
>node: 4.1.0
>v8: 4.5.103.33
>uv: 1.7.4
>zlib: 1.2.8
>ares: 1.10.1-DEV
>modules: 46
>openssl: 1.0.2d

Following is error report:
```java
nothing to commit, working directory clean
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': No error
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': No error

    at ChildProcess.<anonymous> (D:\workspace\blog\node_modules\hexo-deployer-git\node_modules\hexo-util\lib\spawn.js:42:17)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by Chiva-Zhao** [comment]
I resolve this issue by delete some environment variables like "SVN_SSH" or "SSH" path.

and change the deploy repo from https to git@github.com:your git url

**Comment by sabrinaluo** [comment]
Thx Chiva, I met the same issue!
