### ISSUE TITLE
（Solved）TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by losywee** [hexojs/hexo#1566]
当hexo new "test"  的时候报错！

TypeError: Cannot read property 'replace' of undefined
    at Object.exports.parse (/home/1233333/文档/hexo/blog/node_modules/hexo/node_modules/swig/lib/parser.js:438:18)
    at parse (/home/1233333/文档/hexo/blog/node_modules/hexo/node_modules/swig/lib/swig.js:354:19)
    at Object.precompile (/home/1233333/文档/hexo/blog/node_modules/hexo/node_modules/swig/lib/swig.js:486:23)
    at Object.compile (/home/1233333/文档/hexo/blog/node_modules/hexo/node_modules/swig/lib/swig.js:606:16)
    at /home/1233333/文档/hexo/blog/node_modules/hexo/lib/hexo/post.js:71:29
    at tryCatcher (/home/1233333/文档/hexo/blog/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/1233333/文档/hexo/blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:501:31)
    at Promise._settlePromiseAt (/home/1233333/文档/hexo/blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/home/1233333/文档/hexo/blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/home/1233333/文档/hexo/blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/1233333/文档/hexo/blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/1233333/文档/hexo/blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:368:17)

node版本$ node -v
v4.2.1

**Comment by SxxYu** [comment]
貌似跟我那个问题是一个原因

**Comment by losywee** [comment]
我已经解决了，重新在那个目录下初始化一下hexo就行了。

**Comment by bailitugesu** [comment]
怎么解决的啊，hexo init 都运行报错。怎么初始化

**Comment by shauning** [comment]
我把_config.yml配置里的url填上，问题就解决了。

**Comment by OUYANGSIHAI** [comment]
初始化hexo会把以前的还原吗

**Comment by pzs741** [comment]
……点了关注之后，所有人发的邮件我都能接到的么




| |
彭圳生
邮箱：pzsyjsgldd@163.com
|

签名由 网易邮箱大师 定制

在2018年02月10日 13:51，欧阳思海 写道：

初始化hexo会把以前的还原吗

**Comment by xianghongai** [comment]
我出现这个问题是因为改动了根目录下的`_config.yml`文件，

开始配置成了：
```
url: 域名/sub/
root: /sub/
```

后来更改为
```
url: 域名
root: 
```

这样就报错了，

应为`root: /`。

**Comment by FanqXu** [comment]
@losywee 我的也出现了这种情况，但是安装你的说法，初始化这个目录是不可能的，因为这个目录不为空。按照其他的伙伴说的方法修改了依旧无效。
