### ISSUE TITLE
Hexo 3.1.1 generate Error: expected end of comment, got end of file

### ISSUE THREAD

**Issue by YoungGer** [hexojs/hexo#1604]
错误的原因：
我想让hexo的menu指向一个新的自定义的html页，而且不采用主题样式。
因此我在`source`文件夹下面建立了`tools`文件夹，在这个文件夹下面放进了`index.html`。
同时在站点的配置文件中增加了
```
skip_render: 
  - README.md
  - tools/**s
  - test/*
```
在主题的配置文件中增加了
```
menu:
  home: /
  categories: /categories
  about: /about
  archives: /archives
  tags: /tags
  tools: /tools
```

结果报错。

错误信息如下：
```
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: expected end of comment, got end of file
    at Tokenizer.nextToken (E:\hexo\node_modules\nunjucks\src\lexer.js:282:23)
    at Object.extend.nextToken (E:\hexo\node_modules\nunjucks\src\parser.js:32:27)
    at Object.extend.peekToken (E:\hexo\node_modules\nunjucks\src\parser.js:44:43)
    at Object.extend.parseNodes (E:\hexo\node_modules\nunjucks\src\parser.js:1124:38)
    at Object.extend.parseAsRoot (E:\hexo\node_modules\nunjucks\src\parser.js:1177:42)
    at Object.module.exports.parse (E:\hexo\node_modules\nunjucks\src\parser.js:1199:18)
    at Object.module.exports.compile (E:\hexo\node_modules\nunjucks\src\compiler.js:1118:48)
    at Obj.extend._compile (E:\hexo\node_modules\nunjucks\src\environment.js:444:35)
    at Obj.extend.compile (E:\hexo\node_modules\nunjucks\src\environment.js:433:18)
    at null.<anonymous> (E:\hexo\node_modules\nunjucks\src\environment.js:378:22)
    at Object.exports.withPrettyErrors (E:\hexo\node_modules\nunjucks\src\lib.js:24:16)
    at Obj.extend.render (E:\hexo\node_modules\nunjucks\src\environment.js:374:20)
    at Obj.extend.renderString (E:\hexo\node_modules\nunjucks\src\environment.js:261:21)
    at E:\hexo\node_modules\hexo\lib\extend\tag.js:56:9
    at tryCatcher (E:\hexo\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._resolveFromResolver (E:\hexo\node_modules\bluebird\js\main\promise.js:480:31)
    at new Promise (E:\hexo\node_modules\bluebird\js\main\promise.js:70:37)
    at Tag.render (E:\hexo\node_modules\hexo\lib\extend\tag.js:55:10)
    at Object.tagFilter [as onRenderEnd] (E:\hexo\node_modules\hexo\lib\hexo\post.js:253:16)
    at E:\hexo\node_modules\hexo\lib\hexo\render.js:55:19
    at tryCatcher (E:\hexo\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (E:\hexo\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (E:\hexo\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromises (E:\hexo\node_modules\bluebird\js\main\promise.js:697:14)
    at Async._drainQueue (E:\hexo\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (E:\hexo\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\hexo\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

但是我把`index.html`改成一个简单的hello word就可以，请问是跟index.html有关系么？
hexo是不是还对index.html进行了一些解析，一些符号可能解析失败？
另外请教下我有自己制作的网页，想从一个menu链接到自己做的网页该如何做啊，谢谢！

**Comment by reverland** [comment]
我也觉得，如果异常信息如果有关于解析的上下文就好了

**Comment by Xuanwo** [comment]
@YoungGer 
建议使用
```
skip_render: 
  - README.md
  - tools/**s
  - test/*
```
skip_render的配置可能有些问题，可以参考[此处](https://xuanwo.org/2014/08/14/hexo-usual-problem/#Hexo3-0以上支持)，报错的原因应该这个没有被skip掉，还是进行了处理。

如果想连接到自己的网页，只需要进行如下配置（*印象中是这样，来当一次小白鼠吧~*）：
```
menu:
  home: /
  categories: /categories
  about: /about
  archives: /archives
  tags: /tags
  tools: /tools
  diy: //github.com/hexojs/hexo/issues/1604
```

@reverland 确实是个问题，待我有空研究研究- -

**Comment by youngzhu** [comment]
帮我解决了一个问题，谢谢！

我在`source` 下放了个` README.md` 文件，每次deploy的时候总是被渲染成 html 文件。
这不是我想要的。
看到这个配置文件里的 `skip_render: ` ，于是修改了下：

``` bash
skip_render: source/README.md
```

没效果。
原来语法是这样的。

**Comment by corminlu** [comment]
```
skip_render: 
  - README.md
```

用这办法终于解决问题了，readme也不用麻烦了
