### ISSUE TITLE
deploy problem

### ISSUE THREAD

**Issue by gabygoole** [hexojs/hexo#1638]
I can't deploy?prompt:
```
To https://github.com/gabygoole/gabygoole.github.io.git
 ! [remote rejected] master -> master (failed to lock)
error: failed to push some refs to 'https://github.com/gabygoole/gabygoole.githu                                                               b.io.git'
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/do                                                               cs/troubleshooting.html
Error: To https://github.com/gabygoole/gabygoole.github.io.git
 ! [remote rejected] master -> master (failed to lock)
error: failed to push some refs to 'https://github.com/gabygoole/gabygoole.githu                                                               b.io.git'

    at ChildProcess.<anonymous> (C:\blog\node_modules\hexo-deployer-git\node_mod                                                               ules\hexo-util\lib\spawn.js:42:17)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by Xuanwo** [comment]
delete the `.dployer_git` floder and deploy again

**Comment by gabygoole** [comment]
I have solved that,
http://stackoverflow.com/questions/34178224/hexo-cant-deploy/34179099#34179099
