### ISSUE TITLE
hexo generate出现了这样的提示

### ISSUE THREAD

**Issue by gabygoole** [hexojs/hexo#1647]
```
cs/troubleshooting.html
Template render error: expected variable end
    at Error.exports.TemplateError (C:\blog\node_modules\hexo\node_modules\nunju                                                               cks\src\lib.js:51:19)
    at Object.extend.fail (C:\blog\node_modules\hexo\node_modules\nunjucks\src\p                                                               arser.js:64:15)
    at Object.extend.advanceAfterVariableEnd (C:\blog\node_modules\hexo\node_mod                                                               ules\nunjucks\src\parser.js:133:18)
    at Object.extend.parseNodes (C:\blog\node_modules\hexo\node_modules\nunjucks                                                               \src\parser.js:1159:22)
    at Object.extend.parseAsRoot (C:\blog\node_modules\hexo\node_modules\nunjuck                                                               s\src\parser.js:1177:42)
    at Object.module.exports.parse (C:\blog\node_modules\hexo\node_modules\nunju                                                               cks\src\parser.js:1199:18)
    at Object.module.exports.compile (C:\blog\node_modules\hexo\node_modules\nun                                                               jucks\src\compiler.js:1118:48)
    at Obj.extend._compile (C:\blog\node_modules\hexo\node_modules\nunjucks\src\                                                               environment.js:444:35)
    at Obj.extend.compile (C:\blog\node_modules\hexo\node_modules\nunjucks\src\e                                                               nvironment.js:433:18)
    at null.<anonymous> (C:\blog\node_modules\hexo\node_modules\nunjucks\src\env                                                               ironment.js:378:22)
    at Object.exports.withPrettyErrors (C:\blog\node_modules\hexo\node_modules\n                                                               unjucks\src\lib.js:24:16)
    at Obj.extend.render (C:\blog\node_modules\hexo\node_modules\nunjucks\src\en                                                               vironment.js:374:20)
    at Obj.extend.renderString (C:\blog\node_modules\hexo\node_modules\nunjucks\                                                               src\environment.js:261:21)
    at C:\blog\node_modules\hexo\lib\extend\tag.js:56:9
    at tryCatcher (C:\blog\node_modules\hexo\node_modules\bluebird\js\main\util.                                                               js:26:23)
    at Promise._resolveFromResolver (C:\blog\node_modules\hexo\node_modules\blue                                                               bird\js\main\promise.js:480:31)
    at new Promise (C:\blog\node_modules\hexo\node_modules\bluebird\js\main\prom                                                               ise.js:70:37)
    at Tag.render (C:\blog\node_modules\hexo\lib\extend\tag.js:55:10)
    at Object.tagFilter [as onRenderEnd] (C:\blog\node_modules\hexo\lib\hexo\pos                                                               t.js:253:16)
    at C:\blog\node_modules\hexo\lib\hexo\render.js:55:19
    at tryCatcher (C:\blog\node_modules\hexo\node_modules\bluebird\js\main\util.                                                               js:26:23)
    at Promise._settlePromiseFromHandler (C:\blog\node_modules\hexo\node_modules                                                               \bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (C:\blog\node_modules\hexo\node_modules\bluebird                                                               \js\main\promise.js:581:18)
    at Promise._settlePromises (C:\blog\node_modules\hexo\node_modules\bluebird\                                                               js\main\promise.js:697:14)
    at Async._drainQueue (C:\blog\node_modules\hexo\node_modules\bluebird\js\mai                                                               n\async.js:123:16)
    at Async._drainQueues (C:\blog\node_modules\hexo\node_modules\bluebird\js\ma                                                               in\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\blog\node_modules\hexo\                                                               node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

```

**Comment by gabygoole** [comment]
当我删除新写的文章重新`hexo generate`是没问题的，难道博文中有什么问题，我改成七牛图床了来加载图片了

**Comment by gabygoole** [comment]
```
Gaby@Gaby-PC MINGW64 /c/blog
$ hexo generate
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: expected variable end
    at Error.exports.TemplateError (C:\blog\node_modules\hexo\node_modules\nunjucks\src\lib.js:51:19)
    at Object.extend.fail (C:\blog\node_modules\hexo\node_modules\nunjucks\src\parser.js:64:15)
    at Object.extend.advanceAfterVariableEnd (C:\blog\node_modules\hexo\node_modules\nunjucks\src\parser.js:133:18)
    at Object.extend.parseNodes (C:\blog\node_modules\hexo\node_modules\nunjucks\src\parser.js:1159:22)
    at Object.extend.parseAsRoot (C:\blog\node_modules\hexo\node_modules\nunjucks\src\parser.js:1177:42)
    at Object.module.exports.parse (C:\blog\node_modules\hexo\node_modules\nunjucks\src\parser.js:1199:18)
    at Object.module.exports.compile (C:\blog\node_modules\hexo\node_modules\nunjucks\src\compiler.js:1118:48)
    at Obj.extend._compile (C:\blog\node_modules\hexo\node_modules\nunjucks\src\environment.js:444:35)
    at Obj.extend.compile (C:\blog\node_modules\hexo\node_modules\nunjucks\src\environment.js:433:18)
    at null.<anonymous> (C:\blog\node_modules\hexo\node_modules\nunjucks\src\environment.js:378:22)
    at Object.exports.withPrettyErrors (C:\blog\node_modules\hexo\node_modules\nunjucks\src\lib.js:24:16)
    at Obj.extend.render (C:\blog\node_modules\hexo\node_modules\nunjucks\src\environment.js:374:20)
    at Obj.extend.renderString (C:\blog\node_modules\hexo\node_modules\nunjucks\src\environment.js:261:21)
    at C:\blog\node_modules\hexo\lib\extend\tag.js:56:9
    at tryCatcher (C:\blog\node_modules\hexo\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._resolveFromResolver (C:\blog\node_modules\hexo\node_modules\bluebird\js\main\promise.js:480:31)
    at new Promise (C:\blog\node_modules\hexo\node_modules\bluebird\js\main\promise.js:70:37)
    at Tag.render (C:\blog\node_modules\hexo\lib\extend\tag.js:55:10)
    at Object.tagFilter [as onRenderEnd] (C:\blog\node_modules\hexo\lib\hexo\post.js:253:16)
    at C:\blog\node_modules\hexo\lib\hexo\render.js:55:19
    at tryCatcher (C:\blog\node_modules\hexo\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\blog\node_modules\hexo\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (C:\blog\node_modules\hexo\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromises (C:\blog\node_modules\hexo\node_modules\bluebird\js\main\promise.js:697:14)
    at Async._drainQueue (C:\blog\node_modules\hexo\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (C:\blog\node_modules\hexo\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\blog\node_modules\hexo\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by gabygoole** [comment]
已解决！原因是七牛图床不适用与hexo，改为新浪图床就可以了，但据说七牛图床要强大的多啊？

**Comment by Xuanwo** [comment]
原来用过没有问题的，应该是姿势不对
