### ISSUE TITLE
hexo server doesn't work anymore (node: 0.12.0)

### ISSUE THREAD

**Issue by paullo0106** [hexojs/hexo#1648]
I used to have my `hexo server` working normally, but suddenly it doesn't work anymore.
The server doesn't come up, without any error message. (Please see the output below)

I have checked:
1. port 4000 is not in use
2. Executed `hexo clean`
3. *_config.yml* is never changed recently
4. I can execute `hexo new post` successfully

What are some other things I could do to locate the issue? Thanks.

```
root@myhost:/blog/# hexo server --debug
03:40:33.428 DEBUG Hexo version: 3.1.1
03:40:33.443 DEBUG Working directory: /blog/
03:40:33.847 DEBUG Config loaded: /blog/_config.yml
03:40:33.898 DEBUG Script loaded: themes/icarus/scripts/fancybox.js
03:40:33.920 DEBUG Plugin loaded: hexo-generator-archive
03:40:33.938 DEBUG Plugin loaded: hexo-generator-category
03:40:33.956 DEBUG Plugin loaded: hexo-generator-index
03:40:33.974 DEBUG Plugin loaded: hexo-generator-tag
03:40:34.045 DEBUG Plugin loaded: hexo-renderer-ejs
03:40:34.640 DEBUG Plugin loaded: hexo-renderer-stylus
03:40:34.861 DEBUG Plugin loaded: hexo-renderer-marked
03:40:35.364 DEBUG Plugin loaded: hexo-server
03:40:35.842 DEBUG Plugin loaded: hexo-admin
03:40:35.904 DEBUG Loading database.
03:40:35.982 DEBUG Added: source/_posts/A
...
...
03:40:38.727 DEBUG Processed: layout/_partial/archive-post.ejs
03:40:38.728 DEBUG Processed: layout/_partial/after-footer.ejs
03:40:38.730 DEBUG Processed: languages/zh-CN.yml
03:40:38.731 DEBUG Processed: languages/ja.yml
03:40:38.732 DEBUG Processed: languages/id.yml
03:40:38.733 DEBUG Processed: languages/en.yml
03:40:38.734 DEBUG Theme config loaded.
03:40:38.735 DEBUG Processed: _config.yml
Killed
```

**Comment by lichunqiang** [comment]
a trouble to me:
```
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: expected end of comment, got end of file
    at Tokenizer.nextToken (D:\project\lichunqiang.github.io\node_modules\hexo\node_modules\nunjucks\src\lexer.js:282:23)
    at Object.extend.nextToken (D:\project\lichunqiang.github.io\node_modules\hexo\node_modules\nunjucks\src\parser.js:32:27)
    at Object.extend.peekToken (D:\project\lichunqiang.github.io\node_modules\hexo\node_modules\nunjucks\src\parser.js:44:43)
    at Object.extend.parseNodes (D:\project\lichunqiang.github.io\node_modules\hexo\node_modules\nunjucks\src\parser.js:1124:38)
    at Object.extend.parseAsRoot (D:\project\lichunqiang.github.io\node_modules\hexo\node_modules\nunjucks\src\parser.js:1177:42)
    at Object.module.exports.parse (D:\project\lichunqiang.github.io\node_modules\hexo\node_modules\nunjucks\src\parser.js:1199:18)
    at Object.module.exports.compile (D:\project\lichunqiang.github.io\node_modules\hexo\node_modules\nunjucks\src\compiler.js:1118:48)
    at Obj.extend._compile (D:\project\lichunqiang.github.io\node_modules\hexo\node_modules\nunjucks\src\environment.js:444:35)
    at Obj.extend.compile (D:\project\lichunqiang.github.io\node_modules\hexo\node_modules\nunjucks\src\environment.js:433:18)
    at null.<anonymous> (D:\project\lichunqiang.github.io\node_modules\hexo\node_modules\nunjucks\src\environment.js:378:22)
    at Object.exports.withPrettyErrors (D:\project\lichunqiang.github.io\node_modules\hexo\node_modules\nunjucks\src\lib.js:24:16)
    at Obj.extend.render (D:\project\lichunqiang.github.io\node_modules\hexo\node_modules\nunjucks\src\environment.js:374:20)
    at Obj.extend.renderString (D:\project\lichunqiang.github.io\node_modules\hexo\node_modules\nunjucks\src\environment.js:261:21)
    at D:\project\lichunqiang.github.io\node_modules\hexo\lib\extend\tag.js:56:9
    at tryCatcher (D:\project\lichunqiang.github.io\node_modules\hexo\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._resolveFromResolver (D:\project\lichunqiang.github.io\node_modules\hexo\node_modules\bluebird\js\main\promise.js:480:31)
    at new Promise (D:\project\lichunqiang.github.io\node_modules\hexo\node_modules\bluebird\js\main\promise.js:70:37)
    at Tag.render (D:\project\lichunqiang.github.io\node_modules\hexo\lib\extend\tag.js:55:10)
    at Object.tagFilter [as onRenderEnd] (D:\project\lichunqiang.github.io\node_modules\hexo\lib\hexo\post.js:253:16)
    at D:\project\lichunqiang.github.io\node_modules\hexo\lib\hexo\render.js:55:19
    at tryCatcher (D:\project\lichunqiang.github.io\node_modules\hexo\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (D:\project\lichunqiang.github.io\node_modules\hexo\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (D:\project\lichunqiang.github.io\node_modules\hexo\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromises (D:\project\lichunqiang.github.io\node_modules\hexo\node_modules\bluebird\js\main\promise.js:697:14)
    at Async._drainQueue (D:\project\lichunqiang.github.io\node_modules\hexo\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (D:\project\lichunqiang.github.io\node_modules\hexo\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\project\lichunqiang.github.io\node_modules\hexo\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)

```
```
hexo: 3.1.1
os: Windows_NT 6.3.9600 win32 x64
http_parser: 2.3
node: 0.12.0
v8: 3.28.73
uv: 1.0.2
zlib: 1.2.8
modules: 14
openssl: 1.0.1l
```

**Comment by paullo0106** [comment]
I'm using Ubuntu 14.04.2

**Comment by Xuanwo** [comment]
node 0.10.25 may result some problem, try other version?

**Comment by lichunqiang** [comment]
@Xuanwo 那012.0呢

**Comment by Xuanwo** [comment]
@lichunqiang 你可以试一下，据我所知： https://github.com/hexojs/hexo-server/blob/master/.travis.yml ， hexo-server在0.12，4以及5上都是通过了test的。

**Comment by paullo0106** [comment]
I upgraded node version to 0.12.5 and the problem seems resolved
```
21:33:45.531 DEBUG Processed: layout/_partial/archive-post.ejs
21:33:45.532 DEBUG Processed: layout/_partial/after-footer.ejs
21:33:45.534 DEBUG Processed: languages/zh-CN.yml
21:33:45.536 DEBUG Processed: languages/ja.yml
21:33:45.537 DEBUG Processed: languages/id.yml
21:33:45.538 DEBUG Processed: languages/en.yml
21:33:45.540 DEBUG Theme config loaded.
21:33:45.541 DEBUG Processed: _config.yml
21:33:46.900 DEBUG Generator: page
21:33:46.902 DEBUG Generator: post
21:33:46.903 DEBUG Generator: archive
21:33:46.903 DEBUG Generator: category
21:33:46.904 DEBUG Generator: index
21:33:46.904 DEBUG Generator: tag
21:33:46.914 DEBUG Generator: asset
21:33:47.042 INFO  Hexo is running at http://xx.xx.xx.xx:4000/blog/. Press Ctrl+C to stop.
21:33:47.094 DEBUG Database saved
```

Steps:

```
root@myhost:~# sudo npm install -g n  
root@myhost:~# sudo n 0.12.5

     install : node-v0.12.5
       mkdir : /usr/local/n/versions/node/0.12.5
       fetch : https://nodejs.org/dist/v0.12.5/node-v0.12.5-linux-x64.tar.gz
   installed : v0.12.5

root@myhost:~# cd /var/www/html/blog/
root@myhost:/var/www/html/blog# hexo version
hexo: 3.1.1
os: Linux 3.13.0-43-generic linux x64
http_parser: 2.3
node: 0.12.5
v8: 3.28.71.19
uv: 1.6.1
zlib: 1.2.8
modules: 14
openssl: 1.0.1o
```

**Comment by paullo0106** [comment]
@lichunqiang :  I closed this issue for now. If node version is not the cause for you, please feel free to update the status (or create another issue, maybe?).

**Comment by rose1988c** [comment]
````
hexo: 3.1.1
os: Linux 2.6.32-042stab108.2 linux ia32
http_parser: 2.3
node: 0.12.5
v8: 3.28.71.19
uv: 1.6.1
zlib: 1.2.8
modules: 14
openssl: 1.0.1o
````

![image](https://cloud.githubusercontent.com/assets/2977179/12669455/953108a6-c69b-11e5-902e-62cbc66b676d.png)

**Comment by rose1988c** [comment]
换了一台vps，还是有问题~~~~~，醉了。。
````
hexo: 3.1.1
os: Linux 3.18.20-nce-amd64 linux x64
http_parser: 2.3
node: 0.12.7
v8: 3.28.71.19
uv: 1.6.1
zlib: 1.2.8
modules: 14
openssl: 1.0.1p
````

![image](https://cloud.githubusercontent.com/assets/2977179/12670488/d968bb74-c6a3-11e5-9f27-36bf11d95b82.png)

**Comment by drduan** [comment]
你试试重新Init一个文件夹 并且 把你原来的themes 和 _post 还有主目录下的_config. 吧package.json的插件重装一遍。这样最省事
