### ISSUE TITLE
Hexo dies trying to render a file even when using skip_render

### ISSUE THREAD

**Issue by andyhall** [hexojs/hexo#1664]
I have some non-hexo content in my site, so I tell hexo to ignore it in the config:

```yaml
skip_render:
 - demo/**
```
However, when I run hexo commands they fail, trying to parse a file inside the `demo` directory. Specifically there's a large complex JS file in there that causes `hexo generate` and `hexo server` to die. If I remove the JS file they work fine. 

Since `skip_render` is set, shouldn't hexo just copy the file over without processing it? The error message looks like this:

```bash
> hexo clean;hexo generate
INFO  Deleted database.
INFO  Deleted public folder.
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: unexpected token: :
    at Error.exports.TemplateError (/Users/andy/test/node_modules/nunjucks/src/lib.js:51:19)
    at Object.extend.fail (/Users/andy/test/node_modules/nunjucks/src/parser.js:64:15)
    at Object.extend.parsePrimary (/Users/andy/test/node_modules/nunjucks/src/parser.js:947:18)
    at Object.extend.parseUnary (/Users/andy/test/node_modules/nunjucks/src/parser.js:882:25)
    at Object.extend.parsePow (/Users/andy/test/node_modules/nunjucks/src/parser.js:856:25)
    at Object.extend.parseMod (/Users/andy/test/node_modules/nunjucks/src/parser.js:844:25)
    at Object.extend.parseFloorDiv (/Users/andy/test/node_modules/nunjucks/src/parser.js:832:25)
    at Object.extend.parseDiv (/Users/andy/test/node_modules/nunjucks/src/parser.js:820:25)
    at Object.extend.parseMul (/Users/andy/test/node_modules/nunjucks/src/parser.js:808:25)
    at Object.extend.parseSub (/Users/andy/test/node_modules/nunjucks/src/parser.js:796:25)
    at Object.extend.parseAdd (/Users/andy/test/node_modules/nunjucks/src/parser.js:784:25)
    at Object.extend.parseCompare (/Users/andy/test/node_modules/nunjucks/src/parser.js:751:25)
    at Object.extend.parseIn (/Users/andy/test/node_modules/nunjucks/src/parser.js:720:23)
    at Object.extend.parseNot (/Users/andy/test/node_modules/nunjucks/src/parser.js:716:21)
    at Object.extend.parseAnd (/Users/andy/test/node_modules/nunjucks/src/parser.js:698:25)
    at Object.extend.parseOr (/Users/andy/test/node_modules/nunjucks/src/parser.js:686:25)
    at Object.extend.parseInlineIf (/Users/andy/test/node_modules/nunjucks/src/parser.js:668:25)
    at Object.extend.parseExpression (/Users/andy/test/node_modules/nunjucks/src/parser.js:663:25)
    at Object.extend.parseNodes (/Users/andy/test/node_modules/nunjucks/src/parser.js:1158:30)
    at Object.extend.parseAsRoot (/Users/andy/test/node_modules/nunjucks/src/parser.js:1177:42)
    at Object.module.exports.parse (/Users/andy/test/node_modules/nunjucks/src/parser.js:1199:18)
    at Object.module.exports.compile (/Users/andy/test/node_modules/nunjucks/src/compiler.js:1118:48)
    at Obj.extend._compile (/Users/andy/test/node_modules/nunjucks/src/environment.js:444:35)
    at Obj.extend.compile (/Users/andy/test/node_modules/nunjucks/src/environment.js:433:18)
    at null.<anonymous> (/Users/andy/test/node_modules/nunjucks/src/environment.js:378:22)
    at Object.exports.withPrettyErrors (/Users/andy/test/node_modules/nunjucks/src/lib.js:24:16)
    at Obj.extend.render (/Users/andy/test/node_modules/nunjucks/src/environment.js:374:20)
    at Obj.extend.renderString (/Users/andy/test/node_modules/nunjucks/src/environment.js:261:21)
> 
```

**Comment by andyhall** [comment]
Got lost in all the replies and logged a more specific bug.
