### ISSUE TITLE
Error when generate: Object  has no method 'trim'

### ISSUE THREAD

**Issue by MegaThomas** [hexojs/hexo#1717]
When I generate Hexo, it will return this. At `tag.js:84:67`, there are `node.addChild(new nodes.Literal(token.lineno, token.colno, args.trim()));`, while `var args=[];` is declared at `tag.js:77`
```
TypeError: Object  has no method 'trim'
    at NunjucksBlock.NunjucksTag._parseArgs (E:\myweb\basswarlock\node_modules\hexo\lib\extend\tag.js:84:67)
    at NunjucksBlock.parse (E:\myweb\basswarlock\node_modules\hexo\lib\extend\tag.js:104:19)
    at Object.extend.parseStatement (E:\myweb\basswarlock\node_modules\hexo\node_modules\nunjucks\src\parser.js:540:36)
    at Object.extend.parseNodes (E:\myweb\basswarlock\node_modules\hexo\node_modules\nunjucks\src\parser.js:1151:30)
    at Object.extend.parseAsRoot (E:\myweb\basswarlock\node_modules\hexo\node_modules\nunjucks\src\parser.js:1177:42)
    at Object.module.exports.parse (E:\myweb\basswarlock\node_modules\hexo\node_modules\nunjucks\src\parser.js:1199:18)
    at Object.module.exports.compile (E:\myweb\basswarlock\node_modules\hexo\node_modules\nunjucks\src\compiler.js:1118:48)
    at Obj.extend._compile (E:\myweb\basswarlock\node_modules\hexo\node_modules\nunjucks\src\environment.js:444:35)
    at Obj.extend.compile (E:\myweb\basswarlock\node_modules\hexo\node_modules\nunjucks\src\environment.js:433:18)
    at null.<anonymous> (E:\myweb\basswarlock\node_modules\hexo\node_modules\nunjucks\src\environment.js:378:22)
    at Object.exports.withPrettyErrors (E:\myweb\basswarlock\node_modules\hexo\node_modules\nunjucks\src\lib.js:24:16)
    at Obj.extend.render (E:\myweb\basswarlock\node_modules\hexo\node_modules\nunjucks\src\environment.js:374:20)
    at Obj.extend.renderString (E:\myweb\basswarlock\node_modules\hexo\node_modules\nunjucks\src\environment.js:261:21)
    at E:\myweb\basswarlock\node_modules\hexo\lib\extend\tag.js:56:9
    at tryCatcher (E:\myweb\basswarlock\node_modules\hexo\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._resolveFromResolver (E:\myweb\basswarlock\node_modules\hexo\node_modules\bluebird\js\main\promise.js:480:31)
    at new Promise (E:\myweb\basswarlock\node_modules\hexo\node_modules\bluebird\js\main\promise.js:70:37)
    at Tag.render (E:\myweb\basswarlock\node_modules\hexo\lib\extend\tag.js:55:10)
    at Object.tagFilter [as onRenderEnd] (E:\myweb\basswarlock\node_modules\hexo\lib\hexo\post.js:253:16)
    at Promise.then.then.then.output (E:\myweb\basswarlock\node_modules\hexo\lib\hexo\render.js:55:19)
    at tryCatcher (E:\myweb\basswarlock\node_modules\hexo\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (E:\myweb\basswarlock\node_modules\hexo\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (E:\myweb\basswarlock\node_modules\hexo\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromises (E:\myweb\basswarlock\node_modules\hexo\node_modules\bluebird\js\main\promise.js:697:14)
    at Async._drainQueue (E:\myweb\basswarlock\node_modules\hexo\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (E:\myweb\basswarlock\node_modules\hexo\node_modules\bluebird\js\main\async.js:133:10)
    at Async.drainQueues (E:\myweb\basswarlock\node_modules\hexo\node_modules\bluebird\js\main\async.js:15:14)
    at process._tickCallback (node.js:419:13)
```
Is there any generator-... npm module I need to install to prevent this?

**Comment by MegaThomas** [comment]
I've found what's wrong. I have a `` `{%%}` `` in markdown, which is in a incorrect way. I should have escae them.
