### ISSUE TITLE
Permission denied (publickey).

### ISSUE THREAD

**Issue by drduan** [hexojs/hexo#1730]
sometimes I change the plugins ,than deploy it on github but 
```
FATAL Error: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

    at ChildProcess.<anonymous> (/Users/duanxudong/Documents/hexo/node_modules/hexo-util/lib/spawn.js:42:17)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

**Comment by Xuanwo** [comment]
```
FATAL Error: Permission denied (publickey).
```

检查一下密钥或者Git地址吧~

**Comment by drduan** [comment]
恩  不是ssh活着ssh key出错 应该是插件的问题。
我remove掉那个.deploy文件夹 把ssh换成https好用了。

**Comment by drduan** [comment]
你会说中文啊

**Comment by leejay1992** [comment]
请问 怎么把ssh更换为https 呢？谢谢

**Comment by NoahDragon** [comment]
@leejay1992 copy repo url and select https.

**Comment by leejay1992** [comment]
@NoahDragon thx 不过 我操作了 还是不得行哎呀 也不知道哪儿出了毛病 还是 不能 hexo d 总是出错

**Comment by NoahDragon** [comment]
@leejay1992 看下你remote repo的设置 ` git remote -v ` 实在不行可以手动deploy，将Public文件夹下的文件upload到gh-pagesbranch。

**Comment by leejay1992** [comment]
@NoahDragon 好的 thx 我试一下
