### ISSUE TITLE
进入目录页报错，目录页URL包含中文

### ISSUE THREAD

**Issue by raytaylorlin** [hexojs/hexo#1746]
进入该地址`http://localhost:4000/categories/日常`时，页面直接显示以下错误，上个版本是好的，这个版本的tag页包含中文（如`http://localhost:4000/tags/日常`）也是没问题的。

```
TypeError: The header content contains invalid characters
   at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:348:11)
   at C:\Users\RayTaylor\Documents\Github\raytaylorlin.github.io\node_modules\hexo-server\lib\middlewares\route.js:28:11
   at call (C:\Users\RayTaylor\Documents\Github\raytaylorlin.github.io\node_modules\connect\index.js:239:7)
   at next (C:\Users\RayTaylor\Documents\Github\raytaylorlin.github.io\node_modules\connect\index.js:183:5)
   at logger (C:\Users\RayTaylor\Documents\Github\raytaylorlin.github.io\node_modules\morgan\index.js:144:5)
   at call (C:\Users\RayTaylor\Documents\Github\raytaylorlin.github.io\node_modules\connect\index.js:239:7)
   at next (C:\Users\RayTaylor\Documents\Github\raytaylorlin.github.io\node_modules\connect\index.js:183:5)
   at compression (C:\Users\RayTaylor\Documents\Github\raytaylorlin.github.io\node_modules\compression\index.js:218:5)
   at call (C:\Users\RayTaylor\Documents\Github\raytaylorlin.github.io\node_modules\connect\index.js:239:7)
   at next (C:\Users\RayTaylor\Documents\Github\raytaylorlin.github.io\node_modules\connect\index.js:183:5)
   at C:\Users\RayTaylor\Documents\Github\raytaylorlin.github.io\node_modules\hexo-server\lib\middlewares\header.js:6:5
   at call (C:\Users\RayTaylor\Documents\Github\raytaylorlin.github.io\node_modules\connect\index.js:239:7)
   at next (C:\Users\RayTaylor\Documents\Github\raytaylorlin.github.io\node_modules\connect\index.js:183:5)
   at Function.handle (C:\Users\RayTaylor\Documents\Github\raytaylorlin.github.io\node_modules\connect\index.js:186:3)
   at Server.app (C:\Users\RayTaylor\Documents\Github\raytaylorlin.github.io\node_modules\connect\index.js:51:37)
   at emitTwo (events.js:100:13)
   at Server.emit (events.js:185:7)
   at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:537:12)
   at HTTPParser.parserOnHeadersComplete (_http_common.js:89:23)
```

`hexo version`显示如下：

```
hexo: 3.1.1
os: Windows_NT 10.0.10240 win32 x64
http_parser: 2.6.1
node: 5.6.0
v8: 4.6.85.31
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2f
```

**Comment by raytaylorlin** [comment]
突然发现`http://localhost:4000/categories/日常`会报错，但是`http://localhost:4000/categories/日常/`就没问题，后者多一个`/`

**Comment by Xuanwo** [comment]
线上环境有问题么？我怀疑可能是hexo-server的问题。

**Comment by Xuanwo** [comment]
在线上没有问题，测试链接：
https://xuanwo.org/hexo-issue-test/categories/测试/
https://xuanwo.org/hexo-issue-test/categories/测试

在使用hexo-server的时候确实出现了此问题，报错信息：
```
TypeError: The header content contains invalid characters
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:348:11)
    at /media/Data/Code/hexo-issue-test/node_modules/hexo-server/lib/middlewares/route.js:27:11
    at call (/media/Data/Code/hexo-issue-test/node_modules/connect/index.js:239:7)
    at next (/media/Data/Code/hexo-issue-test/node_modules/connect/index.js:183:5)
    at compression (/media/Data/Code/hexo-issue-test/node_modules/compression/index.js:218:5)
    at call (/media/Data/Code/hexo-issue-test/node_modules/connect/index.js:239:7)
    at next (/media/Data/Code/hexo-issue-test/node_modules/connect/index.js:183:5)
    at /media/Data/Code/hexo-issue-test/node_modules/hexo-server/lib/middlewares/header.js:6:5
    at call (/media/Data/Code/hexo-issue-test/node_modules/connect/index.js:239:7)
    at next (/media/Data/Code/hexo-issue-test/node_modules/connect/index.js:183:5)
    at Function.handle (/media/Data/Code/hexo-issue-test/node_modules/connect/index.js:186:3)
    at Server.app (/media/Data/Code/hexo-issue-test/node_modules/connect/index.js:51:37)
    at emitTwo (events.js:100:13)
    at Server.emit (events.js:185:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:537:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
```

**Comment by leesei** [comment]
一定要中文才触發嗎?

**Comment by Arondight** [comment]
英文不会触发此BUG

**Comment by yaochiqkl** [comment]
Try this:
`npm install http-server -D -g `
`npm install http-server -D`
More info in PR: [#311](https://github.com/angular/angular-phonecat/pull/311)

**Comment by leesei** [comment]
But we're using https://www.npmjs.com/package/serve-static
Maybe it has the same bug?

Can someone help produce a test case?

**Comment by xiaotian044500** [comment]
中文路径传入setHeader时报的错, 我也遇到了. 通过encodeURI暂时解决了.

**Comment by stevenjoezhang** [comment]
未在最新版本的 Hexo 中复现
