### ISSUE TITLE
hexo migrate wordpress blog.xml: FATAL can not read a block mapping entry

### ISSUE THREAD

**Issue by iMilnb** [hexojs/hexo#1753]
Hi,

I'm trying to import my current _wordpress_ blog to _hexo_. When processing the exported `xml` file I get the following:
```
FATAL can not read a block mapping entry; a multiline key may not be an implicit key at line 2, column 5:
    date: 2008-07-25 23:54:33
        ^
```
I tried removing this entry, and I would get the same error on the next one.
Here's the full debug entry:
```
YAMLException: can not read a block mapping entry; a multiline key may not be an
 implicit key at line 2, column 5:
    date: 2008-07-25 23:54:33
        ^
    at generateError (/home/imilnet/www/public/blog/node_modules/hexo/node_modul
es/js-yaml/lib/js-yaml/loader.js:162:10)
    at throwError (/home/imilnet/www/public/blog/node_modules/hexo/node_modules/
js-yaml/lib/js-yaml/loader.js:168:9)
    at readBlockMapping (/home/imilnet/www/public/blog/node_modules/hexo/node_mo
dules/js-yaml/lib/js-yaml/loader.js:1040:9)
    at composeNode (/home/imilnet/www/public/blog/node_modules/hexo/node_modules
/js-yaml/lib/js-yaml/loader.js:1326:12)
    at readDocument (/home/imilnet/www/public/blog/node_modules/hexo/node_module
s/js-yaml/lib/js-yaml/loader.js:1488:3)
    at loadDocuments (/home/imilnet/www/public/blog/node_modules/hexo/node_modul
es/js-yaml/lib/js-yaml/loader.js:1544:5)
    at Object.load (/home/imilnet/www/public/blog/node_modules/hexo/node_modules
/js-yaml/lib/js-yaml/loader.js:1561:19)
    at /home/imilnet/www/public/blog/node_modules/hexo/lib/hexo/post.js:79:23
    at tryCatcher (/home/imilnet/www/public/blog/node_modules/hexo/node_modules/
bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/imilnet/www/public/blog/node_mod
ules/hexo/node_modules/bluebird/js/main/promise.js:505:31)
    at Promise._settlePromiseAt (/home/imilnet/www/public/blog/node_modules/hexo
/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/home/imilnet/www/public/blog/node_modules/hexo/
node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/home/imilnet/www/public/blog/node_modules/hexo/node_m
odules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/imilnet/www/public/blog/node_modules/hexo/node_
modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/imilnet/www/public/b
log/node_modules/hexo/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
FATAL can not read a block mapping entry; a multiline key may not be an implicit
 key at line 2, column 5:
    date: 2008-07-25 23:54:33
        ^
YAMLException: can not read a block mapping entry; a multiline key may not be an
 implicit key at line 2, column 5:
    date: 2008-07-25 23:54:33
        ^
    at generateError (/home/imilnet/www/public/blog/node_modules/hexo/node_modul
es/js-yaml/lib/js-yaml/loader.js:162:10)
    at throwError (/home/imilnet/www/public/blog/node_modules/hexo/node_modules/
js-yaml/lib/js-yaml/loader.js:168:9)
    at readBlockMapping (/home/imilnet/www/public/blog/node_modules/hexo/node_mo
dules/js-yaml/lib/js-yaml/loader.js:1040:9)
    at composeNode (/home/imilnet/www/public/blog/node_modules/hexo/node_modules
/js-yaml/lib/js-yaml/loader.js:1326:12)
    at readDocument (/home/imilnet/www/public/blog/node_modules/hexo/node_module
s/js-yaml/lib/js-yaml/loader.js:1488:3)
    at loadDocuments (/home/imilnet/www/public/blog/node_modules/hexo/node_modul
es/js-yaml/lib/$ 
```

Any hint on how to help debugging this issue further?

**Comment by iMilnb** [comment]
Well it seems `js-yaml` is unhappy with titles containing `&quot;` and friends... more like a `js-yaml` issue anyway. Closing.

**Comment by iMilnb** [comment]
Simple fix:

```
perl -pi -e 's,<title>(.*)</title>,<title><![CDATA[$1]]></title>,' my-wp-blog-export.xml
```

**Comment by HelloLadsAndGents** [comment]
my solution is to add space in this file:**_config.yml**,
because i change this file by my own , and i did't notice the space between label and value 
SO,this is my problem

**Comment by warrenwx** [comment]
Here is my _config.yml

**Comment by YoshinoriN** [comment]
@warrenwx 
Would you please write comment to #3445?
