### ISSUE TITLE
Markdown parser can't render this embeded code

### ISSUE THREAD

**Issue by bakyeono** [hexojs/hexo#1757]
### a-post.markdown

    ---
    layout: post
    title: a post
    ---
    
    These are syntax sugars to count elements in array in bash.
    
    sugar 1
    
        ${#arr[*]}
    
    sugar 2
    
        ${#arr[@]}

When I `hexo generate` this markdown, hexo dies. `${#arr[*]}` and `${#arr[@]}` cause problem.

### Environment

* Raspberry PI 2 B + (ARM)
* Raspbian JESSIE 2016-02-09 (Linux 4.1.17-v7+ linux arm)
* node: 4.3.0
* hexo: 3.1.1
* http_parser: 2.5.1
* v8: 4.5.103.35
* uv: 1.8.0
* zlib: 1.2.8
* ares: 1.10.1-DEV
* icu: 56.1
* modules: 46
* openssl: 1.0.2f

### Error Log

    bakyeono@antares-pi:~/project/hexotest $ hexo generate
    FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
    Error: expected end of comment, got end of file
        at Tokenizer.nextToken (/home/bakyeono/project/hexotest/node_modules/hexo/node_modules/nunjucks/src/lexer.js:282:23)
        at Object.extend.nextToken (/home/bakyeono/project/hexotest/node_modules/hexo/node_modules/nunjucks/src/parser.js:32:27)
        at Object.extend.peekToken (/home/bakyeono/project/hexotest/node_modules/hexo/node_modules/nunjucks/src/parser.js:44:43)
        at Object.extend.parseNodes (/home/bakyeono/project/hexotest/node_modules/hexo/node_modules/nunjucks/src/parser.js:1124:38)
        at Object.extend.parseAsRoot (/home/bakyeono/project/hexotest/node_modules/hexo/node_modules/nunjucks/src/parser.js:1177:42)
        at Object.module.exports.parse (/home/bakyeono/project/hexotest/node_modules/hexo/node_modules/nunjucks/src/parser.js:1199:18)
        at Object.module.exports.compile (/home/bakyeono/project/hexotest/node_modules/hexo/node_modules/nunjucks/src/compiler.js:1118:48)
        at Obj.extend._compile (/home/bakyeono/project/hexotest/node_modules/hexo/node_modules/nunjucks/src/environment.js:444:35)
        at Obj.extend.compile (/home/bakyeono/project/hexotest/node_modules/hexo/node_modules/nunjucks/src/environment.js:433:18)
        at null.<anonymous> (/home/bakyeono/project/hexotest/node_modules/hexo/node_modules/nunjucks/src/environment.js:378:22)
        at Object.exports.withPrettyErrors (/home/bakyeono/project/hexotest/node_modules/hexo/node_modules/nunjucks/src/lib.js:24:16)
        at Obj.extend.render (/home/bakyeono/project/hexotest/node_modules/hexo/node_modules/nunjucks/src/environment.js:374:20)
        at Obj.extend.renderString (/home/bakyeono/project/hexotest/node_modules/hexo/node_modules/nunjucks/src/environment.js:261:21)
        at /home/bakyeono/project/hexotest/node_modules/hexo/lib/extend/tag.js:56:9
        at tryCatcher (/home/bakyeono/project/hexotest/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
        at Promise._resolveFromResolver (/home/bakyeono/project/hexotest/node_modules/hexo/node_modules/bluebird/js/main/promise.js:480:31)
        at new Promise (/home/bakyeono/project/hexotest/node_modules/hexo/node_modules/bluebird/js/main/promise.js:70:37)
        at Tag.render (/home/bakyeono/project/hexotest/node_modules/hexo/lib/extend/tag.js:55:10)
        at Object.tagFilter [as onRenderEnd] (/home/bakyeono/project/hexotest/node_modules/hexo/lib/hexo/post.js:253:16)
        at /home/bakyeono/project/hexotest/node_modules/hexo/lib/hexo/render.js:55:19
        at tryCatcher (/home/bakyeono/project/hexotest/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
        at Promise._settlePromiseFromHandler (/home/bakyeono/project/hexotest/node_modules/hexo/node_modules/bluebird/js/main/promise.js:507:31)
        at Promise._settlePromiseAt (/home/bakyeono/project/hexotest/node_modules/hexo/node_modules/bluebird/js/main/promise.js:581:18)
        at Promise._settlePromises (/home/bakyeono/project/hexotest/node_modules/hexo/node_modules/bluebird/js/main/promise.js:697:14)
        at Async._drainQueue (/home/bakyeono/project/hexotest/node_modules/hexo/node_modules/bluebird/js/main/async.js:123:16)
        at Async._drainQueues (/home/bakyeono/project/hexotest/node_modules/hexo/node_modules/bluebird/js/main/async.js:133:10)
        at Immediate.Async.drainQueues [as _onImmediate] (/home/bakyeono/project/hexotest/node_modules/hexo/node_modules/bluebird/js/main/async.js:15:14)
        at processImmediate [as _immediateCallback] (timers.js:383:17)

When I remove those two bash code lines from the post, it generates fine. Looks like markdown parser problem to me.

**Comment by greg-js** [comment]
I just quickly tested this and I get the same error on `hexo 3.1.0` but it renders and generates fine for me on `hexo 3.2.0-beta.2` so I assume the issue was fixed in the beta.

**Comment by leesei** [comment]
With 3.1.1 I can render them with backtick syntax:

    sugar 1
    
    ```
    ${#arr[*]}
    ```
    
    sugar 2
    
    ```
    ${#arr[@]}
    ```
