### ISSUE TITLE
Install ERROR

### ISSUE THREAD

**Issue by shenlw66** [hexojs/hexo#1760]
```
➜ npm install hexo-cli -g
npm http GET http://registry.cnpmjs.org/hexo-cli
npm http 304 http://registry.cnpmjs.org/hexo-cli
npm http GET http://registry.cnpmjs.org/chalk
npm http GET http://registry.cnpmjs.org/hexo-fs
npm http GET http://registry.cnpmjs.org/hexo-util
npm http GET http://registry.cnpmjs.org/bluebird
npm http GET http://registry.cnpmjs.org/minimist
npm http GET http://registry.cnpmjs.org/tildify
npm http GET http://registry.cnpmjs.org/abbrev
npm http GET http://registry.cnpmjs.org/hexo-log
npm http GET http://registry.cnpmjs.org/object-assign
npm http 304 http://registry.cnpmjs.org/minimist
npm ERR! Error: No compatible version found: minimist@'^1.2.0'
npm ERR! Valid install targets:
npm ERR! ["1.2.0","1.1.3","1.1.2","1.1.1","1.1.0","1.0.0","0.2.0","0.1.0","0.0.10","0.0.9","0.0.8","0.0.7","0.0.6","0.0.5","0.0.4","0.0.3","0.0.2","0.0.1","0.0.0"]
npm ERR!     at installTargetsError (/Users/lingweishen/.nvm/v0.8.14/lib/node_modules/npm/lib/cache.js:563:10)
npm ERR!     at /Users/lingweishen/.nvm/v0.8.14/lib/node_modules/npm/lib/cache.js:478:10
npm ERR!     at saved (/Users/lingweishen/.nvm/v0.8.14/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at /Users/lingweishen/.nvm/v0.8.14/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:218:7
npm ERR!     at Object.oncomplete (fs.js:297:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 15.3.0
npm ERR! command "/Users/lingweishen/.nvm/v0.8.14/bin/node" "/Users/lingweishen/.nvm/v0.8.14/bin/npm" "install" "hexo-cli" "-g"
npm ERR! cwd /Users/lingweishen/Documents/hexo
npm ERR! node -v v0.8.14
npm ERR! npm -v 1.1.65
npm http 304 http://registry.cnpmjs.org/tildify
npm http 304 http://registry.cnpmjs.org/hexo-util
npm http 304 http://registry.cnpmjs.org/hexo-fs
npm http 304 http://registry.cnpmjs.org/bluebird
npm http 304 http://registry.cnpmjs.org/chalk
npm http 304 http://registry.cnpmjs.org/hexo-log
npm http 304 http://registry.cnpmjs.org/object-assign
npm http 304 http://registry.cnpmjs.org/abbrev
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/lingweishen/Documents/hexo/npm-debug.log
npm ERR! not ok code 0
```

**Comment by Xuanwo** [comment]
升级你的node版本，Hexo已经不再支持0.8了

**Comment by shenlw66** [comment]
装好之后还是不太正常
hexo -v
{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
Native thread-sleep not available.
This will result in much slower performance, but it will still work.
You should re-install spawn-sync or upgrade to the lastest version of node if possible.
Check /Users/lingweishen/.nvm/v0.10.26/lib/node_modules/hexo-cli/node_modules/hexo-util/node_modules/cross-spawn/node_modules/spawn-sync/error.log for more details
{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
Native thread-sleep not available.
This will result in much slower performance, but it will still work.
You should re-install spawn-sync or upgrade to the lastest version of node if possible.
Check /Users/lingweishen/Documents/hexo/node_modules/hexo-renderer-marked/node_modules/hexo-util/node_modules/cross-spawn/node_modules/spawn-sync/error.log for more details
ERROR Plugin load failed: hexo-server
Error: Cannot find module 'accepts'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/lingweishen/Documents/hexo/node_modules/hexo-server/node_modules/compression/index.js:17:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/lingweishen/Documents/hexo/node_modules/hexo-server/lib/middlewares/gzip.js:3:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (/Users/lingweishen/Documents/hexo/node_modules/hexo/lib/hexo/index.js:213:21)
    at /Users/lingweishen/Documents/hexo/node_modules/hexo-server/index.js:24:50
    at /Users/lingweishen/Documents/hexo/node_modules/hexo/lib/hexo/index.js:229:12
    at tryCatcher (/Users/lingweishen/Documents/hexo/node_modules/hexo/node_modules/hexo-fs/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/lingweishen/Documents/hexo/node_modules/hexo/node_modules/hexo-fs/node_modules/bluebird/js/release/promise.js:497:31)
    at Promise._settlePromise (/Users/lingweishen/Documents/hexo/node_modules/hexo/node_modules/hexo-fs/node_modules/bluebird/js/release/promise.js:555:18)
    at Promise._settlePromise0 (/Users/lingweishen/Documents/hexo/node_modules/hexo/node_modules/hexo-fs/node_modules/bluebird/js/release/promise.js:600:10)
    at Promise._settlePromises (/Users/lingweishen/Documents/hexo/node_modules/hexo/node_modules/hexo-fs/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/Users/lingweishen/Documents/hexo/node_modules/hexo/node_modules/hexo-fs/node_modules/bluebird/js/release/promise.js:624:18)
    at Promise._resolveCallback (/Users/lingweishen/Documents/hexo/node_modules/hexo/node_modules/hexo-fs/node_modules/bluebird/js/release/promise.js:424:57)
    at Promise._settlePromiseFromHandler (/Users/lingweishen/Documents/hexo/node_modules/hexo/node_modules/hexo-fs/node_modules/bluebird/js/release/promise.js:510:17)
    at Promise._settlePromise (/Users/lingweishen/Documents/hexo/node_modules/hexo/node_modules/hexo-fs/node_modules/bluebird/js/release/promise.js:555:18)
    at Promise._settlePromise0 (/Users/lingweishen/Documents/hexo/node_modules/hexo/node_modules/hexo-fs/node_modules/bluebird/js/release/promise.js:600:10)
    at Promise._settlePromises (/Users/lingweishen/Documents/hexo/node_modules/hexo/node_modules/hexo-fs/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/Users/lingweishen/Documents/hexo/node_modules/hexo/node_modules/hexo-fs/node_modules/bluebird/js/release/promise.js:624:18)
    at /Users/lingweishen/Documents/hexo/node_modules/hexo/node_modules/hexo-fs/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/lingweishen/Documents/hexo/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:78:16
    at fs.js:266:14
    at /Users/lingweishen/Documents/hexo/node_modules/hexo/node_modules/nunjucks/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:104:5
    at /Users/lingweishen/Documents/hexo/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:43:10
    at /Users/lingweishen/Documents/hexo/node_modules/hexo/node_modules/warehouse/node_modules/graceful-fs/graceful-fs.js:43:10
    at /Users/lingweishen/.nvm/v0.10.26/lib/node_modules/hexo-cli/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:43:10
    at Object.oncomplete (fs.js:107:15)
Usage: hexo <command>

Commands:
  clean     Removed generated files and cache.
  config    Get or set configurations.
  deploy    Deploy your website.
  generate  Generate static files.
  help      Get help on a command.
  init      Create a new Hexo folder.
  list      List the information of the site
  migrate   Migrate your site from other system to Hexo.
  new       Create a new post.
  publish   Moves a draft post from _drafts to _posts folder.
  render    Render files with renderer plugins.
  server    Start the server.
  version   Display version information.

Global Options:
  --config  Specify config file instead of using _config.yml
  --cwd     Specify the CWD
  --debug   Display all verbose messages in the terminal
  --draft   Display draft posts
  --safe    Disable all plugins and scripts
  --silent  Hide output on console

For more help, you can use 'hexo help [command]' for the detailed information
or you can check the docs: http://hexo.io/docs/

**Comment by Xuanwo** [comment]
Hexo 和 hexo-server执行代码测试的最低版本已经是0.12了。
如果条件限制实在不能升级的话，建议使用3.1.1及以下版本。

**Comment by shenlw66** [comment]
Thx~ 可能是别人的教程写的有些久远了，现在已经更新到4.3.1了，虽然还是有些报错，但已经可以用了
```{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }```

**Comment by Xuanwo** [comment]
Closed for sloved.
