### ISSUE TITLE
Memory usage when generating large site

### ISSUE THREAD

**Issue by leesei** [hexojs/hexo#1763]
https://github.com/hexojs/hexo/issues/1735
https://github.com/hexojs/hexo/issues/1529

I'll try to recreate the environment first.

**Comment by leesei** [comment]
Generate stub files with [leesei/hexo-genstubs](https://github.com/leesei/hexo-genstubs).

With `genstubs.js -N 5000 -P 100`:
```
229M    source/_posts
128M    stub-posts.zip
```

This is enough to generate OOM on my Arch Linux with 8G RAM.
The Hexo site is generated by `hexo init`.

```
hexo-cli@0.1.9
hexo@3.1.1
hexo-generator-archive@0.1.4
hexo-generator-category@0.1.3
hexo-generator-index@0.2.0
hexo-generator-tag@0.2.0
hexo-renderer-ejs@0.1.1
hexo-renderer-marked@0.2.10
hexo-renderer-stylus@0.3.1
hexo-server@0.1.3
```

```sh
$ hexo generate

<--- Last few GCs --->

    7958 ms: Scavenge 1408.7 (1457.0) -> 1408.7 (1457.0) MB, 17.1 / 0 ms (+ 33.0 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
    8984 ms: Mark-sweep 1408.7 (1457.0) -> 1405.9 (1454.0) MB, 1026.3 / 0 ms (+ 967.1 ms in 2405 steps since start of marking, biggest step 33.0 ms) [last resort gc].
   10009 ms: Mark-sweep 1405.9 (1454.0) -> 1405.8 (1457.0) MB, 1024.3 / 0 ms [last resort gc].

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
```

**Comment by tommy351** [comment]
Thanks for the test. :100: :+1:

**Comment by xieguigang** [comment]
My site have over 8000 pages, and encounter this problem too:
```
$ hexo generate
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: (unknown path) [Line 4, Column 929]
  expected variable end
    at Object.exports.prettifyError (D:\gcmodeller-hexo\docs\node_modules\nunjucks\src\lib.js:34:15)
    at Obj.extend.render (D:\gcmodeller-hexo\docs\node_modules\nunjucks\src\environment.js:468:27)
    at Obj.extend.renderString (D:\gcmodeller-hexo\docs\node_modules\nunjucks\src\environment.js:326:21)
    at D:\gcmodeller-hexo\docs\node_modules\hexo\lib\extend\tag.js:66:9
    at Promise._execute (D:\gcmodeller-hexo\docs\node_modules\bluebird\js\release\debuggability.js:272:9)
    at Promise._resolveFromExecutor (D:\gcmodeller-hexo\docs\node_modules\bluebird\js\release\promise.js:473:18)
    at new Promise (D:\gcmodeller-hexo\docs\node_modules\bluebird\js\release\promise.js:77:14)
    at Tag.render (D:\gcmodeller-hexo\docs\node_modules\hexo\lib\extend\tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (D:\gcmodeller-hexo\docs\node_modules\hexo\lib\hexo\post.js:253:16)
    at D:\gcmodeller-hexo\docs\node_modules\hexo\lib\hexo\render.js:63:19
    at tryCatcher (D:\gcmodeller-hexo\docs\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\gcmodeller-hexo\docs\node_modules\bluebird\js\release\promise.js:502:31)
    at Promise._settlePromise (D:\gcmodeller-hexo\docs\node_modules\bluebird\js\release\promise.js:559:18)
    at Promise._settlePromise0 (D:\gcmodeller-hexo\docs\node_modules\bluebird\js\release\promise.js:604:10)
    at Promise._settlePromises (D:\gcmodeller-hexo\docs\node_modules\bluebird\js\release\promise.js:683:18)
    at Async._drainQueue (D:\gcmodeller-hexo\docs\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (D:\gcmodeller-hexo\docs\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\gcmodeller-hexo\docs\node_modules\bluebird\js\release\async.js:17:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
FATAL (unknown path) [Line 4, Column 929]
  expected variable end
Template render error: (unknown path) [Line 4, Column 929]
  expected variable end
    at Object.exports.prettifyError (D:\gcmodeller-hexo\docs\node_modules\nunjucks\src\lib.js:34:15)
    at Obj.extend.render (D:\gcmodeller-hexo\docs\node_modules\nunjucks\src\environment.js:468:27)
    at Obj.extend.renderString (D:\gcmodeller-hexo\docs\node_modules\nunjucks\src\environment.js:326:21)
    at D:\gcmodeller-hexo\docs\node_modules\hexo\lib\extend\tag.js:66:9
    at Promise._execute (D:\gcmodeller-hexo\docs\node_modules\bluebird\js\release\debuggability.js:272:9)
    at Promise._resolveFromExecutor (D:\gcmodeller-hexo\docs\node_modules\bluebird\js\release\promise.js:473:18)
    at new Promise (D:\gcmodeller-hexo\docs\node_modules\bluebird\js\release\promise.js:77:14)
    at Tag.render (D:\gcmodeller-hexo\docs\node_modules\hexo\lib\extend\tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (D:\gcmodeller-hexo\docs\node_modules\hexo\lib\hexo\post.js:253:16)
    at D:\gcmodeller-hexo\docs\node_modules\hexo\lib\hexo\render.js:63:19
    at tryCatcher (D:\gcmodeller-hexo\docs\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\gcmodeller-hexo\docs\node_modules\bluebird\js\release\promise.js:502:31)
    at Promise._settlePromise (D:\gcmodeller-hexo\docs\node_modules\bluebird\js\release\promise.js:559:18)
    at Promise._settlePromise0 (D:\gcmodeller-hexo\docs\node_modules\bluebird\js\release\promise.js:604:10)
    at Promise._settlePromises (D:\gcmodeller-hexo\docs\node_modules\bluebird\js\release\promise.js:683:18)
    at Async._drainQueue (D:\gcmodeller-hexo\docs\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (D:\gcmodeller-hexo\docs\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\gcmodeller-hexo\docs\node_modules\bluebird\js\release\async.js:17:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```

**Comment by leesei** [comment]
@xieguigang Refer to #1771 to help you debug "Template render error".

**Comment by stevenjoezhang** [comment]
Closing due to https://github.com/hexojs/hexo/pull/3756
