### ISSUE TITLE
Disable highlight results in  "Template render error."

### ISSUE THREAD

**Issue by liuzc** [hexojs/hexo#1777]
When I disable `highlight` in `_config.yml`.  A template render error occurred. But I want to use use google prettify highlight code, So I must need disable highlight.

```
highlight:
  enable: false
  line_number: false
  auto_detect: false
  tab_replace:
```
```
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: Error: Unable to call `is_post`, which is undefined or falsey
    at Object.callWrap (/Users/LiuZhichao/Blog/node_modules/nunjucks/src/runtime.js:223:15)
    at root [as rootRenderFunc] (eval at <anonymous> (/Users/LiuZhichao/Blog/node_modules/nunjucks/src/environment.js:450:24), <anonymous>:8:38)
    at null.<anonymous> (/Users/LiuZhichao/Blog/node_modules/nunjucks/src/environment.js:387:18)
    at Object.exports.withPrettyErrors (/Users/LiuZhichao/Blog/node_modules/nunjucks/src/lib.js:24:16)
    at Obj.extend.render (/Users/LiuZhichao/Blog/node_modules/nunjucks/src/environment.js:374:20)
    at Obj.extend.renderString (/Users/LiuZhichao/Blog/node_modules/nunjucks/src/environment.js:261:21)
    at /Users/LiuZhichao/Blog/node_modules/hexo/lib/extend/tag.js:56:9
    at tryCatcher (/Users/LiuZhichao/Blog/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/Users/LiuZhichao/Blog/node_modules/bluebird/js/main/promise.js:480:31)
    at new Promise (/Users/LiuZhichao/Blog/node_modules/bluebird/js/main/promise.js:70:37)
    at Tag.render (/Users/LiuZhichao/Blog/node_modules/hexo/lib/extend/tag.js:55:10)
    at Object.tagFilter [as onRenderEnd] (/Users/LiuZhichao/Blog/node_modules/hexo/lib/hexo/post.js:253:16)
    at /Users/LiuZhichao/Blog/node_modules/hexo/lib/hexo/render.js:55:19
    at tryCatcher (/Users/LiuZhichao/Blog/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/LiuZhichao/Blog/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/LiuZhichao/Blog/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/Users/LiuZhichao/Blog/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/Users/LiuZhichao/Blog/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/LiuZhichao/Blog/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/LiuZhichao/Blog/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by Xuanwo** [comment]
I'll build a environment for this issue, wait for a moment.

**Comment by liuzc** [comment]
I can disable this option before.But today I init a new blog,when I change highlight enable value to false, the error occurred. It may not be compatible with a plug-in or module? I'm not sure.

My plug-in list:
```
  "dependencies": {
    "hexo": "^3.1.0",
    "hexo-autonofollow": "0.0.1",
    "hexo-clean-css": "0.0.2",
    "hexo-deployer-git": "0.0.4",
    "hexo-generator-archive": "^0.1.2",
    "hexo-generator-baidu-sitemap": "^0.1.2",
    "hexo-generator-category": "^0.1.2",
    "hexo-generator-feed": "^1.0.3",
    "hexo-generator-index": "^0.1.2",
    "hexo-generator-sitemap": "^1.0.1",
    "hexo-generator-tag": "^0.1.1",
    "hexo-html-minifier": "0.0.1",
    "hexo-renderer-ejs": "^0.1.0",
    "hexo-renderer-marked": "^0.2.4",
    "hexo-renderer-stylus": "^0.3.0",
    "hexo-server": "^0.1.2",
    "hexo-uglify": "0.0.3"
  }
```
$hexo -v:
```
hexo: 3.1.1
os: Darwin 15.3.0 darwin x64
http_parser: 2.6.2
node: 5.7.0
v8: 4.6.85.31
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2f
```

**Comment by Xuanwo** [comment]
It looks OK: https://xuanwo.org/hexo-issue-test/2016/02/25/1777/
And you can see config here: https://github.com/Xuanwo/hexo-issue-test/blob/master/_config.yml#L40-L44

**Comment by liuzc** [comment]
Could you please use this theme <https://github.com/liuzc/hexo-theme-read> test again. Thx.

**Comment by Xuanwo** [comment]
The theme works well on my environment.
I have noticed that my `hexo-renderer-marked` is newer than you , may be you can update your dep to have a try.

**Comment by liuzc** [comment]
Thank you very much. I will test it again.
You can close this issues now. Thank you again.

**Comment by Xuanwo** [comment]
Issue will be closed when sloved, so don't care about this. If closed too early, I will forget about this issue, :laughing:

**Comment by liuzc** [comment]
I find the cause of this problem.just because the following fields included in my article:
```
     {% if is_post() %}
     {% include '../_partials/reward.swig' %}
     {% endif %}
```
you can create a new post, then copy [this content](https://raw.githubusercontent.com/liuzc/hexo-theme-read/master/README.md) to your post. then type `hexo s` in your console,you will see this error.

**Comment by Xuanwo** [comment]
Well, I got it. We can't use `{%` and `%}` in article content because nunjucks will treat them as template.
You can try to use `{% raw %}` and `{% endraw %}` to include them or use escape.

**Comment by leesei** [comment]
Put content in [backticks](https://hexo.io/docs/tag-plugins.html#Backtick-Code-Block), [codeblock](https://hexo.io/docs/tag-plugins.html#Code-Block) or [raw](https://hexo.io/docs/tag-plugins.html#Raw) tags to bypass Nunjucks parsing issue.
https://hexo.io/docs/troubleshooting.html#Escape_Contents
See #1510 for discussion of disabling Nunjucks.

**Comment by noraj1337** [comment]
@leesei using backtics, codeblock or raw doesn't helped in my case https://github.com/hexojs/hexo/issues/1510#issuecomment-328591242

**Comment by think-in-universe** [comment]
@leesei hello, so if we want to disable the `nunjucks` globally or with post-specific settings (e.g. front matter), how could a hexo user achieve that?

**Comment by leesei** [comment]
I believe `nunjucks` is used for tag plugins so it's a core part of Hexo.
See discussion in #1510 and [this PR](https://github.com/hexojs/hexo/pull/2593).

**Comment by think-in-universe** [comment]
@leesei thanks. I have read that issue and PR, but my use case would prefer ignore nunjucks syntax, and only keep the markdown syntax. 

So if we want to disable tag plugins and `nunjucks` the only available solution at this moment is to create a new renderer that set the option `disableNunjucks`, right? 

Do you have any relatively complete examples of creating a renderer?

**Comment by leesei** [comment]
I believe so.

You can start from one of the existing Markdown renderers: https://hexo.io/plugins/

**Comment by think-in-universe** [comment]
@leesei thanks the suggestion. I'll take a look. 👍

**Comment by think-in-universe** [comment]
@leesei 

one hexo plugin [hexo-stop-tag-plugins](https://www.npmjs.com/package/hexo-stop-tag-plugins) has been created to disable tag-plugins for markdown renderers (hexo plugin PR: https://github.com/hexojs/site/pull/966) 

The logic of `disableNunjucks` contains issues according to my test in [hexo-stop-tag-plugins/test](https://github.com/think-in-universe/hexo-stop-tag-plugins/blob/master/test/index.js). One PR has been submitted https://github.com/hexojs/hexo/pull/3573 to fix that.
