### ISSUE TITLE
Cannot read property 'each' of undefined

### ISSUE THREAD

**Issue by imbyron** [hexojs/hexo#1785]
hexo g的时候报错提示：·Cannot read property 'each' of undefined·
这个不知是啥问题。

**Comment by leesei** [comment]
Hexo 版本
之前成功過嗎?

**Comment by imbyron** [comment]
@leesei 之前是好的，但是我很久没用hexo了。
版本是最新的，刚刚安装的。

**Comment by leesei** [comment]
放`hexo g --debug` 的log 上來看看

**Comment by imbyron** [comment]
@leesei 

Unhandled rejection TypeError: F:\MyNuts\Byron\blog\themes\landscape\layout\category.ejs:1
 >> 1| <%- partial('_partial/archive', {pagination: config.category, index: true}) %>

F:\MyNuts\Byron\blog\themes\landscape\layout\_partial\archive.ejs:2
    1| <% if (pagination == 2){ %>
 >> 2|   <% page.posts.each(function(post){ %>
    3|     <%- partial('article', {post: post, index: true}) %>
    4|   <% }) %>
    5| <% } else { %>

Cannot read property 'each' of undefined
    at eval (eval at <anonymous> (F:\MyNuts\Byron\blog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:102)
    at eval (eval at <anonymous> (F:\MyNuts\Byron\blog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:33:66)
    at F:\MyNuts\Byron\blog\node_modules\ejs\lib\ejs.js:255:15
    at Object.exports.render (F:\MyNuts\Byron\blog\node_modules\ejs\lib\ejs.js:293:13)
    at Hexo.ejsRenderer (F:\MyNuts\Byron\blog\node_modules\hexo-renderer-ejs\lib\renderer.js:7:14)
    at Render.renderSync (F:\MyNuts\Byron\blog\node_modules\hexo\lib\hexo\render.js:95:23)
    at _compiledSync (F:\MyNuts\Byron\blog\node_modules\hexo\lib\theme\view.js:109:21)
    at View.renderSync (F:\MyNuts\Byron\blog\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (F:\MyNuts\Byron\blog\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper (F:\MyNuts\Byron\blog\node_modules\lodash\lodash.js:4151:19)
    at eval (eval at <anonymous> (F:\MyNuts\Byron\blog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:35)
    at eval (eval at <anonymous> (F:\MyNuts\Byron\blog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:117)
    at F:\MyNuts\Byron\blog\node_modules\ejs\lib\ejs.js:255:15
    at Object.exports.render (F:\MyNuts\Byron\blog\node_modules\ejs\lib\ejs.js:293:13)
    at Hexo.ejsRenderer (F:\MyNuts\Byron\blog\node_modules\hexo-renderer-ejs\lib\renderer.js:7:14)
    at Hexo.tryCatcher (F:\MyNuts\Byron\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (F:\MyNuts\Byron\blog\node_modules\bluebird\js\release\method.js:15:34)
    at F:\MyNuts\Byron\blog\node_modules\hexo\lib\hexo\render.js:59:21
    at tryCatcher (F:\MyNuts\Byron\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (F:\MyNuts\Byron\blog\node_modules\bluebird\js\release\promise.js:503:31)
    at Promise._settlePromise (F:\MyNuts\Byron\blog\node_modules\bluebird\js\release\promise.js:560:18)
    at Promise._settlePromiseCtx (F:\MyNuts\Byron\blog\node_modules\bluebird\js\release\promise.js:597:10)

**Comment by leesei** [comment]
你update landscape 的code 了嗎?
如果你的site很舊的話建議你`hexo init`一個新的再compare 一下

**Comment by imbyron** [comment]
@leesei 我不清楚landspace是不是很久，我init一个blog，landspace就自动到我文件夹了。

**Comment by imbyron** [comment]
@leesei 我的site是新init的。

**Comment by leesei** [comment]
你之前的post 是2.x 成功過?
3.x 對md 內容找的比較緊
https://hexo.io/docs/troubleshooting.html#Escape-Contents

`--debug` 可以看到哪個檔案出問題

**Comment by imbyron** [comment]
@leesei 模板的问题对吧？
2.x都是正常的。
3.x也正常过。

**Comment by leesei** [comment]
其實我懷疑是post 的問題
https://github.com/leesei/hexo-vanilla-site
這也是新近hexo init 出來的

你搬開你的post 能生成嗎?

**Comment by imbyron** [comment]
@leesei 喔，你 怀疑是md格式的原因呀？
我试试看。

**Comment by imbyron** [comment]
@leesei 
奇怪了，下载你的测试文件，我运行不了hexo命令，提示
···
ERROR Local hexo not found in F:\hexo
ERROR Try running: 'npm install hexo --save'
···

Ps：
我刚刚把我post里的md都移除了，新new了一个md文档。
`hexo g`
还是报错。

**Comment by leesei** [comment]
確認你做了這兩步:
1. `npm -g hexo-cli`
2. 在Hexo site folder `npm install`
