### ISSUE TITLE
A generate error with Jinja2 macro code block

### ISSUE THREAD

**Issue by ZhaoLion** [hexojs/hexo#1795]
Help~

I can't  A generate my blog when i wrote a jinja2 marcro block in my blog file (markdown file)

eg. myblog.md with like this
```
5. 支持宏 {% macro render（comment） %}
```
alway crash with those error

```
ERROR Process failed: layout/.DS_Store
TypeError: Cannot read property 'compile' of undefined
    at View._precompile (/Users/zhao/LocalRepositories/myblog/node_modules/hexo/lib/theme/view.js:104:22)
    at View (/Users/zhao/LocalRepositories/myblog/node_modules/hexo/lib/theme/view.js:13:8)
    at new Theme._View.View (/Users/zhao/LocalRepositories/myblog/node_modules/hexo/lib/theme/index.js:37:10)
    at Theme.setView (/Users/zhao/LocalRepositories/myblog/node_modules/hexo/lib/theme/index.js:71:20)
    at /Users/zhao/LocalRepositories/myblog/node_modules/hexo/lib/theme/processors/view.js:14:14
    at tryCatcher (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/promise.js:629:18)
    at Promise._resolveCallback (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/promise.js:424:57)
    at Promise._settlePromiseFromHandler (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/promise.js:515:17)
    at Promise._settlePromise (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/promise.js:629:18)
    at /Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/zhao/LocalRepositories/myblog/node_modules/graceful-fs/graceful-fs.js:78:16
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
ERROR Process failed: layout/_partial/.DS_Store
TypeError: Cannot read property 'compile' of undefined
    at View._precompile (/Users/zhao/LocalRepositories/myblog/node_modules/hexo/lib/theme/view.js:104:22)
    at View (/Users/zhao/LocalRepositories/myblog/node_modules/hexo/lib/theme/view.js:13:8)
    at new Theme._View.View (/Users/zhao/LocalRepositories/myblog/node_modules/hexo/lib/theme/index.js:37:10)
    at Theme.setView (/Users/zhao/LocalRepositories/myblog/node_modules/hexo/lib/theme/index.js:71:20)
    at /Users/zhao/LocalRepositories/myblog/node_modules/hexo/lib/theme/processors/view.js:14:14
    at tryCatcher (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/promise.js:629:18)
    at Promise._resolveCallback (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/promise.js:424:57)
    at Promise._settlePromiseFromHandler (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/promise.js:515:17)
    at Promise._settlePromise (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/promise.js:629:18)
    at /Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/zhao/LocalRepositories/myblog/node_modules/graceful-fs/graceful-fs.js:78:16
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: (unknown path) [Line 10, Column 35]
  expected arguments
    at Object.exports.prettifyError (/Users/zhao/LocalRepositories/myblog/node_modules/nunjucks/src/lib.js:34:15)
    at Obj.extend.render (/Users/zhao/LocalRepositories/myblog/node_modules/nunjucks/src/environment.js:468:27)
    at Obj.extend.renderString (/Users/zhao/LocalRepositories/myblog/node_modules/nunjucks/src/environment.js:326:21)
    at /Users/zhao/LocalRepositories/myblog/node_modules/hexo/lib/extend/tag.js:66:9
    at Promise._execute (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/promise.js:474:18)
    at new Promise (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/promise.js:77:14)
    at Tag.render (/Users/zhao/LocalRepositories/myblog/node_modules/hexo/lib/extend/tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (/Users/zhao/LocalRepositories/myblog/node_modules/hexo/lib/hexo/post.js:253:16)
    at /Users/zhao/LocalRepositories/myblog/node_modules/hexo/lib/hexo/render.js:63:19
    at tryCatcher (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/promise.js:684:18)
    at Async._drainQueue (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/async.js:126:16)
    at Async._drainQueues (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/async.js:136:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
FATAL (unknown path) [Line 10, Column 35]
  expected arguments
Template render error: (unknown path) [Line 10, Column 35]
  expected arguments
    at Object.exports.prettifyError (/Users/zhao/LocalRepositories/myblog/node_modules/nunjucks/src/lib.js:34:15)
    at Obj.extend.render (/Users/zhao/LocalRepositories/myblog/node_modules/nunjucks/src/environment.js:468:27)
    at Obj.extend.renderString (/Users/zhao/LocalRepositories/myblog/node_modules/nunjucks/src/environment.js:326:21)
    at /Users/zhao/LocalRepositories/myblog/node_modules/hexo/lib/extend/tag.js:66:9
    at Promise._execute (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/promise.js:474:18)
    at new Promise (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/promise.js:77:14)
    at Tag.render (/Users/zhao/LocalRepositories/myblog/node_modules/hexo/lib/extend/tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (/Users/zhao/LocalRepositories/myblog/node_modules/hexo/lib/hexo/post.js:253:16)
    at /Users/zhao/LocalRepositories/myblog/node_modules/hexo/lib/hexo/render.js:63:19
    at tryCatcher (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/promise.js:684:18)
    at Async._drainQueue (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/async.js:126:16)
    at Async._drainQueues (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/async.js:136:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/zhao/LocalRepositories/myblog/node_modules/bluebird/js/release/async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by leesei** [comment]
Put content in [backticks](https://hexo.io/docs/tag-plugins.html#Backtick-Code-Block), [codeblock](https://hexo.io/docs/tag-plugins.html#Code-Block) or [raw](https://hexo.io/docs/tag-plugins.html#Raw) tags to bypass Nunjucks parsing issue.
https://hexo.io/docs/troubleshooting.html#Escape_Contents
See #1510 for discussion of disabling Nunjucks.
