### ISSUE TITLE
hexo 部分参数提示未注册

### ISSUE THREAD

**Issue by Arondight** [hexojs/hexo#1796]
一个示例输出如下：

```bash
$ hexo help
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: Console `help` has not been registered yet!
    at /home/ispeller/Repo/arondight.github.io/node_modules/hexo/lib/hexo/index.js:194:14
    at Promise._execute (/home/ispeller/Repo/arondight.github.io/node_modules/hexo/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/home/ispeller/Repo/arondight.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:474:18)
    at new Promise (/home/ispeller/Repo/arondight.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:77:14)
    at Hexo.call (/home/ispeller/Repo/arondight.github.io/node_modules/hexo/lib/hexo/index.js:188:10)
    at runHexoCommand (/usr/lib/node_modules/hexo/node_modules/hexo-cli/lib/index.js:58:17)
    at tryCatcher (/home/ispeller/Repo/arondight.github.io/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ispeller/Repo/arondight.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/home/ispeller/Repo/arondight.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/home/ispeller/Repo/arondight.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/home/ispeller/Repo/arondight.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:684:18)
    at Async._drainQueue (/home/ispeller/Repo/arondight.github.io/node_modules/hexo/node_modules/bluebird/js/release/async.js:126:16)
    at Async._drainQueues (/home/ispeller/Repo/arondight.github.io/node_modules/hexo/node_modules/bluebird/js/release/async.js:136:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/ispeller/Repo/arondight.github.io/node_modules/hexo/node_modules/bluebird/js/release/async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

`packages.json` 如下：

```json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.2.0"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-cli": "^1.0.1",
    "hexo-deployer-git": "0.0.4",
    "hexo-generator-archive": "^0.1.2",
    "hexo-generator-baidu-sitemap": "^0.1.2",
    "hexo-generator-category": "^0.1.2",
    "hexo-generator-feed": "^1.0.3",
    "hexo-generator-index": "^0.1.3",
    "hexo-generator-sitemap": "^1.1.2",
    "hexo-generator-tag": "^0.1.1",
    "hexo-renderer-ejs": "^0.1.1",
    "hexo-renderer-marked": "^0.2.10",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.1.2"
  }
}
```

**Comment by samwhelp** [comment]
## 解決方式

提供一個方向，來解決你提到的這個問題，我是這樣解決的

先離開這個資料夾

``` sh
$ cd ../
```

再執行下面指令，觀察版本

``` sh
$ hexo -v
```

要正常使用「3.2.0」的話，要如下面顯示的
``` 
hexo: 3.2.0
hexo-cli: 1.0.1
...略...
```

看您給的訊息，應該是要使用3.2.0，所以先確認「hexo-cli」的版本是「1.0.1」。

「hexo-cli」若不是「1.0.1」，執行下面的指令更新


``` sh
$ npm install hexo-cli -g
```

另外「hexo-cli」應該是裝在「global」，

所以你的「package.json」裡的「dependencies」應該不需要「`"hexo-cli": "^1.0.1",`」這一行

hexo-cli 裝好後

可以執行下面的指令產生一個專案資料夾

``` sh
$ hexo init blog
```

後續步驟可以參考「[Hexo](https://hexo.io/)」首頁，下方的指令說明。

另外上面安裝的過程，在「3.2.0」我觀察到上面的步驟，應該是 clone 「[hexo-starter](https://github.com/hexojs/hexo-starter)」下來。

所以也可以改用下面的方式。

``` sh
$ git clone https://github.com/hexojs/hexo-starter.git blog
```

以下後續的步驟。

``` sh
$ cd blog
$ rm .git -rf
$ npm install
$ hexo server
```

## 額外一提

以下是 手動確認 global hexo-cli 版本 的指令(在Ubuntu的環境下)

``` sh
$ grep version $(npm root -g)/hexo-cli/package.json
```

應該會看到類似下面的字樣

```
"version": "1.0.1"
```

下面的指令，則是可以知道global模組的路徑

``` sh
$ npm root -g
```

所以可以拿來應用

觀看global模組資料夾

``` sh
$ ls $(npm root -g)
```

切換到global模組資料夾

``` sh
$ cd $(npm root -g)
```

**Comment by Arondight** [comment]
确认到原因了：

1. 本地那个package.json 中的hexo-cli 是我以后加上的
+ 原因是全局hexo-cli 有目录丢失（但是我不知道为什么可以g/s/d 却不能h/v……）

**Comment by fgcui1204** [comment]
@Arondight 遇到了和你同样的问题，想知道你最后是怎么解决的这个问题的呢？

**Comment by aimer1124** [comment]
@fgcui1204 
我的解决方法：
进入到其它目录，执行`npm install hexo-cli -g`，安装成功后，问题就得到解决。希望可以帮到你

**Comment by sunblognuke** [comment]
我在升级3.1.1-》3.2.0的过程中也遇到同样的问题，安装以上方式没有解决，我通过进入另外一个目录下hexo v查看了hexo-cli的版本仍然是0.1.9，可以的确是更新到最新的版本了，因为我在目录C:\Users\zh\AppData\Roaming\npm\node_modules\hexo-cli\package.json的文件内容如下：

```xml
{
  "name": "hexo-cli",
  "version": "1.0.1",
  "description": "Command line interface for Hexo",
  "main": "lib/hexo",
  "bin": {
    "hexo": "./bin/hexo"
  },
  "scripts": {
    "eslint": "eslint .",
    "jscs": "jscs .",
    "test": "mocha test/index.js",
    "test-cov": "istanbul cover --print both _mocha -- test/index.js"
  },
  "directories": {
    "lib": "./lib",
    "bin": "./bin"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/hexojs/hexo-cli.git"
  },
  "homepage": "https://hexo.io/",
  "keywords": [
    "website",
    "blog",
    "cms",
    "framework",
    "hexo",
    "cli"
  ],
  "author": {
    "name": "Tommy Chen",
    "email": "tommy351@gmail.com",
    "url": "http://zespia.tw"
  },
  "license": "MIT",
  "dependencies": {
    "abbrev": "^1.0.7",
    "bluebird": "^3.3.0",
    "chalk": "^1.1.1",
    "hexo-fs": "^0.1.5",
    "hexo-log": "^0.1.1",
    "hexo-util": "^0.5.3",
    "minimist": "^1.2.0",
    "object-assign": "^4.0.1",
    "tildify": "^1.1.2"
  },
  "devDependencies": {
    "chai": "^3.5.0",
    "chai-as-promised": "^5.2.0",
    "eslint": "^1.10.3",
    "eslint-config-hexo": "^1.0.2",
    "hexo-renderer-marked": "^0.2.9",
    "istanbul": "^0.4.2",
    "jscs": "^2.9.0",
    "jscs-preset-hexo": "^1.0.1",
    "mocha": "^2.4.5",
    "proxyquire": "^1.7.4",
    "rewire": "^2.5.1",
    "sinon": "^1.17.3"
  },
  "gitHead": "477c381a33efef1bb1e52ef3c6f4943e46f2d99a",
  "bugs": {
    "url": "https://github.com/hexojs/hexo-cli/issues"
  },
  "_id": "hexo-cli@1.0.1",
  "_shasum": "8bcc28975ebaa636c8d9594868240727aadc734f",
  "_from": "hexo-cli@*",
  "_npmVersion": "3.7.1",
  "_nodeVersion": "4.3.0",
  "_npmUser": {
    "name": "tommy351",
    "email": "tommy351@gmail.com"
  },
  "dist": {
    "shasum": "8bcc28975ebaa636c8d9594868240727aadc734f",
    "tarball": "https://registry.npmjs.org/hexo-cli/-/hexo-cli-1.0.1.tgz"
  },
  "maintainers": [
    {
      "name": "tommy351",
      "email": "tommy351@gmail.com"
    }
  ],
  "_npmOperationalInternal": {
    "host": "packages-6-west.internal.npmjs.com",
    "tmp": "tmp/hexo-cli-1.0.1.tgz_1455272163444_0.3437555329874158"
  },
  "_resolved": "https://registry.npmjs.org/hexo-cli/-/hexo-cli-1.0.1.tgz",
  "readme": "ERROR: No README data found!"
}
```

有其他解决方法么？谢谢

**Comment by aimer1124** [comment]
@sunblognuke 不知道你的问题解决了没，刚查看了下我的hexo版本.如果还不行的话，可以先卸载hexo-cli，重新安装试下

`hexo-cli: 1.0.1
os: Darwin 15.2.0 darwin x64
http_parser: 2.5.2
node: 4.4.3
v8: 4.5.103.35
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2g
`

**Comment by sunblognuke** [comment]
可以尝试一下，如何卸载hexo-cli?

**Comment by aimer1124** [comment]
`npm uninstall hexo-cli` -g

可以参考：[http://stackoverflow.com/questions/13066532/how-to-uninstall-npm-modules-in-node-js](http://stackoverflow.com/questions/13066532/how-to-uninstall-npm-modules-in-node-js)
