### ISSUE TITLE
How to make Hexo ignore a json file?

### ISSUE THREAD

**Issue by kuanyui** [hexojs/hexo#1797]
I need to put a `.json` file at `/my-dir/hello.json`, but after running `hexo`, it return:

```
INFO  Deleted database.
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
SyntaxError: Unexpected token ,
    at Object.parse (native)
    at Hexo.jsonRenderer (/home/kuanyui/source-kuanyui.github.io/node_modules/hexo/lib/plugins/renderer/json.js:4:15)
    at Hexo.tryCatcher (/home/kuanyui/source-kuanyui.github.io/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at Hexo.<anonymous> (/home/kuanyui/source-kuanyui.github.io/node_modules/hexo/node_modules/bluebird/js/main/method.js:15:34)
    at /home/kuanyui/source-kuanyui.github.io/node_modules/hexo/lib/hexo/render.js:51:21
    at tryCatcher (/home/kuanyui/source-kuanyui.github.io/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/kuanyui/source-kuanyui.github.io/node_modules/hexo/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/home/kuanyui/source-kuanyui.github.io/node_modules/hexo/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAtPostResolution (/home/kuanyui/source-kuanyui.github.io/node_modules/hexo/node_modules/bluebird/js/main/promise.js:245:10)
    at Async._drainQueue (/home/kuanyui/source-kuanyui.github.io/node_modules/hexo/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/home/kuanyui/source-kuanyui.github.io/node_modules/hexo/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/kuanyui/source-kuanyui.github.io/node_modules/hexo/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```
If remove that json file, the error message disappear. 

I don't know why Hexo need to parse my json file, I try to use this:
```
skip_render:
  - '*.json'
```
But not works. How on earth to make `hexo` ignore my json file?

**Comment by samwhelp** [comment]
## empty json

I put empty file in source/_posts/

``` sh
$ touch source/_posts/hello.json
```

and

``` sh
$ hexo g
```

the error message like you post

## valid json file

let json file content valid

``` sh
$ echo '{}' > source/_posts/hello.json
```

view 「hello.json」

``` sh
$ cat source/_posts/hello.json
```

show

```
{}
```

then

``` sh
$ hexo g
```

no more error message.

but will generate html.

```
INFO  Generated: 2016/03/02/hello/index.html
```

## ignore

if you put 「_」 file name prefix.


``` sh
$ touch source/_posts/_hello.json
```

this will not generate html

```
$ hexo g
```

no more error message.

**Comment by samwhelp** [comment]
## work config example

edit _config.yml

```
skip_render: 
    - "_posts/*.json"
```
this will work.

## reference

* node_modules/hexo/lib/plugins/processor/post.js
* node_modules/hexo/lib/plugins/processor/asset.js

put these line to debug
```
      console.log(ctx.config.skip_render);
      console.log(path);
```
above  
````
result.renderable = ctx.render.isRenderable(path) && !common.isMatch(path, ctx.config.skip_render);
```

**Comment by kuanyui** [comment]
Shit, hexo process my js file. convert 

`var test = "<div class='hello'>";`
becomes to:
`var test = "<div class="hello">";`

what the fuck (╯°□°）╯︵ ┻━┻ these shit waste me 2 days

**Comment by samwhelp** [comment]
My test report:

==========================================

## Result 1

file 「source/hi.js」 

``` javascript
var test = '<div class="hello">';
```

generate file 「public/hi.js」

``` html
var test = '<div class="hello">';
</div>
```

==========================================

## Result 2

file 「source/_posts/hello.js」 

``` javascript
var test = '<div class="hello">';
```

generate file 「public/2016/03/03/hello/index.html」

``` html

... some html ....

<div class="article-entry" itemprop="articleBody">

	var test = '<div class="hello">';
</div>

... some html...

```

==========================================

**Comment by lyh543** [comment]
This is my intial `_posts` dir.

```sh
$ tree source/_posts
.
├── mirrors
│   ├── docker.json
│   └── maven.xml
├── linux-tips.md
```

run `hexo g` will generate `docker/index.html` but copy neither `docker.json` nor `maven.xml`.

```sh
$ hexo clean && hexo g | grep 'mirror'
INFO  Generated: linux/mirrors/docker/index.html
```

-----------------------------------------

Firstly, I **rename `mirrors` to  `linux-tips`**, so that `hexo g` will copy  `docker.json` and `maven.xml`.

```sh
$ tree source/_posts
.
├──  linux-tips
│   ├── docker.json
│   └── maven.xml
├── linux-tips.md
```

Secondly, **I add `skip_render`**, so that `hexo g` will not generate `docker/index.html`.

```yaml
skip_render:
  - "_posts/**/*.json"
```

Now it behaves correctly.

```
$ hexo clean && hexo g | grep 'linux-tips'
INFO  Generated: linux/linux-tips/index.html
INFO  Generated: linux/linux-tips/docker.json
INFO  Generated: linux/linux-tips/maven.xml
```
