### ISSUE TITLE
hexo 3.2.0 come to errors using plugins

### ISSUE THREAD

**Issue by seanlook** [hexojs/hexo#1805]
I just upgrage to 3.2.0 from 3.1.1 (windows). When I run `hexo generate`, **lots of** error come up like this:

```
TypeError: Cannot read property 'compile' of undefined
    at View._precompile (E:\seanlook\Hexo3\node_modules\hexo\lib\theme\view.js:104:22)
    at View (E:\seanlook\Hexo3\node_modules\hexo\lib\theme\view.js:13:8)
    at new Theme._View.View (E:\seanlook\Hexo3\node_modules\hexo\lib\theme\index.js:37:10)
    at Theme.setView (E:\seanlook\Hexo3\node_modules\hexo\lib\theme\index.js:71:20)
    at E:\seanlook\Hexo3\node_modules\hexo\lib\theme\processors\view.js:14:14
    at tryCatcher (E:\seanlook\Hexo3\node_modules\hexo\node_modules\bluebird\js\release\util.js:16:2
3)
    at Promise._settlePromiseFromHandler (E:\seanlook\Hexo3\node_modules\hexo\node_modules\bluebird\
js\release\promise.js:503:31)
    at Promise._settlePromise
 ...  
(E:\seanlook\Hexo3\node_modules\hexo\node_modules\bluebird\js\release\promis
e.js:629:18)
    at E:\seanlook\Hexo3\node_modules\hexo\node_modules\bluebird\js\release\nodeback.js:42:21
    at E:\seanlook\Hexo3\node_modules\hexo\node_modules\hexo-fs\node_modules\graceful-fs\graceful-fs
.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
ERROR Process failed: layout/_partial/post/articlenav.ejs
```

After trying many times, I found out that remove `plugins` area in site `_config.yml` should work for me.

I use the following plugins:
```
plugins:
- hexo-generator-sitemap
- hexo-generator-feed
```

Versions:
```
E:\seanlook\Hexo3>hexo version
hexo: 3.2.0
hexo-cli: 1.0.1
os: Windows_NT 10.0.10586 win32 x64
http_parser: 2.5.2
node: 4.3.1
v8: 4.5.103.35
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2f
```

**Comment by hychen** [comment]
just use `npm install $(hexo-plugin-name)  --save` to install hexo plugins. this works for me.

for example, `npm install hexo-generator-sitemap --save`

**Comment by Xuanwo** [comment]
you need to install them again.

**Comment by leesei** [comment]
`npm update -S` is better.

**Comment by leesei** [comment]
@seanlook Does update fix the issue?

**Comment by seanlook** [comment]
I start a project in new directory, and everything is clean.

**Comment by leesei** [comment]
The error looks like #1855
Do you catch the file producing the error?
Is it possible to push your source to github?

**Comment by leesei** [comment]
Also, specifying plugins disables automatic plugin scan (`hexo/lib/hexo/load_plugins.js`).
Maybe you're using a plugin not in your `plugins` config.

**Comment by leesei** [comment]
`ERROR Process failed: layout/_partial/post/articlenav.ejs`
This is tracked by #1855.
