### ISSUE TITLE
TypeError: Cannot read property 'compile' of undefined on travis-ci

### ISSUE THREAD

**Issue by Waydrow** [hexojs/hexo#1807]
I use travis-ci for auto deploy, now when it came to `hexo generate`,
outputs: 
```
$ hexo generate
INFO  Start processing
ERROR Process failed: layout/archive.ejs
TypeError: Cannot read property 'compile' of undefined
    at View._precompile (/home/travis/build/Waydrow/My-Blog/node_modules/hexo/lib/theme/view.js:104:22)
    at View (/home/travis/build/Waydrow/My-Blog/node_modules/hexo/lib/theme/view.js:13:8)
    at new Theme._View.View (/home/travis/build/Waydrow/My-Blog/node_modules/hexo/lib/theme/index.js:37:10)
    at Theme.setView (/home/travis/build/Waydrow/My-Blog/node_modules/hexo/lib/theme/index.js:71:20)
    at /home/travis/build/Waydrow/My-Blog/node_modules/hexo/lib/theme/processors/view.js:14:14
    at tryCatcher (/home/travis/build/Waydrow/My-Blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/travis/build/Waydrow/My-Blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/home/travis/build/Waydrow/My-Blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/home/travis/build/Waydrow/My-Blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/home/travis/build/Waydrow/My-Blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/home/travis/build/Waydrow/My-Blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:629:18)
    at Promise._resolveCallback (/home/travis/build/Waydrow/My-Blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:424:57)
    at Promise._settlePromiseFromHandler (/home/travis/build/Waydrow/My-Blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:515:17)
    at Promise._settlePromise (/home/travis/build/Waydrow/My-Blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/home/travis/build/Waydrow/My-Blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/home/travis/build/Waydrow/My-Blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/home/travis/build/Waydrow/My-Blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:629:18)
    at /home/travis/build/Waydrow/My-Blog/node_modules/hexo/node_modules/bluebird/js/release/nodeback.js:42:21
    at /home/travis/build/Waydrow/My-Blog/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:78:16
    at fs.js:334:14
    at /home/travis/build/Waydrow/My-Blog/node_modules/hexo-generator-feed/node_modules/nunjucks/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:104:5
    at /home/travis/build/Waydrow/My-Blog/node_modules/hexo/node_modules/nunjucks/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:43:10
ERROR Process failed: layout/category.ejs
TypeError: Cannot read property 'compile' of undefined
```

A few days ago, it still can work.
But now it can't make it, anyone knows how to slove this?
@tommy351 @Nerom

**Comment by leesei** [comment]
What theme are you using?
We've been testing with theme-light (and several others) and it's okay

**Comment by Waydrow** [comment]
yilia 
我的博客地址是 blog.waydrow.com

**Comment by Waydrow** [comment]
yilia 
我的博客地址是 blog.waydrow.com

**Comment by leesei** [comment]
Remove the `.DS_Store` in theme and try again.

**Comment by iwarner** [comment]
This will effect any Mac user who creates a new folder in any theme structure - the OS automatically creates these files - simply saying remove it will not suffice. This should be re-openend and the compile engine should ignore such tiles.

**Comment by leesei** [comment]
Tracked in #1855
