### ISSUE TITLE
could not run hexo in other path outside the ~/.nvm 

### ISSUE THREAD

**Issue by acgmohu** [hexojs/hexo#1824]
My system is OS X.

I can run hero at `~/.nvm`, it work well.

But I run `hexo` in other path, it will:
```
FATAL Cannot read property 'code' of undefined
TypeError: Cannot read property 'code' of undefined
    at /Users/bin/.nvm/versions/node/v4.4.0/lib/node_modules/hexo-cli/lib/find_pkg.js:23:25
    at tryCatcher (/Users/bin/.nvm/versions/node/v4.4.0/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/bin/.nvm/versions/node/v4.4.0/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/Users/bin/.nvm/versions/node/v4.4.0/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Users/bin/.nvm/versions/node/v4.4.0/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Users/bin/.nvm/versions/node/v4.4.0/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/promise.js:680:18)
    at Async._drainQueue (/Users/bin/.nvm/versions/node/v4.4.0/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/async.js:126:16)
    at Async._drainQueues (/Users/bin/.nvm/versions/node/v4.4.0/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/async.js:136:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/bin/.nvm/versions/node/v4.4.0/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

I think it's a configure problem, but I have no idea about it.

**Comment by leesei** [comment]
`export NODE_PATH="'$(npm root -g)'"`
http://stackoverflow.com/questions/13465829/node-js-modules-path

**Comment by acgmohu** [comment]
It seems not worked.
