### ISSUE TITLE
hexo 3.2.0  use "hexo g" command can not be useful

### ISSUE THREAD

**Issue by wuchangfeng** [hexojs/hexo#1832]
```
$ hexo g
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: (unknown path) [Line 32, Column 24]
  expected variable end
    at Object.exports.prettifyError (G:\Hexo\node_modules\hexo\node_modules\nunjucks\src\lib.js:34:15)
    at Obj.extend.render (G:\Hexo\node_modules\hexo\node_modules\nunjucks\src\environment.js:468:27)
    at Obj.extend.renderString (G:\Hexo\node_modules\hexo\node_modules\nunjucks\src\environment.js:326:21)
    at G:\Hexo\node_modules\hexo\lib\extend\tag.js:66:9
    at Promise._execute (G:\Hexo\node_modules\hexo\node_modules\bluebird\js\release\debuggability.js:272:9)
    at Promise._resolveFromExecutor (G:\Hexo\node_modules\hexo\node_modules\bluebird\js\release\promise.js:474:18)
    at new Promise (G:\Hexo\node_modules\hexo\node_modules\bluebird\js\release\promise.js:77:14)
    at Tag.render (G:\Hexo\node_modules\hexo\lib\extend\tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (G:\Hexo\node_modules\hexo\lib\hexo\post.js:253:16)
    at G:\Hexo\node_modules\hexo\lib\hexo\render.js:63:19
    at tryCatcher (G:\Hexo\node_modules\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (G:\Hexo\node_modules\hexo\node_modules\bluebird\js\release\promise.js:503:31)
    at Promise._settlePromise (G:\Hexo\node_modules\hexo\node_modules\bluebird\js\release\promise.js:560:18)
    at Promise._settlePromise0 (G:\Hexo\node_modules\hexo\node_modules\bluebird\js\release\promise.js:605:10)
    at Promise._settlePromises (G:\Hexo\node_modules\hexo\node_modules\bluebird\js\release\promise.js:684:18)
    at Async._drainQueue (G:\Hexo\node_modules\hexo\node_modules\bluebird\js\release\async.js:126:16)
    at Async._drainQueues (G:\Hexo\node_modules\hexo\node_modules\bluebird\js\release\async.js:136:10)
    at Immediate.Async.drainQueues [as _onImmediate] (G:\Hexo\node_modules\hexo\node_modules\bluebird\js\release\async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
FATAL (unknown path) [Line 32, Column 24]
  expected variable end
Template render error: (unknown path) [Line 32, Column 24]
  expected variable end
    at Object.exports.prettifyError (G:\Hexo\node_modules\hexo\node_modules\nunjucks\src\lib.js:34:15)
    at Obj.extend.render (G:\Hexo\node_modules\hexo\node_modules\nunjucks\src\environment.js:468:27)
    at Obj.extend.renderString (G:\Hexo\node_modules\hexo\node_modules\nunjucks\src\environment.js:326:21)
    at G:\Hexo\node_modules\hexo\lib\extend\tag.js:66:9
    at Promise._execute (G:\Hexo\node_modules\hexo\node_modules\bluebird\js\release\debuggability.js:272:9)
    at Promise._resolveFromExecutor (G:\Hexo\node_modules\hexo\node_modules\bluebird\js\release\promise.js:474:18)
    at new Promise (G:\Hexo\node_modules\hexo\node_modules\bluebird\js\release\promise.js:77:14)
    at Tag.render (G:\Hexo\node_modules\hexo\lib\extend\tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (G:\Hexo\node_modules\hexo\lib\hexo\post.js:253:16)
    at G:\Hexo\node_modules\hexo\lib\hexo\render.js:63:19
    at tryCatcher (G:\Hexo\node_modules\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (G:\Hexo\node_modules\hexo\node_modules\bluebird\js\release\promise.js:503:31)
    at Promise._settlePromise (G:\Hexo\node_modules\hexo\node_modules\bluebird\js\release\promise.js:560:18)
    at Promise._settlePromise0 (G:\Hexo\node_modules\hexo\node_modules\bluebird\js\release\promise.js:605:10)
    at Promise._settlePromises (G:\Hexo\node_modules\hexo\node_modules\bluebird\js\release\promise.js:684:18)
    at Async._drainQueue (G:\Hexo\node_modules\hexo\node_modules\bluebird\js\release\async.js:126:16)
    at Async._drainQueues (G:\Hexo\node_modules\hexo\node_modules\bluebird\js\release\async.js:136:10)
    at Immediate.Async.drainQueues [as _onImmediate] (G:\Hexo\node_modules\hexo\node_modules\bluebird\js\release\async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

```

**Comment by Xuanwo** [comment]
Can you paste your `_config.yml` file?

**Comment by leesei** [comment]
Probably one of your md causes the parsing error, run `hexo g --debug` and check which file caused the error

**Comment by wuchangfeng** [comment]
@Xuanwo 谢谢，已经解决了，我感觉应该是文章格式或者MD语法的原因，之前在Github上直接复制readme文件过去，就是发表不了。

**Comment by wuchangfeng** [comment]
@leesei  yout are right.and i solved it, thx.
