### ISSUE TITLE
parse errror if post content with content of {{.value}} 

### ISSUE THREAD

**Issue by sdvdxl** [hexojs/hexo#1833]
the post content is:

```
---
title: test
date: 2016-03-09 14:18:33
tags:
  - spring
  - xd
  - spring-xd
  - spring xd
category: spring
---
just a test `{{.a}}`
```

when run `hexo generate` it will show the errors:

```
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: (unknown path) [Line 2, Column 77]
  unexpected token: .
    at Object.exports.prettifyError (D:\workspace\blog\node_modules\nunjucks\src\lib.js:34:15)
    at Obj.extend.render (D:\workspace\blog\node_modules\nunjucks\src\environment.js:468:27)
    at Obj.extend.renderString (D:\workspace\blog\node_modules\nunjucks\src\environment.js:326:21)
    at D:\workspace\blog\node_modules\hexo\lib\extend\tag.js:66:9
    at Promise._execute (D:\workspace\blog\node_modules\bluebird\js\release\debuggability.js:272:9)
    at Promise._resolveFromExecutor (D:\workspace\blog\node_modules\bluebird\js\release\promise.js:474:18)
    at new Promise (D:\workspace\blog\node_modules\bluebird\js\release\promise.js:77:14)
    at Tag.render (D:\workspace\blog\node_modules\hexo\lib\extend\tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (D:\workspace\blog\node_modules\hexo\lib\hexo\post.js:253:16)
    at D:\workspace\blog\node_modules\hexo\lib\hexo\render.js:63:19
    at tryCatcher (D:\workspace\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\workspace\blog\node_modules\bluebird\js\release\promise.js:503:31)
    at Promise._settlePromise (D:\workspace\blog\node_modules\bluebird\js\release\promise.js:560:18)
    at Promise._settlePromise0 (D:\workspace\blog\node_modules\bluebird\js\release\promise.js:605:10)
    at Promise._settlePromises (D:\workspace\blog\node_modules\bluebird\js\release\promise.js:684:18)
    at Async._drainQueue (D:\workspace\blog\node_modules\bluebird\js\release\async.js:126:16)
    at Async._drainQueues (D:\workspace\blog\node_modules\bluebird\js\release\async.js:136:10)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\workspace\blog\node_modules\bluebird\js\release\async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
FATAL (unknown path) [Line 2, Column 77]
  unexpected token: .
Template render error: (unknown path) [Line 2, Column 77]
  unexpected token: .
    at Object.exports.prettifyError (D:\workspace\blog\node_modules\nunjucks\src\lib.js:34:15)
    at Obj.extend.render (D:\workspace\blog\node_modules\nunjucks\src\environment.js:468:27)
    at Obj.extend.renderString (D:\workspace\blog\node_modules\nunjucks\src\environment.js:326:21)
    at D:\workspace\blog\node_modules\hexo\lib\extend\tag.js:66:9
    at Promise._execute (D:\workspace\blog\node_modules\bluebird\js\release\debuggability.js:272:9)
    at Promise._resolveFromExecutor (D:\workspace\blog\node_modules\bluebird\js\release\promise.js:474:18)
    at new Promise (D:\workspace\blog\node_modules\bluebird\js\release\promise.js:77:14)
    at Tag.render (D:\workspace\blog\node_modules\hexo\lib\extend\tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (D:\workspace\blog\node_modules\hexo\lib\hexo\post.js:253:16)
    at D:\workspace\blog\node_modules\hexo\lib\hexo\render.js:63:19
    at tryCatcher (D:\workspace\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\workspace\blog\node_modules\bluebird\js\release\promise.js:503:31)
    at Promise._settlePromise (D:\workspace\blog\node_modules\bluebird\js\release\promise.js:560:18)
    at Promise._settlePromise0 (D:\workspace\blog\node_modules\bluebird\js\release\promise.js:605:10)
    at Promise._settlePromises (D:\workspace\blog\node_modules\bluebird\js\release\promise.js:684:18)
    at Async._drainQueue (D:\workspace\blog\node_modules\bluebird\js\release\async.js:126:16)
    at Async._drainQueues (D:\workspace\blog\node_modules\bluebird\js\release\async.js:136:10)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\workspace\blog\node_modules\bluebird\js\release\async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by Xuanwo** [comment]
Known issues, Hexo do not support `{{` and `}}`
you can use `{{ raw }}` and `{{ endraw }}` to include them

**Comment by sdvdxl** [comment]
I fixed it to “`go list -f '{{ raw }} {{.ImportPath}} {{ endraw }}'`”,but it does not work.

**Comment by Xuanwo** [comment]
Sorry for my wrong use.

the corrent use style is 

```
{% raw %}
{{abc}
{% endraw %}
```

you can see the example here : https://xuanwo.org/hexo-issue-test/2016/03/16/1833/

**Comment by sdvdxl** [comment]
Thanks very well
