### ISSUE TITLE
ERROR 

### ISSUE THREAD

**Issue by ifgyong** [hexojs/hexo#1850]
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "hero-generator-index"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npm.taobao.org/hero-generator-index
npm ERR! 404
npm ERR! 404 'hero-generator-index' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Jerry/Desktop/hexoDemo/ifgyong.github.io/npm-debug.log

**Comment by ifgyong** [comment]
when i run npm install--save hero-generator-archive,show error.

**Comment by ifgyong** [comment]
run hexo g.show this
RROR Process failed: layout/_scripts/bootstrap/.gitkeep
TypeError: Cannot read property 'compile' of undefined
    at View._precompile (/Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/hexo/lib/theme/view.js:104:22)
    at View (/Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/hexo/lib/theme/view.js:13:8)
    at new Theme._View.View (/Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/hexo/lib/theme/index.js:37:10)
    at Theme.setView (/Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/hexo/lib/theme/index.js:71:20)
    at /Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/hexo/lib/theme/processors/view.js:14:14
    at tryCatcher (/Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/bluebird/js/release/promise.js:629:18)
    at Promise._resolveCallback (/Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/bluebird/js/release/promise.js:424:57)
    at Promise._settlePromiseFromHandler (/Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/bluebird/js/release/promise.js:515:17)
    at Promise._settlePromise (/Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/bluebird/js/release/promise.js:629:18)
    at /Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/graceful-fs/graceful-fs.js:78:16
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
INFO  Files loaded in 504 ms
INFO  Generated: index.html
INFO  Generated: page/2/index.html
INFO  2 files generated in 956 ms

**Comment by ifgyong** [comment]
hexo -v

hexo: 3.2.0
hexo-cli: 1.0.1
os: Darwin 15.2.0 darwin x64
http_parser: 2.6.0
node: 5.4.1
v8: 4.6.85.31
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2e

**Comment by greg-js** [comment]
Are you sure you wrote `hexo-generator-index`? You wrote he**r**o in your posts

**Comment by ifgyong** [comment]
after I run npm  install  --save hexo-generator-index
npm install --save hexo-generator-archive
npm install --save hexo-generator-tag,
hexo clean
hexo g
show error:
Yong-MacBook-Pro:hexogithub Yong$ hexo clean
INFO  Deleted database.
INFO  Deleted public folder.
Yong-MacBook-Pro:hexogithub Yong$ hexo g
INFO  Start processing
ERROR Process failed: layout/_scripts/bootstrap/.gitkeep
TypeError: Cannot read property 'compile' of undefined
    at View._precompile (/Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/hexo/lib/theme/view.js:104:22)
    at View (/Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/hexo/lib/theme/view.js:13:8)
    at new Theme._View.View (/Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/hexo/lib/theme/index.js:37:10)
    at Theme.setView (/Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/hexo/lib/theme/index.js:71:20)
    at /Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/hexo/lib/theme/processors/view.js:14:14
    at tryCatcher (/Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/bluebird/js/release/promise.js:629:18)
    at Promise._resolveCallback (/Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/bluebird/js/release/promise.js:424:57)
    at Promise._settlePromiseFromHandler (/Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/bluebird/js/release/promise.js:515:17)
    at Promise._settlePromise (/Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/bluebird/js/release/promise.js:629:18)
    at /Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/graceful-fs/graceful-fs.js:78:16
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
INFO  Files loaded in 1.98 s
INFO  Generated: index.html
INFO  Generated: CNAME
INFO  Generated: pic.png
INFO  Generated: about/index.html
INFO  Generated: tags/index.html
INFO  Generated: categories/index.html
INFO  Generated: archives/index.html
INFO  Generated: images/cc-by-nc-nd.svg
INFO  Generated: images/cc-by-nd.svg
INFO  Generated: images/cc-by-nc.svg
INFO  Generated: images/cc-by-sa.svg
INFO  Generated: images/cc-by-nc-sa.svg
INFO  Generated: images/cc-zero.svg
INFO  Generated: images/cc-by.svg
INFO  Generated: images/loading.gif
INFO  Generated: images/quote-l.svg
INFO  Generated: images/quote-r.svg
INFO  Generated: images/placeholder.gif
INFO  Generated: archives/page/2/index.html
INFO  Generated: images/searchicon.png
INFO  Generated: page/2/index.html
INFO  Generated: categories/建站/index.html
INFO  Generated: archives/2016/01/index.html
INFO  Generated: archives/2016/03/index.html
INFO  Generated: tags/iOS/index.html
INFO  Generated: tags/建站/index.html
INFO  Generated: tags/hexo/index.html
INFO  Generated: categories/iOS/index.html
INFO  Generated: tags/iOS高级开发/index.html
INFO  Generated: tags/Shell/index.html
INFO  Generated: tags/iOS自动化打包/index.html
INFO  Generated: tags/疑难杂症/index.html
INFO  Generated: archives/2016/index.html
INFO  Generated: vendors/font-awesome/HELP-US-OUT.txt
INFO  Generated: vendors/fastclick/README.html
INFO  Generated: vendors/jquery_lazyload/README.html
INFO  Generated: css/main.css
INFO  Generated: vendors/jquery/index.js
INFO  Generated: vendors/velocity/bower.json
INFO  Generated: vendors/font-awesome/bower.json
INFO  Generated: vendors/fastclick/bower.json
INFO  Generated: vendors/velocity/velocity.ui.min.js
INFO  Generated: vendors/jquery_lazyload/bower.json
INFO  Generated: vendors/jquery_lazyload/CONTRIBUTING.html
INFO  Generated: vendors/velocity/velocity.ui.js
INFO  Generated: vendors/jquery_lazyload/jquery.lazyload.js
INFO  Generated: vendors/velocity/velocity.min.js
INFO  Generated: vendors/fastclick/LICENSE
INFO  Generated: vendors/jquery_lazyload/jquery.scrollstop.js
INFO  Generated: vendors/velocity/velocity.js
INFO  Generated: archives/2016/page/2/index.html
INFO  Generated: vendors/font-awesome/fonts/fontawesome-webfont.eot
INFO  Generated: vendors/font-awesome/fonts/FontAwesome.otf
INFO  Generated: vendors/font-awesome/fonts/fontawesome-webfont.woff
INFO  Generated: vendors/fancybox/source/helpers/fancybox_buttons.png
INFO  Generated: vendors/font-awesome/fonts/fontawesome-webfont.svg
INFO  Generated: js/src/hook-duoshuo.js
INFO  Generated: vendors/fastclick/lib/fastclick.min.js
INFO  Generated: vendors/ua-parser-js/dist/ua-parser.pack.js
INFO  Generated: vendors/font-awesome/css/font-awesome.css
INFO  Generated: js/src/motion.js
INFO  Generated: js/src/scrollspy.js
INFO  Generated: js/src/utils.js
INFO  Generated: vendors/fancybox/source/jquery.fancybox.css
INFO  Generated: js/src/affix.js
INFO  Generated: vendors/fancybox/source/helpers/jquery.fancybox-buttons.css
INFO  Generated: vendors/ua-parser-js/dist/ua-parser.min.js
INFO  Generated: js/src/bootstrap.js
INFO  Generated: vendors/fancybox/source/helpers/jquery.fancybox-buttons.js
INFO  Generated: vendors/fancybox/source/helpers/jquery.fancybox-thumbs.js
INFO  Generated: vendors/fancybox/source/jquery.fancybox.pack.js
INFO  Generated: vendors/fancybox/source/helpers/jquery.fancybox-media.js
INFO  Generated: vendors/fancybox/source/jquery.fancybox.js
INFO  Generated: vendors/fastclick/lib/fastclick.js
INFO  Generated: vendors/fancybox/source/helpers/jquery.fancybox-thumbs.css
INFO  Generated: vendors/font-awesome/css/font-awesome.min.css
INFO  Generated: vendors/font-awesome/fonts/fontawesome-webfont.ttf
INFO  Generated: 2016/03/24/iOS高级开发runtime那点事实战（3）/index.html
INFO  Generated: 2016/01/31/hexo换了电脑怎么解决/index.html
INFO  Generated: vendors/fancybox/source/blank.gif
INFO  Generated: vendors/fancybox/source/fancybox_loading.gif
INFO  Generated: vendors/fancybox/source/fancybox_overlay.png
INFO  Generated: vendors/font-awesome/css/font-awesome.css.map
INFO  Generated: vendors/fancybox/source/fancybox_loading@2x.gif
INFO  Generated: vendors/font-awesome/fonts/fontawesome-webfont.woff2
INFO  Generated: vendors/fancybox/source/fancybox_sprite@2x.png
INFO  Generated: 2016/01/30/Module-version-mismatch/index.html
INFO  Generated: vendors/fancybox/source/fancybox_sprite.png
INFO  Generated: 2016/01/28/MAC-重置MySQL-root-密码/index.html
INFO  Generated: 2016/01/31/hexo换了电脑处理方法/index.html
INFO  Generated: 2016/01/28/iOS-WebView设置cookie/index.html
INFO  Generated: 2016/01/28/iOS自动化打包第一步/index.html
INFO  Generated: 2016/01/28/iOS-static-const-extern-用法技巧/index.html
INFO  Generated: 2016/01/28/iOS证书过期解决方案/index.html
INFO  Generated: 2016/01/28/hexo自定义域名/index.html
INFO  Generated: 2016/03/24/iOS高级开发runtime那点事实战（2）/index.html
INFO  Generated: 2016/03/24/iOS高级开发runtime那点事实战（1）/index.html
INFO  Generated: js/src/schemes/pisces.js
INFO  98 files generated in 1.3 s

**Comment by leesei** [comment]
delete the `.gitkeep` manually for now
