### ISSUE TITLE
deleting post error ENOENT: no such file or directory

### ISSUE THREAD

**Issue by shellhue** [hexojs/hexo#1856]
I run hexo on my Mac. It works very well until i want to delete the `hello-world.md` post. I delete the post in the following order.
1. delete the `hello-world.md` in source/_post
2. run `hexo clean` to delete the `database (db.json)` and `assets` folder
3. run `hexo generate` to generate the new blog without your deleted post, unfortunately, error happens.

the error message is: 
```
/usr/local/lib/node_modules/hexo/node_modules/graceful-fs/polyfills.js:8
    cwd = origCwd.call(process)
                  ^

Error: ENOENT: no such file or directory, uv_cwd
    at Error (native)
    at process.cwd (/usr/local/lib/node_modules/hexo/node_modules/graceful-fs/polyfills.js:8:19)
    at entry (/usr/local/lib/node_modules/hexo/node_modules/hexo-cli/lib/hexo.js:14:24)
    at Object.<anonymous> (/usr/local/lib/node_modules/hexo/bin/hexo:5:20)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3
```

I look up the problem on Google and stackoverflow, but ending with no results. So what is the problem? Thanks for all your help.

**Comment by shellhue** [comment]
This problem is caused because I run `hexo generate` in folder `public` which is deleted when i run `hexo clean`.
