### ISSUE TITLE
ERROR Process failed: layout/_scripts/bootstrap/.gitkeep

### ISSUE THREAD

**Issue by ifgyong** [hexojs/hexo#1857]
版本：
hexo: 3.2.0
hexo-cli: 1.0.1
os: Darwin 15.2.0 darwin x64
http_parser: 2.6.0
node: 5.4.1
v8: 4.6.85.31
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2e

执行: hexo g 
出错：`TypeError: Cannot read property 'compile' of undefined
    at View._precompile (/Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/hexo/lib/theme/view.js:104:22)
    at View (/Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/hexo/lib/theme/view.js:13:8)
    at new Theme._View.View (/Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/hexo/lib/theme/index.js:37:10)`
无法将写好的文章 推到网站上面，本地预览是可以的。

**Comment by leesei** [comment]
delete the `.gitkeep` manually for now

**Comment by leesei** [comment]
Where is the `.gitkeep` causing the error?

**Comment by leesei** [comment]
see #1895
