### ISSUE TITLE
Error running hexo command

### ISSUE THREAD

**Issue by pnmougel** [hexojs/hexo#1860]
I have an error after installing hexo with the hexo command

```
/home/nico/.npm-packages/lib/node_modules/hexo/node_modules/bluebird/js/release/promisify.js:270
        throw new TypeError("expecting a function but got " + util.classString(fn));
              ^
TypeError: expecting a function but got [object Undefined]
    at Function.Promise.promisify (/home/nico/.npm-packages/lib/node_modules/hexo/node_modules/bluebird/js/release/promisify.js:270:15)
    at Object.<anonymous> (/home/nico/.npm-packages/lib/node_modules/hexo/node_modules/hexo-fs/lib/fs.js:580:26)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/nico/.npm-packages/lib/node_modules/hexo/node_modules/hexo-cli/lib/find_pkg.js:4:10)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/nico/.npm-packages/lib/node_modules/hexo/node_modules/hexo-cli/lib/hexo.js:8:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/nico/.npm-packages/lib/node_modules/hexo/bin/hexo:5:544)
```

`fs.lchmod` and `fs.lchown` does not seems to be available on ubuntu 14.04 even with the package `node-graceful-fs`.

**Comment by leesei** [comment]
Can you try cleaning `node_modules` and rerun `npm -i`?

**Comment by pnmougel** [comment]
Thanks, its working fine now.
