### ISSUE TITLE
hero g ,something wrong 

### ISSUE THREAD

**Issue by xuyushi** [hexojs/hexo#1881]
```
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
SyntaxError: Unexpected token ILLEGAL
    at Function (native)
    at Obj.extend._compile (/Users/xuyushi/Documents/hexo/node_modules/hexo/node_modules/nunjucks/src/environment.js:450:24)
    at Obj.extend.compile (/Users/xuyushi/Documents/hexo/node_modules/hexo/node_modules/nunjucks/src/environment.js:433:18)
    at null.<anonymous> (/Users/xuyushi/Documents/hexo/node_modules/hexo/node_modules/nunjucks/src/environment.js:378:22)
    at Object.exports.withPrettyErrors (/Users/xuyushi/Documents/hexo/node_modules/hexo/node_modules/nunjucks/src/lib.js:24:16)
    at Obj.extend.render (/Users/xuyushi/Documents/hexo/node_modules/hexo/node_modules/nunjucks/src/environment.js:374:20)
    at Obj.extend.renderString (/Users/xuyushi/Documents/hexo/node_modules/hexo/node_modules/nunjucks/src/environment.js:261:21)
    at /Users/xuyushi/Documents/hexo/node_modules/hexo/lib/extend/tag.js:56:9
    at tryCatcher (/Users/xuyushi/Documents/hexo/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._resolveFromResolver (/Users/xuyushi/Documents/hexo/node_modules/hexo/node_modules/bluebird/js/main/promise.js:427:31)
    at new Promise (/Users/xuyushi/Documents/hexo/node_modules/hexo/node_modules/bluebird/js/main/promise.js:53:37)
    at Tag.render (/Users/xuyushi/Documents/hexo/node_modules/hexo/lib/extend/tag.js:55:10)
    at Object.tagFilter [as onRenderEnd] (/Users/xuyushi/Documents/hexo/node_modules/hexo/lib/hexo/post.js:253:16)
    at /Users/xuyushi/Documents/hexo/node_modules/hexo/lib/hexo/render.js:55:19
    at tryCatcher (/Users/xuyushi/Documents/hexo/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/Users/xuyushi/Documents/hexo/node_modules/hexo/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/Users/xuyushi/Documents/hexo/node_modules/hexo/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromises (/Users/xuyushi/Documents/hexo/node_modules/hexo/node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (/Users/xuyushi/Documents/hexo/node_modules/hexo/node_modules/bluebird/js/main/async.js:182:16)
    at Async._drainQueues (/Users/xuyushi/Documents/hexo/node_modules/hexo/node_modules/bluebird/js/main/async.js:192:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/xuyushi/Documents/hexo/node_modules/hexo/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```

**Comment by leesei** [comment]
You probably have an erroneous tag.
See https://github.com/hexojs/hexo/issues/1771 and try my branch to trace the file.

**Comment by leesei** [comment]
Any update?
