### ISSUE TITLE
开启二次验证的git账号，在hexo d 时候输入账号密码提示错误

### ISSUE THREAD

**Issue by BaoZijian** [hexojs/hexo#1886]
~/Documents/hexo/myblog » hexo d                                                                                             Baozi@Baozijian
INFO  Deploying: git
INFO  Clearing .deploy_git folder...
INFO  Copying files from public folder...
[master 631fa83] Site updated: 2016-04-14 09:43:14
 8 files changed, 52 insertions(+), 52 deletions(-)
Username for 'https://github.com': BaoZijian
Password for 'https://BaoZijian@github.com': 
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/BaoZijian/BaoZijian.github.io.git/'
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/BaoZijian/BaoZijian.github.io.git/'

    at ChildProcess.<anonymous> (/Users/Baozi/Documents/hexo/myblog/node_modules/hexo-deployer-git/node_modules/hexo-util/lib/spawn.js:37:17)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
FATAL remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/BaoZijian/BaoZijian.github.io.git/'

Error: remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/BaoZijian/BaoZijian.github.io.git/'

    at ChildProcess.<anonymous> (/Users/Baozi/Documents/hexo/myblog/node_modules/hexo-deployer-git/node_modules/hexo-util/lib/spawn.js:37:17)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
------------------------------------------------------------

**Comment by Xuanwo** [comment]
建议你使用SSH形式使用

Baozijian <notifications@github.com>于2016年4月14日周四 上午9:45写道：

**Comment by BaoZijian** [comment]
嗯，搞定啦，多谢^_^
