### ISSUE TITLE
YAML解析异常

### ISSUE THREAD

**Issue by 623637646** [hexojs/hexo#1898]
我的YAML数据为

```
a : 
  - b : 
    - c : 
      - d : 
        - e : "ff"
```

解析代码为 

```
{% for A in a %}
    {% for B in A.b %}
        {% for C in B.c %}
            {{ C.d }}
        {% endfor %}
    {% endfor %}
{% endfor %}
```

异常信息 

```
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: (unknown path)
  unexpected end of file
    at Object.exports.prettifyError (/Users/wangya/Desktop/Progect/hexo-blog/node_modules/hexo/node_modules/nunjucks/src/lib.js:34:15)
    at Obj.extend.render (/Users/wangya/Desktop/Progect/hexo-blog/node_modules/hexo/node_modules/nunjucks/src/environment.js:468:27)
    at Obj.extend.renderString (/Users/wangya/Desktop/Progect/hexo-blog/node_modules/hexo/node_modules/nunjucks/src/environment.js:326:21)
    at /Users/wangya/Desktop/Progect/hexo-blog/node_modules/hexo/lib/extend/tag.js:66:9
    at Promise._execute (/Users/wangya/Desktop/Progect/hexo-blog/node_modules/hexo/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/Users/wangya/Desktop/Progect/hexo-blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:474:18)
    at new Promise (/Users/wangya/Desktop/Progect/hexo-blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:77:14)
    at Tag.render (/Users/wangya/Desktop/Progect/hexo-blog/node_modules/hexo/lib/extend/tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (/Users/wangya/Desktop/Progect/hexo-blog/node_modules/hexo/lib/hexo/post.js:253:16)
    at /Users/wangya/Desktop/Progect/hexo-blog/node_modules/hexo/lib/hexo/render.js:63:19
    at tryCatcher (/Users/wangya/Desktop/Progect/hexo-blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/wangya/Desktop/Progect/hexo-blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/Users/wangya/Desktop/Progect/hexo-blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Users/wangya/Desktop/Progect/hexo-blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Users/wangya/Desktop/Progect/hexo-blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:684:18)
    at Async._drainQueue (/Users/wangya/Desktop/Progect/hexo-blog/node_modules/hexo/node_modules/bluebird/js/release/async.js:126:16)
    at Async._drainQueues (/Users/wangya/Desktop/Progect/hexo-blog/node_modules/hexo/node_modules/bluebird/js/release/async.js:136:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/wangya/Desktop/Progect/hexo-blog/node_modules/hexo/node_modules/bluebird/js/release/async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
FATAL (unknown path)
  unexpected end of file
Template render error: (unknown path)
  unexpected end of file
    at Object.exports.prettifyError (/Users/wangya/Desktop/Progect/hexo-blog/node_modules/hexo/node_modules/nunjucks/src/lib.js:34:15)
    at Obj.extend.render (/Users/wangya/Desktop/Progect/hexo-blog/node_modules/hexo/node_modules/nunjucks/src/environment.js:468:27)
    at Obj.extend.renderString (/Users/wangya/Desktop/Progect/hexo-blog/node_modules/hexo/node_modules/nunjucks/src/environment.js:326:21)
    at /Users/wangya/Desktop/Progect/hexo-blog/node_modules/hexo/lib/extend/tag.js:66:9
    at Promise._execute (/Users/wangya/Desktop/Progect/hexo-blog/node_modules/hexo/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/Users/wangya/Desktop/Progect/hexo-blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:474:18)
    at new Promise (/Users/wangya/Desktop/Progect/hexo-blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:77:14)
    at Tag.render (/Users/wangya/Desktop/Progect/hexo-blog/node_modules/hexo/lib/extend/tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (/Users/wangya/Desktop/Progect/hexo-blog/node_modules/hexo/lib/hexo/post.js:253:16)
    at /Users/wangya/Desktop/Progect/hexo-blog/node_modules/hexo/lib/hexo/render.js:63:19
    at tryCatcher (/Users/wangya/Desktop/Progect/hexo-blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/wangya/Desktop/Progect/hexo-blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/Users/wangya/Desktop/Progect/hexo-blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Users/wangya/Desktop/Progect/hexo-blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Users/wangya/Desktop/Progect/hexo-blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:684:18)
    at Async._drainQueue (/Users/wangya/Desktop/Progect/hexo-blog/node_modules/hexo/node_modules/bluebird/js/release/async.js:126:16)
    at Async._drainQueues (/Users/wangya/Desktop/Progect/hexo-blog/node_modules/hexo/node_modules/bluebird/js/release/async.js:136:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/wangya/Desktop/Progect/hexo-blog/node_modules/hexo/node_modules/bluebird/js/release/async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

求助~~

**Comment by Xuanwo** [comment]
我感觉你的解析代码没有写完啊，是不是少了个`D.e`
