### ISSUE TITLE
can not run hexo generate

### ISSUE THREAD

**Issue by hitao123** [hexojs/hexo#1905]
FATAL bad indentation of a mapping entry at line 71, column 7:
      type: git
 at generateError (E:\Blog\node_modules\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:162:10)
    at throwError (E:\Blog\node_modules\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:168:9)
    at readBlockMapping (E:\Blog\node_modules\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1074:7)
    at composeNode (E:\Blog\node_modules\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1326:12)
    at readDocument (E:\Blog\node_modules\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1488:3)
    at loadDocuments (E:\Blog\node_modules\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1544:5)
    at Object.load (E:\Blog\node_modules\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1561:19)
    at Hexo.yamlHelper (E:\Blog\node_modules\hexo\lib\plugins\renderer\yaml.js:7:15)
    at Hexo.tryCatcher (E:\Blog\node_modules\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (E:\Blog\node_modules\hexo\node_modules\bluebird\js\release\method.js:15:34)
    at E:\Blog\node_modules\hexo\lib\hexo\render.js:59:21
    at tryCatcher (E:\Blog\node_modules\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\Blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:502:31)
    at Promise._settlePromise (E:\Blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:559:18)
    at Promise._settlePromise0 (E:\Blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:604:10)
    at Promise._settlePromises (E:\Blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:683:18)
    at Async._drainQueue (E:\Blog\node_modules\hexo\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (E:\Blog\node_modules\hexo\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\Blog\node_modules\hexo\nod

**Comment by Xuanwo** [comment]
looks like some errors in your `config.yml`
