### ISSUE TITLE
deploy error show: source.replace is not a function

### ISSUE THREAD

**Issue by STayinloves** [hexojs/hexo#1909]
Happened while deploy through git, here's the code and version, update to the version 3.2.0-beta2 doesn't help.
`hexo: 3.1.1
os: Darwin 15.2.0 darwin x64
http_parser: 2.6.2
node: 5.10.1
v8: 4.6.85.31
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2g`
`INFO  Deploying: git
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: source.replace is not a function
    at Object.exports.parse (/Users/STay/blog/node_modules/swig/lib/parser.js:438:19)
    at parse (/Users/STay/blog/node_modules/swig/lib/swig.js:354:19)
    at Object.precompile (/Users/STay/blog/node_modules/swig/lib/swig.js:486:23)
    at Object.compile (/Users/STay/blog/node_modules/swig/lib/swig.js:606:16)
    at commitMessage (/Users/STay/blog/node_modules/hexo-deployer-git/lib/deployer.js:96:15)
    at Hexo.module.exports (/Users/STay/blog/node_modules/hexo-deployer-git/lib/deployer.js:22:17)
    at Hexo.tryCatcher (/Users/STay/blog/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at Hexo.<anonymous> (/Users/STay/blog/node_modules/hexo/node_modules/bluebird/js/main/method.js:15:34)
    at /Users/STay/blog/node_modules/hexo/lib/plugins/console/deploy.js:56:28
    at tryCatcher (/Users/STay/blog/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at ReductionPromiseArray._promiseFulfilled (/Users/STay/blog/node_modules/hexo/node_modules/bluebird/js/main/reduce.js:105:38)
    at ReductionPromiseArray.init (/Users/STay/blog/node_modules/hexo/node_modules/bluebird/js/main/promise_array.js:92:18)
    at Promise._settlePromiseAt (/Users/STay/blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:579:21)
    at Promise._settlePromises (/Users/STay/blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/Users/STay/blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/STay/blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/STay/blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:15:14)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
FATAL source.replace is not a function
TypeError: source.replace is not a function
    at Object.exports.parse (/Users/STay/blog/node_modules/swig/lib/parser.js:438:19)
    at parse (/Users/STay/blog/node_modules/swig/lib/swig.js:354:19)
    at Object.precompile (/Users/STay/blog/node_modules/swig/lib/swig.js:486:23)
    at Object.compile (/Users/STay/blog/node_modules/swig/lib/swig.js:606:16)
    at commitMessage (/Users/STay/blog/node_modules/hexo-deployer-git/lib/deployer.js:96:15)
    at Hexo.module.exports (/Users/STay/blog/node_modules/hexo-deployer-git/lib/deployer.js:22:17)
    at Hexo.tryCatcher (/Users/STay/blog/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at Hexo.<anonymous> (/Users/STay/blog/node_modules/hexo/node_modules/bluebird/js/main/method.js:15:34)
    at /Users/STay/blog/node_modules/hexo/lib/plugins/console/deploy.js:56:28
    at tryCatcher (/Users/STay/blog/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at ReductionPromiseArray._promiseFulfilled (/Users/STay/blog/node_modules/hexo/node_modules/bluebird/js/main/reduce.js:105:38)
    at ReductionPromiseArray.init (/Users/STay/blog/node_modules/hexo/node_modules/bluebird/js/main/promise_array.js:92:18)
    at Promise._settlePromiseAt (/Users/STay/blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:579:21)
    at Promise._settlePromises (/Users/STay/blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/Users/STay/blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/STay/blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/STay/blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:15:14)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)`
[debug.log.zip](https://github.com/hexojs/hexo/files/232974/debug.log.zip)

**Comment by Xuanwo** [comment]
@STayinloves 你这个问题看起来跟 #1855 有些相似，请问你的目录下面是不是有Mac OS自动生成的.DS_store 之类的文件？

**Comment by STayinloves** [comment]
@Xuanwo Problem solved, a careless mistake in setting deploy.Thx.[https://segmentfault.com/q/1010000002922215](url)
