### ISSUE TITLE
运行`hexo g`出错

### ISSUE THREAD

**Issue by dalufine** [hexojs/hexo#1913]
> INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: Cannot set property 'lastIndex' of undefined
    at highlight (/Users/dalu/Documents/blog/node_modules/highlight.js/lib/highlight.js:471:35)
    at /Users/dalu/Documents/blog/node_modules/highlight.js/lib/highlight.js:521:21
    at Array.forEach (native)
    at Object.highlightAuto (/Users/dalu/Documents/blog/node_modules/highlight.js/lib/highlight.js:520:40)
    at highlight (/Users/dalu/Documents/blog/node_modules/hexo-util/lib/highlight.js:98:19)
    at highlightUtil (/Users/dalu/Documents/blog/node_modules/hexo-util/lib/highlight.js:21:14)
    at /Users/dalu/Documents/blog/node_modules/hexo/lib/plugins/filter/before_post_render/backtick_code_block.js:49:15
    at String.replace (native)
    at Hexo.backtickCodeBlock (/Users/dalu/Documents/blog/node_modules/hexo/lib/plugins/filter/before_post_render/backtick_code_block.js:15:31)
    at Hexo.tryCatcher (/Users/dalu/Documents/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Users/dalu/Documents/blog/node_modules/bluebird/js/release/method.js:15:34)
    at /Users/dalu/Documents/blog/node_modules/hexo/lib/extend/filter.js:68:35
    at tryCatcher (/Users/dalu/Documents/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/Users/dalu/Documents/blog/node_modules/bluebird/js/release/reduce.js:145:18)
    at Object.gotAccum (/Users/dalu/Documents/blog/node_modules/bluebird/js/release/reduce.js:134:25)
    at Object.tryCatcher (/Users/dalu/Documents/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/dalu/Documents/blog/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/Users/dalu/Documents/blog/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromiseCtx (/Users/dalu/Documents/blog/node_modules/bluebird/js/release/promise.js:596:10)
    at Async._drainQueue (/Users/dalu/Documents/blog/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/Users/dalu/Documents/blog/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/dalu/Documents/blog/node_modules/bluebird/js/release/async.js:17:14)

package.json

```xml
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.2.0"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.2.0",
    "hexo-renderer-marked": "^0.2.10",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0"
  }
}

```

**Comment by dalufine** [comment]
highlight.js

**Comment by ding112** [comment]
_config.yml中auto_detect设为false

**Comment by cocobear** [comment]
> _config.yml中auto_detect设为false

这样做的话这个配置就没有意义了，有没有人研究过这个呢？

**Comment by counter2015** [comment]
> > _config.yml中auto_detect设为false
> 
> 这样做的话这个配置就没有意义了，有没有人研究过这个呢？

我也遇到了同样的问题，添加某篇新文章时出现，往里面加入`gh-md-toc`生成的目录是报错

但是把出问题的文章移走，重新`hexo g`，再移回来,再次`hexo g`后就没有问题了

玄学BUG

刚刚又看了下发现文末有一个多余的空代码块，不知道是不是因为这个原因 😂

**Comment by counter2015** [comment]
刚才又碰见这个bug了，莫名其妙又好了，步骤如下
- `hexo clean`
- 把`_posts`目录下的文件移出去
- 一开始我怀疑是某个markdown文件语法错了，想排除，于是就分批移动回去，同时`hexo g`检验
- 等我都移动完了，这Bug好了

<del>我还能说什么好呢</del>

**Comment by TeenagerPeng** [comment]
我也遇到了这种问题，我的原因是因为代码块中有的没有指定代码的类型，类似下面这种情况
```
public class A{}
```

**Comment by olderwei** [comment]
确实如@TeenagerPeng所说，代码块指定类型就可以了。

**Comment by csbun** [comment]
`echo "{}" > db.json && hexo g`

**Comment by manongchuangye** [comment]
beast@gentle-beast MINGW64 /d/blogfile
$ hexo g
INFO  Validating config
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/d
ocs/troubleshooting.html
D:\blogfile\node_modules\highlight.js\lib\languages\isbl.js:1806
  // enum TE


SyntaxError: Unexpected end of input
    at wrapSafe (node:internal/modules/cjs/loader:1281:20)
    at Module._compile (node:internal/modules/cjs/loader:1321:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (D:\blogfile\node_modules\highlight.js\lib\index.js:88
:31)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at highlightUtil (D:\blogfile\node_modules\hexo-util\dist\highlight.js:19:16
)
    at Hexo.highlightFilter (D:\blogfile\node_modules\hexo\dist\plugins\highligh
t\highlight.js:41:12)
    at SyntaxHighlight.exec (D:\blogfile\node_modules\hexo\dist\extend\syntax_hi
ghlight.js:21:24)
    at D:\blogfile\node_modules\hexo\dist\plugins\filter\before_post_render\back
tick_code_block.js:49:44
    at String.replace (<anonymous>)
    at Hexo.backtickCodeBlock (D:\blogfile\node_modules\hexo\dist\plugins\filter
\before_post_render\backtick_code_block.js:11:36)
    at Hexo.tryCatcher (D:\blogfile\node_modules\bluebird\js\release\util.js:16:
23)
    at Hexo.<anonymous> (D:\blogfile\node_modules\bluebird\js\release\method.js:
15:34)

beast@gentle-beast MINGW64 /d/blogfile
$ npm update
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memo
ry. Do not use it. Check out lru-cache if you want a good and tested way to coal
esce async requests by a key value, which is much more comprehensive and powerfu
l.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supporte
d
npm warn deprecated abab@2.0.6: Use your platform's native atob() and btoa() met
hods instead
npm warn deprecated domexception@4.0.0: Use your platform's native DOMException
instead
npm warn deprecated cuid@2.1.8: Cuid and other k-sortable and non-cryptographic
ids (Ulid, ObjectId, KSUID, all UUIDs) are all insecure. Use @paralleldrive/cuid
2 instead.

added 3 packages, removed 1 package, and changed 224 packages in 3m

23 packages are looking for funding
  run `npm fund` for details

beast@gentle-beast MINGW64 /d/blogfile
$ npm uninstall highlight.js

up to date in 1s

23 packages are looking for funding
  run `npm fund` for details

beast@gentle-beast MINGW64 /d/blogfile
$ npm install highlight.js

up to date in 1s

23 packages are looking for funding
  run `npm fund` for details

beast@gentle-beast MINGW64 /d/blogfile
$ npm uninstall highlight.js

up to date in 1s

23 packages are looking for funding
  run `npm fund` for details

beast@gentle-beast MINGW64 /d/blogfile
$ cnpm install highlight.js
√ Linked 1 latest versions fallback to D:\blogfile\node_modules\.store\node_modu
les
√ Installed 1 packages on D:\blogfile
√ All packages installed (1 packages installed from npm registry, used 7s(networ
k 7s), speed 0B/s, json 0(0B), tarball 0B, manifests cache hit 1, etag hit 1 / m
iss 0)

dependencies:
+ highlight.js ^11.10.0


beast@gentle-beast MINGW64 /d/blogfile
$ cnpm cache clean --force
npm WARN using --force Recommended protections disabled.

beast@gentle-beast MINGW64 /d/blogfile
$ rm -rf node_modules

beast@gentle-beast MINGW64 /d/blogfile
$ cnpm install
√ Linked 208 latest versions fallback to D:\blogfile\node_modules\.store\node_mo
dules
deprecate hexo-renderer-stylus@3.0.1 › stylus@0.62.0 › glob@^7.1.6 Glob versions
 prior to v9 are no longer supported
deprecate hexo-renderer-stylus@3.0.1 › stylus@0.62.0 › glob@7.2.3 › inflight@^1.
0.4 This module is not supported, and leaks memory. Do not use it. Check out lru
-cache if you want a good and tested way to coalesce async requests by a key val
ue, which is much more comprehensive and powerful.
deprecate hexo-renderer-marked@6.3.0 › jsdom@20.0.3 › domexception@^4.0.0 Use yo
ur platform's native DOMException instead
deprecate hexo-renderer-marked@6.3.0 › jsdom@20.0.3 › abab@^2.0.6 Use your platf
orm's native atob() and btoa() methods instead
deprecate hexo@7.3.0 › warehouse@5.0.1 › cuid@^2.1.8 Cuid and other k-sortable a
nd non-cryptographic ids (Ulid, ObjectId, KSUID, all UUIDs) are all insecure. Us
e @paralleldrive/cuid2 instead.
√ Run 1 script(s) in 835ms.
√ Installed 11 packages on D:\blogfile
√ All packages installed (220 packages installed from npm registry, used 10s(net
work 10s), speed 553.16KB/s, json 155(1.17MB), tarball 4.36MB, manifests cache h
it 54, etag hit 53 / miss 89)


beast@gentle-beast MINGW64 /d/blogfile
$ hexo g
INFO  Validating config
INFO  Start processing
INFO  Files loaded in 236 ms
INFO  Generated: archives/2024/index.html
INFO  Generated: archives/2024/08/index.html
INFO  Generated: archives/index.html
INFO  Generated: index.html
INFO  Generated: fancybox/jquery.fancybox.min.css
INFO  Generated: css/style.css
INFO  Generated: js/jquery-3.6.4.min.js
INFO  Generated: fancybox/jquery.fancybox.min.js
INFO  Generated: js/script.js
INFO  Generated: css/images/banner.jpg
INFO  Generated: 2024/08/13/hello-world/index.html
INFO  11 files generated in 238 ms
莫名其妙，不知道实际有没有用
