### ISSUE TITLE
Mac 下已经装了hexo,仍旧报错

### ISSUE THREAD

**Issue by liushaohua** [hexojs/hexo#1922]
全局已经安装hexo，当前项目下也装了  
blog git:(master) ✗ hexo
{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
ERROR Local hexo not found in ~/Documents/DATA/github/blog
ERROR Try running: 'npm install hexo --save'

**Comment by carl0schen** [comment]
Reference:
http://col.dog/2015/11/08/hello-world/#hexo_init
or
https://hexo.io/docs/troubleshooting.html#Error-with-DTrace-Mac-OS-X

**Comment by ttylcc** [comment]
建议把git, node, hexo全部升级到最新版本。。我之前就是因为node版本太低，提示module not found。

**Comment by ZanderZhang** [comment]
`npm install hexo --no-optional`
works for me

**Comment by perixiaowan** [comment]
请问报什么错呢
在2016年10月13日 09:40，Zander 写道:

npm install hexo --no-optional
works for me

**Comment by MaShiZhao** [comment]
$ npm install hexo --no-optional
if it doesn't work 
 try 
$ npm uninstall hexo-cli -g
$ npm install hexo-cli -g

**Comment by potcode** [comment]
@MaShiZhao solve my problem!!!    thanks!!!

**Comment by liujinlingchn** [comment]
@MaShiZhao 
 very well
thanks!!

**Comment by maobon** [comment]
@MaShiZhao Thanks a lot... break that error....

**Comment by LiangKim** [comment]
@MaShiZhao  
Thanks, it really works!

**Comment by chunInsane** [comment]
Thx~~

**Comment by phping1** [comment]
@MaShiZhao thanks!!!

**Comment by 2lei** [comment]
@MaShiZhao i tried but it doesn't work

**Comment by nl101531** [comment]
@MaShiZhao thanks!!!

**Comment by yuluo-ding** [comment]
@MaShiZhao thanks a lot

**Comment by duan007a** [comment]
@MaShiZhao thanks a lot

**Comment by shizihao123** [comment]
It saves my day , many thanks.

**Comment by imbyron** [comment]
```
$ npm uninstall hexo-cli -g
$ npm install hexo-cli -g
```
It works.
Thanks a lot.

**Comment by moreoronce** [comment]
still suffered this problem

i've tried all the two solution above this issue

`npm uninstall hexo-cli -g`
'npm install hexo-cli -g'

and 

'npm install hexo --opential'

but all of this two doesn't work

the error message i got is

`{ Error: Cannot find module './build/Release/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/hexo-cli/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/hexo-cli/node_modules/bunyan/lib/bunyan.js:79:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/default/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/hexo-cli/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/hexo-cli/node_modules/bunyan/lib/bunyan.js:79:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Debug/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/hexo-cli/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/hexo-cli/node_modules/bunyan/lib/bunyan.js:79:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Release/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/moreoronce/Dropbox/Documents/Daily/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/moreoronce/Dropbox/Documents/Daily/node_modules/bunyan/lib/bunyan.js:79:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/moreoronce/Dropbox/Documents/Daily/node_modules/hexo-log/lib/log.js:3:14)
    at Module._compile (module.js:571:32) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/default/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/moreoronce/Dropbox/Documents/Daily/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/moreoronce/Dropbox/Documents/Daily/node_modules/bunyan/lib/bunyan.js:79:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/moreoronce/Dropbox/Documents/Daily/node_modules/hexo-log/lib/log.js:3:14)
    at Module._compile (module.js:571:32) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Debug/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/moreoronce/Dropbox/Documents/Daily/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/moreoronce/Dropbox/Documents/Daily/node_modules/bunyan/lib/bunyan.js:79:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/moreoronce/Dropbox/Documents/Daily/node_modules/hexo-log/lib/log.js:3:14)
    at Module._compile (module.js:571:32) code: 'MODULE_NOT_FOUND' }`

Are there any other solution?

**Comment by wzqcongcong** [comment]
@MaShiZhao Thanks!

**Comment by sylan215** [comment]
@MaShiZhao Great, Thanks!

**Comment by shijinzhan** [comment]
@MaShiZhao 
thanks!!

**Comment by xibuka** [comment]
I resolve this issue by run following command, remove dtrace-provider and re-install hexo-cli with sudo

```
$ sudo npm uninstall hexo-cli -g
$ sudo npm uninstall dtrace-provider -g
$ sudo npm install hexo-cli -g --no-optional
```
without sudo, it didn't work for me.

**Comment by shaoguangleo** [comment]
@moreoronce  try using `npm install dtrace` again.

**Comment by Jhontomson** [comment]
I was in mac ，how can I fix it ?

**Comment by NoahDragon** [comment]
@Jhontomson have you tried `npm install hexo --no-optional`

**Comment by shenzekun** [comment]
@MaShiZhao very good

**Comment by gysxl** [comment]
@MaShiZhao Thanks!

**Comment by laiwenqiang** [comment]
$ npm install hexo --no-optional
if it doesn't work
try
$ npm uninstall hexo-cli -g
$ npm install hexo-cli -g
Thx!

**Comment by lujqme** [comment]
```
sudo npm uninstall hexo-cli -g
sudo npm uninstall dtrace-provider -g
sudo npm install hexo-cli -g --no-optional
```

when i execute these commands, but i doesn't work.
i use 
npm 3.10.10
node v6.11.0
Sierra 10.12.5 (16F73)

Error: Cannot find module './build/Release/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/hexo-cli/node_modules/_dtrace-provider@0.8.3@dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/hexo-cli/node_modules/_bunyan@1.8.10@bunyan/lib/bunyan.js:79:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/default/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/hexo-cli/node_modules/_dtrace-provider@0.8.3@dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/hexo-cli/node_modules/_bunyan@1.8.10@bunyan/lib/bunyan.js:79:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Debug/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/hexo-cli/node_modules/_dtrace-provider@0.8.3@dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/hexo-cli/node_modules/_bunyan@1.8.10@bunyan/lib/bunyan.js:79:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Release/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/lujianqiang/Development/hexo/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/lujianqiang/Development/hexo/node_modules/hexo/node_modules/bunyan/lib/bunyan.js:79:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/lujianqiang/Development/hexo/node_modules/hexo/node_modules/hexo-log/lib/log.js:3:14)
    at Module._compile (module.js:570:32) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/default/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/lujianqiang/Development/hexo/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/lujianqiang/Development/hexo/node_modules/hexo/node_modules/bunyan/lib/bunyan.js:79:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/lujianqiang/Development/hexo/node_modules/hexo/node_modules/hexo-log/lib/log.js:3:14)
    at Module._compile (module.js:570:32) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Debug/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/lujianqiang/Development/hexo/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/lujianqiang/Development/hexo/node_modules/hexo/node_modules/bunyan/lib/bunyan.js:79:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/lujianqiang/Development/hexo/node_modules/hexo/node_modules/hexo-log/lib/log.js:3:14)
    at Module._compile (module.js:570:32) code: 'MODULE_NOT_FOUND' }

**Comment by connor11528** [comment]
I was getting this same error when using Yarn. It is an issue with node/npm/yarn (https://github.com/react-community/create-react-native-app/issues/135)

make sure to use `npm i` instead of `yarn install`

**Comment by LeoEatle** [comment]
I solve this problem by doing this:
```bash
cd ./node_modules/hexo/node_modules/hexo-log/node_modules/bunyan
npm uninstall dtrace-provider --save
```
Because hexo does not really use the 'dtrace-provider' module. We can just uninstall it to avoid those error message. You can also re-install it as you wish.

**Comment by AotY** [comment]
npm uninstall hexo-cli -g
npm install hexo --no-optional -g

it works for me.

**Comment by wjw19854** [comment]
```
npm uninstall hexo-cli -g
npm install dtrace
npm install hexo-cli -g
```
this works for me.

**Comment by Anastasmloza** [comment]
I find that I can install it with npm install hexo 
But I can not install it with npm install hexo -g
So, I just go to the global catalog(Mine is /root/Cache/NPM/.npm-global/lib/node_modules) and install it with npm install hexo 
And then add the bin catalog of hexo to the environment path.
Hope this works for you

**Comment by kwanCCC** [comment]
@MaShiZhao  THX 🦈

**Comment by wendy-w** [comment]
npm uninstall hexo-cli -g
npm install dtrace
npm audit fix
npm install hexo-cli -g


this works for me too.
i think dtrace installation is necessary.

**Comment by mrzhouxiaofei** [comment]
@wendy-w nice work.

**Comment by StarKang1** [comment]
you can try 
cnpm install hexo --no-optional
