### ISSUE TITLE
ERROR Process failed: layout/_scripts/.DS_Store

### ISSUE THREAD

**Issue by zachary05** [hexojs/hexo#1929]
ERROR Process failed: layout/_scripts/.DS_Store
TypeError: Cannot read property 'compile' of undefined
    at View._precompile (/Users/Zachary/blog/node_modules/hexo/lib/theme/view.js:104:22)
    at View (/Users/Zachary/blog/node_modules/hexo/lib/theme/view.js:13:8)
    at new Theme._View.View (/Users/Zachary/blog/node_modules/hexo/lib/theme/index.js:37:10)
    at Theme.setView (/Users/Zachary/blog/node_modules/hexo/lib/theme/index.js:71:20)
    at /Users/Zachary/blog/node_modules/hexo/lib/theme/processors/view.js:14:14
    at tryCatcher (/Users/Zachary/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/Zachary/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/Users/Zachary/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Users/Zachary/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/Zachary/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/Users/Zachary/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:628:18)
    at Promise._resolveCallback (/Users/Zachary/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:423:57)
    at Promise._settlePromiseFromHandler (/Users/Zachary/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:514:17)
    at Promise._settlePromise (/Users/Zachary/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Users/Zachary/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/Zachary/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/Users/Zachary/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:628:18)
    at /Users/Zachary/blog/node_modules/hexo/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/Zachary/blog/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)

**Comment by carl0schen** [comment]
I use [Asepsis](http://asepsis.binaryage.com/) to solve .DS_Store problem.

**Comment by leesei** [comment]
#1855, #1793
