### ISSUE TITLE
Why  `{%}` in article will cause error?

### ISSUE THREAD

**Issue by Edenharder** [hexojs/hexo#1942]
I want to write \`{%}\` to generate `{%}`in article, but there will be some error when I run `hexo generate`.  While \`{\%}\` will generate `{\%}` which is not what I want.

The error says that

```
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: tag name expected
    at Error.exports.TemplateError (/Users/Eden/Documents/Git/hexo/node_modules/hexo/node_modules/nunjucks/src/lib.js:51:19)
    at Object.extend.fail (/Users/Eden/Documents/Git/hexo/node_modules/hexo/node_modules/nunjucks/src/parser.js:64:15)
    at Object.extend.parseStatement (/Users/Eden/Documents/Git/hexo/node_modules/hexo/node_modules/nunjucks/src/parser.js:510:18)
    at Object.extend.parseNodes (/Users/Eden/Documents/Git/hexo/node_modules/hexo/node_modules/nunjucks/src/parser.js:1151:30)
    at Object.extend.parseAsRoot (/Users/Eden/Documents/Git/hexo/node_modules/hexo/node_modules/nunjucks/src/parser.js:1177:42)
    at Object.module.exports.parse (/Users/Eden/Documents/Git/hexo/node_modules/hexo/node_modules/nunjucks/src/parser.js:1199:18)
    at Object.module.exports.compile (/Users/Eden/Documents/Git/hexo/node_modules/hexo/node_modules/nunjucks/src/compiler.js:1118:48)
    at Obj.extend._compile (/Users/Eden/Documents/Git/hexo/node_modules/hexo/node_modules/nunjucks/src/environment.js:444:35)
    at Obj.extend.compile (/Users/Eden/Documents/Git/hexo/node_modules/hexo/node_modules/nunjucks/src/environment.js:433:18)
    at null.<anonymous> (/Users/Eden/Documents/Git/hexo/node_modules/hexo/node_modules/nunjucks/src/environment.js:378:22)
    at Object.exports.withPrettyErrors (/Users/Eden/Documents/Git/hexo/node_modules/hexo/node_modules/nunjucks/src/lib.js:24:16)
    at Obj.extend.render (/Users/Eden/Documents/Git/hexo/node_modules/hexo/node_modules/nunjucks/src/environment.js:374:20)
    at Obj.extend.renderString (/Users/Eden/Documents/Git/hexo/node_modules/hexo/node_modules/nunjucks/src/environment.js:261:21)
    at /Users/Eden/Documents/Git/hexo/node_modules/hexo/lib/extend/tag.js:56:9
    at tryCatcher (/Users/Eden/Documents/Git/hexo/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/Users/Eden/Documents/Git/hexo/node_modules/hexo/node_modules/bluebird/js/main/promise.js:480:31)
    at new Promise (/Users/Eden/Documents/Git/hexo/node_modules/hexo/node_modules/bluebird/js/main/promise.js:70:37)
    at Tag.render (/Users/Eden/Documents/Git/hexo/node_modules/hexo/lib/extend/tag.js:55:10)
    at Object.tagFilter [as onRenderEnd] (/Users/Eden/Documents/Git/hexo/node_modules/hexo/lib/hexo/post.js:253:16)
    at /Users/Eden/Documents/Git/hexo/node_modules/hexo/lib/hexo/render.js:55:19
    at tryCatcher (/Users/Eden/Documents/Git/hexo/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/Eden/Documents/Git/hexo/node_modules/hexo/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/Eden/Documents/Git/hexo/node_modules/hexo/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/Users/Eden/Documents/Git/hexo/node_modules/hexo/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/Users/Eden/Documents/Git/hexo/node_modules/hexo/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/Eden/Documents/Git/hexo/node_modules/hexo/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/Eden/Documents/Git/hexo/node_modules/hexo/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

**Comment by Xuanwo** [comment]
You can use `{% raw %}` and `{% endraw %}`
