### ISSUE TITLE
hexo server doesn't work

### ISSUE THREAD

**Issue by searene** [hexojs/hexo#1980]
It doesn't work even if I init a new blog with it. This is the process to reproduce the problem:

```
hexo init blog
cd blog
npm install
hexo server
```

Then I got the error:

```
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: watch /tmp/blog/themes/landscape/languages ENOSPC
    at exports._errnoException (util.js:860:11)
    at FSWatcher.start (fs.js:1313:19)
    at Object.fs.watch (fs.js:1341:11)
    at createFsWatchInstance (/tmp/blog/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/tmp/blog/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/tmp/blog/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/tmp/blog/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/tmp/blog/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/tmp/blog/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:82:15)
FATAL watch /tmp/blog/themes/landscape/languages ENOSPC
Error: watch /tmp/blog/themes/landscape/languages ENOSPC
    at exports._errnoException (util.js:860:11)
    at FSWatcher.start (fs.js:1313:19)
    at Object.fs.watch (fs.js:1341:11)
    at createFsWatchInstance (/tmp/blog/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/tmp/blog/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/tmp/blog/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/tmp/blog/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/tmp/blog/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/tmp/blog/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:82:15)
```

What's wrong with it? It used to work, but I don't know what's going on with it now.

**Comment by searene** [comment]
Sorry I didn't see it before, the answer is right here

[ENOSPC-Error-Linux](https://hexo.io/docs/troubleshooting.html#ENOSPC-Error-Linux)
