### ISSUE TITLE
Dockerfile 造成 Highlight.js 錯誤

### ISSUE THREAD

**Issue by elct9620** [hexojs/hexo#2004]
當我在文章中插入 Dockerfile 的內容，會發生錯誤。

PS. 舊文章好像不會有這個問題

```
Unhandled rejection TypeError: Cannot set property 'lastIndex' of undefined
    at highlight (/Volumes/Transcend/blog.frost.tw/node_modules/highlight.js/lib/highlight.js:471:35)
    at /Volumes/Transcend/blog.frost.tw/node_modules/highlight.js/lib/highlight.js:521:21
    at Array.forEach (native)
    at Object.highlightAuto (/Volumes/Transcend/blog.frost.tw/node_modules/highlight.js/lib/highlight.js:520:40)
    at highlight (/Volumes/Transcend/blog.frost.tw/node_modules/hexo-util/lib/highlight.js:98:19)
    at highlightUtil (/Volumes/Transcend/blog.frost.tw/node_modules/hexo-util/lib/highlight.js:21:14)
    at /Volumes/Transcend/blog.frost.tw/node_modules/hexo/lib/plugins/filter/before_post_render/backtick_code_block.js:49:15
    at String.replace (native)
    at Hexo.backtickCodeBlock (/Volumes/Transcend/blog.frost.tw/node_modules/hexo/lib/plugins/filter/before_post_render/backtick_code_block.js:15:31)
    at Hexo.tryCatcher (/Volumes/Transcend/blog.frost.tw/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Volumes/Transcend/blog.frost.tw/node_modules/bluebird/js/release/method.js:15:34)
    at /Volumes/Transcend/blog.frost.tw/node_modules/hexo/lib/extend/filter.js:68:35
    at tryCatcher (/Volumes/Transcend/blog.frost.tw/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/Volumes/Transcend/blog.frost.tw/node_modules/bluebird/js/release/reduce.js:145:18)
    at Object.gotAccum (/Volumes/Transcend/blog.frost.tw/node_modules/bluebird/js/release/reduce.js:134:25)
    at Object.tryCatcher (/Volumes/Transcend/blog.frost.tw/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Volumes/Transcend/blog.frost.tw/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/Volumes/Transcend/blog.frost.tw/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromiseCtx (/Volumes/Transcend/blog.frost.tw/node_modules/bluebird/js/release/promise.js:596:10)
    at Async._drainQueue (/Volumes/Transcend/blog.frost.tw/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/Volumes/Transcend/blog.frost.tw/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Volumes/Transcend/blog.frost.tw/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```

**Comment by leesei** [comment]
Put content in [backticks](https://hexo.io/docs/tag-plugins.html#Backtick-Code-Block), [codeblock](https://hexo.io/docs/tag-plugins.html#Code-Block) or [raw](https://hexo.io/docs/tag-plugins.html#Raw) tags to bypass Nunjucks parsing issue.
https://hexo.io/docs/troubleshooting.html#Escape_Contents
See #1510 for discussion of disabling Nunjucks.

**Comment by be5invis** [comment]
@leesei The Nunjucks pass is applied **BEFORE** the article is sent to the renderer????

**Comment by leesei** [comment]
I suppose so, but don't have time to look into the code to confirm this.
Nunjucks parse template tags from the posts (`.md`), replace them with html before parsing to the Markdown renderer.

**Comment by be5invis** [comment]
I've made a pr.

发自我的 iPhone

在 2017年3月30日，12:21，leesei <notifications@github.com<mailto:notifications@github.com>> 写道：


I suppose so, but don't have time to look into the code to confirm this.
Nunjucks parse template tags from the posts (.md), replace them with html before parsing to the Markdown renderer.

**Comment by leesei** [comment]
Can you try on the contents mentioned in #1510 and report back if they can be rendered correctly?

**Comment by be5invis** [comment]
I have a site using a custom renderer and I can confirm that with my PR and the option I added set to True, these contents can be properly handled .

发自我的 iPhone

在 2017年3月30日，12:25，leesei <notifications@github.com<mailto:notifications@github.com>> 写道：


Can you try on the contents mentioned in #1510<https://github.com/hexojs/hexo/issues/1510> and report back if they can be rendered correctly?

**Comment by leesei** [comment]
The PR is mostly related to #1510. Could we move the discussion over there?
Note this breaks all the [Tag Plugins](https://hexo.io/docs/tag-plugins.html)

**Comment by be5invis** [comment]
The option is set to False by default. When it is set to True it WILL turn off all tags.

发自我的 iPhone

在 2017年3月30日，12:29，leesei <notifications@github.com<mailto:notifications@github.com>> 写道：


The PR is mostly related to #1510<https://github.com/hexojs/hexo/issues/1510>. Could we move the discussion over there?
Note this breaks all the Tag Plugins<https://hexo.io/docs/tag-plugins.html>
