### ISSUE TITLE
Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by JackGuoFranklin** [hexojs/hexo#2006]
执行 hexo g 后
FATAL Cannot read property 'replace' of null
TypeError: Cannot read property 'replace' of null
    at /Users/guojunbing23/gitresouce/hexo/node_modules/hexo/lib/hexo/load_config.js:35:28
    at tryCatcher (/Users/guojunbing23/gitresouce/hexo/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/guojunbing23/gitresouce/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/Users/guojunbing23/gitresouce/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Users/guojunbing23/gitresouce/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/guojunbing23/gitresouce/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:683:18)
    at Async._drainQueue (/Users/guojunbing23/gitresouce/hexo/node_modules/hexo/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/guojunbing23/gitresouce/hexo/node_modules/hexo/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate](/Users/guojunbing23/gitresouce/hexo/node_modules/hexo/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback](timers.js:383:17)

**Comment by leesei** [comment]
Do refer to Hexo/plugin doc for properly configuring Hexo/your plugin
Also validate YAML with [Online YAML Parser](http://yaml-online-parser.appspot.com/)

**Comment by ulisesantana** [comment]
I have exactly the same issue, how do you fixed @JackGuoFranklin?
Only happens when  I am trying to generate. This the terminal output @leesei :
```
FATAL Cannot read property 'replace' of null
TypeError: Cannot read property 'replace' of null
    at /home/ulisesantana/apps/ulisesantana.github.io/node_modules/hexo/lib/hexo/load_config.js:34:30
    at tryCatcher (/home/ulisesantana/apps/ulisesantana.github.io/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ulisesantana/apps/ulisesantana.github.io/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/home/ulisesantana/apps/ulisesantana.github.io/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/home/ulisesantana/apps/ulisesantana.github.io/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/home/ulisesantana/apps/ulisesantana.github.io/node_modules/bluebird/js/release/promise.js:685:18)
    at Async._drainQueue (/home/ulisesantana/apps/ulisesantana.github.io/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/home/ulisesantana/apps/ulisesantana.github.io/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/home/ulisesantana/apps/ulisesantana.github.io/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback] (timers.js:529:5)
```

**Comment by simazhao** [comment]
check the js code, find out your must config "url" property.

**Comment by moqu79** [comment]
请不要把 url: http://yoursite.com/ 中url:后面的部分删掉。

**Comment by hezhii** [comment]
Though you don't have a personal site, don't delete the configuration of "url" in "_config.yml".

**Comment by OUYANGSIHAI** [comment]
when i write new blog ,it happen,how to fix?

**Comment by isFibonacci** [comment]
make sure there is a slash after root:
I delete it accidentally
'''
root: /
'''

**Comment by cugxuan** [comment]
I am sure I set `url and root`,but I meet the same question.

- hexo: 4.2.0
- next: 6.7.0
blog/_config.yml
```
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://blog.cugxuan.cn
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks
```


```
# xuan @ xuandeMacBook-Pro in ~/blog on git:blog x [15:05:49]
$ hexo g
INFO  Start processing
INFO  Files loaded in 553 ms
ERROR Render HTML failed: categories/index.html
TypeError: Cannot read property 'replace' of null
    at Hexo.externalLinkFilter (/Users/xuan/blog/node_modules/hexo/lib/plugins/filter/after_render/external_link.js:22:15)
    at Hexo.tryCatcher (/Users/xuan/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Users/xuan/blog/node_modules/bluebird/js/release/method.js:15:34)
    at /Users/xuan/blog/node_modules/hexo/lib/extend/filter.js:62:52
    at tryCatcher (/Users/xuan/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/Users/xuan/blog/node_modules/bluebird/js/release/reduce.js:166:18)
    at Object.gotAccum (/Users/xuan/blog/node_modules/bluebird/js/release/reduce.js:155:25)
    at Object.tryCatcher (/Users/xuan/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/xuan/blog/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/xuan/blog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/Users/xuan/blog/node_modules/bluebird/js/release/promise.js:641:10)
    at _drainQueueStep (/Users/xuan/blog/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/Users/xuan/blog/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/xuan/blog/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/xuan/blog/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
```
