### ISSUE TITLE
hexo server 出现错误

### ISSUE THREAD

**Issue by zhihaofans** [hexojs/hexo#2013]
```
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: watch /mnt/f/ubuntu/hexo/source/ EPERM
    at exports._errnoException (util.js:870:11)
    at FSWatcher.start (fs.js:1 2 3 4:19)
    at Object.fs.watch (fs.js:1262:11)
    at createFsWatchInstance (/mnt/f/ubuntu/hexo/node_modules/hexo/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/mnt/f/ubuntu/hexo/node_modules/hexo/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/mnt/f/ubuntu/hexo/node_modules/hexo/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/mnt/f/ubuntu/hexo/node_modules/hexo/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/mnt/f/ubuntu/hexo/node_modules/hexo/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/mnt/f/ubuntu/hexo/node_modules/hexo/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:82:15)
FATAL watch /mnt/f/ubuntu/hexo/source/ EPERM
Error: watch /mnt/f/ubuntu/hexo/source/ EPERM
    at exports._errnoException (util.js:870:11)
    at FSWatcher.start (fs.js:1234:19)
    at Object.fs.watch (fs.js:1262:11)
    at createFsWatchInstance (/mnt/f/ubuntu/hexo/node_modules/hexo/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/mnt/f/ubuntu/hexo/node_modules/hexo/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/mnt/f/ubuntu/hexo/node_modules/hexo/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/mnt/f/ubuntu/hexo/node_modules/hexo/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/mnt/f/ubuntu/hexo/node_modules/hexo/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/mnt/f/ubuntu/hexo/node_modules/hexo/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by Xuanwo** [comment]
EPERM 是权限问题，你确定hexo-server对你的这个文件夹有可读写权限么？

**Comment by zhihaofans** [comment]
@Xuanwo 我是在win10带的ubuntu 14.04上使用的，理论上ubuntu拥有/mnt/f/（即F盘）的可读写权限，因为我之前试过可以的，而且我在前面加了sudo也不行

**Comment by leesei** [comment]
能否試一下https://github.com/paulmillr/chokidar 本身在該環境是否正常

**Comment by MACDfree** [comment]
也是在win10 wsl下出现此问题

**Comment by MACDfree** [comment]
ping命令在用管理员权限启动cmd后可以使用

**Comment by familyld** [comment]
期待解决方案~

**Comment by yosef-gao** [comment]
同样有这个问题

**Comment by pipirt** [comment]
大家好，这是wsl不支持的文件系统看问题。在BashOnWindows相关的问题是
https://github.com/Microsoft/BashOnWindows/issues/216 。

这是目前正在开发中，但为他们投票给它的优先级在那里UserVoice的页面
https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13469097-support-for-filesystem-watchers-like-inotify

**Comment by NoahDragon** [comment]
Hexo对于系统底层的操作也是无能为力的啊，只能期待Windows能尽快解决了。
