### ISSUE TITLE
Codeblock Rendering Fails with '{{ Characters

### ISSUE THREAD

**Issue by jamespedwards42** [hexojs/hexo#2030]
## Environment Info

Node version(`node -v`)

```
v5.10.1
```
## Hexo Configuration

```
https://github.com/jamespedwards42/jamespedwards42.github.io/blob/source/_config.yml

```

Plugin version(`npm ls --depth 0`)

```
hexo-site@0.0.0 /Users/james/blog/jamespedwards42
├── hexo@3.2.2
├── hexo-deployer-git@0.2.0
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-feed@1.1.0
├── hexo-generator-index@0.2.0
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-marked@0.2.11
├── hexo-renderer-stylus@0.3.1
├── hexo-server@0.2.0
```
## BUG

I get the following rendering exception when adding code blocks with `{{` characters.  [Here is the code](https://github.com/jamespedwards42/alpine-redis/blob/swarm/swarm/redis-cluster/meetNodes.sh#L19) I'm trying to add.  If I escape the characters like `\{\{` it renders just fine.

```
Unhandled rejection Template render error: (unknown path) [Line 78, Column 69]
  expected variable end
    at Object.exports.prettifyError (/Users/james/blog/jamespedwards42/node_modules/nunjucks/src/lib.js:34:15)
    at Obj.extend.render (/Users/james/blog/jamespedwards42/node_modules/nunjucks/src/environment.js:468:27)
    at Obj.extend.renderString (/Users/james/blog/jamespedwards42/node_modules/nunjucks/src/environment.js:326:21)
    at /Users/james/blog/jamespedwards42/node_modules/hexo/lib/extend/tag.js:66:9
    at Promise._execute (/Users/james/blog/jamespedwards42/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/Users/james/blog/jamespedwards42/node_modules/bluebird/js/release/promise.js:475:18)
    at new Promise (/Users/james/blog/jamespedwards42/node_modules/bluebird/js/release/promise.js:77:14)
    at Tag.render (/Users/james/blog/jamespedwards42/node_modules/hexo/lib/extend/tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (/Users/james/blog/jamespedwards42/node_modules/hexo/lib/hexo/post.js:253:16)
    at /Users/james/blog/jamespedwards42/node_modules/hexo/lib/hexo/render.js:65:19
    at tryCatcher (/Users/james/blog/jamespedwards42/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/james/blog/jamespedwards42/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/Users/james/blog/jamespedwards42/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/Users/james/blog/jamespedwards42/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/Users/james/blog/jamespedwards42/node_modules/bluebird/js/release/promise.js:685:18)
    at Async._drainQueue (/Users/james/blog/jamespedwards42/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/james/blog/jamespedwards42/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/james/blog/jamespedwards42/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```

**Comment by Xuanwo** [comment]
Known issue.

**Comment by Xuanwo** [comment]
As for now, you can use `{{ raw }}` and `{{ endraw }}` for solution.

**Comment by jamespedwards42** [comment]
Where should I place those tags?  If I do the following it injects the posts' raw markdown into the code block.

```
{{ raw }}
readonly LOCAL_PORT=$(docker inspect --format='{{index .Config.Labels "com.docker.swarm.service.name"}}' "$LOCAL_CONTAINER_ID" | sed 's|.*-||')
{{ endraw }}
```

**Comment by Xuanwo** [comment]
Sorry, it's:
```
{% raw %}
content
{% endraw %}
```

**Comment by jamespedwards42** [comment]
Nice, that got it. Thank you.

Should I leave this open?  I can't find an open issue to close this under.

**Comment by Xuanwo** [comment]
Just keep it.

**Comment by stevenjoezhang** [comment]
There is a discussion about it #3259
I'm closing this issue. Please join the discussion there :)
