### ISSUE TITLE
Get YAMLException from _post/xxx.md file

### ISSUE THREAD

**Issue by chainkite** [hexojs/hexo#2031]
> before you submit your issue, please delete all the example code in template

## Environment Info

Node version(`node -v`)
```
v4.4.6
```

Plugin version(`npm ls --depth 0`)
```
hexo-site@0.0.0 ...
├── hexo@3.2.0
├── hexo-deployer-git@0.1.0
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-feed@1.1.0 extraneous
├── hexo-generator-index@0.2.0
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.1.1
├── hexo-renderer-marked@0.2.10
├── hexo-renderer-stylus@0.3.1
└── hexo-server@0.1.3
```

## For BUG

- BUG description

```
Get YAMLException from `_post/xxx.md` file
```

- the way to reproduce

```
hexo g
```

- log with hexo <command> --debug

```
hexo g --debug
07:21:02.491 DEBUG Hexo version: 3.2.0
07:21:02.494 DEBUG Working directory: blog_dir/
07:21:02.558 DEBUG Config loaded: blog_dir/_config.yml
07:21:02.713 DEBUG Plugin loaded: hexo-deployer-git
07:21:02.715 DEBUG Plugin loaded: hexo-generator-archive
07:21:02.716 DEBUG Plugin loaded: hexo-generator-index
07:21:02.718 DEBUG Plugin loaded: hexo-generator-category
07:21:02.720 DEBUG Plugin loaded: hexo-generator-tag
07:21:02.723 DEBUG Plugin loaded: hexo-renderer-ejs
07:21:02.785 DEBUG Plugin loaded: hexo-renderer-marked
07:21:02.786 DEBUG Plugin loaded: hexo-renderer-stylus
07:21:02.868 DEBUG Plugin loaded: hexo-server
07:21:02.870 DEBUG Loading database.
07:21:02.891 INFO  Start processing
07:21:02.917 DEBUG Processed: CNAME
07:21:02.947 DEBUG Processed: _posts/scala_hk_meet_up_#1.md
07:21:02.947 DEBUG Processed: _posts/why_play_java.md
07:21:02.959 DEBUG Processed: source/css/style.styl
07:21:02.959 DEBUG Processed: source/fancybox/blank.gif
07:21:02.960 DEBUG Processed: source/fancybox/fancybox_loading@2x.gif
07:21:02.960 DEBUG Processed: source/fancybox/fancybox_overlay.png
07:21:02.960 DEBUG Processed: source/fancybox/fancybox_loading.gif
07:21:02.961 DEBUG Processed: source/fancybox/fancybox_sprite.png
07:21:02.961 DEBUG Processed: source/fancybox/fancybox_sprite@2x.png
07:21:02.961 DEBUG Processed: source/fancybox/jquery.fancybox.css
07:21:02.961 DEBUG Processed: source/js/gallery.js
07:21:02.961 DEBUG Processed: source/fancybox/jquery.fancybox.pack.js
07:21:02.962 DEBUG Processed: source/js/jquery.imagesloaded.min.js
07:21:02.968 DEBUG Theme config loaded.
07:21:02.968 DEBUG Processed: _config.yml
07:21:02.978 DEBUG Processed: layout/category.ejs
07:21:02.978 DEBUG Processed: layout/archive.ejs
07:21:02.978 DEBUG Processed: layout/index.ejs
07:21:02.978 DEBUG Processed: layout/layout.ejs
07:21:02.978 DEBUG Processed: layout/page.ejs
07:21:02.978 DEBUG Processed: layout/post.ejs
07:21:02.980 ERROR Process failed: _posts/first_shoot_in_js_world.md
YAMLException: end of the stream or a document separator is expected at line 8, column 6:
    `npm`:
         ^
    at generateError (blog_dir/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
    at throwError (blog_dir/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
    at readDocument (blog_dir/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1508:5)
    at loadDocuments (blog_dir/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1544:5)
    at Object.load (blog_dir/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1561:19)
    at parseYAML (blog_dir/node_modules/hexo/node_modules/hexo-front-matter/lib/front_matter.js:80:21)
    at parse (blog_dir/node_modules/hexo/node_modules/hexo-front-matter/lib/front_matter.js:56:12)
    at blog_dir/node_modules/hexo/lib/plugins/processor/post.js:52:18
    at tryCatcher (blog_dir/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (blog_dir/node_modules/hexo/node_modules/bluebird/js/release/promise.js:501:35)
    at Promise._settlePromise (blog_dir/node_modules/hexo/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (blog_dir/node_modules/hexo/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (blog_dir/node_modules/hexo/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (blog_dir/node_modules/hexo/node_modules/bluebird/js/release/promise.js:630:18)
    at PromiseArray._resolve (blog_dir/node_modules/hexo/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (blog_dir/node_modules/hexo/node_modules/bluebird/js/release/promise_array.js:143:14)
    at PromiseArray._iterate (blog_dir/node_modules/hexo/node_modules/bluebird/js/release/promise_array.js:113:31)
    at PromiseArray.init [as _init] (blog_dir/node_modules/hexo/node_modules/bluebird/js/release/promise_array.js:77:10)
    at Promise._settlePromise (blog_dir/node_modules/hexo/node_modules/bluebird/js/release/promise.js:558:21)
    at Promise._settlePromise0 (blog_dir/node_modules/hexo/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (blog_dir/node_modules/hexo/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (blog_dir/node_modules/hexo/node_modules/bluebird/js/release/promise.js:630:18)
    at PromiseArray._resolve (blog_dir/node_modules/hexo/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (blog_dir/node_modules/hexo/node_modules/bluebird/js/release/promise_array.js:143:14)
    at Promise._settlePromise (blog_dir/node_modules/hexo/node_modules/bluebird/js/release/promise.js:566:26)
    at Promise._settlePromise0 (blog_dir/node_modules/hexo/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (blog_dir/node_modules/hexo/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (blog_dir/node_modules/hexo/node_modules/bluebird/js/release/promise.js:630:18)
    at Promise._resolveCallback (blog_dir/node_modules/hexo/node_modules/bluebird/js/release/promise.js:425:57)
    at Promise._settlePromiseFromHandler (blog_dir/node_modules/hexo/node_modules/bluebird/js/release/promise.js:516:17)
    at Promise._settlePromise (blog_dir/node_modules/hexo/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (blog_dir/node_modules/hexo/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (blog_dir/node_modules/hexo/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (blog_dir/node_modules/hexo/node_modules/bluebird/js/release/promise.js:630:18)
    at blog_dir/node_modules/hexo/node_modules/bluebird/js/release/nodeback.js:42:21
    at blog_dir/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
07:21:02.983 DEBUG Processed: languages/de.yml
07:21:02.983 DEBUG Processed: languages/es.yml
07:21:02.983 DEBUG Processed: languages/no.yml
07:21:02.983 DEBUG Processed: languages/default.yml
07:21:02.983 DEBUG Processed: languages/pl.yml
07:21:02.983 DEBUG Processed: languages/ru.yml
07:21:02.983 DEBUG Processed: languages/zh-CN.yml
07:21:02.983 DEBUG Processed: languages/zh-TW.yml
07:21:02.984 DEBUG Processed: source/css/font/fontawesome-webfont.eot
07:21:02.985 DEBUG Processed: source/css/font/fontawesome-webfont.woff
07:21:02.986 DEBUG Processed: layout/tag.ejs
07:21:02.987 DEBUG Processed: source/css/font/fontawesome-webfont.svg
07:21:02.987 DEBUG Processed: source/css/font/fontawesome-webfont.ttf
07:21:02.988 DEBUG Processed: layout/_partial/after_footer.ejs
07:21:02.989 DEBUG Processed: layout/_partial/archive.ejs
07:21:02.989 DEBUG Processed: layout/_partial/comment.ejs
07:21:02.989 DEBUG Processed: layout/_partial/article.ejs
07:21:02.989 DEBUG Processed: layout/_partial/facebook_comment.ejs
07:21:02.989 DEBUG Processed: layout/_partial/footer.ejs
07:21:02.989 DEBUG Processed: layout/_partial/google_analytics.ejs
07:21:02.989 DEBUG Processed: layout/_partial/head.ejs
07:21:02.989 DEBUG Processed: layout/_partial/header.ejs
07:21:02.989 DEBUG Processed: layout/_partial/pagination.ejs
07:21:02.989 DEBUG Processed: layout/_partial/sidebar.ejs
07:21:02.989 DEBUG Processed: layout/_widget/category.ejs
07:21:02.989 DEBUG Processed: layout/_widget/search.ejs
07:21:02.989 DEBUG Processed: layout/_widget/recent_posts.ejs
07:21:02.989 DEBUG Processed: layout/_widget/tag.ejs
07:21:02.990 DEBUG Processed: layout/_widget/tagcloud.ejs
07:21:02.990 DEBUG Processed: layout/_partial/post/category.ejs
07:21:03.000 DEBUG Processed: layout/_partial/post/gallery.ejs
07:21:03.000 DEBUG Processed: layout/_partial/post/share.ejs
07:21:03.000 DEBUG Processed: layout/_partial/post/tag.ejs
07:21:03.000 DEBUG Processed: layout/_partial/post/title.ejs
07:21:03.013 DEBUG Generator: page
07:21:03.013 DEBUG Generator: post
07:21:03.013 DEBUG Generator: archive
07:21:03.013 DEBUG Generator: index
07:21:03.013 DEBUG Generator: category
07:21:03.013 DEBUG Generator: tag
07:21:03.014 DEBUG Generator: asset
07:21:03.017 INFO  Files loaded in 147 ms
07:21:03.022 DEBUG Rendering post: 2016/06/09/why_play_java/index.html
07:21:03.027 DEBUG Rendering post: 2016/05/12/scala_hk_meet_up_#1/index.html
07:21:03.028 DEBUG Rendering archive: archives/index.html
07:21:03.031 DEBUG Rendering archive: archives/2016/index.html
07:21:03.031 DEBUG Rendering archive: archives/2016/05/index.html
07:21:03.032 DEBUG Rendering archive: archives/2016/06/index.html
07:21:03.033 DEBUG Rendering index: index.html
07:21:03.176 INFO  0 files generated in 159 ms
07:21:03.182 DEBUG Database saved
```

**Comment by Xuanwo** [comment]
Paste the content of `_posts/first_shoot_in_js_world.md`

**Comment by chainkite** [comment]
```
## First Shoot in Javascript World

Trying hard to have a hand in in js world...
Then, being killed

**Build Tool**

`npm`: 

* mostly for back-end stuffs (Node.js)
* nested dependencies management

`bower`: 

* strictly, not a build tool, but a package manager
* mostly for front-end stuffs (CSS/HTML Templates/...)
* flat dependencies management (it's not acceptable there are 3 jQuery in your front-end project)
* BTW, we install `bower` through `npm`, hahaha

`gulp`:

* a task runner, install through `npm` as well
* plenty of plugins
* usage example: minify all the js/css files and so on

`nvm`: 

* a version manager for `Node.js`, easily switch current version of node
* In js world (type unsafe), things seem not very compatible with historical versions.

*p.s.* 
In `scala` world, `sbt` and its plugins takeover everything above.

--

**Test**

`jasmine`: Behavior-Driven Development Framework

`karma`:

* test runner
* use the browser js engine to test

`protractor`:

* angular's e2e test framework, with selenium
* real and live browser test

---

**AngularJS**

Module -> Directive -> Component

**ReactJS**


***To Be Continue***

---
**REF**
[nvm](https://github.com/creationix/nvm)
[bower](http://bower.io)
[npm](https://www.npmjs.com)
[bower vs. npm](http://ng-learn.org/2013/11/Bower-vs-npm/)
[jasmine](https://github.com/jasmine/jasmine)
[karma](https://github.com/karma-runner/karma)
[A Beginners Guide to the Task Runner Gulp](http://andy-carter.com/blog/a-beginners-guide-to-the-task-runner-gulp)
[A Beginners Guide to Package Manager Bower and Using Gulp to Manage Components](http://andy-carter.com/blog/a-beginners-guide-to-package-manager-bower-and-using-gulp-to-manage-components)
```

**Comment by Xuanwo** [comment]
Did you add meta info in this post?
Something like :
```
---
title: intro
date: 2016-07-10 18:00
---
```

**Comment by chainkite** [comment]
Where does this meta info need to be?
I have no idea that I manually added meta info in my previous posts and they are generated successfully.

**Comment by Xuanwo** [comment]
The content between first two `---` will be treat as meta data.
So the `npm` was treat as a key, try to add a meta data to see if the problem fixed.

**Comment by chainkite** [comment]
@Xuanwo Got it. It works now. Thx~
