### ISSUE TITLE
hexo server issue

### ISSUE THREAD

**Issue by ZhackerZ** [hexojs/hexo#2036]
```
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: (unknown path)
  SyntaxError: Unexpected token ILLEGAL
    at Object.exports.prettifyError (/Users/macbookair/Documents/blog/node_modules/hexo/node_modules/nunjucks/src/lib.js:34:15)
    at Obj.extend.render (/Users/macbookair/Documents/blog/node_modules/hexo/node_modules/nunjucks/src/environment.js:468:27)
    at Obj.extend.renderString (/Users/macbookair/Documents/blog/node_modules/hexo/node_modules/nunjucks/src/environment.js:326:21)
    at /Users/macbookair/Documents/blog/node_modules/hexo/lib/extend/tag.js:66:9
    at Promise._execute (/Users/macbookair/Documents/blog/node_modules/hexo/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/Users/macbookair/Documents/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:473:18)
    at new Promise (/Users/macbookair/Documents/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:77:14)
    at Tag.render (/Users/macbookair/Documents/blog/node_modules/hexo/lib/extend/tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (/Users/macbookair/Documents/blog/node_modules/hexo/lib/hexo/post.js:253:16)
    at /Users/macbookair/Documents/blog/node_modules/hexo/lib/hexo/render.js:63:19
    at tryCatcher (/Users/macbookair/Documents/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/macbookair/Documents/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/Users/macbookair/Documents/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Users/macbookair/Documents/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/macbookair/Documents/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:683:18)
    at Async._drainQueue (/Users/macbookair/Documents/blog/node_modules/hexo/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/macbookair/Documents/blog/node_modules/hexo/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/macbookair/Documents/blog/node_modules/hexo/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
FATAL (unknown path)
  SyntaxError: Unexpected token ILLEGAL
Template render error: (unknown path)
  SyntaxError: Unexpected token ILLEGAL
    at Object.exports.prettifyError (/Users/macbookair/Documents/blog/node_modules/hexo/node_modules/nunjucks/src/lib.js:34:15)
    at Obj.extend.render (/Users/macbookair/Documents/blog/node_modules/hexo/node_modules/nunjucks/src/environment.js:468:27)
    at Obj.extend.renderString (/Users/macbookair/Documents/blog/node_modules/hexo/node_modules/nunjucks/src/environment.js:326:21)
    at /Users/macbookair/Documents/blog/node_modules/hexo/lib/extend/tag.js:66:9
    at Promise._execute (/Users/macbookair/Documents/blog/node_modules/hexo/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/Users/macbookair/Documents/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:473:18)
    at new Promise (/Users/macbookair/Documents/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:77:14)
    at Tag.render (/Users/macbookair/Documents/blog/node_modules/hexo/lib/extend/tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (/Users/macbookair/Documents/blog/node_modules/hexo/lib/hexo/post.js:253:16)
    at /Users/macbookair/Documents/blog/node_modules/hexo/lib/hexo/render.js:63:19
    at tryCatcher (/Users/macbookair/Documents/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/macbookair/Documents/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/Users/macbookair/Documents/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Users/macbookair/Documents/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/macbookair/Documents/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:683:18)
    at Async._drainQueue (/Users/macbookair/Documents/blog/node_modules/hexo/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/macbookair/Documents/blog/node_modules/hexo/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/macbookair/Documents/blog/node_modules/hexo/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by Xuanwo** [comment]
贴config.yml

**Comment by ZhackerZ** [comment]
# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: random

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/ZhackerZ/ZhackerZ.github.io.git
  branch: master

我使用了一个random的主题。今天hexo server突然不work了，这是random里的config.yml

# stylesheets loaded in the <head>
stylesheets:
- /css/random.css
- /css/vegas.min.css
- /css/highlight-railscasts.css
- /css/jquery.fancybox.css
- /css/iconfont/iconfont.css
- /css/jquery.fancybox-thumbs.css
- /css/plyr.css

# scripts loaded in the end of the body
scripts:
- /js/jquery-2.2.3.min.js
- /js/vegas.min.js
- /js/random.js
- /js/highlight.pack.js
- /js/jquery.mousewheel.pack.js
- /js/jquery.fancybox.pack.js
- /js/jquery.fancybox-thumbs.js
- /js/plyr.js

backgroundImages:
- /images/1.jpg
- /images/2.jpg
- /images/3.jpg
- /images/4.jpg
- /images/7.jpg
- /images/9.jpg
- /images/12.jpg
- /images/13.jpg

vegasConfig:
  # more about config http://vegas.jaysalvat.com/documentation/settings/
  #animation: 'random'
  #transition: 'swirlRight'
  preload­Image: true
  transition:
    - slideLeft2
    - slideRight2
    - zoomIn
    - swirLeft
    - swirRight
    - flash
    - flash2
  timer: true
  delay: 5000
  shuffle: true
  count: 28

unsplashConfig:
  # more about config on https://unsplash.it/
  # blur: true
  gravity: 'north' # north, east, south, west, center
  # greyscale: true

avatar: /images/me.jpeg

# do not like fancybox, set this as false, this will turn it off
fancybox: true

# set the visibility of hide button in left bottom.
hideButtonVisibility: true

#avatar: 

不过我认为应该不是config.yml的问题，因为我之前用hexo一直是没问题的

**Comment by ZhackerZ** [comment]
`# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: random

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/ZhackerZ/ZhackerZ.github.io.git
  branch: master
`
我觉得应该不是config.yml的问题吧，这个我一直没动过，之前post都是可以的，会不会是dependency的问题？谢~

**Comment by Xuanwo** [comment]
如果之前可以，请说清楚从之前到现在你做了哪些操作。

**Comment by ZhackerZ** [comment]
没有改过东西，只是加了一个新的post....难道加post只能用hexo new 这个command不可以直接在目录里添加吗？

**Comment by Xuanwo** [comment]
不要相信玄学，把post的位置和内容贴出来。

**Comment by xialeizhou** [comment]
@ZhackerZ  你丫新增post时正文上面部分没写全或者有错误吧?

**Comment by ZhackerZ** [comment]
ok，谢谢找到问题了，可以关了。。。

**Comment by vsxen** [comment]
怎么解决的？@ZhackerZ
