### ISSUE TITLE
Fail to start server with hexo 3.2.2

### ISSUE THREAD

**Issue by perqin** [hexojs/hexo#2037]
## Environment Info

Node version(`node -v`)

```
v6.0.0
```

Your site `_config.yml`

```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Perqin's Blog
subtitle: Maintaining...
description:
author: Perqin
language: zh
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://blog.perqin.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: README.md

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 1
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: made

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:perqin/perqin.github.io.git
  branch: master

```

Your theme `_config.yml`

```
```

Plugin version(`npm ls --depth 0`)

```
hexo-site@0.0.0 /mnt/d/Workspaces/Hexo/source.perqin.github.io
├── hexo@3.2.2
├── hexo-browsersync@0.2.0
├── hexo-deployer-git@0.1.0
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-feed@1.1.0
├── hexo-generator-index@0.2.0
├── hexo-generator-sitemap@1.1.2
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-jade@0.3.0
├── hexo-renderer-less@0.1.3
├── hexo-renderer-marked@0.2.11
├── hexo-renderer-stylus@0.3.1
└── hexo-server@0.2.0
```
## For BUG
- Unable to start server after update hexo from 3.2.0 to 3.2.2
- run `hexo server`
- CLI output:

```
19:44:08.105 DEBUG Hexo version: 3.2.2
19:44:08.109 DEBUG Working directory: /mnt/d/Workspaces/Hexo/source.perqin.github.io/
19:44:08.490 DEBUG Config loaded: /mnt/d/Workspaces/Hexo/source.perqin.github.io/_config.yml
19:44:08.614 DEBUG Plugin loaded: hexo-browsersync
19:44:08.641 DEBUG Plugin loaded: hexo-deployer-git
19:44:08.652 DEBUG Plugin loaded: hexo-generator-archive
19:44:08.719 DEBUG Plugin loaded: hexo-generator-feed
19:44:08.733 DEBUG Plugin loaded: hexo-generator-category
19:44:08.739 DEBUG Plugin loaded: hexo-renderer-ejs
19:44:08.745 DEBUG Plugin loaded: hexo-generator-tag
19:44:08.748 DEBUG Plugin loaded: hexo-renderer-stylus
(node:1075) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
19:44:08.840 DEBUG Plugin loaded: hexo-renderer-less
19:44:08.858 DEBUG Plugin loaded: hexo-renderer-marked
19:44:09.343 DEBUG Plugin loaded: hexo-renderer-jade
19:44:09.349 DEBUG Plugin loaded: hexo-generator-index
19:44:09.354 DEBUG Plugin loaded: hexo-generator-sitemap
19:44:09.520 DEBUG Plugin loaded: hexo-server
19:44:09.600 FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: EINVAL: invalid argument, uv_interface_addresses
    at Error (native)
    at getIp (/mnt/d/Workspaces/Hexo/source.perqin.github.io/node_modules/dev-ip/lib/dev-ip.js:21:43)
    at Object.<anonymous> (/mnt/d/Workspaces/Hexo/source.perqin.github.io/node_modules/browser-sync/lib/utils.js:4:38)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/d/Workspaces/Hexo/source.perqin.github.io/node_modules/browser-sync/lib/snippet.js:9:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/d/Workspaces/Hexo/source.perqin.github.io/node_modules/browser-sync/lib/hooks.js:5:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/d/Workspaces/Hexo/source.perqin.github.io/node_modules/browser-sync/lib/browser-sync.js:3:23)
    at Module._compile (module.js:541:32)
19:44:09.610 DEBUG Database saved
19:44:09.612 FATAL EINVAL: invalid argument, uv_interface_addresses
Error: EINVAL: invalid argument, uv_interface_addresses
    at Error (native)
    at getIp (/mnt/d/Workspaces/Hexo/source.perqin.github.io/node_modules/dev-ip/lib/dev-ip.js:21:43)
    at Object.<anonymous> (/mnt/d/Workspaces/Hexo/source.perqin.github.io/node_modules/browser-sync/lib/utils.js:4:38)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/d/Workspaces/Hexo/source.perqin.github.io/node_modules/browser-sync/lib/snippet.js:9:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/d/Workspaces/Hexo/source.perqin.github.io/node_modules/browser-sync/lib/hooks.js:5:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/d/Workspaces/Hexo/source.perqin.github.io/node_modules/browser-sync/lib/browser-sync.js:3:23)
    at Module._compile (module.js:541:32)
```

**Comment by lcnju** [comment]
the problem is more related to bash on windows.
see [BashOnWindows issues](https://github.com/Microsoft/BashOnWindows/issues/468)
and another similar problem [node issues](https://github.com/nodejs/node/issues/7150)
