### ISSUE TITLE
 Cannot find module 'async-each' 

### ISSUE THREAD

**Issue by Everfighting** [hexojs/hexo#2061]
在添加谷歌跟百度 sitemap过程中，hexo generate发生错误。

错误信息如下,不知道有没有大神能够帮忙解决下。

$ hexo g
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: Cannot find module 'async-each'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (E:\blog\node_modules\hexo-generator-sitemap\node_modules\nunjucks\node_modules\chokidar\index.js:5:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (E:\blog\node_modules\hexo-generator-sitemap\node_modules\nunjucks\src\node-loaders.js:7:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (E:\blog\node_modules\hexo-generator-sitemap\node_modules\nunjucks\src\loaders.js:3:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (E:\blog\node_modules\hexo-generator-sitemap\node_modules\nunjucks\src\environment.js:9:23)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (E:\blog\node_modules\hexo-generator-sitemap\node_modules\nunjucks\index.js:4:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at module.exports (E:\blog\node_modules\hexo-generator-sitemap\lib\template.js:10:18)
    at Hexo.module.exports (E:\blog\node_modules\hexo-generator-sitemap\lib\generator.js:24:13)
    at Hexo.tryCatcher (E:\blog\node_modules\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (E:\blog\node_modules\hexo\node_modules\bluebird\js\release\method.js:15:34)
    at E:\blog\node_modules\hexo\lib\hexo\index.js:337:24
    at tryCatcher (E:\blog\node_modules\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (E:\blog\node_modules\hexo\node_modules\bluebird\js\release\map.js:57:38)
FATAL Cannot find module 'async-each'
Error: Cannot find module 'async-each'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (E:\blog\node_modules\hexo-generator-sitemap\node_modules\nunjucks\node_modules\chokidar\index.js:5:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (E:\blog\node_modules\hexo-generator-sitemap\node_modules\nunjucks\src\node-loaders.js:7:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (E:\blog\node_modules\hexo-generator-sitemap\node_modules\nunjucks\src\loaders.js:3:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (E:\blog\node_modules\hexo-generator-sitemap\node_modules\nunjucks\src\environment.js:9:23)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (E:\blog\node_modules\hexo-generator-sitemap\node_modules\nunjucks\index.js:4:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at module.exports (E:\blog\node_modules\hexo-generator-sitemap\lib\template.js:10:18)
    at Hexo.module.exports (E:\blog\node_modules\hexo-generator-sitemap\lib\generator.js:24:13)
    at Hexo.tryCatcher (E:\blog\node_modules\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (E:\blog\node_modules\hexo\node_modules\bluebird\js\release\method.js:15:34)
    at E:\blog\node_modules\hexo\lib\hexo\index.js:337:24
    at tryCatcher (E:\blog\node_modules\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (E:\blog\node_modules\hexo\node_modules\bluebird\js\release\map.js:57:38)

**Comment by Everfighting** [comment]
后面使用npm安装该模块 
npm install async-each 解决了该模块的缺失
但是又冒出了 async-each anymatch  glob-parent 等模块缺失 
我想问下有没有一道命令可以所有模块都装上？

**Comment by Everfighting** [comment]
问题解决了，根据提示装了七八个包之后正常了。
