### ISSUE TITLE
最新Bug，js复制失败

### ISSUE THREAD

**Issue by netcan** [hexojs/hexo#2103]
在我的主题js文件夹下存入下列代码`github-calendar.js`：

``` js
define(function (require, exports, module) {"use strict";

const parse = require("github-calendar-parser")
    , $ = require("elly")
    , addSubtractDate = require("add-subtract-date")
    , formatoid = require("formatoid")
    ;

const DATE_FORMAT1 = "MMM D, YYYY"
    , DATE_FORMAT2 = "MMMM D"
    ;

module.exports = function GitHubCalendar (container, username, options) {

    container = $(container);

    options = options || {};
    options.summary_text = options.summary_text || `Summary of pull requests, issues opened, and commits made by <a href="https://github.com/${username}" target="blank">@${username}</a>`;

    if (options.global_stats === false) {
        container.style.minHeight = "175px";
    }

    // We need a proxy for CORS
    // Thanks, @izuzak (https://github.com/izuzak/urlreq)
    options.proxy = options.proxy || function (url) {
        return "https://urlreq.appspot.com/req?method=GET&url=" + url;
    };

    let fetchCalendar = () => fetch(options.proxy("https://github.com/" + username)).then(response => {
        return response.text()
    }).then(body => {
        let div = document.createElement("div");
        div.innerHTML = body;
        let cal = div.querySelector("#contributions-calendar");
        cal.querySelector(".left.text-muted").innerHTML = options.summary_text;

        // If 'include-fragment' with spinner img loads instead of the svg, fetchCalendar again
        if (cal.querySelector("include-fragment")) {
            setTimeout(fetchCalendar, 500);
        } else {
            if (options.global_stats !== false) {
                let parsed = parse($("svg", cal).outerHTML)
                  , currentStreakInfo = parsed.current_streak
                                      ? `${formatoid(parsed.current_streak_range[0], DATE_FORMAT2)} – ${formatoid(parsed.current_streak_range[1], DATE_FORMAT2)}`
                                      : parsed.last_contributed
                                      ? `Last contributed in ${formatoid(parsed.last_contributed, DATE_FORMAT2)}.`
                                      : "Rock - Hard Place"
                  , longestStreakInfo = parsed.longest_streak
                                      ? `${formatoid(parsed.longest_streak_range[0], DATE_FORMAT2)} – ${formatoid(parsed.longest_streak_range[1], DATE_FORMAT2)}`
                                      : parsed.last_contributed
                                      ? `Last contributed in ${formatoid(parsed.last_contributed, DATE_FORMAT2)}.`
                                      : "Rock - Hard Place"
                  , firstCol = $("<div>", {
                        "class": "contrib-column contrib-column-first table-column"
                      , html: `<span class="text-muted">Contributions in the last year</span>
                               <span class="contrib-number">${parsed.last_year} total</span>
                               <span class="text-muted">${formatoid(addSubtractDate.subtract(new Date(), 1, "year"), DATE_FORMAT1)} – ${formatoid(new Date(), DATE_FORMAT1)}</span>`
                    })
                  , secondCol = $("<div>", {
                        "class": "contrib-column table-column"
                      , html: `<span class="text-muted">Longest streak</span>
                               <span class="contrib-number">${parsed.longest_streak} days</span>
                               <span class="text-muted">${longestStreakInfo}</span>`
                    })
                  , thirdCol = $("<div>", {
                        "class": "contrib-column table-column"
                      , html: `<span class="text-muted">Current streak</span>
                               <span class="contrib-number">${parsed.current_streak} days</span>
                               <span class="text-muted">${currentStreakInfo}</span>`
                    })
                  ;

                cal.appendChild(firstCol);
                cal.appendChild(secondCol);
                cal.appendChild(thirdCol);
            }

            container.innerHTML = cal.innerHTML;
        }
    }).catch(e => console.error(e));

    return fetchCalendar();
}

});
```

`hexo g`的时候，public/js下的`github-calendar.js`为空，不是说好的只是复制过去而已么= =其他js脚本正常。
然而`hexo s`会出现下列错误：

``` js
ERROR Asset render failed: js/github-calendar.js
Error
    at new JS_Parse_Error (eval at <anonymous> (F:\workspace\Netcan_web\blog\node_modules\.npminstall\uglify-js\2.7.0\uglify-js\tools\node.js:28:1), <anonymous>:1545:18)
    at js_error (eval at <anonymous> (F:\workspace\Netcan_web\blog\node_modules\.npminstall\uglify-js\2.7.0\uglify-js\tools\node.js:28:1), <anonymous>:1553:11)
    at parse_error (eval at <anonymous> (F:\workspace\Netcan_web\blog\node_modules\.npminstall\uglify-js\2.7.0\uglify-js\tools\node.js:28:1), <anonymous>:1677:9)
    at Object.next_token [as input] (eval at <anonymous> (F:\workspace\Netcan_web\blog\node_modules\.npminstall\uglify-js\2.7.0\uglify-js\tools\node.js:28:1), <anonymous>:1946:9)
    at next (eval at <anonymous> (F:\workspace\Netcan_web\blog\node_modules\.npminstall\uglify-js\2.7.0\uglify-js\tools\node.js:28:1), <anonymous>:2075:25)
    at expr_op (eval at <anonymous> (F:\workspace\Netcan_web\blog\node_modules\.npminstall\uglify-js\2.7.0\uglify-js\tools\node.js:28:1), <anonymous>:2813:13)
    at expr_ops (eval at <anonymous> (F:\workspace\Netcan_web\blog\node_modules\.npminstall\uglify-js\2.7.0\uglify-js\tools\node.js:28:1), <anonymous>:2827:16)
    at maybe_conditional (eval at <anonymous> (F:\workspace\Netcan_web\blog\node_modules\.npminstall\uglify-js\2.7.0\uglify-js\tools\node.js:28:1), <anonymous>:2832:20)
    at maybe_assign (eval at <anonymous> (F:\workspace\Netcan_web\blog\node_modules\.npminstall\uglify-js\2.7.0\uglify-js\tools\node.js:28:1), <anonymous>:2856:20)
    at maybe_assign (eval at <anonymous> (F:\workspace\Netcan_web\blog\node_modules\.npminstall\uglify-js\2.7.0\uglify-js\tools\node.js:28:1), <anonymous>:2864:32)
    at expression (eval at <anonymous> (F:\workspace\Netcan_web\blog\node_modules\.npminstall\uglify-js\2.7.0\uglify-js\tools\node.js:28:1), <anonymous>:2875:20)
    at simple_statement (eval at <anonymous> (F:\workspace\Netcan_web\blog\node_modules\.npminstall\uglify-js\2.7.0\uglify-js\tools\node.js:28:1), <anonymous>:2314:55)
    at eval (eval at <anonymous> (F:\workspace\Netcan_web\blog\node_modules\.npminstall\uglify-js\2.7.0\uglify-js\tools\node.js:28:1), <anonymous>:2183:19)
    at eval (eval at <anonymous> (F:\workspace\Netcan_web\blog\node_modules\.npminstall\uglify-js\2.7.0\uglify-js\tools\node.js:28:1), <anonymous>:2136:24)
    at block_ (eval at <anonymous> (F:\workspace\Netcan_web\blog\node_modules\.npminstall\uglify-js\2.7.0\uglify-js\tools\node.js:28:1), <anonymous>:2429:20)
    at eval (eval at <anonymous> (F:\workspace\Netcan_web\blog\node_modules\.npminstall\uglify-js\2.7.0\uglify-js\tools\node.js:28:1), <anonymous>:2401:25)
    at function_ (eval at <anonymous> (F:\workspace\Netcan_web\blog\node_modules\.npminstall\uglify-js\2.7.0\uglify-js\tools\node.js:28:1), <anonymous>:2407:15)
    at expr_atom (eval at <anonymous> (F:\workspace\Netcan_web\blog\node_modules\.npminstall\uglify-js\2.7.0\uglify-js\tools\node.js:28:1), <anonymous>:2622:24)
    at maybe_unary (eval at <anonymous> (F:\workspace\Netcan_web\blog\node_modules\.npminstall\uglify-js\2.7.0\uglify-js\tools\node.js:28:1), <anonymous>:2792:19)
    at expr_ops (eval at <anonymous> (F:\workspace\Netcan_web\blog\node_modules\.npminstall\uglify-js\2.7.0\uglify-js\tools\node.js:28:1), <anonymous>:2827:24)
    at maybe_conditional (eval at <anonymous> (F:\workspace\Netcan_web\blog\node_modules\.npminstall\uglify-js\2.7.0\uglify-js\tools\node.js:28:1), <anonymous>:2832:20)
    at maybe_assign (eval at <anonymous> (F:\workspace\Netcan_web\blog\node_modules\.npminstall\uglify-js\2.7.0\uglify-js\tools\node.js:28:1), <anonymous>:2856:20)
    at maybe_assign (eval at <anonymous> (F:\workspace\Netcan_web\blog\node_modules\.npminstall\uglify-js\2.7.0\uglify-js\tools\node.js:28:1), <anonymous>:2864:32)
    at expression (eval at <anonymous> (F:\workspace\Netcan_web\blog\node_modules\.npminstall\uglify-js\2.7.0\uglify-js\tools\node.js:28:1), <anonymous>:2875:20)
    at simple_statement (eval at <anonymous> (F:\workspace\Netcan_web\blog\node_modules\.npminstall\uglify-js\2.7.0\uglify-js\tools\node.js:28:1), <anonymous>:2314:55)
    at eval (eval at <anonymous> (F:\workspace\Netcan_web\blog\node_modules\.npminstall\uglify-js\2.7.0\uglify-js\tools\node.js:28:1), <anonymous>:2183:19)
    at eval (eval at <anonymous> (F:\workspace\Netcan_web\blog\node_modules\.npminstall\uglify-js\2.7.0\uglify-js\tools\node.js:28:1), <anonymous>:2136:24)
    at block_ (eval at <anonymous> (F:\workspace\Netcan_web\blog\node_modules\.npminstall\uglify-js\2.7.0\uglify-js\tools\node.js:28:1), <anonymous>:2429:20)
```

**Comment by NoahDragon** [comment]
还有这个问题么？如果还存在请reopen这个issue。

**Comment by netcan** [comment]
不知道，后来换替代脚本了。。
