### ISSUE TITLE
i meet this error.. what should i do? 

### ISSUE THREAD

**Issue by AL0n4k** [hexojs/hexo#2109]
my environment is:

```
C:\Users\AL0N4k>npm -v
2.15.9

C:\Users\AL0N4k>hexo -v
hexo-cli: 1.0.2
os: Windows_NT 6.1.7601 win32 x64
http_parser: 2.7.0
node: 4.5.0
v8: 4.5.103.37
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2h

C:\Users\AL0N4k>node -v
v4.5.0
```

the error out put is:

```
Connection reset by 192.30.253.112
fatal: sha1 file '<stdout>' write error: Broken pipe
fatal: The remote end hung up unexpectedly
error: failed to push some refs to 'git@github.com:AL0n4k/aL0n4k.github.io.git'
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: Connection reset by 192.30.253.112
fatal: sha1 file '<stdout>' write error: Broken pipe
fatal: The remote end hung up unexpectedly
error: failed to push some refs to 'git@github.com:AL0n4k/aL0n4k.github.io.git'

    at ChildProcess.<anonymous> (E:\Hexo\node_modules\hexo-deployer-git\node_modules\hexo-util\lib\spawn.js:37:17)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at ChildProcess.cp.emit (E:\Hexo\node_modules\hexo-deployer-git\node_modules\hexo-util\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:829:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
FATAL Connection reset by 192.30.253.112
fatal: sha1 file '<stdout>' write error: Broken pipe
fatal: The remote end hung up unexpectedly
error: failed to push some refs to 'git@github.com:AL0n4k/aL0n4k.github.io.git'
```

---

The Hexo Configuratoin is:

``` yml
# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: AL0N4k's Blog
subtitle: The night is endless.
description:
author: AL0N4k
language: default
timezone:

sidebar: false

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: Http://AL0N4k.CoM
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: 

# Category & Tag
default_category: code
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: spfk

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  # repo: https://github.com/aL0n4k/aL0n4k.github.io.git
  repo: git@github.com:AL0n4k/aL0n4k.github.io.git
  branch: master

```

i'm using ssh to connection to the github, in before, it worked fine in this way.
now i got the error in the above. what should i do?

**Comment by perixiaowan** [comment]
你在本地生成ssh的私钥和公钥了么，并将github上配置ssh了么？github》settings》ssh and GPG keys

**Comment by perixiaowan** [comment]
replace   'git@github.com:AL0n4k/aL0n4k.github.io.git?  ' by 
'git@github.com:aL0n4k/aL0n4k.github.io.git?  '

**Comment by AL0n4k** [comment]
yeah, SSH i have configured into my github settings. As you said, i try to replace repository url by "git@github.com:aL0n4k/aL0n4k.github.io.git" , but i get the error again.

**Comment by AL0n4k** [comment]
thanks a lot, it works when i try a few times again.
