### ISSUE TITLE
unable to access Permission denied

### ISSUE THREAD

**Issue by qing-song** [hexojs/hexo#2114]
> before you submit your issue, please delete all the example code in template
## Environment Info

Node version(`node -v`)

```
v6.4.0
```

Your site `_config.yml`

```
deploy:
  type:  git   
  repository:  https://github.com/qing-song/qing-song.github.com.git
  branch:  master
...
```

```
localhost:qingsong_blog wangshuai$ hexo d
INFO  Deploying: git
INFO  Clearing .deploy_git folder...
INFO  Copying files from public folder...
warning: unable to access '.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/gh_inspector-1.0.2/.gitignore': Permission denied
error: open(".rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/gh_inspector-1.0.2/.gitignore"): Permission denied
error: unable to index file .rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/gh_inspector-1.0.2/.gitignore
fatal: adding files failed
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: warning: unable to access '.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/gh_inspector-1.0.2/.gitignore': Permission denied
error: open(".rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/gh_inspector-1.0.2/.gitignore"): Permission denied
error: unable to index file .rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/gh_inspector-1.0.2/.gitignore
fatal: adding files failed

    at ChildProcess.<anonymous> (/Users/wangshuai/qingsong_blog/node_modules/hexo-util/lib/spawn.js:37:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
FATAL warning: unable to access '.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/gh_inspector-1.0.2/.gitignore': Permission denied
error: open(".rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/gh_inspector-1.0.2/.gitignore"): Permission denied
error: unable to index file .rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/gh_inspector-1.0.2/.gitignore
fatal: adding files failed

Error: warning: unable to access '.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/gh_inspector-1.0.2/.gitignore': Permission denied
error: open(".rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/gh_inspector-1.0.2/.gitignore"): Permission denied
error: unable to index file .rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/gh_inspector-1.0.2/.gitignore
fatal: adding files failed

    at ChildProcess.<anonymous> (/Users/wangshuai/qingsong_blog/node_modules/hexo-util/lib/spawn.js:37:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
just push question

what's the matter ?
```

**Comment by JimmieM** [comment]
Try writing 'sudo' before each line. For example:

sudo npm install -g
