### ISSUE TITLE
hexo g/d/init，then the shell shows "FATAL Cannot read property 'replace' of null,TypeError: Cannot read property 'replace' of null", how to solve this problem?

### ISSUE THREAD

**Issue by mg2015started** [hexojs/hexo#2141]
# error message

$ hexo g
FATAL Cannot read property 'replace' of null
TypeError: Cannot read property 'replace' of null
    at D:\hexo\node_modules\hexo\lib\hexo\load_config.js:35:28
    at tryCatcher (D:\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\hexo\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (D:\hexo\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (D:\hexo\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (D:\hexo\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (D:\hexo\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (D:\hexo\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues (D:\hexo\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback](timers.js:533:5)

**Comment by qiusheng2011** [comment]
me too

**Comment by loveCG** [comment]
me too

**Comment by NoahDragon** [comment]
Can you run ` hexo g --debug`, and list the output here?

**Comment by elvawyf** [comment]
11:10:40.910 DEBUG Hexo version: 3.2.2
11:10:40.912 DEBUG Working directory: ~/Hexo/
11:10:40.983 DEBUG Config loaded: ~/Hexo/_config.yml
11:10:40.987 FATAL Cannot read property 'replace' of null
TypeError: Cannot read property 'replace' of null

**Comment by moqu79** [comment]
have you guys delete the address in:
>  url: http://yoursite.com/
