### ISSUE TITLE
Fold gist

### ISSUE THREAD

**Issue by Explorare** [hexojs/hexo#2221]
Is it possible to config the lines a gist window shows? Maybe 20 lines with a vertical scroll bar.
Also support maximize or minimize the gist window with click.

Showing 100 lines of code at once may be too many for a post.

**Comment by NoahDragon** [comment]
Using [CSS style](http://stackoverflow.com/questions/22950812/gist-how-to-set-the-height-and-width-of-an-embedded-gist).

For example, set height and width to 500px:

```html
<style type="text/css">
  .gist {width:500px !important;}
  .gist-file
  .gist-data {max-height: 500px;max-width: 500px;}
</style>
```

**Comment by Explorare** [comment]
@NoahDragon So where is the suitable place to append these lines?  `\source\css\_custom\custom.styl` ?

**Comment by Neveryu** [comment]
@Explorare yes

**Comment by Explorare** [comment]
@Neveryu 
```
ERROR Asset render failed: css/main.css
ParseError: C:/Users/Explorare/Dropbox/Blog/themes/next/source/css/_custom/custom.styl:6:9
   2| <style type="text/css">
   3|   .gist {width:500px !important;}
   4|   .gist-file
   5|   .gist-data {max-height: 500px;max-width: 500px;}
   6| </style>
--------------^

expected "indent", got "eos"

    at Parser.error (C:\Users\Explorare\Dropbox\Blog\node_modules\stylus\lib\parser.js:259:11)
    at Parser.expect (C:\Users\Explorare\Dropbox\Blog\node_modules\stylus\lib\parser.js:287:12)
    at Parser.block (C:\Users\Explorare\Dropbox\Blog\node_modules\stylus\lib\parser.js:845:12)
    at Parser.selector (C:\Users\Explorare\Dropbox\Blog\node_modules\stylus\lib\parser.js:1555:24)
    at Parser.stmt (C:\Users\Explorare\Dropbox\Blog\node_modules\stylus\lib\parser.js:797:27)
    at Parser.statement (C:\Users\Explorare\Dropbox\Blog\node_modules\stylus\lib\parser.js:685:21)
    at Parser.parse (C:\Users\Explorare\Dropbox\Blog\node_modules\stylus\lib\parser.js:236:25)
    at Evaluator.importFile (C:\Users\Explorare\Dropbox\Blog\node_modules\stylus\lib\visitor\evaluator.js:74:20)
    at Evaluator.visitImport (C:\Users\Explorare\Dropbox\Blog\node_modules\stylus\lib\visitor\evaluator.js:906:27)
    at Evaluator.Visitor.visit (C:\Users\Explorare\Dropbox\Blog\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (C:\Users\Explorare\Dropbox\Blog\node_modules\stylus\lib\visitor\evaluator.js:156:18)
    at Evaluator.visitRoot (C:\Users\Explorare\Dropbox\Blog\node_modules\stylus\lib\visitor\evaluator.js:693:27)
    at Evaluator.Visitor.visit (C:\Users\Explorare\Dropbox\Blog\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (C:\Users\Explorare\Dropbox\Blog\node_modules\stylus\lib\visitor\evaluator.js:156:18)
    at Evaluator.evaluate (C:\Users\Explorare\Dropbox\Blog\node_modules\stylus\lib\visitor\evaluator.js:233:15)
    at Renderer.render (C:\Users\Explorare\Dropbox\Blog\node_modules\stylus\lib\renderer.js:86:26)
    at Hexo.module.exports (C:\Users\Explorare\Dropbox\Blog\node_modules\hexo-renderer-stylus\lib\renderer.js:53:6)
    at Hexo.tryCatcher (C:\Users\Explorare\Dropbox\Blog\node_modules\bluebird\js\main\util.js:26:23)
    at Hexo.ret (eval at <anonymous> (C:\Users\Explorare\Dropbox\Blog\node_modules\bluebird\js\main\promisify.js:163:12), <anonymous>:13:39)
    at C:\Users\Explorare\Dropbox\Blog\node_modules\hexo\lib\hexo\render.js:51:21
    at tryCatcher (C:\Users\Explorare\Dropbox\Blog\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\Users\Explorare\Dropbox\Blog\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (C:\Users\Explorare\Dropbox\Blog\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromises (C:\Users\Explorare\Dropbox\Blog\node_modules\bluebird\js\main\promise.js:697:14)
    at Async._drainQueue (C:\Users\Explorare\Dropbox\Blog\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (C:\Users\Explorare\Dropbox\Blog\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Explorare\Dropbox\Blog\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by Explorare** [comment]
@NoahDragon @Neveryu Remove line 1 and line 5 fix this problem. But met a new problem.
![image](https://cloud.githubusercontent.com/assets/5090766/19710816/b18d73a2-9b63-11e6-9c08-81ad6d73ef76.png)

**Comment by Explorare** [comment]
Clean all rules added above, only append one line 
`.gist-data {max-height: 500px;}`
fix the problem. @NoahDragon  @Neveryu Thanks for help.

![image](https://cloud.githubusercontent.com/assets/5090766/19711284/3dc66524-9b67-11e6-98a9-b6514f3f525a.png)

**Comment by Neveryu** [comment]
@Explorare  Thanks,you don`t need write `<style type="text/css">` and `</style>` on custom.styl.
