### ISSUE TITLE
Template render error when have a particular LaTeX formula

### ISSUE THREAD

**Issue by zhangtianle** [hexojs/hexo#2231]
When I have a particular LaTeX formula in my article, I used the "hexo g" command to generate the article, reported the following error, what is going on, thank you!

the LaTeX formula is $L({V_1},{V_2}) = \sum\nolimits_{i \in {V_1},j \in {V_2}} {{A_{ij}}}$ 

```
INFO  [hexo-inject] installing hotfix for hexojs/hexo#1791
INFO  [hexo-math] Using engine 'mathjax'
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: (unknown path) [Line 30, Column 233]
  expected variable end
    at Object.exports.prettifyError (D:\project\git\blog\node_modules\hexo\node_modules\nunjucks\src\lib.js:34:15)
    at Obj.extend.render (D:\project\git\blog\node_modules\hexo\node_modules\nunjucks\src\environment.js:469:27)
    at Obj.extend.renderString (D:\project\git\blog\node_modules\hexo\node_modules\nunjucks\src\environment.js:327:21)
    at D:\project\git\blog\node_modules\hexo\lib\extend\tag.js:66:9
    at Promise._execute (D:\project\git\blog\node_modules\hexo\node_modules\bluebird\js\release\debuggability.js:299:9)
    at Promise._resolveFromExecutor (D:\project\git\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:481:18)
    at new Promise (D:\project\git\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:77:14)
    at Tag.render (D:\project\git\blog\node_modules\hexo\lib\extend\tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (D:\project\git\blog\node_modules\hexo\lib\hexo\post.js:253:16)
    at D:\project\git\blog\node_modules\hexo\lib\hexo\render.js:65:19
    at tryCatcher (D:\project\git\blog\node_modules\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\project\git\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (D:\project\git\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (D:\project\git\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (D:\project\git\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (D:\project\git\blog\node_modules\hexo\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (D:\project\git\blog\node_modules\hexo\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\project\git\blog\node_modules\hexo\node_modules\bluebird\js\release\async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
FATAL (unknown path) [Line 30, Column 233]
  expected variable end
Template render error: (unknown path) [Line 30, Column 233]
  expected variable end
    at Object.exports.prettifyError (D:\project\git\blog\node_modules\hexo\node_modules\nunjucks\src\lib.js:34:15)
    at Obj.extend.render (D:\project\git\blog\node_modules\hexo\node_modules\nunjucks\src\environment.js:469:27)
    at Obj.extend.renderString (D:\project\git\blog\node_modules\hexo\node_modules\nunjucks\src\environment.js:327:21)
    at D:\project\git\blog\node_modules\hexo\lib\extend\tag.js:66:9
    at Promise._execute (D:\project\git\blog\node_modules\hexo\node_modules\bluebird\js\release\debuggability.js:299:9)
    at Promise._resolveFromExecutor (D:\project\git\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:481:18)
    at new Promise (D:\project\git\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:77:14)
    at Tag.render (D:\project\git\blog\node_modules\hexo\lib\extend\tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (D:\project\git\blog\node_modules\hexo\lib\hexo\post.js:253:16)
    at D:\project\git\blog\node_modules\hexo\lib\hexo\render.js:65:19
    at tryCatcher (D:\project\git\blog\node_modules\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\project\git\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (D:\project\git\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (D:\project\git\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (D:\project\git\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (D:\project\git\blog\node_modules\hexo\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (D:\project\git\blog\node_modules\hexo\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\project\git\blog\node_modules\hexo\node_modules\bluebird\js\release\async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.2.2"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-deployer-git": "^0.2.0",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-baidu-sitemap": "^0.1.2",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.0",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-searchdb": "^1.0.1",
    "hexo-generator-sitemap": "^1.1.2",
    "hexo-generator-tag": "^0.2.0",
    "hexo-inject": "^1.0.0",
    "hexo-math": "^3.0.2",
    "hexo-renderer-ejs": "^0.2.0",
    "hexo-renderer-markdown-it": "^3.4.1",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0"
  }
}

**Comment by zhangtianle** [comment]
https://hexo.io/docs/troubleshooting.html#Escape_Contents

Escape Contents

Hexo uses Nunjucks to render posts (Swig was used in older version, which share a similar syntax). Content wrapped with {{ }} or {% %} will get parsed and may cause problems. You can wrap sensitive content with the raw tag plugin.

{% raw %}
Hello {{ sensitive }}
{% endraw %}
