### ISSUE TITLE
body is undefined when using additional layouts

### ISSUE THREAD

**Issue by nathanielks** [hexojs/hexo#2290]
## Environment Info

Node version(`node -v`)
```
v6.9.1
```

Your site `_config.yml`
```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hexo
subtitle:
description:
author: John Doe
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: landscape
theme: sierra

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:

```

Your theme `_config.yml`
```
stylesheets:
  - /css/main.css
```

Plugin version(`npm ls --depth 0`)
```
hexo-site@0.0.0 /Users/aang/Code/beanstalk/sierra
├── bootstrap@4.0.0-alpha.5
├── hexo@3.2.2
├── hexo-autoprefixer@1.0.0
├── hexo-browsersync@0.2.0
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.0
├── hexo-generator-tag@0.2.0
├── hexo-render-pug@1.0.1
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-marked@0.2.11
├── hexo-renderer-scss@1.0.2
├── hexo-renderer-stylus@0.3.1
├── hexo-server@0.2.0
└── node-pre-gyp@0.6.32 extraneous

npm ERR! extraneous: node-pre-gyp@0.6.32 /Users/aang/Code/beanstalk/sierra/node_modules/node-pre-gyp
```

## For BUG

- BUG description

I've created an additonal layout I'd like to use for a page, but it's yelling at me saying `body` is undefined. What's confusing to me is I duplicated my theme's `layout.ejs` and it's borked, so it's not like I've done anything different 🤔.

- the way to reproduce

Create an additional layout and navigate to a page.

- log with hexo <command> --debug
```
$ hexo server --draft --open --debug                                                                                                 32m (2.2.5) feature/user-registration [84ac172] modified…
00:22:52.135 DEBUG Hexo version: 3.2.2
00:22:52.138 DEBUG Working directory: ~/Code/beanstalk/sierra/
00:22:52.233 DEBUG Config loaded: ~/Code/beanstalk/sierra/_config.yml
00:22:52.408 DEBUG Plugin loaded: hexo-autoprefixer
00:22:52.460 DEBUG Plugin loaded: hexo-browsersync
00:22:52.463 DEBUG Plugin loaded: hexo-generator-archive
00:22:52.464 DEBUG Plugin loaded: hexo-generator-category
00:22:52.466 DEBUG Plugin loaded: hexo-generator-index
00:22:52.468 DEBUG Plugin loaded: hexo-generator-tag
00:22:52.666 DEBUG Plugin loaded: hexo-render-pug
00:22:52.670 DEBUG Plugin loaded: hexo-renderer-ejs
00:22:52.676 DEBUG Plugin loaded: hexo-renderer-marked
00:22:52.688 DEBUG Plugin loaded: hexo-renderer-scss
00:22:52.689 DEBUG Plugin loaded: hexo-renderer-stylus
00:22:52.771 DEBUG Plugin loaded: hexo-server
[BS] Access URLs:
 --------------------------------------
          UI: http://localhost:3001
 --------------------------------------
 UI External: http://192.168.43.94:3001
 --------------------------------------
00:22:53.104 DEBUG Loading database.
00:22:53.158 INFO  Start processing
00:22:53.227 DEBUG Processed: _data/hero.yml
00:22:53.228 DEBUG Processed: _data/home.yml
00:22:53.228 DEBUG Processed: _data/nav.yml
00:22:53.228 DEBUG Processed: _data/social.yml
00:22:53.228 DEBUG Processed: _data/stores.yml
00:22:53.228 DEBUG Processed: user-registration-1/index.md
00:22:53.229 DEBUG Processed: index/index.md
00:22:53.250 DEBUG Theme config loaded.
00:22:53.250 DEBUG Processed: _config.yml
00:22:53.259 DEBUG Processed: source/css/bootstrap.scss
00:22:53.259 DEBUG Processed: source/css/main.scss
00:22:53.259 DEBUG Processed: source/images/app-store.png
00:22:53.260 DEBUG Processed: source/images/bbb.png
00:22:53.262 DEBUG Processed: source/images/down.png
00:22:53.262 DEBUG Processed: source/images/play-store.png
00:22:53.262 DEBUG Processed: source/images/right-arrow.png
00:22:53.262 DEBUG Processed: source/js/main.js
00:22:53.263 DEBUG Processed: source/images/sierralogo.png
00:22:53.281 DEBUG Processed: layout/layout.ejs
00:22:53.281 DEBUG Processed: layout/page.ejs
00:22:53.295 DEBUG Processed: layout/authenticated.ejs
00:22:53.296 DEBUG Processed: layout/index.ejs
00:22:53.296 DEBUG Processed: layout/partials/basic-info.ejs
00:22:53.296 DEBUG Processed: layout/partials/footer.ejs
00:22:53.296 DEBUG Processed: layout/partials/head.ejs
00:22:53.296 DEBUG Processed: layout/partials/download.ejs
00:22:53.297 DEBUG Processed: layout/partials/header.ejs
00:22:53.297 DEBUG Processed: layout/partials/i-am-a.ejs
00:22:53.297 DEBUG Processed: layout/partials/image-cta.ejs
00:22:53.297 DEBUG Processed: layout/partials/javascript.ejs
00:22:53.298 DEBUG Processed: layout/partials/login.ejs
00:22:53.298 DEBUG Processed: layout/partials/nav.ejs
00:22:53.298 DEBUG Processed: source/images/i-am-a-dealer.png
00:22:53.298 DEBUG Processed: source/images/i-am-a-driver.png
00:22:53.307 DEBUG Processed: source/images/customer-service.png
00:22:53.309 DEBUG Processed: source/images/payment.png
00:22:53.311 DEBUG Processed: source/images/faq.png
00:22:53.329 DEBUG Processed: source/images/2-layers.png
00:22:53.331 DEBUG Processed: source/images/layer-14.png
00:22:53.333 DEBUG Processed: source/images/user-registration-hero.png
00:22:53.334 DEBUG Processed: layout/partials/home-cta.ejs
00:22:53.355 DEBUG Generator: page
00:22:53.355 DEBUG Generator: post
00:22:53.355 DEBUG Generator: archive
00:22:53.355 DEBUG Generator: category
00:22:53.355 DEBUG Generator: index
00:22:53.355 DEBUG Generator: tag
00:22:53.356 DEBUG Generator: asset
00:22:53.360 INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.
00:22:53.376 DEBUG Database saved
00:22:53.726 DEBUG Rendering page: index.html
GET / 200 77.307 ms - -
GET /css/main.css 200 343.457 ms - -
GET /images/sierralogo.png 200 1.448 ms - -
GET /css/bootstrap.css 200 705.335 ms - -
GET /images/app-store.png 200 1.771 ms - -
GET /images/play-store.png 200 1.530 ms - -
GET /images/bbb.png 200 1.170 ms - -
GET /js/main.js 200 0.848 ms - -
GET /images/2-layers.png 200 0.696 ms - -
GET /user-registration-1 302 0.345 ms - -
00:23:00.401 DEBUG Rendering authenticated: user-registration-1/index.html
Unhandled rejection ReferenceError: /Users/aang/Code/beanstalk/sierra/themes/sierra/layout/authenticated.ejs:10
    8|   </head>
    9|   <body>
 >> 10|     <%- body %>
    11|     <%- partial('partials/download') %>
    12|     <%- partial('partials/footer') %>
    13|     <%- partial('partials/login') %>

body is not defined
    at eval (eval at <anonymous> (/Users/aang/Code/beanstalk/sierra/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:32:182)
    at eval (eval at <anonymous> (/Users/aang/Code/beanstalk/sierra/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:32:468)
    at /Users/aang/Code/beanstalk/sierra/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (/Users/aang/Code/beanstalk/sierra/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/Users/aang/Code/beanstalk/sierra/node_modules/hexo/lib/theme/view.js:29:15)
    at /Users/aang/Code/beanstalk/sierra/node_modules/hexo/lib/hexo/index.js:387:25
    at tryCatcher (/Users/aang/Code/beanstalk/sierra/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/aang/Code/beanstalk/sierra/node_modules/hexo/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/aang/Code/beanstalk/sierra/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:348:10)
    at resume_ (_stream_readable.js:737:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by NoahDragon** [comment]
Where did you put the `body.ejs` file?

**Comment by nathanielks** [comment]
```
// layout.ejs
<%
var pageTitle = page.title || config.subtitle || ''
%>
<!DOCTYPE html>
<html lang="en">
  <head>
    <%- partial('partials/head', { pageTitle }) %>
  </head>
  <body>
    <%- partial('partials/nav') %>
    <%- partial('partials/header') %>
    <%- body %>
    <%- partial('partials/download') %>
    <%- partial('partials/footer') %>
    <%- partial('partials/login') %>
    <%- partial('partials/javascript') %>
  </body>
</html>
```

```
// authenticated.ejs
<%
var pageTitle = page.title || config.subtitle || ''
%>
<!DOCTYPE html>
<html lang="en">
  <head>
    <%- partial('partials/head', { pageTitle }) %>
  </head>
  <body>
    <%- body %>
    <%- partial('partials/download') %>
    <%- partial('partials/footer') %>
    <%- partial('partials/login') %>
    <%- partial('partials/javascript') %>
  </body>
</html>
```

```md
# new page
---
title: user-registration-1
date: 2016-12-01 16:03:57
layout: authenticated
---

hello!
```

**Comment by NoahDragon** [comment]
@nathanielks The process is correct. I assume the issue is caused by the ejs files.

How about change the ejs files to the following?

```
// layout.ejs
<%
var pageTitle = page.title || config.subtitle || ''
%>
<!DOCTYPE html>
<html lang="en">
  <head>
    <%- partial('partials/head', { pageTitle }) %>
  </head>
  <body>
    <%- body %>
    <%- partial('partials/download') %>
    <%- partial('partials/footer') %>
    <%- partial('partials/login') %>
    <%- partial('partials/javascript') %>
  </body>
</html>
```

```
// authenticated.ejs
    <%- page.content %>
```

```
// post.ejs
    <%- partial('partials/nav') %>
    <%- partial('partials/header') %>
    <%- post.content %>
```

I think when you chose another layout, the `body` will be replaced by that layout. So the `layout.ejs` should only contain the minimal elements.

**Comment by nathanielks** [comment]
Ahhh, gotcha. That makes more sense. Thanks for the input!

**Comment by nathanielks** [comment]
@NoahDragon is it possible to have different `layout.ejs` files?

**Comment by nathanielks** [comment]
I see if I don't have a `layout.ejs` file at all, it will use the `post.ejs`, `page.ejs`, etc templates, I just didn't know if there's a way to define multiple "wrappers."

**Comment by NoahDragon** [comment]
@nathanielks 
Yes, it is possible. https://hexo.io/docs/templates.html#Layouts
Just like what you did, remove the layout.ejs, hexo will pick up the template which specified in front matter.
