### ISSUE TITLE
安装时出现以下错误，请教如何解决?

### ISSUE THREAD

**Issue by relax89757** [hexojs/hexo#2339]
FATAL incomplete explicit mapping pair; a key node is missed at line 103, column 32:
      secret_file: sec/qn.json or C:
                                   ^
YAMLException: incomplete explicit mapping pair; a key node is missed at line 103, column 32:
      secret_file: sec/qn.json or C:
                                   ^
    at generateError (C:\Program Files\Git\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:162:1                                                 0)
    at throwError (C:\Program Files\Git\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:168:9)
    at readBlockMapping (C:\Program Files\Git\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:99                                                 4:9)
    at composeNode (C:\Program Files\Git\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1326:12                                                 )
    at readBlockMapping (C:\Program Files\Git\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:10                                                 56:11)
    at composeNode (C:\Program Files\Git\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1326:12                                                 )
    at readDocument (C:\Program Files\Git\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1488:3                                                 )
    at loadDocuments (C:\Program Files\Git\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1544:                                                 5)
    at Object.load (C:\Program Files\Git\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1561:19                                                 )
    at Hexo.yamlHelper (C:\Program Files\Git\hexo\node_modules\hexo\lib\plugins\renderer\yaml.js                                                 :7:15)
    at Hexo.tryCatcher (C:\Program Files\Git\hexo\node_modules\bluebird\js\release\util.js:16:23                                                 )
    at Hexo.<anonymous> (C:\Program Files\Git\hexo\node_modules\bluebird\js\release\method.js:15                                                 :34)
    at C:\Program Files\Git\hexo\node_modules\hexo\lib\hexo\render.js:61:21
    at tryCatcher (C:\Program Files\Git\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\Git\hexo\node_modules\bluebird\js\rel                                                 ease\promise.js:510:31)
    at Promise._settlePromise (C:\Program Files\Git\hexo\node_modules\bluebird\js\release\promis                                                 e.js:567:18)
    at Promise._settlePromise0 (C:\Program Files\Git\hexo\node_modules\bluebird\js\release\promi                                                 se.js:612:10)
    at Promise._settlePromises (C:\Program Files\Git\hexo\node_modules\bluebird\js\release\promi                                                 se.js:691:18)
    at Async._drainQueue (C:\Program Files\Git\hexo\node_modules\bluebird\js\release\async.js:13                                                 8:16)
    at Async._drainQueues (C:\Program Files\Git\hexo\node_modules\bluebird\js\release\async.js:1                                                 48:10)
    at Immediate.Async.drainQueues (C:\Program Files\Git\hexo\node_modules\bluebird\js\release\a                                                 sync.js:17:14)
    at runCallback (timers.js:574:20)

**Comment by NoahDragon** [comment]
感觉是yml文件格式出错。请问安装是指运行`npm install -g hexo-cli`么？

**Comment by relax89757** [comment]
谢谢答复，我是用npm install -g hexo，后来准备安装一些插件，然后hexo d -g就出现这些错误信息，但是我不知道哪里出错了

**Comment by NoahDragon** [comment]
能否贴下_config.yml么？

**Comment by relax89757** [comment]
`# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 疯狂世界bolg
subtitle:
description:
author:  疯狂世界
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://relax89757.github.io
root:  /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: ture
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:



# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: yilia

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: https://github.com/relax89757/relax89757.github.io.git
  branch: master

plugins:
  - hexo-qiniu-sync

#七牛云存储设置
##offline       是否离线. 离线状态将使用本地地址渲染
##sync          是否同步
##bucket        空间名称.
##access_key    上传密钥AccessKey
##secret_key    上传密钥SecretKey
##secret_file   秘钥文件路径，可以将上述两个属性配置到文件内，防止泄露，json格式。绝对路径相对路径均可
##dirPrefix     上传的资源子目录前缀.如设置，需与urlPrefix同步 
##urlPrefix     外链前缀.
##up_host      上传服务器路径,如选择华北区域的话配置为http://up-z1.qiniu.com
##local_dir     本地目录.
##update_exist  是否更新已经上传过的文件(仅文件大小不同或在上次上传后进行更新的才会重新上传)
##image/js/css  子参数folder为不同静态资源种类的目录名称，一般不需要改动
##image.extend  这是个特殊参数，用于生成缩略图或加水印等操作。具体请参考http://developer.qiniu.com/docs/v6/api/reference/fop/image/ 
##              可使用基本图片处理、高级图片处理、图片水印处理这3个接口。例如 ##imageView2/2/w/500 即生成宽度最多500px的缩略图
qiniu:
  offline: false
  sync: true
  bucket: bucket_name
  secret_file: sec/qn.json or C:
  access_key: AccessKey
  secret_key: SecretKey
  dirPrefix: static
  urlPrefix: http://bucket_name.qiniudn.com/static
  up_host: http://upload.qiniu.com
  local_dir: static
  update_exist: true
  image: 
    folder: images
    extend: 
  js:
    folder: js
  css:
    folder: css`

**Comment by relax89757** [comment]
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 疯狂世界bolg
subtitle:
description:
author:  疯狂世界
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://relax89757.github.io
root:  /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: ture
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:



# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: yilia

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: https://github.com/relax89757/relax89757.github.io.git
  branch: master

plugins:
  - hexo-qiniu-sync

#七牛云存储设置
##offline       是否离线. 离线状态将使用本地地址渲染
##sync          是否同步
##bucket        空间名称.
##access_key    上传密钥AccessKey
##secret_key    上传密钥SecretKey
##secret_file   秘钥文件路径，可以将上述两个属性配置到文件内，防止泄露，json格式。绝对路径相对路径均可
##dirPrefix     上传的资源子目录前缀.如设置，需与urlPrefix同步 
##urlPrefix     外链前缀.
##up_host      上传服务器路径,如选择华北区域的话配置为http://up-z1.qiniu.com
##local_dir     本地目录.
##update_exist  是否更新已经上传过的文件(仅文件大小不同或在上次上传后进行更新的才会重新上传)
##image/js/css  子参数folder为不同静态资源种类的目录名称，一般不需要改动
##image.extend  这是个特殊参数，用于生成缩略图或加水印等操作。具体请参考http://developer.qiniu.com/docs/v6/api/reference/fop/image/ 
##              可使用基本图片处理、高级图片处理、图片水印处理这3个接口。例如 ##imageView2/2/w/500 即生成宽度最多500px的缩略图
qiniu:
  offline: false
  sync: true
  bucket: bucket_name
  secret_file: sec/qn.json or C:
  access_key: AccessKey
  secret_key: SecretKey
  dirPrefix: static
  urlPrefix: http://bucket_name.qiniudn.com/static
  up_host: http://upload.qiniu.com
  local_dir: static
  update_exist: true
  image: 
    folder: images
    extend: 
  js:
    folder: js
  css:
    folder: css

**Comment by relax89757** [comment]
刚学前端不久，代码上传后就自动变成了Markdown格式了，不知道怎么转换，还请看看

**Comment by NoahDragon** [comment]
七牛云存储这段的问题：

![image](https://cloud.githubusercontent.com/assets/5704064/21683796/f4a13870-d328-11e6-938f-f340d3861979.png)

由于没有用过此插件，所以也不是很清楚该如何改……

另外git deployer设置是repo， 不是repository.
![image](https://cloud.githubusercontent.com/assets/5704064/21683849/26341bc8-d329-11e6-897e-e61fb5f8c603.png)

**Comment by relax89757** [comment]
非常感谢，问题解决了。

**Comment by NoahDragon** [comment]
👍
