### ISSUE TITLE
hexo g提示md语法错误

### ISSUE THREAD

**Issue by DDDDSzr** [hexojs/hexo#2352]
```
$ hexo g
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: (unknown path) [Line 20, Column 181]
  expected variable end
    at Object.exports.prettifyError (F:\blog\node_modules\nunjucks\src\lib.js:34:15)
    at new_cls.render (F:\blog\node_modules\nunjucks\src\environment.js:469:27)
    at new_cls.renderString (F:\blog\node_modules\nunjucks\src\environment.js:327:21)
    at F:\blog\node_modules\hexo\lib\extend\tag.js:66:9
    at Promise._execute (F:\blog\node_modules\bluebird\js\release\debuggability.js:300:9)
    at Promise._resolveFromExecutor (F:\blog\node_modules\bluebird\js\release\promise.js:481:18)
    at new Promise (F:\blog\node_modules\bluebird\js\release\promise.js:77:14)
    at Tag.render (F:\blog\node_modules\hexo\lib\extend\tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (F:\blog\node_modules\hexo\lib\hexo\post.js:253:16)
    at F:\blog\node_modules\hexo\lib\hexo\render.js:65:19
    at tryCatcher (F:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (F:\blog\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (F:\blog\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (F:\blog\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (F:\blog\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (F:\blog\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (F:\blog\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (F:\blog\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
FATAL (unknown path) [Line 20, Column 181]
  expected variable end
Template render error: (unknown path) [Line 20, Column 181]
  expected variable end
    at Object.exports.prettifyError (F:\blog\node_modules\nunjucks\src\lib.js:34:15)
    at new_cls.render (F:\blog\node_modules\nunjucks\src\environment.js:469:27)
    at new_cls.renderString (F:\blog\node_modules\nunjucks\src\environment.js:327:21)
    at F:\blog\node_modules\hexo\lib\extend\tag.js:66:9
    at Promise._execute (F:\blog\node_modules\bluebird\js\release\debuggability.js:300:9)
    at Promise._resolveFromExecutor (F:\blog\node_modules\bluebird\js\release\promise.js:481:18)
    at new Promise (F:\blog\node_modules\bluebird\js\release\promise.js:77:14)
    at Tag.render (F:\blog\node_modules\hexo\lib\extend\tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (F:\blog\node_modules\hexo\lib\hexo\post.js:253:16)
    at F:\blog\node_modules\hexo\lib\hexo\render.js:65:19
    at tryCatcher (F:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (F:\blog\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (F:\blog\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (F:\blog\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (F:\blog\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (F:\blog\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (F:\blog\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (F:\blog\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```
---
然而我并没有动F:\blog\node_modules中的任何文件，请问这是怎么回事，谢谢。

**Comment by NoahDragon** [comment]
看起来像是在渲染Tag时候的一个错误。

**Comment by DDDDSzr** [comment]
@NoahDragon 请问tag是md文档里面的标签吗？如果是的话我所有的md文档的模板都是一样的直接复制，以前没有出现过这个问题。我把hexo卸掉重新来一遍还是这个问题。

**Comment by NoahDragon** [comment]
全新安装，没有任何md文件也出现这个问题？

**Comment by DDDDSzr** [comment]
@NoahDragon 刚才解决了，是mathjax不知道哪里错了，可能是嵌套过多(但是从md的预览上没有发现问题)。我用排除法一个个试的……不过还是谢谢了。
