### ISSUE TITLE
hexo server运行时间久了之后会报错

### ISSUE THREAD

**Issue by Wensibob** [hexojs/hexo#2355]
windows 2012的虚拟主机，hexo server超过半天之后就会报错，但是网站依旧可以正常访问，这是[我的网站](http://www.wensibo.top) ，报错内容如下：
```
TypeError: The header content contains invalid characters
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:358:11)
    at C:\blog\node_modules\hexo-server\lib\middlewares\route.js:27:11
    at call (C:\blog\node_modules\connect\index.js:239:7)
    at next (C:\blog\node_modules\connect\index.js:183:5)
    at C:\blog\node_modules\hexo-server\lib\middlewares\header.js:9:5
    at call (C:\blog\node_modules\connect\index.js:239:7)
    at next (C:\blog\node_modules\connect\index.js:183:5)
    at Function.handle (C:\blog\node_modules\connect\index.js:186:3)
    at Server.app (C:\blog\node_modules\connect\index.js:51:37)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:546:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
```

**Comment by NoahDragon** [comment]
应该是server response的header有问题，如果能看到header的内容就好解决。
建议使用Nginx来搭建server，Hexo server只是用于测试之用。

**Comment by Wensibob** [comment]
请问在Windows Server虚拟主机上如何使用Nginx搭建server，请大神赐教

**Comment by Wensibob** [comment]
Nice，我已经学会了，谢谢指导

**Comment by NoahDragon** [comment]
Nginx还是很易使用的~
