### ISSUE TITLE
TypeError: Cannot set property 'lastIndex' of undefined

### ISSUE THREAD

**Issue by Rapiz1** [hexojs/hexo#2380]
## Environment Info

Node version(`node -v`)
```
v7.4.0
```

Plugin version(`npm ls --depth 0`)
```
rapiz@sig ~/Blog $ npm ls --depth 0
hexo-site@0.0.0 /home/rapiz/Blog
├── hexo@3.2.2
├── hexo-deployer-git@0.2.0 -> /home/rapiz/Blog/node_modules/.0.2.0@hexo-deployer-git
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.0
├── hexo-generator-tag@0.2.0
├── hexo-inject@1.0.0
├── hexo-math@3.0.2 -> /home/rapiz/Blog/node_modules/.3.0.2@hexo-math
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-marked@0.2.11
├── hexo-renderer-stylus@0.3.1
├── hexo-server@0.2.0
├── katex@0.6.0 -> /home/rapiz/Blog/node_modules/.0.6.0@katex extraneous
└── match-at@0.1.0 -> /home/rapiz/Blog/node_modules/.0.1.0@match-at extraneous

npm ERR! extraneous: katex@0.6.0 /home/rapiz/Blog/node_modules/katex
npm ERR! extraneous: match-at@0.1.0 /home/rapiz/Blog/node_modules/match-at
```

## For BUG
```
rapiz@sig ~/Blog $ hexo g
INFO  [hexo-inject] installing hotfix for hexojs/hexo#1791
INFO  [hexo-math] Using engine 'mathjax'
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: Cannot set property 'lastIndex' of undefined
    at highlight (/home/rapiz/Blog/node_modules/highlight.js/lib/highlight.js:514:35)            
    at /home/rapiz/Blog/node_modules/highlight.js/lib/highlight.js:564:21                        
    at Array.forEach (native)                                                                    
    at Object.highlightAuto (/home/rapiz/Blog/node_modules/highlight.js/lib/highlight.js:563:40) 
    at highlight (/home/rapiz/Blog/node_modules/hexo-util/lib/highlight.js:100:19)               
    at highlightUtil (/home/rapiz/Blog/node_modules/hexo-util/lib/highlight.js:22:14)            
    at /home/rapiz/Blog/node_modules/hexo/lib/plugins/filter/before_post_render/backtick_code_block.js:49:15                                                                                      
    at RegExp.[Symbol.replace] (native)                                                          
    at String.replace (native)                                                                   
    at Hexo.backtickCodeBlock (/home/rapiz/Blog/node_modules/hexo/lib/plugins/filter/before_post_render/backtick_code_block.js:15:31)                                                             
    at Hexo.tryCatcher (/home/rapiz/Blog/node_modules/bluebird/js/release/util.js:16:23)         
    at Hexo.<anonymous> (/home/rapiz/Blog/node_modules/bluebird/js/release/method.js:15:34)      
    at /home/rapiz/Blog/node_modules/hexo/lib/extend/filter.js:68:35                             
    at tryCatcher (/home/rapiz/Blog/node_modules/bluebird/js/release/util.js:16:23)              
    at Object.gotValue (/home/rapiz/Blog/node_modules/bluebird/js/release/reduce.js:155:18)      
    at Object.gotAccum (/home/rapiz/Blog/node_modules/bluebird/js/release/reduce.js:144:25)      
    at Object.tryCatcher (/home/rapiz/Blog/node_modules/bluebird/js/release/util.js:16:23)       
    at Promise._settlePromiseFromHandler (/home/rapiz/Blog/node_modules/bluebird/js/release/promise.js:510:31)                                                                                    
    at Promise._settlePromise (/home/rapiz/Blog/node_modules/bluebird/js/release/promise.js:567:18)                                                                                               
    at Promise._settlePromiseCtx (/home/rapiz/Blog/node_modules/bluebird/js/release/promise.js:604:10)                                                                                            
    at Async._drainQueue (/home/rapiz/Blog/node_modules/bluebird/js/release/async.js:138:12)     
    at Async._drainQueues (/home/rapiz/Blog/node_modules/bluebird/js/release/async.js:143:10)    
    at Immediate.Async.drainQueues (/home/rapiz/Blog/node_modules/bluebird/js/release/async.js:17:14)                                                                                             
    at runCallback (timers.js:651:20)                                                            
    at tryOnImmediate (timers.js:624:5)                                                          
    at processImmediate [as _immediateCallback] (timers.js:596:5)                                
FATAL Cannot set property 'lastIndex' of undefined
TypeError: Cannot set property 'lastIndex' of undefined
    at highlight (/home/rapiz/Blog/node_modules/highlight.js/lib/highlight.js:514:35)            
    at /home/rapiz/Blog/node_modules/highlight.js/lib/highlight.js:564:21                        
    at Array.forEach (native)                                                                    
    at Object.highlightAuto (/home/rapiz/Blog/node_modules/highlight.js/lib/highlight.js:563:40) 
    at highlight (/home/rapiz/Blog/node_modules/hexo-util/lib/highlight.js:100:19)               
    at highlightUtil (/home/rapiz/Blog/node_modules/hexo-util/lib/highlight.js:22:14)            
    at /home/rapiz/Blog/node_modules/hexo/lib/plugins/filter/before_post_render/backtick_code_block.js:49:15                                                                                      
    at RegExp.[Symbol.replace] (native)                                                          
    at String.replace (native)                                                                   
    at Hexo.backtickCodeBlock (/home/rapiz/Blog/node_modules/hexo/lib/plugins/filter/before_post_render/backtick_code_block.js:15:31)                                                             
    at Hexo.tryCatcher (/home/rapiz/Blog/node_modules/bluebird/js/release/util.js:16:23)         
    at Hexo.<anonymous> (/home/rapiz/Blog/node_modules/bluebird/js/release/method.js:15:34)      
    at /home/rapiz/Blog/node_modules/hexo/lib/extend/filter.js:68:35                             
    at tryCatcher (/home/rapiz/Blog/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/home/rapiz/Blog/node_modules/bluebird/js/release/reduce.js:155:18)
    at Object.gotAccum (/home/rapiz/Blog/node_modules/bluebird/js/release/reduce.js:144:25)
    at Object.tryCatcher (/home/rapiz/Blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/rapiz/Blog/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/rapiz/Blog/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromiseCtx (/home/rapiz/Blog/node_modules/bluebird/js/release/promise.js:604:10)
    at Async._drainQueue (/home/rapiz/Blog/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/home/rapiz/Blog/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/rapiz/Blog/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

**Comment by Rapiz1** [comment]
Found the same issue here: https://github.com/hexojs/hexo/issues/1913
Where should I set auto_detect to false?

**Comment by NoahDragon** [comment]
The auto_detect is set for detecting language automatically, https://github.com/hexojs/hexo-util#highlightstr-options

I assume the issue is caused by when the highlight.js tries to detect the code language.

**Comment by dreambo8563** [comment]
got the same issue, after change the
 ```scala xx ``` 
 to 
```js xxx ``` 
 hexo is back

**Comment by jongio** [comment]
Setting auto_detect: false in _config.yml resolved this for me:

_config.yml

```yaml
highlight: 
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:
```

**Comment by marcofranssen** [comment]
The solution provided here just gives me another error. See my ticket #3486 with some more details and ideas to finally find a real solution to this issue.

**Comment by MrConfused** [comment]
这是因为在你的博客中，在用代码段`````时没有指明语言，这时候如果你的auto_detect: true，就会产生这个错误。
解决的话：
1. 找到那篇文章没有指明语言，随便加上一个就行。
2. 如果找不到哪篇博客，
2.1 可以在\myBlog\node_modules\hexo\lib\hexo\render.js中的第51、52行加上
console.log(data.path);
console.log(data.text);
查看在哪篇博客之后出现的问题。
2.2 然后，设置auto_detect: false，运行`hexo g`，查看生成文章的顺序，在2.1找到的文章之后的那篇文章，基本就是你没有指明语言的文章了。
2.3 此时给他随便指明一个语言，然后可以吧`render.js`中加的两行删掉，设置`auto_detect: true`，运行`hexo clean`，`hexo g`即可解决
