### ISSUE TITLE
使用hexo g命令后出错

### ISSUE THREAD

**Issue by Helihua1992** [hexojs/hexo#2386]
MachcdeMacBook-Pro:blog mac-hc$ hexo g
FATAL can not read a block mapping entry; a multiline key may not be an implicit key at line 8, column 12:
    description:
               ^
YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 8, column 12:
    description:
               ^
    at generateError (/Users/mac-hc/blog/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
    at throwError (/Users/mac-hc/blog/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
    at readBlockMapping (/Users/mac-hc/blog/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1041:9)
    at composeNode (/Users/mac-hc/blog/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1327:12)
    at readDocument (/Users/mac-hc/blog/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1489:3)
    at loadDocuments (/Users/mac-hc/blog/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1545:5)
    at Object.load (/Users/mac-hc/blog/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1562:19)
    at Hexo.yamlHelper (/Users/mac-hc/blog/node_modules/hexo/lib/plugins/renderer/yaml.js:7:15)
    at Hexo.tryCatcher (/Users/mac-hc/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Users/mac-hc/blog/node_modules/hexo/node_modules/bluebird/js/release/method.js:15:34)
    at /Users/mac-hc/blog/node_modules/hexo/lib/hexo/render.js:61:21
    at tryCatcher (/Users/mac-hc/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/mac-hc/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/mac-hc/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/mac-hc/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/mac-hc/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/Users/mac-hc/blog/node_modules/hexo/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/mac-hc/blog/node_modules/hexo/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/mac-hc/blog/node_modules/hexo/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:396:17)
MachcdeMacBook-Pro:blog mac-hc$

**Comment by NoahDragon** [comment]
能否贴下_config.yml？应该是yaml parse的错误。

**Comment by Helihua1992** [comment]
应该是，我前几天已解决。就是在修改_config.yml文件时，键值对的冒号后面少了空格所导致的错误。

**Comment by NoahDragon** [comment]
好的，先关闭这个Issue了。
