### ISSUE TITLE
deploy解析public时报错

### ISSUE THREAD

**Issue by moyuqi** [hexojs/hexo#239]
``` javascript
Clearing
Copying files from public folder.

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)
```

环境参数：
win 7 环境，
hexo: 1.2.4
http_parser: 1.0
node: 0.10.12
v8: 3.14.5.9
ares: 1.9.0-DEV
uv: 0.10.11
zlib: 1.2.3
modules: 11
openssl: 1.0.1e

在deploy时报这个错

**Comment by meiyouqing** [comment]
@moyuqi 
谢谢了，你的分析也解决了我遇到的问题！
