### ISSUE TITLE
TypeError: Cannot read property 'count' of undefined

### ISSUE THREAD

**Issue by myerandme** [hexojs/hexo#2402]
$ hexo g
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: Cannot read property 'count' of undefined
    at Hexo.module.exports (E:\github\hexo\node_modules\hexo-baidu-url-submit\lib\generator.js:4:40)
    at Hexo.tryCatcher (E:\github\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (E:\github\hexo\node_modules\bluebird\js\release\method.js:15:34)
    at E:\github\hexo\node_modules\hexo\lib\hexo\index.js:337:24
    at tryCatcher (E:\github\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (E:\github\hexo\node_modules\bluebird\js\release\map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (E:\github\hexo\node_modules\bluebird\js\release\promise_array.js:113:31)
    at MappingPromiseArray.init (E:\github\hexo\node_modules\bluebird\js\release\promise_array.js:77:10)
    at MappingPromiseArray._asyncInit (E:\github\hexo\node_modules\bluebird\js\release\map.js:30:10)
    at Async._drainQueue (E:\github\hexo\node_modules\bluebird\js\release\async.js:138:12)
    at Async._drainQueues (E:\github\hexo\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (E:\github\hexo\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
FATAL Cannot read property 'count' of undefined
TypeError: Cannot read property 'count' of undefined
    at Hexo.module.exports (E:\github\hexo\node_modules\hexo-baidu-url-submit\lib\generator.js:4:40)
    at Hexo.tryCatcher (E:\github\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (E:\github\hexo\node_modules\bluebird\js\release\method.js:15:34)
    at E:\github\hexo\node_modules\hexo\lib\hexo\index.js:337:24
    at tryCatcher (E:\github\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (E:\github\hexo\node_modules\bluebird\js\release\map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (E:\github\hexo\node_modules\bluebird\js\release\promise_array.js:113:31)
    at MappingPromiseArray.init (E:\github\hexo\node_modules\bluebird\js\release\promise_array.js:77:10)
    at MappingPromiseArray._asyncInit (E:\github\hexo\node_modules\bluebird\js\release\map.js:30:10)
    at Async._drainQueue (E:\github\hexo\node_modules\bluebird\js\release\async.js:138:12)
    at Async._drainQueues (E:\github\hexo\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (E:\github\hexo\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)

**Comment by NoahDragon** [comment]
Could you please run the `hexo g --debug` and paste the trace log?

**Comment by Mine-MuYan** [comment]
Do you slove this problem now?

**Comment by mrpanc** [comment]
I have the same problem.

**Comment by strugglingxingf** [comment]
1.npm remove hexo-baidu-url-submit
2.hexo clean
3.hexo g
 You can try it!

**Comment by sunnogo** [comment]
issue [2556](https://github.com/hexojs/hexo/issues/2556) shows that this plugin needs configuration.
The [repo hexo-baidu-url-submit](https://github.com/huiwang/hexo-baidu-url-submit) doesn't show User Guide in README, but links to the author's [website](http://hui-wang.info/2016/10/23/Hexo%E6%8F%92%E4%BB%B6%E4%B9%8B%E7%99%BE%E5%BA%A6%E4%B8%BB%E5%8A%A8%E6%8F%90%E4%BA%A4%E9%93%BE%E6%8E%A5/). It's really sucks.

**Comment by zhangzhengyi12** [comment]
这个插件真的有点坑到我，反复尝试了很久 感谢@strugglingxingf

**Comment by gaohanghang** [comment]
@strugglingxingf  thanks

**Comment by ruiyongsheng** [comment]
@strugglingxingf Thank you very much!

**Comment by shawnyc** [comment]
@strugglingxingf  thanks

**Comment by ithou** [comment]
@strugglingxingf Thanks!

**Comment by haojianxun** [comment]
安装了百度推送的插件 瞬间崩溃  真是 搞了好久才好  把百度推送的和抓取的都删掉就可以

**Comment by THW2015** [comment]
@strugglingxingf thanks!!!

**Comment by xiarihuoyan** [comment]
> 1.npm remove hexo-baidu-url-submit
> 2.hexo clean
> 3.hexo g
> You can try it.
> hope that can help you.

真的非常感谢您的回答，搜索了很多解决办法都无效，郁闷死，尝试了您的方法，立即解决问题，感谢！

**Comment by Seachal** [comment]
thinks @strugglingxingf

**Comment by ahjwen** [comment]
感谢，学会了使用  `hexo g --debug` 发现了导致报错的两个插件，已删除并解决问题，感谢。

介质-图像插件: `hexo-renderer-stylus`
SEO链接，可视化: `hexo-seo-link-visualizer`

**Comment by GeneralLi95** [comment]
@strugglingxingf Thank you very much
