### ISSUE TITLE
hexo d  失败： bash: /dev/tty: No such device or address

### ISSUE THREAD

**Issue by kokiers** [hexojs/hexo#2406]
hexo版本：
$ hexo -v
hexo: 3.2.2
hexo-cli: 1.0.2
os: Windows_NT 6.1.7601 win32 x64
http_parser: 2.6.0
node: 5.3.0
v8: 4.6.85.31
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2e

Your site `_config.yml`
deploy:
  type: git
  repository: https://github.com/kokiers/kokiers.github.io.git
  branch: master

## For BUG
$ hexo d
INFO  Deploying: git
INFO  Clearing .deploy_git folder...
INFO  Copying files from public folder...
On branch master
nothing to commit, working tree clean
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': Invalid argument
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': Invalid argument

    at ChildProcess.<anonymous> (E:\kokier\kokiers.github.io\node_modules\hexo-util\lib\spawn.js:37:17)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at ChildProcess.cp.emit (E:\kokier\kokiers.github.io\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
FATAL bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': Invalid argument

Error: bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': Invalid argument

    at ChildProcess.<anonymous> (E:\kokier\kokiers.github.io\node_modules\hexo-util\lib\spawn.js:37:17)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at ChildProcess.cp.emit (E:\kokier\kokiers.github.io\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

## For question
请问我应该怎么修改？本地是可以启动hexo博客。

## 另一种情况
deploy:
  type: git
  repository: git@github.com:andybroker/andybroker.github.io.git
  branch: master
然后就弹出 
open ssh 输入id_rsa窗口。

**Comment by NoahDragon** [comment]
你是使用Cygwin么？

**Comment by kokiers** [comment]
不是，就是用win系统cmd，和git bash。这两个都不行。

**Comment by Mine-MuYan** [comment]
你把你的sshkey重新生成一下看看呢？

**Comment by avocadowang** [comment]
重新生成ssh重新添加或者提交路径换一下,ssh和https互换

**Comment by ToSeven** [comment]
我也有相同的问题 怎么解决的？

**Comment by NoahDragon** [comment]
@ToSeven 添加ssh key或者用改成https链接。

**Comment by Simmon12** [comment]
你可能本机没有添加ssh key

**Comment by ToSeven** [comment]
添加了ssh key 然后测试也连接上了 还成https报其他错误。。。

**Comment by yangsiheng** [comment]
我也有这个问题，求解决方案
