### ISSUE TITLE
FATAL fatal: The remote end hung up unexpectedly

### ISSUE THREAD

**Issue by Xing-Chuan** [hexojs/hexo#2410]
error info ↓ :
```
fatal: The remote end hung up unexpectedly
error: RPC failed; curl 56 SSL read: error:00000000:lib(0):func(0):reason(0), errno 10053
Everything up-to-date
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
error: RPC failed; curl 56 SSL read: error:00000000:lib(0):func(0):reason(0), errno 10053
Everything up-to-date

    at ChildProcess.<anonymous> (E:\blog\node_modules\hexo-util\lib\spawn.js:37:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at ChildProcess.cp.emit (E:\blog\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
FATAL fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
error: RPC failed; curl 56 SSL read: error:00000000:lib(0):func(0):reason(0), errno 10053
Everything up-to-date

Error: fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
error: RPC failed; curl 56 SSL read: error:00000000:lib(0):func(0):reason(0), errno 10053
Everything up-to-date

    at ChildProcess.<anonymous> (E:\blog\node_modules\hexo-util\lib\spawn.js:37:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at ChildProcess.cp.emit (E:\blog\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

0 0 只是新写了文章,怎么出了这种错误,还没研究明白,哪位可以解惑下吗?

**Comment by NoahDragon** [comment]
是哪条指令引发的这个错误？

**Comment by akeliw** [comment]
@NoahDragon hexo d.   上传到github空间命令

**Comment by NoahDragon** [comment]
可否贴出`hexo d --debug`的输出？

**Comment by akeliw** [comment]
@NoahDragon 这是`hexo d --debug`的输出

```
$ hexo d --debug
13:34:05.207 DEBUG Hexo version: 3.2.2
13:34:05.210 DEBUG Working directory: E:\blog\
13:34:05.339 DEBUG Config loaded: E:\blog\_config.yml
13:34:05.354 DEBUG Plugin loaded: hexo-deployer-git
13:34:05.358 DEBUG Plugin loaded: hexo-generator-archive
13:34:05.360 DEBUG Plugin loaded: hexo-generator-category
13:34:05.362 DEBUG Plugin loaded: hexo-generator-index
13:34:05.396 DEBUG Plugin loaded: hexo-generator-json-content
13:34:05.397 DEBUG Plugin loaded: hexo-generator-tag
13:34:05.400 DEBUG Plugin loaded: hexo-renderer-ejs
13:34:05.406 DEBUG Plugin loaded: hexo-renderer-marked
13:34:05.407 DEBUG Plugin loaded: hexo-renderer-stylus
13:34:05.480 DEBUG Plugin loaded: hexo-server
13:34:05.482 INFO  Deploying: git
13:34:05.489 INFO  Clearing .deploy_git folder...
13:34:05.759 INFO  Copying files from public folder...
warning: LF will be replaced by CRLF in 2017/01/03/setTimeoutçç§å¯/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in 2017/01/04/ES6æ ¸å¿åå®¹/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in 2017/01/15/PCè½¯ä»¶æ¨è/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in 2017/01/17/ç§»å¨ç«¯è½¯ä»¶æ¨è/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in 2017/02/07/201702/å­¦ä¹ ç¬è®°/ç§»å¨webå¼åä¹viewport/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in 2017/02/13/font-sizeåå§åçå¿è¦æ§/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in about/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in archives/2017/01/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in archives/2017/02/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in archives/2017/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in archives/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in ca/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in categories/IT/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in main.2d7529.js.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in slider.885efe.js.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in tags/Bug/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in tags/CSS/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in tags/ES6/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in tags/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in tags/javascript/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in tags/ç ç©¶/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in tags/ç§»å¨ç«¯/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in tags/è½¯ä»¶/index.html.
The file will have its original line endings in your working directory.
[master 3d01712] Site updated: 2017-02-20 21:34:05
 22 files changed, 110 insertions(+), 110 deletions(-)
Branch master set up to track remote branch master from https://akeliw:w023138866@github.com/akeliw/akeliw.github.io.git.
To https://github.com/akeliw/akeliw.github.io.git
   ae1cfde..3d01712  HEAD -> master
13:35:24.729 INFO  Deploy done: git
13:35:24.731 DEBUG Database saved

```

**Comment by akeliw** [comment]
@NoahDragon 使用`hexo d --debug`之后github仓库代码更新了,但是空间上不去了,
**以下是命令返回代码**
```
$ hexo d --debug
13:34:05.207 DEBUG Hexo version: 3.2.2
13:34:05.210 DEBUG Working directory: E:\blog\
13:34:05.339 DEBUG Config loaded: E:\blog\_config.yml
13:34:05.354 DEBUG Plugin loaded: hexo-deployer-git
13:34:05.358 DEBUG Plugin loaded: hexo-generator-archive
13:34:05.360 DEBUG Plugin loaded: hexo-generator-category
13:34:05.362 DEBUG Plugin loaded: hexo-generator-index
13:34:05.396 DEBUG Plugin loaded: hexo-generator-json-content
13:34:05.397 DEBUG Plugin loaded: hexo-generator-tag
13:34:05.400 DEBUG Plugin loaded: hexo-renderer-ejs
13:34:05.406 DEBUG Plugin loaded: hexo-renderer-marked
13:34:05.407 DEBUG Plugin loaded: hexo-renderer-stylus
13:34:05.480 DEBUG Plugin loaded: hexo-server
13:34:05.482 INFO  Deploying: git
13:34:05.489 INFO  Clearing .deploy_git folder...
13:34:05.759 INFO  Copying files from public folder...
warning: LF will be replaced by CRLF in 2017/01/03/setTimeoutçç§å¯/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in 2017/01/04/ES6æ ¸å¿åå®¹/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in 2017/01/15/PCè½¯ä»¶æ¨è/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in 2017/01/17/ç§»å¨ç«¯è½¯ä»¶æ¨è/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in 2017/02/07/201702/å­¦ä¹ ç¬è®°/ç§»å¨webå¼åä¹viewport/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in 2017/02/13/font-sizeåå§åçå¿è¦æ§/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in about/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in archives/2017/01/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in archives/2017/02/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in archives/2017/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in archives/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in ca/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in categories/IT/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in main.2d7529.js.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in slider.885efe.js.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in tags/Bug/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in tags/CSS/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in tags/ES6/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in tags/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in tags/javascript/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in tags/ç ç©¶/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in tags/ç§»å¨ç«¯/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in tags/è½¯ä»¶/index.html.
The file will have its original line endings in your working directory.
[master 3d01712] Site updated: 2017-02-20 21:34:05
 22 files changed, 110 insertions(+), 110 deletions(-)
Branch master set up to track remote branch master from https://akeliw:===密码===@github.com/akeliw/akeliw.github.io.git.
To https://github.com/akeliw/akeliw.github.io.git
   ae1cfde..3d01712  HEAD -> master
13:35:24.729 INFO  Deploy done: git
13:35:24.731 DEBUG Database saved
```

**Comment by jievhaha** [comment]
git config http.postBuffer 524288000
使用该命令后假如提示fatal: not in a git directory
那就先在项目的根目录下使用git init，然后再使用上边的命令，今天碰到这个问题就这样做的，成功解决
