### ISSUE TITLE
21:39:51.543 FATAL (unknown path) [Line 3, Column 1215]   unexpected token: }}

### ISSUE THREAD

**Issue by xenoterracide** [hexojs/hexo#2419]
after trying to [import with a failure](https://github.com/hexojs/hexo-migrator-rss/issues/10) I get an error trying to serve pages, but the exception, nor debug? identifies which template it's attempting to process. I haven't customized anything beyond running the init, and then the import

## Environment Info

Node version(`node -v`)
```
v6.10.0
```

Plugin version(`npm ls --depth 0`)
```
+-- hexo@3.2.2
+-- hexo-generator-archive@0.1.4
+-- hexo-generator-category@0.1.3
+-- hexo-generator-index@0.2.0
+-- hexo-generator-tag@0.2.0
+-- hexo-migrator-rss@0.1.2
+-- hexo-renderer-ejs@0.2.0
+-- hexo-renderer-marked@0.2.11
+-- hexo-renderer-stylus@0.3.1
`-- hexo-server@0.2.0
```

```
C:\Users\xeno\IdeaProjects\blog>hexo server --debug
21:39:49.609 DEBUG Hexo version: 3.2.2
21:39:49.614 DEBUG Working directory: ~\IdeaProjects\blog\
21:39:49.715 DEBUG Config loaded: ~\IdeaProjects\blog\_config.yml
21:39:49.729 DEBUG Script loaded: themes\landscape\scripts\fancybox.js
21:39:49.734 DEBUG Plugin loaded: hexo-generator-tag
21:39:49.737 DEBUG Plugin loaded: hexo-generator-category
21:39:49.739 DEBUG Plugin loaded: hexo-generator-index
21:39:49.879 DEBUG Plugin loaded: hexo-migrator-rss
21:39:49.884 DEBUG Plugin loaded: hexo-renderer-ejs
21:39:49.890 DEBUG Plugin loaded: hexo-renderer-marked
21:39:49.938 DEBUG Plugin loaded: hexo-server
21:39:49.941 DEBUG Plugin loaded: hexo-renderer-stylus
21:39:49.946 DEBUG Plugin loaded: hexo-generator-archive
21:39:49.955 DEBUG Loading database.
21:39:50.120 INFO  Start processing
21:39:50.226 DEBUG Processed: _posts/minimum-permissions-and-privilegdges.md
21:39:50.356 DEBUG Processed: _posts/10-ways-of-implementing-Polymorphism.md
21:39:50.357 DEBUG Processed: _posts/Abandoning-all-Perl-modules.md
21:39:50.361 DEBUG Processed: _posts/A-page-for-Perl-WebHosts.md
21:39:50.363 DEBUG Processed: _posts/Adding-a-new-group-to-an-open-shell-without-logging-in-and-out.md
21:39:50.364 DEBUG Processed: _posts/Adding-and-Deleting-subdomains-with-Plesk-on-the-Command-Line.md
21:39:50.364 DEBUG Processed: _posts/Advent-good-idea-but-problematic-execution.md
21:39:50.365 DEBUG Processed: _posts/Adventures-with-SOAP-using-Perl-Part-1-SOAP-Lite.md
21:39:50.365 DEBUG Processed: _posts/Adventures-with-SOAP-using-Perl-Part-2-SOAP-Data-Builder.md
21:39:50.367 DEBUG Processed: _posts/Adventures-with-SOAP-using-Perl-Part-0-prelude.md
21:39:50.367 DEBUG Processed: _posts/Annoucing-Template-Plugin-Haml.md
21:39:50.367 DEBUG Processed: _posts/Announcing-Dist-Zilla-Plugin-Catalyst.md
21:39:50.367 DEBUG Processed: _posts/Bad-Customer-Service-from-T-Mobile.md
21:39:50.368 DEBUG Processed: _posts/Arch-Funtoo-and-Regen2-s-future.md
21:39:50.368 DEBUG Processed: _posts/Banned-from-funtoo.md
21:39:50.368 DEBUG Processed: _posts/Better-Exceptions-with-Exception-Base.md
21:39:50.368 DEBUG Processed: _posts/Business-CyberSource-API-is-stabilizing-as-of-0-7-x.md
21:39:50.369 DEBUG Processed: _posts/Can-t-Find-Google-s-OpenID.md
21:39:50.369 DEBUG Processed: _posts/Bypassing-disabled-accounts-with-KDM.md
21:39:50.369 DEBUG Processed: _posts/Celebrity-nude-scandal-on-security-an-analogy.md
21:39:50.369 DEBUG Processed: _posts/Changing-default-behavior-of-File-chmod.md
21:39:50.370 DEBUG Processed: _posts/Continuous-Integration-with-Wercker-and-Maven.md
21:39:50.370 DEBUG Processed: _posts/Creating-new-projects-with-dzil-new-and-templates.md
21:39:50.370 DEBUG Processed: _posts/Difference-Between-a-Database-and-a-Database-Instance.md
21:39:50.370 DEBUG Processed: _posts/Dist-Zilla-vs-xenoterracide.md
21:39:50.371 DEBUG Processed: _posts/Documentation-it-should-be-TDDD.md
21:39:50.371 DEBUG Processed: _posts/Don-t-Use-Big-Words.md
21:39:50.371 DEBUG Processed: _posts/Download-Book-The-Ruining-of-a-Good-Feature.md
21:39:50.371 DEBUG Processed: _posts/Experience-with-having-a-non-Dist-Zilla-user-contribute-to-a-Dist-Zilla-project-it-s-not-hard-for-them-or-me.md
21:39:50.372 DEBUG Processed: _posts/FSDaily-security-fail-see-image.md
21:39:50.372 DEBUG Processed: _posts/Falsehoods-programmers-believe-about-versions.md
21:39:50.372 DEBUG Processed: _posts/Finally-Linux-gets-something-first.md
21:39:50.372 DEBUG Processed: _posts/Forking-Funtoo-Regen2-project-born.md
21:39:50.373 DEBUG Processed: _posts/Funtoo-News.md
21:39:50.373 DEBUG Processed: _posts/GPL-3-and-Artistic-2-0-Software-License.md
21:39:50.373 DEBUG Processed: _posts/Funtoo-gets-the-new-Perl.md
21:39:50.374 DEBUG Processed: _posts/Git-Presentation.md
21:39:50.374 DEBUG Processed: _posts/Google-trashed-my-Google-Site-s-Content.md
21:39:50.374 DEBUG Processed: _posts/Heritage-Paper-Cultural-Diversity.md
21:39:50.377 DEBUG Processed: _posts/How-not-to-ask-for-help.md
21:39:50.377 DEBUG Processed: _posts/I-am-a-explicitive-or-Formal-Apology-to-RJBS.md
21:39:50.378 DEBUG Processed: _posts/I-need-a-new-favorite-OSI-license-or-Why-I-don-t-like-the-GPL-anymore.md
21:39:50.378 DEBUG Processed: _posts/I-wish-my-would-go-away.md
21:39:50.378 DEBUG Processed: _posts/If-you-can-t-beat-them-join-them.md
21:39:50.378 DEBUG Processed: _posts/Iron-Man-and-introductions.md
21:39:50.379 DEBUG Processed: _posts/Interface-Driven-Design.md
21:39:50.382 DEBUG Processed: _posts/Inversion-of-Control-Principle.md
21:39:50.382 DEBUG Processed: _posts/Java-Privacy-broken-by-design.md
21:39:50.382 DEBUG Processed: _posts/Jeff-Atwood-fails-at-password-security.md
21:39:50.382 DEBUG Processed: _posts/KDE-4-is-finally-ready-for-users.md
21:39:50.383 DEBUG Processed: _posts/Looking-for-tree-maintainers.md
21:39:50.383 DEBUG Processed: _posts/Making-re-pl-usable.md
21:39:50.383 DEBUG Processed: _posts/Making-Secure-Recoverable-Passwords-part-3.md
21:39:50.383 DEBUG Processed: _posts/Making-secure-recoverable-Passwords-Part-2.md
21:39:50.384 DEBUG Processed: _posts/Managing-CPAN-on-Arch-Linux.md
21:39:50.384 DEBUG Processed: _posts/Matching-Hex-characters-in-a-Regex.md
21:39:50.385 DEBUG Processed: _posts/Moose-Interface-Pattern-with-parameter-enforcement.md
21:39:50.385 DEBUG Processed: _posts/More-Security-Better-Wrong.md
21:39:50.385 DEBUG Processed: _posts/My-new-Love-Hate-Relationship-with-Dist-Zilla.md
21:39:50.391 DEBUG Processed: _posts/My-solution-to-not-using-PluginBundle-AUTHOR-for-dzil-is-git.md
21:39:50.391 DEBUG Processed: _posts/New-Module-MooseX-RemoteHelper-RFC.md
21:39:50.393 DEBUG Processed: _posts/New-beginnings.md
21:39:50.394 DEBUG Processed: _posts/OpenWRT-static-DHCP.md
21:39:50.394 DEBUG Processed: _posts/Override-DNS-on-a-Linux-system-without-root.md
21:39:50.394 DEBUG Processed: _posts/Perl-Blogger-annoyances.md
21:39:50.394 DEBUG Processed: _posts/Perl-Core-Syntax-Wishlist-Class-support.md
21:39:50.395 DEBUG Processed: _posts/Perl-Core-Syntax-Wishlist-Role-Support.md
21:39:50.395 DEBUG Processed: _posts/Perl-Core-Syntax-Wishlist-an-Exception-Stack.md
21:39:50.395 DEBUG Processed: _posts/Perl-Core-Syntax-Wishlist-die-should-die.md
21:39:50.395 DEBUG Processed: _posts/Pod-Spell-maintained-but-could-use-more-hands.md
21:39:50.398 DEBUG Processed: _posts/Port-forwarding-in-OpenWRT.md
21:39:50.398 DEBUG Processed: _posts/PostgreSQL-edit-and-Syntax-Highlighting.md
21:39:50.398 DEBUG Processed: _posts/PostgreSQL-initial-setup-authentication-Part-2.md
21:39:50.399 DEBUG Processed: _posts/PostgreSQL-initial-setup-authentication.md
21:39:50.399 DEBUG Processed: _posts/Premature-optimization-is-not-evil.md
21:39:50.399 DEBUG Processed: _posts/Providing-with-Providers-and-Bread-Board.md
21:39:50.399 DEBUG Processed: _posts/Quick-sha1sum-with-Crypto.md
21:39:50.399 DEBUG Processed: _posts/REST-ROA-and-HATEOAS-often-leads-to-bad-webservice-design.md
21:39:50.400 DEBUG Processed: _posts/RT-git-workflow.md
21:39:50.401 DEBUG Processed: _posts/Recovering-from-a-deleted-etc.md
21:39:50.402 DEBUG Processed: _posts/Regen2-0-9-1-0-Released.md
21:39:50.405 DEBUG Processed: _posts/Regen2-0-9-1-0-soon.md
21:39:50.406 DEBUG Processed: _posts/Regen2-0-9-1-0.md
21:39:50.406 DEBUG Processed: _posts/Regen2-accounts-transferred.md
21:39:50.407 DEBUG Processed: _posts/Regen2-development-has-officially-begun.md
21:39:50.407 DEBUG Processed: _posts/Regen2-don-t-care-anymore.md
21:39:50.407 DEBUG Processed: _posts/SYNC-METHOD.md
21:39:50.408 DEBUG Processed: _posts/Say-Perl.md
21:39:50.408 DEBUG Processed: _posts/Selling-Open-Source-Software-specifically-games.md
21:39:50.408 DEBUG Processed: _posts/Semver-org-probably-not-compat-with-all-downstream.md
21:39:50.409 DEBUG Processed: _posts/Simple-scripting-CLI-with-Expect-pm.md
21:39:50.409 DEBUG Processed: _posts/Single-Repository-one-Aggregate.md
21:39:50.409 DEBUG Processed: _posts/Solving-code-generation-problems-in-dzil.md
21:39:50.409 DEBUG Processed: _posts/Some-Stack-Exchange-site-s-I-d-like-to-see-come-to-fruition.md
21:39:50.410 DEBUG Processed: _posts/Sunrise-s-over-Funtoo.md
21:39:50.410 DEBUG Processed: _posts/Teaching-Perl-Part-0-Preface.md
21:39:50.410 DEBUG Processed: _posts/Teaching-Perl-Week-1-Part1.md
21:39:50.410 DEBUG Processed: _posts/Teaching-Perl-Week-1-Part2.md
21:39:50.411 DEBUG Processed: _posts/Teaching-Perl-Week-2.md
21:39:50.411 DEBUG Processed: _posts/Teaching-Perl-Week-2-part2.md
21:39:50.411 DEBUG Processed: _posts/Teaching-Perl-Week-3-Prelude-Commentary.md
21:39:50.411 DEBUG Processed: _posts/Teaching-Perl-Week-3-Textual-Data.md
21:39:50.411 DEBUG Processed: _posts/Test-Perl-5-12-on-Arch-Linux.md
21:39:50.412 DEBUG Processed: _posts/That-s-not-what-I-m-saying.md
21:39:50.412 DEBUG Processed: _posts/Test-Version-under-maintenance-again.md
21:39:50.412 DEBUG Processed: _posts/Testing-TT-Template-s.md
21:39:50.412 DEBUG Processed: _posts/The-Motherboard-I-want-doesn-t-exist.md
21:39:50.412 DEBUG Processed: _posts/Thinking-of-presenting-at-YAPC-NA-2014.md
21:39:50.413 DEBUG Processed: _posts/The-ShareDir-Problem.md
21:39:50.413 DEBUG Processed: _posts/To-pointer-or-not-to-pointer-That-is-the-question.md
21:39:50.413 DEBUG Processed: _posts/Tree-hasn-t-been-updated-why.md
21:39:50.413 DEBUG Processed: _posts/Two-Hundred-Posts.md
21:39:50.413 DEBUG Processed: _posts/UML-Tools.md
21:39:50.414 DEBUG Processed: _posts/Ubuntu-isn-t-Linux-What-s-a-Beginner-anyways.md
21:39:50.414 DEBUG Processed: _posts/Unpaid-volunteer-work-is-a-job.md
21:39:50.414 DEBUG Processed: _posts/Using-ref-to-fix-5-year-old-bug.md
21:39:50.417 DEBUG Processed: _posts/Using-Spring-to-create-a-full-REST-API-in-less-than-60-lines-of-code.md
21:39:50.422 DEBUG Processed: _posts/Warranties-what-do-they-have-to-do-with-anything.md
21:39:50.423 DEBUG Processed: _posts/Where-s-5-16-1.md
21:39:50.423 DEBUG Processed: _posts/Would-You-Miss-Autoderef-in-5-20-solutions-in-search-of-a-problem.md
21:39:50.423 DEBUG Processed: _posts/Writing-a-simple-Dist-Zilla-Tester-test.md
21:39:50.423 DEBUG Processed: _posts/Writing-deprecation-notices-in-perl-optionally-with-Moose.md
21:39:50.424 DEBUG Processed: _posts/You-should-have-hired-me-just-a-vent.md
21:39:50.427 DEBUG Processed: _posts/a-snake-in-regen2.md
21:39:50.428 DEBUG Processed: _posts/accept-input-from-stdin.md
21:39:50.428 DEBUG Processed: _posts/arch-will-be-testing-again-not-stable.md
21:39:50.429 DEBUG Processed: _posts/bash-and-konsole.md
21:39:50.429 DEBUG Processed: _posts/cat-that-displays-tabs-at-4-spaces.md
21:39:50.429 DEBUG Processed: _posts/empty-function-for-postgresql-in-sql.md
21:39:50.430 DEBUG Processed: _posts/git-workflows.md
21:39:50.430 DEBUG Processed: _posts/github-renders-POD.md
21:39:50.430 DEBUG Processed: _posts/hello-world.md
21:39:50.431 DEBUG Processed: _posts/iptables-browsing-samba-shares.md
21:39:50.431 DEBUG Processed: _posts/merged-java-overlay.md
21:39:50.431 DEBUG Processed: _posts/mpd-overlay.md
21:39:50.432 DEBUG Processed: _posts/my-git-remote.md
21:39:50.432 DEBUG Processed: _posts/of-Volunteers-and-Work.md
21:39:50.432 DEBUG Processed: _posts/open-letter-to-Dan-Robbins-merge-regen2.md
21:39:50.432 DEBUG Processed: _posts/please-don-t-use-Dist-Zilla-PluginBundle-USERNAME.md
21:39:50.433 DEBUG Processed: _posts/postgresql-initial-setup-users-and-databases.md
21:39:50.433 DEBUG Processed: _posts/sync-should-be-sync.md
21:39:50.433 DEBUG Processed: _posts/regen2-maintaining-it-s-own-openrc.md
21:39:50.433 DEBUG Processed: _posts/split-package-mask.md
21:39:50.434 DEBUG Processed: _posts/sync-target-support.md
21:39:50.435 DEBUG Processed: _posts/tag-builds.md
21:39:50.435 DEBUG Processed: _posts/to-Gentoo-dev-or-not-to-Gentoo-dev.md
21:39:50.435 DEBUG Processed: _posts/types-of-use-flags.md
21:39:50.473 DEBUG Theme config loaded.
21:39:50.478 DEBUG Processed: _config.yml
21:39:50.480 DEBUG Processed: source/css/style.styl
21:39:50.488 DEBUG Processed: source/fancybox/blank.gif
21:39:50.488 DEBUG Processed: source/fancybox/fancybox_loading.gif
21:39:50.489 DEBUG Processed: source/fancybox/fancybox_loading@2x.gif
21:39:50.492 DEBUG Processed: source/fancybox/fancybox_overlay.png
21:39:50.493 DEBUG Processed: source/fancybox/fancybox_sprite.png
21:39:50.494 DEBUG Processed: source/fancybox/fancybox_sprite@2x.png
21:39:50.494 DEBUG Processed: source/fancybox/jquery.fancybox.js
21:39:50.495 DEBUG Processed: source/fancybox/jquery.fancybox.css
21:39:50.495 DEBUG Processed: source/fancybox/jquery.fancybox.pack.js
21:39:50.495 DEBUG Processed: source/js/script.js
21:39:50.506 DEBUG Processed: layout/layout.ejs
21:39:50.506 DEBUG Processed: layout/archive.ejs
21:39:50.507 DEBUG Processed: layout/category.ejs
21:39:50.507 DEBUG Processed: layout/post.ejs
21:39:50.507 DEBUG Processed: layout/tag.ejs
21:39:50.507 DEBUG Processed: layout/page.ejs
21:39:50.508 DEBUG Processed: layout/index.ejs
21:39:50.524 DEBUG Processed: languages/default.yml
21:39:50.528 DEBUG Processed: languages/nl.yml
21:39:50.529 DEBUG Processed: languages/no.yml
21:39:50.529 DEBUG Processed: languages/fr.yml
21:39:50.530 DEBUG Processed: languages/ru.yml
21:39:50.531 DEBUG Processed: languages/zh-CN.yml
21:39:50.531 DEBUG Processed: languages/zh-TW.yml
21:39:50.532 DEBUG Processed: source/css/fonts/FontAwesome.otf
21:39:50.532 DEBUG Processed: source/css/fonts/fontawesome-webfont.eot
21:39:50.532 DEBUG Processed: source/css/fonts/fontawesome-webfont.woff
21:39:50.538 DEBUG Processed: source/fancybox/helpers/fancybox_buttons.png
21:39:50.538 DEBUG Processed: source/fancybox/helpers/jquery.fancybox-buttons.css
21:39:50.539 DEBUG Processed: source/fancybox/helpers/jquery.fancybox-buttons.js
21:39:50.539 DEBUG Processed: source/fancybox/helpers/jquery.fancybox-thumbs.css
21:39:50.540 DEBUG Processed: source/fancybox/helpers/jquery.fancybox-media.js
21:39:50.541 DEBUG Processed: source/fancybox/helpers/jquery.fancybox-thumbs.js
21:39:50.541 DEBUG Processed: source/css/fonts/fontawesome-webfont.ttf
21:39:50.558 DEBUG Processed: layout/_partial/archive-post.ejs
21:39:50.560 DEBUG Processed: layout/_partial/after-footer.ejs
21:39:50.560 DEBUG Processed: layout/_partial/archive.ejs
21:39:50.560 DEBUG Processed: layout/_partial/article.ejs
21:39:50.561 DEBUG Processed: layout/_partial/google-analytics.ejs
21:39:50.561 DEBUG Processed: layout/_partial/footer.ejs
21:39:50.562 DEBUG Processed: layout/_partial/head.ejs
21:39:50.562 DEBUG Processed: layout/_partial/header.ejs
21:39:50.563 DEBUG Processed: layout/_partial/mobile-nav.ejs
21:39:50.563 DEBUG Processed: layout/_partial/sidebar.ejs
21:39:50.565 DEBUG Processed: layout/_widget/archive.ejs
21:39:50.566 DEBUG Processed: layout/_widget/category.ejs
21:39:50.567 DEBUG Processed: layout/_widget/recent_posts.ejs
21:39:50.567 DEBUG Processed: layout/_widget/tag.ejs
21:39:50.567 DEBUG Processed: layout/_widget/tagcloud.ejs
21:39:50.572 DEBUG Processed: source/css/fonts/fontawesome-webfont.svg
21:39:50.574 DEBUG Processed: source/css/images/banner.jpg
21:39:50.576 DEBUG Processed: layout/_partial/post/category.ejs
21:39:50.577 DEBUG Processed: layout/_partial/post/nav.ejs
21:39:50.577 DEBUG Processed: layout/_partial/post/date.ejs
21:39:50.577 DEBUG Processed: layout/_partial/post/gallery.ejs
21:39:50.577 DEBUG Processed: layout/_partial/post/title.ejs
21:39:50.577 DEBUG Processed: layout/_partial/post/tag.ejs
21:39:51.334 FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: (unknown path) [Line 3, Column 1215]
  unexpected token: }}
    at Object.exports.prettifyError (C:\Users\xeno\IdeaProjects\blog\node_modules\nunjucks\src\lib.js:34:15)
    at new_cls.render (C:\Users\xeno\IdeaProjects\blog\node_modules\nunjucks\src\environment.js:469:27)
    at new_cls.renderString (C:\Users\xeno\IdeaProjects\blog\node_modules\nunjucks\src\environment.js:327:21)
    at C:\Users\xeno\IdeaProjects\blog\node_modules\hexo\lib\extend\tag.js:66:9
    at Promise._execute (C:\Users\xeno\IdeaProjects\blog\node_modules\bluebird\js\release\debuggability.js:300:9)
    at Promise._resolveFromExecutor (C:\Users\xeno\IdeaProjects\blog\node_modules\bluebird\js\release\promise.js:481:18)
    at new Promise (C:\Users\xeno\IdeaProjects\blog\node_modules\bluebird\js\release\promise.js:77:14)
    at Tag.render (C:\Users\xeno\IdeaProjects\blog\node_modules\hexo\lib\extend\tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (C:\Users\xeno\IdeaProjects\blog\node_modules\hexo\lib\hexo\post.js:253:16)
    at C:\Users\xeno\IdeaProjects\blog\node_modules\hexo\lib\hexo\render.js:65:19
    at tryCatcher (C:\Users\xeno\IdeaProjects\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\xeno\IdeaProjects\blog\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\xeno\IdeaProjects\blog\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\xeno\IdeaProjects\blog\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\xeno\IdeaProjects\blog\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\Users\xeno\IdeaProjects\blog\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\xeno\IdeaProjects\blog\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\xeno\IdeaProjects\blog\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
21:39:51.543 DEBUG Database saved
21:39:51.543 FATAL (unknown path) [Line 3, Column 1215]
  unexpected token: }}
Template render error: (unknown path) [Line 3, Column 1215]
  unexpected token: }}
    at Object.exports.prettifyError (C:\Users\xeno\IdeaProjects\blog\node_modules\nunjucks\src\lib.js:34:15)
    at new_cls.render (C:\Users\xeno\IdeaProjects\blog\node_modules\nunjucks\src\environment.js:469:27)
    at new_cls.renderString (C:\Users\xeno\IdeaProjects\blog\node_modules\nunjucks\src\environment.js:327:21)
    at C:\Users\xeno\IdeaProjects\blog\node_modules\hexo\lib\extend\tag.js:66:9
    at Promise._execute (C:\Users\xeno\IdeaProjects\blog\node_modules\bluebird\js\release\debuggability.js:300:9)
    at Promise._resolveFromExecutor (C:\Users\xeno\IdeaProjects\blog\node_modules\bluebird\js\release\promise.js:481:18)
    at new Promise (C:\Users\xeno\IdeaProjects\blog\node_modules\bluebird\js\release\promise.js:77:14)
    at Tag.render (C:\Users\xeno\IdeaProjects\blog\node_modules\hexo\lib\extend\tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (C:\Users\xeno\IdeaProjects\blog\node_modules\hexo\lib\hexo\post.js:253:16)
    at C:\Users\xeno\IdeaProjects\blog\node_modules\hexo\lib\hexo\render.js:65:19
    at tryCatcher (C:\Users\xeno\IdeaProjects\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\xeno\IdeaProjects\blog\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\xeno\IdeaProjects\blog\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\xeno\IdeaProjects\blog\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\xeno\IdeaProjects\blog\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\Users\xeno\IdeaProjects\blog\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\xeno\IdeaProjects\blog\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\xeno\IdeaProjects\blog\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
````

**Comment by NoahDragon** [comment]
It looks like in one of your posts, there has `{{` but no `}}`.

**Comment by xenoterracide** [comment]
yes, that was the problem but this exception didn't help me narrow it down when migrating from blogger. and that post has several `{{` and `}}` because it was a post on a template language... ultimately I decided to use Hugo because it continued processing, and only refused to process that template, as well as logging the error for just that file. Feel free to do what you want with this post.
