### ISSUE TITLE
hexo/node_modules/hexo/lib/plugins/helper/url_for.js出错

### ISSUE THREAD

**Issue by snowluliang** [hexojs/hexo#2427]
> before you submit your issue, please delete all the example code in template

## Environment Info

Node version(`node -v`)
```
v5.7.0
```

Your site `_config.yml`
```

# Hexo Configuration
...
```

Your theme `_config.yml`
```
# Hexo Configuration
...
```

Plugin version(`npm ls --depth 0`)
```
hexo-vanilla-site@0.0.0 ~/hexo-vanilla-site
├── hexo@3.1.1
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.0
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.1.1
├── hexo-renderer-marked@0.2.10
├── hexo-renderer-stylus@0.3.1
└── hexo-server@0.1.3
```

## For BUG

- BUG description
- the way to reproduce
- log with hexo <command> --debug

## For question
Unhandled rejection TypeError: path.substring is not a function
    at Object.urlForHelper (E:\软件\hexo\node_modules\hexo\lib\plugins\helper\ur
l_for.js:9:31)
    at wrapper (E:\软件\hexo\node_modules\lodash\lodash.js:4968:19)
    at Object.eval [as tpl] (eval at <anonymous> (E:\软件\hexo\node_modules\swig
\lib\swig.js:498:13), <anonymous>:103:119)
    at compiled (E:\软件\hexo\node_modules\swig\lib\swig.js:619:18)
    at Object.eval [as tpl] (eval at <anonymous> (E:\软件\hexo\node_modules\swig
\lib\swig.js:498:13), <anonymous>:718:119)
    at compiled (E:\软件\hexo\node_modules\swig\lib\swig.js:619:18)
    at _compiled (E:\软件\hexo\node_modules\hexo\lib\theme\view.js:127:30)
    at View.render (E:\软件\hexo\node_modules\hexo\lib\theme\view.js:29:15)
    at E:\软件\hexo\node_modules\hexo\lib\hexo\index.js:387:25
    at tryCatcher (E:\软件\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at E:\软件\hexo\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\软件\hexo\node_modules\hexo\lib\hexo\router.js:134:
3)
    at RouteStream.Readable.read (_stream_readable.js:348:10)
    at resume_ (_stream_readable.js:737:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
just push question

## For feature request

just push feature request

**Comment by snowluliang** [comment]
文件内容没有动过,下载了一个音乐播放器后,再次启动就不行了,请大神告诉我,哪里出错了

**Comment by NoahDragon** [comment]
什么音乐播放器呢？

**Comment by snowluliang** [comment]
你好,这个已经解决了,我重装了一下,就好了,好像是 **rss**设置问题,不知道为什么.

**Comment by NoahDragon** [comment]
好的，如仍有疑问可重开此贴。

**Comment by secwing** [comment]
请问重装一下就重装的什么？
