### ISSUE TITLE
Errors occurs when insert some words

### ISSUE THREAD

**Issue by jacentsao** [hexojs/hexo#2428]
> before you submit your issue, please delete all the example code in template

## Environment Info
hexo-cli: 1.0.2
os: Darwin 16.4.0 darwin x64
http_parser: 2.7.0
node: 6.9.4
v8: 5.1.281.89
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2j

## For BUG

- BUG description
After insert below words into .md file, errors occurs
{\displaystyle p(n)\approx 1-e^{-n^{2}/{2\cdot x}}} p(n)\approx 1-e^{{-n^{2}/{2\cdot x}}}
68,719,476,736 = 236	0.0000000000000004 (4 x 10-16)
2,199,023,255,552 = 241	0.0000000000004 (4 x 10-13)
70,368,744,177,664 = 246	0.0000000004 (4 x 10-10)
- the way to reproduce
- log with hexo <command> --debug
Unhandled rejection Template render error: (unknown path) [Line 7, Column 192]
  expected variable end
    at Object.exports.prettifyError (/Users/Eveee/Storage/workspace/hexo/node_modules/nunjucks/src/lib.js:34:15)
    at new_cls.render (/Users/Eveee/Storage/workspace/hexo/node_modules/nunjucks/src/environment.js:469:27)
    at new_cls.renderString (/Users/Eveee/Storage/workspace/hexo/node_modules/nunjucks/src/environment.js:327:21)
    at /Users/Eveee/Storage/workspace/hexo/node_modules/hexo/lib/extend/tag.js:66:9
    at Promise._execute (/Users/Eveee/Storage/workspace/hexo/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Users/Eveee/Storage/workspace/hexo/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/Users/Eveee/Storage/workspace/hexo/node_modules/bluebird/js/release/promise.js:77:14)
    at Tag.render (/Users/Eveee/Storage/workspace/hexo/node_modules/hexo/lib/extend/tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (/Users/Eveee/Storage/workspace/hexo/node_modules/hexo/lib/hexo/post.js:253:16)
    at /Users/Eveee/Storage/workspace/hexo/node_modules/hexo/lib/hexo/render.js:65:19
    at tryCatcher (/Users/Eveee/Storage/workspace/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/Eveee/Storage/workspace/hexo/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/Eveee/Storage/workspace/hexo/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/Eveee/Storage/workspace/hexo/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/Eveee/Storage/workspace/hexo/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/Users/Eveee/Storage/workspace/hexo/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/Eveee/Storage/workspace/hexo/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/Eveee/Storage/workspace/hexo/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)

Thanks for you kindly help

**Comment by NoahDragon** [comment]
Please try to use the raw tag to wrap the content. https://hexo.io/docs/tag-plugins.html#Raw
