### ISSUE TITLE
hexo deploy 出现TypeError: Cannot read property 'filename' of undefined

### ISSUE THREAD

**Issue by wendingp** [hexojs/hexo#2431]
```
INFO  Deploying: git
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: Cannot read property 'filename' of undefined
    at Object.precompile (/Users/pwd/work/hexo/node_modules/swig/lib/swig.js:505:40)
    at Object.compile (/Users/pwd/work/hexo/node_modules/swig/lib/swig.js:606:16)
    at commitMessage (/Users/pwd/work/hexo/node_modules/hexo-deployer-git/lib/deployer.js:103:15)
    at Hexo.module.exports (/Users/pwd/work/hexo/node_modules/hexo-deployer-git/lib/deployer.js:22:17)
    at Hexo.tryCatcher (/Users/pwd/work/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Users/pwd/work/hexo/node_modules/bluebird/js/release/method.js:15:34)
    at /Users/pwd/work/hexo/node_modules/hexo/lib/plugins/console/deploy.js:55:28
    at tryCatcher (/Users/pwd/work/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/Users/pwd/work/hexo/node_modules/bluebird/js/release/reduce.js:155:18)
    at Object.gotAccum (/Users/pwd/work/hexo/node_modules/bluebird/js/release/reduce.js:144:25)
    at Object.tryCatcher (/Users/pwd/work/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/pwd/work/hexo/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/pwd/work/hexo/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/Users/pwd/work/hexo/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/Users/pwd/work/hexo/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/Users/pwd/work/hexo/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/pwd/work/hexo/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
FATAL Cannot read property 'filename' of undefined
TypeError: Cannot read property 'filename' of undefined
    at Object.precompile (/Users/pwd/work/hexo/node_modules/swig/lib/swig.js:505:40)
    at Object.compile (/Users/pwd/work/hexo/node_modules/swig/lib/swig.js:606:16)
    at commitMessage (/Users/pwd/work/hexo/node_modules/hexo-deployer-git/lib/deployer.js:103:15)
    at Hexo.module.exports (/Users/pwd/work/hexo/node_modules/hexo-deployer-git/lib/deployer.js:22:17)
    at Hexo.tryCatcher (/Users/pwd/work/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Users/pwd/work/hexo/node_modules/bluebird/js/release/method.js:15:34)
    at /Users/pwd/work/hexo/node_modules/hexo/lib/plugins/console/deploy.js:55:28
    at tryCatcher (/Users/pwd/work/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/Users/pwd/work/hexo/node_modules/bluebird/js/release/reduce.js:155:18)
    at Object.gotAccum (/Users/pwd/work/hexo/node_modules/bluebird/js/release/reduce.js:144:25)
    at Object.tryCatcher (/Users/pwd/work/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/pwd/work/hexo/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/pwd/work/hexo/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/Users/pwd/work/hexo/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/Users/pwd/work/hexo/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/Users/pwd/work/hexo/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/pwd/work/hexo/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

**Comment by wanzaiwanger** [comment]
Same issue here.

**Comment by NoahDragon** [comment]
Please check the file path in the theme folder. Something like:
```
<%- partial('_partial/paginator') %>
```
Make sure those paths are correct.

**Comment by oozliuoo** [comment]
Same issues here, cannot find any <%- partial('_partial/paginator') %> in my theme...

it works well in localhost

**Comment by NoahDragon** [comment]
@oozliuoo Could you share your Hexo folder? I can take a look at it.

**Comment by oozliuoo** [comment]
<img width="295" alt="screen shot 2017-04-09 at 1 09 17 pm" src="https://cloud.githubusercontent.com/assets/6527286/24840599/b9ca6c62-1d24-11e7-8a6b-40203796cdd0.png">


Thanks @NoahDragon , This is a screenshot of my hexo folder. I've added the **"next" theme** to my **theme folder**, and updated post under **source**. Additionally, I added an **img/** folder under **source**

**Comment by oozliuoo** [comment]
<img width="270" alt="screen shot 2017-04-09 at 1 43 02 pm" src="https://cloud.githubusercontent.com/assets/6527286/24840813/6ee3ddd2-1d29-11e7-9ec7-9202b7f9561d.png">

This is a screenshot for the structure of **next/** folder

**Comment by NoahDragon** [comment]
@oozliuoo The message in git config is following swig template, so `{{ }}` tries to find the variable inside, hence caused the error.

![image](https://cloud.githubusercontent.com/assets/5704064/24841158/3128a3ca-1d4b-11e7-9c84-73c35028bf0c.png)

**Comment by oozliuoo** [comment]
I see, that did solve my problem! Thanks!
