### ISSUE TITLE
markdown包含{{.a}}时，hexo g出错

### ISSUE THREAD

**Issue by tailnode** [hexojs/hexo#2440]
## Environment Info

Node version(`node -v`)
```
v6.9.2
```

Plugin version(`npm ls --depth 0`)
```
$ npm ls --depth 0
hexo-site@0.0.0 E:\hexo
+-- bluebird@3.5.0 extraneous
+-- camel-case@3.0.0 extraneous
+-- cross-spawn@4.0.2 extraneous
+-- hexo@3.2.2
+-- hexo-generator-archive@0.1.4
+-- hexo-generator-category@0.1.3
+-- hexo-generator-index@0.2.0
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-ejs@0.2.0
+-- hexo-renderer-marked@0.2.11
+-- hexo-renderer-stylus@0.3.1
+-- hexo-server@0.2.0
+-- hexo-util@0.6.0 extraneous
+-- highlight.js@9.9.0 extraneous
+-- html-entities@1.2.0 extraneous
+-- isexe@1.1.2 extraneous
+-- lower-case@1.1.4 extraneous
+-- lru-cache@4.0.2 extraneous
+-- no-case@2.3.1 extraneous
+-- pseudomap@1.0.2 extraneous
+-- striptags@2.2.1 extraneous
+-- upper-case@1.1.3 extraneous
+-- which@1.2.12 extraneous
`-- yallist@2.0.0 extraneous

npm ERR! extraneous: bluebird@3.5.0 E:\hexo\node_modules\bluebird
npm ERR! extraneous: camel-case@3.0.0 E:\hexo\node_modules\camel-case
npm ERR! extraneous: cross-spawn@4.0.2 E:\hexo\node_modules\cross-spawn
npm ERR! extraneous: hexo-util@0.6.0 E:\hexo\node_modules\hexo-util
npm ERR! extraneous: highlight.js@9.9.0 E:\hexo\node_modules\highlight.js
npm ERR! extraneous: html-entities@1.2.0 E:\hexo\node_modules\html-entities
npm ERR! extraneous: isexe@1.1.2 E:\hexo\node_modules\isexe
npm ERR! extraneous: lower-case@1.1.4 E:\hexo\node_modules\lower-case
npm ERR! extraneous: lru-cache@4.0.2 E:\hexo\node_modules\lru-cache
npm ERR! extraneous: no-case@2.3.1 E:\hexo\node_modules\no-case
npm ERR! extraneous: pseudomap@1.0.2 E:\hexo\node_modules\pseudomap
npm ERR! extraneous: striptags@2.2.1 E:\hexo\node_modules\striptags
npm ERR! extraneous: upper-case@1.1.3 E:\hexo\node_modules\upper-case
npm ERR! extraneous: which@1.2.12 E:\hexo\node_modules\which
npm ERR! extraneous: yallist@2.0.0 E:\hexo\node_modules\yallist

```

## For BUG
当markdown中包含{{.a}}时（{{.a}}是golang的模版标签，在代码块中不会出错），hexo g出错

log:
```
$ hexo g --debug
11:53:22.893 DEBUG Hexo version: 3.2.2
11:53:22.895 DEBUG Working directory: E:\hexo\
11:53:23.012 DEBUG Config loaded: E:\hexo\_config.yml
11:53:23.028 DEBUG Plugin loaded: hexo-generator-archive
11:53:23.032 DEBUG Plugin loaded: hexo-generator-index
11:53:23.036 DEBUG Plugin loaded: hexo-generator-tag
11:53:23.039 DEBUG Plugin loaded: hexo-generator-category
11:53:23.041 DEBUG Plugin loaded: hexo-renderer-stylus
11:53:23.132 DEBUG Plugin loaded: hexo-renderer-marked
11:53:23.295 DEBUG Plugin loaded: hexo-server
11:53:23.301 DEBUG Script loaded: themes\next\scripts\merge-configs.js
11:53:23.306 DEBUG Plugin loaded: hexo-renderer-ejs
11:53:23.307 DEBUG Script loaded: themes\next\scripts\tags\center-quote.js
11:53:23.307 DEBUG Script loaded: themes\next\scripts\tags\button.js
11:53:23.394 DEBUG Script loaded: themes\next\scripts\tags\exturl.js
11:53:23.396 DEBUG Script loaded: themes\next\scripts\merge.js
11:53:23.396 DEBUG Script loaded: themes\next\scripts\tags\full-image.js
11:53:23.397 DEBUG Script loaded: themes\next\scripts\tags\note.js
11:53:23.398 DEBUG Script loaded: themes\next\scripts\tags\group-pictures.js
11:53:23.399 DEBUG Loading database.
11:53:23.508 INFO  Start processing
11:53:23.627 DEBUG Processed: _posts/Go的内存模型.md
11:53:23.627 DEBUG Processed: _posts/alertmanager报警规则详解.md
11:53:23.627 DEBUG Processed: _posts/alertmanager邮件模版.md
11:53:23.627 DEBUG Processed: _posts/IDEA使用技巧收集.md
11:53:23.627 DEBUG Processed: _posts/beego orm中时区的问题.md
11:53:23.627 DEBUG Processed: _posts/ghost修改代码高亮和字体.md
11:53:23.627 DEBUG Processed: _posts/docker容器间通信的一种方法.md
11:53:23.628 DEBUG Processed: _posts/golang在编译时用ldflags设置变量的值.md
11:53:23.628 DEBUG Processed: _posts/golang闭包.md
11:53:23.628 DEBUG Processed: _posts/k8s-apiserver.md
11:53:23.630 DEBUG Processed: _posts/了解etcd.md
11:53:23.631 DEBUG Processed: _posts/了解kubernetes的ConfigMap.md
11:53:23.631 DEBUG Processed: _posts/常用命令.md
11:53:23.631 DEBUG Processed: _posts/深入理解Go语言的slice.md
11:53:23.631 DEBUG Processed: about/index.md
11:53:23.631 DEBUG Processed: tags/index.md
11:53:23.684 DEBUG Theme config loaded.
11:53:23.691 DEBUG Processed: _config.yml
11:53:23.691 DEBUG Processed: source/css/main.styl
11:53:23.692 DEBUG Processed: source/images/algolia_logo.svg
11:53:23.692 DEBUG Processed: source/images/cc-by-nc-nd.svg
11:53:23.693 DEBUG Processed: source/images/avatar.gif
11:53:23.693 DEBUG Processed: source/images/cc-by-nc-sa.svg
11:53:23.694 DEBUG Processed: source/images/cc-by-nc.svg
11:53:23.694 DEBUG Processed: source/images/cc-by-nd.svg
11:53:23.694 DEBUG Processed: source/images/cc-by-sa.svg
11:53:23.694 DEBUG Processed: source/images/cc-by.svg
11:53:23.696 DEBUG Processed: source/images/cc-zero.svg
11:53:23.696 DEBUG Processed: source/images/loading.gif
11:53:23.696 DEBUG Processed: source/images/placeholder.gif
11:53:23.697 DEBUG Processed: source/images/quote-l.svg
11:53:23.698 DEBUG Processed: source/images/quote-r.svg
11:53:23.698 DEBUG Processed: source/images/searchicon.png
11:53:23.932 DEBUG Processed: layout/_layout.swig
11:53:23.932 DEBUG Processed: layout/archive.swig
11:53:23.932 DEBUG Processed: layout/index.swig
11:53:23.932 DEBUG Processed: layout/category.swig
11:53:23.932 DEBUG Processed: layout/schedule.swig
11:53:23.932 DEBUG Processed: layout/post.swig
11:53:23.932 DEBUG Processed: layout/page.swig
11:53:23.932 DEBUG Processed: layout/tag.swig
11:53:23.947 DEBUG Processed: languages/de.yml
11:53:23.947 DEBUG Processed: languages/en.yml
11:53:23.947 DEBUG Processed: languages/default.yml
11:53:23.947 DEBUG Processed: languages/fr-FR.yml
11:53:23.947 DEBUG Processed: languages/id.yml
11:53:23.947 DEBUG Processed: languages/ja.yml
11:53:23.947 DEBUG Processed: languages/ko.yml
11:53:23.947 DEBUG Processed: languages/pt-BR.yml
11:53:23.951 DEBUG Processed: languages/pt.yml
11:53:23.951 DEBUG Processed: languages/ru.yml
11:53:23.951 DEBUG Processed: languages/zh-Hans.yml
11:53:23.951 DEBUG Processed: languages/zh-tw.yml
11:53:23.951 DEBUG Processed: languages/zh-hk.yml
11:53:23.954 DEBUG Processed: source/js/src/affix.js
11:53:23.954 DEBUG Processed: source/js/src/algolia-search.js
11:53:23.954 DEBUG Processed: source/js/src/exturl.js
11:53:23.955 DEBUG Processed: source/js/src/bootstrap.js
11:53:23.955 DEBUG Processed: source/js/src/hook-duoshuo.js
11:53:23.955 DEBUG Processed: source/js/src/motion.js
11:53:23.955 DEBUG Processed: source/js/src/post-details.js
11:53:23.955 DEBUG Processed: source/js/src/scrollspy.js
11:53:23.956 DEBUG Processed: source/js/src/utils.js
11:53:23.956 DEBUG Processed: source/lib/algolia-instant-search/instantsearch.min.css
11:53:23.956 DEBUG Processed: source/lib/canvas-nest/canvas-nest.min.js
11:53:23.957 DEBUG Processed: source/lib/font-awesome/HELP-US-OUT.txt
11:53:23.957 DEBUG Processed: source/lib/font-awesome/bower.json
11:53:23.957 DEBUG Processed: source/lib/jquery_lazyload/CONTRIBUTING.md
11:53:23.957 DEBUG Processed: source/lib/jquery_lazyload/README.md
11:53:23.957 DEBUG Processed: source/lib/jquery_lazyload/jquery.lazyload.js
11:53:23.958 DEBUG Processed: source/lib/jquery_lazyload/bower.json
11:53:23.959 DEBUG Processed: source/lib/fastclick/LICENSE
11:53:23.959 DEBUG Processed: source/lib/fastclick/bower.json
11:53:23.959 DEBUG Processed: source/lib/jquery_lazyload/jquery.scrollstop.js
11:53:23.959 DEBUG Processed: source/lib/fastclick/README.md
11:53:23.978 DEBUG Processed: source/lib/velocity/bower.json
11:53:23.978 DEBUG Processed: source/lib/velocity/velocity.min.js
11:53:23.978 DEBUG Processed: source/lib/velocity/velocity.ui.js
11:53:23.978 DEBUG Processed: source/lib/velocity/velocity.ui.min.js
11:53:23.978 DEBUG Processed: source/lib/jquery/index.js
11:53:24.033 DEBUG Processed: layout/_custom/sidebar.swig
11:53:24.034 DEBUG Processed: layout/_custom/header.swig
11:53:24.034 DEBUG Processed: layout/_macro/reward.swig
11:53:24.034 DEBUG Processed: layout/_macro/post.swig
11:53:24.034 DEBUG Processed: layout/_macro/wechat-subscriber.swig
11:53:24.034 DEBUG Processed: layout/_macro/sidebar.swig
11:53:24.034 DEBUG Processed: layout/_partials/comments.swig
11:53:24.034 DEBUG Processed: layout/_partials/duoshuo-hot-articles.swig
11:53:24.034 DEBUG Processed: layout/_partials/footer.swig
11:53:24.034 DEBUG Processed: layout/_macro/post-collapse.swig
11:53:24.034 DEBUG Processed: layout/_partials/header.swig
11:53:24.034 DEBUG Processed: layout/_partials/head.swig
11:53:24.034 DEBUG Processed: layout/_partials/pagination.swig
11:53:24.034 DEBUG Processed: layout/_partials/page-header.swig
11:53:24.034 DEBUG Processed: layout/_partials/search.swig
11:53:24.034 DEBUG Processed: layout/_scripts/boostrap.swig
11:53:24.034 DEBUG Processed: layout/_scripts/baidu-push.swig
11:53:24.034 DEBUG Processed: layout/_scripts/commons.swig
11:53:24.034 DEBUG Processed: layout/_scripts/vendors.swig
11:53:24.036 DEBUG Processed: source/js/src/schemes/pisces.js
11:53:24.037 DEBUG Processed: source/lib/fancybox/source/blank.gif
11:53:24.037 DEBUG Processed: source/lib/fancybox/source/fancybox_loading.gif
11:53:24.037 DEBUG Processed: source/lib/fancybox/source/fancybox_loading@2x.gif
11:53:24.037 DEBUG Processed: source/lib/fancybox/source/fancybox_overlay.png
11:53:24.037 DEBUG Processed: source/lib/fancybox/source/fancybox_sprite.png
11:53:24.037 DEBUG Processed: source/lib/fancybox/source/fancybox_sprite@2x.png
11:53:24.037 DEBUG Processed: source/lib/fancybox/source/jquery.fancybox.css
11:53:24.038 DEBUG Processed: source/lib/fancybox/source/jquery.fancybox.pack.js
11:53:24.038 DEBUG Processed: source/lib/fancybox/source/jquery.fancybox.js
11:53:24.038 DEBUG Processed: source/lib/font-awesome/css/font-awesome.css
11:53:24.038 DEBUG Processed: source/lib/font-awesome/css/font-awesome.css.map
11:53:24.038 DEBUG Processed: source/lib/font-awesome/css/font-awesome.min.css
11:53:24.038 DEBUG Processed: source/lib/fastclick/lib/fastclick.js
11:53:24.038 DEBUG Processed: source/lib/fastclick/lib/fastclick.min.js
11:53:24.039 DEBUG Processed: source/lib/ua-parser-js/dist/ua-parser.min.js
11:53:24.039 DEBUG Processed: source/lib/ua-parser-js/dist/ua-parser.pack.js
11:53:24.044 DEBUG Processed: layout/_scripts/schemes/muse.swig
11:53:24.045 DEBUG Processed: source/lib/font-awesome/fonts/fontawesome-webfont.eot
11:53:24.045 DEBUG Processed: source/lib/font-awesome/fonts/fontawesome-webfont.woff
11:53:24.045 DEBUG Processed: source/lib/font-awesome/fonts/fontawesome-webfont.woff2
11:53:24.045 DEBUG Processed: source/lib/font-awesome/fonts/FontAwesome.otf
11:53:24.067 DEBUG Processed: layout/_scripts/schemes/mist.swig
11:53:24.068 DEBUG Processed: layout/_partials/head/custom-head.swig
11:53:24.068 DEBUG Processed: layout/_components/algolia-search/assets.swig
11:53:24.068 DEBUG Processed: layout/_components/algolia-search/dom.swig
11:53:24.068 DEBUG Processed: layout/_partials/head/external-fonts.swig
11:53:24.068 DEBUG Processed: layout/_partials/search/localsearch.swig
11:53:24.068 DEBUG Processed: layout/_partials/search/tinysou.swig
11:53:24.068 DEBUG Processed: layout/_partials/search/swiftype.swig
11:53:24.068 DEBUG Processed: layout/_partials/share/baidushare.swig
11:53:24.068 DEBUG Processed: layout/_partials/share/jiathis.swig
11:53:24.068 DEBUG Processed: layout/_partials/share/duoshuo_share.swig
11:53:24.068 DEBUG Processed: layout/_partials/share/add-this.swig
11:53:24.068 DEBUG Processed: layout/_scripts/pages/post-details.swig
11:53:24.068 DEBUG Processed: layout/_scripts/schemes/pisces.swig
11:53:24.068 DEBUG Processed: layout/_scripts/third-party/localsearch.swig
11:53:24.068 DEBUG Processed: layout/_scripts/third-party/analytics.swig
11:53:24.068 DEBUG Processed: layout/_scripts/third-party/comments.swig
11:53:24.068 DEBUG Processed: layout/_scripts/third-party/schedule.swig
11:53:24.068 DEBUG Processed: layout/_scripts/third-party/lean-analytics.swig
11:53:24.068 DEBUG Processed: layout/_scripts/third-party/tinysou.swig
11:53:24.068 DEBUG Processed: layout/_scripts/third-party/mathjax.swig
11:53:24.074 DEBUG Processed: source/lib/velocity/velocity.js
11:53:24.076 DEBUG Processed: source/lib/fancybox/source/helpers/fancybox_buttons.png
11:53:24.079 DEBUG Processed: source/lib/fancybox/source/helpers/jquery.fancybox-buttons.css
11:53:24.079 DEBUG Processed: source/lib/fancybox/source/helpers/jquery.fancybox-media.js
11:53:24.079 DEBUG Processed: source/lib/fancybox/source/helpers/jquery.fancybox-thumbs.js
11:53:24.079 DEBUG Processed: source/lib/fancybox/source/helpers/jquery.fancybox-thumbs.css
11:53:24.080 DEBUG Processed: source/lib/fancybox/source/helpers/jquery.fancybox-buttons.js
11:53:24.080 DEBUG Processed: source/lib/font-awesome/fonts/fontawesome-webfont.ttf
11:53:24.098 DEBUG Processed: layout/_scripts/third-party/analytics/application-insights.swig
11:53:24.099 DEBUG Processed: layout/_scripts/third-party/analytics/baidu-analytics.swig
11:53:24.099 DEBUG Processed: layout/_scripts/third-party/analytics/busuanzi-counter.swig
11:53:24.099 DEBUG Processed: layout/_scripts/third-party/analytics/cnzz-analytics.swig
11:53:24.099 DEBUG Processed: layout/_scripts/third-party/analytics/facebook-sdk.swig
11:53:24.099 DEBUG Processed: layout/_scripts/third-party/analytics/google-analytics.swig
11:53:24.099 DEBUG Processed: layout/_scripts/third-party/analytics/tencent-mta.swig
11:53:24.099 DEBUG Processed: layout/_scripts/third-party/analytics/tencent-analytics.swig
11:53:24.099 DEBUG Processed: layout/_scripts/third-party/comments/disqus.swig
11:53:24.099 DEBUG Processed: layout/_scripts/third-party/analytics/vkontakte-api.swig
11:53:24.099 DEBUG Processed: layout/_scripts/third-party/comments/gentie.swig
11:53:24.099 DEBUG Processed: layout/_scripts/third-party/comments/livere.swig
11:53:24.099 DEBUG Processed: layout/_scripts/third-party/comments/youyan.swig
11:53:24.099 DEBUG Processed: layout/_scripts/third-party/comments/hypercomments.swig
11:53:24.099 DEBUG Processed: layout/_scripts/third-party/comments/duoshuo.swig
11:53:24.100 DEBUG Processed: source/lib/algolia-instant-search/instantsearch.min.js
11:53:24.100 DEBUG Processed: source/lib/font-awesome/fonts/fontawesome-webfont.svg
11:53:24.149 FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: (unknown path) [Line 1, Column 1]
  unexpected token: .
    at Object.exports.prettifyError (E:\hexo\node_modules\hexo\node_modules\nunjucks\src\lib.js:34:15)
    at new_cls.render (E:\hexo\node_modules\hexo\node_modules\nunjucks\src\environment.js:469:27)
    at new_cls.renderString (E:\hexo\node_modules\hexo\node_modules\nunjucks\src\environment.js:327:21)
    at E:\hexo\node_modules\hexo\lib\extend\tag.js:66:9
    at Promise._execute (E:\hexo\node_modules\hexo\node_modules\bluebird\js\release\debuggability.js:300:9)
    at Promise._resolveFromExecutor (E:\hexo\node_modules\hexo\node_modules\bluebird\js\release\promise.js:483:18)
    at new Promise (E:\hexo\node_modules\hexo\node_modules\bluebird\js\release\promise.js:79:10)
    at Tag.render (E:\hexo\node_modules\hexo\lib\extend\tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (E:\hexo\node_modules\hexo\lib\hexo\post.js:253:16)
    at E:\hexo\node_modules\hexo\lib\hexo\render.js:65:19
    at tryCatcher (E:\hexo\node_modules\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\hexo\node_modules\hexo\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (E:\hexo\node_modules\hexo\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (E:\hexo\node_modules\hexo\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (E:\hexo\node_modules\hexo\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (E:\hexo\node_modules\hexo\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (E:\hexo\node_modules\hexo\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (E:\hexo\node_modules\hexo\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
11:53:24.189 DEBUG Database saved
11:53:24.190 FATAL (unknown path) [Line 1, Column 1]
  unexpected token: .
Template render error: (unknown path) [Line 1, Column 1]
  unexpected token: .
    at Object.exports.prettifyError (E:\hexo\node_modules\hexo\node_modules\nunjucks\src\lib.js:34:15)
    at new_cls.render (E:\hexo\node_modules\hexo\node_modules\nunjucks\src\environment.js:469:27)
    at new_cls.renderString (E:\hexo\node_modules\hexo\node_modules\nunjucks\src\environment.js:327:21)
    at E:\hexo\node_modules\hexo\lib\extend\tag.js:66:9
    at Promise._execute (E:\hexo\node_modules\hexo\node_modules\bluebird\js\release\debuggability.js:300:9)
    at Promise._resolveFromExecutor (E:\hexo\node_modules\hexo\node_modules\bluebird\js\release\promise.js:483:18)
    at new Promise (E:\hexo\node_modules\hexo\node_modules\bluebird\js\release\promise.js:79:10)
    at Tag.render (E:\hexo\node_modules\hexo\lib\extend\tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (E:\hexo\node_modules\hexo\lib\hexo\post.js:253:16)
    at E:\hexo\node_modules\hexo\lib\hexo\render.js:65:19
    at tryCatcher (E:\hexo\node_modules\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\hexo\node_modules\hexo\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (E:\hexo\node_modules\hexo\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (E:\hexo\node_modules\hexo\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (E:\hexo\node_modules\hexo\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (E:\hexo\node_modules\hexo\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (E:\hexo\node_modules\hexo\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (E:\hexo\node_modules\hexo\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

**Comment by Lizhooh** [comment]
好像，不给使用  {{  }}

**Comment by NoahDragon** [comment]
可以用Raw tag： https://hexo.io/docs/tag-plugins.html#Raw
