### ISSUE TITLE
hexo server can't start correct

### ISSUE THREAD

**Issue by GoDotDotDot** [hexojs/hexo#2441]
## Environment Info
MAC OS X 10.11
Node version(`node -v`)
```
v7.3
```
## For BUG
- BUG description
when i use `hexo server -p 4000` on os x system, unfortunately,the terminal give me th following message:
```
hukuideMacBook-Air:hexo-blog-src chukui$ hexo server -p 4000
INFO  Start processing
INFO  update Optimize IMG: css/fonts/fontawesome/fontawesome-webfont.svg [ 100.00% saved]
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: dyld: Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
  Referenced from: /Users/chukui/Documents/frontend/hexo/hexo-blog-src/node_modules/.4.1.1@mozjpeg/vendor/cjpeg
  Reason: image not found

    at Promise.all.then.arr (/Users/chukui/Documents/frontend/hexo/hexo-blog-src/node_modules/.0.5.1@execa/index.js:201:11)
    at process._tickCallback (internal/process/next_tick.js:103:7)
INFO  update Optimize IMG: img/img-err.png [ 2.46% saved]
INFO  update Optimize IMG: img/img-loading.png [ 3.09% saved]
FATAL dyld: Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
  Referenced from: /Users/chukui/Documents/frontend/hexo/hexo-blog-src/node_modules/.4.1.1@mozjpeg/vendor/cjpeg
  Reason: image not found

Error: dyld: Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
  Referenced from: /Users/chukui/Documents/frontend/hexo/hexo-blog-src/node_modules/.4.1.1@mozjpeg/vendor/cjpeg
  Reason: image not found

    at Promise.all.then.arr (/Users/chukui/Documents/frontend/hexo/hexo-blog-src/node_modules/.0.5.1@execa/index.js:201:11)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```
and it will be ok running on windows 7.what can I do?
source code on [github](https://github.com/GoDotDotDot/hexo-blog)

**Comment by NoahDragon** [comment]
Based on the answers from [stackoverflow](http://stackoverflow.com/questions/8455432/installing-node-js-with-package-installer-dyldlibrary-not-loaded-error), it seems your environment missing the openssl.
