### ISSUE TITLE
multi-config fails during Hexo initialization if it tries to log

### ISSUE THREAD

**Issue by tuck182** [hexojs/hexo#2499]
## Environment Info

Node version(`node -v`): 6.9.1

Hexo and Plugin version(`npm ls --depth 0`): 3.3.0

## BUG

When creating a Hexo object, if anything in multi_config_path causes a log attempt, it fails with:
```
[21:12:02] TypeError: Cannot read property 'w' of undefined
    at multiConfigPath (.../node_modules/hexo/lib/hexo/multi_config_path.js:27:12)
    at new Hexo (.../node_modules/hexo/lib/hexo/index.js:57:36)
```

This is because multi_config_path initialization happens in the Hexo constructor before the log object is created and assigned to `this` (which is what's passed to multi-config as `ctx`).

**Comment by NoahDragon** [comment]
Which command did you run? `hexo init` or `hexo new`?

**Comment by tuck182** [comment]
I ran this:

  const hexo = new Hexo(CLIENT_ROOT, {
    config: path.join(DIST_ROOT, '_config.yml'),
    staging: process.env.NODE_ENV || 'development',
  });
  hexo.plugin_dir = P(PROJECT_ROOT, 'node_modules');
  hexo.call('generate')

**Comment by tuck182** [comment]
Sorry, when I said "Hexo initialization" I should have been more clear. I meant "initialization of the Hexo object in code", not a project structure.

**Comment by NoahDragon** [comment]
No worries. Thanks for the info. I will try to reproduce.

**Comment by NoahDragon** [comment]
Not sure if the PR fix the issue here. https://github.com/hexojs/hexo/pull/2520

**Comment by tuck182** [comment]
That looks like the right solution; I'll test it later tonight. Thanks!

**Comment by stevenjoezhang** [comment]
Closing due to inactivity, please re-open if it is still outstanding.
