### ISSUE TITLE
FATAL Cannot find module icessun.github.io\node_modules\hexo-generate-feed

### ISSUE THREAD

**Issue by icessun** [hexojs/hexo#2512]
FATAL Cannot find module 'C:\Documents and Settings\Administrator\桌面\hexo\icessun.github.io\node_modules\hexo-generate-feed'
Error: Cannot find module 'C:\Documents and Settings\Administrator\桌面\hexo\icessun.github.io\node_modules\hexo-generate-feed'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.require.resolve (internal/module.js:16:19)
    at C:\Documents and Settings\Administrator\桌面\hexo\icessun.github.io\node_modules\hexo\lib\hexo\load_plugins.js:52:24
    at tryCatcher (C:\Documents and Settings\Administrator\桌面\hexo\icessun.github.io\node_modules\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (C:\Documents and Settings\Administrator\桌面\hexo\icessun.github.io\node_modules\hexo\node_modules\bluebird\js\release\map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (C:\Documents and Settings\Administrator\桌面\hexo\icessun.github.io\node_modules\hexo\node_modules\bluebird\js\release\promise_array.js:114:31)
    at MappingPromiseArray.init (C:\Documents and Settings\Administrator\桌面\hexo\icessun.github.io\node_modules\hexo\node_modules\bluebird\js\release\promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (C:\Documents and Settings\Administrator\桌面\hexo\icessun.github.io\node_modules\hexo\node_modules\bluebird\js\release\map.js:30:10)
    at Async._drainQueue (C:\Documents and Settings\Administrator\桌面\hexo\icessun.github.io\node_modules\hexo\node_modules\bluebird\js\release\async.js:138:12)
    at Async._drainQueues (C:\Documents and Settings\Administrator\桌面\hexo\icessun.github.io\node_modules\hexo\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Documents and Settings\Administrator\桌面\hexo\icessun.github.io\node_modules\hexo\node_modules\bluebird\js\release\async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by icessun** [comment]
hexo s本地浏览时出现这个错误

**Comment by NoahDragon** [comment]
尽可能将hexo放于纯英文的路径中，比如`c:\hexo`。中文路径总会有些莫名其妙的bug

**Comment by icessun** [comment]
@NoahDragon 目前这个问题解决，重新安装了一下hexo，多谢提醒，中文目录下面是好多莫名其妙的bug，再次感谢
