### ISSUE TITLE
npm install -g hexo-cli 和sudo npm install -g hexo-cli安装报错,怎么解?

### ISSUE THREAD

**Issue by LoSenTrad** [hexojs/hexo#2542]
module.js:472
    throw err;
    ^

Error: Cannot find module './internal/streams/BufferList'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_readable.js:58:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by NoahDragon** [comment]
https://github.com/npm/npm/issues/14343

可能是nodejs的问题，是否尝试了重装？
