### ISSUE TITLE
Cannot read property 'count' of null

### ISSUE THREAD

**Issue by Adherentman** [hexojs/hexo#2556]
## Environment Info

Node version(`node -v`):

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 

## For question

blog git:(master) ✗ hexo d
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: Cannot read property 'count' of null
    at Hexo.module.exports (/Users/xuzihao/blog/node_modules/hexo-baidu-url-submit/lib/generator.js:4:40)
    at Hexo.tryCatcher (/Users/xuzihao/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Users/xuzihao/blog/node_modules/bluebird/js/release/method.js:15:34)
    at /Users/xuzihao/blog/node_modules/hexo/lib/hexo/index.js:340:24
    at tryCatcher (/Users/xuzihao/blog/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/Users/xuzihao/blog/node_modules/bluebird/js/release/map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (/Users/xuzihao/blog/node_modules/bluebird/js/release/promise_array.js:114:31)
    at MappingPromiseArray.init (/Users/xuzihao/blog/node_modules/bluebird/js/release/promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (/Users/xuzihao/blog/node_modules/bluebird/js/release/map.js:30:10)
    at Async._drainQueue (/Users/xuzihao/blog/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/Users/xuzihao/blog/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/xuzihao/blog/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
FATAL Cannot read property 'count' of null
TypeError: Cannot read property 'count' of null
    at Hexo.module.exports (/Users/xuzihao/blog/node_modules/hexo-baidu-url-submit/lib/generator.js:4:40)
    at Hexo.tryCatcher (/Users/xuzihao/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Users/xuzihao/blog/node_modules/bluebird/js/release/method.js:15:34)
    at /Users/xuzihao/blog/node_modules/hexo/lib/hexo/index.js:340:24
    at tryCatcher (/Users/xuzihao/blog/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/Users/xuzihao/blog/node_modules/bluebird/js/release/map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (/Users/xuzihao/blog/node_modules/bluebird/js/release/promise_array.js:114:31)
    at MappingPromiseArray.init (/Users/xuzihao/blog/node_modules/bluebird/js/release/promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (/Users/xuzihao/blog/node_modules/bluebird/js/release/map.js:30:10)
    at Async._drainQueue (/Users/xuzihao/blog/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/Users/xuzihao/blog/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/xuzihao/blog/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

**Comment by NoahDragon** [comment]
Based on the line of code https://github.com/huiwang/hexo-baidu-url-submit/blob/master/lib/generator.js#L4

You have to set `baidu_url_submit.count` in the _config.yml file.
