### ISSUE TITLE
something  error

### ISSUE THREAD

**Issue by Erchoc** [hexojs/hexo#2565]
```
D:\OneDrive\erchoc.github.io>hexo s
INFO  Start processing
INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.
ERROR Theme config load failed.
ERROR Process failed: _config.yml
Error
    at generateError (D:\OneDrive\erchoc.github.io\node_modules\js-yaml\lib\js-yaml\loader.js:162:10)
    at throwError (D:\OneDrive\erchoc.github.io\node_modules\js-yaml\lib\js-yaml\loader.js:168:9)
    at readBlockMapping (D:\OneDrive\erchoc.github.io\node_modules\js-yaml\lib\js-yaml\loader.js:1036:11)
    at composeNode (D:\OneDrive\erchoc.github.io\node_modules\js-yaml\lib\js-yaml\loader.js:1331:12)
    at readBlockMapping (D:\OneDrive\erchoc.github.io\node_modules\js-yaml\lib\js-yaml\loader.js:1061:11)
    at composeNode (D:\OneDrive\erchoc.github.io\node_modules\js-yaml\lib\js-yaml\loader.js:1331:12)
    at readDocument (D:\OneDrive\erchoc.github.io\node_modules\js-yaml\lib\js-yaml\loader.js:1493:3)
    at loadDocuments (D:\OneDrive\erchoc.github.io\node_modules\js-yaml\lib\js-yaml\loader.js:1549:5)
    at Object.load (D:\OneDrive\erchoc.github.io\node_modules\js-yaml\lib\js-yaml\loader.js:1566:19)
    at Hexo.yamlHelper (D:\OneDrive\erchoc.github.io\node_modules\hexo\lib\plugins\renderer\yaml.js:7:15)
    at Hexo.tryCatcher (D:\OneDrive\erchoc.github.io\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (D:\OneDrive\erchoc.github.io\node_modules\bluebird\js\release\method.js:15:34)
    at D:\OneDrive\erchoc.github.io\node_modules\hexo\lib\hexo\render.js:61:21
    at tryCatcher (D:\OneDrive\erchoc.github.io\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\OneDrive\erchoc.github.io\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\OneDrive\erchoc.github.io\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\OneDrive\erchoc.github.io\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\OneDrive\erchoc.github.io\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (D:\OneDrive\erchoc.github.io\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (D:\OneDrive\erchoc.github.io\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (D:\OneDrive\erchoc.github.io\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:672:20)
ERROR Theme config load failed.
ERROR Process failed: _config.yml
Error
```

**Comment by loatheb** [comment]
@Erchoc please check these config one by one.

1. hexo config `_config.yml`
2. your theme config `_config.yml`
3. the config at your every posts header.

to see if there have a format error.Something went wrong when hexo parse the config.
