### ISSUE TITLE
Hexo 3.3.6 Generate Error

### ISSUE THREAD

**Issue by 502647092** [hexojs/hexo#2577]
## Environment Info

Node version(`node -v`):

```
$ node -v
v7.9.0
```

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 

```
$ npm ls --depth 0
hexo-site@0.0.0 E:\JTB\GitWorkSpace\hexo
+-- gulp@3.9.1
+-- gulp-clean@0.3.2
+-- gulp-load-plugins@1.5.0
+-- gulp-minify-css@1.2.4
+-- gulp-minify-html@1.0.6
+-- gulp-rename@1.2.2
+-- gulp-shell@0.6.3
+-- gulp-uglify@2.1.2
+-- hexo@3.3.6
+-- hexo-deployer-git@0.2.0
+-- hexo-generator-archive@0.1.4
+-- hexo-generator-category@0.1.3
+-- hexo-generator-feed@1.2.0
+-- hexo-generator-index@0.2.1
+-- hexo-generator-searchdb@1.0.7
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-ejs@0.2.0
+-- hexo-renderer-marked@0.2.11
+-- hexo-renderer-stylus@0.3.3
+-- hexo-server@0.2.0
`-- hexo-wordcount@2.0.1
```

## For BUG

Run Command `hexo g`
```
02:10:34.210 FATAL <pre> tag should not be nested
AssertionError: <pre> tag should not be nested
    at escapeContent (E:\JTB\GitWorkSpace\hexo\node_modules\hexo\lib\extend\tag.js:64:5)
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at E:\JTB\GitWorkSpace\hexo\node_modules\hexo\lib\extend\tag.js:71:15
    at Promise._execute (E:\JTB\GitWorkSpace\hexo\node_modules\bluebird\js\release\debuggability.js:300:13)
    at Promise._resolveFromExecutor (E:\JTB\GitWorkSpace\hexo\node_modules\bluebird\js\release\promise.js:483:18)
    at new Promise (E:\JTB\GitWorkSpace\hexo\node_modules\bluebird\js\release\promise.js:79:10)
    at Tag.render (E:\JTB\GitWorkSpace\hexo\node_modules\hexo\lib\extend\tag.js:70:10)
    at Object.tagFilter [as onRenderEnd] (E:\JTB\GitWorkSpace\hexo\node_modules\hexo\lib\hexo\post.js:253:16)
    at E:\JTB\GitWorkSpace\hexo\node_modules\hexo\lib\hexo\render.js:65:19
    at tryCatcher (E:\JTB\GitWorkSpace\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\JTB\GitWorkSpace\hexo\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (E:\JTB\GitWorkSpace\hexo\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (E:\JTB\GitWorkSpace\hexo\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (E:\JTB\GitWorkSpace\hexo\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (E:\JTB\GitWorkSpace\hexo\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (E:\JTB\GitWorkSpace\hexo\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (E:\JTB\GitWorkSpace\hexo\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by NoahDragon** [comment]
It's under investigation. Close as duplicated. https://github.com/hexojs/hexo/issues/2574
