### ISSUE TITLE
Error: fatal: CRLF would be replaced by LF in fonts/tooltip.4004ff.svg.

### ISSUE THREAD

**Issue by guhhhhaa** [hexojs/hexo#2595]
## Environment Info

Node version(`node -v`):
```
v8.0.0
```

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 
```
yilia
```

Hexo and Plugin version(`npm ls --depth 0`): 

    ├── dos2unix@1.1.2
    ├── hexo@3.3.7
    ├── hexo-deployer-git@0.3.0
    ├── hexo-generator-archive@0.1.4
    ├── hexo-generator-category@0.1.3
    ├── hexo-generator-index@0.2.1
    ├── hexo-generator-tag@0.2.0
    ├── hexo-renderer-ejs@0.2.0
    ├── hexo-renderer-marked@0.2.11
    ├── hexo-renderer-stylus@0.3.3
    └── hexo-server@0.2.0

## For BUG

1. BUG description

```
Error: fatal: CRLF would be replaced by LF in fonts/tooltip.4004ff.svg.

      at ChildProcess.<anonymous> (/…/blog/node_modules/hexo-util/lib/spawn.js:37:17)
      at emitTwo (events.js:125:13)
      at ChildProcess.emit (events.js:213:7)
      at maybeClose (internal/child_process.js:887:16)
      at Socket.stream.socket.on (internal/child_process.js:340:11)
      at emitOne (events.js:115:13)
      at Socket.emit (events.js:210:7)
      at Pipe._handle.close [as _onclose] (net.js:546:12)
```

2. The way to reproduce

```
cd …/blog
hexo d
```

3. Log with hexo <command> --debug

```
Error: The module '/usr/local/lib/node_modules/hexo-cli/node_modules/dtrace-
      provider/build/Release/DTraceProviderBindings.node'
      was compiled against a different Node.js version using
      NODE_MODULE_VERSION 48. This version of Node.js requires
      NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
      the module (for instance, using `npm rebuild` or `npm install`).
          at Object.Module._extensions..node (module.js:598:18)
          at Module.load (module.js:503:32)
          at tryModuleLoad (module.js:466:12)
          at Function.Module._load (module.js:458:3)
          at Module.require (module.js:513:17)
          at require (internal/module.js:11:18)
          at Object.<anonymous> (/usr/local/lib/node_modules/hexo-cli/node_modules/dtrace-provider/dtrace-provider.js:17:23)
          at Module._compile (module.js:569:30)
          at Object.Module._extensions..js (module.js:580:10)
          at Module.load (module.js:503:32)
          at tryModuleLoad (module.js:466:12)
          at Function.Module._load (module.js:458:3)
          at Module.require (module.js:513:17)
          at require (internal/module.js:11:18)
          at Object.<anonymous> (/usr/local/lib/node_modules/hexo-cli/node_modules/bunyan/lib/bunyan.js:79:18)
         at Module._compile (module.js:569:30)
      { Error: Cannot find module './build/default/DTraceProviderBindings'
          at Function.Module._resolveFilename (module.js:485:15)
          at Function.Module._load (module.js:437:25)
          at Module.require (module.js:513:17)
          at require (internal/module.js:11:18)
          at Object.<anonymous> (/usr/local/lib/node_modules/hexo-cli/node_modules/dtrace-provider/dtrace-provider.js:17:23)
          at Module._compile (module.js:569:30)
          at Object.Module._extensions..js (module.js:580:10)
          at Module.load (module.js:503:32)
          at tryModuleLoad (module.js:466:12)
          at Function.Module._load (module.js:458:3)
          at Module.require (module.js:513:17)
          at require (internal/module.js:11:18)
          at Object.<anonymous> (/usr/local/lib/node_modules/hexo-cli/node_modules/bunyan/lib/bunyan.js:79:18)
          at Module._compile (module.js:569:30)
          at Object.Module._extensions..js (module.js:580:10)
          at Module.load (module.js:503:32) code: 'MODULE_NOT_FOUND' }
      { Error: Cannot find module './build/Debug/DTraceProviderBindings'
          at Function.Module._resolveFilename (module.js:485:15)
          at Function.Module._load (module.js:437:25)
          at Module.require (module.js:513:17)
          at require (internal/module.js:11:18)
          at Object.<anonymous> (/usr/local/lib/node_modules/hexo-cli/node_modules/dtrace-provider/dtrace-provider.js:17:23)
          at Module._compile (module.js:569:30)
          at Object.Module._extensions..js (module.js:580:10)
          at Module.load (module.js:503:32)
          at tryModuleLoad (module.js:466:12)
          at Function.Module._load (module.js:458:3)
          at Module.require (module.js:513:17)
          at require (internal/module.js:11:18)
          at Object.<anonymous> (/usr/local/lib/node_modules/hexo-cli/node_modules/bunyan/lib/bunyan.js:79:18)
          at Module._compile (module.js:569:30)
          at Object.Module._extensions..js (module.js:580:10)
          at Module.load (module.js:503:32) code: 'MODULE_NOT_FOUND' }
      (node:12460) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.
      00:28:00.385 DEBUG Hexo version: 3.3.7
      00:28:00.387 DEBUG Working directory: ~/Desktop/myblog/blog/
      00:28:00.478 DEBUG Config loaded: ~/Desktop/myblog/blog/_config.yml
      00:28:00.495 DEBUG Plugin loaded: hexo-deployer-git
      00:28:00.496 DEBUG Plugin loaded: hexo-generator-category
      00:28:00.497 DEBUG Plugin loaded: hexo-generator-index
      00:28:00.499 DEBUG Plugin loaded: hexo-generator-archive
      00:28:00.499 DEBUG Plugin loaded: hexo-generator-tag
      00:28:00.501 DEBUG Plugin loaded: hexo-renderer-ejs
      00:28:00.505 DEBUG Plugin loaded: hexo-renderer-marked
      00:28:00.506 DEBUG Plugin loaded: hexo-renderer-stylus
      00:28:00.557 DEBUG Plugin loaded: hexo-server
```

**Comment by guhhhhaa** [comment]
https://github.com/litten/hexo-theme-yilia/issues/526
