### ISSUE TITLE
TypeError: Cannot read property 'code' of undefined

### ISSUE THREAD

**Issue by ZhongHuaJiaDZPP** [hexojs/hexo#2599]
## Environment Info

Node version(`node -v`): v8.0.0

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`):  

## For question

$ Desktop : hexo version
FATAL Cannot read property 'code' of undefined
TypeError: Cannot read property 'code' of undefined
    at /usr/local/lib/node_modules/hexo-cli/lib/find_pkg.js:23:25
    at tryCatcher (/usr/local/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/usr/local/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/local/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)

What's the reason for this?
What should I do？

**Comment by NoahDragon** [comment]
Which version of Hexo? you could run `npm ls --depth 0` to view it.

**Comment by tingkai-zhang** [comment]
> Which version of Hexo? you could run `npm ls --depth 0` to view it.

THANK YOU!!
