### ISSUE TITLE
Migrate from Wordpress

### ISSUE THREAD

**Issue by VinceG** [hexojs/hexo#2604]
## Environment Info

Node version(`node -v`): 7.10

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 

```
├── hexo@3.3.7
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.1
├── hexo-generator-tag@0.2.0
├── hexo-migrator-wordpress@0.1.2
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-marked@0.2.11
├── hexo-renderer-stylus@0.3.3
└── hexo-server@0.2.1
```

## For BUG

The error does not provide any meaningful and helpful information as to what exactly went wrong.

```
➜  hexo_blog hexo migrate wordpress ~/Downloads/blog.wordpress.2017-06-11.xml --debug
02:06:01.578 DEBUG Hexo version: 3.3.7
02:06:01.580 DEBUG Working directory: ~/Sites/hexo_blog/
02:06:01.646 DEBUG Config loaded: ~/Sites/hexo_blog/_config.yml
02:06:01.656 DEBUG Script loaded: themes/landscape/scripts/fancybox.js
02:06:01.658 DEBUG Plugin loaded: hexo-generator-archive
02:06:01.659 DEBUG Plugin loaded: hexo-generator-category
02:06:01.660 DEBUG Plugin loaded: hexo-generator-index
02:06:01.661 DEBUG Plugin loaded: hexo-generator-tag
02:06:01.784 DEBUG Plugin loaded: hexo-migrator-wordpress
02:06:01.786 DEBUG Plugin loaded: hexo-renderer-ejs
02:06:01.790 DEBUG Plugin loaded: hexo-renderer-marked
02:06:01.790 DEBUG Plugin loaded: hexo-renderer-stylus
02:06:01.823 DEBUG Plugin loaded: hexo-server
02:06:01.824 INFO  Analyzing /Users/vincentgabriel/Downloads/blog.wordpress.2017-06-11.xml...
02:06:02.322 INFO  Page found: About
02:06:02.342 INFO  Page found: Contact
02:06:02.347 INFO  Post found: עבודה עם פריימוורק או התחלה חדשה?
02:06:02.348 INFO  Post found: הצפנת סיסמאות - זה לא כל כך פשוט!
02:06:02.348 INFO  Post found: Twitter טוענים שהם זורקים את Rails ועוברים ל PHP
02:06:02.349 INFO  Post found: מה זה Ruby On Rails ?
02:06:02.350 INFO  Post found: התקנת Rails על Windows; שלב אחרי שלב
02:06:02.350 INFO  Page found: Terms Of Use
02:06:02.351 INFO  Page found: Archive
02:06:02.352 INFO  Page found: WPForms Preview
02:06:02.352 INFO  Post found: LEOWAİSİKER
02:06:02.352 INFO  Post found: מערכת ניהול תוכן? מה כל כך מיוחד בה!
02:06:02.353 INFO  Post found: Inspekt  כתיבת מערכות מאובטחות יותר. מה?
02:06:02.353 INFO  Post found: ניהול פרוייקטים, איך בידיוק מנהלים אותם?
02:06:02.353 INFO  Post found: תחסוך לעצמך זמן, CACHE IT!
02:06:02.354 INFO  Post found: הפרדת הקוד מהעיצוב, כמה קשה זה כבר יכול להיות?
02:06:02.355 INFO  Post found: כמה עובדות בנוגע לפירצות האבטחה של PHPList והפריצה אל phpbb.com
02:06:02.355 INFO  Post found: מהנדס, עכשיו עם תעודות!
02:06:02.359 INFO  Post found: מצוד אחר אחסון, שוב פעם...!
02:06:02.359 INFO  Post found: מערכת ניהול תוכן, ההמשך, ואתם בתור חלק בלתי נפרד ממנה.
02:06:02.360 INFO  Post found: מעבר לשרת החדש בוצע ועבר בהצלחה!
02:06:02.360 INFO  Post found: וורדפרס 2.7.1 גרסאת הפא'ץ הראשונה של סדרת 2.7
02:06:02.360 INFO  Post found: מה עושה מערכת ניהול תוכן למערכת טובה? מה אתם הייתם רוצים שיהיה בה?!
02:06:02.361 INFO  Post found: שרשור פונקציות במחלקה
02:06:02.362 INFO  Post found: PHP Design Patterns - השימוש ב Singleton
02:06:02.362 INFO  Post found: שערי מט"ח אונליין במהירות ויעילות (עודכן)
02:06:02.362 INFO  Post found: מנוע טמפלייטים המהיר ביותר...ב C ??
02:06:02.363 INFO  Post found: כלי לבדיקת תקינות העמודים שלכם לתקן W3
02:06:02.363 INFO  Post found: בדיקת זמן טעינה ב PHP
02:06:02.364 INFO  Post found: Zend Framework - למה באמת כדי להשתמש בה?
02:06:02.366 INFO  Post found: מסד נתונים - הגדרת סוגי שדות נכונים בהתאם לתוכן השדה
02:06:02.367 INFO  Post found: יצירת קבצי PDF דינאמית בעזרת PHP ו HARU
02:06:02.367 INFO  Post found: הכנה לבחינה של ZEND - דברים שרצוי לעשות
02:06:02.368 INFO  Post found: Zend Server - סביבת פיתוח ועבודה עם PHP בכמה דקות
02:06:02.369 INFO  Post found: Wamp5 Vs. Zend Server 4.0
02:06:02.369 INFO  Post found: מערכת מכירת עיצובים ולוגואים...המקום האידיאלי למעצבים
02:06:02.369 INFO  Post found: זכויות יוצרים עבור עבודות שנעשות ומתפרסמות באינטרנט
02:06:02.370 INFO  Post found: חיוב באמצעות Paypal, פשוט.
02:06:02.370 INFO  Post found: חיוב כרטיס אשראי באמצעות טרנזילה
02:06:02.370 INFO  Post found: Zend Framework גרסא 1.7.8 שוחררה
02:06:02.371 INFO  Post found: SQL Injection Cheat Sheet
02:06:02.371 INFO  Post found: Zend Certified? עכשיו גם Zend Framework Certified Engineer
02:06:02.371 INFO  Post found: Zend Framework 1.8 גרסאת הדגמה
02:06:02.372 INFO  Post found: מערך ל XML וההפך, בעזרת Zend Framework אבל לא רק.
02:06:02.372 INFO  Post found: Zend_Payment - Using Tranzila as the Gateway
02:06:02.372 INFO  Post found: Zend_Payment - Using MoneyBookers as the Gateway
02:06:02.373 INFO  Post found: Zend_Payment - Using Paypal as the Gateway
02:06:02.373 INFO  Post found: ZendFramework 1.8 Manual CHM file
02:06:02.374 INFO  Post found: IPB 3.0.0 RC1 - יישור הסקין
02:06:02.375 INFO  Post found: שימוש ב MICROPAY לשליחת SMS
02:06:02.376 INFO  Post found: Application Installer Wizard Class
02:06:02.376 INFO  Post found: אשף התקנת מערכות ב PHP
02:06:02.377 INFO  Post found: Yii - Creating a blog in just 30 minutes - ScreenCast
02:06:02.377 INFO  Post found: יצירת בלוג בעזרת Yii תוך 30 דקות בלבד - מדריך וידאו
02:06:02.380 INFO  Post found: Yii - PHP Coding Standards (draft)
02:06:02.384 INFO  Post found: (IM) Custom Forum Blocks For IPB 3
02:06:02.385 INFO  Post found: Speed up a web site by enabling Apache file compression
02:06:02.386 INFO  Post found: Difference Between InnoDB and MyISAM
02:06:02.386 INFO  Post found: MySQL Data Types Quick Reference Table: MySQL Version 5.0
02:06:02.387 INFO  Post found: PHP Developer job position
02:06:02.387 INFO  Post found: (IM) Custom Navigation 1.0
02:06:02.388 INFO  Post found: Mod_Rewrite Tips and Tricks are lot of .htaccess rewrite examples
02:06:02.389 INFO  Post found: Custom Test Center
02:06:02.390 INFO  Post found: מבחני דוגמא בנושאים שונים
02:06:02.390 INFO  Post found: Forums now available
02:06:02.390 INFO  Post found: פורומים פעילים באתר
02:06:02.391 INFO  Post found: New Mysql 5 Test / Exam
02:06:02.392 INFO  Post found: בחינה חדשה בנושא מסדי נתונים MySQL 5
02:06:02.392 INFO  Post found: PHP Job Position - Center Tel-Aviv, Israel
02:06:02.393 INFO  Post found: IPB SDK V3 FOR IPB 3
02:06:02.393 INFO  Post found: Get server load time
02:06:02.393 INFO  Post found: קבלת עומס השרת כרגע - SERVER LOAD
02:06:02.393 INFO  Post found: Apache rewrite rules - Http to Https - Force SSL
02:06:02.394 INFO  Post found: צפייה באתר תחת SSL - להכריח את המשתמש - Apache Mod Rewrite
02:06:02.396 INFO  Post found: Exceptional PHP: Introduction to Exceptions
02:06:02.397 INFO  Post found: Difference Between isset empty is null
02:06:02.397 INFO  Post found: התקנה ושימוש ב XDEBUG
02:06:02.397 INFO  Post found: Yii - Version 1.0.11 Released
02:06:02.398 INFO  Post found: גרסא חדשה לפריימוורק Yii - 1.0.11
02:06:02.399 INFO  Post found: Creating a Yii widget for FCKeditor easier usage
02:06:02.399 INFO  Post found: HipHop for PHP: Move Fast
02:06:02.400 INFO  Post found: HipHop PHP - לזוז מהר?
02:06:02.400 INFO  Post found: כפתור החזור בדפדפן FF בלינוקס
02:06:02.400 INFO  Post found: תרגום של YII לעברית
02:06:02.401 INFO  Post found: אתר תמיכה ל YII בעברית - בקרוב!
02:06:02.401 INFO  Post found: Yii גרסא 1.1.1 שוחררה!
02:06:02.401 INFO  Post found: Yiiframework.co.il - הרשמו לקבלת עדכונים ברגע שהאתר פתוח לקהל הרחב
02:06:02.401 INFO  Post found: PHPClasses.org השיקו את העיצוב החדש, בין המעצבים ישראלית בשם יפעת עמית.
02:06:02.402 INFO  Post found: New Yii Extension - Gravatar Support
02:06:02.414 INFO  Post found: תוסף ל Yii - שימוש ב Gravatar
02:06:02.414 INFO  Post found: Yii Framework Twitter API Extension
02:06:02.414 INFO  Post found: תוסף חדש עבור Yii - קבלת נתונים מחשבונות טויטר
02:06:02.414 INFO  Post found: CSS Janus: converts website's layout from left-to-right to right-to-left
02:06:02.415 INFO  Post found: CSS Janus - כלי ההופך ישור מימין לשמאל וההפך
02:06:02.415 INFO  Post found: תוסף חדש עבור Yii קיצור כתובת בעזרת bit.ly
02:06:02.415 INFO  Post found: Bit.ly URL Shortener Yii Extension
02:06:02.416 INFO  Post found: Fusion Charts Yii Extension
02:06:02.416 INFO  Post found: יצירה וניהול של גרפים - תוסף עבור Yii
02:06:02.416 INFO  Post found: Java Uploader Yii Extension
02:06:02.417 INFO  Post found: העלאת קבצים בעזרת Java , סטייל facebook תוסף עבור Yii
02:06:02.417 INFO  Post found: Yii: Add missing translations to the DB automatically
02:06:02.417 INFO  Post found: Yii: הוספת תרגומים חסרים לטבלאות התרגומים אוטומטית
02:06:02.418 INFO  Post found: Yii: Google Closure Complier
02:06:02.418 INFO  Post found: Yii: כווץ קבצים וקוד JS בעזרת Google Closure Complier
02:06:02.419 INFO  Post found: Facebook PHP Class Library - Graph, Social Plugins, Search, Posting And more
02:06:02.419 INFO  Post found: InlineReport - Report content inline
02:06:02.420 INFO  Post found: דווח שגיאות וטעויות בטקסט באופן דינאמי ומהיר
02:06:02.420 INFO  Post found: אתר התמיכה עבור Yiiframework עלה
02:06:02.420 INFO  Post found: Yii 1.1.3 שוחררה
02:06:02.421 INFO  Post found: הספר הראשון עבור Yii
02:06:02.421 INFO  Post found: SVN יצירה, שימוש ובעיות נפוצות
02:06:02.421 INFO  Post found: Yii 1.1.4 שוחררה
02:06:02.422 INFO  Post found: ספרים מומלצים ללימוד PHP - למתחילים ואלו שרוצים להשתפר
02:06:02.422 INFO  Post found: MongoDB - חלק 1 - התקנה
02:06:02.423 INFO  Post found: MongoDB - חלק 2 - התקנת התוסף עבור PHP
02:06:02.424 INFO  Post found: MongoDB - חלק 3 - התחברות למסד נתונים הרצת שאילתות על גבי מסד הנתונים
02:06:02.424 INFO  Post found: בלוגים טכנולוגיים
02:06:02.425 INFO  Post found: PHP 5.3 - Closures & Lambda/Anonymous Functions
02:06:02.425 INFO  Post found: PHP 5.3 Namespaces
02:06:02.426 INFO  Post found: PHP 5.3 Late Static Bindings
02:06:02.426 INFO  Post found: PHP 5.3 - תוספות תחביר
02:06:02.427 INFO  Post found: PHP 5.3 Zend Certified
02:06:02.427 INFO  Post found: PHP Bug Tracker Project
02:06:02.429 INFO  Post found: PHP Project Manager Feature List
02:06:02.430 INFO  Post found: Yii E-Commerce Platform – Language Manager
02:06:02.432 INFO  Post found: PHP US States Array Grouped By Region
02:06:02.432 INFO  Post found: Rain TPL Yii View Renderer
02:06:02.433 INFO  Post found: Yii Widget for the Aloha Editor
02:06:02.434 INFO  Post found: Twitter Bootstrap Wizard Plugin
02:06:02.434 INFO  Post found: Cars Makes & Models list - PHP Array, JSON String, DB Tables
02:06:02.436 INFO  Post found: Pure Inspection - Home Inspection Cloud Management Tool
02:06:02.436 INFO  Post found: US Adjacent States List
02:06:02.440 INFO  Post found: US Zip Codes List - Updated 42,000 Zip Codes
02:06:02.441 INFO  Post found: Yii eCommerce Changes
02:06:02.441 INFO  Post found: Yii eCommerce - A Look Inside
02:06:02.442 INFO  Post found: Bootstrap Admin Theme
02:06:02.442 INFO  Post found: Free Bootstrap Admin Theme - Updated
02:06:02.442 INFO  Post found: Backbone Tracker - Issue Tracker
02:06:02.443 INFO  Post found: PHP Console Progress Bar
02:06:02.443 INFO  Post found: Bootstrap Admin Theme - Available Free @ Github
02:06:02.443 INFO  Post found: Twitter Bootstrap Wizard - Enabling, Disabling, Showing, Hiding, Removing Steps
02:06:02.444 INFO  Post found: Bootstrap Wizard With jQuery Validation
02:06:02.444 INFO  Post found: Backbone.js Issue Tracker - Backbone Tracker
02:06:02.444 INFO  Post found: First Data Global Gateway PHP API Service
02:06:02.445 INFO  Post found: Bootstrap Admin Theme - New Pages & Plugins
02:06:02.445 INFO  Post found: PHP 5.5 Certification Exam
02:06:02.445 INFO  Post found: Bootstrap Admin Theme 3.x – Available Free @ Github
02:06:02.446 INFO  Post found: Enterprise Applications - Making Them Social
02:06:02.446 INFO  Post found: Yii eCommerce Public On Github
02:06:02.447 INFO  Post found: PHP 5.5 Zend Certified Engineer
02:06:02.447 INFO  Post found: Support Ticket Management
02:06:02.447 INFO  Post found: Bootstrap 2.x eCommerce Theme
02:06:02.448 INFO  Post found: Zillow API PHP
02:06:02.448 INFO  Post found: Realtor.com PHP library to Search and View
02:06:02.725 FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error
    at generateError (/Users/vincentgabriel/Sites/hexo_blog/node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
    at throwError (/Users/vincentgabriel/Sites/hexo_blog/node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
    at readBlockMapping (/Users/vincentgabriel/Sites/hexo_blog/node_modules/js-yaml/lib/js-yaml/loader.js:1045:9)
    at composeNode (/Users/vincentgabriel/Sites/hexo_blog/node_modules/js-yaml/lib/js-yaml/loader.js:1331:12)
    at readDocument (/Users/vincentgabriel/Sites/hexo_blog/node_modules/js-yaml/lib/js-yaml/loader.js:1493:3)
    at loadDocuments (/Users/vincentgabriel/Sites/hexo_blog/node_modules/js-yaml/lib/js-yaml/loader.js:1549:5)
    at Object.load (/Users/vincentgabriel/Sites/hexo_blog/node_modules/js-yaml/lib/js-yaml/loader.js:1566:19)
    at /Users/vincentgabriel/Sites/hexo_blog/node_modules/hexo/lib/hexo/post.js:122:18
    at tryCatcher (/Users/vincentgabriel/Sites/hexo_blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/vincentgabriel/Sites/hexo_blog/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/vincentgabriel/Sites/hexo_blog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/vincentgabriel/Sites/hexo_blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/vincentgabriel/Sites/hexo_blog/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/vincentgabriel/Sites/hexo_blog/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/vincentgabriel/Sites/hexo_blog/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/vincentgabriel/Sites/hexo_blog/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
02:06:02.744 DEBUG Database saved
```

**Comment by VinceG** [comment]
I went ahead and wrote something with PHP that worked well.

https://github.com/VinceG/vincent-blog/blob/master/wordpress_importer.php
