### ISSUE TITLE
hexo g failed with migrate wordpress

### ISSUE THREAD

**Issue by changchichung** [hexojs/hexo#2657]
## Environment Info

Node version(`node -v`):v8.0.0

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 
hexo-site@0.0.0 /usr/share/nginx/html/hexoblog
├── ejs@1.0.0
├── hexo@3.3.7
├── hexo-deployer-git@0.3.0
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-feed@1.2.0
├── hexo-generator-index@0.2.1
├── hexo-generator-sitemap@1.2.0
├── hexo-generator-tag@0.2.0
├── hexo-git-backup@0.1.2
├── hexo-migrator-wordpress@0.1.2
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-less@0.2.0
├── hexo-renderer-marked@0.2.11
├── hexo-renderer-stylus@0.3.3
├── hexo-server@0.2.1
├── moment@2.18.1
└── utils-merge@1.0.0

## For question

I try to migrate my wordpress to hexo . because there are too many posts to migrate , I decide to import by categories ( about 10) using wordpress export xml file.
this is not the first time I try to migrate from wp to hexo , so I know the "{{" chars will cause migrate failed.
so I replace all "{{" and "}}" to "{ {" "} }" in all xml files.
then I using hexo migrate wordpress xml_filename to import categogy one by one.
and there`s one cat can not been import with  error like this

> Template render error: (unknown path)
> Error: unexpected end of comment

exactly the same error when the "{{" chars not been replace . But I check again and again , there`s no "{{" "}}" "{%" "{#" chars in the error xml file.

is there any chars will cuase this problem ? or any other suggestions ?

here is the eror xml file "without" replacing {{ .
[wp-other.zip](https://github.com/hexojs/hexo/files/1157803/wp-other.zip)

and here is the debug log
{"name":"hexo","hostname":"3cx1","pid":9832,"level":60,"err":{"message":"(unknown path)¥n  Error: unexpected end of comment","name":"Template render error","stack":"Template render error: (unknown path)¥n  Error: unexpected end of comment¥n    at Object.exports.prettifyError (/usr/share/nginx/html/hexoblog/node_modules/nunjucks/src/lib.js:34:15)¥n    at new_cls.render (/usr/share/nginx/html/hexoblog/node_modules/nunjucks/src/environment.js:469:27)¥n    at new_cls.renderString (/usr/share/nginx/html/hexoblog/node_modules/nunjucks/src/environment.js:327:21)¥n    at /usr/share/nginx/html/hexoblog/node_modules/hexo/lib/extend/tag.js:66:9¥n    at Promise._execute (/usr/share/nginx/html/hexoblog/node_modules/bluebird/js/release/debuggability.js:300:9)¥n    at Promise._resolveFromExecutor (/usr/share/nginx/html/hexoblog/node_modules/bluebird/js/release/promise.js:483:18)¥n    at new Promise (/usr/share/nginx/html/hexoblog/node_modules/bluebird/js/release/promise.js:79:10)¥n    at Tag.render (/usr/share/nginx/html/hexoblog/node_modules/hexo/lib/extend/tag.js:64:10)¥n    at Object.tagFilter [as onRenderEnd] (/usr/share/nginx/html/hexoblog/node_modules/hexo/lib/hexo/post.js:253:16)¥n    at /usr/share/nginx/html/hexoblog/node_modules/hexo/lib/hexo/render.js:65:19¥n    at tryCatcher (/usr/share/nginx/html/hexoblog/node_modules/bluebird/js/release/util.js:16:23)¥n    at Promise._settlePromiseFromHandler (/usr/share/nginx/html/hexoblog/node_modules/bluebird/js/release/promise.js:512:31)¥n    at Promise._settlePromise (/usr/share/nginx/html/hexoblog/node_modules/bluebird/js/release/promise.js:569:18)¥n    at Promise._settlePromise0 (/usr/share/nginx/html/hexoblog/node_modules/bluebird/js/release/promise.js:614:10)¥n    at Promise._settlePromises (/usr/share/nginx/html/hexoblog/node_modules/bluebird/js/release/promise.js:693:18)¥n    at Async._drainQueue (/usr/share/nginx/html/hexoblog/node_modules/bluebird/js/release/async.js:133:16)¥n    at Async._drainQueues (/usr/share/nginx/html/hexoblog/node_modules/bluebird/js/release/async.js:143:10)¥n    at Immediate.Async.drainQueues [as _onImmediate] (/usr/share/nginx/html/hexoblog/node_modules/bluebird/js/release/async.js:17:14)¥n    at runCallback (timers.js:800:20)¥n    at tryOnImmediate (timers.js:762:5)¥n    at processImmediate [as _immediateCallback] (timers.js:733:5)"},"msg":"Something's wrong. Maybe you can find the solution here: ¥u001b[4mhttp://hexo.io/docs/troubleshooting.html¥u001b[24m","time":"2017-07-19T01:40:54.169Z","v":0}
{"name":"hexo","hostname":"3cx1","pid":9832,"level":20,"msg":"Database saved","time":"2017-07-19T01:40:54.238Z","v":0}

**Comment by changchichung** [comment]
well , it turns out the symbol " #}" will cause the issue , I replace all "#}" with "# }" and it works.
