### ISSUE TITLE
[bug]show "fatal: multiple stage entries for merged file 'archives'" when `hexo d`

### ISSUE THREAD

**Issue by bighuang624** [hexojs/hexo#2665]
## Environment Info

`hexo -v`显示：

```
hexo: 3.3.8
hexo-cli: 1.0.2
os: Darwin 14.5.0 darwin x64
http_parser: 2.7.0
node: 7.9.0
v8: 5.5.372.43
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 51
openssl: 1.0.2k
icu: 58.2
unicode: 9.0
cldr: 30.0.3
tz: 2016j
```

Hexo and Plugin version(`npm ls --depth 0`): 

![屏幕快照 2017-07-26 14.30.16.png](http://upload-images.jianshu.io/upload_images/2702529-0e0dfca308968bae.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

## For BUG

报错截图：

![屏幕快照 2017-07-26 14.25.31.png](http://upload-images.jianshu.io/upload_images/2702529-bf00e43d45ab29e7.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

Log with hexo <command> --debug：

```
06:33:04.836 DEBUG Hexo version: 3.3.8
06:33:04.842 DEBUG Working directory: ~/hexo-blog/
06:33:05.422 DEBUG Config loaded: ~/hexo-blog/_config.yml
06:33:05.491 DEBUG Script loaded: themes/next/scripts/merge.js
06:33:05.495 DEBUG Script loaded: themes/next/scripts/merge-configs.js
06:33:05.496 DEBUG Script loaded: themes/next/scripts/tags/exturl.js
06:33:05.497 DEBUG Script loaded: themes/next/scripts/tags/center-quote.js
06:33:05.497 DEBUG Script loaded: themes/next/scripts/tags/button.js
06:33:05.498 DEBUG Script loaded: themes/next/scripts/tags/full-image.js
06:33:05.521 DEBUG Plugin loaded: hexo-deployer-git
06:33:05.523 DEBUG Script loaded: themes/next/scripts/tags/group-pictures.js
06:33:05.523 DEBUG Script loaded: themes/next/scripts/tags/note.js
06:33:05.548 DEBUG Plugin loaded: hexo-generator-archive
06:33:05.580 DEBUG Plugin loaded: hexo-generator-baidu-sitemap
06:33:05.591 DEBUG Plugin loaded: hexo-generator-category
06:33:05.606 DEBUG Plugin loaded: hexo-generator-index
06:33:05.679 DEBUG Plugin loaded: hexo-generator-searchdb
06:33:05.687 DEBUG Plugin loaded: hexo-generator-sitemap
06:33:05.691 DEBUG Plugin loaded: hexo-generator-tag
06:33:05.695 DEBUG Plugin loaded: hexo-renderer-ejs
06:33:05.709 DEBUG Plugin loaded: hexo-generator-feed
06:33:05.725 DEBUG Plugin loaded: hexo-renderer-marked
06:33:05.728 DEBUG Plugin loaded: hexo-renderer-stylus
06:33:06.122 DEBUG Plugin loaded: hexo-server
06:33:06.126 INFO  Deploying: git
06:33:06.138 INFO  Clearing .deploy_git folder...
06:33:06.224 INFO  Copying files from public folder...
fatal: multiple stage entries for merged file 'archives'
06:33:06.496 FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: fatal: multiple stage entries for merged file 'archives'

    at ChildProcess.<anonymous> (/Users/huang/hexo-blog/node_modules/hexo-util/lib/spawn.js:37:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
06:33:06.498 DEBUG Database saved
06:33:06.498 FATAL fatal: multiple stage entries for merged file 'archives'

Error: fatal: multiple stage entries for merged file 'archives'

    at ChildProcess.<anonymous> (/Users/huang/hexo-blog/node_modules/hexo-util/lib/spawn.js:37:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
```

**Comment by NoahDragon** [comment]
Have you tried the solution provided in the StackOverflow? https://stackoverflow.com/questions/27330446/getting-a-fatal-error-in-git-for-multiple-stage-entries

**Comment by bighuang624** [comment]
OK 了。之前其实试过这个方法，但是 hexo 的目录下没直接找到 .git 文件夹。这次先 ls -l -a 看了一下，然后进 .deploy_git 中找到了 .git/index。Thanks！

**Comment by NoahDragon** [comment]
好的，如果还有问题欢迎重开此Issue.
