### ISSUE TITLE
TypeError: Cannot set property 'lastIndex' of undefined

### ISSUE THREAD

**Issue by AlexiaChen** [hexojs/hexo#2672]
## Environment Info

Node version(`node -v`): 6.9.5

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 

```
+-- hexo@3.3.8
+-- hexo-generator-archive@0.1.4
+-- hexo-generator-category@0.1.3
+-- hexo-generator-index@0.2.1
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-ejs@0.2.0
+-- hexo-renderer-marked@0.2.11
+-- hexo-renderer-stylus@0.3.3
`-- hexo-server@0.2.1

```

## For BUG

run hexo command with generate output:

```
TypeError: Cannot set property 'lastIndex' of undefined
    at highlight (C:\Users\MathxH\Desktop\buildblog\src\node_modules\highlight.js\lib\highlight.js:511:35)
    at C:\Users\MathxH\Desktop\buildblog\src\node_modules\highlight.js\lib\highlight.js:561:21
    at Array.forEach (native)
    at Object.highlightAuto (C:\Users\MathxH\Desktop\buildblog\src\node_modules\highlight.js\lib\highlight.js:560:40)
    at highlight (C:\Users\MathxH\Desktop\buildblog\src\node_modules\hexo-util\lib\highlight.js:100:19)
    at highlightUtil (C:\Users\MathxH\Desktop\buildblog\src\node_modules\hexo-util\lib\highlight.js:22:14)
    at C:\Users\MathxH\Desktop\buildblog\src\node_modules\hexo\lib\plugins\filter\before_post_render\backtick_code_block.js:49:15
    at RegExp.[Symbol.replace] (native)
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at Hexo.backtickCodeBlock (C:\Users\MathxH\Desktop\buildblog\src\node_modules\hexo\lib\plugins\filter\before_post_render\backtick_code_block.js:15:31)
    at Hexo.tryCatcher (C:\Users\MathxH\Desktop\buildblog\src\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (C:\Users\MathxH\Desktop\buildblog\src\node_modules\bluebird\js\release\method.js:15:34)
    at C:\Users\MathxH\Desktop\buildblog\src\node_modules\hexo\lib\extend\filter.js:68:35
    at tryCatcher (C:\Users\MathxH\Desktop\buildblog\src\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (C:\Users\MathxH\Desktop\buildblog\src\node_modules\bluebird\js\release\reduce.js:155:18)
    at Object.gotAccum (C:\Users\MathxH\Desktop\buildblog\src\node_modules\bluebird\js\release\reduce.js:144:25)
    at Object.tryCatcher (C:\Users\MathxH\Desktop\buildblog\src\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\MathxH\Desktop\buildblog\src\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\MathxH\Desktop\buildblog\src\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromiseCtx (C:\Users\MathxH\Desktop\buildblog\src\node_modules\bluebird\js\release\promise.js:606:10)
    at Async._drainQueue (C:\Users\MathxH\Desktop\buildblog\src\node_modules\bluebird\js\release\async.js:138:12)

```

I tried to uninstall hexo and re-install hexo ,but it ouput errors like above.

**Comment by NoahDragon** [comment]
Have you deleted the node_module folder?

**Comment by AlexiaChen** [comment]
@NoahDragon    nope.   node_module foler does exist

**Comment by AlexiaChen** [comment]
@NoahDragon   I have re-install hexo, but the error always like above.

**Comment by tea3** [comment]
@AlexiaChen 
There may be a problem with the posting data.  Does the same error occur if I move all markdown files in `source/_posts` to `source/_draft` ?

**Comment by AlexiaChen** [comment]
I found the error is  _config.yaml in blog root, maybe my _config.yaml is outdate, cause I use hexo re-initialize blog and use new _config.yaml instead of old one , it works fine .

**Comment by marcofranssen** [comment]
The solution provided here just gives me another error. See my ticket #3486 with some more details and ideas to finally find a real solution to this issue.
