### ISSUE TITLE
hexo genereate faile  Template render error: (unknown path)

### ISSUE THREAD

**Issue by ZJsnowman** [hexojs/hexo#2679]
## Environment Info

Node version(`node -v`):v7.2.1

## For BUG
08:29:52.632 FATAL (unknown path)
  SyntaxError: Invalid or unexpected token
Template render error: (unknown path)
  SyntaxError: Invalid or unexpected token
    at Object.exports.prettifyError (/Users/zhangjun/Write/wholeBlog/node_modules/nunjucks/src/lib.js:34:15)
    at new_cls.render (/Users/zhangjun/Write/wholeBlog/node_modules/nunjucks/src/environment.js:469:27)
    at new_cls.renderString (/Users/zhangjun/Write/wholeBlog/node_modules/nunjucks/src/environment.js:327:21)
    at /Users/zhangjun/Write/wholeBlog/node_modules/hexo/lib/extend/tag.js:66:9
    at Promise._execute (/Users/zhangjun/Write/wholeBlog/node_modules/bluebird/js/release/debuggability.js:299:9)
    at Promise._resolveFromExecutor (/Users/zhangjun/Write/wholeBlog/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/Users/zhangjun/Write/wholeBlog/node_modules/bluebird/js/release/promise.js:77:14)
    at Tag.render (/Users/zhangjun/Write/wholeBlog/node_modules/hexo/lib/extend/tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (/Users/zhangjun/Write/wholeBlog/node_modules/hexo/lib/hexo/post.js:253:16)
    at /Users/zhangjun/Write/wholeBlog/node_modules/hexo/lib/hexo/render.js:65:19
    at tryCatcher (/Users/zhangjun/Write/wholeBlog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/zhangjun/Write/wholeBlog/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/zhangjun/Write/wholeBlog/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/zhangjun/Write/wholeBlog/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/zhangjun/Write/wholeBlog/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/Users/zhangjun/Write/wholeBlog/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/zhangjun/Write/wholeBlog/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/Users/zhangjun/Write/wholeBlog/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)

## For question
i know which file is wrong ,but i don'n know how to fix it .remove the file will be ok.

## The markdown file that i think is wrong.Remove the file will be ok.
```markdown
---
title: 正则表达式学习笔记
date: 2017-6-12 18:38:49
tags: [others]
---

正则表达式一些注意点。 <!-- more -->

# 正则表达式是什么
在编写处理字符串的程序或网页时，经常会有查找符合某些复杂规则的字符串的需要。正则表达式就是用于描
述这些规则的工具。换句话说，正则表达式就是记录文本规则的代码。
很可能你使用过Windows/Dos下用于文件查找的通配符(wildcard)，也就是\*和?。如果你想查找某个目录
下的所有的Word文档的话，你会搜索\*.doc。在这里，"\*"会被解释成任意的字符串。和通配符类似，正则
表达式也是用来进行文本匹配的工具，只不过比起通配符，它能更精确地描述你的需求——当然，代价就是
更复杂——比如你可以编写一个正则表达式，用来查找所有以0开头，后面跟着2-3个数字，然后是一个连
字号“-”，最后是7或8位数字的字符串(像010-12345678或0376-7654321)。

# 用途
正则的用途是查找, 替换, 分割字符串 

# 基本用法
根据不同的语言自行搞定
参考：[正则表达式ppt](https://drive.google.com/open?id=0B8SC8SttiuHPLUVZLVBPak5wNUE)

# 注意点
- 如果查找运算符本身，需要转义。例如字符串包含. 就在前面加一个斜杠 --> \\.
- 一些修饰符，如果不明确用括号()分开，则只修饰离他最近的。例如：
'``shell
http|https|ftp:\/\/[\w.]+
'``
**这个+只修饰[\w.]**

- 括号()可以界定范围的作用。
例如：
如果你的表达式是由一部分一部分组成的, 就可能会用到分组, 举个例子, 你希望匹配  
'``shell
ftp://www.google.com 
http://www.google.com 
https://www.google.com  
'``
你希望限定协议部分只有ftp, http, https  你可能需要这样写  
'``shell
(http|https|ftp):\/\/[\w.]+  
'``
如果上面没有分组变成了
'``shell
http|https|ftp:\/\/[\w.]+
'``
"|" 实际上是作用于"http", "https","ftp:\/\/[\w.]+"这三种选择.
这里是否添加括号，"|"符号作用的范围就是不一样的。

```

**Comment by NoahDragon** [comment]
Could you please try to remove the following three code snippets?

```shell
http|https|ftp:\/\/[\w.]+
```

```shell
(http|https|ftp):\/\/[\w.]+
```

```shell
http|https|ftp:\/\/[\w.]+
```

I assume these cause the nunjucks syntax error. 
Or wrap the entire content with {% raw %} {% endraw %} tags.

**Comment by ZJsnowman** [comment]
thank you for your anwner.i do as you say,but not work.At last,i rewrite the article and it work.what a 
strange error.forget it!

**Comment by NoahDragon** [comment]
glad it fixed. :smile

**Comment by YTLogos** [comment]
just renove the {},then it will be OK
