### ISSUE TITLE
hexo deploy error! >.<

### ISSUE THREAD

**Issue by Summyj** [hexojs/hexo#2687]
## question：

关联Hexo和github时，网站部署报错，_config.yml配置文件已经修改了deploy的内容。以下是报错信息：

F:\Bolg\blog>hexo d
INFO  Deploying: git
INFO  Setting up Git deployment...
Initialized empty Git repository in F:/Bolg/blog/.deploy_git/.git/

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got '˭��Ǯ����@Summy-j.(none)')
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error:
*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got '˭��Ǯ����@Summy-j.(none)')

    at ChildProcess.<anonymous> (F:\Bolg\blog\node_modules\hexo-util\lib\spawn.js:37:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at ChildProcess.cp.emit (F:\Bolg\blog\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:891:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12) 

please hlep me fix it, thanks!

**Comment by Summyj** [comment]
this problem has solved, ,,

**Comment by fastzhong** [comment]
原来好好的，今天也跳出这个问题，你是怎么解决的？

**Comment by fastzhong** [comment]
$ hexo d
INFO  Deploying: git
INFO  Clearing .deploy_git folder...
INFO  Copying files from public folder...
INFO  Copying files from extend dirs...
On branch master
nothing to commit, working tree clean
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error
    at ChildProcess.<anonymous> (D:\GoogleDrive\workspace\fastzhong.com\node_modules\hexo-util\lib\spawn.js:37:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at ChildProcess.cp.emit (D:\GoogleDrive\workspace\fastzhong.com\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:891:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)

**Comment by fastzhong** [comment]
deploy:
  type: git
  repository:
    github: git@github-fastzhong:fastzhong/fastzhong.github.io.git
    coding: git@coding-fastzhong:fastzhong/fastzhong.git
    branch: master

**Comment by fastzhong** [comment]
把.deploy_git删掉重来，则出现：
 create mode 100755 tags/vs-code/index.html
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error
    at ChildProcess.<anonymous> (D:\GoogleDrive\workspace\fastzhong.com\node_modules\hexo-util\lib\spawn.js:37:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at ChildProcess.cp.emit (D:\GoogleDrive\workspace\fastzhong.com\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:891:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)

**Comment by darkwebgl** [comment]
同样在把hexo部署到GitHub上时，报同样的错，请问当初您是如何解决的？

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'username@localhost.(none)')
error: src refspec HEAD does not match any.
error: failed to push some refs to 'https://github.com/username/username.github.io.git'
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: error: src refspec HEAD does not match any.
error: failed to push some refs to 'https://github.com/username/username.github.io.git'

    at ChildProcess.<anonymous> (/Users/username/Desktop/myblog/blog1/node_modules/hexo-util/lib/spawn.js:37:17)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
