### ISSUE TITLE
ERROR Plugin load failed: hexo-server

### ISSUE THREAD

**Issue by fractal128** [hexojs/hexo#2689]
```
ERROR Plugin load failed: hexo-server
Error: Cannot find module './db.json'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/qijiachen/fractal128.github.io/node_modules/hexo-server/node_modules/compression/node_modules/accepts/node_modules/mime-types/node_modules/mime-db/index.js:11:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
...
```
always shows like that when run any hexo act, please help

package.json:
```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.1.1"
  },
  "dependencies": {
    "hexo": "^3.1.0",
    "hexo-browsersync": "^0.2.0",
    "hexo-deployer-git": "0.0.4",
    "hexo-generator-archive": "^0.1.2",
    "hexo-generator-category": "^0.1.2",
    "hexo-generator-feed": "^1.0.3",
    "hexo-generator-index": "^0.1.2",
    "hexo-generator-sitemap": "^1.0.1",
    "hexo-generator-tag": "^0.1.1",
    "hexo-html-minifier": "0.0.1",
    "hexo-pdf": "^1.1.0",
    "hexo-renderer-ejs": "^0.1.0",
    "hexo-renderer-jade": "^0.1.0",
    "hexo-renderer-marked": "^0.2.5",
    "hexo-renderer-stylus": "^0.3.0",
    "hexo-ruby-character": "^1.0.5",
    "hexo-server": "^0.1.2",
    "hexo-tag-bilibili": "^0.2.1",
    "hexo-tag-bootstrap": "0.0.8",
    "hexo-tag-codepen": "^0.1.2",
    "hexo-tag-vine": "^0.1.0"
  }
}

```

**Comment by NoahDragon** [comment]
Could you please try to run the `npm install`? If still fails, please paste the package.json file.

**Comment by fractal128** [comment]
npm install fails...

**Comment by NoahDragon** [comment]
What're the fail messages?

**Comment by fractal128** [comment]
sorry, ```npm install``` didn't help actually.

**Comment by fractal128** [comment]
I have put  the package.json at the beginnning

**Comment by tea3** [comment]
@fractal128 
If `db.json` exists in your dir , please delete forcely this file and try again. 

```
$ rm -rf ./db.json
$ hexo clean
$ hexo server
```

**Comment by fractal128** [comment]
@tea3 
I've tried but no use at all

**Comment by connor11528** [comment]
This is the package.json for a new hexo project. you can try upgrading your dependencies using `yarn upgrade` or `yarn upgrade hexo-server`. Before you do this run `hexo clean` and `rm -rf node_modules` 

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.3.8"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-server": "^0.2.0"
  }
}
```
