### ISSUE TITLE
Error: Cannot find module './build/Release/DTraceProviderBindings'

### ISSUE THREAD

**Issue by connor11528** [hexojs/hexo#2707]
I did a fresh hexo install and am encountering a warning having to do with dtrace. I was able to fix the issue (as outlined in [this thread](https://github.com/react-community/create-react-native-app/issues/135)) by removing `node_modules` and running fresh `npm i`. Seems to be common issue with node and happened on brand new install running node v8.3.0 and python 3.5.2 so wanted to report it

```
hexo server
{ Error: Cannot find module './build/Release/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/connorleech/hexo-inkubator-theme/node_modules/dtrace-provider/dtrace-provider.js:18:23)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
```

**Comment by NoahDragon** [comment]
Do you also have yarn installed? This could be an issue when hexo-cli calls yarn to install the dependencies.

**Comment by connor11528** [comment]
I do have yarn installed. If I remove `node_modules` again and do a yarn install the error comes back. With `npm i` it goes away. weird

**Comment by connor11528** [comment]
Mostly made an issue so if other people encounter it it is a very quick fix, do npm i instead of yarn install if the error persists. Plus it does not actually stop the server from starting on port 4000

**Comment by JLHwung** [comment]
If you are still using yarn, could you run
```
yarn upgrade hexo-log
```
to see if this issue can be reproduced?
Thank you.
