### ISSUE TITLE
npm install hexo error on macos

### ISSUE THREAD

**Issue by longkeyy** [hexojs/hexo#2714]
npm install hexo --no-optional
module.js:491
    throw err;
    ^

Error: Cannot find module '../lib/utils/unsupported.js'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:19:21
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:92:3)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)

## Environment Info

Node version(`node -v`): v8.4.0

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`):

**Comment by JLHwung** [comment]
Could you print your npm version? It will help us narrow down the issue.
```
npm --version
```

Thank you.

**Comment by longkeyy** [comment]
macos node env error 
fixup step:

chown -R `whoami`:whell /usr/local/lib/node_modules/
brew postinstall node

it's done

**Comment by JLHwung** [comment]
Glad to hear that you have solved this issue on your own. Closing now.
