### ISSUE TITLE
YAMLException: end of the stream or a document separator is expected at line 2, column 1:     date: 2017-08-20 05:35:10

### ISSUE THREAD

**Issue by KarelWintersky** [hexojs/hexo#2717]
WTF? You engine is FULL of WTF-code

```
YAMLException: end of the stream or a document separator is expected at line 2, column 1:
    date: 2017-08-20 05:35:10
    ^
    at generateError (/srv/shared/archives/.Hexo/node_modules/js-yaml/lib/js-yaml/loader.js:165:10)
    at throwError (/srv/shared/archives/.Hexo/node_modules/js-yaml/lib/js-yaml/loader.js:171:9)
    at readDocument (/srv/shared/archives/.Hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1512:5)
    at loadDocuments (/srv/shared/archives/.Hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1548:5)
    at Object.load (/srv/shared/archives/.Hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1569:19)
    at parseYAML (/srv/shared/archives/.Hexo/node_modules/hexo-front-matter/lib/front_matter.js:80:21)
    at Function.parse (/srv/shared/archives/.Hexo/node_modules/hexo-front-matter/lib/front_matter.js:56:12)
    at module.exports (/srv/shared/archives/.Hexo/node_modules/hexo-admin/update.js:34:20)
    at /srv/shared/archives/.Hexo/node_modules/hexo-admin/api.js:326:5
    at /srv/shared/archives/.Hexo/node_modules/hexo-admin/api.js:141:7
    at call (/srv/shared/archives/.Hexo/node_modules/connect/index.js:239:7)
    at next (/srv/shared/archives/.Hexo/node_modules/connect/index.js:183:5)
    at next (/srv/shared/archives/.Hexo/node_modules/connect/index.js:161:14)
    at next (/srv/shared/archives/.Hexo/node_modules/connect/index.js:161:14)
    at next (/srv/shared/archives/.Hexo/node_modules/connect/index.js:161:14)
    at next (/srv/shared/archives/.Hexo/node_modules/connect/index.js:161:14)
    at next (/srv/shared/archives/.Hexo/node_modules/connect/index.js:161:14)
    at next (/srv/shared/archives/.Hexo/node_modules/connect/index.js:161:14)
    at next (/srv/shared/archives/.Hexo/node_modules/connect/index.js:161:14)
    at next (/srv/shared/archives/.Hexo/node_modules/connect/index.js:161:14)
    at /srv/shared/archives/.Hexo/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/srv/shared/archives/.Hexo/node_modules/raw-body/index.js:262:16)
```

**Comment by JLHwung** [comment]
Please add `---` to the frontmatter, see https://hexo.io/docs/front-matter.html
