### ISSUE TITLE
HexoJS theme won't load JS and CSS files on gitlab after deploying, Localhost is all fine.

### ISSUE THREAD

**Issue by javidrashid** [hexojs/hexo#2766]
So I setup the Hexo on my localbox and all works good and as expected, I am serving on port 5000 using : hexo server -p 5000;

If I change any theme it loads the new theme resources without any issue.

But when I push to gitlab, I just see a blank page with no errors in console, 
e-g :  https://integeroverflow.gitlab.io/blog/

If I happen to change my theme (say tranquilpeak) the gitlab would just serve the blank content without loading any CSS or JS, chrome console returns 404 in this case for css and js (broken files) What could be the issue here any guesses? My node version local setup is 8.2.1 but that should not be a problem because it works well on localbox.

Thanks,
Javid

**Comment by tea3** [comment]
@javidrashid 
Are all the files uploaded to gitlab ? There is probably no file other than the top page. For example, it seems that the follow as page does not exist.

(e.g.)
- atom.xml
- https://integeroverflow.gitlab.io/2010/09/20/html5-form-validation/
- https://integeroverflow.gitlab.io/2011/09/20/javascript-apply-call-functions/
- https://integeroverflow.gitlab.io/2012/09/20/goodbye-akamai/
...

When `hexo generate` or `hexo d -g`, are all the files generated ?

**Comment by javidrashid** [comment]
Well these files look broken on gitlab but fine on localbox, were am I supposed to run hexo d -g for gitlab.  My .gitlab-ci.yml looks like this:

image: node:4.2.2

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install hexo-cli -g
  - npm install
  - hexo deploy
  artifacts:
    paths:
    - public
  only:
  - master

**Comment by tea3** [comment]
@javidrashid 
Sorry , I don't understand gitlab CI in detail.  But your `.gitlab-ci.yml` is probably correct. Have you confirmed the CI succeeded in the build ? Can I check the CI log ?

Also , is this article helpful?
https://lisplover.gitlab.io/blog/2016/04/23/How-to-Setup-Hexo-Blog-on-GitLab/

**Comment by javidrashid** [comment]
Yes, it did pass the CI, Apparently I forked an existing repo and all works good there https://integeroverflow.gitlab.io/hexo/
 but not the one I have issue with, which I created from scratch. I triggered another build just now and below is the log:
(FOR https://integeroverflow.gitlab.io/blog/)
....
...
...
npm info install hexo-site@0.0.0
npm info postinstall hexo-site@0.0.0
npm info prepublish hexo-site@0.0.0
npm info ok 
$ hexo deploy
ERROR Script load failed: themes/tranquilpeak/scripts/migrators/1.4.0.js
Error: Cannot find module 'async'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (/builds/integeroverflow/blog/node_modules/hexo/lib/hexo/index.js:216:21)
    at /builds/integeroverflow/blog/themes/tranquilpeak/scripts/migrators/1.4.0.js:6:15
    at /builds/integeroverflow/blog/themes/tranquilpeak/scripts/migrators/1.4.0.js:233:3
    at /builds/integeroverflow/blog/node_modules/hexo/lib/hexo/index.js:232:12
    at tryCatcher (/builds/integeroverflow/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/builds/integeroverflow/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/builds/integeroverflow/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/builds/integeroverflow/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/builds/integeroverflow/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/builds/integeroverflow/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/builds/integeroverflow/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/builds/integeroverflow/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/builds/integeroverflow/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/builds/integeroverflow/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/builds/integeroverflow/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/builds/integeroverflow/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:638:18)
    at /builds/integeroverflow/blog/node_modules/hexo/node_modules/bluebird/js/release/nodeback.js:42:21
    at /builds/integeroverflow/blog/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
ERROR Script load failed: themes/tranquilpeak/scripts/tags/tabbed_codeblock.js
Error: Cannot find module 'hexo-util'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (/builds/integeroverflow/blog/node_modules/hexo/lib/hexo/index.js:216:21)
    at /builds/integeroverflow/blog/themes/tranquilpeak/scripts/tags/tabbed_codeblock.js:3:12
    at /builds/integeroverflow/blog/node_modules/hexo/lib/hexo/index.js:232:12
    at tryCatcher (/builds/integeroverflow/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/builds/integeroverflow/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/builds/integeroverflow/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/builds/integeroverflow/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/builds/integeroverflow/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/builds/integeroverflow/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/builds/integeroverflow/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/builds/integeroverflow/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/builds/integeroverflow/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/builds/integeroverflow/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/builds/integeroverflow/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/builds/integeroverflow/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:638:18)
    at /builds/integeroverflow/blog/node_modules/hexo/node_modules/bluebird/js/release/nodeback.js:42:21
    at /builds/integeroverflow/blog/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
INFO  Start processing
INFO  Files loaded in 1.01 s
INFO  Generated: atom.xml
INFO  Generated: index.html
INFO  Generated: all-categories/index.html
INFO  Generated: archives/index.html
INFO  Generated: all-tags/index.html
INFO  Generated: all-archives/index.html
INFO  Generated: archives/page/2/index.html
INFO  Generated: archives/2012/09/index.html
INFO  Generated: archives/2013/09/index.html
INFO  Generated: archives/2009/09/index.html
INFO  Generated: archives/2011/09/index.html
INFO  Generated: archives/2009/index.html
INFO  Generated: archives/2010/index.html
INFO  Generated: archives/2011/index.html
INFO  Generated: archives/2010/09/index.html
INFO  Generated: archives/2012/index.html
INFO  Generated: archives/2013/index.html
INFO  Generated: archives/2017/index.html
INFO  Generated: page/2/index.html
INFO  Generated: archives/2017/09/index.html
INFO  Generated: 2017/09/22/hello-world/index.html
INFO  Generated: 2011/09/20/javascript-apply-call-functions/index.html
INFO  Generated: 2013/09/20/using-resolve-in-angular/index.html
INFO  Generated: 2010/09/20/about/index.html
INFO  Generated: 2009/09/20/Hello-Hexo/index.html
INFO  Generated: 2012/09/20/goodbye-akamai/index.html
INFO  Generated: 2010/09/20/making-cross-domain-calls-in -jquery/index.html
INFO  Generated: 2011/09/20/angular-tutorial/index.html
INFO  Generated: 2010/09/20/previous-post/index.html
INFO  Generated: 2009/09/20/Hello-Hexo/Hello-Hexo.html
INFO  Generated: 2010/09/20/html5-form-validation/index.html
INFO  Generated: 2009/09/20/Hello-Hexo/Hello-Hexo/index.html
INFO  32 files generated in 1.65 s
Creating cache default...
node_modules/: found 16854 matching files          
Uploading cache.zip to http://runners-cache-5-internal.gitlab.com:444/runner/project/4205350/default 
Created cache
Uploading artifacts...
public: found 82 matching files                    
Uploading artifacts to coordinator... ok            id=33694417 responseStatus=201 Created token=xCM9sMZz
Job succeeded

**Comment by NoahDragon** [comment]
I saw there is an error in the trace log. Could you please try to install the async package for the theme?

**Comment by javidrashid** [comment]
What sense does it make to install async as it works fine on localhost, when I push to gitlab, I am not pushing async module as such. Should gitlab not just install async if it thats needed?

**Comment by javidrashid** [comment]
This issue doesn't look specific to hexo, I guess this is related to the theme tranquilpeak, Hence closing the issue for this repo.

**Comment by NoahDragon** [comment]
@javidrashid As on the localhost, the dependency packages may already installed. However, during the CI, I think it fails to install the dependency packages that the theme needs. Here is the error message in your trace, which indicates it fails inside the theme scripts:
```
ERROR Script load failed: themes/tranquilpeak/scripts/migrators/1.4.0.js
Error: Cannot find module 'async'
```
