### ISSUE TITLE
error: do hexo deploy

### ISSUE THREAD

**Issue by SageLu** [hexojs/hexo#2774]
Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 'GitHub.Authentication, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null                              ' or one of its dependencies. ▒▒ͼ▒▒▒ظ▒ʽ▒▒▒▒ȷ▒ĳ▒▒▒
   at Microsoft.Alm.Cli.Program..ctor()
   at Microsoft.Alm.Cli.Program.Main(String[] args)
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': No error
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error:
Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 'GitHub.Authentication, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null                              ' or one of its dependencies. ��ͼ���ظ�ʽ����ȷ�ĳ�����
   at Microsoft.Alm.Cli.Program..ctor()
   at Microsoft.Alm.Cli.Program.Main(String[] args)
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': No error

    at ChildProcess.<anonymous> (E:\gitpage\node_modules\hexo-util\lib\spawn.js:37:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at ChildProcess.cp.emit (E:\gitpage\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:920:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)

**Comment by SageLu** [comment]
参考的博客：http://www.cnblogs.com/visugar/p/6821777.html
安装了：npm install hexo-deployer-git --save 之后
执行了下边的命令：
hexo clean
hexo generate
hexo deploy

**Comment by NoahDragon** [comment]
Does the solution in the stackoverflow could solve your issue? https://stackoverflow.com/questions/5229310/system-badimageformatexception-could-not-load-file-or-assembly
