### ISSUE TITLE
When install, get Error: Cannot find module

### ISSUE THREAD

**Issue by iyezhou** [hexojs/hexo#2800]
```
# npm install

> dtrace-provider@0.8.5 install /data/www/test/node_modules/dtrace-provider
> node scripts/install.js

module.js:471
    throw err;
    ^

Error: Cannot find module '/data/www/test/node_modules/dtrace-provider/scripts/install.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.8.5 (node_modules/dtrace-provider):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.8.5 install: `node scripts/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

**Comment by JLHwung** [comment]
You can try with
```
npm install hexo-log@0.2.0
```
