### ISSUE TITLE
What do you need to do to deploy to Heroku?

### ISSUE THREAD

**Issue by ItsPugle** [hexojs/hexo#2823]
I've already installed [`hexo-deployer-heroku`](https://github.com/hexojs/hexo-deployer-heroku) and changed my `_config.yml`:
```yaml
# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: heroku
  repo: https://git.heroku.com/service-church.git
  message: ~DeployOps~ Site generation pushed ({{ now('YYYY-MM-DD HH:mm:ss') }})
```

Here's the deploy log when I run `$ hexo deploy --generate`:
```
ItsPugle/ServiceChurch [master] » hexo deploy --generate
INFO  Start processing
INFO  Files loaded in 1.88 s
INFO  Generated: sitemap.xml
INFO  Generated: atom.xml
INFO  Generated: index.html
INFO  Generated: favicon.png
INFO  Generated: hello-world/index.html
INFO  Generated: archives/index.html
INFO  Generated: scss/apollo.scss
INFO  Generated: archives/2017/index.html
INFO  Generated: font/sourcesanspro.woff2
INFO  Generated: archives/2017/11/index.html
INFO  Generated: font/sourcesanspro.woff
INFO  Generated: css/apollo.css
INFO  12 files generated in 63 ms
INFO  Deploying: heroku
INFO  Setting up Heroku deployment...
Initialized empty Git repository in /Users/itspugle/Code/ItsPugle/ServiceChurch/.deploy_heroku/.git/
[master (root-commit) ec5fb43] First commit
 2 files changed, 1 insertion(+)
 create mode 100644 Procfile
 create mode 100644 index.php
INFO  Copying files from public folder...
[master 0f80113] ~DeployOps~ Site generation pushed (2017-11-01 17:00:32)
 12 files changed, 85 insertions(+)
 create mode 100644 public/archives/2017/11/index.html
 create mode 100644 public/archives/2017/index.html
 create mode 100644 public/archives/index.html
 create mode 100644 public/atom.xml
 create mode 100644 public/css/apollo.css
 create mode 100644 public/favicon.png
 create mode 100644 public/font/sourcesanspro.woff
 create mode 100644 public/font/sourcesanspro.woff2
 create mode 100644 public/hello-world/index.html
 create mode 100644 public/index.html
 create mode 100644 public/scss/apollo.scss
 create mode 100644 public/sitemap.xml
remote: Compressing source files... done.        
remote: Building source:        
remote: 
remote: -----> App not compatible with buildpack: https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/nodejs.tgz        
remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure        
remote: 
remote:  !     Push failed        
remote: Verifying deploy...
remote: 
remote: !	Push rejected to service-church.        
remote: 
To https://git.heroku.com/service-church.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/service-church.git'
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: remote: Compressing source files... done.        
remote: Building source:        
remote: 
remote: -----> App not compatible with buildpack: https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/nodejs.tgz        
remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure        
remote: 
remote:  !     Push failed        
remote: Verifying deploy...
remote: 
remote: !	Push rejected to service-church.        
remote: 
To https://git.heroku.com/service-church.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/service-church.git'

    at ChildProcess.<anonymous> (/Users/itspugle/Code/ItsPugle/ServiceChurch/node_modules/hexo-util/lib/spawn.js:37:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Socket.<anonymous> (internal/child_process.js:351:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)
```

I'm quite new to all this, so I need some basic instructions that I can understand

**Comment by ItsPugle** [comment]
Nevermind. Jekyll has started to work for me.

**Comment by ChenDark** [comment]
Empty the content of the network warehouse, and then re hexo d the local content
