### ISSUE TITLE
Error executing Hexo command

### ISSUE THREAD

**Issue by Pudge1996** [hexojs/hexo#2832]
iMac:PudgeBlog pudge$ hexo s
FATAL Cannot find module '/Volumes/File/PudgeBlog/node_modules/hexo-deployer-git'
Error: Cannot find module '/Volumes/File/PudgeBlog/node_modules/hexo-deployer-git'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.resolve (internal/module.js:18:19)
    at /Volumes/File/PudgeBlog/node_modules/hexo/lib/hexo/load_plugins.js:52:24
    at tryCatcher (/Volumes/File/PudgeBlog/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/Volumes/File/PudgeBlog/node_modules/bluebird/js/release/map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (/Volumes/File/PudgeBlog/node_modules/bluebird/js/release/promise_array.js:114:31)
    at MappingPromiseArray.init (/Volumes/File/PudgeBlog/node_modules/bluebird/js/release/promise_array.js:78:10)
    at Promise._settlePromise (/Volumes/File/PudgeBlog/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/Volumes/File/PudgeBlog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Volumes/File/PudgeBlog/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Volumes/File/PudgeBlog/node_modules/bluebird/js/release/promise.js:638:18)
    at MappingPromiseArray.PromiseArray._resolve (/Volumes/File/PudgeBlog/node_modules/bluebird/js/release/promise_array.js:126:19)
    at MappingPromiseArray._filter (/Volumes/File/PudgeBlog/node_modules/bluebird/js/release/map.js:127:10)
    at MappingPromiseArray._promiseFulfilled (/Volumes/File/PudgeBlog/node_modules/bluebird/js/release/map.js:99:18)
    at Promise._settlePromise (/Volumes/File/PudgeBlog/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/Volumes/File/PudgeBlog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Volumes/File/PudgeBlog/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Volumes/File/PudgeBlog/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/Volumes/File/PudgeBlog/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/Volumes/File/PudgeBlog/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/Volumes/File/PudgeBlog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Volumes/File/PudgeBlog/node_modules/bluebird/js/release/promise.js:614:10)

**Comment by Pudge1996** [comment]
npm install hexo-cli --no-optional
npm install --save hexo-deployer-git
