### ISSUE TITLE
hexo s出现错误

### ISSUE THREAD

**Issue by StormMaybin** [hexojs/hexo#2840]
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: (unknown path)
  Error: expected end of comment, got end of file
    at Object.exports.prettifyError (/Users/stormma/blog/node_modules/nunjucks/src/lib.js:34:15)
    at new_cls.render (/Users/stormma/blog/node_modules/nunjucks/src/environment.js:469:27)
    at new_cls.renderString (/Users/stormma/blog/node_modules/nunjucks/src/environment.js:327:21)
    at /Users/stormma/blog/node_modules/hexo/lib/extend/tag.js:66:9
    at Promise._execute (/Users/stormma/blog/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Users/stormma/blog/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/stormma/blog/node_modules/bluebird/js/release/promise.js:79:10)
    at Tag.render (/Users/stormma/blog/node_modules/hexo/lib/extend/tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (/Users/stormma/blog/node_modules/hexo/lib/hexo/post.js:253:16)
    at /Users/stormma/blog/node_modules/hexo/lib/hexo/render.js:65:19
    at tryCatcher (/Users/stormma/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/stormma/blog/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/stormma/blog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/stormma/blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/stormma/blog/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/stormma/blog/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/stormma/blog/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/stormma/blog/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)

出现这个错误，我检查了md文件，没有发现官网说的错误，不知道怎么解决

**Comment by MegaJ** [comment]
I think maybe https://hexo.io/docs/troubleshooting.html#Escape-Contents this should get updated. This is the third issue I've seen posted about this. See #2904 and #2907 , which were newer than you.

You probably have a `{#` somewhere in your markdown. This makes nunjucks think you are starting a comment. So you should escape your `{#`.

**Comment by StormMaybin** [comment]
thanks



发自我的小米手机
在 MegaJ <notifications@github.com>，2017年12月15日 上午11:42写道：

I think maybe https://hexo.io/docs/troubleshooting.html#Escape-Contents this should get updated. This is the third issue I've seen posted about this. See #2904<https://github.com/hexojs/hexo/issues/2904> and #2907<https://github.com/hexojs/hexo/issues/2907> , which were newer than you.

You probably have a {# somewhere in your markdown. This makes nunjucks think you are starting a comment. So you should escape your {#.
