### ISSUE TITLE
Hexo API incorrect report in use“Cannot read property 'f' of undefined”

### ISSUE THREAD

**Issue by YuYanDev** [hexojs/hexo#2851]
I want to call the HEXO API in the Express.js framework as a hook,But it is wrong.

Perhaps due to the documentation is too simple and lead developers to understand the error caused the error.

I can not get any answer from Google. so,How should I call api?

This is my fail code and console output error:
``` javascript
var express = require('express');
var router = express.Router();
var Hexo = require('hexo');

router.get('/', function(req, res, next) {
  var hexo = new Hexo(process.cwd(), {});
  hexo.init().then(function(){
    hexo.watch().then(function(){
      hexo.call('generate').then(function(){
        return hexo.exit();
      }).catch(function(err){
        return hexo.exit(err);
      });
    });
  });
  res.send('hexo g ture');
});

module.exports = router;
```

and console error
``` 
FATAL Something's wrong.  Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: Cannot read property 'f' of undefined
    at Hexo.generateConsole (/Users/Hiroya/Project/express-blog-hexo/hexo/node_modules/hexo/lib/plugins/console/generate.js:16:20)
From previous event:
    at /Users/Hiroya/Project/express-blog-hexo/hexo/node_modules/hexo/lib/hexo/index.js:195:9
From previous event:
    at Hexo.call (/Users/Hiroya/Project/express-blog-hexo/hexo/node_modules/hexo/lib/hexo/index.js:191:10)
    at /Users/Hiroya/Project/express-blog-hexo/hexo/hexo.js:12:12
From previous event:
    at /Users/Hiroya/Project/express-blog-hexo/hexo/hexo.js:11:18
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at /Users/Hiroya/Project/express-blog-hexo/hexo/hexo.js:10:15
    at Layer.handle [as handle_request] (/Users/Hiroya/Project/express-blog-hexo/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/Hiroya/Project/express-blog-hexo/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/Hiroya/Project/express-blog-hexo/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/Hiroya/Project/express-blog-hexo/node_modules/express/lib/router/layer.js:95:5)
    at /Users/Hiroya/Project/express-blog-hexo/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/Hiroya/Project/express-blog-hexo/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/Hiroya/Project/express-blog-hexo/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/Users/Hiroya/Project/express-blog-hexo/node_modules/express/lib/router/index.js:174:3)
    at router (/Users/Hiroya/Project/express-blog-hexo/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/Users/Hiroya/Project/express-blog-hexo/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/Hiroya/Project/express-blog-hexo/node_modules/express/lib/router/index.js:317:13)
    at /Users/Hiroya/Project/express-blog-hexo/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/Hiroya/Project/express-blog-hexo/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/Hiroya/Project/express-blog-hexo/node_modules/express/lib/router/index.js:275:10)
    at /Users/Hiroya/Project/express-blog-hexo/node_modules/express/lib/router/index.js:635:15
    at next (/Users/Hiroya/Project/express-blog-hexo/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/Users/Hiroya/Project/express-blog-hexo/node_modules/express/lib/router/index.js:174:3)
    at router (/Users/Hiroya/Project/express-blog-hexo/node_modules/express/lib/router/index.js:47:12)
```
and this is my file tree
```
.
├── app.js
├── bin
│   └── www
├── hexo
│   ├── _config.yml
│   ├── hexo.js
│   ├── node_modules
│   ├── package-lock.json
│   ├── package.json
│   ├── scaffolds
│   ├── source
│   └── themes
├── node_modules
├── package-lock.json
├── package.json
├── public
│   ├── images
│   ├── javascripts
│   └── stylesheets
├── routes
│   ├── index.js
│   └── users.js
├── source
│   └── _posts
└── views
    ├── error.ejs
    └── index.ejs
```

**Comment by bhaskarmelkani** [comment]
Hey.

You missed the second argument of the `generate` function. 
It should be called like following.
```js
hexo.call('generate', {}).then(function(){  // ...});
```

Updated your code.
```js
var express = require('express');
var router = express.Router();
var Hexo = require('hexo');

router.get('/', function(req, res, next) {
  var hexo = new Hexo(process.cwd(), {});
  hexo.init().then(function(){
    hexo.watch().then(function(){
      hexo.call('generate', {}).then(function(){
        return hexo.exit();
      }).catch(function(err){
        return hexo.exit(err);
      });
    });
  });
  res.send('hexo g ture');
});

module.exports = router;
```

**Comment by bhaskarmelkani** [comment]
@NoahDragon Maybe we should do `args = args || {}` [here](https://github.com/hexojs/hexo/blob/master/lib/plugins/console/generate.js#L15) or write in documentation that the second argument is mandatory.

**Comment by NoahDragon** [comment]
@bhaskarmelkani  agree, we should document that.

**Comment by bhaskarmelkani** [comment]
I will prefer adding default `args = args || {}` to it.

**Comment by bhaskarmelkani** [comment]
Linked a PR if we decide to go other way.

**Comment by JLHwung** [comment]
The common node.js function will have signature
```
foo(arg[, options])
```
see https://nodejs.org/api/fs.html#fs_fs_readdirsync_path_options. I suggest we keep consistency with node.js convention.

@bhaskarmelkani Could you file a PR to add defaults? Thank you

**Comment by YuYanDev** [comment]
Thank yours, I can now use it☺️

**Comment by bhaskarmelkani** [comment]
Yeah will do it asap.

**Comment by bhaskarmelkani** [comment]
Closing in reference to [#PR](https://github.com/hexojs/hexo/pull/2862)
