### ISSUE TITLE
hexo generate 报错，不知道哪里有问题，

### ISSUE THREAD

**Issue by woozs** [hexojs/hexo#2878]
下面是报错信息
I:\blog>hexo generate
INFO  -----------------------------------------------------------
INFO  qiniu state: offline
INFO  qiniu sync:  false
INFO  qiniu local dir:  cdn
INFO  qiniu url:   /cdn
INFO  -----------------------------------------------------------
WARN  qiniu sync is offline mode
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: (unknown path) [Line 8, Column 23]
  Error: Unable to call `the return value of (posts["first"])["updated"]["toISOString"]`, which is undefined or falsey
    at Object.exports.prettifyError (I:\blog\node_modules\hexo-generator-feed\node_modules\nunjucks\src\lib.js:34:15)
    at I:\blog\node_modules\hexo-generator-feed\node_modules\nunjucks\src\environment.js:489:31
    at new_cls.root [as rootRenderFunc] (eval at _compile (I:\blog\node_modules\hexo-generator-feed\node_modules\nunjucks\src\environment.js:568:24), <anonymous>:210:3)
    at new_cls.render (I:\blog\node_modules\hexo-generator-feed\node_modules\nunjucks\src\environment.js:482:15)
    at Hexo.module.exports (I:\blog\node_modules\hexo-generator-feed\lib\generator.js:40:22)
    at Hexo.tryCatcher (I:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (I:\blog\node_modules\bluebird\js\release\method.js:15:34)
    at I:\blog\node_modules\hexo\lib\hexo\index.js:340:24
    at tryCatcher (I:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (I:\blog\node_modules\bluebird\js\release\map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (I:\blog\node_modules\bluebird\js\release\promise_array.js:114:31)
    at MappingPromiseArray.init (I:\blog\node_modules\bluebird\js\release\promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (I:\blog\node_modules\bluebird\js\release\map.js:30:10)
    at Async._drainQueue (I:\blog\node_modules\bluebird\js\release\async.js:138:12)
    at Async._drainQueues (I:\blog\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (I:\blog\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)

**Comment by MegaJ** [comment]
Hmm...looks like `hexo-generator-feed` hit a snag. There's something in that feed generation that gave nunjucks a problem. From the call stack, it looks like some environment variable isn't being set correctly.

The relevant source is [here](https://github.com/hexojs/hexo-generator-feed/blob/master/lib/generator.js). 

It looks like the error happens when nunjucks hits this line: https://github.com/hexojs/hexo-generator-feed/blob/master/atom.xml#L9

So something in a `{{ posts.first().updated.toISOString() }}` call doesn't return correctly. Do you have any posts?
