### ISSUE TITLE
{#}

### ISSUE THREAD

**Issue by gavin-fu** [hexojs/hexo#2907]
markdown文档中存在 "{#}"会报错，hexo: 3.4.2
报错内容如下：
PS D:\GitRepository\hexo-blog\source> hexo g
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: (unknown path)
  Error: expected end of comment, got end of file
    at Object.exports.prettifyError (D:\GitRepository\hexo-blog\node_modules\nunjucks\src\lib.js:34:15)
    at new_cls.render (D:\GitRepository\hexo-blog\node_modules\nunjucks\src\environment.js:469:27)
    at new_cls.renderString (D:\GitRepository\hexo-blog\node_modules\nunjucks\src\environment.js:327:21)
    at D:\GitRepository\hexo-blog\node_modules\hexo\lib\extend\tag.js:66:9
    at Promise._execute (D:\GitRepository\hexo-blog\node_modules\bluebird\js\release\debuggability.js:303:9)
    at Promise._resolveFromExecutor (D:\GitRepository\hexo-blog\node_modules\bluebird\js\release\promise.js:483:18)
    at new Promise (D:\GitRepository\hexo-blog\node_modules\bluebird\js\release\promise.js:79:10)
    at Tag.render (D:\GitRepository\hexo-blog\node_modules\hexo\lib\extend\tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (D:\GitRepository\hexo-blog\node_modules\hexo\lib\hexo\post.js:266:16)
    at D:\GitRepository\hexo-blog\node_modules\hexo\lib\hexo\render.js:65:19
    at tryCatcher (D:\GitRepository\hexo-blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\GitRepository\hexo-blog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\GitRepository\hexo-blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\GitRepository\hexo-blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\GitRepository\hexo-blog\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (D:\GitRepository\hexo-blog\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (D:\GitRepository\hexo-blog\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\GitRepository\hexo-blog\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

**Comment by tcrowe** [comment]
It says you're in `D:\GitRepository\hexo-blog\source`. Does it work if you back out to the parent directory `hexo-blog` and do it again? `cd ..`

**Comment by MegaJ** [comment]
@gavin-fu
See https://github.com/hexojs/hexo/issues/2904
