### ISSUE TITLE
hexo generate failed Error: write EPIPE

### ISSUE THREAD

**Issue by TingxunShi** [hexojs/hexo#2913]
## Environment Info

Node version(`node -v`):
```
hexo: 3.4.3
hexo-cli: 1.0.4
os: Darwin 17.3.0 darwin x64
http_parser: 2.7.0
node: 9.2.1
v8: 6.2.414.44-node.11
uv: 1.16.1
zlib: 1.2.11
ares: 1.13.0
modules: 59
nghttp2: 1.25.0
openssl: 1.0.2n
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
```

Hexo and Plugin version(`npm ls --depth 0`): 
```
├── hexo@3.4.3
├── hexo-deployer-git@0.3.1
├── hexo-generator-archive@0.1.5
├── hexo-generator-baidu-sitemap@0.1.2
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.1
├── hexo-generator-sitemap@1.2.0
├── hexo-generator-tag@0.2.0
├── hexo-inject@1.0.0
├── hexo-math@3.0.4
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-marked@0.3.0
├── hexo-renderer-pandoc@0.1.1
├── hexo-renderer-stylus@0.3.3
└── hexo-server@0.2.2
```

## For question

博客在Ubuntu的笔记本上构建正常，但是通过git同步到mac上以后执行`hexo g`报错：
> INFO  [hexo-math] Using engine 'mathjax'
> INFO  Start processing
> events.js:136
>       throw er; // Unhandled 'error' event
>       ^

> Error: write EPIPE
>     at _errnoException (util.js:1031:13)
>     at WriteWrap.afterWrite [as oncomplete] (net.js:873:14)

**Comment by NoahDragon** [comment]
Could you please node 8.9?

**Comment by TimothyShi-kika** [comment]
@NoahDragon Thanks for the response. I've downgraded node to 8.9 however the same thing happened again. 

I ran `hexo g --debug` and the more detailed information (snippet) is shown below:
```
12:39:51.085 DEBUG Plugin loaded: hexo-server
12:39:51.087 DEBUG [hexo-inject] firing inject_ready
12:39:51.092 INFO  Start processing
12:39:51.097 DEBUG [hexo-inject] SKIP: undefined
12:39:51.098 DEBUG Incomplete document
Error: Incomplete document
    at Inject._transform (/Users/txshi/Blogs/node_modules/hexo-inject/lib/mixin/transform.js:29:34)
    at Hexo.tryCatcher (/Users/txshi/Blogs/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Users/txshi/Blogs/node_modules/bluebird/js/release/method.js:15:34)
    at /Users/txshi/Blogs/node_modules/hexo/lib/extend/filter.js:68:35
    at tryCatcher (/Users/txshi/Blogs/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/Users/txshi/Blogs/node_modules/bluebird/js/release/reduce.js:155:18)
    at Object.gotAccum (/Users/txshi/Blogs/node_modules/bluebird/js/release/reduce.js:144:25)
    at Object.tryCatcher (/Users/txshi/Blogs/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/txshi/Blogs/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/txshi/Blogs/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/Users/txshi/Blogs/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/Users/txshi/Blogs/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/Users/txshi/Blogs/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/txshi/Blogs/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
12:39:51.117 DEBUG Processed: .nojekyll
12:39:51.123 DEBUG Processed: CNAME
12:39:51.124 DEBUG Processed: robots.txt
12:39:51.150 DEBUG Processed: images/avatar.jpg
...
12:39:51.366 DEBUG Processed: _posts/NTUML-2-Learning-to-Answer-Yes-No.md
12:39:51.369 DEBUG Processed: _posts/NTUML-23-Blending-Bagging.md
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at _errnoException (util.js:1024:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:867:14)
```

I've noticed the "incomplete document" error and I did some search, but didn't get any clue. All the markdown files can be parsed in the original Ubuntu env, no "{{" can be found

Please kindly give further help, thanks

**Comment by NoahDragon** [comment]
Thanks for the details. Is that some issue related to the `hexo-inject`? I never used it, so not sure it injects something that conflict with Hexo.

**Comment by TingxunShi** [comment]
I removed `hexo-inject` and also `hexo-math`, this time no other error message was reported but only the original wrte EPIPE error:

```
15:00:38.947 DEBUG Hexo version: 3.4.3
15:00:38.949 DEBUG Working directory: ~/Blogs/
15:00:39.017 DEBUG Config loaded: ~/Blogs/_config.yml
15:00:39.026 DEBUG Plugin loaded: hexo-deployer-git
15:00:39.029 DEBUG Plugin loaded: hexo-generator-archive
15:00:39.033 DEBUG Plugin loaded: hexo-generator-baidu-sitemap
15:00:39.035 DEBUG Plugin loaded: hexo-generator-category
15:00:39.037 DEBUG Plugin loaded: hexo-generator-index
15:00:39.038 DEBUG Plugin loaded: hexo-generator-sitemap
15:00:39.039 DEBUG Plugin loaded: hexo-generator-tag
15:00:39.040 DEBUG Plugin loaded: hexo-renderer-ejs
15:00:39.046 DEBUG Plugin loaded: hexo-renderer-marked
15:00:39.047 DEBUG Plugin loaded: hexo-renderer-pandoc
15:00:39.047 DEBUG Plugin loaded: hexo-renderer-stylus
15:00:39.103 DEBUG Plugin loaded: hexo-server
15:00:39.109 DEBUG Script loaded: themes/next/scripts/merge-configs.js
15:00:39.111 DEBUG Script loaded: themes/next/scripts/merge.js
15:00:39.111 DEBUG Script loaded: themes/next/scripts/tags/button.js
15:00:39.111 DEBUG Script loaded: themes/next/scripts/tags/center-quote.js
15:00:39.111 DEBUG Script loaded: themes/next/scripts/tags/exturl.js
15:00:39.112 DEBUG Script loaded: themes/next/scripts/tags/full-image.js
15:00:39.112 DEBUG Script loaded: themes/next/scripts/tags/group-pictures.js
15:00:39.113 DEBUG Script loaded: themes/next/scripts/tags/label.js
15:00:39.113 DEBUG Script loaded: themes/next/scripts/tags/lazy-image.js
15:00:39.113 DEBUG Script loaded: themes/next/scripts/tags/note.js
15:00:39.113 DEBUG Script loaded: themes/next/scripts/tags/tabs.js
15:00:39.114 DEBUG Loading database.
15:00:39.262 INFO  Start processing
15:00:39.305 DEBUG Processed: .nojekyll
15:00:39.320 DEBUG Processed: googlea1eaf9be22597702.html
15:00:39.321 DEBUG Processed: CNAME
15:00:39.321 DEBUG Processed: robots.txt
15:00:39.405 DEBUG Processed: categories/index.md
15:00:39.405 DEBUG Processed: _posts/CS20SI-1-Introduction.md
15:00:39.405 DEBUG Processed: _posts/CS20SI-2-Operations.md
...
15:00:39.464 DEBUG Theme config loaded.
15:00:39.466 DEBUG Processed: _config.yml
15:00:39.466 DEBUG Processed: source/css/main.styl
15:00:39.466 DEBUG Processed: source/images/algolia_logo.svg
15:00:39.467 DEBUG Processed: source/images/apple-touch-icon-next.png
15:00:39.467 DEBUG Processed: source/images/avatar.gif
15:00:39.467 DEBUG Processed: source/images/cc-by-nc-nd.svg
15:00:39.467 DEBUG Processed: source/images/cc-by-nc-sa.svg
15:00:39.467 DEBUG Processed: source/images/cc-by-nc.svg
15:00:39.468 DEBUG Processed: source/images/cc-by-nd.svg
15:00:39.468 DEBUG Processed: source/images/cc-by-sa.svg
...
15:00:39.803 DEBUG Processed: layout/_third-party/search/algolia-search/dom.swig
15:00:39.803 DEBUG Processed: source/lib/three/three.min.js
15:00:39.803 DEBUG Processed: source/lib/font-awesome/fonts/fontawesome-webfont.svg
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at _errnoException (util.js:1024:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:867:14)
```

**Comment by NoahDragon** [comment]
Is the https://github.com/TingxunShi/blog_src Hexo source code?

I got the following error:
```
Template render error: (unknown path)
  Error: expected end of comment, got end of file
    at Object.exports.prettifyError (C:\Users\tester\Dev\2913-hexo\node_modules\nunjucks\src\lib.js:34:15)
    at new_cls.render (C:\Users\tester\Dev\2913-hexo\node_modules\nunjucks\src\environment.js:469:27)
    at new_cls.renderString (C:\Users\tester\Dev\2913-hexo\node_modules\nunjucks\src\environment.js:327:21)
    at C:\Users\tester\Dev\2913-hexo\node_modules\hexo\lib\extend\tag.js:66:9
    at Promise._execute (C:\Users\tester\Dev\2913-hexo\node_modules\bluebird\js\release\debuggability.js:303:9)
    at Promise._resolveFromExecutor (C:\Users\tester\Dev\2913-hexo\node_modules\bluebird\js\release\promise.js:483:18)
    at new Promise (C:\Users\tester\Dev\2913-hexo\node_modules\bluebird\js\release\promise.js:79:10)
    at Tag.render (C:\Users\tester\Dev\2913-hexo\node_modules\hexo\lib\extend\tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (C:\Users\tester\Dev\2913-hexo\node_modules\hexo\lib\hexo\post.js:266:16)
    at C:\Users\tester\Dev\2913-hexo\node_modules\hexo\lib\hexo\render.js:65:19
    at tryCatcher (C:\Users\tester\Dev\2913-hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\tester\Dev\2913-hexo\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\tester\Dev\2913-hexo\node_modules\bluebird\js\release\promise.js:569:18)

    at Promise._settlePromise0 (C:\Users\tester\Dev\2913-hexo\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\tester\Dev\2913-hexo\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\tester\Dev\2913-hexo\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\tester\Dev\2913-hexo\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\tester\Dev\2913-hexo\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

Here is my environment:
```
hexo: 3.4.4
hexo-cli: 1.0.4
os: Windows_NT 6.3.9600 win32 x64
http_parser: 2.7.0
node: 6.9.1
v8: 5.1.281.84
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2j
```

Based on the info, seems there is an error in the template. Really odd.

**Comment by TingxunShi** [comment]
Really appreciate for your investigation @NoahDragon -- Yes, that url links to my hexo source code, but before I didn't commit the next theme together with my other code so you got that error. I've updated the project, could please kindly see it again?

**Comment by NoahDragon** [comment]
I see, I used the latest NexT instead. Will try the new commit.

**Comment by TimothyShi-kika** [comment]
Thanks @NoahDragon 's help. After two weeks' work everything (approximately) goes fine now. 

Here are some notes for the other guys who may also suffering:
- as NoahDragon's comment, update hexo-renderer-pandoc to 0.2.0
- remove hexo-inject, and also hexo-math
- add files "mathjax.ejs" and "after_footer.ejs" in themes/next/layout/_partials . Contents of these files can be found via Google
- if you have `engine: 'mathjax'` in the _config.yml of your root dir of the blog, comment it out

Here is my output after executing `npm ls --depth 0`:
```
hexo-site@0.0.0 /Users/txshi/Blogs
├── hexo@3.4.3
├── hexo-deployer-git@0.3.1
├── hexo-generator-archive@0.1.5
├── hexo-generator-baidu-sitemap@0.1.2
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.1
├── hexo-generator-sitemap@1.2.0
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-pandoc@0.2.0
├── hexo-renderer-stylus@0.3.3
└── hexo-server@0.2.2
```

Hope this could help

**Comment by TingxunShi** [comment]
Thanks @NoahDragon 's help. After two weeks' work everything (approximately) goes fine now. 

Here are some notes for the other guys who may also suffering:
- as NoahDragon's comment, update hexo-renderer-pandoc to 0.2.0
- remove hexo-inject, and also hexo-math
- add files "mathjax.ejs" and "after_footer.ejs" in themes/next/layout/_partials . Contents of these files can be found via Google
- if you have `engine: 'mathjax'` in the _config.yml of your root dir of the blog, comment it out

Here is my output after executing `npm ls --depth 0`:
```
hexo-site@0.0.0 /Users/txshi/Blogs
├── hexo@3.4.3
├── hexo-deployer-git@0.3.1
├── hexo-generator-archive@0.1.5
├── hexo-generator-baidu-sitemap@0.1.2
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.1
├── hexo-generator-sitemap@1.2.0
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-pandoc@0.2.0
├── hexo-renderer-stylus@0.3.3
└── hexo-server@0.2.2
```

Hope this could help

**Comment by NoahDragon** [comment]
👍 @TingxunShi Thanks for your feedback.
