### ISSUE TITLE
npm update error (Error: write EPIPE)

### ISSUE THREAD

**Issue by BerkhanBerkdemir** [hexojs/hexo#2963]
Node version: ```v8.9.1```
Hexo and Plugin version: 
```
├── hexo@3.4.4
├── hexo-all-minifier@0.4.1
├── hexo-generator-archive@0.1.5
├── hexo-generator-category@0.1.3
├── hexo-generator-feed@1.2.2
├── hexo-generator-index@0.2.1
├── hexo-generator-seo-friendly-sitemap@0.0.21
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.3.1
├── hexo-renderer-marked@0.3.2
├── hexo-renderer-stylus@0.3.3
└── hexo-server@0.2.2
```

I wanted upload npm with `npm update`. But, I got this error.

```
Error: write EPIPE
    at _errnoException (util.js:1024:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:867:14)
```

output for `hexo generate --debug`

```
02:37:33.167 DEBUG Generator: page
02:37:33.167 DEBUG Generator: post
02:37:33.167 DEBUG Generator: archive
02:37:33.167 DEBUG Generator: category
02:37:33.167 DEBUG Generator: feed
02:37:33.167 DEBUG Generator: index
02:37:33.168 DEBUG Generator: tag
02:37:33.170 DEBUG Generator: asset
02:37:33.177 DEBUG Generator: sitemap
02:37:33.215 FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
...
Error: write EPIPE
    at _errnoException (util.js:1024:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:867:14)
02:37:33.235 DEBUG Database saved
```

Also I rewrite the file, but still I am getting problem.

**Comment by NoahDragon** [comment]
Close as duplicate to #2913
