### ISSUE TITLE
ERROR Plugin load failed: hexo-tag-uml

### ISSUE THREAD

**Issue by huangjihua** [hexojs/hexo#2981]
ERROR Plugin load failed: hexo-tag-uml
TypeError: Cannot read property 'html_tag' of undefined
    at /Users/huangjihua/Desktop/github/MySelf_Project_Workspace/huangjihua.github.io/node_modules/hexo-tag-uml/bin/index.js:10:20
    at /Users/huangjihua/Desktop/github/MySelf_Project_Workspace/huangjihua.github.io/node_modules/hexo/lib/hexo/index.js:232:12
    at tryCatcher (/Users/huangjihua/Desktop/github/MySelf_Project_Workspace/huangjihua.github.io/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/huangjihua/Desktop/github/MySelf_Project_Workspace/huangjihua.github.io/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/huangjihua/Desktop/github/MySelf_Project_Workspace/huangjihua.github.io/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/huangjihua/Desktop/github/MySelf_Project_Workspace/huangjihua.github.io/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/huangjihua/Desktop/github/MySelf_Project_Workspace/huangjihua.github.io/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/huangjihua/Desktop/github/MySelf_Project_Workspace/huangjihua.github.io/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/Users/huangjihua/Desktop/github/MySelf_Project_Workspace/huangjihua.github.io/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/Users/huangjihua/Desktop/github/MySelf_Project_Workspace/huangjihua.github.io/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/Users/huangjihua/Desktop/github/MySelf_Project_Workspace/huangjihua.github.io/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/huangjihua/Desktop/github/MySelf_Project_Workspace/huangjihua.github.io/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/huangjihua/Desktop/github/MySelf_Project_Workspace/huangjihua.github.io/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/huangjihua/Desktop/github/MySelf_Project_Workspace/huangjihua.github.io/node_modules/bluebird/js/release/promise.js:638:18)
    at /Users/huangjihua/Desktop/github/MySelf_Project_Workspace/huangjihua.github.io/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/huangjihua/Desktop/github/MySelf_Project_Workspace/huangjihua.github.io/node_modules/graceful-fs/graceful-fs.js:78:16
    at tryToString (fs.js:449:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)

hexo: 3.4.4
hexo-cli: 1.0.4
os: Darwin 15.6.0 darwin x64
http_parser: 2.7.0
node: 6.2.0
v8: 5.0.71.47
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h

**Comment by NoahDragon** [comment]
Close as lack of info.
