### ISSUE TITLE
Template render erro

### ISSUE THREAD

**Issue by charsdavy** [hexojs/hexo#2995]
## Environment Info

Node version(`node -v`):

v6.11.0

Hexo and Plugin version(`npm ls --depth 0`): 

├── hexo@3.5.0
├── hexo-algolia@1.2.4
├── hexo-algoliasearch@0.2.3
├── hexo-generator-archive@0.1.5
├── hexo-generator-baidu-sitemap@0.1.2
├── hexo-generator-category@0.1.3
├── hexo-generator-feed@1.2.2
├── hexo-generator-index@0.2.1
├── hexo-generator-json-content@3.0.1
├── hexo-generator-sitemap@1.2.0
├── hexo-generator-tag@0.2.0
├── hexo-helper-qrcode@1.0.2
├── hexo-renderer-ejs@0.1.1
├── hexo-renderer-less@0.2.0
├── hexo-renderer-marked@0.2.11
├── hexo-renderer-stylus@0.3.3
├── hexo-server@0.1.3
└── hexo-wordcount@2.0.1

## For BUG

Template render error: (unknown path)
  SyntaxError: Invalid or unexpected token
    at Object.exports.prettifyError (/Users/dengw/hexo/node_modules/nunjucks/src/lib.js:34:15)
    at new_cls.render (/Users/dengw/hexo/node_modules/nunjucks/src/environment.js:472:27)
    at new_cls.renderString (/Users/dengw/hexo/node_modules/nunjucks/src/environment.js:328:21)
    at /Users/dengw/hexo/node_modules/hexo/lib/extend/tag.js:66:9
    at Promise._execute (/Users/dengw/hexo/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/Users/dengw/hexo/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/dengw/hexo/node_modules/bluebird/js/release/promise.js:79:10)
    at Tag.render (/Users/dengw/hexo/node_modules/hexo/lib/extend/tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (/Users/dengw/hexo/node_modules/hexo/lib/hexo/post.js:266:16)
    at /Users/dengw/hexo/node_modules/hexo/lib/hexo/render.js:65:19
    at tryCatcher (/Users/dengw/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/dengw/hexo/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/dengw/hexo/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/dengw/hexo/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/dengw/hexo/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/dengw/hexo/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/dengw/hexo/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/dengw/hexo/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

**Comment by JLHwung** [comment]
Could you give us a minimal reproducing examples? It seems there is some tag plugins causing nunjuck errors.

Does it work on previous hexo version?

**Comment by IamBusy** [comment]
I came up with the same suitatuion.

**Comment by NoahDragon** [comment]
Could you please elaborate?

It usually caused by some string like `{{` or `}}`.

**Comment by tcrowe** [comment]
@IamBusy @charsdavy Did you solve it? If not you can post your template code. I'm sure we can spot the bug.

**Comment by IamBusy** [comment]
@tcrowe  I finally solved it by removing an unexpected char in my article. I checked the char and got the following result:

```
>>> ord(line[0])
8232
```
