### ISSUE TITLE
Allow server to run with no posts in source/_posts

### ISSUE THREAD

**Issue by Whassup** [hexojs/hexo#2996]
## Environment Info

Node version(`node -v`):
v8.2.1

Hexo and Plugin version(`npm ls --depth 0`): 
├── hexo@3.5.0
├── hexo-generator-archive@0.1.5
├── hexo-generator-category@0.1.3
├── hexo-generator-feed@1.2.2
├── hexo-generator-index@0.2.1
├── hexo-generator-json-content@3.0.1
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.3.1
├── hexo-renderer-marked@0.3.2
├── hexo-renderer-stylus@0.3.3
└── hexo-server@0.2.2

## For feature request

Allow for hexo server to be started when there are no posts in `source/_posts` folder.

Currently if you run the following with an empty posts folder it returns the following error. 
```
hexo server
```

### Error
```
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: (unknown path) [Line 8, Column 23]
  Error: Unable to call `the return value of (posts["first"])["updated"]["toISOString"]`, which is undefined or falsey
    at Object.exports.prettifyError (/Users/rprib/projects/rp-blog/node_modules/hexo-generator-feed/node_modules/nunjucks/src/lib.js:34:15)
    at /Users/rprib/projects/rp-blog/node_modules/hexo-generator-feed/node_modules/nunjucks/src/environment.js:489:31
    at new_cls.root [as rootRenderFunc] (eval at _compile (/Users/rprib/projects/rp-blog/node_modules/hexo-generator-feed/node_modules/nunjucks/src/environment.js:568:24), <anonymous>:210:3)
    at new_cls.render (/Users/rprib/projects/rp-blog/node_modules/hexo-generator-feed/node_modules/nunjucks/src/environment.js:482:15)
    at Hexo.module.exports (/Users/rprib/projects/rp-blog/node_modules/hexo-generator-feed/lib/generator.js:40:22)
    at Hexo.tryCatcher (/Users/rprib/projects/rp-blog/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Users/rprib/projects/rp-blog/node_modules/bluebird/js/release/method.js:15:34)
    at /Users/rprib/projects/rp-blog/node_modules/hexo/lib/hexo/index.js:340:26
    at tryCatcher (/Users/rprib/projects/rp-blog/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/Users/rprib/projects/rp-blog/node_modules/bluebird/js/release/map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (/Users/rprib/projects/rp-blog/node_modules/bluebird/js/release/promise_array.js:114:31)
    at MappingPromiseArray.init (/Users/rprib/projects/rp-blog/node_modules/bluebird/js/release/promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (/Users/rprib/projects/rp-blog/node_modules/bluebird/js/release/map.js:30:10)
    at Async._drainQueue (/Users/rprib/projects/rp-blog/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/Users/rprib/projects/rp-blog/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/rprib/projects/rp-blog/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
```

It could instead log a warning and still load the server.

**Comment by NoahDragon** [comment]
Which theme are you using?

**Comment by Whassup** [comment]
I test with the theme it comes packaged with 'hexo-theme-landscape' and a custom https://github.com/ppoffice/hexo-theme-hueman

**Comment by NoahDragon** [comment]
Could you try to remove the `hexo-generator-feed` plugin?
