### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by Jiiiiiin** [hexojs/hexo#3000]
## Environment Info

Node version(`node -v`):v8.9.3

Your site `_config.yml` (Optional):
```js
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 赵津的日常工作、技术记录
subtitle:
description: 记录一些自己学习、工作中遇到的有帮助的东西，念念不忘，以求不断进步和成熟。
author: 赵津
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://jiiiiiin.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: landscape
# theme: apollo
theme: archer

# apollo theme要求
# 新增
# 在归档页面显示所有文章
# 需要上面安装的 hexo-generator-archive 插件支持
archive_generator:
    per_page: 0
    yearly: false
    monthly: false
    daily: false

# archer theme要求
jsonContent:
  meta: false
  pages: false
  posts:
    title: true
    date: true
    path: true
    text: false
    raw: false
    content: false
    slug: false
    updated: false
    comments: false
    link: false
    permalink: false
    excerpt: false
    categories: false
    tags: true


# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:Jiiiiiin/Jiiiiiin.github.io.git
  branch: master

```

Your theme `_config.yml` (Optional): 
```js
# ========== Profile ========== #
# avatar
avatar: /avatar/favicon.jpg
# author name
author: 赵津
# signature
signature: 学习、工作和狗粮
# SNS
social:
  email: jiiiiiin@yeah.net
  github: //github.com/Jiiiiiin
  # weibo:
  zhihu: //www.zhihu.com/people/jiiiiiin/activities
  # douban:
  # facebook:
  # twitter:
  # instagram:
  # stack-overflow:
  # linkedin:
  # others:
  # rss: /atom.xml
# friends
# friends:
#   friendA: //www.baidu.com
#   friendB: //www.google.com
  # friendC :
about:
  enable: true
  image: '/intro/about-page.jpg'

# ========== Site ========== #
# title of the site
SEO_title: 赵津
# main title
main_title: 学习、工作和狗粮
# subtitle
subtitle: 赵津
# site haeder image
site_header_image: 'http://oumn0o088.bkt.clouddn.com/intro-desktop.jpg'
# post haeder image
post_header_image: 'http://oumn0o088.bkt.clouddn.com/post-bg.jpg'
# 404 image
_404_image: 'http://oumn0o088.bkt.clouddn.com/404.jpg'

# ========== Comment ========== #
# Fill in the field to enable the corresponding comment plugin
# If you want to add other comment plugin, edit in "custom.ejs"
comment:
  # livere  site: https://livere.com/
  livere_uid:
  # disqus  site: https://disqus.com/
  disqus_shortname: jiiiiiin-cn
  # changyan  site: http://changyan.kuaizhan.com/
  changyan_appid:
  changyan_conf:
  # gitment  site: https://github.com/imsun/gitment
  gitment_owner:
  gitment_repo:
  gitment_client_id:
  gitment_client_secret:
  # youyan  site: http://www.uyan.cc/
  youyan_uid:

# ========== Analytics ========== #
# Busuanzi pv Analytics
busuanzi: true
# Baidu analytics
baidu_analytics:
# Google analytics
google_analytics:
# CNZZ analytics
CNZZ_analytics:

# ========== Others ========== #
# favicon
# favicon: /assets/favicon.ico
favicon: /avatar/favicon.jpg
# truncate length (the default is 300)
truncate_length:
# enable toc
toc: true

tags: tags
categories: /categories

```

Hexo and Plugin version(`npm ls --depth 0`): 

## For BUG

 1. BUG description

不管执行哪一个hexo命令都会报`ReferenceError: document is not defined`:

```js
 jiiiiiin@jiiiiiins-MBP  ~/Documents/Atom/hexo/blog   master ●  hexo c && hexo g && hexo s
ERROR Script load failed: scripts/main.js
ReferenceError: document is not defined
    at Object.defineProperty.value (/Users/jiiiiiin/Documents/Atom/hexo/blog/scripts/main.js:1:532)
    at t (/Users/jiiiiiin/Documents/Atom/hexo/blog/scripts/main.js:1:172)
    at Object.defineProperty.value (/Users/jiiiiiin/Documents/Atom/hexo/blog/scripts/main.js:1:294)
    at t (/Users/jiiiiiin/Documents/Atom/hexo/blog/scripts/main.js:1:172)
    at /Users/jiiiiiin/Documents/Atom/hexo/blog/scripts/main.js:1:252
    at /Users/jiiiiiin/Documents/Atom/hexo/blog/scripts/main.js:1:257
    at /Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/hexo/lib/hexo/index.js:232:12
    at tryCatcher (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/promise.js:638:18)
    at /Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
Usage: hexo <command>

Commands:
  clean     Remove generated files and cache.
  config    Get or set configurations.
  deploy    Deploy your website.
  generate  Generate static files.
  help      Get help on a command.
  init      Create a new Hexo folder.
  list      List the information of the site
  migrate   Migrate your site from other system to Hexo.
  new       Create a new post.
  publish   Moves a draft post from _drafts to _posts folder.
  render    Render files with renderer plugins.
  server    Start the server.
  version   Display version information.

Global Options:
  --config  Specify config file instead of using _config.yml
  --cwd     Specify the CWD
  --debug   Display all verbose messages in the terminal
  --draft   Display draft posts
  --safe    Disable all plugins and scripts
  --silent  Hide output on console

For more help, you can use 'hexo help [command]' for the detailed information
or you can check the docs: http://hexo.io/docs/
ERROR Script load failed: scripts/main.js
ReferenceError: document is not defined
    at Object.defineProperty.value (/Users/jiiiiiin/Documents/Atom/hexo/blog/scripts/main.js:1:532)
    at t (/Users/jiiiiiin/Documents/Atom/hexo/blog/scripts/main.js:1:172)
    at Object.defineProperty.value (/Users/jiiiiiin/Documents/Atom/hexo/blog/scripts/main.js:1:294)
    at t (/Users/jiiiiiin/Documents/Atom/hexo/blog/scripts/main.js:1:172)
    at /Users/jiiiiiin/Documents/Atom/hexo/blog/scripts/main.js:1:252
    at /Users/jiiiiiin/Documents/Atom/hexo/blog/scripts/main.js:1:257
    at /Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/hexo/lib/hexo/index.js:232:12
    at tryCatcher (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/promise.js:638:18)
    at /Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
INFO  Start processing
INFO  Files loaded in 4.46 s
INFO  Generated: atom.xml
INFO  Generated: sitemap.xml
INFO  Generated: content.json
INFO  Generated: about/index.html
INFO  Generated: categories/index.html
INFO  Generated: tags/index.html
INFO  Generated: 404.html
INFO  Generated: 2018/01/27/webpack/webpack实践记录/index.html
INFO  Generated: 2018/01/27/IDE/Atom常用插件记录/index.html
INFO  Generated: 2018/01/28/Git/Git学习资料记录/index.html
INFO  Generated: 2018/01/27/Git/Git常用命令记录/index.html
INFO  Generated: 2018/01/28/Git/Git使用中遇到的问题记录/index.html
INFO  Generated: 2018/01/26/Mac/Mac常用快捷键/index.html
INFO  Generated: 2018/01/26/Mac/Homebrew相关记录/index.html
INFO  Generated: 2018/01/27/IDE/VIM学习记录/index.html
INFO  Generated: 2018/01/26/Mac/Mac上好用的一些小软件/index.html
INFO  Generated: 2018/01/26/Linux/SSH免密登录/index.html
INFO  Generated: 2018/01/25/Android/Android开发常用库记录/index.html
INFO  Generated: 2018/01/25/iTerm2/常用的iTerm2快捷键整理/index.html
INFO  Generated: 2018/01/24/前端/简单构建前端集成开发（Mac Vue -> Ubuntu Nginx）/index.html
INFO  Generated: 2018/01/22/Mac/Mac安装Vagrant相关资料记录/index.html
INFO  Generated: 2018/01/23/Node/Ubuntu环境安装node记录/index.html
INFO  Generated: archives/index.html
INFO  Generated: 2018/01/21/Linux/Ubuntu环境安装Nginx记录/index.html
INFO  Generated: 2018/01/20/Hexo/使用Hexo搭配Github Pages来做笔记本/index.html
INFO  Generated: categories/git/index.html
INFO  Generated: categories/ide/index.html
INFO  Generated: categories/Android/index.html
INFO  Generated: categories/Mac/index.html
INFO  Generated: categories/Linux/index.html
INFO  Generated: categories/nodejs/index.html
INFO  Generated: categories/webpack/index.html
INFO  Generated: categories/Hexo/index.html
INFO  Generated: categories/Nginx/index.html
INFO  Generated: categories/前端/index.html
INFO  Generated: categories/iTerm2/index.html
INFO  Generated: index.html
INFO  Generated: tags/Android/index.html
INFO  Generated: page/2/index.html
INFO  Generated: tags/awesome/index.html
INFO  Generated: tags/ide/index.html
INFO  Generated: tags/Atom/index.html
INFO  Generated: tags/Android-Studio/index.html
INFO  Generated: tags/Hexo/index.html
INFO  Generated: tags/zsh/index.html
INFO  Generated: tags/Ubuntu/index.html
INFO  Generated: tags/Linux/index.html
INFO  Generated: tags/Nginx/index.html
INFO  Generated: tags/Mac/index.html
INFO  Generated: tags/terminal/index.html
INFO  Generated: tags/Vagrant/index.html
INFO  Generated: tags/Homebrew/index.html
INFO  Generated: tags/nodejs/index.html
INFO  Generated: tags/iTerm2/index.html
INFO  Generated: tags/webpack/index.html
INFO  Generated: tags/前端/index.html
INFO  Generated: tags/Git/index.html
INFO  Generated: tags/Vue/index.html
INFO  Generated: tags/git/index.html
INFO  Generated: 2018/01/26/IDE/Atom常用快捷键记录/index.html
INFO  Generated: 2018/01/25/IDE/Android Studio快捷键整理/index.html
INFO  Generated: CNAME
INFO  Generated: avatar/Misaka.jpg
INFO  Generated: assets/loading.svg
INFO  Generated: assets/favicon.ico
INFO  Generated: avatar/kumamon.jpg
INFO  Generated: avatar/favicon.jpg
INFO  Generated: font/Source Sans Pro.woff
INFO  Generated: font/Source Sans Pro.woff2
INFO  Generated: static/api/imgshare/pop_c.gif
INFO  Generated: static/api/imgshare/icons_0_16.png
INFO  Generated: font/Oswald-Regular.ttf
INFO  Generated: font/SourceCodePro-Regular.ttf.woff
INFO  Generated: scripts/main.js
INFO  Generated: static/api/css/share_style1_16.css
INFO  Generated: font/SourceCodePro-Regular.ttf.woff2
INFO  Generated: css/style.css
INFO  Generated: intro/404.jpg
INFO  Generated: static/api/js/base/tangram.js
INFO  Generated: static/api/js/component/anticheat.js
INFO  Generated: static/api/js/component/partners.js
INFO  Generated: static/api/js/component/pop_base.js
INFO  Generated: static/api/js/component/pop_dialog.js
INFO  Generated: static/api/js/component/qrcode.js
INFO  Generated: static/api/js/component/pop_popup.js
INFO  Generated: static/api/js/share/api_base.js
INFO  Generated: static/api/js/share/share_api.js
INFO  Generated: static/api/js/view/share_view.js
INFO  Generated: static/api/js/trans/logger.js
INFO  Generated: static/api/js/trans/trans_weixin.js
INFO  Generated: static/api/js/view/view_base.js
INFO  Generated: static/api/css/share_popup.css
INFO  Generated: static/api/css/weixin_popup.css
INFO  Generated: static/api/js/share.js
INFO  Generated: intro/about-page.jpg
INFO  Generated: intro/intro-desktop.jpg
INFO  Generated: intro/post-bg.jpg
INFO  97 files generated in 526 ms
ERROR Script load failed: scripts/main.js
ReferenceError: document is not defined
    at Object.defineProperty.value (/Users/jiiiiiin/Documents/Atom/hexo/blog/scripts/main.js:1:532)
    at t (/Users/jiiiiiin/Documents/Atom/hexo/blog/scripts/main.js:1:172)
    at Object.defineProperty.value (/Users/jiiiiiin/Documents/Atom/hexo/blog/scripts/main.js:1:294)
    at t (/Users/jiiiiiin/Documents/Atom/hexo/blog/scripts/main.js:1:172)
    at /Users/jiiiiiin/Documents/Atom/hexo/blog/scripts/main.js:1:252
    at /Users/jiiiiiin/Documents/Atom/hexo/blog/scripts/main.js:1:257
    at /Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/hexo/lib/hexo/index.js:232:12
    at tryCatcher (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/promise.js:638:18)
    at /Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
[Browsersync] Access URLs:
 --------------------------------------
          UI: http://localhost:3001
 --------------------------------------
 UI External: http://192.168.43.58:3001
 --------------------------------------
INFO  Start processing
INFO  Hexo is running at http://localhost:4000. Press Ctrl+C to stop.
```

不知道是啥原因？看看 能不能帮忙看看，reop地址：https://github.com/Jiiiiiin/Jiiiiiin.github.io

谢谢

**Comment by NoahDragon** [comment]
Which hexo version you have installed?

BTW `hexo c` is not a supported command for `hexo clean`.

**Comment by tcrowe** [comment]
@Jiiiiiin  `./scripts` is for site-specific plugins:
https://hexo.io/docs/plugins.html#Script
`hexo` is an available global there but not `document`

If you have a content script please move it to `./source` or into your theme then if you need you can use `skip_render` config option to block it from rendering https://hexo.io/docs/configuration.html#Directory

If that solves it please close and thank you!

**Comment by tcrowe** [comment]
@Jiiiiiin I'm closing it out. Please re-open if you're still working on that and my previous post did not help solve it. 👋
