### ISSUE TITLE
Unhandled rejection

### ISSUE THREAD

**Issue by 1W3** [hexojs/hexo#3020]
Hello ,How can fix this is error

`INFO  Start processing
INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.
Unhandled rejection TypeError: /home/pouria/Documents/Gpl/blog/themes/landscape/layout/index.ejs:1
 >> 1| <%- partial('_partial/archive', {pagination: 2, index: true}) %>

/home/pouria/Documents/Gpl/blog/themes/landscape/layout/_partial/archive.ejs:3
    1| <% if (pagination == 2){ %>
    2|   <% page.posts.each(function(post){ %>
 >> 3|     <%- partial('article', {post: post, index: true}) %>
    4|   <% }) %>
    5| <% } else { %>
    6|   <% var last; %>

/home/pouria/Documents/Gpl/blog/themes/landscape/layout/_partial/article.ejs:3
    1| <article id="<%= post.layout %>-<%= post.slug %>" class="article article-type-<%= post.layout %>" itemscope itemprop="blogPost">
    2|   <div class="article-meta">
 >> 3|     <%- partial('post/date', {class_name: 'article-date', date_format: null}) %>
    4|     <%- partial('post/category') %>
    5|   </div>
    6|   <div class="article-inner">

/home/pouria/Documents/Gpl/blog/themes/landscape/layout/_partial/post/date.ejs:2
    1| <a href="<%- url_for(post.path) %>" class="<%= class_name %>">
 >> 2|   <time datetime="<%= date_xml(post.date) %>" itemprop="datePublished"><%= date(post.date, date_format) %></time>
    3| </a>

(name || "").toLowerCase is not a function
    at normalizeName (/home/pouria/Documents/Gpl/blog/node_modules/moment-timezone/moment-timezone.js:375:23)
    at getZone (/home/pouria/Documents/Gpl/blog/node_modules/moment-timezone/moment-timezone.js:396:10)
    at Moment.fn.tz (/home/pouria/Documents/Gpl/blog/node_modules/moment-timezone/moment-timezone.js:554:14)
    at getMoment (/home/pouria/Documents/Gpl/blog/node_modules/hexo/lib/plugins/helper/date.js:12:29)
    at Object.dateHelper (/home/pouria/Documents/Gpl/blog/node_modules/hexo/lib/plugins/helper/date.js:31:16)
    at Object.wrapper [as date] (/home/pouria/Documents/Gpl/blog/node_modules/lodash/lodash.js:4941:19)
    at eval (eval at compile (/home/pouria/Documents/Gpl/blog/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:17:26)
    at returnedFn (/home/pouria/Documents/Gpl/blog/node_modules/ejs/lib/ejs.js:580:17)
    at Theme._View.View._compiledSync (/home/pouria/Documents/Gpl/blog/node_modules/hexo/lib/theme/view.js:122:20)
    at Theme._View.View.View.renderSync (/home/pouria/Documents/Gpl/blog/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/pouria/Documents/Gpl/blog/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper [as partial] (/home/pouria/Documents/Gpl/blog/node_modules/lodash/lodash.js:4941:19)
    at eval (eval at compile (/home/pouria/Documents/Gpl/blog/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:17:17)
    at returnedFn (/home/pouria/Documents/Gpl/blog/node_modules/ejs/lib/ejs.js:580:17)
    at Theme._View.View._compiledSync (/home/pouria/Documents/Gpl/blog/node_modules/hexo/lib/theme/view.js:122:20)
    at Theme._View.View.View.renderSync (/home/pouria/Documents/Gpl/blog/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/pouria/Documents/Gpl/blog/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper [as partial] (/home/pouria/Documents/Gpl/blog/node_modules/lodash/lodash.js:4941:19)
    at eval (eval at compile (/home/pouria/Documents/Gpl/blog/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:15:17)
    at Model._Query.Query.Query.forEach (/home/pouria/Documents/Gpl/blog/node_modules/warehouse/lib/query.js:42:5)
    at eval (eval at compile (/home/pouria/Documents/Gpl/blog/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:12:19)
    at returnedFn (/home/pouria/Documents/Gpl/blog/node_modules/ejs/lib/ejs.js:580:17)
`

Nodejs : v6.11.4
ubuntu :17.10
And _config.yml is the Persian language

**Comment by pzs741** [comment]
问一下，给文章加tags 比如说番茄和鸡蛋 我这么写 tags： 番茄 鸡蛋 或者分开单独写都不行，打击是怎么写的呢？




| |
彭圳生
邮箱：pzsyjsgldd@163.com
|

签名由 网易邮箱大师 定制

On 02/11/2018 20:22, Pouria wrote:

Hello ,How can fix this is error

`INFO Start processing
INFO Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.
Unhandled rejection TypeError: /home/pouria/Documents/Gpl/blog/themes/landscape/layout/index.ejs:1

1| <%- partial('_partial/archive', {pagination: 2, index: true}) %>

/home/pouria/Documents/Gpl/blog/themes/landscape/layout/_partial/archive.ejs:3
1| <% if (pagination == 2){ %>
2| <% page.posts.each(function(post){ %>

3| <%- partial('article', {post: post, index: true}) %>
4| <% }) %>
5| <% } else { %>
6| <% var last; %>

/home/pouria/Documents/Gpl/blog/themes/landscape/layout/_partial/article.ejs:3
1|


2|

3| <%- partial('post/date', {class_name: 'article-date', date_format: null}) %>
4| <%- partial('post/category') %>
5|


6|

/home/pouria/Documents/Gpl/blog/themes/landscape/layout/_partial/post/date.ejs:2
1|

2| <%= date(post.date, date_format) %>
3|

(name || "").toLowerCase is not a function
at normalizeName (/home/pouria/Documents/Gpl/blog/node_modules/moment-timezone/moment-timezone.js:375:23)
at getZone (/home/pouria/Documents/Gpl/blog/node_modules/moment-timezone/moment-timezone.js:396:10)
at Moment.fn.tz (/home/pouria/Documents/Gpl/blog/node_modules/moment-timezone/moment-timezone.js:554:14)
at getMoment (/home/pouria/Documents/Gpl/blog/node_modules/hexo/lib/plugins/helper/date.js:12:29)
at Object.dateHelper (/home/pouria/Documents/Gpl/blog/node_modules/hexo/lib/plugins/helper/date.js:31:16)
at Object.wrapper [as date] (/home/pouria/Documents/Gpl/blog/node_modules/lodash/lodash.js:4941:19)
at eval (eval at compile (/home/pouria/Documents/Gpl/blog/node_modules/ejs/lib/ejs.js:549:12), :17:26)
at returnedFn (/home/pouria/Documents/Gpl/blog/node_modules/ejs/lib/ejs.js:580:17)
at Theme._View.View._compiledSync (/home/pouria/Documents/Gpl/blog/node_modules/hexo/lib/theme/view.js:122:20)
at Theme._View.View.View.renderSync (/home/pouria/Documents/Gpl/blog/node_modules/hexo/lib/theme/view.js:50:21)
at Object.partial (/home/pouria/Documents/Gpl/blog/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
at Object.wrapper [as partial] (/home/pouria/Documents/Gpl/blog/node_modules/lodash/lodash.js:4941:19)
at eval (eval at compile (/home/pouria/Documents/Gpl/blog/node_modules/ejs/lib/ejs.js:549:12), :17:17)
at returnedFn (/home/pouria/Documents/Gpl/blog/node_modules/ejs/lib/ejs.js:580:17)
at Theme._View.View._compiledSync (/home/pouria/Documents/Gpl/blog/node_modules/hexo/lib/theme/view.js:122:20)
at Theme._View.View.View.renderSync (/home/pouria/Documents/Gpl/blog/node_modules/hexo/lib/theme/view.js:50:21)
at Object.partial (/home/pouria/Documents/Gpl/blog/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
at Object.wrapper [as partial] (/home/pouria/Documents/Gpl/blog/node_modules/lodash/lodash.js:4941:19)
at eval (eval at compile (/home/pouria/Documents/Gpl/blog/node_modules/ejs/lib/ejs.js:549:12), :15:17)
at Model._Query.Query.Query.forEach (/home/pouria/Documents/Gpl/blog/node_modules/warehouse/lib/query.js:42:5)
at eval (eval at compile (/home/pouria/Documents/Gpl/blog/node_modules/ejs/lib/ejs.js:549:12), :12:19)
at returnedFn (/home/pouria/Documents/Gpl/blog/node_modules/ejs/lib/ejs.js:580:17)
`

Nodejs : v6.11.4
ubuntu :17.10
And _config.yml is the Persian language
