### ISSUE TITLE
进行部署时候出现错误，该如何解决？

### ISSUE THREAD

**Issue by forget1** [hexojs/hexo#3043]
> 当我使用`hexo d`进行博客的部署时，控制台出现如图所示的错误，请问这是什么原因导致的呢？我该如何进行解决呢？

![](http://owklx3f60.bkt.clouddn.com//18-2-23/29642138.jpg)

**Comment by JoeJoeyMa** [comment]
请查看在目录内_config.yml文件里的github地址是否填写正确，最好把内文件po出来方便进一步查看是什么问题

**Comment by forget1** [comment]
```

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/forget1/forget1.github.io.git
  branch: master
  
search:
  path: search.xml
  filed: post
  format: html
  limit: 10000


live2d:
  model: miku
  bottom: -60
```
> 这个是_comfig.yml中的相关代码，GitHub的地址填写没有出现错误。

**Comment by xiaotan828** [comment]
@forget1 我刚刚也遇到了跟你一样的问题，也不知道怎么解决！

**Comment by xiaotan828** [comment]
最近大家都出现了这个问题，https://superuser.com/questions/1297583/git-push-failing-with-fatal-httprequestexception-encountered    不是咱们的问题，看一下这个，TLS 1.0停用了

**Comment by JLHwung** [comment]
可以尝试以下设置：
```
deploy:
  type: git
  repo: git@github.com:forget1/forget1.github.io.git
  branch: master
```

**Comment by xiaotan828** [comment]
@JLHwung 最好能把这个页面置顶以下什么的，很多人应该都会遇到这个问题

**Comment by forget1** [comment]
好的，我试一下



发自我的小米手机在 Huáng Jùnliàng <notifications@github.com>，2018年2月23日 21:35写道：可以尝试以下设置：
deploy:
  type: git
  repo: git@github.com:forget1/forget1.github.io.git
  branch: master


—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/hexojs/hexo","title":"hexojs/hexo","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/hexojs/hexo"}},"updates":{"snippets":[{"icon":"PERSON","message":"@JLHwung in #3043: 可以尝试以下设置：\r\n```\r\ndeploy:\r\n  type: git\r\n  repo: git@github.com:forget1/forget1.github.io.git\r\n  branch: master\r\n```"}],"action":{"name":"View Issue","url":"https://github.com/hexojs/hexo/issues/3043#issuecomment-368010294"}}}

**Comment by vimcaw** [comment]
@JLHwung 改完还是报错
```yml
deploy:
  type: git
  repo: git@github.com:vimcaw/blog.git
  branch: master
```
```cmd
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

    at ChildProcess.<anonymous> (C:\Users\vimcaw\Documents\GitHub\blog\node_modules\hexo-util\lib\spawn.js:37:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at ChildProcess.cp.emit (C:\Users\vimcaw\Documents\GitHub\blog\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
FATAL Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Error: Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

    at ChildProcess.<anonymous> (C:\Users\vimcaw\Documents\GitHub\blog\node_modules\hexo-util\lib\spawn.js:37:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at ChildProcess.cp.emit (C:\Users\vimcaw\Documents\GitHub\blog\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

Process finished with exit code 2
```

**Comment by JLHwung** [comment]
@vimcaw What's the output of
```shell
ssh -v git@github.com
```
?
And how `github.com` is resolved?
```
nslookup github.com
```

**Comment by breakingcoder** [comment]
you can try command :  "git config --global credential.helper wincred" in git bash terminal

**Comment by steve-yuan-8276** [comment]
@xiaotan828   我 也遇到这个问题，请问在mac下如何解决呢？

**Comment by xiaotan828** [comment]
@steve-yuan-8276 你可以在[这里](https://github.com/Microsoft/Git-Credential-Manager-for-Mac-and-Linux/releases)尝试安装Git Credential Manager for Mac，理论上重新安装最新版git也能解决

**Comment by yyangMr** [comment]
windows把repo改为git@github.com:forget1/forget1.github.io.git解决了，谢谢

**Comment by YuanAaron** [comment]
windows10 repo:git@github.com:forget1/forget1.github.io.git，problem solved,thanks!

**Comment by zhangliao-legend** [comment]
请问一下各位大佬，为什么把repo那一行改成repo:git@github.com:forget1/forget1.github.io.git就可以了呢？

**Comment by ligj1706** [comment]
![image](https://user-images.githubusercontent.com/44646119/96325323-7a9a5300-1059-11eb-9bcb-c0b65330f4fa.png)

尝试了很多方法仍然无法解决，MAC上大家如何解决的呢？

**Comment by yiyayamaya** [comment]
> windows把repo改为[git@github.com](mailto:git@github.com):forget1/forget1.github.io.git解决了，谢谢

可用！

**Comment by maxpbs** [comment]
很神奇，我只是重新修改了SSH（并没有更改存储库），保存配置文件后重启了命令行再运行就部署成功了

**Comment by stevenjoezhang** [comment]
@maxpbs 这种一般就是网络连接问题，GitHub有时候可以SSH直连，就可以部署成功了
