### ISSUE TITLE
Cannot read property 'nodes' of undefined when processing css/style.css

### ISSUE THREAD

**Issue by cmpute** [hexojs/hexo#3058]
## Environment Info

Node version(`node -v`): v8.9.4

Your site `_config.yml` (Optional): 

Your theme `_config.yml` (Optional): use default landscape

Hexo and Plugin version(`npm ls --depth 0`): 
```
+-- hexo@3.6.0
+-- hexo-all-minifier@0.2.6
+-- hexo-deployer-git@0.3.1
+-- hexo-generator-archive@0.1.5
+-- hexo-generator-category@0.1.3
+-- hexo-generator-feed@1.2.2
+-- hexo-generator-index@0.2.1
+-- hexo-generator-sitemap@1.2.0
+-- hexo-generator-tag@0.2.0
+-- hexo-minecraft-templates@0.2.1
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-marked@0.3.2
+-- hexo-renderer-stylus@0.3.3
`-- hexo-server@0.2.2
```

## For BUG

Just run `hexo g`, the log shows
```
...
08:02:01.700 INFO  Generated: sitemap.xml
08:02:01.702 INFO  Generated: atom.xml
08:02:01.935 ERROR Asset render failed: css/style.css
TypeError: D:\#Blog\Blog\hexo\themes\landscape\source\css\style.styl:19:59
   15| @font-face
   16|   font-family: FontAwesome
   17|   font-style: normal
   18|   font-weight: normal
   19|   src: url(font-icon-path + ".eot?v=#" + font-icon-version)
-----------------------------------------------------------------^
   20|   src: url(font-icon-path + ".eot?#iefix&v=#" + font-icon-version) format("embedded-opentype"),
   21|        url(font-icon-path + ".woff?v=#" + font-icon-version) format("woff"),
   22|        url(font-icon-path + ".ttf?v=#" + font-icon-version) format("truetype"),

Cannot read property 'nodes' of undefined

    at Evaluator.vendors (D:\#Blog\Blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:1567:32)
    at Evaluator.unvendorize (D:\#Blog\Blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:1581:30)
    at Evaluator.visitCall (D:\#Blog\Blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:484:24)
    at Evaluator.Visitor.visit (D:\#Blog\Blog\hexo\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (D:\#Blog\Blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitExpression (D:\#Blog\Blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:644:26)
    at Evaluator.Visitor.visit (D:\#Blog\Blog\hexo\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (D:\#Blog\Blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitProperty (D:\#Blog\Blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:687:22)
    at Evaluator.Visitor.visit (D:\#Blog\Blog\hexo\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (D:\#Blog\Blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitBlock (D:\#Blog\Blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:720:39)
    at Evaluator.Visitor.visit (D:\#Blog\Blog\hexo\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (D:\#Blog\Blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitAtrule (D:\#Blog\Blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:754:41)
    at Evaluator.Visitor.visit (D:\#Blog\Blog\hexo\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (D:\#Blog\Blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitRoot (D:\#Blog\Blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:707:27)
    at Evaluator.Visitor.visit (D:\#Blog\Blog\hexo\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (D:\#Blog\Blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.evaluate (D:\#Blog\Blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:247:15)
    at Renderer.render (D:\#Blog\Blog\hexo\node_modules\stylus\lib\renderer.js:86:26)
...
```

I found this problem first when I use the theme next, then I changed back to landscape and the problem remains.

**Comment by NoahDragon** [comment]
Have you tried to `hexo clean` then `hexo g`?

**Comment by cmpute** [comment]
@NoahDragon Yes. Same problem.
