### ISSUE TITLE
possible bug?

### ISSUE THREAD

**Issue by joejztang** [hexojs/hexo#3073]
## Environment Info

Node version(`node -v`): 8.10.0

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 
├── hexo@3.6.0
├── hexo-generator-archive@0.1.5
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.1
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.3.1
├── hexo-renderer-marked@0.3.2
├── hexo-renderer-stylus@0.3.3
└── hexo-server@0.2.2

## For BUG

way to reproduce: insert the following into your .md file

```
* templates tagging and inheritance

firstly in apps `urls.py`, we need to set a namespace. `app_name = <your_app_name>`

see documentation

`{% block body_block %} {% endblock %}`

`{% extend <your_base_html_file> %}`

* django filter

say you want to display all capital letters in one page and display all lower letters in another page, that is why we use filters.

see documentation `django templates`

`{{ value| filter: "parameter" }}`

`{% load my_templates %}`

```

go ahead and `hexo clean` and `hexo g`

it will give you the following:

```
Template render error: unknown block tag: extend
    at Object._prettifyError (/Users/jizhoutang/Documents/TechBlog/node_modules/nunjucks/src/lib.js:35:11)
    at Template.render (/Users/jizhoutang/Documents/TechBlog/node_modules/nunjucks/src/environment.js:526:21)
    at Environment.renderString (/Users/jizhoutang/Documents/TechBlog/node_modules/nunjucks/src/environment.js:364:17)
    at Promise (/Users/jizhoutang/Documents/TechBlog/node_modules/hexo/lib/extend/tag.js:66:9)
    at Promise._execute (/Users/jizhoutang/Documents/TechBlog/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/Users/jizhoutang/Documents/TechBlog/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/jizhoutang/Documents/TechBlog/node_modules/bluebird/js/release/promise.js:79:10)
    at Tag.render (/Users/jizhoutang/Documents/TechBlog/node_modules/hexo/lib/extend/tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (/Users/jizhoutang/Documents/TechBlog/node_modules/hexo/lib/hexo/post.js:260:16)
    at Promise.then.then.result (/Users/jizhoutang/Documents/TechBlog/node_modules/hexo/lib/hexo/render.js:65:19)
    at tryCatcher (/Users/jizhoutang/Documents/TechBlog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/jizhoutang/Documents/TechBlog/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/jizhoutang/Documents/TechBlog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/jizhoutang/Documents/TechBlog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/jizhoutang/Documents/TechBlog/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/jizhoutang/Documents/TechBlog/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/jizhoutang/Documents/TechBlog/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/jizhoutang/Documents/TechBlog/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)

```

At first I think it was my settings of the site, but right now I am suspicious of the module the hexo use has some bug.

To me what I wrote is legitimate markdown sentence. And previous(2 years ago) it has ever run with no issue.

**Comment by NoahDragon** [comment]
It because of the `{% extend <your_base_html_file> %}` recognized as a tag in Hexo https://hexo.io/docs/tag-plugins.html . You could try to escape the `{%` and `{{` characters.
