### ISSUE TITLE
想删除文章，本地删除之后执行hexo clean报错

### ISSUE THREAD

**Issue by CfortWang** [hexojs/hexo#3097]
## Environment Info

Node version(`node -v`): v6.11.3

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 
+-- hexo@3.3.9
+-- hexo-deployer-git@0.3.1
+-- hexo-generator-archive@0.1.4
+-- hexo-generator-baidu-sitemap@0.1.2
+-- hexo-generator-category@0.1.3
+-- hexo-generator-feed@1.2.2
+-- hexo-generator-index@0.2.1
+-- hexo-generator-search@2.1.1
+-- hexo-generator-sitemap@1.2.0
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-marked@0.3.0
+-- hexo-renderer-stylus@0.3.3
+-- hexo-server@0.2.2
`-- hexo-wordcount@3.0.2

npm ERR! invalid: hexo-generator-baidu-sitemap@0.0.8 D:\blog\node_modules\hexo-generator-baidu-sitemap\node_modules\hexo-generator-baidu-sitemap

## For question

想删除文章，本地删除之后执行hexo clean报错，报错如下：
FATAL can not read an implicit mapping pair; a colon is missed at line 74, column 17:
       path atom.xml
                    ^
YAMLException: can not read an implicit mapping pair; a colon is missed at line 74, column 17:
       path atom.xml
                    ^
    at generateError (D:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:165:10)
    at throwError (D:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:171:9)
    at readBlockMapping (D:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1037:11)
    at composeNode (D:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1332:12)
    at readBlockMapping (D:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1062:11)
    at composeNode (D:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1332:12)
    at readDocument (D:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1492:3)
    at loadDocuments (D:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1548:5)
    at Object.load (D:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1569:19)
    at Hexo.yamlHelper (D:\blog\node_modules\hexo\lib\plugins\renderer\yaml.js:7:15)
    at Hexo.tryCatcher (D:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (D:\blog\node_modules\bluebird\js\release\method.js:15:34)
    at D:\blog\node_modules\hexo\lib\hexo\render.js:61:21
    at tryCatcher (D:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\blog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\blog\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (D:\blog\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (D:\blog\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (D:\blog\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:672:20)
博客有挺久时间没管了有点生疏，希望能帮忙解决，谢谢！

**Comment by JLHwung** [comment]
> can not read an implicit mapping pair; a colon is missed at line 74, column 17

找到 `_config.yaml` 第74行第10个字符，加上冒号。
```
path: atom.xml
```
