### ISSUE TITLE
Cannot set property 'lastIndex' of undefined

### ISSUE THREAD

**Issue by MurasakiSeiFu** [hexojs/hexo#3128]
My hexo is always running perfectly.
But today, I write a new blog by hexo-admin .
 when I run $ hexo g
Error in background：

(node:18224) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: TypeError: Cannot set property 'lastIndex' of undefined
    at Object._prettifyError (/Users/murasakiseifu/blog/node_modules/nunjucks/src/lib.js:35:11)
    at /Users/murasakiseifu/blog/node_modules/nunjucks/src/environment.js:547:19
    at Template.root [as rootRenderFunc] (eval at _compile (/Users/murasakiseifu/blog/node_modules/nunjucks/src/environment.js:617:18), <anonymous>:43:3)
    at Template.render (/Users/murasakiseifu/blog/node_modules/nunjucks/src/environment.js:540:10)
    at Environment.renderString (/Users/murasakiseifu/blog/node_modules/nunjucks/src/environment.js:364:17)
    at Promise (/Users/murasakiseifu/blog/node_modules/hexo/lib/extend/tag.js:66:9)
    at Promise._execute (/Users/murasakiseifu/blog/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/Users/murasakiseifu/blog/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/murasakiseifu/blog/node_modules/bluebird/js/release/promise.js:79:10)
    at Tag.render (/Users/murasakiseifu/blog/node_modules/hexo/lib/extend/tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (/Users/murasakiseifu/blog/node_modules/hexo/lib/hexo/post.js:230:16)
    at Promise.then.then.result (/Users/murasakiseifu/blog/node_modules/hexo/lib/hexo/render.js:65:19)
    at tryCatcher (/Users/murasakiseifu/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/murasakiseifu/blog/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/murasakiseifu/blog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/murasakiseifu/blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/murasakiseifu/blog/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/murasakiseifu/blog/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/murasakiseifu/blog/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/murasakiseifu/blog/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)

Please help me.... Thanks a lot !!!!

**Comment by tcrowe** [comment]
Hello @MurasakiSeiFu 🤔 

Can you search your project for "lastIndex" that shows up in the error message? It says template error.

You can open your JS file to find more info:
`/Users/murasakiseifu/blog/node_modules/nunjucks/src/lib.js:35:11`

You can try upgrading all your modules to see if that helps:

```sh
npm install --global npm-check-updates
ncu -an
npm install
```
