### ISSUE TITLE
Unable deploy to GitHub private rope

### ISSUE THREAD

**Issue by mashirozx** [hexojs/hexo#3136]
## Environment Info

```
hexo: 3.7.1
hexo-cli: 1.1.0
os: Windows_NT 10.0.16299 win32 x64
http_parser: 2.7.0
node: 8.9.1
v8: 6.1.534.47
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2m
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
```

Your site `_config.yml` (Optional):

```
# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/mashirozx/Next.git
  branch: master
```

Hexo and Plugin version(`npm ls --depth 0`): 

```
+-- gulp@3.9.1
+-- gulp-htmlclean@2.7.22
+-- gulp-htmlmin@4.0.0
+-- gulp-minify-css@1.2.4
+-- gulp-uglify@3.0.0
+-- hexo@3.7.1
+-- hexo-deployer-git@0.3.1
+-- hexo-generator-archive@0.1.5
+-- hexo-generator-category@0.1.3
+-- hexo-generator-feed@1.2.2
+-- hexo-generator-index@0.2.1
+-- hexo-generator-searchdb@1.0.8
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-marked@0.3.2
+-- hexo-renderer-stylus@0.3.3
`-- hexo-server@0.2.2
```

## For BUG

Unable to push via `https://github.com/mashirozx/Next.git`

It shows: 
```shell
On branch master
nothing to commit, working tree clean
fatal: HttpRequestException encountered.
   An error occurred while sending the request.
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': No error
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: fatal: HttpRequestException encountered.
   An error occurred while sending the request.
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': No error

    at ChildProcess.<anonymous> (C:\WorkDirectory\GitHub\Next\node_modules\hexo-util\lib\spawn.js:37:17)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at ChildProcess.cp.emit (C:\WorkDirectory\GitHub\Next\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
PS C:\WorkDirectory\GitHub\Next> nodejs -v
nodejs : The term 'nodejs' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.
At line:1 char:1
+ nodejs -v
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (nodejs:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Also I tried using `git@github.com:mashirozx/Next.git`

But I'm unable to input `y` in Windows CMD/PowerShell here:
![image](https://user-images.githubusercontent.com/16148054/39257249-af2efa66-48e3-11e8-9fd5-7047550c5347.png)

## For question

1. Am I able to deploy with a GitHub private rope?
2. If use SSH method, how to input letter `y` on Windows? 😂

**Comment by tcrowe** [comment]
Good day @mashirozx 👋 

Is there any way you can run openssh ssh-agent on Windows and add your ssh key on github?

Alternatively sometimes auth can be done over https like this:
`https://user:pass@github.com/mashirozx/Next.git`

My apologies if you've already tried these and it didn't work.

**Comment by mashirozx** [comment]
@tcrowe Well, `https://user:pass@github.com/mashirozx/Next.git` works, thank you! :laughing:

**Comment by tcrowe** [comment]
Hooray! 😀
