### ISSUE TITLE
deploy to git fails

### ISSUE THREAD

**Issue by m4sterbunny** [hexojs/hexo#3149]
Windows 10 Pro
Node version(`node -v`): v8.11.1

`_config.yml`:
plugins: git

theme: landscape

# Deployment
deploy:
  type: git
  repo: http://github.com/m4sterbunny/m4sterbunny.github.io
  message: new-deploy-success

Hexo and Plugin version(`npm ls --depth 0`): 
hexo@3.7.1
+-- hexo-deployer-git@0.3.1
+-- hexo-generator-archive@0.1.5
+-- hexo-generator-category@0.1.3
+-- hexo-generator-index@0.2.1
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-marked@0.3.2
+-- hexo-renderer-stylus@0.3.3
`-- hexo-server@0.2.2

## Error Report

<!--
REPORT
 C:\Users\bunny\coding-journey>hexo deploy
INFO  Deploying: git
INFO  Clearing .deploy_git folder...
INFO  Copying files from public folder...
INFO  Copying files from extend dirs...
'git' is not recognized as an internal or external command,
operable program or batch file.
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: spawn git ENOENT
    at notFoundError (C:\Users\bunny\coding-journey\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (C:\Users\bunny\coding-journey\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (C:\Users\bunny\coding-journey\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

**Comment by m4sterbunny** [comment]
Have I perhaps mucked up the configuration of the _yml file (one indent used for the type/repo and message)?
