### ISSUE TITLE
hexo init blogs 报错/usr/lib/node_modules/hexo-cli/lib/hexo.js:13 

### ISSUE THREAD

**Issue by Tmanman123** [hexojs/hexo#3154]
hexo init blogs

/usr/lib/node_modules/hexo-cli/lib/hexo.js:13
class HexoNotFoundError extends Error {}
^^^^^
SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/hexo-cli/bin/hexo:5:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

已经试验过两个服务器，结果都是一样的。

**Comment by JLHwung** [comment]
As node.js 4 is going to EOL, hexo does not support node.js version below 6, please upgrade node.js to the latest version. You can go to https://nodejs.org/en/ to download the latest node.js.
