### ISSUE TITLE
 Cannot find module postinstall-build when init

### ISSUE THREAD

**Issue by StrickerLee** [hexojs/hexo#3164]
## Environment Info

Ubuntu 18.04 LTS x64

Node version(`node -v`):

v8.10.0

## For question

Error when using `hexo init myblog`

````
> nunjucks@3.1.3 postinstall /root/myblog/node_modules/nunjucks
> node postinstall-build.js src

module.js:549
    throw err;
    ^

Error: Cannot find module '/root/myblog/node_modules/nunjucks/postinstall-build.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

````

**Comment by StrickerLee** [comment]
It works when I use another user instead of root.
