### ISSUE TITLE
Hexo-NexT Blog on github pages go blank after deploying

### ISSUE THREAD

**Issue by Janegao011919** [hexojs/hexo#3166]
## Environment Info

Node version(`node -v`):
$ node -v
v8.11.2

$ npm -v
5.6.0

$ cat package.json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.7.1"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-asset-image": "0.0.3",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0",
    "hexo-wordcount": "^3.0.2"
  }
}
$ hexo -v
hexo: 3.7.1
hexo-cli: 1.1.0
os: Windows_NT 10.0.16299 win32 x64
http_parser: 2.8.0
node: 8.11.2
v8: 6.2.414.54
uv: 1.19.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.29.0
napi: 3
openssl: 1.0.2o
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
Your site `_config.yml` (Optional):
#Site
title: Jtalks
subtitle: 简聊
description: 
keywords:
author: Jane Gao
language: zh-Hans
timezone:

#URL
##If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://janegao011919.github.io/Jtalks.github.io 
root: /Jtalks.github.io/
permalink: :year/:month/:day/:title/
permalink_defaults:

#Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

#Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
#Home page setting
#path: Root path for your blogs index page. (default = '')
#per_page: Posts displayed per page. (0 = disable pagination)
#order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
#Category & Tag
default_category: uncategorized
category_map:
tag_map:

#Date / Time format
##Hexo uses Moment.js to parse and display date
##You can customize the date format as defined in
##http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

#Pagination
##Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

#Extensions
##Plugins: https://hexo.io/plugins/
##Themes: https://hexo.io/themes/
theme: next

#Deployment
##Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/Janegao011919/Jtalks.github.io.git
  branch: master

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 

## For BUG

Tried $ hexo s --debug:
`svg
10:50:30.538 DEBUG Generator: page
10:50:30.538 DEBUG Generator: post
10:50:30.538 DEBUG Generator: category
10:50:30.538 DEBUG Generator: archive
10:50:30.538 DEBUG Generator: index
10:50:30.538 DEBUG Generator: feed
10:50:30.538 DEBUG Generator: tag
10:50:30.540 DEBUG Generator: asset
10:50:30.547 WARN  =============================================================                                ==
10:50:30.547 WARN  ========================= ATTENTION! ========================                                ==
10:50:30.547 WARN  =============================================================                                ==
10:50:30.547 WARN   NexT repository is moving here: https://github.com/theme-nex                                t
10:50:30.548 WARN  =============================================================                                ==
10:50:30.548 WARN   It's rebase to v6.0.0 and future maintenance will resume the                                re
10:50:30.548 WARN  =============================================================                                ==
10:50:30.550 INFO  Hexo is running at http://localhost:4000/Jtalks.github.io/. P                                ress Ctrl+C to stop.
10:50:30.564 DEBUG Database saved
10:50:36.668 DEBUG Rendering archive: archives/index.html
Unhandled rejection Error: ENOENT: no such file or directory, open 'D:\软件\My R                                epository\{Jtalks}\themes\next\layout\_scripts\schemes\.swig'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.ret.load (D:\软件\My Repository\{Jtalks}\node_modules\swig-templat                                es\lib\loaders\filesystem.js:55:15)
    at exports.Swig.compileFile (D:\软件\My Repository\{Jtalks}\node_modules\swi                                g-templates\lib\swig.js:694:31)
    at Object.eval [as tpl] (eval at precompile (D:\软件\My Repository\{Jtalks}\                                node_modules\swig-templates\lib\swig.js:497:13), <anonymous>:476:18)
    at compiled (D:\软件\My Repository\{Jtalks}\node_modules\swig-templates\lib\                                swig.js:618:18)
    at Theme._View.View._compiled.locals [as _compiled] (D:\软件\My Repository\{                                Jtalks}\node_modules\hexo\lib\theme\view.js:124:48)
    at Theme._View.View.View.render (D:\软件\My Repository\{Jtalks}\node_modules                                \hexo\lib\theme\view.js:29:15)
    at route.set (D:\软件\My Repository\{Jtalks}\node_modules\hexo\lib\hexo\inde                                x.js:386:29)
    at tryCatcher (D:\软件\My Repository\{Jtalks}\node_modules\bluebird\js\relea                                se\util.js:16:23)
    at D:\软件\My Repository\{Jtalks}\node_modules\bluebird\js\release\method.js                                :15:34
    at RouteStream._read (D:\软件\My Repository\{Jtalks}\node_modules\hexo\lib\h                                exo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:442:10)
    at resume_ (_stream_readable.js:822:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
GET /Jtalks.github.io/archives/ - - ms - -
10:52:36.675 DEBUG Rendering archive: archives/index.html
Unhandled rejection Error: ENOENT: no such file or directory, open 'D:\软件\My Repository\{Jtalks}\themes\next\layout\_scripts\schemes\.swig'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.ret.load (D:\软件\My Repository\{Jtalks}\node_modules\swig-templates\lib\loaders\filesystem.js:55:15)
    at exports.Swig.compileFile (D:\软件\My Repository\{Jtalks}\node_modules\swig-templates\lib\swig.js:694:31)
    at Object.eval [as tpl] (eval at precompile (D:\软件\My Repository\{Jtalks}\node_modules\swig-templates\lib\swig.js:497:13), <anonymous>:476:18)
    at compiled (D:\软件\My Repository\{Jtalks}\node_modules\swig-templates\lib\swig.js:618:18)
    at Theme._View.View._compiled.locals [as _compiled] (D:\软件\My Repository\{Jtalks}\node_modules\hexo\lib\theme\view.js:124:48)
    at Theme._View.View.View.render (D:\软件\My Repository\{Jtalks}\node_modules\hexo\lib\theme\view.js:29:15)
    at route.set (D:\软件\My Repository\{Jtalks}\node_modules\hexo\lib\hexo\index.js:386:29)
    at tryCatcher (D:\软件\My Repository\{Jtalks}\node_modules\bluebird\js\release\util.js:16:23)
    at D:\软件\My Repository\{Jtalks}\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\软件\My Repository\{Jtalks}\node_modules\hexo\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:442:10)
    at resume_ (_stream_readable.js:822:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
GET /Jtalks.github.io/archives/ - - ms - -
10:54:36.676 DEBUG Rendering archive: archives/index.html
Unhandled rejection Error: ENOENT: no such file or directory, open 'D:\软件\My Repository\{Jtalks}\themes\next\layout\_scripts\schemes\.swig'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.ret.load (D:\软件\My Repository\{Jtalks}\node_modules\swig-templates\lib\loaders\filesystem.js:55:15)
    at exports.Swig.compileFile (D:\软件\My Repository\{Jtalks}\node_modules\swig-templates\lib\swig.js:694:31)
    at Object.eval [as tpl] (eval at precompile (D:\软件\My Repository\{Jtalks}\node_modules\swig-templates\lib\swig.js:497:13), <anonymous>:476:18)
    at compiled (D:\软件\My Repository\{Jtalks}\node_modules\swig-templates\lib\swig.js:618:18)
    at Theme._View.View._compiled.locals [as _compiled] (D:\软件\My Repository\{Jtalks}\node_modules\hexo\lib\theme\view.js:124:48)
    at Theme._View.View.View.render (D:\软件\My Repository\{Jtalks}\node_modules\hexo\lib\theme\view.js:29:15)
    at route.set (D:\软件\My Repository\{Jtalks}\node_modules\hexo\lib\hexo\index.js:386:29)
    at tryCatcher (D:\软件\My Repository\{Jtalks}\node_modules\bluebird\js\release\util.js:16:23)
    at D:\软件\My Repository\{Jtalks}\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\软件\My Repository\{Jtalks}\node_modules\hexo\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:442:10)
    at resume_ (_stream_readable.js:822:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
10:55:51.852 INFO  See you again
10:55:51.911 DEBUG Database saved

## For question

Some clues I found according to the results above:
`Unhandled rejection Error: ENOENT: no such file or directory, open 'D:\软件\My R                                epository\{Jtalks}\themes\next\layout\_scripts\schemes\.swig'`

6. I know my workflow is a mess. Really appreciate if you could give me some advice. I read the 《Pro Git》file several times. But since the Hexo and the theme file NexT are all frameworks with their own commands. It's hard to figure which file to"$ git add" exactly. So I just 
`$ hexo clean
$ hexo g
$ hexo s --debug
$ hexo d` 
every time. Sometimes after $ hexo s, the page doesn't work on localhost, but $ hexo d works.  So I just got careless and my blog is down.

**Comment by legendarynacar** [comment]
@Janegao011919 Firstly, check your commits to find the problem if it is related to you. And you can even roleback.

I should remind you that, when you test something try to wipe all blog data and push first. Then add the eddited blog data and push it. Remember, do your testings on your test repo like I do. Open and org and tweak your site on org github page.

I used this command to follow : 
`hexo clean --debug && hexo generate --debug && hexo deploy --debug`
__________________________
I wanna give a different explanation on this.

I got the same issue while trying to add an html5 landing template and move my blog to sub folder. I thought the issue was related to template but while doing tests, I found out that it was not. I think hexo it self has this problem.

Test repo : https://github.com/lnctf/lnctf.github.io
Test site : https://lnctf.github.io
You can check the commits of mine as well for proof.

Using NeXT theme

### Test 1 : testing if my blog is working as normal on main folder.
Edited Hexo's _config.yml as :
```yml
url: https://lnctf.github.io/
root: /
```
Used this command to generate and follow the verbose : 
`hexo clean --debug && hexo generate --debug && hexo deploy --debug`

Then copied public/* files&folders into my repository and pushed it.

It worked.


### Test 2 : testing subfolder with same blog settings etc.

Edited Hexo's _config.yml as :
```yml
url: https://lnctf.github.io/blog
root: /blog/
```

Used this command to generate and follow the verbose : 
`hexo clean --debug && hexo generate --debug && hexo deploy --debug`

Then copied public/* files&folders into my repository and pushed it.

It did not worked.  And it is still like that. You can check it https://lnctf.github.io/blog/

Importing thing to notice is that, elements are being created. And if you hover the mouse on correct location, you can still click and surf inside of website.

I hope you can fix || find solution to this.

**Comment by legendarynacar** [comment]
Btw @Janegao011919 on the log you can see that NeXT theme repository was moved.

New account is : https://github.com/theme-next/

New repo is : https://github.com/theme-next/hexo-theme-next

**Comment by Janegao011919** [comment]
@legendarynacar Thank you so much! Still trying to understand — still lots to learn

**Comment by legendarynacar** [comment]
Is it fixed?
