### ISSUE TITLE
update pandoc then failed hexo g

### ISSUE THREAD

**Issue by Jarvis-K** [hexojs/hexo#3177]
## Environment Info

Node version(`node -v`):v10.3.0
 
pandoc version:v2.2.1
## For BUG

1. I just use brew update all libraries,then pandoc version goes to 2.2.1,`hexo g` went wrong
2. the error msg is 

```
NFO  [hexo-math] Using engine 'mathjax'
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: pandoc exited with code 2: --smart/-S has been removed.  Use +smart or -smart extension instead.
For example: pandoc -f markdown+smart -t markdown-smart.
Try pandoc --help for more information.

    at ChildProcess.<anonymous> (/Users/jarvis/Documents/myBlog/node_modules/hexo-renderer-pandoc/index.js:73:20)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close [as _onclose] (net.js:596:12)
```
if i changed the `--smart` to `-smart ` ,then other bugs would happen.

**Comment by Jarvis-K** [comment]
sorry , i just tried `npm install hexo-renderer-pandoc --save`
then  the bug disappear.maybe  because the `hexo-renderer-pandoc` be removed incidently.

**Comment by sli1989** [comment]
any attemps more?
