### ISSUE TITLE
hexo d 报错，没有权限

### ISSUE THREAD

**Issue by hanxiao6** [hexojs/hexo#3197]
因为之前尝试一下双ssh的配置，我今天提交了下hexo，就报错了

Please make sure you have the correct access rights
and the repository exists.

    at ChildProcess.<anonymous> (F:\life\Blog\node_modules\hexo-util\lib\spawn.js:37:17)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at ChildProcess.cp.emit (F:\life\Blog\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:545:12)

当我使用ssh时，
$ ssh -T git@github.com
Warning: Permanently added the RSA host key for IP address '13.250.177.223' to the list of known hosts.
Hi hanxiao6! You've successfully authenticated, but GitHub does not provide shell access.

所以我不知道怎么解决

**Comment by hanxiao6** [comment]
我尝试了重置rsa，但是没有作用。

**Comment by shizhihuaxu** [comment]
同问，我使用ssh -T git@github.com可以显示成功的信息，并且deploy配置如下：
deploy:
  type: git
  repo: git@github.com:shizhihuaxu/shizhihuaxu.github.io.git
  branch: master
空格问题也注意过了，
https和git两种方式都使用过了，
本地拉取shizhihuaxu.github.io这个仓库代码也能获取到
就是提示没有权限这个错误
hexo 3.2.0
node 8.11.3
git 2.18.0

**Comment by shizhihuaxu** [comment]
我忘记在哪个issue里看到的解决办法了，下载一个这个安装上试试，我试了一整天安装后终于提交上去了

**Comment by shizhihuaxu** [comment]
我忘记在哪个issue里看到的解决办法了，下载一个这个安装上试试，https://github.com/Microsoft/Git-Credential-Manager-for-Windows/releases/tag/v1.14.0 我试了一整天安装后终于提交上去了
