### ISSUE TITLE
hexo deploy经常卡死 最后抛出 OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 10054,上传成功概率很低

### ISSUE THREAD

**Issue by boold** [hexojs/hexo#3221]
在环境配置上面确定是正确的
## Environment Info
Your theme `_config.yml` (Optional): 
next
Hexo and Plugin version(`npm ls --depth 0`): 

hexo: 3.7.1
hexo-cli: 1.1.0
os: Windows_NT 10.0.17134 win32 ia32
http_parser: 2.7.0
node: 9.4.0
v8: 6.2.414.46-node.17
uv: 1.18.0
zlib: 1.2.11
ares: 1.13.0
modules: 59
nghttp2: 1.29.0
openssl: 1.0.2n
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c

## For BUG
无法hexo deploy
会抛出错误
```
INFO  Deploying: git
INFO  Clearing .deploy_git folder...
INFO  Copying files from public folder...
INFO  Copying files from extend dirs...
[master 361f892] Site updated: 2018-07-30 15:30:30
 17 files changed, 103 insertions(+), 103 deletions(-)
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
error: RPC failed; curl 56 OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 10054
Everything up-to-date
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
error: RPC failed; curl 56 OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 10054
Everything up-to-date

    at ChildProcess.<anonymous> (G:\vkcyan\blog\node_modules\hexo-util\lib\spawn.js:37:17)
    at ChildProcess.emit (events.js:160:13)
    at ChildProcess.cp.emit (G:\vkcyan\blog\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
```
配置是没问题的,第一次配置好deploy成功过一两次,后面基本上失败
hexo d -debug的信息
```
INFO  Start processing                                                
WARN  =============================================================== 
WARN  ========================= ATTENTION! ========================== 
WARN  =============================================================== 
WARN   NexT repository is moving here: https://github.com/theme-next  
WARN  =============================================================== 
WARN   It's rebase to v6.0.0 and future maintenance will resume there 
WARN  =============================================================== 
INFO  Files loaded in 860 ms                                          
INFO  0 files generated in 5.84 s                                     
INFO  Start processing                                                
WARN  =============================================================== 
WARN  ========================= ATTENTION! ========================== 
WARN  =============================================================== 
WARN   NexT repository is moving here: https://github.com/theme-next  
WARN  =============================================================== 
WARN   It's rebase to v6.0.0 and future maintenance will resume there 
WARN  =============================================================== 
INFO  Files loaded in 514 ms                                          
INFO  0 files generated in 5.8 s                                      
INFO  Start processing                                                
WARN  =============================================================== 
WARN  ========================= ATTENTION! ========================== 
WARN  =============================================================== 
WARN   NexT repository is moving here: https://github.com/theme-next  
WARN  =============================================================== 
WARN   It's rebase to v6.0.0 and future maintenance will resume there 
WARN  =============================================================== 
INFO  Files loaded in 501 ms                                          
INFO  0 files generated in 5.98 s                
                     `
```

## For feature request
请各位大佬说说解决办法 这每天都deploy不上去体验感很差劲

**Comment by NaraLuwan** [comment]
@vkcyan 你好，我也遇到同样的问题，请问最后是怎么解决的？
