### ISSUE TITLE
deploy problem/ deploy 问题

### ISSUE THREAD

**Issue by Adam1679** [hexojs/hexo#3223]
**Issue: cannot deploy

Error description:
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: warning: redirecting to https://github.com/Adam1679/Adam.github.io.git/
error: RPC failed; curl 55 SSL_write() returned SYSCALL, errno = 32
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date

    at ChildProcess.<anonymous> (/Users/adam/Adam1679.github.io/node_modules/hexo-util/lib/spawn.js:37:17)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)**

Background Infomation:
1. node version: v8.11.3
2. npm ls --depth 0
hexo-site@0.0.0 /Users/adam/Adam1679.github.io
├── hexo@3.7.1
├── hexo-deployer-git@0.3.1
├── hexo-generator-archive@0.1.5
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.1
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.3.1
├── hexo-renderer-marked@0.3.2
├── hexo-renderer-stylus@0.3.3
└── hexo-server@0.2.2

3. _config.yml:
# Hexo Configuration
## Source: https://github.com/hexojs/hexo/

# Site
title: Work is in your heart!
subtitle: Hello, World!
description:
keywords:
author: Adam Zhang
language: zh-Hans
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: http://github.com/Adam1679/Adam.github.io.git 
  branch: master

**Comment by tcrowe** [comment]
Hey @Adam1679 :wave:

Try this:

```yaml
deploy:
  type: git
  repo: git@github.com:Adam1679/Adam.github.io.git
  branch: master
```

Can you tell me if that works?

**Comment by fortunato-all** [comment]
@tcrowe omg, it truly works!!!
