### ISSUE TITLE
Accessing hexo variables using pug template

### ISSUE THREAD

**Issue by kankyu** [hexojs/hexo#3228]
## Environment Info

Node version(`node -v`):
v10.6.0

Hexo and Plugin version(`npm ls --depth 0`): 
├── hexo@3.7.1
├── hexo-browsersync@0.3.0
├── hexo-generator-archive@0.1.5
├── hexo-generator-category@0.1.3
├── hexo-generator-feed@1.2.2
├── hexo-generator-index@0.2.1
├── hexo-generator-sitemap@1.2.0
├── hexo-generator-tag@0.2.0
├── hexo-render-pug@2.0.0
├── hexo-renderer-ejs@0.3.1
├── hexo-renderer-marked@0.3.2
├── hexo-renderer-scss@1.2.0
├── hexo-renderer-stylus@0.3.3
├── hexo-server@0.2.2
└── include-media@1.4.9

What I want to do:
In a pug template file I want to look at the hexo variables' properties and methods.

Based on https://github.com/hexojs/hexo/issues/2974 I tried to use pre #{JSON.stringify(site)}

In my page.pug I have written:
```
extends _partial/layout
block content
    p Page.pug
    pre #{JSON.stringify(site)}
```

## Error output
```
0:39:45.485 DEBUG Rendering page: Projects/index.html
Unhandled rejection TypeError: themes/mytheme/layout/page.pug:5
    3| block content
    4|     p Page.pug
  > 5|     pre #{JSON.stringify(site)}

Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at eval (eval at wrap (/Users/Andrew/miminal/miminal-hexo/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:43:62)
    at template (eval at wrap (/Users/Andrew/miminal/miminal-hexo/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:45:72)
    at pugRenderer (/Users/Andrew/miminal/miminal-hexo/node_modules/hexo-render-pug/lib/renderer.js:12:26)
    at Hexo.<anonymous> (/Users/Andrew/miminal/miminal-hexo/node_modules/hexo-render-pug/index.js:11:10)
    at Hexo.tryCatcher (/Users/Andrew/miminal/miminal-hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Users/Andrew/miminal/miminal-hexo/node_modules/bluebird/js/release/method.js:15:34)
    at Promise.then.text (/Users/Andrew/miminal/miminal-hexo/node_modules/hexo/lib/hexo/render.js:61:21)
    at tryCatcher (/Users/Andrew/miminal/miminal-hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/Andrew/miminal/miminal-hexo/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/Andrew/miminal/miminal-hexo/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/Users/Andrew/miminal/miminal-hexo/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/Users/Andrew/miminal/miminal-hexo/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/Users/Andrew/miminal/miminal-hexo/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/Andrew/miminal/miminal-hexo/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)

```

Help would be much appreciated :)

**Comment by kankyu** [comment]
I've also tried

```
script.
        console.log(site)
```
I get the error: 
ReferenceError: site is not defined[Learn More] Projects:1:1
<anonymous>
http://localhost:4000/Projects/:1:1

**Comment by kankyu** [comment]
Update: I have found a way to access the hexo variables through the output when the hexo server is running locally using `- console.log(hexo_variable)`
