### ISSUE TITLE
兄弟们，我从next主题切换到别人自定义的主题后报错Template render error: (unknown path) [Line 1, Column 2]   unknown block tag: cq

### ISSUE THREAD

**Issue by booboom** [hexojs/hexo#3272]
```
$ hexo s
(node:80924) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: (unknown path) [Line 1, Column 2]
  unknown block tag: cq
    at Object._prettifyError (/Users/admin/Documents/baomer/node_modules/nunjucks/src/lib.js:36:11)
    at Template.render (/Users/admin/Documents/baomer/node_modules/nunjucks/src/environment.js:524:21)
    at Environment.renderString (/Users/admin/Documents/baomer/node_modules/nunjucks/src/environment.js:362:17)
    at Promise (/Users/admin/Documents/baomer/node_modules/hexo/lib/extend/tag.js:66:9)
    at Promise._execute (/Users/admin/Documents/baomer/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/Users/admin/Documents/baomer/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/admin/Documents/baomer/node_modules/bluebird/js/release/promise.js:79:10)
    at Tag.render (/Users/admin/Documents/baomer/node_modules/hexo/lib/extend/tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (/Users/admin/Documents/baomer/node_modules/hexo/lib/hexo/post.js:230:16)
    at Promise.then.then.result (/Users/admin/Documents/baomer/node_modules/hexo/lib/hexo/render.js:65:19)
    at tryCatcher (/Users/admin/Documents/baomer/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/admin/Documents/baomer/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/admin/Documents/baomer/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/admin/Documents/baomer/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/admin/Documents/baomer/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/admin/Documents/baomer/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/admin/Documents/baomer/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/admin/Documents/baomer/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5) 
```

**Comment by YoshinoriN** [comment]
@booboom 

I can't read chinese. But, I think maybe below issue is same problem.
Please use below issue if for your information.

> https://github.com/iissnan/hexo-theme-next/issues/1348

**Comment by cliuyang** [comment]
He means when changing the theme from NexT to others, there are some errors. Emmmm,  I am not sure if I have expressed it clearly.

**Comment by monkeyWzr** [comment]
@YoshinoriN He changed theme from NexT to other theme and error occurred. That's because NexT has a costum tag `{% cq %}` `{% endcq %}`. He used that tag somewhere in his post so when changing to other theme hexo could not render the tag. Delete the cq tags in his post will work. 
The referenced issue seems different :-D

兄弟你用NexT的时候肯定是在某一篇博客里面使用了 `{% cq %}` `{% endcq %}`标签。这是NexT自定义的标签，切换到其他主题之后hexo处理不了这种标签了。找一下那个标签删掉就可以了。

**Comment by booboom** [comment]
谢谢大家，问题解决了，是hexo-tag的原因，之前写文章的时候用的很多都是next自带的tag，所以别的主题没发识别，thanks @YoshinoriN @monkeyWzr @cliuyang
