### ISSUE TITLE
Hexo fails to install with Node 10.13.0

### ISSUE THREAD

**Issue by alanosman** [hexojs/hexo#3348]
## Environment Info
Node version(`node -v`):
v10.13.0

Running on Ubuntu under Windows WSL

## For BUG
```
npm install03:34:27 {master} ~/elastc-help$ npm install

> node-sass@4.7.2 install /mnt/d/elastc-help/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.7.2/linux-x64-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.7.2/linux-x64-64_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> git-validate@2.2.2 install /mnt/d/elastc-help/node_modules/codacy-coverage/node_modules/nsp/node_modules/git-validate
> node bin/install


> base62@1.2.7 postinstall /mnt/d/elastc-help/node_modules/base62
> node scripts/install-stats.js || exit 0


> nunjucks@3.1.2 postinstall /mnt/d/elastc-help/node_modules/nunjucks
> node postinstall-build.js src


> node-sass@4.7.2 postinstall /mnt/d/elastc-help/node_modules/node-sass
> node scripts/build.js

Building: /home/aosman/.nvm/versions/node/v10.13.0/bin/node /mnt/d/elastc-help/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/home/aosman/.nvm/versions/node/v10.13.0/bin/node',
gyp verb cli   '/mnt/d/elastc-help/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@10.13.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.15rc1\n"
gyp verb get node dir no --target version specified, falling back to host node version: 10.13.0
gyp verb command install [ '10.13.0' ]
gyp verb install input version string "10.13.0"
gyp verb install installing version: 10.13.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 10.13.0
gyp verb build dir attempting to create "build" dir: /mnt/d/elastc-help/node_modules/node-sass/build
gyp verb build dir "build" dir needed to be created? /mnt/d/elastc-help/node_modules/node-sass/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /mnt/d/elastc-help/node_modules/node-sass/build/config.gypi
gyp verb config.gypi checking for gypi file: /mnt/d/elastc-help/node_modules/node-sass/config.gypi
gyp verb common.gypi checking for gypi file: /mnt/d/elastc-help/node_modules/node-sass/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/mnt/d/elastc-help/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/mnt/d/elastc-help/node_modules/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/mnt/d/elastc-help/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/aosman/.node-gyp/10.13.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/aosman/.node-gyp/10.13.0',
gyp info spawn args   '-Dnode_gyp_dir=/mnt/d/elastc-help/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/aosman/.node-gyp/10.13.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/mnt/d/elastc-help/node_modules/node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /home/aosman/.node-gyp/10.13.0
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/mnt/d/elastc-help/node_modules/node-sass/build'
  g++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/home/aosman/.node-gyp/10.13.0/include/node -I/home/aosman/.node-gyp/10.13.0/src -I/home/aosman/.node-gyp/10.13.0/deps/uv/include -I/home/aosman/.node-gyp/10.13.0/deps/v8/include -I../../nan  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -MMD -MF ./Release/.deps/Release/obj.target/binding/src/binding.o.d.raw   -c -o Release/obj.target/binding/src/binding.o ../src/binding.cpp
In file included from ../src/binding.cpp:3:0:
../src/sass_context_wrapper.h:8:10: fatal error: sass/context.h: No such file or directory
 #include <sass/context.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.
binding.target.mk:110: recipe for target 'Release/obj.target/binding/src/binding.o' failed
make: *** [Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory '/mnt/d/elastc-help/node_modules/node-sass/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/mnt/d/elastc-help/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.4.0-17134-Microsoft
gyp ERR! command "/home/aosman/.nvm/versions/node/v10.13.0/bin/node" "/mnt/d/elastc-help/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /mnt/d/elastc-help/node_modules/node-sass
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN elastc-help@0.1.0 No repository field.
npm WARN elastc-help@0.1.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.7.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/aosman/.npm/_logs/2018-11-12T20_37_59_303Z-debug.log
```

**Comment by tomap** [comment]
I don't believe this has anything to do with hexo. 
It is more related to a node-saas issue: https://github.com/sass/node-sass/issues/2536

Could you provide your package.json ?

**Comment by alanosman** [comment]
Hi @tomap, here's my package.json.  It's a pretty vanilla setup.

```
{
  "name": "elastc-help",
  "version": "0.1.0",
  "scripts": {},
  "hexo": {
    "version": "3.7.1"
  },
  "dependencies": {
    "dress-code": "^2.4.0",
    "eslint": "^4.19.1",
    "hexo": "^3.7.1",
    "hexo-deployer-git": "^0.3.1",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-less": "^0.2.0",
    "hexo-renderer-marked": "^0.3.2",
    "hexo-renderer-sass": "^0.3.2",
    "hexo-server": "^0.3.2",
    "hexo-theme-doc": "1.0.0-rc.1"
  }
}
```

**Comment by YoshinoriN** [comment]
I cant' reproduce this error at node v8.11.3 & 10.13.0
Also I used your `package.json`.

It seems some people [reported some same error](https://www.google.com/search?hl=en&source=hp&ei=BK_sW_KHI9GroATEq6a4Aw&q=sass%2Fcontext.h%3A+No+such+file+or+directory&oq=sass%2Fcontext.h%3A+No+such+file+or+directory&gs_l=psy-ab.3..35i39k1j0.735.735.0.1071.2.1.0.0.0.0.125.125.0j1.1.0....0...1.1.64.psy-ab..1.1.124.0...0.aPVFNx1pjYc) to node-sass repository.
Colud you please try to check them ?

**Comment by JLHwung** [comment]
@tomap The culprit is that `node-sass@^4.5.3` is locked to `4.7.2` due to `package-lock.json` or `yarn.lock`.

As you have updated node to latest version, you should also update `node-sass` since it is a native bindings with prebuilt binaries on specific V8 versions.

If you are using yarn, please run
```
yarn add node-sass
```

If you are using npm, please run
```
npm add node-sass
```

**Comment by alanosman** [comment]
@JLHwung @tomap indeed the culprit was `package-lock.json`.  I still don't know the real benefit of that file.  Anyway. thanks for the pointers.  That was not obvious!

**Comment by JLHwung** [comment]
@alanosman No. It is not related to the distributed `package-lock.json`. npm will [ignore](https://docs.npmjs.com/files/package-lock.json) any package-lock in the distributed package. The package-lock.json is generated per project.

Every consumer of `node-sass` will have to run [`npm rebuild`](https://docs.npmjs.com/cli/rebuild) on updating node.js since it is a C++ addon. So this issue is technically, irrelevant to hexo.

> Maybe you should not distribute with package-lock.json?

Yes, we will ignore package-lock only to shrink the size of distributed tarball.
