### ISSUE TITLE
如何使用非默认ssh key

### ISSUE THREAD

**Issue by lluxury** [hexojs/hexo#3461]
我的环境上有多个ssh密钥,默认名字不是id_rsa

请问如何修改配置可以正常使用

现象
hexo d

无文件要提交，干净的工作区
ERROR: Permission to yannweb/yann_web.git denied to test1.
fatal: 无法读取远程仓库。

请确认您有正确的访问权限并且仓库存在。
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: Spawn failed
    at ChildProcess.<anonymous> (C:\_data\blog_web\node_modules\hexo-util\lib\spawn.js:52:19)
    at ChildProcess.emit (events.js:180:13)
    at ChildProcess.cp.emit (C:\_data\blog_web\node_modules\cross-spawn\lib\enoent.js:40:29)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)

我需要test2用户证书,但程序会默认使用 test1的

我觉得应该像 ssh -i ~/.ssh/test2 git@github.com 这样建立ssh链接

**Comment by roastduckcd** [comment]
看看这样行不行
在本地配置`~/.ssh/config`, 添加
```
Host github.com   
   HostName github.com  
   PreferredAuthentications publickey
   IdentityFile ~/.ssh/github_deploy_rsa   # 对应的私钥文件路径
```
前提是已经在网站配置了相应的公钥。
