### ISSUE TITLE
hexo-admin 配置后，输入用户名，密码后 登录后 hexo报错退出

### ISSUE THREAD

**Issue by yh11971** [hexojs/hexo#3469]
/data/blog/node_modules/serve-static/index.js:121
      next()
      ^

TypeError: next is not a function
    at SendStream.error (/data/blog/node_modules/serve-static/index.js:121:7)
    at emitOne (events.js:116:13)
    at SendStream.emit (events.js:211:7)
    at SendStream.error (/data/blog/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/data/blog/node_modules/send/index.js:421:12)
    at onstat (/data/blog/node_modules/send/index.js:727:26)
    at FSReqWrap.oncomplete (fs.js:152:21)

**Comment by YoshinoriN** [comment]
Depulicate #3470
