### ISSUE TITLE
安装hexo-admin 点击编辑hexo报错退出

### ISSUE THREAD

**Issue by yh11971** [hexojs/hexo#3470]
TypeError: next is not a function
    at /data/blog/node_modules/hexo-admin/api.js:318:25
    at /data/blog/node_modules/hexo-admin/api.js:141:7
    at call (/data/blog/node_modules/connect/index.js:239:7)
    at next (/data/blog/node_modules/connect/index.js:183:5)
    at next (/data/blog/node_modules/connect/index.js:161:14)
    at next (/data/blog/node_modules/connect/index.js:161:14)
    at next (/data/blog/node_modules/connect/index.js:161:14)
    at next (/data/blog/node_modules/connect/index.js:161:14)
    at next (/data/blog/node_modules/connect/index.js:161:14)
    at next (/data/blog/node_modules/connect/index.js:161:14)
    at next (/data/blog/node_modules/connect/index.js:161:14)
    at next (/data/blog/node_modules/connect/index.js:161:14)
    at jsonParser (/data/blog/node_modules/body-parser/lib/types/json.js:110:7)
    at call (/data/blog/node_modules/connect/index.js:239:7)
    at next (/data/blog/node_modules/connect/index.js:183:5)
    at SendStream.error (/data/blog/node_modules/serve-static/index.js:121:7)
    at emitOne (events.js:116:13)
    at SendStream.emit (events.js:211:7)
    at SendStream.error (/data/blog/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/data/blog/node_modules/send/index.js:421:12)
    at next (/data/blog/node_modules/send/index.js:736:16)
    at onstat (/data/blog/node_modules/send/index.js:725:14)

**Comment by YoshinoriN** [comment]
Seems [this issue](https://github.com/jaredly/hexo-admin/issues/111).
Perhaps hexo-admin issue. Thanks :)
