### ISSUE TITLE
hexo s "Template render error" on this specific article

### ISSUE THREAD

**Issue by HarborZeng** [hexojs/hexo#3485]
**Note that, I have tried at Marked Demo, and version greater and equal than 0.2.7 can properly parse the md text**

below is the unparsable md code:

```markdown
| 模板                              | 描述                                                         |

| --------------------------------- | ------------------------------------------------------------ |
| `{{ .Branch }}`                   | 正在构建中的VCS分支名                                        |
| `{{ .BuildNum }}`                 | 此构建的CircleCI作业编号                                     |
| `{{ .Revision }}`                 | 目前正在构建VCS修订版本号                                    |
| `{{ .Environment.variableName }}` | 环境变量`variableName`                                       |
| `{{ checksum "filename" }}`       | 给定文件名内容的base64编码SHA256哈希，考虑使用依赖性清单，例如`package-lock.json`，`pom.xml`或`project.clj`。 |
| `{{ epoch }}`                     | 自00:00:00 UTC 以来经过的秒数                                |
| `{{ arch }}`                      | OS和CPU信息                                                  |
```

## Environment Info

Node version(`node -v`): v10.13.0

Hexo and Plugin version(`npm ls --depth 0`): 

+-- hexo@3.8.0
+-- hexo-baidu-url-submit@0.0.6
+-- hexo-clean-css@0.0.3
+-- hexo-deployer-git@1.0.0
+-- hexo-generator-archive@0.1.5
+-- hexo-generator-category@0.1.3
+-- hexo-generator-index@0.2.1
+-- hexo-generator-search@2.4.0
+-- hexo-generator-sitemap@1.2.0
+-- hexo-generator-tag@0.2.0
+-- hexo-lazyload-image-modified@1.0.6
+-- hexo-photoswipe@1.5.3
+-- hexo-prism-plugin@2.3.0
+-- hexo-reference-updated@1.0.5
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-marked@0.3.2
+-- hexo-renderer-sass@0.3.2
+-- hexo-renderer-stylus@0.3.3
+-- hexo-server@0.3.3
+-- hexo-translate-title-modified@1.0.11
`-- hexo-wordcount@6.0.1

## For BUG

add this specific article to _post dir, and run `hexo s --debug`, got some err in console:

```console
14:39:58.773 DEBUG Writing database to C:\Users\zengxg\hexo-tellyouwhat/db.json
14:39:58.792 DEBUG Hexo version: 3.8.0
14:39:58.793 DEBUG Working directory: ~\hexo-tellyouwhat\
14:39:58.945 DEBUG Config loaded: ~\hexo-tellyouwhat\_config.yml
14:39:58.980 DEBUG Plugin loaded: hexo-baidu-url-submit
14:39:59.091 DEBUG Plugin loaded: hexo-clean-css
14:39:59.183 DEBUG Plugin loaded: hexo-deployer-git
14:39:59.188 DEBUG Plugin loaded: hexo-generator-archive
14:39:59.190 DEBUG Plugin loaded: hexo-generator-sitemap
14:39:59.193 DEBUG Plugin loaded: hexo-generator-category
14:39:59.195 DEBUG Plugin loaded: hexo-generator-index
14:39:59.197 DEBUG Plugin loaded: hexo-generator-search
14:39:59.199 DEBUG Plugin loaded: hexo-generator-tag
14:40:00.220 DEBUG Plugin loaded: hexo-photoswipe
14:40:00.265 DEBUG Plugin loaded: hexo-lazyload-image-modified
14:40:00.468 DEBUG Plugin loaded: hexo-prism-plugin
14:40:00.531 DEBUG Plugin loaded: hexo-reference-updated
14:40:00.539 DEBUG Plugin loaded: hexo-renderer-marked
14:40:00.545 DEBUG Plugin loaded: hexo-renderer-ejs
14:40:00.577 DEBUG Plugin loaded: hexo-renderer-sass
14:40:00.579 DEBUG Plugin loaded: hexo-renderer-stylus
14:40:00.669 DEBUG Plugin loaded: hexo-server
14:40:00.941 DEBUG Plugin loaded: hexo-translate-title-modified
14:40:00.943 DEBUG Plugin loaded: hexo-wordcount
14:40:00.957 DEBUG Script loaded: scripts\events.js
14:40:00.961 DEBUG Loading database.
14:40:01.091 INFO  Start processing
14:40:01.122 DEBUG Processed: CNAME
14:40:01.133 DEBUG Processed: manifest.json
14:40:01.136 DEBUG Processed: google9dee8b8a6358ecc8.html
14:40:01.137 DEBUG Processed: robots.txt
14:40:01.173 DEBUG Processed: _posts/2018年秋招掌阅面经.md
14:40:01.174 DEBUG Processed: _posts/2分钟教你做安卓单纯的二维码识别，不涉及实时取景扫描.md
14:40:01.174 DEBUG Processed: _posts/MySQL如何按表创建千万级的测试数据，进行数据库压力测试和练习.md
14:40:01.175 DEBUG Processed: _posts/PWA踩坑记-从零到一让你的博客也能离线访问.md
14:40:01.175 DEBUG Processed: _posts/UML统一建模语言期末考试复习资料试卷.md
14:40:01.176 DEBUG Processed: _posts/Windows下常用的网络配置命令浅析.md
14:40:01.178 DEBUG Processed: _posts/android跳转到MIUI神隐模式详细设置界面.md
14:40:01.179 DEBUG Processed: _posts/个人开发者使用微信支付做打赏捐赠.md
14:40:01.179 DEBUG Processed: _posts/为什么是静态博客.md
14:40:01.179 DEBUG Processed: _posts/互联网程序设计期末考试复习资料指南.md
14:40:01.180 DEBUG Processed: _posts/人机交互期末考试复习.md
14:40:01.180 DEBUG Processed: _posts/利用python写一个爬虫爬取京东商品评论分析情感倾向并绘制词云.md
14:40:01.180 DEBUG Processed: _posts/基于智能手表感知的人体运动状态深度识别.md
14:40:01.181 DEBUG Processed: _posts/如何使用Java优雅的破解维吉尼亚密码.md
14:40:01.181 DEBUG Processed: _posts/如何使用Java手写实现一个RSA加密算法.md
14:40:01.181 DEBUG Processed: _posts/如何使用python做syn-flood攻击的实验.md
14:40:01.181 DEBUG Processed: _posts/如何搭配一个无与伦比的主题.md
14:40:01.182 DEBUG Processed: _posts/如何给腾讯云服务器的域名配置SSL证书，给自己的网站上https.md
14:40:01.182 DEBUG Processed: _posts/我的一点关于人生活法想法.md
14:40:01.182 DEBUG Processed: _posts/操作系统期末考试复习资料卷子.md
14:40:01.183 DEBUG Processed: _posts/新版中日交流标准日本语单词.md
14:40:01.184 DEBUG Processed: _posts/新秀语言go：Golang入门语法知识点总结.md
14:40:01.184 DEBUG Processed: _posts/机器学习tensorflow-keras之保存和恢复模型h5py.md
14:40:01.185 DEBUG Processed: _posts/机器学习tensorflow-keras之如何优雅的从上次断掉的地方继续训练.md
14:40:01.185 DEBUG Processed: _posts/机器学习tensorflow-keras之影评文本分类.md
14:40:01.185 DEBUG Processed: _posts/机器学习tensorflow-keras之过拟合，欠拟合实验详解.md
14:40:01.186 DEBUG Processed: _posts/机器学习tensorflow-keras之训练首个神经网络：对服饰图像基本分类.md
14:40:01.186 DEBUG Processed: _posts/机器学习tensorflow-keras之预测汽车燃油效率-回归问题.md
14:40:01.186 DEBUG Processed: _posts/浅论12306网上购票系统的设计.md
14:40:01.186 DEBUG Processed: _posts/第一个静态博客告你日记.md
14:40:01.187 DEBUG Processed: _posts/系统管理与维护复习资料期末考试.md
14:40:01.187 DEBUG Processed: _posts/网络安全与保密基本概念考试复习.md
14:40:01.187 DEBUG Processed: _posts/网络安全与保密复习资料照片.md
14:40:01.188 DEBUG Processed: _posts/网络工程课程实践实验之利用WireShark分析IP协议.md
14:40:01.188 DEBUG Processed: _posts/网络工程课程实践实验之利用pcattcp分析TCP协议.md
14:40:01.188 DEBUG Processed: _posts/网络工程课程实践实验之观察一个轻量级网络.md
14:40:01.188 DEBUG Processed: _posts/计算机组成原理期末考试往届复习资料卷子.md
14:40:01.189 DEBUG Processed: _posts/计算机网络作业之常用命令ping-tracert-ipconfig-nbtstat-route和arp.md
14:40:01.189 DEBUG Processed: _posts/计算机网络实验作业windows下网络命令的理解：netsh-arp-nslookup.md
14:40:01.189 DEBUG Processed: _posts/计算机网络期末考试复习资料.md
14:40:01.190 DEBUG Processed: _posts/计算机网络期末考试复习资料卷子.md
14:40:01.190 DEBUG Processed: _posts/软件工程复习资料卷子.md
14:40:01.190 DEBUG Processed: _posts/软件测试白盒黑盒路径测试期末考试卷子复习资料.md
14:40:01.191 DEBUG Processed: _posts/通过Xposed的hook机制探究加固的app的密码盐值实战.md
14:40:01.191 DEBUG Processed: _posts/项目管理期末考试复习资料卷子.md
14:40:01.211 DEBUG Processed: _drafts/人工神经网络机器学习的基础概念：为什么是神经网络.md
14:40:01.212 DEBUG Processed: about/index.md
14:40:01.213 DEBUG Processed: categories/index.md
14:40:01.216 DEBUG Processed: tags/index.md
14:40:01.219 DEBUG Processed: source/128x128-logo.png
14:40:01.219 DEBUG Processed: source/144x144-logo.png
14:40:01.220 DEBUG Processed: source/152x152-logo.png
14:40:01.220 DEBUG Processed: source/192x192-logo.png
14:40:01.221 DEBUG Processed: source/512x512-logo.png
14:40:01.221 DEBUG Processed: source/256x256-logo.png
14:40:01.221 DEBUG Processed: source/favicon.png
14:40:01.240 DEBUG Processed: source/css/gitment.css
14:40:01.241 DEBUG Processed: source/css/my-gitalk.css
14:40:01.243 DEBUG Processed: source/css/my.css
14:40:01.244 DEBUG Processed: source/js/matery.js
14:40:01.244 DEBUG Processed: source/medias/avatar.jpg
14:40:01.245 DEBUG Processed: source/js/search.js
14:40:01.248 DEBUG Processed: source/medias/logo.svg
14:40:01.271 DEBUG Theme config loaded.
14:40:01.275 DEBUG Processed: _config.yml
14:40:01.275 DEBUG Processed: _posts/如何更新CircleCI的缓存.md
14:40:01.276 DEBUG Processed: source/css/matery.css
14:40:01.277 DEBUG Processed: source/medias/cover.jpg
14:40:01.295 DEBUG Processed: layout/about.ejs
14:40:01.296 DEBUG Processed: layout/archive.ejs
14:40:01.297 DEBUG Processed: layout/categories.ejs
14:40:01.297 DEBUG Processed: layout/category.ejs
14:40:01.297 DEBUG Processed: layout/index.ejs
14:40:01.298 DEBUG Processed: layout/layout.ejs
14:40:01.303 DEBUG Processed: languages/default.yml
14:40:01.303 DEBUG Processed: languages/zh-CN.yml
14:40:01.304 DEBUG Processed: source/medias/banner/5.jpg
14:40:01.304 DEBUG Processed: source/medias/featureimages/0.jpg
14:40:01.305 DEBUG Processed: source/medias/featureimages/10.jpg
14:40:01.305 DEBUG Processed: source/medias/featureimages/11.jpg
14:40:01.306 DEBUG Processed: source/medias/featureimages/13.jpg
14:40:01.306 DEBUG Processed: source/medias/featureimages/15.jpg
14:40:01.307 DEBUG Processed: source/medias/featureimages/18.jpg
14:40:01.307 DEBUG Processed: source/medias/featureimages/19.jpg
14:40:01.308 DEBUG Processed: source/medias/featureimages/2.jpg
14:40:01.309 DEBUG Processed: source/medias/featureimages/20.jpg
14:40:01.309 DEBUG Processed: source/medias/featureimages/21.jpg
14:40:01.310 DEBUG Processed: source/medias/featureimages/23.jpg
14:40:01.310 DEBUG Processed: source/medias/featureimages/3.jpg
14:40:01.312 DEBUG Processed: source/medias/featureimages/4.jpg
14:40:01.312 DEBUG Processed: source/medias/featureimages/5.jpg
14:40:01.313 DEBUG Processed: source/medias/featureimages/6.jpg
14:40:01.315 DEBUG Processed: source/medias/featureimages/8.jpg
14:40:01.316 DEBUG Processed: source/medias/featureimages/7.jpg
14:40:01.317 DEBUG Processed: source/medias/featureimages/9.jpg
14:40:01.318 DEBUG Processed: source/libs/animate/animate.min.css
14:40:01.318 DEBUG Processed: source/libs/aos/aos.css
14:40:01.319 DEBUG Processed: source/medias/reward/wechat.png
14:40:01.320 DEBUG Processed: source/medias/reward/alipay.png
14:40:01.321 DEBUG Processed: source/libs/aos/aos.js
14:40:01.321 DEBUG Processed: source/libs/gitalk/gitalk.css
14:40:01.322 DEBUG Processed: source/libs/cryptojs/crypto-js.min.js
14:40:01.322 DEBUG Processed: source/libs/gitment/gitment-default.css
14:40:01.323 DEBUG Processed: source/libs/jqcloud/jqcloud.css
14:40:01.323 DEBUG Processed: source/libs/jqcloud/jqcloud-1.0.4.min.js
14:40:01.324 DEBUG Processed: source/libs/masonry/masonry.pkgd.min.js
14:40:01.324 DEBUG Processed: source/libs/others/busuanzi.pure.mini.js
14:40:01.325 DEBUG Processed: source/libs/others/clicklove.js
14:40:01.326 DEBUG Processed: source/libs/photoswipe/photoswipe.css
14:40:01.326 DEBUG Processed: source/libs/photoswipe/photoswipe-ui-default.js
14:40:01.327 DEBUG Processed: source/libs/photoswipe/photoswipe-ui-default.min.js
14:40:01.327 DEBUG Processed: source/libs/photoswipe/photoswipe.min.js
14:40:01.327 DEBUG Processed: source/libs/scrollprogress/scrollProgress.min.js
14:40:01.328 DEBUG Processed: source/libs/tocbot/tocbot.css
14:40:01.328 DEBUG Processed: source/libs/tocbot/tocbot.min.js
14:40:01.351 DEBUG Processed: layout/post.ejs
14:40:01.351 DEBUG Processed: layout/tag.ejs
14:40:01.351 DEBUG Processed: layout/tags.ejs
14:40:01.353 DEBUG Processed: source/medias/banner/0.jpg
14:40:01.353 DEBUG Processed: source/medias/banner/2.jpg
14:40:01.354 DEBUG Processed: source/medias/banner/1.jpg
14:40:01.354 DEBUG Processed: source/medias/banner/3.jpg
14:40:01.355 DEBUG Processed: source/medias/banner/6.jpg
14:40:01.355 DEBUG Processed: source/medias/featureimages/1.jpg
14:40:01.355 DEBUG Processed: source/medias/featureimages/12.jpg
14:40:01.356 DEBUG Processed: source/medias/featureimages/14.jpg
14:40:01.356 DEBUG Processed: source/medias/featureimages/16.jpg
14:40:01.357 DEBUG Processed: source/medias/featureimages/17.jpg
14:40:01.357 DEBUG Processed: source/medias/featureimages/22.jpg
14:40:01.357 DEBUG Processed: source/libs/gitment/gitment.js
14:40:01.358 DEBUG Processed: source/libs/jquery/jquery-2.2.0.min.js
14:40:01.358 DEBUG Processed: source/libs/photoswipe/photoswipe.js
14:40:01.359 DEBUG Processed: source/libs/valine/Valine.min.js
14:40:01.376 DEBUG Processed: layout/_partial/footer.ejs
14:40:01.377 DEBUG Processed: layout/_partial/bg-cover.ejs
14:40:01.378 DEBUG Processed: layout/_partial/gitment.ejs
14:40:01.378 DEBUG Processed: layout/_partial/back-top.ejs
14:40:01.379 DEBUG Processed: layout/_partial/disqus.ejs
14:40:01.379 DEBUG Processed: layout/_partial/gitalk.ejs
14:40:01.380 DEBUG Processed: layout/_partial/github-link.ejs
14:40:01.380 DEBUG Processed: layout/_partial/head.ejs
14:40:01.380 DEBUG Processed: layout/_partial/google-analytics.ejs
14:40:01.381 DEBUG Processed: layout/_partial/livere.ejs
14:40:01.381 DEBUG Processed: layout/_partial/header.ejs
14:40:01.381 DEBUG Processed: layout/_partial/mobile-nav.ejs
14:40:01.382 DEBUG Processed: layout/_partial/navigation.ejs
14:40:01.382 DEBUG Processed: layout/_partial/paging.ejs
14:40:01.382 DEBUG Processed: layout/_partial/photoswipe.ejs
14:40:01.383 DEBUG Processed: layout/_partial/post-cover.ejs
14:40:01.383 DEBUG Processed: layout/_partial/post-detail-toc.ejs
14:40:01.384 DEBUG Processed: layout/_partial/post-statis.ejs
14:40:01.384 DEBUG Processed: layout/_partial/post-detail.ejs
14:40:01.386 DEBUG Processed: layout/_partial/reward.ejs
14:40:01.386 DEBUG Processed: layout/_partial/social-link.ejs
14:40:01.387 DEBUG Processed: layout/_partial/share.ejs
14:40:01.387 DEBUG Processed: layout/_partial/search.ejs
14:40:01.388 DEBUG Processed: layout/_widget/about-site.ejs
14:40:01.388 DEBUG Processed: layout/_partial/valine.ejs
14:40:01.389 DEBUG Processed: layout/_widget/category-radar.ejs
14:40:01.389 DEBUG Processed: layout/_widget/category-cloud.ejs
14:40:01.390 DEBUG Processed: layout/_widget/my-projects.ejs
14:40:01.390 DEBUG Processed: layout/_widget/post-calendar.ejs
14:40:01.390 DEBUG Processed: layout/_widget/my-gallery.ejs
14:40:01.391 DEBUG Processed: layout/_widget/recommend.ejs
14:40:01.391 DEBUG Processed: layout/_widget/post-charts.ejs
14:40:01.391 DEBUG Processed: layout/_widget/tag-wordcloud.ejs
14:40:01.392 DEBUG Processed: layout/_widget/tag-cloud.ejs
14:40:01.392 DEBUG Processed: layout/_widget/my-skills.ejs
14:40:01.395 DEBUG Processed: source/medias/assets/loading/Dual_Ring-1s-200px.svg
14:40:01.396 DEBUG Processed: source/medias/assets/loading/Eclipse-1s-200px.svg
14:40:01.397 DEBUG Processed: source/medias/assets/loading/Flickr-1s-200px.svg
14:40:01.398 DEBUG Processed: source/medias/assets/loading/Ripple-0.8s-200px.svg
14:40:01.398 DEBUG Processed: source/medias/assets/loading/Ripple-0.8s-200px.gif
14:40:01.398 DEBUG Processed: source/medias/banner/4.jpg
14:40:01.399 DEBUG Processed: source/libs/awesome/css/font-awesome.min.css
14:40:01.400 DEBUG Processed: source/libs/gitalk/gitalk.min.js
14:40:01.401 DEBUG Processed: source/libs/photoswipe/default-skin/default-skin.css
14:40:01.402 DEBUG Processed: source/libs/photoswipe/default-skin/default-skin.svg
14:40:01.402 DEBUG Processed: source/libs/photoswipe/default-skin/preloader.gif
14:40:01.403 DEBUG Processed: source/libs/photoswipe/default-skin/default-skin.png
14:40:01.403 DEBUG Processed: source/libs/share/css/share.min.css
14:40:01.404 DEBUG Processed: source/libs/share/fonts/iconfont.eot
14:40:01.406 DEBUG Processed: source/libs/share/fonts/iconfont.svg
14:40:01.407 DEBUG Processed: source/libs/share/fonts/iconfont.ttf
14:40:01.408 DEBUG Processed: source/libs/share/fonts/iconfont.woff
14:40:01.408 DEBUG Processed: source/libs/share/js/jquery.share.min.js
14:40:01.409 DEBUG Processed: source/libs/share/js/social-share.min.js
14:40:01.413 DEBUG Processed: layout/_partial/prev-next.ejs
14:40:01.413 DEBUG Processed: source/libs/valine/av-min.js
14:40:01.414 DEBUG Processed: source/medias/assets/loading/loading3.gif
14:40:01.416 DEBUG Processed: source/medias/assets/loading/loading2.gif
14:40:01.416 DEBUG Processed: source/libs/awesome/fonts/fontawesome-webfont.woff2
14:40:01.420 DEBUG Processed: source/libs/materialize/font/material-design-icons/LICENSE.txt
14:40:01.421 DEBUG Processed: source/libs/materialize/js/materialize.min.js
14:40:01.423 DEBUG Processed: source/libs/awesome/fonts/fontawesome-webfont.eot
14:40:01.424 DEBUG Processed: source/libs/materialize/font/material-design-icons/Material-Design-Icons.woff2
14:40:01.428 DEBUG Processed: source/libs/awesome/fonts/FontAwesome.otf
14:40:01.429 DEBUG Processed: source/libs/awesome/fonts/fontawesome-webfont.woff
14:40:01.429 DEBUG Processed: source/libs/materialize/font/material-design-icons/Material-Design-Icons.eot
14:40:01.430 DEBUG Processed: source/libs/materialize/font/material-design-icons/Material-Design-Icons.ttf
14:40:01.433 DEBUG Processed: source/libs/materialize/css/materialize.min.css
14:40:01.435 DEBUG Processed: source/libs/materialize/font/material-design-icons/Material-Design-Icons.woff
14:40:01.436 DEBUG Processed: source/libs/awesome/fonts/fontawesome-webfont.ttf
14:40:01.439 DEBUG Processed: source/libs/materialize/font/material-design-icons/Material-Design-Icons.svg
14:40:01.440 DEBUG Processed: source/libs/awesome/fonts/fontawesome-webfont.svg
14:40:01.446 DEBUG Processed: source/libs/echarts/echarts.min.js
14:40:01.447 DEBUG Processed: source/medias/assets/loading/loading.gif
14:40:02.004 FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: (unknown path) [Line 22, Column 12]
  unexpected token: .
    at Object._prettifyError (C:\Users\zengxg\hexo-tellyouwhat\node_modules\nunjucks\src\lib.js:36:11)
    at Template.render (C:\Users\zengxg\hexo-tellyouwhat\node_modules\nunjucks\src\environment.js:526:21)
    at Environment.renderString (C:\Users\zengxg\hexo-tellyouwhat\node_modules\nunjucks\src\environment.js:364:17)
    at Promise.fromCallback.cb (C:\Users\zengxg\hexo-tellyouwhat\node_modules\hexo\lib\extend\tag.js:62:48)
    at tryCatcher (C:\Users\zengxg\hexo-tellyouwhat\node_modules\bluebird\js\release\util.js:16:23)
    at Function.Promise.fromNode.Promise.fromCallback (C:\Users\zengxg\hexo-tellyouwhat\node_modules\bluebird\js\release\promise.js:180:30)
    at Tag.render (C:\Users\zengxg\hexo-tellyouwhat\node_modules\hexo\lib\extend\tag.js:62:18)
    at Object.onRenderEnd (C:\Users\zengxg\hexo-tellyouwhat\node_modules\hexo\lib\hexo\post.js:282:20)
    at Promise.then.then.result (C:\Users\zengxg\hexo-tellyouwhat\node_modules\hexo\lib\hexo\render.js:65:19)
    at tryCatcher (C:\Users\zengxg\hexo-tellyouwhat\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\zengxg\hexo-tellyouwhat\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\zengxg\hexo-tellyouwhat\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\zengxg\hexo-tellyouwhat\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\zengxg\hexo-tellyouwhat\node_modules\bluebird\js\release\promise.js:694:18)
    at _drainQueueStep (C:\Users\zengxg\hexo-tellyouwhat\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (C:\Users\zengxg\hexo-tellyouwhat\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (C:\Users\zengxg\hexo-tellyouwhat\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues (C:\Users\zengxg\hexo-tellyouwhat\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

14:40:03.331 DEBUG Database saved
```

**Comment by HarborZeng** [comment]
looks like confliction with nunjucks. Is there any way to avoid this error? thanks.

**Comment by YoshinoriN** [comment]
@HarborZeng 

Try to use [raw](https://hexo.io/docs/tag-plugins#Raw) like this.

```
| 模板                                   | 描述                        |
| -------------------------------------- | ---------------------------|
| {% raw %} {{ .Branch }} {% endraw %}   | 正在构建中的VCS分支名        |
| {% raw %} {{ .BuildNum }} {% endraw %} | 此构建的CircleCI作业编号     |
...
```

Thanks :)

**Comment by HarborZeng** [comment]
Thank you @YoshinoriN It works like a charm now.
