### ISSUE TITLE
hexo generate highlight cannot set property 'lastIndex' of undefined

### ISSUE THREAD

**Issue by marcofranssen** [hexojs/hexo#3486]
I'm very often getting this error. I have been trying to figure out where I could add some logs so the enduser will get to know in which source file the issue is occuring. For some bizarre reason I can see in my Git I don't have any changes compared to previous `hexo generate` or `hexo server` attempts which where still working.

I have had this in the past as well and just switching to some older commits and running again magically made it work again. Does anyone have any clue where hexo caches its data or something like that? Is there some cache folder I could clear? Currently I'm completely unable to use hexo and this time not able to recover. Any thoughts are welcome as I'm kind of in the mode to switch to a different engine at the moment.

```bash
$ hexo generate
INFO Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: Cannot set property 'lastIndex' of undefined
at highlight (C:\code\my_project\node_modules\highlight.js\lib\highlight.js:511:35)
at C:\code\my_project\node_modules\highlight.js\lib\highlight.js:561:21
at Array.forEach (<anonymous>)
at Object.highlightAuto (C:\code\my_project\node_modules\highlight.js\lib\highlight.js:560:40)
at C:\code\my_project\node_modules\hexo-util\lib\highlight.js:117:25
at highlight (C:\code\my_project\node_modules\hexo-util\lib\highlight.js:120:7)
at highlightUtil (C:\code\my_project\node_modules\hexo-util\lib\highlight.js:22:14)
at data.content.data.content.replace (C:\code\my_project\node_modules\hexo\lib\plugins\filter\before_post_render\backtick_code_block.js:59:15)
at String.replace (<anonymous>)
at Hexo.backtickCodeBlock (C:\code\my_project\node_modules\hexo\lib\plugins\filter\before_post_render\backtick_code_block.js:14:31)
at Hexo.tryCatcher (C:\code\my_project\node_modules\bluebird\js\release\util.js:16:23)
at Hexo.<anonymous> (C:\code\my_project\node_modules\bluebird\js\release\method.js:15:34)
at Promise.each.filter (C:\code\my_project\node_modules\hexo\lib\extend\filter.js:63:65)
at tryCatcher (C:\code\my_project\node_modules\bluebird\js\release\util.js:16:23)
at Object.gotValue (C:\code\my_project\node_modules\bluebird\js\release\reduce.js:155:18)
at Object.gotAccum (C:\code\my_project\node_modules\bluebird\js\release\reduce.js:144:25)
at Object.tryCatcher (C:\code\my_project\node_modules\bluebird\js\release\util.js:16:23)
at Promise._settlePromiseFromHandler (C:\code\my_project\node_modules\bluebird\js\release\promise.js:512:31)
at Promise._settlePromise (C:\code\my_project\node_modules\bluebird\js\release\promise.js:569:18)
at Promise._settlePromiseCtx (C:\code\my_project\node_modules\bluebird\js\release\promise.js:606:10)
at Async._drainQueue (C:\code\my_project\node_modules\bluebird\js\release\async.js:138:12)
at Async._drainQueues (C:\code\my_project\node_modules\bluebird\js\release\async.js:143:10)
at Immediate.Async.drainQueues [as _onImmediate] (C:\code\my_project\node_modules\bluebird\js\release\async.js:17:14)
at processImmediate (timers.js:637:19)
```

After changing `_config.yml` `highlight.auto_detect` to `false` I get following error.

```bash
$ hexo generate
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: Cannot read property 'toString' of undefined
    at toString (C:\code\my_project\node_modules\hexo\lib\hexo\render.js:122:21)
    at Promise.then.then.result (C:\code\my_project\node_modules\hexo\lib\hexo\render.js:63:14)
    at tryCatcher (C:\code\my_project\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\code\my_project\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\code\my_project\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\code\my_project\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\code\my_project\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\code\my_project\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\code\my_project\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\code\my_project\node_modules\bluebird\js\release\async.js:17:14)
    at processImmediate (timers.js:637:19)
```

Even when I switch back this setting to `true` it sticks now with the `toString` error. So where does hexo cache its data and where to clear this? That might resolve the error.

I also tried removing the node_modules folder and reinstalling the dependencies in my project.

Never the less I think there should be some additional logging so someone will know in which file it is failing.

I did notice other tickets, but these are not the solution. 

#2380 #2672

**Comment by marcofranssen** [comment]
After more troubleshooting (as I really want to publish my blogpost) I figured that a docker-compose.yml file in my downloads/code/docker-example folder is causing the issue. Even with the following in my config it just fails. with the tostring of undefined error.

```yml
skip_render: downloads/code/**/*
```

I was able to figure this out by putting 

```js
    console.log(data.path);
    console.log(data.text);
```

at line 51 and 52 in hexo/lib/hexo/render.js

1. Is there anyone more experienced in hexo who could add a debug option to the cli to enable this kind of logs so users can figure out where errors are occurring?
2. Is there anyone more experienced in hexo who could fix the bug caused by yaml files in downloads/code folder?

For now I resolved by removing my docker-compose.yml so I can at least publish my blogpost with a workarround.

As many people in the past have experienced similar issues it would be great someone of the core contributors could fix this.

**Comment by YoshinoriN** [comment]
@marcofranssen 
How about [ignore option](https://github.com/hexojs/hexo/issues/2855). (It's undocumented)

**Comment by marcofranssen** [comment]
Hmmm I was able to generate once and now we are back with the highlight lastIndex error again.

I did a `hexo clean` as it was still pulling the docker-compose.yml from the cache. when I put it back afterwards to test and then removed it again.

**Comment by HomoEfficio** [comment]
If there are brackets( `[]` ) in the triple-backtick block, then this error happens.  
In this case, append `text` to triple-backtick, instead of using just triple-backtick.
