### ISSUE TITLE
Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by isjinhao** [hexojs/hexo#3523]
TypeError: Cannot read property 'replace' of undefined
    at Object.<anonymous> (D:\blog\isjinhao\node_modules\hexo-asset-image\index.js:31:38)
    at initialize.exports.each (D:\blog\isjinhao\node_modules\hexo-asset-image\node_modules\cheerio\lib\api\traversing.js:293:24)
    at Hexo.<anonymous> (D:\blog\isjinhao\node_modules\hexo-asset-image\index.js:29:16)
    at Hexo.tryCatcher (D:\blog\isjinhao\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (D:\blog\isjinhao\node_modules\bluebird\js\release\method.js:15:34)
    at Promise.each.filter (D:\blog\isjinhao\node_modules\hexo\lib\extend\filter.js:63:65)
    at tryCatcher (D:\blog\isjinhao\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (D:\blog\isjinhao\node_modules\bluebird\js\release\reduce.js:155:18)
    at Object.gotAccum (D:\blog\isjinhao\node_modules\bluebird\js\release\reduce.js:144:25)
    at Object.tryCatcher (D:\blog\isjinhao\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\blog\isjinhao\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\blog\isjinhao\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\blog\isjinhao\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\blog\isjinhao\node_modules\bluebird\js\release\promise.js:694:18)
    at _drainQueueStep (D:\blog\isjinhao\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (D:\blog\isjinhao\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (D:\blog\isjinhao\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\blog\isjinhao\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

**Comment by gautamz07** [comment]
@isjinhao  when are you getting this error ? can you provide a bit more context ?

**Comment by isjinhao** [comment]
@gautamz07 this happens when I use hexo g, but it won't happen if the post_asset_folder in the _config.yml file is set to false

**Comment by tcrowe** [comment]
These look similar: https://github.com/hexojs/hexo/issues/3530

My guess is that there is a syntax error in the markdown or template and it does not have a `try-catch`.
