### ISSUE TITLE
$ npm install -g hexo-cli 安裝錯誤

### ISSUE THREAD

**Issue by shuwn** [hexojs/hexo#3539]
## Environment Info
Mac OS X 10.14.4
Node v12.0.0
npm 6.9.0
nvm 0.34.0

## For BUG
```shell
Shuwns-MacBook-Pro:~ shuwn$ npm install -g hexo-cli
/Users/shuwn/.nvm/versions/node/v12.0.0/bin/hexo -> /Users/shuwn/.nvm/versions/node/v12.0.0/lib/node_modules/hexo-cli/bin/hexo

> fsevents@1.2.8 install /Users/shuwn/.nvm/versions/node/v12.0.0/lib/node_modules/hexo-cli/node_modules/fsevents
> node install

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.8/fse-v1.2.8-node-v72-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.8 and node@12.0.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
../fsevents.cc:43:32: error: no template named 'Handle' in namespace 'v8'
    static void Initialize(v8::Handle<v8::Object> exports);
                           ~~~~^
In file included from ../fsevents.cc:73:
../src/constants.cc:89:11: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagNone").ToLoca...
          ^
/Users/shuwn/.node-gyp/12.0.0/include/node/v8.h:3358:3: note: 'Set' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/shuwn/.node-gyp/12.0.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:73:
../src/constants.cc:90:11: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagMustScanSubDi...
          ^
/Users/shuwn/.node-gyp/12.0.0/include/node/v8.h:3358:3: note: 'Set' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/shuwn/.node-gyp/12.0.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:73:
../src/constants.cc:91:11: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagUserDropped")...
          ^
/Users/shuwn/.node-gyp/12.0.0/include/node/v8.h:3358:3: note: 'Set' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/shuwn/.node-gyp/12.0.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:73:
../src/constants.cc:92:11: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagKernelDropped...
          ^
/Users/shuwn/.node-gyp/12.0.0/include/node/v8.h:3358:3: note: 'Set' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/shuwn/.node-gyp/12.0.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:73:
../src/constants.cc:93:11: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagEventIdsWrapp...
          ^
/Users/shuwn/.node-gyp/12.0.0/include/node/v8.h:3358:3: note: 'Set' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/shuwn/.node-gyp/12.0.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:73:
../src/constants.cc:94:11: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagHistoryDone")...
          ^
/Users/shuwn/.node-gyp/12.0.0/include/node/v8.h:3358:3: note: 'Set' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/shuwn/.node-gyp/12.0.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:73:
../src/constants.cc:95:11: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagRootChanged")...
          ^
/Users/shuwn/.node-gyp/12.0.0/include/node/v8.h:3358:3: note: 'Set' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/shuwn/.node-gyp/12.0.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:73:
../src/constants.cc:96:11: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagMount").ToLoc...
          ^
/Users/shuwn/.node-gyp/12.0.0/include/node/v8.h:3358:3: note: 'Set' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/shuwn/.node-gyp/12.0.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:73:
../src/constants.cc:97:11: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagUnmount").ToL...
          ^
/Users/shuwn/.node-gyp/12.0.0/include/node/v8.h:3358:3: note: 'Set' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/shuwn/.node-gyp/12.0.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:73:
../src/constants.cc:98:11: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemCreated")...
          ^
/Users/shuwn/.node-gyp/12.0.0/include/node/v8.h:3358:3: note: 'Set' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/shuwn/.node-gyp/12.0.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:73:
../src/constants.cc:99:11: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemRemoved")...
          ^
/Users/shuwn/.node-gyp/12.0.0/include/node/v8.h:3358:3: note: 'Set' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/shuwn/.node-gyp/12.0.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:73:
../src/constants.cc:100:11: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemInodeMeta...
          ^
/Users/shuwn/.node-gyp/12.0.0/include/node/v8.h:3358:3: note: 'Set' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/shuwn/.node-gyp/12.0.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:73:
../src/constants.cc:101:11: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemRenamed")...
          ^
/Users/shuwn/.node-gyp/12.0.0/include/node/v8.h:3358:3: note: 'Set' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/shuwn/.node-gyp/12.0.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:73:
../src/constants.cc:102:11: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemModified"...
          ^
/Users/shuwn/.node-gyp/12.0.0/include/node/v8.h:3358:3: note: 'Set' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/shuwn/.node-gyp/12.0.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:73:
../src/constants.cc:103:11: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemFinderInf...
          ^
/Users/shuwn/.node-gyp/12.0.0/include/node/v8.h:3358:3: note: 'Set' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/shuwn/.node-gyp/12.0.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:73:
../src/constants.cc:104:11: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemChangeOwn...
          ^
/Users/shuwn/.node-gyp/12.0.0/include/node/v8.h:3358:3: note: 'Set' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/shuwn/.node-gyp/12.0.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:73:
../src/constants.cc:105:11: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemXattrMod"...
          ^
/Users/shuwn/.node-gyp/12.0.0/include/node/v8.h:3358:3: note: 'Set' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/shuwn/.node-gyp/12.0.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:73:
../src/constants.cc:106:11: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemIsFile")....
          ^
/Users/shuwn/.node-gyp/12.0.0/include/node/v8.h:3358:3: note: 'Set' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/shuwn/.node-gyp/12.0.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:73:
../src/constants.cc:107:11: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemIsDir").T...
          ^
/Users/shuwn/.node-gyp/12.0.0/include/node/v8.h:3358:3: note: 'Set' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/shuwn/.node-gyp/12.0.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:73:
../src/constants.cc:108:11: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemIsSymlink...
          ^
/Users/shuwn/.node-gyp/12.0.0/include/node/v8.h:3358:3: note: 'Set' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/shuwn/.node-gyp/12.0.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../fsevents.cc:76:16: error: variable has incomplete type 'void'
void FSEvents::Initialize(v8::Handle<v8::Object> exports) {
               ^
../fsevents.cc:76:31: error: no member named 'Handle' in namespace 'v8'
void FSEvents::Initialize(v8::Handle<v8::Object> exports) {
                          ~~~~^
../fsevents.cc:76:48: error: expected '(' for function-style cast or type
      construction
void FSEvents::Initialize(v8::Handle<v8::Object> exports) {
                                     ~~~~~~~~~~^
../fsevents.cc:76:50: error: use of undeclared identifier 'exports'
void FSEvents::Initialize(v8::Handle<v8::Object> exports) {
                                                 ^
../fsevents.cc:76:58: error: expected ';' after top level declarator
void FSEvents::Initialize(v8::Handle<v8::Object> exports) {
                                                         ^
                                                         ;
20 warnings and 6 errors generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/shuwn/.nvm/versions/node/v12.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/Users/shuwn/.nvm/versions/node/v12.0.0/bin/node" "/Users/shuwn/.nvm/versions/node/v12.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/shuwn/.nvm/versions/node/v12.0.0/lib/node_modules/hexo-cli/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/shuwn/.nvm/versions/node/v12.0.0/lib/node_modules/hexo-cli/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /Users/shuwn/.nvm/versions/node/v12.0.0/lib/node_modules/hexo-cli/node_modules/fsevents
gyp ERR! node -v v12.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/shuwn/.nvm/versions/node/v12.0.0/bin/node /Users/shuwn/.nvm/versions/node/v12.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/shuwn/.nvm/versions/node/v12.0.0/lib/node_modules/hexo-cli/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/shuwn/.nvm/versions/node/v12.0.0/lib/node_modules/hexo-cli/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/shuwn/.nvm/versions/node/v12.0.0/lib/node_modules/hexo-cli/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1000:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:5)
node-pre-gyp ERR! System Darwin 18.5.0
node-pre-gyp ERR! command "/Users/shuwn/.nvm/versions/node/v12.0.0/bin/node" "/Users/shuwn/.nvm/versions/node/v12.0.0/lib/node_modules/hexo-cli/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/shuwn/.nvm/versions/node/v12.0.0/lib/node_modules/hexo-cli/node_modules/fsevents
node-pre-gyp ERR! node -v v12.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok
Failed to execute '/Users/shuwn/.nvm/versions/node/v12.0.0/bin/node /Users/shuwn/.nvm/versions/node/v12.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/shuwn/.nvm/versions/node/v12.0.0/lib/node_modules/hexo-cli/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/shuwn/.nvm/versions/node/v12.0.0/lib/node_modules/hexo-cli/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules/hexo-cli/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ hexo-cli@1.1.0
updated 1 package in 7.679s
```
## For question
無法順利安裝，該如何處理？謝謝！

**Comment by weyusi** [comment]
Use `npm install -g hexo-cli --prod` to skip installation of fsevents dep.

**Comment by shuwn** [comment]
Thank you for your reply, I am referenced to this article to solve.
https://blog.csdn.net/weixin_40514790/article/details/85334617

step 1
```
npm install -g node-inspector@latest
```
step 2
```
npm install -g node-inspector@latest
```
step 3
```
npm install -g hexo-cli --prod
```

**Comment by weyusi** [comment]
Please close this issue if solved.
