### ISSUE TITLE
TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by Zhanchenhaha** [hexojs/hexo#3540]
## Environment Info

hexo: 3.8.0
hexo-cli: 1.1.0
os: Windows_NT 6.1.7601 win32 x64
http_parser: 2.8.0
node: 8.12.0
v8: 6.2.414.66
uv: 1.19.2
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.32.0
napi: 3
openssl: 1.0.2p
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c

## For question

FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: Cannot read property 'toString' of undefined
    at toString (F:\myblog\node_modules\hexo\lib\hexo\render.js:122:21)
    at Promise.then.then.result (F:\myblog\node_modules\hexo\lib\hexo\render.js:63:14)
    at tryCatcher (F:\myblog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (F:\myblog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (F:\myblog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (F:\myblog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (F:\myblog\node_modules\bluebird\js\release\promise.js:694:18)
    at _drainQueueStep (F:\myblog\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (F:\myblog\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (F:\myblog\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues (F:\myblog\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
F:\myblog\node_modules\hexo-renderer-pandoc\index.js:91
      return callback(new Error(error_msg));
             ^

TypeError: callback is not a function
    at ChildProcess.<anonymous> (F:\myblog\node_modules\hexo-renderer-pandoc\index.js:91:14)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Socket.stream.socket.on (internal/child_process.js:336:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:561:12)

**Comment by Zhanchenhaha** [comment]
重启电脑之后已经解决了。如果有人知道原理可以告诉我，谢谢大家了。

**Comment by Zhanchenhaha** [comment]
好了之后，又报错了，希望有人可以解答一样。
