### ISSUE TITLE
hexo generate/server error

### ISSUE THREAD

**Issue by kmcyjm** [hexojs/hexo#3572]
OS: macOS Mojave 10.14.5

When running `hexo generate/server`, the following error is returned,

```
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: Cannot find module 'entities/lib/decode_codepoint.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/jiaming/Desktop/my_Hexo_site/security/node_modules/htmlparser2/lib/Tokenizer.js:3:23)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/jiaming/Desktop/my_Hexo_site/security/node_modules/htmlparser2/lib/Parser.js:1:79)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/jiaming/Desktop/my_Hexo_site/security/node_modules/htmlparser2/lib/index.js:1:76)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
```

Tried the following command, but no luck,

`npm install grunt-contrib-jshint --save-dev`
## Environment Info

node -v
`v11.2.0`

Hexo and Plugin version(`npm ls --depth 0`): 
```
hexo-site@0.0.0 /Users/jiaming/Desktop/my_Hexo_site/security
├── grunt@1.0.4
├── grunt-contrib-jshint@2.1.0
├── hexo@3.8.0
├── hexo-deployer-git@0.3.1
├── hexo-generator-archive@0.1.5
├── hexo-generator-category@0.1.3
├── hexo-generator-feed@1.2.2
├── hexo-generator-index@0.2.1
├── hexo-generator-search@2.3.0
├── hexo-generator-sitemap@1.2.0
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.3.1
├── hexo-renderer-marked@0.3.2
├── hexo-renderer-stylus@0.3.3
└── hexo-server@0.3.3
```

Your package.json `package.json`: 
```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "grunt": "^1.0.4",
    "hexo": "^3.8.0",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-search": "^2.3.0",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-marked": "^0.3.2",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.1"
  },
  "devDependencies": {
    "grunt-contrib-jshint": "^2.1.0"
  }
}
```

**Comment by kmcyjm** [comment]
run `rm -rf node_modules/ && npm install` fixed the issue.

Don't know what went wrong, but it did the job.

Closing this issue.
