### ISSUE TITLE
Deploy ENOMEM Error

### ISSUE THREAD

**Issue by buptljy** [hexojs/hexo#3590]
Server Configuration: 1 Core 1GB RAM.

The server is used to deploy my blog, so I think 1GB RAM is enough. However, after I wrote 30+ posts and deployment goes wrong sometimes. 

```
Error: spawn ENOMEM
    at exports._errnoException (util.js:1020:11)
    at ChildProcess.spawn (internal/child_process.js:319:11)
    at Object.exports.spawn (child_process.js:369:9)
    at spawn (/server/hexo/node_modules/cross-spawn/index.js:17:18)
    at /server/hexo/node_modules/hexo-util/lib/spawn.js:19:16
    at Promise._execute (/server/hexo/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/server/hexo/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/server/hexo/node_modules/bluebird/js/release/promise.js:79:10)
    at promiseSpawn (/server/hexo/node_modules/hexo-util/lib/spawn.js:18:10)
    at git (/server/hexo/node_modules/hexo-deployer-git/lib/deployer.js:58:12)
    at push (/server/hexo/node_modules/hexo-deployer-git/lib/deployer.js:84:12)
    at /server/hexo/node_modules/hexo-deployer-git/lib/deployer.js:154:12
    at tryCatcher (/server/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/server/hexo/node_modules/bluebird/js/release/reduce.js:155:18)
    at Object.gotAccum (/server/hexo/node_modules/bluebird/js/release/reduce.js:144:25)
    at Object.tryCatcher (/server/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/server/hexo/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/server/hexo/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/server/hexo/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/server/hexo/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/server/hexo/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/server/hexo/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

It looks like a memory issue, which doesn't make sense to me. Maybe hexo uses multiple threads to finish the deployment and that's why 1GB RAM cannot hold. Anyone can tell me how to solve this?

**Comment by tcrowe** [comment]
Hi @buptljy 👋 I think hexo mostly runs in one thread but depending on how many posts and pages you are working with the memory use could go up.

For example if you generate `1,000` posts, run `hexo serve --debug`, then check your process manager for memory use you can see a metric there.

Then lets say you generate `30,000` posts and do the same you can see how much memory that uses.

---

I know on one of my VMs recently I was running many other node processes which took up memory. Then when I tried to use another node instance it was using the virtual memory on the hard drive. Maybe it's possible that you can use `top`, `ps`, or some other tools to find it.

**Comment by buptljy** [comment]
@tcrowe  Thank you! I think it is solved now after I change the node memory size in bin/hexo.

**Comment by tcrowe** [comment]
@buptljy You're welcome. If you share your solution maybe others searching for a similar problem will benefit from your experience. 🤓👍
