### ISSUE TITLE
hexo deploy via sftp got "no passphrase given" error

### ISSUE THREAD

**Issue by wuyuchang** [hexojs/hexo#3602]
## Environment Info

``` shell
node -v # v10.16.0
```

Your site `_config.yml` (Optional):
``` yml
deploy:
  type: sftp
  host: afacat.com
  user: afacat
  remotePath: /home/afacat/Websites/blog
  privateKey: /Users/jackie/.ssh/afacat_id_rsa
```

Hexo and Plugin version(`npm ls --depth 0`): 
``` shell
hexo-site@0.0.0 /Users/jackie/Websites/Gogs-Git/blog
├── hexo@3.9.0
├── hexo-deployer-sftp@0.1.0
├── hexo-generator-archive@0.1.5
├── hexo-generator-category@0.1.3
├── hexo-generator-feed@1.2.2
├── hexo-generator-index@0.2.1
├── hexo-generator-json-content@4.1.6
├── hexo-generator-tag@0.2.0
├── hexo-helper-qrcode@1.0.2
├── hexo-renderer-ejs@0.3.1
├── hexo-renderer-less@1.0.0
├── hexo-renderer-marked@1.0.1
├── hexo-renderer-stylus@0.3.3
├── hexo-server@0.3.3
├── keyword-extractor@0.0.16 extraneous
└── node-pre-gyp@0.12.0 extraneous
```

Your package.json `package.json`: 
``` json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.9.0"
  },
  "dependencies": {
    "hexo": "^3.9.0",
    "hexo-deployer-sftp": "^0.1.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-json-content": "^4.1.6",
    "hexo-generator-tag": "^0.2.0",
    "hexo-helper-qrcode": "^1.0.2",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-less": "^1.0.0",
    "hexo-renderer-marked": "^1.0.1",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.3"
  },
  "devDependencies": {}
}
```
## For BUG

1. Bug description
**Error: Encrypted private key detected, but no passphrase given**
2. The way to reproduce
**set hexo deploy type as sftp with passphrase (ssh-agent was set)**
3. Log with hexo <command> --debug
``` shell
jackie ➜  blog git:(master) ✗ hexo deploy
INFO  Deploying: sftp
* Deploying to host afacat.com
* local dir  = /Users/jackie/Websites/Gogs-Git/blog/public
* remote dir = /home/afacat/Websites/blog

FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
Error: Encrypted private key detected, but no passphrase given
    at Client.connect (/Users/jackie/Websites/Gogs-Git/blog/node_modules/ssh2/lib/client.js:235:15)
    at Bluebird (/Users/jackie/Websites/Gogs-Git/blog/node_modules/sftp-sync-deploy/lib/sftpSync.js:62:22)
    at Promise._execute (/Users/jackie/Websites/Gogs-Git/blog/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/Users/jackie/Websites/Gogs-Git/blog/node_modules/bluebird/js/release/promise.js:488:18)
    at new Promise (/Users/jackie/Websites/Gogs-Git/blog/node_modules/bluebird/js/release/promise.js:79:10)
    at Bluebird.resolve.then.then (/Users/jackie/Websites/Gogs-Git/blog/node_modules/sftp-sync-deploy/lib/sftpSync.js:53:20)
    at tryCatcher (/Users/jackie/Websites/Gogs-Git/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/jackie/Websites/Gogs-Git/blog/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/Users/jackie/Websites/Gogs-Git/blog/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/Users/jackie/Websites/Gogs-Git/blog/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/Users/jackie/Websites/Gogs-Git/blog/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/Users/jackie/Websites/Gogs-Git/blog/node_modules/bluebird/js/release/promise.js:643:18)
    at Promise._resolveCallback (/Users/jackie/Websites/Gogs-Git/blog/node_modules/bluebird/js/release/promise.js:437:57)
    at Promise._settlePromiseFromHandler (/Users/jackie/Websites/Gogs-Git/blog/node_modules/bluebird/js/release/promise.js:529:17)
    at Promise._settlePromise (/Users/jackie/Websites/Gogs-Git/blog/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/Users/jackie/Websites/Gogs-Git/blog/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/Users/jackie/Websites/Gogs-Git/blog/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/Users/jackie/Websites/Gogs-Git/blog/node_modules/bluebird/js/release/promise.js:643:18)
    at Promise._settlePromise (/Users/jackie/Websites/Gogs-Git/blog/node_modules/bluebird/js/release/promise.js:587:21)
    at Promise._settlePromise0 (/Users/jackie/Websites/Gogs-Git/blog/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/Users/jackie/Websites/Gogs-Git/blog/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/Users/jackie/Websites/Gogs-Git/blog/node_modules/bluebird/js/release/promise.js:643:18)
```

## For question
Hexo deploy as type of sftp with ssh passphrase get "no passphrase given" error.

I'm using sftp to deploy my blog to my personal website (not github), I can log in to server without provide passphrase because  I was set `ssh-add ~/.ssh/afacat_id_rsa` to `ssh-agent`, but I got error when I try to use `hexo deploy` to deploy my blog to server site. I will not get the error if I set the passphrase as empty, but it's not secure, so I'm not gonna to set it as empty. So how can deploy my site to server with passphrase was set.

**Comment by YoshinoriN** [comment]
Hi @wuyuchang 👋 

hexo-deployer-sftp has [passphrase option](https://github.com/lucascaro/hexo-deployer-sftp/blob/6a5283087677d302e512e50bcb6639c0ece794c7/index.js#L33). Did you try it?

**Comment by wuyuchang** [comment]
> Hi @wuyuchang 👋
> 
> hexo-deployer-sftp has [passphrase option](https://github.com/lucascaro/hexo-deployer-sftp/blob/6a5283087677d302e512e50bcb6639c0ece794c7/index.js#L33). Did you try it?

@YoshinoriN I tried it. It's is okay when I set passphrase, but I can ssh to server without passphrase because I set the `ssh-agent` via `ssh-add`, so that I think it doesn't have to set passphrase for hexo-deployer-sftp passphrase option according to the hexo document.

> Deploys the site via SFTP, allowing for passwordless connections using ssh-agent.

**Comment by tcrowe** [comment]
It could be that it's not finding your `~/.ssh/config`

**Comment by wuyuchang** [comment]
@tcrowe  I had set the `~/.ssh/config`.
```
Host afacat.com
  User afacat
  HostName afacat.com
  Port 22
  IdentityFile ~/.ssh/afacat_id_rsa 
```

**Comment by tcrowe** [comment]
Lets try this first:

`./_config.yml`

```yml
deploy:
  type: sftp
  host: afacat.com
  user: afacat
  # you can fix the remote path to the website
  remotePath: /var/www/afacat.com

  # for windows
  privateKey: C:\Users\afacat\.ssh\afacat_id_rsa

  # for osx
  # privateKey: /Users/afacat/.ssh/afacat_id_rsa

  # for linux
  privateKey: /home/afacat/.ssh/afacat_id_rsa
```

**Comment by tcrowe** [comment]
Sorry, @wuyuchang you probably already had that correct above.

---

Don't put it in here but `passphrase: ___________`  might be needed.

**Comment by tcrowe** [comment]
Another thing you can try is to get `ssh-agent` to help. View the output of `ssh-agent -s`.

```sh
# help the apps with the environment
eval $(ssh-agent -s)

hexo generate
hexo deploy
```

**Comment by tcrowe** [comment]
`echo $SSH_AUTH_SOCK`
