### ISSUE TITLE
deploy错误

### ISSUE THREAD

**Issue by York618** [hexojs/hexo#3623]
## 我部署时出现问题
使用hexo deploy出现以下信息：

INFO  Deploying: heroku
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError: source.replace is not a function
    at Object.exports.parse (/home/coding/workspace/hexo/node_modules/hexo-deployer-heroku/node_modules/swig/lib/parser.js:438:19)
    at exports.Swig.parse (/home/coding/workspace/hexo/node_modules/hexo-deployer-heroku/node_modules/swig/lib/swig.js:354:19)
    at Object.precompile (/home/coding/workspace/hexo/node_modules/hexo-deployer-heroku/node_modules/swig/lib/swig.js:486:23)
    at Object.compile (/home/coding/workspace/hexo/node_modules/hexo-deployer-heroku/node_modules/swig/lib/swig.js:606:16)
    at commitMessage (/home/coding/workspace/hexo/node_modules/hexo-deployer-heroku/lib/deployer.js:100:15)
    at Hexo.module.exports (/home/coding/workspace/hexo/node_modules/hexo-deployer-heroku/lib/deployer.js:25:17)
    at Hexo.tryCatcher (/home/coding/workspace/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/home/coding/workspace/hexo/node_modules/bluebird/js/release/method.js:15:34)
    at /home/coding/workspace/hexo/node_modules/hexo/lib/plugins/console/deploy.js:55:20
    at tryCatcher (/home/coding/workspace/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/home/coding/workspace/hexo/node_modules/bluebird/js/release/reduce.js:155:18)
    at Object.gotAccum (/home/coding/workspace/hexo/node_modules/bluebird/js/release/reduce.js:144:25)
    at Object.tryCatcher (/home/coding/workspace/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/coding/workspace/hexo/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/home/coding/workspace/hexo/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromiseCtx (/home/coding/workspace/hexo/node_modules/bluebird/js/release/promise.js:611:10)
    at _drainQueueStep (/home/coding/workspace/hexo/node_modules/bluebird/js/release/async.js:142:12)
    at _drainQueue (/home/coding/workspace/hexo/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/coding/workspace/hexo/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/coding/workspace/hexo/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:439:21)
➜  hexo git:(master) ✗ 

请各位帮忙
谢

**Comment by stevenjoezhang** [comment]
建议在这里开issue：https://github.com/hexojs/hexo-deployer-heroku/issues

**Comment by m-maohuawei** [comment]
deploy:
  type: git
  repo: 你的地址 
#  branch: [master] 
#  message: [message]

将branch和message注释或者写正确的格式

**Comment by York618** [comment]
> deploy:
> type: git
> repo: 你的地址
> branch: [master]
> message: [message]
> 将branch和message注释或者写正确的格式

## 没用啦老铁。
最新的hexo是用ssh免密来推送的啦，而Heroku并没有类似于
`git@github.com`这样的服务器地址。只能把Public导出来，重新整理git仓库试一下。
或者你试试。
