### ISSUE TITLE
在hexo init的时候报语法错误

### ISSUE THREAD

**Issue by xYang98** [hexojs/hexo#3638]
E:\Hexo>hexo init
C:\Users\Administrator\AppData\Roaming\npm\node_modules\hexo-cli\lib\hexo.js:15
function entry(cwd = process.cwd(), args) {
                   ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\hexo-cli\bin\hexo:5:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)

**Comment by Avento** [comment]
请问是怎么解决的呢？我看了一天了
