### ISSUE TITLE
How to troubleshoot generating errors?

### ISSUE THREAD

**Issue by twatzl** [hexojs/hexo#3640]
Hello,

I modified some of the files of my theme to support multi language posts, however somewhere I made a mistake. Since it was a few days ago and generating still works to a certain extend I have not paid attention to when this error started to come up. However when generating I get the following error: 

```
Unhandled rejection TypeError: expecting an array or an iterable object but got [object Null]
    at apiRejection (/data/blog/node_modules/bluebird/js/release/promise.js:10:27)                    
    at ReductionPromiseArray.init (/data/blog/node_modules/bluebird/js/release/promise_array.js:63:19)
    at Promise._settlePromise (/data/blog/node_modules/bluebird/js/release/promise.js:571:21)         
    at Promise._settlePromise0 (/data/blog/node_modules/bluebird/js/release/promise.js:619:10)        
    at Promise._settlePromises (/data/blog/node_modules/bluebird/js/release/promise.js:699:18)        
    at _drainQueueStep (/data/blog/node_modules/bluebird/js/release/async.js:138:12)                  
    at _drainQueue (/data/blog/node_modules/bluebird/js/release/async.js:131:9)                       
    at Async._drainQueues (/data/blog/node_modules/bluebird/js/release/async.js:147:5)                
    at Immediate.Async.drainQueues [as _onImmediate] (/data/blog/node_modules/bluebird/js/release/async.js:17:14)                                                                                           
    at processImmediate (internal/timers.js:439:21)
```

Is there a way to find out exactly which file is being processed when this error is thrown or is there some commandline flag to enable more verbose output during generate?

**Comment by twatzl** [comment]
I now found out that `hexo generate --debug` gives detailed information. However the `--debug` flag is not documented with `hexo generate -h`.

I ended up just looking for the error by deactivating plugins in the config one by one.
