### ISSUE TITLE
运行hexo有关命令报错

### ISSUE THREAD

**Issue by ATURICS** [hexojs/hexo#3664]
`C:\Users\dguser\Desktop\myBlog\ATURICS.github.io\node_modules\nanomatch\index.js:243
nanomatch.every = ftn�tion(list,`peUdgrns$ Ottioos� {
                     ^

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\dguser\Desktop\myBlog\ATURICS.github.io\node_modules\micromatch\lib\compilers.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\dguser\Desktop\myBlog\ATURICS.github.io\node_modules\micromatch\index.js:16:17)`

**Comment by tcrowe** [comment]
We need more information to help. What were you doing to get the error?

---

我们需要更多信息来提供帮助。你在做什么来弄错这个错误？

---

Maybe you can also try to update:

```sh
npm install --global npm-check-updates@latest hexo-cli@latest

# in your directory "C:\Users\dguser\Desktop\myBlog\ATURICS.github.io"
# update module versions
ncu -unt

# install
npm install

# try to run it again
hexo server --debug
```

**Comment by ATURICS** [comment]
@tcrowe 我在学校的电脑上设置好了博客，然后将博客的整个文件夹拷贝到了家里的电脑上，输入hexo 就会显示上面的这段提示。[MyBlog](https://aturics.github.io/)这是原本的显示效果。拷贝后没有对文件夹内的内容做任何改动。

**Comment by ATURICS** [comment]
fixed
