### ISSUE TITLE
Template render error: when use {{ Mustache }}

### ISSUE THREAD

**Issue by eonun** [hexojs/hexo#3752]
我在hexo文章中使用到 {#rgb} 出现以下错误，查下来是 {# 导致的错误，删除了又正常了

FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
Template render error: (unknown path)
Error: expected end of comment, got end of file
at Object._prettifyError (/home/eonun/testhexo/node_modules/nunjucks/src/lib.js:36:11)
at Template.render (/home/eonun/testhexo/node_modules/nunjucks/src/environment.js:542:21)
at Environment.renderString (/home/eonun/testhexo/node_modules/nunjucks/src/environment.js:380:17)
at Promise.fromCallback.cb (/home/eonun/testhexo/node_modules/hexo/lib/extend/tag.js:123:48)
at tryCatcher (/home/eonun/testhexo/node_modules/bluebird/js/release/util.js:16:23)
at Function.Promise.fromNode.Promise.fromCallback (/home/eonun/testhexo/node_modules/bluebird/js/release/promise.js:209:30)
at Tag.render (/home/eonun/testhexo/node_modules/hexo/lib/extend/tag.js:123:18)
at Object.onRenderEnd (/home/eonun/testhexo/node_modules/hexo/lib/hexo/post.js:280:20)
at Promise.then.then.result (/home/eonun/testhexo/node_modules/hexo/lib/hexo/render.js:64:19)
at tryCatcher (/home/eonun/testhexo/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/home/eonun/testhexo/node_modules/bluebird/js/release/promise.js:547:31)
at Promise._settlePromise (/home/eonun/testhexo/node_modules/bluebird/js/release/promise.js:604:18)
at Promise._settlePromise0 (/home/eonun/testhexo/node_modules/bluebird/js/release/promise.js:649:10)
at Promise._settlePromises (/home/eonun/testhexo/node_modules/bluebird/js/release/promise.js:729:18)
at _drainQueueStep (/home/eonun/testhexo/node_modules/bluebird/js/release/async.js:93:12)
at _drainQueue (/home/eonun/testhexo/node_modules/bluebird/js/release/async.js:86:9)
at Async._drainQueues (/home/eonun/testhexo/node_modules/bluebird/js/release/async.js:102:5)
at Immediate.Async.drainQueues (/home/eonun/testhexo/node_modules/bluebird/js/release/async.js:15:14)
at runCallback (timers.js:705:18)
at tryOnImmediate (timers.js:676:5)
at processImmediate (timers.js:658:5)
INFO Start processing
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
Template render error: (unknown path)
Error: expected end of comment, got end of file
at Object._prettifyError (/home/eonun/testhexo/node_modules/nunjucks/src/lib.js:36:11)
at Template.render (/home/eonun/testhexo/node_modules/nunjucks/src/environment.js:542:21)
at Environment.renderString (/home/eonun/testhexo/node_modules/nunjucks/src/environment.js:380:17)
at Promise.fromCallback.cb (/home/eonun/testhexo/node_modules/hexo/lib/extend/tag.js:123:48)
at tryCatcher (/home/eonun/testhexo/node_modules/bluebird/js/release/util.js:16:23)
at Function.Promise.fromNode.Promise.fromCallback (/home/eonun/testhexo/node_modules/bluebird/js/release/promise.js:209:30)
at Tag.render (/home/eonun/testhexo/node_modules/hexo/lib/extend/tag.js:123:18)
at Object.onRenderEnd (/home/eonun/testhexo/node_modules/hexo/lib/hexo/post.js:280:20)
at Promise.then.then.result (/home/eonun/testhexo/node_modules/hexo/lib/hexo/render.js:64:19)
at tryCatcher (/home/eonun/testhexo/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/home/eonun/testhexo/node_modules/bluebird/js/release/promise.js:547:31)
at Promise._settlePromise (/home/eonun/testhexo/node_modules/bluebird/js/release/promise.js:604:18)
at Promise._settlePromise0 (/home/eonun/testhexo/node_modules/bluebird/js/release/promise.js:649:10)
at Promise._settlePromises (/home/eonun/testhexo/node_modules/bluebird/js/release/promise.js:729:18)
at _drainQueueStep (/home/eonun/testhexo/node_modules/bluebird/js/release/async.js:93:12)
at _drainQueue (/home/eonun/testhexo/node_modules/bluebird/js/release/async.js:86:9)
at Async._drainQueues (/home/eonun/testhexo/node_modules/bluebird/js/release/async.js:102:5)
at Immediate.Async.drainQueues (/home/eonun/testhexo/node_modules/bluebird/js/release/async.js:15:14)
at runCallback (timers.js:705:18)
at tryOnImmediate (timers.js:676:5)
at processImmediate (timers.js:658:5)

**Comment by eonun** [comment]
hexo: 3.9.0
hexo-cli: 2.0.0
os: Linux 4.19.69-1-MANJARO linux x64
http_parser: 2.9.2
node: 10.16.3
v8: 6.8.275.32-node.54
uv: 1.31.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 64
nghttp2: 1.39.2
napi: 4
openssl: 1.1.1c
icu: 64.2
unicode: 12.1
cldr: 35.1
tz: 2019a

**Comment by YoshinoriN** [comment]
You have to use [`{% raw %}`](https://hexo.io/docs/tag-plugins#Raw) tag like following.

```
{% raw %}  {#rgb} {% endraw %}
```

Please see https://github.com/hexojs/hexo/issues/1930#issuecomment-262469074

**Comment by eonun** [comment]
谢谢！
-_-  花费了一天的时间才找出来报错点（`{#`）  居然是这样的，谁能想到呢

**Comment by AllanZyne** [comment]
我在写 MathJax 时也发生了这种情况，就像
```
$$\def\P(#1){\operatorname{P}\left\{#1\right\}}$$
```
这也太坑了吧？普通的正文中竟然**可以**有引起 crash 的字符串，简直应该写进文档里。
为什么会这样？还有哪些像 `{#` 这样引起 crash 的字符串吗？

**Comment by SakuraWald** [comment]
This bug still exists in 2022.
I am using mathjax to define a macro
```
$$\newcommand\magic[1]{\textcolor{red}{#1}}$$
```

**Comment by SakuraWald** [comment]
> 我在写 MathJax 时也发生了这种情况，就像
> 
> ```
> $$\def\P(#1){\operatorname{P}\left\{#1\right\}}$$
> ```
> 
> 这也太坑了吧？普通的正文中竟然**可以**有引起 crash 的字符串，简直应该写进文档里。 为什么会这样？还有哪些像 `{#` 这样引起 crash 的字符串吗？

This bug still exists in 2022.
I am using mathjax to define a macro
```
$$\newcommand\magic[1]{\textcolor{red}{#1}}$$
```
