### ISSUE TITLE
"hexo new page" error

### ISSUE THREAD

**Issue by 1am-one** [hexojs/hexo#3757]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Node.js is higher than 6.9

## Question

When I type hexo new page "_else"
I want it to build a forder named "_else" in the forder "sourses"

t didn't do it and report error, which I find in troubleshooting says that "Make sure you are using soft tabs and add a space after colons." . But I did check them and the problem still.

this is the error report:
(the /aiguosb is my blog's root forder)

$ hexo new page "_else"
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 5, column 1:

^
at generateError (C:\Users\Administrator\Documents\GitHub\aiguosb\node_modules\js-yaml\lib\js-yaml\loader.js:167:10)
at throwError (C:\Users\Administrator\Documents\GitHub\aiguosb\node_modules\js-yaml\lib\js-yaml\loader.js:173:9)
at readBlockMapping (C:\Users\Administrator\Documents\GitHub\aiguosb\node_modules\js-yaml\lib\js-yaml\loader.js:1073:9)
at composeNode (C:\Users\Administrator\Documents\GitHub\aiguosb\node_modules\js-yaml\lib\js-yaml\loader.js:1359:12)
at readDocument (C:\Users\Administrator\Documents\GitHub\aiguosb\node_modules\js-yaml\lib\js-yaml\loader.js:1519:3)
at loadDocuments (C:\Users\Administrator\Documents\GitHub\aiguosb\node_modules\js-yaml\lib\js-yaml\loader.js:1575:5)
at Object.load (C:\Users\Administrator\Documents\GitHub\aiguosb\node_modules\js-yaml\lib\js-yaml\loader.js:1596:19)
at _getScaffold.then.then.frontMatter (C:\Users\Administrator\Documents\GitHub\aiguosb\node_modules\hexo\lib\hexo\post.js:125:66)
at tryCatcher (C:\Users\Administrator\Documents\GitHub\aiguosb\node_modules\bluebird\js\release\util.js:16:23)
at Promise._settlePromiseFromHandler (C:\Users\Administrator\Documents\GitHub\aiguosb\node_modules\bluebird\js\release\promise.js:517:31)
at Promise._settlePromise (C:\Users\Administrator\Documents\GitHub\aiguosb\node_modules\bluebird\js\release\promise.js:574:18)
at Promise._settlePromise0 (C:\Users\Administrator\Documents\GitHub\aiguosb\node_modules\bluebird\js\release\promise.js:619:10)
at Promise._settlePromises (C:\Users\Administrator\Documents\GitHub\aiguosb\node_modules\bluebird\js\release\promise.js:699:18)
at Promise._fulfill (C:\Users\Administrator\Documents\GitHub\aiguosb\node_modules\bluebird\js\release\promise.js:643:18)
at Promise._resolveCallback (C:\Users\Administrator\Documents\GitHub\aiguosb\node_modules\bluebird\js\release\promise.js:437:57)
at Promise._settlePromiseFromHandler (C:\Users\Administrator\Documents\GitHub\aiguosb\node_modules\bluebird\js\release\promise.js:529:17)
at Promise._settlePromise (C:\Users\Administrator\Documents\GitHub\aiguosb\node_modules\bluebird\js\release\promise.js:574:18)
at Promise._settlePromise0 (C:\Users\Administrator\Documents\GitHub\aiguosb\node_modules\bluebird\js\release\promise.js:619:10)
at Promise._settlePromises (C:\Users\Administrator\Documents\GitHub\aiguosb\node_modules\bluebird\js\release\promise.js:699:18)
at Promise._fulfill (C:\Users\Administrator\Documents\GitHub\aiguosb\node_modules\bluebird\js\release\promise.js:643:18)
at Promise._settlePromise (C:\Users\Administrator\Documents\GitHub\aiguosb\node_modules\bluebird\js\release\promise.js:587:21)
at Promise._settlePromise0 (C:\Users\Administrator\Documents\GitHub\aiguosb\node_modules\bluebird\js\release\promise.js:619:10)

Steps to reproduce the behavior

   1.  I open git bash on my blog's root forder.
   2. I type hexo new page "_else" and enter.
   3. The git bash just report error.

Hexo Configuration

I have check all the space after colon:

NexT Configuration

I have check all the part that I've changed 
there do are space after colon:

## Environment & Settings

**Node.js & npm version**

```
$ node -v
v10.16.3

$ npm -v
6.9.0
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.9.0"
  },
  "dependencies": {
    "hexo": "^3.9.0",
    "hexo-blog-encrypt": "^3.0.3",
    "hexo-deployer-git": "^2.0.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index-pin-top": "^0.2.2",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-marked": "^1.0.1",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.3"
  }
}

```

**Comment by 1am-one** [comment]
the theme next and landscape both meet this problem and I promise I haven't change anything in landscape

**Comment by YoshinoriN** [comment]
@1am-one Hi 👋 
Would you please tell me your `scaffolds/page.md`?
I think maybe `scaffolds/page.md`'s yaml syntax is something wrong.

Thanks :)

**Comment by 1am-one** [comment]
> 
> 
> @1am-one Hi wave
> Would you please tell me your `scaffolds/page.md`?
> I think maybe `scaffolds/page.md`'s yaml syntax is something wrong.
> 
> Thanks :)

---
title: {{ title }}
date: {{ date }}
ptype: page
purl: {{ type }}
---

The "ptype" and "purl" is my own-defined permalink

**Comment by YoshinoriN** [comment]
So, your `post.md` front-matter is following. Is it right?

```yaml
---
title: {{ title }}
date: {{ date }}
ptype: page
purl: {{ type }}
---
```

Do you add `---` separator?
Would you please delete `db.json` before `hexo new page _else`?

**Comment by 1am-one** [comment]
> 
> 
> @1am-one Hi wave
> Would you please tell me your `scaffolds/page.md`?
> I think maybe `scaffolds/page.md`'s yaml syntax is something wrong.
> 
> Thanks :)

uh...yes. I reset all the space after the colon. And the problem solved!
Maybe some space are not soft one.
Anyway, thank you very much!

**Comment by YoshinoriN** [comment]
You are welcome. Thanks :)
