### ISSUE TITLE
执行hexo g之后出现了错误

### ISSUE THREAD

**Issue by howtowin8** [hexojs/hexo#3771]
## Check List

Please check followings before submitting a new issue.

- [ ] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [ ] I have already searched existing issues and they are not help to me
- [ ] I examined error or warning messages and it's difficult to solve
- [ ] Node.js is higher than 6.9

## Question

TypeError: Cannot read property 'on' of undefined
    at E:\blog\site\scripts\responsive.js:56:17
    at new Promise (<anonymous>)
    at E:\blog\site\scripts\responsive.js:53:12
    at Array.map (<anonymous>)
    at Hexo.responsive (E:\blog\site\scripts\responsive.js:52:44)

**Comment by howtowin8** [comment]
ok,thank you. it is ok now.
