### ISSUE TITLE
安装hexo运行后报错 /usr/lib/node_modules/hexo-cli/node_modules/chokidar/index.js:150

### ISSUE THREAD

**Issue by wangzhilun** [hexojs/hexo#3781]
/usr/lib/node_modules/hexo-cli/node_modules/chokidar/index.js:150
  async remove(item) {
        ^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/hexo-cli/node_modules/hexo-fs/lib/fs.js:6:18)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)

**Comment by wangzhilun** [comment]
> @wangzhilun 兄弟 你怎么解决到

我的nodejs版本太低了。升级到了10版本可以了

**Comment by hongjin95** [comment]
升级nodejs 正解

**Comment by 408881465** [comment]
@wangzhilun   nodejs版本修改如下
language: node_js
node_js: stable

**Comment by King-996** [comment]
升级nodejs到最新稳定版，就OK了嘿嘿
