### ISSUE TITLE
如果文章的tag以数字3开头运行hexo s就会报错

### ISSUE THREAD

**Issue by note4** [hexojs/hexo#3840]
##标签示范
tags: [315消费者维权日] 

tags: [金山软件,金山毒霸,315消费者维权日] 

## 报错提示
ERROR Process failed: _posts/177.md
TypeError: str must be a string!
    at slugize (/Users/cccc/git/hexo-blog/node_modules/hexo-util/lib/slugize.js:9:38)
    at Model._Document.Document.<anonymous> (/Users/cccc/git/hexo-blog/node_modules/hexo/lib/models/tag.js:22:12)
    at Model._Document.Document.slug (/Users/cccc/git/hexo-blog/node_modules/warehouse/lib/types/virtual.js:70:22)
    at Model._Document.Document.Document.toObject (/Users/cccc/git/hexo-blog/node_modules/warehouse/lib/document.js:79:42)
    at Database._Model.Model.Model._insertOne (/Users/cccc/git/hexo-blog/node_modules/warehouse/lib/model.js:189:21)
    at /Users/cccc/git/hexo-blog/node_modules/warehouse/lib/model.js:214:17
    at tryCatcher (/Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/c'c'c'c/git/hexo-yijile/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/async.js:147:5)

**Comment by YoshinoriN** [comment]
Can not reproduce this phenomenon. Please write more details.

**Comment by SukkaW** [comment]
@note4 What about other numbers? Or just number `3`?

```markdown
---
tags:
  - 315
  - 2_Test
---
```

**Comment by note4** [comment]
> Can not reproduce this phenomenon in Hexo 4. Please write more details.

hexo: 3.8.0
hexo-cli: 1.1.0
os: Darwin 19.0.0 darwin x64
http_parser: 2.8.0
node: 10.15.3
v8: 6.8.275.32-node.51
uv: 1.23.2
zlib: 1.2.11
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0j
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e



ERROR Process failed: _posts/177.md
TypeError: str must be a string!
    at slugize (/Users/cccc/git/hexo-blog/node_modules/hexo-util/lib/slugize.js:9:38)
    at Model._Document.Document.<anonymous> (/Users/cccc/git/hexo-blog/node_modules/hexo/lib/models/tag.js:22:12)
    at Model._Document.Document.slug (/Users/cccc/git/hexo-blog/node_modules/warehouse/lib/types/virtual.js:70:22)
    at Model._Document.Document.Document.toObject (/Users/cccc/git/hexo-blog/node_modules/warehouse/lib/document.js:79:42)
    at Database._Model.Model.Model._insertOne (/Users/cccc/git/hexo-blog/node_modules/warehouse/lib/model.js:189:21)
    at /Users/cccc/git/hexo-blog/node_modules/warehouse/lib/model.js:214:17
    at tryCatcher (/Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/async.js:147:5)
ERROR Process failed: _posts/215.md
TypeError: str must be a string!
    at slugize (/Users/cccc/git/hexo-blog/node_modules/hexo-util/lib/slugize.js:9:38)
    at Model._Document.Document.<anonymous> (/Users/cccc/git/hexo-blog/node_modules/hexo/lib/models/tag.js:22:12)
    at Model._Document.Document.slug (/Users/cccc/git/hexo-blog/node_modules/warehouse/lib/types/virtual.js:70:22)
    at Model._Document.Document.Document.toObject (/Users/cccc/git/hexo-blog/node_modules/warehouse/lib/document.js:79:42)
    at Database._Model.Model.Model._insertOne (/Users/cccc/git/hexo-blog/node_modules/warehouse/lib/model.js:189:21)
    at /Users/cccc/git/hexo-blog/node_modules/warehouse/lib/model.js:214:17
    at tryCatcher (/Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/cccc/git/hexo-blog/node_modules/bluebird/js/release/async.js:147:5)
这是全部报错信息了

**Comment by note4** [comment]
> ```gfm
> tags:
>   - 315
>   - 2_Test
> ```

太诡异了，似乎是 `315消费者维权日` 这个TAG 触发的，315改成312都没问题，或者后面任意改一个字也都OK

**Comment by note4** [comment]
> Can not reproduce this phenomenon in Hexo 4. Please write more details.

难道hexo有词汇黑名单？其中就包含`315消费者维权日`？

**Comment by SukkaW** [comment]
@note4 Of course Hexo has no blacklisted words. You can review the Hexo's source code if you do not believe.

I wonder the number mixed with character might cause TypeError when Hexo read YAML. The safest way is to wrap your keywords into strings, for example `"315消费"`.

**Comment by snowyu** [comment]
yaml treat 315 as number, so the tag should 

```yml
tag
  - '315'
```

**Comment by note4** [comment]
黑名单只是玩笑话，很好奇这个bug的原理，今天发现又好了，谢谢各位大佬了。

弱弱的问一句，如果文件后缀为'.MD'就不会生成内容？

**Comment by curbengh** [comment]
> 如果文件后缀为'.MD'就不会生成内容

yes, it must be in lowercase `.md`. To avoid file creation issue, I recommend to always use lowercase in folder/filename especially in [case-insensitive](https://en.wikipedia.org/wiki/Case_preservation) file system used in Windows & Mac.

**Comment by note4** [comment]
> > 如果文件后缀为'.MD'就不会生成内容
> 
> yes, it must be in lowercase `.md`. To avoid file creation issue, I recommend to always use lowercase in folder/filename especially in [case-insensitive](https://en.wikipedia.org/wiki/Case_preservation) file system used in Windows & Mac.

thank you

**Comment by note4** [comment]
又遇到了相同的问题，导入的文字，标签第一个字是数字3就会报错，两种书写方式都试了，但是如果在3前面加一个任意数字，如1，就不会再报错。

Front-matter
```
---
layout: post 
title: "#360诉腾讯垄断案#微博投票腾讯真的输了票数？" 
date: 2013-12-20 18:45 
updated: 
tags: 
    - 腾讯
    - QQ
    - 微博
    - 360安全卫士
    - '360'
categories: [软件]
typecho_cid: '350' 
permalink: log/350.html 
---
```
报错
```
TypeError: str must be a string!
    at slugize (/Users/andy/git/hexo-yijile/node_modules/hexo-util/lib/slugize.js:10:38)
    at _Document.<anonymous> (/Users/andy/git/hexo-yijile/node_modules/hexo/lib/models/tag.js:22:12)
    at _Document.setGetter [as slug] (/Users/andy/git/hexo-yijile/node_modules/warehouse/lib/types/virtual.js:59:24)
    at _Document.toObject (/Users/andy/git/hexo-yijile/node_modules/warehouse/lib/document.js:73:44)
    at _Model._insertOne (/Users/andy/git/hexo-yijile/node_modules/warehouse/lib/model.js:157:25)
    at Promise.using (/Users/andy/git/hexo-yijile/node_modules/warehouse/lib/model.js:179:63)
    at tryCatcher (/Users/andy/git/hexo-yijile/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/andy/git/hexo-yijile/node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/Users/andy/git/hexo-yijile/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/andy/git/hexo-yijile/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/andy/git/hexo-yijile/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/andy/git/hexo-yijile/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/andy/git/hexo-yijile/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/andy/git/hexo-yijile/node_modules/bluebird/js/release/promise.js:673:18)
    at PromiseArray._resolve (/Users/andy/git/hexo-yijile/node_modules/bluebird/js/release/promise_array.js:127:19)
    at PromiseArray._promiseFulfilled (/Users/andy/git/hexo-yijile/node_modules/bluebird/js/release/promise_array.js:145:14)
    at Promise._settlePromise (/Users/andy/git/hexo-yijile/node_modules/bluebird/js/release/promise.js:609:26)
    at Promise._settlePromise0 (/Users/andy/git/hexo-yijile/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/andy/git/hexo-yijile/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/Users/andy/git/hexo-yijile/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/andy/git/hexo-yijile/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/andy/git/hexo-yijile/node_modules/bluebird/js/release/async.js:102:5)
```

hexo 版本
```
hexo: 4.0.0
hexo-cli: 1.1.0
os: Darwin 19.0.0 darwin x64
http_parser: 2.8.0
node: 10.15.3
v8: 6.8.275.32-node.51
uv: 1.23.2
zlib: 1.2.11
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0j
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e

```

文章并不重要，就是比较想知道原因😂

**Comment by note4** [comment]
刚刚进行了测试
依次填写及结果
```
tags:
  - 315
```
正常 

```
tags:
  - 315消
```
正常

```
tags:
  - 315消费者维权
```
正常

```
tags:
  - 315消费者维权日
```
报错 😂

**Comment by note4** [comment]
[package.txt](https://github.com/hexojs/hexo/files/3954565/package.txt)
[package-lock.txt](https://github.com/hexojs/hexo/files/3954566/package-lock.txt)

**Comment by note4** [comment]
把标签移动到另一个hexo blog 文章中却没有报错，可能是插件冲突

**Comment by note4** [comment]
找到问题的所在了
因为_config.yml tagmap 值没用用`" "`

### 会报错
```
tag_map:
    360: 360
```

### 不会报错
```
tag_map:
    360: “360”
```

因为报错提示的是md文章，所以一直没有找到问题所在。bengkui

**Comment by curbengh** [comment]
Issue resolved then?

**Comment by note4** [comment]
> Issue resolved then?

solved

**Comment by note4** [comment]
The file pointed to by the error is inaccurate
报错所指向文件不准确
