### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined when run hexo new post

### ISSUE THREAD

**Issue by hiyoung123** [hexojs/hexo#3856]
$hexo new post "yun"
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError: Cannot read property 'replace' of undefined
    at Tag.render (/home/liuhaiyang/YoungBlog/node_modules/hexo/lib/extend/tag.js:118:13)
    at /home/liuhaiyang/YoungBlog/node_modules/hexo/lib/hexo/post.js:127:16
    at tryCatcher (/home/liuhaiyang/YoungBlog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/liuhaiyang/YoungBlog/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/liuhaiyang/YoungBlog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/liuhaiyang/YoungBlog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/liuhaiyang/YoungBlog/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/home/liuhaiyang/YoungBlog/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/home/liuhaiyang/YoungBlog/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/home/liuhaiyang/YoungBlog/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/home/liuhaiyang/YoungBlog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/liuhaiyang/YoungBlog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/liuhaiyang/YoungBlog/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/home/liuhaiyang/YoungBlog/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/home/liuhaiyang/YoungBlog/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/home/liuhaiyang/YoungBlog/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/home/liuhaiyang/YoungBlog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/liuhaiyang/YoungBlog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/liuhaiyang/YoungBlog/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/home/liuhaiyang/YoungBlog/node_modules/bluebird/js/release/promise.js:673:18)
    at /home/liuhaiyang/YoungBlog/node_modules/bluebird/js/release/nodeback.js:42:21
    at /home/liuhaiyang/YoungBlog/node_modules/graceful-fs/graceful-fs.js:115:16

**Comment by hiyoung123** [comment]
已解决，post.md的---后面多了个空格
