### ISSUE TITLE
使用FTP部署博客的时候出错？？？

### ISSUE THREAD

**Issue by suyin-long** [hexojs/hexo#3883]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than 8.6.0

## Environment & Settings

**Node.js & npm version**

```
npm v6.12.1
node v10.16.0
```

**Your site `_config.yml`** (Optional)

```
deploy:
  type: ftpsync
  host: localhost
  user: www_suyin_blog_club
  pass: 22tarYLKjX8PFHsy
  remote: /www/wwwroot/www.suyin-blog.club
  port: [port]
  ignore: [ignore]
  connections: [connections]
  verbose: [true|false]
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
hexo-site@0.0.0 E:\Hexo
+-- bootstrap@3.4.1
+-- canvas-nest.js@2.0.4
+-- gitalk@1.5.0
+-- hexo@4.0.0
+-- hexo-asset-image@0.0.5 (git+https://github.com/CodeFalling/hexo-asset-image.git#3c114cf0c0343ab28469635085b225fcae7fb9d3)
+-- hexo-auto-excerpt@0.0.1 (github:theme-next/hexo-auto-excerpt#4e48e0515a4fe2bc7d7225c724f4ef48a92d5093)
+-- hexo-blog-encrypt@3.0.3
+-- hexo-deployer-ftpsync@0.1.1
+-- hexo-deployer-git@2.0.0
+-- hexo-enhancer@1.0.7
+-- hexo-filter-optimize@0.2.7
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-feed@2.0.0
+-- hexo-generator-index@1.0.0
+-- hexo-generator-searchdb@1.1.0
+-- hexo-generator-tag@1.0.0
+-- hexo-related-popular-posts@3.0.6
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@2.0.0
+-- hexo-renderer-stylus@1.1.0
+-- hexo-server@1.0.0
+-- hexo-symbols-count-time@0.6.3
+-- hexo-tag-plugin@0.1.0 (github:theme-next/hexo-tag-plugin#695b7b6296778a671a4761f713cf11516a779398)
+-- hexo-theme-next-anchor@1.0.3
`-- shelljs@0.8.3

```

**Your package.json `package.json`**

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "4.0.0"
  },
  "dependencies": {
    "bootstrap": "^3.4.1",
    "canvas-nest.js": "^2.0.4",
    "gitalk": "^1.5.0",
    "hexo": "^4.0.0",
    "hexo-asset-image": "git+https://github.com/CodeFalling/hexo-asset-image.git",
    "hexo-auto-excerpt": "github:theme-next/hexo-auto-excerpt",
    "hexo-blog-encrypt": "^3.0.3",
    "hexo-deployer-ftpsync": "^0.1.1",
    "hexo-deployer-git": "^2.0.0",
    "hexo-enhancer": "^1.0.7",
    "hexo-filter-optimize": "^0.2.7",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^2.0.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-searchdb": "^1.1.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-related-popular-posts": "^3.0.6",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0",
    "hexo-symbols-count-time": "^0.6.3",
    "hexo-tag-plugin": "github:theme-next/hexo-tag-plugin",
    "hexo-theme-next-anchor": "^1.0.3",
    "shelljs": "^0.8.3"
  }
}

```

## Others

问题：
使用ftp部署博客报错，错误如下：
`events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: connect EADDRNOTAVAIL 127.0.0.1 - Local (0.0.0.0:51869)
    at internalConnect (net.js:881:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:294:19)
    at GetAddrInfoReqWrap.emitLookup [as callback] (net.js:1028:9)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:61:10)
Emitted 'error' event at:
    at Stream.<anonymous> (E:\Hexo\node_modules\jsftp\lib\jsftp.js:91:32)
    at Stream.emit (events.js:198:13)
    at Socket.reemit (E:\Hexo\node_modules\duplexer\index.js:85:16)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)`

请问该怎么解决？谢谢！

**Comment by suyin-long** [comment]
参考链接：https://hexo.io/docs/one-command-deployment

**Comment by YoshinoriN** [comment]
Is the deployment destination correct?
By your setting is `localhost `.

**Comment by suyin-long** [comment]
我把他设置为IP地址也不行啊，还是报错！
还有用Rsync也不行，也是报错，不知所措！

# FTPSync
# deploy:
#   type: ftpsync
#   host: 123.207.147.235
#   user: www_suyin_blog_club
#   pass: 22tarYLKjX8PFHsy
#   remote: /www/wwwroot/www.suyin-blog.club
#   port: 21
#   ignore: [ignore]
#   connections: [connections]
#   verbose: true

# Rsync
# deploy:
#   type: rsync
#   host: 123.207.147.235
#   user: root
#   root: /www/wwwroot/www.suyin-blog.club
#   port: 22
#   delete: [true|false]
#   verbose: [true|false]
#   ignore_errors: [true|false]

**Comment by suyin-long** [comment]
我把他设置为IP地址也不行啊，还是报错！
还有用Rsync也不行，也是报错，不知所措！

# FTPSync
# deploy:
#   type: ftpsync
#   host: 123.207.147.235
#   user: www_suyin_blog_club
#   pass: 22tarYLKjX8PFHsy
#   remote: /www/wwwroot/www.suyin-blog.club
#   port: 21
#   ignore: [ignore]
#   connections: [connections]
#   verbose: true

# Rsync
# deploy:
#   type: rsync
#   host: 123.207.147.235
#   user: root
#   root: /www/wwwroot/www.suyin-blog.club
#   port: 22
#   delete: [true|false]
#   verbose: [true|false]
#   ignore_errors: [true|false]

**Comment by YoshinoriN** [comment]
@suyin-long 
I sent an email to you. If you received my email, please reply before submitting a new comment.

Thanks :)
