### ISSUE TITLE
hexo 命令只有help init version 三个command   官网方法未解决

### ISSUE THREAD

**Issue by liuqiqi1** [hexojs/hexo#3923]
根据官网把这一段内容放到package.json中后 报错如下
{
--
"hexo": {
"version": "3.2.2"
}
}

FATAL Cannot read property 'code' of undefined
TypeError: Cannot read property 'code' of undefined
    at /home/node-v12.13.1-linux-x64/lib/node_modules/hexo-cli/lib/find_pkg.js:21:26
    at tryCatcher (/home/node-v12.13.1-linux-x64/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/node-v12.13.1-linux-x64/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/node-v12.13.1-linux-x64/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/node-v12.13.1-linux-x64/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/node-v12.13.1-linux-x64/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/node-v12.13.1-linux-x64/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/node-v12.13.1-linux-x64/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/node-v12.13.1-linux-x64/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/node-v12.13.1-linux-x64/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)

**Comment by curbengh** [comment]
what specific content you're trying to insert to package.json?
which specific page of hexo.io are you referring to?

**Comment by stevenjoezhang** [comment]
If I understand correctly, you may have added content that does not conform to the json syntax to `package.json`. The error message appears when `hexo-cli` is reading `package.json`.

https://github.com/hexojs/hexo-cli/blob/9027b1996ca5bea66b895493f462a5afe3606347/lib/find_pkg.js#L21
