### ISSUE TITLE
hexo g TypeError [ERR_INVALID_URL]

### ISSUE THREAD

**Issue by 799953468** [hexojs/hexo#3988]
TypeError [ERR_INVALID_URL]: Invalid URL: http://www.sina.com 时，浏览器将显示新浪的首页。在这个过程中，浏览器都干了哪些 事情呢？通过Network的记录，我们就可以知道。在Network中，找到www.sina.com那条记录，点击，右侧将显示Request
    at onParseError (internal/url.js:256:9)
    at new URL (internal/url.js:332:5)
    at isExternalLink (E:\blog\node_modules\hexo-util\lib\is_external_link.js:17:16)
    at E:\blog\node_modules\hexo\lib\plugins\filter\after_render\external_link.js:23:35
    at String.replace (<anonymous>)
    at Hexo.externalLinkFilter (E:\blog\node_modules\hexo\lib\plugins\filter\after_render\external_link.js:22:15)
    at Hexo.tryCatcher (E:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (E:\blog\node_modules\bluebird\js\release\method.js:15:34)
    at E:\blog\node_modules\hexo\lib\extend\filter.js:61:50
    at tryCatcher (E:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (E:\blog\node_modules\bluebird\js\release\reduce.js:166:18)
    at Object.gotAccum (E:\blog\node_modules\bluebird\js\release\reduce.js:155:25)
    at Object.tryCatcher (E:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\blog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (E:\blog\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (E:\blog\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (E:\blog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\blog\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\blog\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:445:21)

**Comment by curbengh** [comment]
can you attach the full link of the sina.com?
