### ISSUE TITLE
生成静态页面时，创建了一个新的page,但是hexo g的时候说page.swig有问题，是我太菜了看不懂/(ㄒoㄒ)/~~

### ISSUE THREAD

**Issue by essesy** [hexojs/hexo#4085]
$ hexo g
INFO  Start processing
ERROR Process failed: layout/page.swig
Error: Unexpected dot on line 4 in file E:\blog\themes\hexo-theme-next5-polished-master\layout\page.swig.
    at Object.exports.throwError (E:\blog\node_modules\swig-templates\lib\utils.js:188:9)
    at TokenParser.parseVar (E:\blog\node_modules\swig-templates\lib\parser.js:472:15)
    at TokenParser.parseToken (E:\blog\node_modules\swig-templates\lib\parser.js:357:14)
    at E:\blog\node_modules\swig-templates\lib\parser.js:112:12
    at Object.exports.each (E:\blog\node_modules\swig-templates\lib\utils.js:45:11)
    at TokenParser.parse (E:\blog\node_modules\swig-templates\lib\parser.js:102:11)
    at parseTag (E:\blog\node_modules\swig-templates\lib\parser.js:708:12)
    at E:\blog\node_modules\swig-templates\lib\parser.js:778:15
    at Object.exports.each (E:\blog\node_modules\swig-templates\lib\utils.js:45:11)
    at Object.exports.parse (E:\blog\node_modules\swig-templates\lib\parser.js:755:9)
    at exports.Swig.parse (E:\blog\node_modules\swig-templates\lib\swig.js:383:19)
    at exports.Swig.precompile (E:\blog\node_modules\swig-templates\lib\swig.js:526:23)
    at Object.compile (E:\blog\node_modules\swig-templates\lib\swig.js:651:16)
    at Function.swigRenderer.compile (E:\blog\node_modules\hexo\lib\plugins\renderer\swig.js:41:47)
    at viewFn.View._precompile (E:\blog\node_modules\hexo\lib\theme\view.js:129:31)
    at viewFn.View (E:\blog\node_modules\hexo\lib\theme\view.js:26:8)
    at new viewFn (E:\blog\node_modules\hexo\lib\theme\index.js:35:15)
    at Theme.setView (E:\blog\node_modules\hexo\lib\theme\index.js:71:18)
    at E:\blog\node_modules\hexo\lib\theme\processors\view.js:14:14
    at tryCatcher (E:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\blog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\blog\node_modules\bluebird\js\release\promise.js:604:18)
WARN  ===============================================================
WARN  ========================= ATTENTION! ==========================
WARN  ===============================================================
WARN   NexT repository is moving here: https://github.com/theme-next
WARN  ===============================================================
WARN   It's rebase to v6.0.0 and future maintenance will resume there
WARN  ===============================================================
INFO  Files loaded in 2.02 s

**Comment by YoshinoriN** [comment]
Please check `page.swig` line 4.

> Error: Unexpected dot on line 4 in file E:\blog\themes\hexo-theme-next5-polished-master\layout\page.swig.

**Comment by essesy** [comment]
> Please check `page.swig` line 4.
> 
> > Error: Unexpected dot on line 4 in file E:\blog\themes\hexo-theme-next5-polished-master\layout\page.swig.

ok!thanks,I have solved this problem.
