### ISSUE TITLE
Unhandled rejection TypeError: \themes\yilia\layout\tag.ejs:1

### ISSUE THREAD

**Issue by MrSunCodes** [hexojs/hexo#4091]
I add categories and tags on my home page, but when I set /source/categories/index.md 
`layout: "category"` ，and turn to the 127.0.0.1/categories/, it cause the problem:
```
Unhandled rejection TypeError: F:\MyBlog\themes\yilia\layout\tag.ejs:1
 >> 1| <%- partial('_partial/archive', {pagination: config.tag, index: true}) %>

F:\MyBlog\themes\yilia\layout\_partial\archive.ejs:15
    13| <% } else { %>
    14|   <% var last; %>
 >> 15|   <% page.posts.each(function(post, i){ %>
    16|     <% var year = post.date.year(); %>
    17|     <% if (last != year){ %>
    18|       <% if (last != null){ %>

Cannot read property 'each' of undefined
    at eval (F:\MyBlog\themes\yilia\layout\_partial\archive.ejs:41:19)
    at archive (F:\MyBlog\node_modules\ejs\lib\ejs.js:682:17)
    at viewFn._compiledSync.locals [as _compiledSync] (F:\MyBlog\node_modules\hexo\lib\theme\view.js:132:22)
    at viewFn.View.renderSync (F:\MyBlog\node_modules\hexo\lib\theme\view.js:60:23)
    at Object.partial (F:\MyBlog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (F:\MyBlog\themes\yilia\layout\tag.ejs:10:17)
    at tag (F:\MyBlog\node_modules\ejs\lib\ejs.js:682:17)
    at viewFn._compiled.locals [as _compiled] (F:\MyBlog\node_modules\hexo\lib\theme\view.js:136:48)
    at viewFn.View.render (F:\MyBlog\node_modules\hexo\lib\theme\view.js:41:15)
    at F:\MyBlog\node_modules\hexo\lib\hexo\index.js:61:21
    at tryCatcher (F:\MyBlog\node_modules\bluebird\js\release\util.js:16:23)
    at F:\MyBlog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (F:\MyBlog\node_modules\hexo\lib\hexo\router.js:126:3)
    at RouteStream.Readable.read (_stream_readable.js:457:10)
    at resume_ (_stream_readable.js:933:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

```
**need help guys! thanks!**

**Comment by YoshinoriN** [comment]
I think, maybe this is a theme issue.
Please ask to it to [hexo-theme-yilia](https://github.com/voidking/hexo-theme-yilia).

Thanks :)

**Comment by MrSunCodes** [comment]
> I think, maybe this is a theme issue.
> Please ask to it to [hexo-theme-yilia](https://github.com/voidking/hexo-theme-yilia) once.
> 
> Thanks :)

thanks,i will try that.
