### ISSUE TITLE
run $ hexo s and get 'fatal error'

### ISSUE THREAD

**Issue by evanyf** [hexojs/hexo#4095]
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/d ocs/troubleshooting.html                                                         
SyntaxError: Unexpected end of JSON input                                            
at JSON.parse ()                                                      
at Hexo.jsonRenderer (C:\Documents\Github_Blog\node_modules\hexo\lib\plugins \renderer\json.js:4:15)                                                              
at Hexo.tryCatcher (C:\Documents\Github_Blog\node_modules\bluebird\js\releas e\util.js:16:23)                                                                     at Hexo. (C:\Documents\Github_Blog\node_modules\bluebird\js\relea se\method.js:15:34)                                                                  at Promise.then.text (C:\Documents\Github_Blog\node_modules\hexo\lib\hexo\re nder.js:60:20)                                                                       at tryCatcher (C:\Documents\Github_Blog\node_modules\bluebird\js\release\uti l.js:16:23)                                                                          at Promise._settlePromiseFromHandler (C:\Documents\Github_Blog\node_modules\ bluebird\js\release\promise.js:512:31)                                               
at Promise._settlePromise (C:\Documents\Github_Blog\node_modules\bluebird\js \release\promise.js:569:18)                                                          
at Promise._settlePromiseCtx (C:\Documents\Github_Blog\node_modules\bluebird \js\release\promise.js:606:10)                                                       
at _drainQueueStep (C:\Documents\Github_Blog\node_modules\bluebird\js\releas e\async.js:142:12)                                                                   at _drainQueue (C:\Documents\Github_Blog\node_modules\bluebird\js\release\as ync.js:131:9)                                                                        at Async._drainQueues (C:\Documents\Github_Blog\node_modules\bluebird\js\rel ease\async.js:147:5)                                                                 
at Immediate.Async.drainQueues [as _onImmediate] (C:\Documents\Github_Blog\n ode_modules\bluebird\js\release\async.js:17:14)                                      
at runCallback (timers.js:705:18)                                                
at tryOnImmediate (timers.js:676:5)                                             
 at processImmediate (timers.js:658:5)
--

**Comment by BenFromHRBUST** [comment]
Hey, guy! Have you solved the problem? I meet the same problem, and I cannot find any way to deal with it.
