### ISSUE TITLE
Show Erros TypeError [ERR_INVALID_URL] When Generate Static Pages

### ISSUE THREAD

**Issue by qinyuanpei** [hexojs/hexo#4107]
## Check List

Please check followings before submitting a new issue.

- [ &radic;] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [ &radic;] I have already searched existing issues and they are not help  to me
- [&radic; ] I examined error or warning messages and it's difficult to solve
- [ &radic;] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [ &radic;] Node.js is higher than 8.6.0

## Expected behavior
Upgrade `Hexo` from `v3.4.4` to `v4.2.0`, then clean and generate static pages should be fine.

## Actual behavior
I can't generate static pages via `hexo g`, the terminal show errors as follows：
```
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.htm                                                                                                    l
TypeError [ERR_INVALID_URL]: Invalid URL: http://localhost:4000就可以看到如下画面(这里的端口号为4000)：
    at onParseError (internal/url.js:243:9)
    at new URL (internal/url.js:319:5)
    at C:\Users\admin\Downloads\Projects\Blog\node_modules\hexo\node_modules\hexo-util\lib\is_external_                                                                                                    link.js:21:18
    at Cache.apply (C:\Users\admin\Downloads\Projects\Blog\node_modules\hexo\node_modules\hexo-util\lib                                                                                                    \cache.js:27:46)
    at isExternalLink (C:\Users\admin\Downloads\Projects\Blog\node_modules\hexo\node_modules\hexo-util\                                                                                                    lib\is_external_link.js:19:16)
    at C:\Users\admin\Downloads\Projects\Blog\node_modules\hexo\lib\plugins\filter\after_render\externa                                                                                                    l_link.js:23:35
    at String.replace (<anonymous>)
    at Hexo.externalLinkFilter (C:\Users\admin\Downloads\Projects\Blog\node_modules\hexo\lib\plugins\fi                                                                                                    lter\after_render\external_link.js:22:15)
    at Hexo.tryCatcher (C:\Users\admin\Downloads\Projects\Blog\node_modules\hexo\node_modules\bluebird\                                                                                                    js\release\util.js:16:23)
    at Hexo.<anonymous> (C:\Users\admin\Downloads\Projects\Blog\node_modules\hexo\node_modules\bluebird                                                                                                    \js\release\method.js:15:34)
    at C:\Users\admin\Downloads\Projects\Blog\node_modules\hexo\lib\extend\filter.js:62:52
    at tryCatcher (C:\Users\admin\Downloads\Projects\Blog\node_modules\hexo\node_modules\bluebird\js\re                                                                                                    lease\util.js:16:23)
    at Object.gotValue (C:\Users\admin\Downloads\Projects\Blog\node_modules\hexo\node_modules\bluebird\                                                                                                    js\release\reduce.js:166:18)
    at Object.gotAccum (C:\Users\admin\Downloads\Projects\Blog\node_modules\hexo\node_modules\bluebird\                                                                                                    js\release\reduce.js:155:25)
    at Object.tryCatcher (C:\Users\admin\Downloads\Projects\Blog\node_modules\hexo\node_modules\bluebir                                                                                                    d\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\admin\Downloads\Projects\Blog\node_modules\hexo\node                                                                                                    _modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\admin\Downloads\Projects\Blog\node_modules\hexo\node_modules\bl                                                                                                    uebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (C:\Users\admin\Downloads\Projects\Blog\node_modules\hexo\node_modules                                                                                                    \bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (C:\Users\admin\Downloads\Projects\Blog\node_modules\hexo\node_modules\bluebird\                                                                                                    js\release\async.js:97:12)
    at _drainQueue (C:\Users\admin\Downloads\Projects\Blog\node_modules\hexo\node_modules\bluebird\js\r                                                                                                    elease\async.js:86:9)
    at Async._drainQueues (C:\Users\admin\Downloads\Projects\Blog\node_modules\hexo\node_modules\bluebi                                                                                                    rd\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\admin\Downloads\Projects\Blog\node_modul                                                                                                    es\hexo\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
````
It seems like caused by `\hexo-util\lib\is_external_link.js` when Hexo try to initialize new `URL`. 
The url of this blog is `http://localhost:4000` and it doesn't  changes in _config.yml                                                                

## How to reproduce?

* Uninstall Hexo(v3.4.4)
```
npm uninstall hexo
```
* Install Hexo(v4.2.0)
```
npm install hexo
```
* Install hexo-util(v1.8.1)
```
npm uninstall hexo-util
```
* Clean & Generate
```
hexo clean
hexo g
```

## Environment & Settings
None

**Node.js & npm version**
Nodejs: 12.14.1
npm: 6.13.4

**Your site `_config.yml`** (Optional)
https://raw.githubusercontent.com/qinyuanpei/qinyuanpei.github.io/blog/_config.yml

**Your theme `_config.yml`** (Optional)
None

**Hexo and Plugin version(`npm ls --depth 0`)**

```
+-- UNMET PEER DEPENDENCY hexo@4.2.0
+-- hexo-abbrlink@2.0.5
+-- hexo-all-minifier@0.5.3
+-- hexo-codepen@0.1.1
+-- hexo-deployer-git@0.3.1
+-- hexo-douban-plus@1.1.3
+-- hexo-generator-archive@0.1.5
+-- hexo-generator-baidu-sitemap@0.1.6
+-- hexo-generator-category@0.1.3
+-- hexo-generator-feed@1.2.2
+-- hexo-generator-index@0.1.3
+-- hexo-generator-json-content@3.0.1
+-- hexo-generator-portfolio@1.0.2
+-- hexo-generator-search@2.4.0
+-- hexo-generator-sitemap@1.2.0
+-- hexo-generator-tag@0.1.2
+-- hexo-helper-live2d@3.1.1
+-- hexo-offline@1.0.0
+-- hexo-reading-time@1.0.3
+-- hexo-renderer-ejs@0.1.1
+-- hexo-renderer-less@0.1.3
+-- hexo-renderer-marked@0.2.11
+-- hexo-renderer-stylus@0.2.3
+-- hexo-server@0.1.3
+-- hexo-tag-aplayer@3.0.4
+-- hexo-tag-cloudmusic@1.2.3
+-- hexo-util@1.8.1
+-- live2d-widget-model-hijiki@1.0.5
+-- live2d-widget-model-shizuku@1.0.5
+-- live2d-widget-model-tororo@1.0.5
+-- live2d-widget-model-tsumiki@1.0.5
+-- lunr@2.3.6
`-- parcel-bundler@1.12.4

```

**Your package.json `package.json`**
https://raw.githubusercontent.com/qinyuanpei/qinyuanpei.github.io/blog/package.json

**Comment by SukkaW** [comment]
Add a space between `http://localhost:4000` and the content after.

**Comment by qinyuanpei** [comment]
Actually，the `url` of blog is `https://blog.yuanpei.me` and `https://qinyuanpei.github.io`，`http://localhost:4000` is just used in development. Add some spsces to it？

**Comment by SukkaW** [comment]
@qinyuanpei In your post.

Log can't show more clearly: `TypeError [ERR_INVALID_URL]: Invalid URL: http://localhost:4000就可以看到如下画面(这里的端口号为4000)：`.

Can't you notice the log?

**Comment by qinyuanpei** [comment]
I know. But it is fine in previous version.
Should I try to modify the post which contains 'http://localhost:4000'?

**Comment by qinyuanpei** [comment]
Fixed by checking content of post, Thanks

**Comment by ProfessorX** [comment]
> 检查一下的md文件(${hexo}/source中)，是否存在错误的url，如果存在，新版本的hexo会抛错
> 
> Check the md file (${hexo}/source) for the wrong url, and if true, the new version of hexo will be thrown wrong

-------
找到出错原因了。

新版本hexo 对md文件中
作者：秦怡丁
链接：<https://www.zhihu.com/question/36540597/answer/129987936>
来源：知乎
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。

这种有 `//` 的编译无法支持，会报错。  不过很奇怪，为啥会报无效url.

-------
ref issue:  https://github.com/theme-next/hexo-theme-next/issues/1370

**Comment by ProfessorX** [comment]
老版本的知乎转载中，链接的引用是带了尖括号的 <> 所以parser无法正确识别里面的链接

LOL

新版本就没这个问题了。

可以关了。

···
作者：匿名用户
链接：<https://www.zhihu.com/question/35190992/answer/83037354>
来源：知乎
···

for example

**Comment by qinyuanpei** [comment]
我是博客中某些文章举例的时候，使用了类似localhost:8080这样的字样，然后新版的Hexo认为这是一个链接，在生成的时候就会报错，我最后修改为`localhost:8080`就好了。

**Comment by qinyuanpei** [comment]
新版本生成速度确实不错，为作者点赞！
