### ISSUE TITLE
More detailed information for "Template render error: (unknown path)"

### ISSUE THREAD

**Issue by TingxunShi** [hexojs/hexo#4109]
## Check List

Please check followings before submitting a new feature request.

- [ ] I have already read [Docs page](https://hexo.io/docs/)
- [ ] I have already searched existing issues

## Feature Request

Currently I am stucking with a very common issue: hexo failed to generate pages, gave the following information 
```
[myname@myname-pc blog_src]$ hexo g
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
Template render error: (unknown path)
  Error: expected end of comment, got end of file
    at Object._prettifyError (/home/myname/Projects/blog_src/node_modules/nunjucks/src/lib.js:36:11)
    at Template.render (/home/myname/Projects/blog_src/node_modules/nunjucks/src/environment.js:542:21)
    at Environment.renderString (/home/myname/Projects/blog_src/node_modules/nunjucks/src/environment.js:380:17)
    at /home/myname/Projects/blog_src/node_modules/hexo/lib/extend/tag.js:120:48
    at tryCatcher (/home/myname/Projects/blog_src/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.fromNode.Promise.fromCallback (/home/myname/Projects/blog_src/node_modules/bluebird/js/release/promise.js:209:30)
    at Tag.render (/home/myname/Projects/blog_src/node_modules/hexo/lib/extend/tag.js:120:18)
    at Object.onRenderEnd (/home/myname/Projects/blog_src/node_modules/hexo/lib/hexo/post.js:288:20)
    at /home/myname/Projects/blog_src/node_modules/hexo/lib/hexo/render.js:64:19
    at tryCatcher (/home/myname/Projects/blog_src/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/myname/Projects/blog_src/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/myname/Projects/blog_src/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/myname/Projects/blog_src/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/myname/Projects/blog_src/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/home/myname/Projects/blog_src/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/myname/Projects/blog_src/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/myname/Projects/blog_src/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues (/home/myname/Projects/blog_src/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
```

even add `--debug` option seems it was rendering **all** markdown files, but it didn't show which file caused the failure

Could you please kindly add more detailed information for this error? It would be perfect to have 

- The bad file
- The bad line
- Recommended modification (e.g. change {{ to { {)

Many thanks

**Comment by Aqua-Dream** [comment]
same problem

**Comment by stevenjoezhang** [comment]
In fact, the details of the error message are limited by nunjucks. Maybe you can open an Issue here: https://github.com/mozilla/nunjucks/issues
