### ISSUE TITLE
Post.js doesn't escape data with double quote characters

### ISSUE THREAD

**Issue by smroe** [hexojs/hexo#4142]
## Expected behaviour
Import of xml2js file (created from Joomla site) to create a set of .md files representing the origin Joomla site.

## Actual behavior
YAML processing exception thrown:
YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 2, column 5:
    date: 2011-11-14 14:38:13
        ^
    at generateError (<>\import\node_modules\js-yaml\lib\js-yaml\loader.js:167:10)
    at throwError (<>\import\node_modules\js-yaml\lib\js-yaml\loader.js:173:9)
    at readBlockMapping (<>\import\node_modules\js-yaml\lib\js-yaml\loader.js:1073:9)
    at composeNode (<>\import\node_modules\js-yaml\lib\js-yaml\loader.js:1359:12)
    at readDocument (<>\import\node_modules\js-yaml\lib\js-yaml\loader.js:1519:3)
    at loadDocuments (<>\import\node_modules\js-yaml\lib\js-yaml\loader.js:1575:5)
    at load (<>\import\node_modules\js-yaml\lib\js-yaml\loader.js:1596:19)
    at _getScaffold.then.then.frontMatter (<>\import\node_modules\hexo\lib\hexo\post.js:149:63)
    at tryCatcher (<>\import\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (<>\import\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (<>\import\node_modules\bluebird\js\release\promise.js:604:18)

## Possible Solution
I have traced this and think that the problem is in post.js @ PostRenderCache.prepareFrontMatter. The current string case assumes that the **item** variable doesn't include any double quotation marks. If it does, then the resulting data[key] value has an incorrect format.

I don't know if this will impact elsewhere, but I think that the last case needs to be modified to:
```javascript
for (const key of Object.keys(data)) {
    const item = data[key];

    if (moment.isMoment(item)) {
      data[key] = item.utc().format('YYYY-MM-DD HH:mm:ss');
    } else if (moment.isDate(item)) {
      data[key] = moment.utc(item).format('YYYY-MM-DD HH:mm:ss');
    } else if (typeof item === 'string') {
      data[key] = `"` + item.replace( /"/g, '\\"')  + `"`;
    }
  }

  return data;
```

**Comment by SukkaW** [comment]
Would you mind providing me about the exact front-matter of your markdown file?

**Comment by smroe** [comment]
The problem occurs when using the Joomla migrator, so you need to use an xml2js file. Mine is 100+Meg in size, so I have distilled it into a single article (at a much more friendly 2k).

Migrating the attachment, via: 
> hexo migrate joomla input.xml

results in the exception. Escaping the " characters in the title (via the above adjustment) sorts the problem.
[input.zip](https://github.com/hexojs/hexo/files/4236681/input.zip)
