### ISSUE TITLE
执行  hexo s -d后报错

### ISSUE THREAD

**Issue by InfiniteYinux** [hexojs/hexo#4156]
执行  hexo s -d后报错

TypeError [ERR_INVALID_URL]: Invalid URL: http://localhost:8080”
    at onParseError (internal/url.js:257:9)
    at new URL (internal/url.js:333:5)
    at E:\HexoBlog\Hexo\node_modules\hexo\node_modules\hexo-util\lib\is_external_link.js:21:18
    at Cache.apply (E:\HexoBlog\Hexo\node_modules\hexo\node_modules\hexo-util\lib\cache.js:27:46)
    at isExternalLink (E:\HexoBlog\Hexo\node_modules\hexo\node_modules\hexo-util\lib\is_external_link.js:19:16)
    at E:\HexoBlog\Hexo\node_modules\hexo\lib\plugins\filter\after_render\external_link.js:23:35
    at String.replace (<anonymous>)
    at Hexo.externalLinkFilter (E:\HexoBlog\Hexo\node_modules\hexo\lib\plugins\filter\after_render\external_link.js:22:15)
    at Hexo.tryCatcher (E:\HexoBlog\Hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (E:\HexoBlog\Hexo\node_modules\bluebird\js\release\method.js:15:34)
    at E:\HexoBlog\Hexo\node_modules\hexo\lib\extend\filter.js:62:52
    at tryCatcher (E:\HexoBlog\Hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (E:\HexoBlog\Hexo\node_modules\bluebird\js\release\reduce.js:155:18)
    at Object.gotAccum (E:\HexoBlog\Hexo\node_modules\bluebird\js\release\reduce.js:144:25)
    at Object.tryCatcher (E:\HexoBlog\Hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\HexoBlog\Hexo\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (E:\HexoBlog\Hexo\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromiseCtx (E:\HexoBlog\Hexo\node_modules\bluebird\js\release\promise.js:611:10)
    at _drainQueueStep (E:\HexoBlog\Hexo\node_modules\bluebird\js\release\async.js:142:12)
    at _drainQueue (E:\HexoBlog\Hexo\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (E:\HexoBlog\Hexo\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\HexoBlog\Hexo\node_modules\bluebird\js\release\async.js:17:14)

**Comment by SukkaW** [comment]
#4130 Duplicated.
