### ISSUE TITLE
How to solve this kind of error? Thanks!

### ISSUE THREAD

**Issue by Akijou-Lee** [hexojs/hexo#4167]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than 8.6.0

#####  I really don't know how to read it or solve it since I am weak at learning programming. There is no answer to this kind of problem, I guest, . Would you please help me? Thanks!
ERROR Render HTML failed: about/index.html
TypeError: Cannot read property 'includes' of null
    at PartialView.isFullPage (C:\Program Files\Hexo\blog\node_modules\hexo-tag-aplayer\lib\view.js:24:27)
    at Hexo.<anonymous> (C:\Program Files\Hexo\blog\node_modules\hexo-tag-aplayer\index.js:86:12)
    at Hexo.tryCatcher (C:\Program Files\Hexo\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (C:\Program Files\Hexo\blog\node_modules\bluebird\js\release\method.js:15:34)
    at C:\Program Files\Hexo\blog\node_modules\hexo\lib\extend\filter.js:62:52
    at tryCatcher (C:\Program Files\Hexo\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (C:\Program Files\Hexo\blog\node_modules\bluebird\js\release\reduce.js:166:18)
    at Object.gotAccum (C:\Program Files\Hexo\blog\node_modules\bluebird\js\release\reduce.js:155:25)
    at Object.tryCatcher (C:\Program Files\Hexo\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\Hexo\blog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Program Files\Hexo\blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Program Files\Hexo\blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Program Files\Hexo\blog\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Program Files\Hexo\blog\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Program Files\Hexo\blog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Program Files\Hexo\blog\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Program Files\Hexo\blog\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)

## Environment & Settings

**Version Information**

```
hexo: 4.2.0
hexo-cli: 3.1.0
os: Windows_NT 10.0.17763 win32 x64
node: 13.6.0
v8: 7.9.317.25-node.26
uv: 1.34.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 79
nghttp2: 1.40.0
napi: 5
llhttp: 2.0.1
openssl: 1.1.1d
cldr: 36.0
icu: 65.1
tz: 2019c
unicode: 12.1
```

**Your site `_config.yml`** (Optional)

```
Hexo: https://akijou-lee.github.io/
[_config.zip](https://github.com/hexojs/hexo/files/4273519/_config.zip)

```

**Your theme `_config.yml`** (Optional)

```
NexT
[_config.zip](https://github.com/hexojs/hexo/files/4273520/_config.zip)

```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
Hexo: Latest
Hexo-tag-aplayer
hexo-tag-dplayer
Live2D
Revolvermaps
Gitalk
```

**Your package.json `package.json`**

```
```

## Others
This is my repository building my own blog.

https://github.com/Akijou-Lee/Akijou-Lee.github.io

I type "hexo clean" and that's fine. And then I type "hexo g" and then the error comes.

**Comment by YoshinoriN** [comment]
@Akijou-Lee 
This error caused by [hexo-tag-aplayer](https://github.com/MoePlayer/hexo-tag-aplayer).
Would you please ask it to plugin's owner?

Thanks :)

**Comment by Akijou-Lee** [comment]
> @Akijou-Lee
> This error caused by [hexo-tag-aplayer](https://github.com/MoePlayer/hexo-tag-aplayer).
> Would you please ask it to plugin's owner?
> 
> Thanks :)

Thank you for your reply! I'll ask the owner. 👍
