### ISSUE TITLE
hexo Cannot read property 'enable' of undefined

### ISSUE THREAD

**Issue by Jeislu** [hexojs/hexo#4175]
$ hexo generate
INFO  Start processing
INFO  Files loaded in 3.64 s
ERROR G:\blog\themes\Butterfly\layout\post.pug:95
    93|     include includes/share/index.pug
    94|
  > 95|   if theme.reward.enable
    96|     include includes/reward.pug
    97|   include includes/pagination.pug
    98|

Cannot read property 'enable' of undefined
TypeError: G:\blog\themes\Butterfly\layout\post.pug:95
    93|     include includes/share/index.pug
    94|
  > 95|   if theme.reward.enable
    96|     include includes/reward.pug
    97|   include includes/pagination.pug
    98|

Cannot read property 'enable' of undefined
    at eval (eval at wrap (G:\blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:2696:18)
    at template (eval at wrap (G:\blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:4315:72)
    at viewFn._compiled (G:\blog\node_modules\hexo\lib\theme\view.js:136:48)
    at viewFn.View.render (G:\blog\node_modules\hexo\lib\theme\view.js:41:15)
    at G:\blog\node_modules\hexo\lib\hexo\index.js:61:21
    at tryCatcher (G:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at G:\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (G:\blog\node_modules\hexo\lib\hexo\router.js:126:3)
    at RouteStream.Readable.read (_stream_readable.js:478:10)
    at resume_ (_stream_readable.js:965:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

我不知道如何去解决这个问题
I don't know how to solve this problem

**Comment by Jeislu** [comment]
我不知道那里为什么错了
I don't know why it's wrong there

**Comment by Jeislu** [comment]
现在我的博客的md文档打不开了
Now my blog's markdown can't be opened

**Comment by stevenjoezhang** [comment]
If you're using` hexo-theme-butterfly`, this means that `reward` option is missing from `_config.yml`

https://github.com/jerryc127/hexo-theme-butterfly/blob/c118e1e16a3edbff15e1a00fd89eb2159bf05d1f/_config.yml#L334

This issue has nothing to do with Hexo, please ask the author of the theme for help.
