### ISSUE TITLE
hexo g doesn't work

### ISSUE THREAD

**Issue by drppy** [hexojs/hexo#4186]
here is the massage.

```
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: (unknown path)
  SyntaxError: Invalid or unexpected token
    at Object._prettifyError (/Users/lyubingo/blog/github/lyubingo.github.com/node_modules/nunjucks/src/lib.js:36:11)
    at Template.render (/Users/lyubingo/blog/github/lyubingo.github.com/node_modules/nunjucks/src/environment.js:524:21)
    at Environment.renderString (/Users/lyubingo/blog/github/lyubingo.github.com/node_modules/nunjucks/src/environment.js:362:17)
```

even when I delete all my .md files in _post , it still happend, please help me.

my .yaml file is well, too.

where is problem ?

**Comment by stevenjoezhang** [comment]
Please execute `hexo g --debug` to locate the problem
