### ISSUE TITLE
unknown block tag: tabs

### ISSUE THREAD

**Issue by asdf2014** [hexojs/hexo#4213]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than 8.6.0

## Expected behavior

`hexo g` without error

## Actual behavior

```javascript
hexo g
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
Nunjucks Error:  [Line 22, Column 4] unknown block tag: tabs
    =====               Context Dump               =====
    === (line number probably different from source) ===
  26 | {% codeblock lang:python %}
    =====             Context Dump Ends            =====
    at formatNunjucksError (/Users/benedictjin/code/yuzhouwan-blog/node_modules/hexo/lib/extend/tag.js:99:13)
    at /Users/benedictjin/code/yuzhouwan-blog/node_modules/hexo/lib/extend/tag.js:121:34
    at tryCatcher (/Users/benedictjin/code/yuzhouwan-blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/benedictjin/code/yuzhouwan-blog/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/benedictjin/code/yuzhouwan-blog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/benedictjin/code/yuzhouwan-blog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/benedictjin/code/yuzhouwan-blog/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/Users/benedictjin/code/yuzhouwan-blog/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/benedictjin/code/yuzhouwan-blog/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/benedictjin/code/yuzhouwan-blog/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/benedictjin/code/yuzhouwan-blog/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
```

## How to reproduce?

* create a markdown document that have the `tabs` tag content
* exectute `hexo g`

## Environment & Settings

**Node.js & npm version**

```
[1] 45342
v12.16.1
[1]  + 45342 done       node -v
{
  yuzhouwan: '0.0.0',
  npm: '6.13.4',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.9.3',
  icu: '64.2',
  llhttp: '2.0.4',
  modules: '72',
  napi: '5',
  nghttp2: '1.40.0',
  node: '12.16.1',
  openssl: '1.1.1d',
  tz: '2019c',
  unicode: '12.1',
  uv: '1.34.0',
  v8: '7.8.279.23-node.31',
  zlib: '1.2.11'
}
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
├── @babel/core@7.9.0
├── babel-core@6.26.3
├── babel-preset-env@1.7.0
├── browser-sync@2.26.7
├── gulp@4.0.2
├── gulp-htmlclean@2.7.22
├── gulp-htmlmin@5.0.1
├── gulp-imagemin@7.1.0
├── gulp-install@1.1.0
├── gulp-minify-css@1.2.4
├── gulp-uglify@3.0.2
├── hexo@4.2.0
├── hexo-abbrlink@2.0.5
├── hexo-autonofollow@1.0.1
├── hexo-deployer-git@2.1.0
├── hexo-douban@1.1.3
├── hexo-filter-flowchart@1.0.4
├── hexo-filter-github-emojis@2.1.0
├── hexo-filter-mermaid-diagrams@1.0.5
├── hexo-fs@2.0.0
├── hexo-generator-archive@1.0.0
├── hexo-generator-category@1.0.0
├── hexo-generator-feed@2.2.0
├── hexo-generator-index@1.0.0
├── hexo-generator-searchdb@1.2.1
├── hexo-generator-sitemap@2.0.0
├── hexo-generator-tag@1.0.0
├── hexo-inject@1.0.0
├── hexo-related-popular-posts@4.0.0
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-kramed@0.1.4
├── hexo-renderer-stylus@1.1.0
├── hexo-server@1.0.0
├── hexo-symbols-count-time@0.7.1
├── hexo-tag-mermaid@1.0.0
├── hexo-util@1.9.0
├── mermaid@8.4.8
└── natives@1.1.6
```

**Your package.json `package.json`**

```
{
  "name": "yuzhouwan",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "4.2.0"
  },
  "dependencies": {
    "@babel/core": "^7.9.0",
    "browser-sync": "^2.26.7",
    "gulp": "^4.0.2",
    "gulp-htmlclean": "^2.7.22",
    "gulp-htmlmin": "^5.0.1",
    "gulp-imagemin": "^7.1.0",
    "gulp-install": "^1.1.0",
    "gulp-minify-css": "^1.2.4",
    "gulp-uglify": "^3.0.2",
    "hexo": "^4.2.0",
    "hexo-abbrlink": "^2.0.5",
    "hexo-autonofollow": "^1.0.1",
    "hexo-deployer-git": "^2.1.0",
    "hexo-douban": "^1.1.3",
    "hexo-filter-flowchart": "^1.0.4",
    "hexo-filter-github-emojis": "^2.1.0",
    "hexo-filter-mermaid-diagrams": "^1.0.5",
    "hexo-fs": "^2.0.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^2.2.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-searchdb": "^1.1.0",
    "hexo-generator-sitemap": "^2.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-inject": "^1.0.0",
    "hexo-related-popular-posts": "^4.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-kramed": "^0.1.4",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0",
    "hexo-symbols-count-time": "^0.7.1",
    "hexo-tag-mermaid": "^1.0.0",
    "mermaid": "^8.4.8",
    "natives": "^1.1.6"
  },
  "devDependencies": {
    "babel-core": "^6.26.3",
    "babel-preset-env": "^1.7.0",
    "hexo-util": "^1.9.0"
  }
}
```

**Comment by asdf2014** [comment]
Never mind, it’s only supported by next theme.  https://yuzhouwan.com/posts/666/
