### ISSUE TITLE
未对配置进行修改,页面渲染失败

### ISSUE THREAD

**Issue by it-beige** [hexojs/hexo#4241]
ERROR Render HTML failed: 2020/04/12/hello/index.html
TypeError: Cannot read property 'replace' of null
    at Hexo.externalLinkFilter (C:\Users\ks\Desktop\blog\myblog\node_modules\hexo\lib\plugins\filter\after_render\external_link.js:22:15)
    at Hexo.tryCatcher (C:\Users\ks\Desktop\blog\myblog\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (C:\Users\ks\Desktop\blog\myblog\node_modules\bluebird\js\release\method.js:15:34)
    at Promise.each.filter (C:\Users\ks\Desktop\blog\myblog\node_modules\hexo\lib\extend\filter.js:62:52)
    at tryCatcher (C:\Users\ks\Desktop\blog\myblog\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (C:\Users\ks\Desktop\blog\myblog\node_modules\bluebird\js\release\reduce.js:166:18)
    at Object.gotAccum (C:\Users\ks\Desktop\blog\myblog\node_modules\bluebird\js\release\reduce.js:155:25)
    at Object.tryCatcher (C:\Users\ks\Desktop\blog\myblog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\ks\Desktop\blog\myblog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\ks\Desktop\blog\myblog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (C:\Users\ks\Desktop\blog\myblog\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (C:\Users\ks\Desktop\blog\myblog\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (C:\Users\ks\Desktop\blog\myblog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\ks\Desktop\blog\myblog\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\ks\Desktop\blog\myblog\node_modules\bluebird\js\release\async.js:15:14)
    at runCallback (timers.js:705:18)
ERROR Cannot read property 'replace' of null
TypeError: Cannot read property 'replace' of null
    at Hexo.externalLinkFilter (C:\Users\ks\Desktop\blog\myblog\node_modules\hexo\lib\plugins\filter\after_render\external_link.js:22:15)
    at Hexo.tryCatcher (C:\Users\ks\Desktop\blog\myblog\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (C:\Users\ks\Desktop\blog\myblog\node_modules\bluebird\js\release\method.js:15:34)
    at Promise.each.filter (C:\Users\ks\Desktop\blog\myblog\node_modules\hexo\lib\extend\filter.js:62:52)
    at tryCatcher (C:\Users\ks\Desktop\blog\myblog\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (C:\Users\ks\Desktop\blog\myblog\node_modules\bluebird\js\release\reduce.js:166:18)
    at Object.gotAccum (C:\Users\ks\Desktop\blog\myblog\node_modules\bluebird\js\release\reduce.js:155:25)
    at Object.tryCatcher (C:\Users\ks\Desktop\blog\myblog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\ks\Desktop\blog\myblog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\ks\Desktop\blog\myblog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (C:\Users\ks\Desktop\blog\myblog\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (C:\Users\ks\Desktop\blog\myblog\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (C:\Users\ks\Desktop\blog\myblog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\ks\Desktop\blog\myblog\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\ks\Desktop\blog\myblog\node_modules\bluebird\js\release\async.js:15:14)
    at runCallback (timers.js:705:18)

**Comment by stevenjoezhang** [comment]
如果希望别人帮助解决问题，请尽可能多地提供有效的信息。谢谢。
