### ISSUE TITLE
hexo d failed  :sob:  help me！！！

### ISSUE THREAD

**Issue by LolitaSian** [hexojs/hexo#4275]
:sob: I can't find a solution

***

**when I input** `$ hexo d`
**output**
(node:6788) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6788) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:6788) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
(node:6788) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(node:6788) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:6788) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
INFO  Deploying: git
INFO  Setting up Git deployment...
Initialized empty Git repository in E:/hexoblog/.deploy_git/.git/
[master (root-commit) 801bc33] First commit
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 placeholder
INFO  Clearing .deploy_git folder...
INFO  Copying files from public folder...
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError [ERR_INVALID_ARG_TYPE]: The "mode" argument must be integer. Received an instance of Object
    at copyFile (fs.js:1890:10)
    at tryCatcher (E:\hexoblog\node_modules\bluebird\js\release\util.js:16:23)
    at ret (eval at makeNodePromisifiedEval (C:\Users\16627\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\promisify.js:184:12), <anonymous>:13:39)
    at E:\hexoblog\node_modules\hexo-fs\lib\fs.js:144:39
    at tryCatcher (E:\hexoblog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\hexoblog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\hexoblog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\hexoblog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\hexoblog\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (E:\hexoblog\node_modules\bluebird\js\release\promise.js:673:18)
    at Promise._resolveCallback (E:\hexoblog\node_modules\bluebird\js\release\promise.js:466:57)
    at Promise._settlePromiseFromHandler (E:\hexoblog\node_modules\bluebird\js\release\promise.js:559:17)
    at Promise._settlePromise (E:\hexoblog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\hexoblog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\hexoblog\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (E:\hexoblog\node_modules\bluebird\js\release\promise.js:673:18)
    at Promise._resolveCallback (E:\hexoblog\node_modules\bluebird\js\release\promise.js:466:57)
    at Promise._settlePromiseFromHandler (E:\hexoblog\node_modules\bluebird\js\release\promise.js:559:17)
    at Promise._settlePromise (E:\hexoblog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\hexoblog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\hexoblog\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (E:\hexoblog\node_modules\bluebird\js\release\promise.js:673:18)

***

**when  I use** `$ hexo version`
**it output：**
(node:2760) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2760) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:2760) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
(node:2760) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(node:2760) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:2760) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
hexo: 4.2.0
hexo-cli: 3.1.0
os: Windows_NT 10.0.18363 win32 x64
node: 14.0.0
v8: 8.1.307.30-node.30
uv: 1.37.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.16.0
modules: 83
nghttp2: 1.40.0
napi: 6
llhttp: 2.0.4
openssl: 1.1.1f
cldr: 36.1
icu: 66.1
tz: 2019c
unicode: 13.0

**Comment by stevenjoezhang** [comment]
Please downgrade to Node.js 13 or 12.

https://github.com/hexojs/hexo/issues/4268#issuecomment-619398547

**Comment by lephones** [comment]
node 14也有这个问题 换回13就OK了

**Comment by THE-NAMELESS-SPECTRE** [comment]
都一样, 大家都挂了
我快炸了
重装电脑恢复博客后死活deploy不了
...
今天才发现是这个问题(不过话说hexo开发人员还不发布新版本吗? 这么严重的兼容性问题...)
而且也有pr解决了, 这么懒?

**Comment by THE-NAMELESS-SPECTRE** [comment]
我 裂 开 了

**Comment by THE-NAMELESS-SPECTRE** [comment]
不行, 我要口吐芬芳了, 虽然迟迟不发布新版并不是hexo的错...
但是我还是要强烈谴责这种行为

**Comment by stevenjoezhang** [comment]
如果你有能力的话，可以将发牢骚的时间用来帮助 Hexo 改进代码~
反正都是敲键盘，不如做点有意义的事情~

**Comment by xindubawukong222** [comment]
Emmm, I met the same problem.
