### ISSUE TITLE
我也不知道咋回事，我就换了个主题"NxtMoe"就报错了

### ISSUE THREAD

**Issue by i-am-a-loser-using-windows-server** [hexojs/hexo#4282]
Unhandled rejection TypeError: G:\github\hexo\Another-Blog\themes\nxtmoe\layout\index.ejs:11
    9|                 </div>
    10|             <%}  else{ %>
 >> 11|                 <div class="nexmoe-post-cover mdui-ripple" style="padding-bottom: <%- theme.background.height/theme.background.width*100 %>%;">
    12|                     <img data-src="<%- theme.background.path %>" data-sizes="auto" alt="<%= page.title %>" class="lazyload">
    13|                     <h1><%= page.title %></h1>
    14|                 </div>

Cannot read property 'height' of undefined
    at eval (G:\github\hexo\Another-Blog\themes\nxtmoe\layout\index.ejs:33:34)
    at _Query.forEach (G:\github\hexo\Another-Blog\node_modules\warehouse\lib\query.js:36:7)
    at eval (G:\github\hexo\Another-Blog\themes\nxtmoe\layout\index.ejs:10:19)
    at index (G:\github\hexo\Another-Blog\node_modules\ejs\lib\ejs.js:682:17)
    at viewFn._compiled (G:\github\hexo\Another-Blog\node_modules\hexo\lib\theme\view.js:136:48)
    at viewFn.View.render (G:\github\hexo\Another-Blog\node_modules\hexo\lib\theme\view.js:41:15)
    at G:\github\hexo\Another-Blog\node_modules\hexo\lib\hexo\index.js:61:21
    at tryCatcher (G:\github\hexo\Another-Blog\node_modules\bluebird\js\release\util.js:16:23)
    at G:\github\hexo\Another-Blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (G:\github\hexo\Another-Blog\node_modules\hexo\lib\hexo\router.js:126:3)
    at RouteStream.Readable.read (_stream_readable.js:459:10)
    at resume_ (_stream_readable.js:948:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by stevenjoezhang** [comment]
你好，未在 GitHub 上找到名为 NxtMoe 的主题。请提供更多信息。

**Comment by i-am-a-loser-using-windows-server** [comment]
没事了，脑残没看文档。

**Comment by stevenjoezhang** [comment]
有其他问题欢迎提出～
