### ISSUE TITLE
hexo d 报错

### ISSUE THREAD

**Issue by Clannad-1** [hexojs/hexo#4288]
(node:22186) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:22186) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:22186) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
(node:22186) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(node:22186) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:22186) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
INFO  Deploying: git
INFO  Clearing .deploy_git folder...
INFO  Copying files from public folder...
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError [ERR_INVALID_ARG_TYPE]: The "mode" argument must be integer. Received an instance of Object
    at copyFile (fs.js:1890:10)
    at tryCatcher (/project/blog/node_modules/bluebird/js/release/util.js:16:23)
    at ret (eval at makeNodePromisifiedEval (/usr/local/application/nodejs/lib/node_modules/hexo-cli/node_modules/_bluebird@3.7.2@bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
    at /project/blog/node_modules/hexo-fs/lib/fs.js:144:39
    at tryCatcher (/project/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/project/blog/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/project/blog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/project/blog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/project/blog/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/project/blog/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/project/blog/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/project/blog/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/project/blog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/project/blog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/project/blog/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/project/blog/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/project/blog/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/project/blog/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/project/blog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/project/blog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/project/blog/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/project/blog/node_modules/bluebird/js/release/promise.js:673:18)

**Comment by stevenjoezhang** [comment]
Please search for existing issues before creating a new issue, thanks.

#4268
#4272
#4275
https://github.com/hexojs/hexo/issues/4281
hexojs/hexo-deployer-git#177

**Comment by YoshinoriN** [comment]
@Clannad-1 

We published [v4.2.1](https://github.com/hexojs/hexo/releases/tag/4.2.1).
v4.2.1 has included fixed compatible with Node 14.

Thanks :)

**Comment by Clannad-1** [comment]
解决了 用node 12
