### ISSUE TITLE
执行 hexo generate 的时候，抛出下面的错误

### ISSUE THREAD

**Issue by LeeYiua** [hexojs/hexo#4302]
ERROR Process failed: _posts/Tomcat-学习笔记1.md
ValidationError: `null` is not a string!
    at new WarehouseError (/Users/liyihua/blog/node_modules/warehouse/lib/error.js:14:11)
    at new ValidationError (/Users/liyihua/blog/node_modules/warehouse/lib/error/validation.js:5:1)
    at SchemaTypeString.validate (/Users/liyihua/blog/node_modules/warehouse/lib/types/string.js:36:13)
    at Array.<anonymous> (/Users/liyihua/blog/node_modules/warehouse/lib/schema.js:479:27)
    at Schema._applySetters (/Users/liyihua/blog/node_modules/warehouse/lib/schema.js:609:15)
    at _Model._insertOne (/Users/liyihua/blog/node_modules/warehouse/lib/model.js:158:12)
    at /Users/liyihua/blog/node_modules/warehouse/lib/model.js:179:63
    at tryCatcher (/Users/liyihua/blog/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/liyihua/blog/node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/Users/liyihua/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/liyihua/blog/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/liyihua/blog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/liyihua/blog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/liyihua/blog/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/liyihua/blog/node_modules/bluebird/js/release/promise.js:673:18)
    at PromiseArray._resolve (/Users/liyihua/blog/node_modules/bluebird/js/release/promise_array.js:127:19)
    at PromiseArray._promiseFulfilled (/Users/liyihua/blog/node_modules/bluebird/js/release/promise_array.js:145:14)
    at Promise._settlePromise (/Users/liyihua/blog/node_modules/bluebird/js/release/promise.js:609:26)
    at Promise._settlePromise0 (/Users/liyihua/blog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/liyihua/blog/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/Users/liyihua/blog/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/liyihua/blog/node_modules/bluebird/js/release/async.js:86:9)

前段时间 hexo new "XXX"，然后hexo claen / hexo generate / hexo server 都是没问题的，就今天修改了博客目录下的_config.yml 文件的 post_asset_folder: true，卸载了hexo-asset-image，现在进行 hexo generate 就报错了，不知道怎么解决

**Comment by AFGXF** [comment]
已知的是您用中文肯定没有人解答.

**Comment by SukkaW** [comment]
@AFGXF 

That is not right. At least there will be someone adding those labels `non-english` and `not following issue template` to the issue.
