### ISSUE TITLE
执行hexo clean && hexo deploy时报错mode参数错误

### ISSUE THREAD

**Issue by graythornvi** [hexojs/hexo#4304]
(node:60446) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:60446) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:60446) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
(node:60446) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(node:60446) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:60446) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
INFO  Deleted database.
INFO  Deleted public folder.
(node:60447) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:60447) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:60447) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
(node:60447) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(node:60447) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:60447) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
INFO  Start processing
INFO  Files loaded in 341 ms
(node:60447) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(node:60447) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:60447) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
(node:60447) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(node:60447) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:60447) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
INFO  Generated: index.html
INFO  Generated: archives/index.html
INFO  Generated: fancybox/blank.gif
INFO  Generated: fancybox/jquery.fancybox.css
INFO  Generated: fancybox/jquery.fancybox.pack.js
INFO  Generated: fancybox/jquery.fancybox.js
INFO  Generated: fancybox/fancybox_loading.gif
INFO  Generated: fancybox/fancybox_loading@2x.gif
INFO  Generated: fancybox/fancybox_sprite.png
INFO  Generated: fancybox/fancybox_overlay.png
INFO  Generated: archives/2020/05/index.html
INFO  Generated: fancybox/fancybox_sprite@2x.png
INFO  Generated: archives/2020/index.html
INFO  Generated: css/fonts/fontawesome-webfont.eot
INFO  Generated: js/script.js
INFO  Generated: fancybox/helpers/jquery.fancybox-buttons.js
INFO  Generated: css/style.css
INFO  Generated: fancybox/helpers/jquery.fancybox-thumbs.js
INFO  Generated: fancybox/helpers/jquery.fancybox-media.js
INFO  Generated: fancybox/helpers/jquery.fancybox-buttons.css
INFO  Generated: fancybox/helpers/fancybox_buttons.png
INFO  Generated: css/fonts/fontawesome-webfont.woff
INFO  Generated: fancybox/helpers/jquery.fancybox-thumbs.css
INFO  Generated: css/fonts/FontAwesome.otf
INFO  Generated: css/fonts/fontawesome-webfont.ttf
INFO  Generated: css/images/banner.jpg
INFO  Generated: css/fonts/fontawesome-webfont.svg
INFO  Generated: 2020/05/11/hello-world/index.html
INFO  28 files generated in 749 ms
INFO  Deploying: git
INFO  Clearing .deploy_git folder...
INFO  Copying files from public folder...
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError [ERR_INVALID_ARG_TYPE]: The "mode" argument must be integer. Received an instance of Object
    at copyFile (fs.js:1890:10)
    at tryCatcher (/Users/graythornvi/graythornvi/node_modules/bluebird/js/release/util.js:16:23)
    at ret (eval at makeNodePromisifiedEval (/usr/local/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
    at /Users/graythornvi/graythornvi/node_modules/hexo-fs/lib/fs.js:144:39
    at tryCatcher (/Users/graythornvi/graythornvi/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/graythornvi/graythornvi/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/graythornvi/graythornvi/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/graythornvi/graythornvi/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/graythornvi/graythornvi/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/graythornvi/graythornvi/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/Users/graythornvi/graythornvi/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/Users/graythornvi/graythornvi/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/Users/graythornvi/graythornvi/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/graythornvi/graythornvi/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/graythornvi/graythornvi/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/graythornvi/graythornvi/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/Users/graythornvi/graythornvi/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/Users/graythornvi/graythornvi/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/Users/graythornvi/graythornvi/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/graythornvi/graythornvi/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/graythornvi/graythornvi/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/graythornvi/graythornvi/node_modules/bluebird/js/release/promise.js:673:18)

**Comment by stevenjoezhang** [comment]
见 https://github.com/hexojs/hexo/issues/4281

**Comment by YoshinoriN** [comment]
@graythornvi 

We published [v4.2.1](https://github.com/hexojs/hexo/releases/tag/4.2.1).
v4.2.1 has included fixed compatible with Node 14.

Thanks :)
