### ISSUE TITLE
hexo g出现错误

### ISSUE THREAD

**Issue by libertyunionkjy** [hexojs/hexo#4305]
错误代码：
```
FATAL can not read a block mapping entry; a multiline key may not be an implicit key at line 8, column 12:
    description: 'KK's Blog'
               ^
YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 8, column 12:
    description: 'KK's Blog'
               ^
    at generateError (F:\Blog\HEXO\node_modules\js-yaml\lib\js-yaml\loader.js:167:10)
    at throwError (F:\Blog\HEXO\node_modules\js-yaml\lib\js-yaml\loader.js:173:9)
    at readBlockMapping (F:\Blog\HEXO\node_modules\js-yaml\lib\js-yaml\loader.js:1073:9)
    at composeNode (F:\Blog\HEXO\node_modules\js-yaml\lib\js-yaml\loader.js:1359:12)
    at readDocument (F:\Blog\HEXO\node_modules\js-yaml\lib\js-yaml\loader.js:1519:3)
    at loadDocuments (F:\Blog\HEXO\node_modules\js-yaml\lib\js-yaml\loader.js:1575:5)
    at Object.load (F:\Blog\HEXO\node_modules\js-yaml\lib\js-yaml\loader.js:1596:19)
    at Hexo.yamlHelper (F:\Blog\HEXO\node_modules\hexo\lib\plugins\renderer\yaml.js:7:15)
    at Hexo.tryCatcher (F:\Blog\HEXO\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (F:\Blog\HEXO\node_modules\bluebird\js\release\method.js:15:34)
    at F:\Blog\HEXO\node_modules\hexo\lib\hexo\render.js:75:22
    at tryCatcher (F:\Blog\HEXO\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (F:\Blog\HEXO\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (F:\Blog\HEXO\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (F:\Blog\HEXO\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (F:\Blog\HEXO\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (F:\Blog\HEXO\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (F:\Blog\HEXO\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (F:\Blog\HEXO\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (F:\Blog\HEXO\node_modules\bluebird\js\release\async.js:15:14)
```
但是我的description:后是加了空格的，并且用的也是英文输入法，不知道出了什么问题？
```
title: 柯柯的博客
subtitle: 'KK's Blog'
description: 'KK's Blog'
keywords:
author: Keke
language: zh-Hans
timezone: ''
```

**Comment by stevenjoezhang** [comment]
字符串中有引号需要转义
```
'KK\'s Blog'
```

**Comment by libertyunionkjy** [comment]
> 字符串中有引号需要转义
> 
> ```
> 'KK\'s Blog'
> ```

我好像解决了，好像是因为有空格要用双引号，对YAML语言不太了解，你的方法试了一下好像还是报同样的错误。
```
title: 柯柯的博客
subtitle: "KK's Blog"
description: '记录学习的地方'
keywords:
author: Keke
language: zh-Hans
timezone: ''
```
