### ISSUE TITLE
compatibility problems with Node.js v14.3.0

### ISSUE THREAD

**Issue by yanhuacuo** [hexojs/hexo#4321]
I have these problems in Ubuntu 20.04 LTS

```
$ node -v
v14.3.0
```
and this is the version of my hexo

```
$ hexo -v
(node:35237) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:35237) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:35237) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
(node:35237) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(node:35237) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:35237) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
hexo: 4.2.1
hexo-cli: 3.1.0
os: Linux 5.4.0-31-generic linux x64
node: 14.3.0
v8: 8.1.307.31-node.33
uv: 1.37.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.16.0
modules: 83
nghttp2: 1.40.0
napi: 6
llhttp: 2.0.4
openssl: 1.1.1g
cldr: 37.0
icu: 67.1
tz: 2019c
unicode: 13.0
```

**Comment by yanhuacuo** [comment]
```
$ npm fund
hexo-site@0.0.0
├─┬ https://opencollective.com/hexo
│ └── hexo@4.2.1
├─┬ https://github.com/sponsors/ljharb
│ └── resolve@1.17.0
├─┬ https://github.com/chalk/ansi-styles?sponsor=1
│ └── ansi-styles@4.2.1
├─┬ https://github.com/sponsors/jonschlinkert
│ └── picomatch@2.2.2
└─┬ https://github.com/sponsors/isaacs
  └── glob@7.1.6
```

**Comment by yanhuacuo** [comment]
````
$ hexo server
(node:32081) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:32081) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:32081) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
(node:32081) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(node:32081) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:32081) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
INFO  Start processing
INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
````

**Comment by yanhuacuo** [comment]
``````
npm audit fix
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

up to date in 0.824s

5 packages are looking for funding
  run `npm fund` for details

fixed 0 of 1 vulnerability in 254 scanned packages
  1 vulnerability required manual review and could not be updated
``````

**Comment by jiangtj** [comment]
So what problem did you encounter? 
Of course, you can take a look at #4260, about node v14 compatibility.

**Comment by yanhuacuo** [comment]
So sadly，i back to node.js  v14.2.0
the problems all the same

**Comment by yanhuacuo** [comment]
> So what problem did you encounter?
> Of course, you can take a look at #4260, about node v14 compatibility.

yes ,i have read that page, but it is useless

**Comment by yanhuacuo** [comment]
now ,i rebuild hexo from source with this commit 

:https://github.com/hexojs/hexo/commit/956242e4e6f008c5a2e0d1feddaa4f3a7bb2251e

and , this mistake still exists

**Comment by yanhuacuo** [comment]
```
 hexo -v
hexo-cli: 3.1.0
os: Linux 5.4.0-31-generic linux x64
node: 14.2.0
v8: 8.1.307.31-node.33
uv: 1.37.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.16.0
modules: 83
nghttp2: 1.40.0
napi: 6
llhttp: 2.0.4
openssl: 1.1.1g
cldr: 36.1
icu: 66.1
tz: 2019c
unicode: 13.0

```

**Comment by jiangtj** [comment]
Are you asking the "circular dependency" issue?

https://github.com/hexojs/hexo/issues/4260#issuecomment-623942492
https://github.com/hexojs/hexo/issues/4257

 This is caused by stylus, we need to wait for them to fix.

**Comment by yanhuacuo** [comment]
> Are you asking the "circular dependency" issue?
> 
> [#4260 (comment)](https://github.com/hexojs/hexo/issues/4260#issuecomment-623942492)
> #4257
> 
> This is caused by stylus, we need to wait for them to fix.

these caused by stylus indeed，now，what should we do ?

they're annoying :(

**Comment by SukkaW** [comment]
@yanhuacuo 

> these caused by stylus indeed，now，what should we do ?

Nothing. Only wait for stylus to fix it.

**Comment by yanhuacuo** [comment]
for these issues ，the hexo d will be failed


``````
$ hexo d
(node:5496) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5496) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:5496) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
(node:5496) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(node:5496) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:5496) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
INFO  Deploying: git
INFO  Clearing .deploy_git folder...
INFO  Copying files from public folder...
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError [ERR_INVALID_ARG_TYPE]: The "mode" argument must be integer. Received an instance of Object
    at copyFile (fs.js:1890:10)
    at tryCatcher (/home/i5/文档/blog/node_modules/bluebird/js/release/util.js:16:23)
    at ret (eval at makeNodePromisifiedEval (/usr/local/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
    at /home/i5/文档/blog/node_modules/hexo-fs/lib/fs.js:144:39
    at tryCatcher (/home/i5/文档/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/i5/文档/blog/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/i5/文档/blog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/i5/文档/blog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/i5/文档/blog/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/home/i5/文档/blog/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/home/i5/文档/blog/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/home/i5/文档/blog/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/home/i5/文档/blog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/i5/文档/blog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/i5/文档/blog/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/home/i5/文档/blog/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/home/i5/文档/blog/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/home/i5/文档/blog/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/home/i5/文档/blog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/i5/文档/blog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/i5/文档/blog/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/home/i5/文档/blog/node_modules/bluebird/js/release/promise.js:673:18)
``````

**Comment by YoshinoriN** [comment]
@yanhuacuo 
Please see https://github.com/hexojs/hexo/issues/4281#issuecomment-630775755
