### ISSUE TITLE
Is cheerio removed from mode_module？

### ISSUE THREAD

**Issue by finnley** [hexojs/hexo#4329]
I don't see cheerio in node_module, after installing hexo-translate-title, using hexo command will cause an error

```
ERROR Plugin load failed: hexo-translate-title
Error: Cannot find module 'cheerio'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/finnley/finnley.github.io.test/node_modules/hexo-translate-title/lib/util.js:9:17)
```
I compared the previous package-json.lock file and found that there is no cheerio in the latest，
Is cheerio removed from mode_module？

**Comment by stevenjoezhang** [comment]
Yes, `cheerio` is removed: https://github.com/hexojs/hexo/issues/3677
If you need to use `cheerio` in the script, please execute `npm i cheerio`
