### ISSUE TITLE
Template render error: (unknown path)

### ISSUE THREAD

**Issue by Desperado1001** [hexojs/hexo#4330]
When I use`hexo n` to generate a md file，and after`hexo g -d`. Hexo dosen't work. But I still got the same error after deleting this file.
MD file is as follows:
```
---
title: Nginx+FastDFS配置
top: 0
date: 2020-05-24 10:31:42
tags:
categories: Nginx

---

# 本文介绍在Mac以及Linux下安装配置FastDFS 和Nginx 详细步骤以及一些坑
```

The error message is as follows:
```
  Error: Block "body" defined more than once.
    at Object._prettifyError (/Users/macos/Desktop/blog/node_modules/nunjucks/src/lib.js:36:11)
    at Template.render (/Users/macos/Desktop/blog/node_modules/nunjucks/src/environment.js:542:21)
    at Environment.renderString (/Users/macos/Desktop/blog/node_modules/nunjucks/src/environment.js:380:17)
    at Promise.fromCallback.cb (/Users/macos/Desktop/blog/node_modules/hexo/lib/extend/tag.js:120:48)
    at tryCatcher (/Users/macos/Desktop/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.fromNode.Promise.fromCallback (/Users/macos/Desktop/blog/node_modules/bluebird/js/release/promise.js:209:30)
    at Tag.render (/Users/macos/Desktop/blog/node_modules/hexo/lib/extend/tag.js:120:18)
    at Object.onRenderEnd (/Users/macos/Desktop/blog/node_modules/hexo/lib/hexo/post.js:288:20)
    at Promise.then.then.result (/Users/macos/Desktop/blog/node_modules/hexo/lib/hexo/render.js:64:19)
    at tryCatcher (/Users/macos/Desktop/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/macos/Desktop/blog/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/macos/Desktop/blog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/macos/Desktop/blog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/macos/Desktop/blog/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/Users/macos/Desktop/blog/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/macos/Desktop/blog/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/macos/Desktop/blog/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues (/Users/macos/Desktop/blog/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

**Comment by stevenjoezhang** [comment]
This means that the template file of the theme you are using is corrupted and has nothing to do with Hexo.

**Comment by Desperado1001** [comment]
> This means that the template file of the theme you are using is corrupted and has nothing to do with Hexo.

Directly modify the subject field of the _config.yml file to the next theme will also report the same error

**Comment by stevenjoezhang** [comment]
There is no subject field in `_config.yml`. Do you mean `theme`?

**Comment by Desperado1001** [comment]
> There is no subject field in `_config.yml`. Do you mean `theme`?


I used the `material-x `theme before, if there is a problem with the configuration file of this theme, it is now modified to the `next `theme. It seems to be wrong.
