### ISSUE TITLE
无法正常deploy

### ISSUE THREAD

**Issue by RanchoCooper** [hexojs/hexo#4347]
(node:36833) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:36833) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:36833) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
(node:36833) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(node:36833) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:36833) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
INFO  Deploying: git
INFO  Clearing .deploy_git folder...
INFO  Copying files from public folder...
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError [ERR_INVALID_ARG_TYPE]: The "mode" argument must be integer. Received an instance of Object
    at copyFile (fs.js:1890:10)
    at tryCatcher (/Users/rancho/blog/node_modules/bluebird/js/release/util.js:16:23)
    at ret (eval at makeNodePromisifiedEval (/usr/local/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
    at /Users/rancho/blog/node_modules/hexo-fs/lib/fs.js:144:39
    at tryCatcher (/Users/rancho/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/rancho/blog/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/rancho/blog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/rancho/blog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/rancho/blog/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/rancho/blog/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/Users/rancho/blog/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/Users/rancho/blog/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/Users/rancho/blog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/rancho/blog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/rancho/blog/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/rancho/blog/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/Users/rancho/blog/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/Users/rancho/blog/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/Users/rancho/blog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/rancho/blog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/rancho/blog/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/rancho/blog/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/Users/rancho/blog/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/Users/rancho/blog/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/Users/rancho/blog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/rancho/blog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/rancho/blog/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/rancho/blog/node_modules/bluebird/js/release/promise.js:673:18)

## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [ ] I examined error or warning messages and it's difficult to solve
- [ ] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [ ] Node.js is higher than 8.6.0

## How to reproduce?

* Step1
* Step2
* etc...

## Environment & Settings

**Node.js & npm version**

```
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

**Comment by stevenjoezhang** [comment]
https://github.com/hexojs/hexo-deployer-git/issues/186
