### ISSUE TITLE
The following error appears when executing "hexo init"

### ISSUE THREAD

**Issue by bao-william** [hexojs/hexo#4350]
The following error appears when executing "hexo init". My nodejs version is v6.17.1.
[root@localhost ~]# hexo init hexo-blog
/usr/lib/node_modules/hexo-cli/node_modules/chokidar/index.js:151
  async remove(item) {
        ^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/hexo-cli/node_modules/hexo-fs/lib/fs.js:6:18)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)

**Comment by stevenjoezhang** [comment]
Please upgrade the Node.js on your machine to v10 or above.
See also https://github.com/hexojs/hexo/issues/3781
