### ISSUE TITLE
请问各位有遇到这样的情况吗？提示2种报错。

### ISSUE THREAD

**Issue by melodyjerry** [hexojs/hexo#4424]
# `hexo g`后会有两种报错，分别是
1.  
```
YAMLException: end of the stream or a document separator is expected at line 2, column 5:
    date: 2020-02-23 17:36:53
        ^
```
2. 
```
YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 2, column 5:
    date: 2020-07-16 15:55
        ^
```

# 详细全部报错
第一种
```
ERROR Process failed: _posts/Druid.md
YAMLException: end of the stream or a document separator is expected at line 2, column 5:
    date: 2020-02-23 17:36:53
        ^
    at generateError (G:\blog_gitee\node_modules\js-yaml\lib\js-yaml\loader.js:167:10)
    at throwError (G:\blog_gitee\node_modules\js-yaml\lib\js-yaml\loader.js:173:9)
    at readDocument (G:\blog_gitee\node_modules\js-yaml\lib\js-yaml\loader.js:1539:5)
    at loadDocuments (G:\blog_gitee\node_modules\js-yaml\lib\js-yaml\loader.js:1575:5)
    at Object.load (G:\blog_gitee\node_modules\js-yaml\lib\js-yaml\loader.js:1596:19)
    at parseYAML (G:\blog_gitee\node_modules\hexo-front-matter\lib\front_matter.js:78:23)
    at parse (G:\blog_gitee\node_modules\hexo-front-matter\lib\front_matter.js:54:12)
    at G:\blog_gitee\node_modules\hexo\lib\plugins\processor\post.js:48:20
    at tryCatcher (G:\blog_gitee\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (G:\blog_gitee\node_modules\bluebird\js\release\promise.js:544:35)
    at Promise._settlePromise (G:\blog_gitee\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (G:\blog_gitee\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (G:\blog_gitee\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (G:\blog_gitee\node_modules\bluebird\js\release\promise.js:673:18)
    at PromiseArray._resolve (G:\blog_gitee\node_modules\bluebird\js\release\promise_array.js:127:19)
    at PromiseArray._promiseFulfilled (G:\blog_gitee\node_modules\bluebird\js\release\promise_array.js:145:14)
    at PromiseArray._iterate (G:\blog_gitee\node_modules\bluebird\js\release\promise_array.js:115:31)
    at PromiseArray.init [as _init] (G:\blog_gitee\node_modules\bluebird\js\release\promise_array.js:79:10)
    at Promise._settlePromise (G:\blog_gitee\node_modules\bluebird\js\release\promise.js:601:21)
    at Promise._settlePromise0 (G:\blog_gitee\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (G:\blog_gitee\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (G:\blog_gitee\node_modules\bluebird\js\release\promise.js:673:18)
    at PromiseArray._resolve (G:\blog_gitee\node_modules\bluebird\js\release\promise_array.js:127:19)
    at PromiseArray._promiseFulfilled (G:\blog_gitee\node_modules\bluebird\js\release\promise_array.js:145:14)
    at Promise._settlePromise (G:\blog_gitee\node_modules\bluebird\js\release\promise.js:609:26)
    at Promise._settlePromise0 (G:\blog_gitee\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (G:\blog_gitee\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (G:\blog_gitee\node_modules\bluebird\js\release\promise.js:673:18)
```
第二种
```
hh MINGW64 /g/blog_gitee (master)
$ hexo g
INFO  Start processing
ERROR Process failed: _posts/KMP-算法详解.md
YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 2, column 5:
    date: 2020-07-16 15:55
        ^
    at generateError (G:\blog_gitee\node_modules\js-yaml\lib\js-yaml\loader.js:167:10)
    at throwError (G:\blog_gitee\node_modules\js-yaml\lib\js-yaml\loader.js:173:9)
    at readBlockMapping (G:\blog_gitee\node_modules\js-yaml\lib\js-yaml\loader.js:1073:9)
    at composeNode (G:\blog_gitee\node_modules\js-yaml\lib\js-yaml\loader.js:1359:12)
    at readDocument (G:\blog_gitee\node_modules\js-yaml\lib\js-yaml\loader.js:1519:3)
    at loadDocuments (G:\blog_gitee\node_modules\js-yaml\lib\js-yaml\loader.js:1575:5)
    at Object.load (G:\blog_gitee\node_modules\js-yaml\lib\js-yaml\loader.js:1596:19)
    at parseYAML (G:\blog_gitee\node_modules\hexo-front-matter\lib\front_matter.js:78:23)
    at parse (G:\blog_gitee\node_modules\hexo-front-matter\lib\front_matter.js:54:12)
    at G:\blog_gitee\node_modules\hexo\lib\plugins\processor\post.js:48:20
    at tryCatcher (G:\blog_gitee\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (G:\blog_gitee\node_modules\bluebird\js\release\promise.js:544:35)
    at Promise._settlePromise (G:\blog_gitee\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (G:\blog_gitee\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (G:\blog_gitee\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (G:\blog_gitee\node_modules\bluebird\js\release\promise.js:673:18)
    at PromiseArray._resolve (G:\blog_gitee\node_modules\bluebird\js\release\promise_array.js:127:19)
    at PromiseArray._promiseFulfilled (G:\blog_gitee\node_modules\bluebird\js\release\promise_array.js:145:14)
    at PromiseArray._iterate (G:\blog_gitee\node_modules\bluebird\js\release\promise_array.js:115:31)
    at PromiseArray.init [as _init] (G:\blog_gitee\node_modules\bluebird\js\release\promise_array.js:79:10)
    at Promise._settlePromise (G:\blog_gitee\node_modules\bluebird\js\release\promise.js:601:21)
    at Promise._settlePromise0 (G:\blog_gitee\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (G:\blog_gitee\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (G:\blog_gitee\node_modules\bluebird\js\release\promise.js:673:18)
    at PromiseArray._resolve (G:\blog_gitee\node_modules\bluebird\js\release\promise_array.js:127:19)
    at PromiseArray._promiseFulfilled (G:\blog_gitee\node_modules\bluebird\js\release\promise_array.js:145:14)
    at Promise._settlePromise (G:\blog_gitee\node_modules\bluebird\js\release\promise.js:609:26)
    at Promise._settlePromise0 (G:\blog_gitee\node_modules\bluebird\js\release\promise.js:649:10)
```

**Comment by stevenjoezhang** [comment]
There is a discussion about it: #4548
I'm closing this issue. Please join the discussion there :)
