### ISSUE TITLE
请问，为什么会突然报这样的提示？之前都没有，主题配置也没动过

### ISSUE THREAD

**Issue by melodyjerry** [hexojs/hexo#4425]
之前都没有，主题配置也没动过
控制台显示👇
```
hh@hh MINGW64 /g/blog_gitee (master)
$ hexo g
INFO  Start processing
ERROR Process failed: layout/_partial/baidu-analytics.ejs
SyntaxError: Missing catch or finally after try in G:\blog_gitee\themes\material-x\layout\_partial\baidu-analytics.ejs while compiling ejs

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
Or, if you meant to create an async function, pass `async: true` as an option.
    at new Function (<anonymous>)
    at Template.compile (G:\blog_gitee\node_modules\ejs\lib\ejs.js:652:12)
    at Object.compile (G:\blog_gitee\node_modules\ejs\lib\ejs.js:392:16)
    at Function.ejsRenderer.compile (G:\blog_gitee\node_modules\hexo-renderer-ejs\lib\renderer.js:10:14)
    at viewFn.View._precompile (G:\blog_gitee\node_modules\hexo\lib\theme\view.js:129:31)
    at viewFn.View (G:\blog_gitee\node_modules\hexo\lib\theme\view.js:26:8)
    at new viewFn (G:\blog_gitee\node_modules\hexo\lib\theme\index.js:35:15)
    at Theme.setView (G:\blog_gitee\node_modules\hexo\lib\theme\index.js:71:18)
    at G:\blog_gitee\node_modules\hexo\lib\theme\processors\view.js:14:14
    at tryCatcher (G:\blog_gitee\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (G:\blog_gitee\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (G:\blog_gitee\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (G:\blog_gitee\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (G:\blog_gitee\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (G:\blog_gitee\node_modules\bluebird\js\release\promise.js:673:18)
    at Promise._resolveCallback (G:\blog_gitee\node_modules\bluebird\js\release\promise.js:466:57)
    at Promise._settlePromiseFromHandler (G:\blog_gitee\node_modules\bluebird\js\release\promise.js:559:17)
    at Promise._settlePromise (G:\blog_gitee\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (G:\blog_gitee\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (G:\blog_gitee\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (G:\blog_gitee\node_modules\bluebird\js\release\promise.js:673:18)
    at G:\blog_gitee\node_modules\bluebird\js\release\nodeback.js:42:21
    at G:\blog_gitee\node_modules\graceful-fs\graceful-fs.js:115:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError [ERR_INVALID_URL]: Invalid URL: http://localhost:8081来登录；
    at onParseError (internal/url.js:243:9)
    at new URL (internal/url.js:319:5)
    at G:\blog_gitee\node_modules\hexo-util\lib\is_external_link.js:21:18
    at Cache.apply (G:\blog_gitee\node_modules\hexo-util\lib\cache.js:27:46)
    at isExternalLink (G:\blog_gitee\node_modules\hexo-util\lib\is_external_link.js:19:16)
    at G:\blog_gitee\node_modules\hexo\lib\plugins\filter\after_render\external_link.js:23:35
    at String.replace (<anonymous>)
    at Hexo.externalLinkFilter (G:\blog_gitee\node_modules\hexo\lib\plugins\filter\after_render\external_link.js:22:15)
    at Hexo.tryCatcher (G:\blog_gitee\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (G:\blog_gitee\node_modules\bluebird\js\release\method.js:15:34)
    at G:\blog_gitee\node_modules\hexo\lib\extend\filter.js:62:52
    at tryCatcher (G:\blog_gitee\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (G:\blog_gitee\node_modules\bluebird\js\release\reduce.js:166:18)
    at Object.gotAccum (G:\blog_gitee\node_modules\bluebird\js\release\reduce.js:155:25)
    at Object.tryCatcher (G:\blog_gitee\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (G:\blog_gitee\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (G:\blog_gitee\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (G:\blog_gitee\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (G:\blog_gitee\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (G:\blog_gitee\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (G:\blog_gitee\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (G:\blog_gitee\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
```

**Comment by stevenjoezhang** [comment]
你好，报错信息来自主题，请向你所使用的主题的维护者寻求帮助。
