### ISSUE TITLE
FATAL ERROR when copying files from public folder...

### ISSUE THREAD

**Issue by fuzheng1998** [hexojs/hexo#4465]
```
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError [ERR_INVALID_ARG_TYPE]: The "mode" argument must be integer. Received an instance of Object
    at copyFile (fs.js:1924:10)
    at tryCatcher (/Users/snowdenfu/Documents/GitHub/fuzheng1998.github.io/node_modules/bluebird/js/release/util.js:16:23)
    at ret (eval at makeNodePromisifiedEval (/usr/local/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
    at /Users/snowdenfu/Documents/GitHub/fuzheng1998.github.io/node_modules/hexo-fs/lib/fs.js:144:39
    at tryCatcher (/Users/snowdenfu/Documents/GitHub/fuzheng1998.github.io/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/snowdenfu/Documents/GitHub/fuzheng1998.github.io/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/Users/snowdenfu/Documents/GitHub/fuzheng1998.github.io/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/Users/snowdenfu/Documents/GitHub/fuzheng1998.github.io/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/Users/snowdenfu/Documents/GitHub/fuzheng1998.github.io/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/Users/snowdenfu/Documents/GitHub/fuzheng1998.github.io/node_modules/bluebird/js/release/promise.js:643:18)
    at Promise._resolveCallback (/Users/snowdenfu/Documents/GitHub/fuzheng1998.github.io/node_modules/bluebird/js/release/promise.js:437:57)
    at Promise._settlePromiseFromHandler (/Users/snowdenfu/Documents/GitHub/fuzheng1998.github.io/node_modules/bluebird/js/release/promise.js:529:17)
    at Promise._settlePromise (/Users/snowdenfu/Documents/GitHub/fuzheng1998.github.io/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/Users/snowdenfu/Documents/GitHub/fuzheng1998.github.io/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/Users/snowdenfu/Documents/GitHub/fuzheng1998.github.io/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/Users/snowdenfu/Documents/GitHub/fuzheng1998.github.io/node_modules/bluebird/js/release/promise.js:643:18)
    at Promise._resolveCallback (/Users/snowdenfu/Documents/GitHub/fuzheng1998.github.io/node_modules/bluebird/js/release/promise.js:437:57)
    at Promise._settlePromiseFromHandler (/Users/snowdenfu/Documents/GitHub/fuzheng1998.github.io/node_modules/bluebird/js/release/promise.js:529:17)
    at Promise._settlePromise (/Users/snowdenfu/Documents/GitHub/fuzheng1998.github.io/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/Users/snowdenfu/Documents/GitHub/fuzheng1998.github.io/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/Users/snowdenfu/Documents/GitHub/fuzheng1998.github.io/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/Users/snowdenfu/Documents/GitHub/fuzheng1998.github.io/node_modules/bluebird/js/release/promise.js:643:18)
snowdenfu@Snowdens-MacBook-Pro fuzheng1998.github.io % hexo server

```
node version 14.7.0
hexo version 3.9

**Comment by stevenjoezhang** [comment]
Hexo 3.9 is incompatible with Node.js 14. You can choose to:
1. Downgrade to Node.js 12
2. Or upgrade to Hexo 4.2.1 or later

**Comment by fuzheng1998** [comment]
thanks I made it
