### ISSUE TITLE
ERROR Asset render failed: css/main.css

### ISSUE THREAD

**Issue by ghost1372** [hexojs/hexo#4474]
hi When I try to deploy a blog, I get the following error
```
ERROR Asset render failed: css/main.css
TypeError: D:/English-doc/themes/next/source/css/_variables/base.styl:311:31
   307| hexo-config('note.light_bg_offset') is a 'unit' ? (lbg = unit(hexo-config('note.light_bg_offset'),"%")) : (lbg = 0)
   308|
   309| // Default
   310| $note-default-border        = #777
   311| $note-default-bg            = lighten(spin($note-default-border, 0), 94% + lbg)
--------------------------------------^
   312| $note-default-text          = $note-default-border
   313| $note-default-icon          = "\f0a9"
   314|

Cannot read property 'nodes' of undefined

    at Evaluator.vendors (D:\English-doc\node_modules\stylus\lib\visitor\evaluator.js:1570:32)
    at Evaluator.unvendorize (D:\English-doc\node_modules\stylus\lib\visitor\evaluator.js:1584:30)
    at Evaluator.visitCall (D:\English-doc\node_modules\stylus\lib\visitor\evaluator.js:484:24)
    at Evaluator.Visitor.visit (D:\English-doc\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (D:\English-doc\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitExpression (D:\English-doc\node_modules\stylus\lib\visitor\evaluator.js:644:26)
    at Evaluator.Visitor.visit (D:\English-doc\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (D:\English-doc\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitIdent (D:\English-doc\node_modules\stylus\lib\visitor\evaluator.js:551:22)
    at Evaluator.Visitor.visit (D:\English-doc\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (D:\English-doc\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitBlock (D:\English-doc\node_modules\stylus\lib\visitor\evaluator.js:720:39)
    at Evaluator.Visitor.visit (D:\English-doc\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (D:\English-doc\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.importFile (D:\English-doc\node_modules\stylus\lib\visitor\evaluator.js:99:18)
    at Evaluator.visitImport (D:\English-doc\node_modules\stylus\lib\visitor\evaluator.js:920:27)
    at Evaluator.Visitor.visit (D:\English-doc\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (D:\English-doc\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitBlock (D:\English-doc\node_modules\stylus\lib\visitor\evaluator.js:720:39)
    at Evaluator.Visitor.visit (D:\English-doc\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (D:\English-doc\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at visitBody (D:\English-doc\node_modules\stylus\lib\visitor\evaluator.js:433:17)

```

this is my package.json
```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.9.0"
  },
  "dependencies": {
    "hexo": "^3.8.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-marked": "^0.3.2",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.3"
  }
}

```

**Comment by stevenjoezhang** [comment]
Try this:
```
npm install hexo-renderer-stylus@1.1.0
hexo clean
```

**Comment by ghost1372** [comment]
@stevenjoezhang  tnx but not worked

**Comment by stevenjoezhang** [comment]
I found a similar issue, but it was not resolved: https://github.com/hexojs/hexo/issues/3058
Maybe you can open an issue here, because the error message comes from within stylus package: https://github.com/stylus/stylus/issues

**Comment by ghost1372** [comment]
@stevenjoezhang  I found the solution after some research
I do not know why, but when I moved the blog to another place (desktop), it generated without any problems and was deployed on the host.

Now either this problem is from NodeJS or from Hexo or something special may be in that path
