### ISSUE TITLE
After I input hexo generate, the html file under my /blog/public file did not render successfully, but the template file of swig. It may be the reason why I input npm audit fix --force. Now I don’t know how to adjust it, request help.

### ISSUE THREAD

**Issue by DjangoPan** [hexojs/hexo#4495]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [ ] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Question

After I input hexo generate, the html file under my /blog/public file did not render successfully, but the template file of swig. It may be the reason why I input npm audit fix --force. Now I don’t know how to adjust it, request help.

## Environment & Settings

**Node.js & npm version**

```
node -v
v12.18.3
npm -v
6.14.6
```

**Your site `_config.yml`** (Optional)

```
i can confirm that this file is OK......
```

**Your theme `_config.yml`** (Optional)

```
Also I can confirm this file is OK......
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
npm ls --depth 0
hexo-site@0.0.0 /Users/django/Public/MyBlog
├── clipboard@2.0.6
├── eslint@7.7.0
├── hexo@5.1.1
├── hexo-admin@2.3.0
├── hexo-asset-image@1.0.0
├── hexo-baidu-url-submit@0.0.6
├── hexo-deployer-git@2.1.0
├── hexo-douban@1.1.3
├── hexo-filter-github-emojis@2.1.0
├── hexo-generator-archive@0.1.5
├── hexo-generator-baidu-sitemap@0.1.9
├── hexo-generator-category@0.1.3
├── hexo-generator-feed@3.0.0
├── hexo-generator-index-pin-top@0.2.2
├── hexo-generator-searchdb@1.3.2
├── hexo-generator-sitemap@2.1.0
├── hexo-generator-tag@0.2.0
├── hexo-helper-live2d@3.1.1
├── hexo-lazyload-image@1.0.9
├── hexo-leancloud-counter-security@1.5.0
├── hexo-reference@1.0.4
├── hexo-related-popular-posts@5.0.0
├── hexo-renderer-ejs@0.3.1
├── hexo-renderer-marked@3.1.0
├── hexo-renderer-stylus@0.3.3
├── hexo-server@0.3.3
├── hexo-tag-aplayer@3.0.4
├── hexo-tag-cloud@2.1.2
├── hexo-wordcount@6.0.1
├── image-size@0.8.3
├── live2d-widget-model-wanko@1.0.5
├── quicklink@2.0.0
├── react@16.13.1
└── react-dom@16.13.1
```

**Your package.json `package.json`**

```
cat package.json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "5.1.1"
  },
  "dependencies": {
    "clipboard": "^2.0.6",
    "eslint": "^7.7.0",
    "hexo": "^5.1.1",
    "hexo-admin": "^2.3.0",
    "hexo-asset-image": "^1.0.0",
    "hexo-baidu-url-submit": "0.0.6",
    "hexo-deployer-git": "^2.1.0",
    "hexo-douban": "^1.1.3",
    "hexo-filter-github-emojis": "^2.1.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-baidu-sitemap": "^0.1.9",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^3.0.0",
    "hexo-generator-index-pin-top": "^0.2.2",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-sitemap": "^2.1.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-helper-live2d": "^3.1.1",
    "hexo-lazyload-image": "^1.0.9",
    "hexo-leancloud-counter-security": "^1.5.0",
    "hexo-reference": "^1.0.4",
    "hexo-related-popular-posts": "^5.0.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-marked": "^3.1.0",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.3",
    "hexo-tag-aplayer": "^3.0.4",
    "hexo-tag-cloud": "^2.1.2",
    "hexo-wordcount": "^6.0.1",
    "image-size": "^0.8.3",
    "live2d-widget-model-wanko": "^1.0.5",
    "quicklink": "^2.0.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1"
  }
}

```

## Others
And my html file just like this:

{% extends '_layout.swig' %}
{% import '_macro/post.swig' as post_template %}
{% import '_macro/sidebar.swig' as sidebar_template %}

{% block title %}{{ page.title }} | {{ config.title }}{% endblock %}

{% block page_class %}page-post-detail{% endblock %}

{% block content %}

  <div id="posts" class="posts-expand">
    {{ post_template.render(page) }}

    <div class="post-spread">
      {% if theme.jiathis %}
        {% include '_partials/share/jiathis.swig' %}
      {% elseif theme.baidushare %}
        {% include '_partials/share/baidushare.swig' %}
      {% elseif theme.add_this_id %}
        {% include '_partials/share/add-this.swig' %}
      {% elseif theme.duoshuo_shortname and theme.duoshuo_share %}
        {% include '_partials/share/duoshuo_share.swig' %}
      {% endif %}
    </div>
  </div>

{% endblock %}

{% block sidebar %}
  {{ sidebar_template.render(true) }}
{% endblock %}

{% block script_extra %}
  {% include '_scripts/pages/post-details.swig' %}
{% endblock %}

**Comment by stevenjoezhang** [comment]
Run
```
npm i hexo-renderer-swig
```

**Comment by DjangoPan** [comment]
> Run
> 
> ```
> npm i hexo-renderer-swig
> ```

there is a new error after i run 
```
hexo g
```
```
INFO  Validating config
WARN  Deprecated config detected: "external_link" with a Boolean value is deprecated. See https://hexo.io/docs/configuration for more details.
INFO  Start processing
ERROR {
  err: Error: Unexpected variable "with" on line 2.
      at TokenParser.<anonymous> (/Users/django/Public/MyBlog/node_modules/hexo-renderer-swig/node_modules/swig/lib/tags/import.js:76:13)
      at TokenParser.parseToken (/Users/django/Public/MyBlog/node_modules/hexo-renderer-swig/node_modules/swig/lib/parser.js:148:15)
      at /Users/django/Public/MyBlog/node_modules/hexo-renderer-swig/node_modules/swig/lib/parser.js:86:12
      at Object.exports.each (/Users/django/Public/MyBlog/node_modules/hexo-renderer-swig/node_modules/swig/lib/utils.js:45:11)
      at TokenParser.parse (/Users/django/Public/MyBlog/node_modules/hexo-renderer-swig/node_modules/swig/lib/parser.js:76:11)
      at parseTag (/Users/django/Public/MyBlog/node_modules/hexo-renderer-swig/node_modules/swig/lib/parser.js:577:12)
      at /Users/django/Public/MyBlog/node_modules/hexo-renderer-swig/node_modules/swig/lib/parser.js:640:15
      at Object.exports.each (/Users/django/Public/MyBlog/node_modules/hexo-renderer-swig/node_modules/swig/lib/utils.js:45:11)
      at Object.exports.parse (/Users/django/Public/MyBlog/node_modules/hexo-renderer-swig/node_modules/swig/lib/parser.js:624:9)
      at exports.Swig.parse (/Users/django/Public/MyBlog/node_modules/hexo-renderer-swig/node_modules/swig/lib/swig.js:354:19)
      at Object.precompile (/Users/django/Public/MyBlog/node_modules/hexo-renderer-swig/node_modules/swig/lib/swig.js:486:23)
      at Object.compile (/Users/django/Public/MyBlog/node_modules/hexo-renderer-swig/node_modules/swig/lib/swig.js:606:16)
      at Function.swigRenderer.compile (/Users/django/Public/MyBlog/node_modules/hexo-renderer-swig/lib/renderer.js:42:15)
      at _View._precompile (/Users/django/Public/MyBlog/node_modules/hexo/lib/theme/view.js:129:33)
      at new View (/Users/django/Public/MyBlog/node_modules/hexo/lib/theme/view.js:27:10)
      at new _View (/Users/django/Public/MyBlog/node_modules/hexo/lib/theme/index.js:33:5)
      at Theme.setView (/Users/django/Public/MyBlog/node_modules/hexo/lib/theme/index.js:65:18)
      at /Users/django/Public/MyBlog/node_modules/hexo/lib/theme/processors/view.js:14:14
      at tryCatcher (/Users/django/Public/MyBlog/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/Users/django/Public/MyBlog/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/Users/django/Public/MyBlog/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/Users/django/Public/MyBlog/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/Users/django/Public/MyBlog/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/Users/django/Public/MyBlog/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/Users/django/Public/MyBlog/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/Users/django/Public/MyBlog/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/Users/django/Public/MyBlog/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:456:21)
} Process failed: %s layout/album.swig
```

**Comment by stevenjoezhang** [comment]
The error message means that there is a syntax error in the theme's template file. Please contact the maintainer of the theme for help.

**Comment by DjangoPan** [comment]
aaaaa,after i deleted the album.swig,it worked!
think you so much!

**Comment by stevenjoezhang** [comment]
You're welcome 😊
