### ISSUE TITLE
`hexo generate --bail` seems to read some route files as string instead of buffers

### ISSUE THREAD

**Issue by oncletom** [hexojs/hexo#4499]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Expected behavior

`hexo generate --bail` renders my fails, and stops if one file failed to render.

## Actual behavior

`hexo generate --bail` produce an error on CSS and JavaScript files:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "list[0]" argument must be an instance of Buffer or Uint8Array. Received type string ('/*! normalize.css v8.0.1...)
    at Function.concat (buffer.js:570:13)
    at /Users/oncletom/workspace/talks/node_modules/hexo/lib/plugins/console/generate.js:86:32
    at tryCatcher (/Users/oncletom/workspace/talks/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/oncletom/workspace/talks/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/oncletom/workspace/talks/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/oncletom/workspace/talks/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/oncletom/workspace/talks/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/Users/oncletom/workspace/talks/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/oncletom/workspace/talks/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/oncletom/workspace/talks/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/oncletom/workspace/talks/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:458:21) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

## How to reproduce?

* Ensure you have a site with CSS or JS static assets
* Run `./node_modules/.bin/hexo clean`
* Run `./node_modules/.bin/hexo generate --bail` (will produce an error on each file it fails to copy)
* Try instead with `./node_modules/.bin/hexo generate` (will work)

## Is the problem still there under "Safe mode"?

Yes

## Environment & Settings

**Node.js & npm version(`node -v && npm -v`)**

```
v14.8.0
6.14.7
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
├── decktape@3.1.0
├── hexo@5.1.1
├── hexo-algolia@1.3.1
├── hexo-cli@4.2.0
├── hexo-generator-feed@3.0.0
├── hexo-generator-index@2.0.0
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-markdown-it@4.1.0
├── hexo-server@2.0.0
├── hexo-theme-oncletom@2.16.2 (github:oncletom/hexo-theme#41cf05329caf888cc87c89f3188afe6f980606f3)
└── markdown-it-attrs@3.0.3
```

**Your package.json `package.json`**

```
{
  "name": "talks",
  "version": "3.2.0",
  "description": "Public talks provided either in English or French, about JavaScript or human-centric topics.",
  "private": true,
  "scripts": {
    "prepare": "export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1",
    "build": "hexo generate",
    "build:pdf": "decktape reveal \"https://oncletom.io/talks/$YEAR/$EVENT/\" slides-thomas-parisot.pdf",
    "start": "hexo server",
    "new": "hexo new",
    "test": "exit 0"
  },
  "repository": {
    "type": "git",
    "url": "git://github.com/oncletom/talks.git"
  },
  "keywords": [
    "talks",
    "javascript",
    "french",
    "english",
    "conference",
    "sharing",
    "knowledge"
  ],
  "author": "Thomas Parisot (https://oncletom.io)",
  "license": "BSD",
  "readmeFilename": "README.md",
  "hexo": {
    "version": "5.1.1"
  },
  "dependencies": {
    "hexo": "^5.1.1",
    "hexo-algolia": "^1.3.1",
    "hexo-cli": "^4.2.0",
    "hexo-generator-feed": "^3.0.0",
    "hexo-generator-index": "^2.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-markdown-it": "^4.1.0",
    "hexo-server": "^2.0.0",
    "hexo-theme-oncletom": "github:oncletom/hexo-theme#semver:^v2",
    "markdown-it-attrs": "^3.0.3"
  },
  "optionalDependencies": {
    "decktape": "^3.1.0"
  }
}

```

## Others

It happens here:

https://github.com/hexojs/hexo/blob/08c8b23621ab834a1c827247c290e32788ddb0cc/lib/plugins/console/generate.js#L86

`buffers` entries are strings on text files (CSS, JS assets) when `--bail` flag is on. `Buffer.concat()` expects array content to be of type `Buffer` (which `route.get()` is supposed to deliver).

But it seems the `--bail` option has an influence on how the cache writes its content:

https://github.com/hexojs/hexo/blob/08c8b23621ab834a1c827247c290e32788ddb0cc/lib/plugins/console/generate.js#L108-L110

For some reason, the passthrough seems to ensure text files are read as buffers:

https://github.com/hexojs/hexo/blob/08c8b23621ab834a1c827247c290e32788ddb0cc/lib/plugins/console/generate.js#L117

**Comment by oncletom** [comment]
Side note: this error was not thrown on hexo@3, maybe hexo@4. I stumbled on it after upgrading to hexo@5

**Comment by oncletom** [comment]
Thank you @ppoffice for the fix 🙂
