### ISSUE TITLE
hexo -g is err

### ISSUE THREAD

**Issue by zhixuan666** [hexojs/hexo#4539]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Expected behavior
hexo -g
## Actual behavior
```
nhandled rejection Template render error: (unknown path)
  unexpected end of file
    at Object._prettifyError (D:\workspace\blog\node_modules\nunjucks\src\lib.js:36:11)
    at Template.render (D:\workspace\blog\node_modules\nunjucks\src\environment.js:536:21)
    at Environment.renderString (D:\workspace\blog\node_modules\nunjucks\src\environment.js:378:17)
    at D:\workspace\blog\node_modules\hexo\lib\extend\tag.js:236:16
    at tryCatcher (D:\workspace\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Function.Promise.fromNode.Promise.fromCallback (D:\workspace\blog\node_modules\bluebird\js\release\promise.js:209:30)
    at Tag.render (D:\workspace\blog\node_modules\hexo\lib\extend\tag.js:235:20)
    at Object.onRenderEnd (D:\workspace\blog\node_modules\hexo\lib\hexo\post.js:283:22)
    at D:\workspace\blog\node_modules\hexo\lib\hexo\render.js:79:21
    at tryCatcher (D:\workspace\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\workspace\blog\node_modules\bluebird\js\release\promise.js:547:31) 
    at Promise._settlePromise (D:\workspace\blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\workspace\blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\workspace\blog\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (D:\workspace\blog\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (D:\workspace\blog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\workspace\blog\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues (D:\workspace\blog\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
```
## How to reproduce?

* Step1
* Step2
* etc...

## Environment & Settings

**Node.js & npm version(`node -v && npm -v`)**
hexo: 5.1.1
hexo-cli: 4.2.0
os: Windows_NT 10.0.18363 win32 x64
node: 12.18.3
v8: 7.8.279.23-node.39
uv: 1.38.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.16.0
modules: 72
nghttp2: 1.41.0
napi: 6
llhttp: 2.0.4
http_parser: 2.9.3
openssl: 1.1.1g
cldr: 37.0
icu: 67.1
tz: 2019c
unicode: 13.0

```
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
hexo-site@0.0.0 D:\workspace\blog
+-- hexo@5.1.1
+-- hexo-deployer-git@2.1.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-index@2.0.0
+-- hexo-generator-searchdb@1.3.3
+-- hexo-generator-sitemap@2.1.0
+-- hexo-generator-tag@1.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@3.2.0
+-- hexo-renderer-stylus@2.0.1
+-- hexo-server@2.0.0
+-- hexo-symbols-count-time@0.7.1
`-- hexo-wordcount@6.0.1
```

**Your package.json `package.json`**

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "5.1.1"
  },
  "dependencies": {
    "hexo": "^5.0.0",
    "hexo-deployer-git": "^2.1.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^2.0.0",
    "hexo-generator-searchdb": "^1.3.3",
    "hexo-generator-sitemap": "^2.1.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^3.0.0",
    "hexo-renderer-stylus": "^2.0.0",
    "hexo-server": "^2.0.0",
    "hexo-symbols-count-time": "^0.7.1",
    "hexo-wordcount": "^6.0.1"
  }
}

```

## Others

[I an writing this post.md](https://raw.githubusercontent.com/zhixuan666/gh-blog/master/Github-Hexo-Next%E6%90%AD%E5%BB%BA%E5%8D%9A%E5%AE%A2.md)

**Comment by BH1SCW** [comment]
same with me

**Comment by LanYunDev** [comment]
请问如何解决的?我也遇到了此问题.
<img width="730" alt="image" src="https://user-images.githubusercontent.com/95263282/177995353-a8b12e3d-b53e-4aba-b711-ad0977741f25.png">
