### ISSUE TITLE
err: Error: Spawn failed at ChildProcess.<anonymous>

### ISSUE THREAD

**Issue by leilfs** [hexojs/hexo#4549]
## Check List

Please check followings before submitting a new issue.

- [ ] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [ ] I have already searched existing issues and they are not help to me
- [ ] I examined error or warning messages and it's difficult to solve
- [ ] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [ ] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Question

error message:

[master 3d5a622] Site updated: 2020-10-03 20:27:08
 2 files changed, 2 insertions(+), 2 deletions(-)
fatal: could not read Username for 'https://github.com': No such file or directory
FATAL {
  err: Error: Spawn failed
      at ChildProcess.<anonymous> (C:\CODE\blog\node_modules\hexo-deployer-git\node_modules\hexo-util\lib\spawn.js:51:21)
      at ChildProcess.emit (events.js:315:20)
      at ChildProcess.cp.emit (C:\CODE\blog\node_modules\cross-spawn\lib\enoent.js:34:29)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12) {
    code: 128
  }
}

## Environment & Settings

**Node.js & npm version**

``` Node.js version v12.18.4.
``` npm version 6.14.6

**Hexo and Plugin version(`npm ls --depth 0`)**

``` hexo version 5.2.0
```
**Your package.json `package.json`**

```
```

**Comment by YoshinoriN** [comment]
@reinsss 

Please check your deploy settings.
I think the below issue will help you :)

> https://github.com/hexojs/hexo/issues/2778
