### ISSUE TITLE
Hexo doesn't work

### ISSUE THREAD

**Issue by hesy-zhoulijie** [hexojs/hexo#4558]
# This is what displayed after I entered "hexo" in the console
```
console.js:35
    throw new TypeError('Console expects a writable stream instance');
    ^

TypeError: Console expects a writable stream instance
    at new Console (console.js:35:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/hexo/node_modules/hexo-log/lib/log.js:31:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/hexo/node_modules/hexo-cli/lib/context.js:3:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
```
> Nothing works

## NPM info
```
{ npm: '6.14.8',
  ares: '1.14.0',
  cldr: '32.0.1',
  http_parser: '2.7.1',
  icu: '60.2',
  modules: '57',
  nghttp2: '1.30.0',
  node: '8.10.0',
  openssl: '1.0.2n',
  tz: '2017c',
  unicode: '10.0',
  uv: '1.18.0',
  v8: '6.2.414.50',
  zlib: '1.2.11' }
```

**Comment by zkqiang** [comment]
Try to upgrade your node, hexo 5 depends on node version >= 10.13.0

**Comment by noraj** [comment]
I recommend nodejs LTS 12.19.0 (managed with [asdf](https://asdf-vm.com/) if you need a virtual environment)
