### ISSUE TITLE
 err: TypeError: Expected pattern to be a non-empty string

### ISSUE THREAD

**Issue by JanU-YieG** [hexojs/hexo#4608]
INFO  Validating config
INFO  Start processing
ERROR {
  err: TypeError: Expected pattern to be a non-empty string
      at picomatch (/home/borer/Hexo/borer-blog/node_modules/picomatch/lib/picomatch.js:48:11)
      at Function.micromatch.isMatch (/home/borer/Hexo/borer-blog/node_modules/micromatch/index.js:123:50)
      at isMatch (/home/borer/Hexo/borer-blog/node_modules/hexo/lib/plugins/processor/common.js:12:21)
      at Pattern.pattern [as match] (/home/borer/Hexo/borer-blog/node_modules/hexo/lib/plugins/processor/post.js:231:61)
      at /home/borer/Hexo/borer-blog/node_modules/hexo/lib/box/index.js:133:40
      at tryCatcher (/home/borer/Hexo/borer-blog/node_modules/bluebird/js/release/util.js:16:23)
      at Object.gotValue (/home/borer/Hexo/borer-blog/node_modules/bluebird/js/release/reduce.js:168:18)
      at Object.gotAccum (/home/borer/Hexo/borer-blog/node_modules/bluebird/js/release/reduce.js:155:25)
      at Object.tryCatcher (/home/borer/Hexo/borer-blog/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/home/borer/Hexo/borer-blog/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/home/borer/Hexo/borer-blog/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/home/borer/Hexo/borer-blog/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/home/borer/Hexo/borer-blog/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/home/borer/Hexo/borer-blog/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/home/borer/Hexo/borer-blog/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/home/borer/Hexo/borer-blog/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/home/borer/Hexo/borer-blog/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:461:21)
} Process failed: %s _posts/about-me.md
ERROR {
  err: TypeError: Expected pattern to be a non-empty string
      at picomatch (/home/borer/Hexo/borer-blog/node_modules/picomatch/lib/picomatch.js:48:11)
      at Function.micromatch.isMatch (/home/borer/Hexo/borer-blog/node_modules/micromatch/index.js:123:50)
      at isMatch (/home/borer/Hexo/borer-blog/node_modules/hexo/lib/plugins/processor/common.js:12:21)
      at Pattern.pattern [as match] (/home/borer/Hexo/borer-blog/node_modules/hexo/lib/plugins/processor/post.js:231:61)
      at /home/borer/Hexo/borer-blog/node_modules/hexo/lib/box/index.js:133:40
      at tryCatcher (/home/borer/Hexo/borer-blog/node_modules/bluebird/js/release/util.js:16:23)
      at Object.gotValue (/home/borer/Hexo/borer-blog/node_modules/bluebird/js/release/reduce.js:168:18)
      at Object.gotAccum (/home/borer/Hexo/borer-blog/node_modules/bluebird/js/release/reduce.js:155:25)
      at Object.tryCatcher (/home/borer/Hexo/borer-blog/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/home/borer/Hexo/borer-blog/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/home/borer/Hexo/borer-blog/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/home/borer/Hexo/borer-blog/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/home/borer/Hexo/borer-blog/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/home/borer/Hexo/borer-blog/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/home/borer/Hexo/borer-blog/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/home/borer/Hexo/borer-blog/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/home/borer/Hexo/borer-blog/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:461:21)
} Process failed: %s _posts/valuable-links.md
INFO  Files loaded in 391 ms
INFO  Generated: images/2021-01-04_08-56.png
INFO  Generated: images/avatar.gif

**Comment by JanU-YieG** [comment]
the _config.yml format is wrong.
