### ISSUE TITLE
Unable to render and report errors 无法渲染和报错

### ISSUE THREAD

**Issue by XiaMoHuaHuo-CN** [hexojs/hexo#4692]
## Check List

Please check followings before submitting a new issue.

- [ √ ] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [ √ ] I have already searched existing issues and they are not help to me
- [ √ ] I examined error or warning messages and it's difficult to solve
- [ √ ] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [ √ ] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Question

Is in 'C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob'

node.js version:14.16.1 LTS

hexo version:5.4.0

question:
ERROR { err: TypeError: C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\themes\Wikitten\layout\layout.ejs:1 >> 1| <%- partial('common/head') %> 2| <body> 3|     <div id="container"> 4|         <%- partial('common/header') %> C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\themes\Wikitten\layout\common\head.ejs:22 20|     %> 21|     <title><% if (title) { %><%= title %> | <% } %><%= config.title %></title> >> 22|     <% 23|        var keywords_content = undefined; 24|        if (page.keywords) { 25|            keywords_content = page.keywords; page.tags.toArray is not a function at eval (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\themes\Wikitten\layout\common\head.ejs:46:41) at head (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\ejs\lib\ejs.js:682:17) at _View._compiledSync (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\hexo\lib\theme\view.js:132:24) at _View.renderSync (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\hexo\lib\theme\view.js:59:25) at Object.partial (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\hexo\lib\plugins\helper\partial.js:34:15) at eval (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\themes\Wikitten\layout\layout.ejs:10:17) at layout (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\ejs\lib\ejs.js:682:17) at _View._compiled (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\hexo\lib\theme\view.js:136:50) at _View.render (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\hexo\lib\theme\view.js:39:17) at C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\hexo\lib\theme\view.js:51:25 at tryCatcher (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\bluebird\js\release\util.js:16:23) at Promise._settlePromiseFromHandler (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\bluebird\js\release\promise.js:547:31) at Promise._settlePromise (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\bluebird\js\release\promise.js:604:18) at Promise._settlePromise0 (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\bluebird\js\release\promise.js:649:10) at Promise._settlePromises (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\bluebird\js\release\promise.js:729:18) at _drainQueueStep (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\bluebird\js\release\async.js:93:12) at _drainQueue (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\bluebird\js\release\async.js:86:9) at Async._drainQueues (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\bluebird\js\release\async.js:102:5) at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\bluebird\js\release\async.js:15:14) at processImmediate (internal/timers.js:461:21) { path: 'C:\\Users\\Administrator\\Desktop\\MCinaBoxWiKi\\mob\\themes\\Wikitten\\layout\\layout.ejs' } } Render HTML failed: en/MCinaBox/index.html ERROR { err: TypeError: C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\themes\Wikitten\layout\layout.ejs:1 >> 1| <%- partial('common/head') %> 2| <body> 3|     <div id="container"> 4|         <%- partial('common/header') %> C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\themes\Wikitten\layout\common\head.ejs:22 20|     %> 21|     <title><% if (title) { %><%= title %> | <% } %><%= config.title %></title> >> 22|     <% 23|        var keywords_content = undefined; 24|        if (page.keywords) { 25|            keywords_content = page.keywords; page.tags.toArray is not a function at eval (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\themes\Wikitten\layout\common\head.ejs:46:41) at head (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\ejs\lib\ejs.js:682:17) at _View._compiledSync (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\hexo\lib\theme\view.js:132:24) at _View.renderSync (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\hexo\lib\theme\view.js:59:25) at Object.partial (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\hexo\lib\plugins\helper\partial.js:34:15) at eval (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\themes\Wikitten\layout\layout.ejs:10:17) at layout (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\ejs\lib\ejs.js:682:17) at _View._compiled (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\hexo\lib\theme\view.js:136:50) at _View.render (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\hexo\lib\theme\view.js:39:17) at C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\hexo\lib\theme\view.js:51:25 at tryCatcher (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\bluebird\js\release\util.js:16:23) at Promise._settlePromiseFromHandler (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\bluebird\js\release\promise.js:547:31) at Promise._settlePromise (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\bluebird\js\release\promise.js:604:18) at Promise._settlePromise0 (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\bluebird\js\release\promise.js:649:10) at Promise._settlePromises (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\bluebird\js\release\promise.js:729:18) at _drainQueueStep (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\bluebird\js\release\async.js:93:12) at _drainQueue (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\bluebird\js\release\async.js:86:9) at Async._drainQueues (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\bluebird\js\release\async.js:102:5) at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\bluebird\js\release\async.js:15:14) at processImmediate (internal/timers.js:461:21) { path: 'C:\\Users\\Administrator\\Desktop\\MCinaBoxWiKi\\mob\\themes\\Wikitten\\layout\\layout.ejs' } } Render HTML failed: zh-CN/MCinaBox/index.html ERROR TypeError: C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\themes\Wikitten\layout\layout.ejs:1 >> 1| <%- partial('common/head') %> 2| <body> 3|     <div id="container"> 4|         <%- partial('common/header') %> C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\themes\Wikitten\layout\common\head.ejs:22 20|     %> 21|     <title><% if (title) { %><%= title %> | <% } %><%= config.title %></title> >> 22|     <% 23|        var keywords_content = undefined; 24|        if (page.keywords) { 25|            keywords_content = page.keywords; page.tags.toArray is not a function at eval (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\themes\Wikitten\layout\common\head.ejs:46:41) at head (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\ejs\lib\ejs.js:682:17) at _View._compiledSync (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\hexo\lib\theme\view.js:132:24) at _View.renderSync (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\hexo\lib\theme\view.js:59:25) at Object.partial (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\hexo\lib\plugins\helper\partial.js:34:15) at eval (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\themes\Wikitten\layout\layout.ejs:10:17) at layout (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\ejs\lib\ejs.js:682:17) at _View._compiled (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\hexo\lib\theme\view.js:136:50) at _View.render (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\hexo\lib\theme\view.js:39:17) at C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\hexo\lib\theme\view.js:51:25 at tryCatcher (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\bluebird\js\release\util.js:16:23) at Promise._settlePromiseFromHandler (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\bluebird\js\release\promise.js:547:31) at Promise._settlePromise (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\bluebird\js\release\promise.js:604:18) at Promise._settlePromise0 (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\bluebird\js\release\promise.js:649:10) at Promise._settlePromises (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\bluebird\js\release\promise.js:729:18) at _drainQueueStep (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\bluebird\js\release\async.js:93:12) at _drainQueue (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\bluebird\js\release\async.js:86:9) at Async._drainQueues (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\bluebird\js\release\async.js:102:5) at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\bluebird\js\release\async.js:15:14) at processImmediate (internal/timers.js:461:21) { path: 'C:\\Users\\Administrator\\Desktop\\MCinaBoxWiKi\\mob\\themes\\Wikitten\\layout\\layout.ejs' } ERROR TypeError: C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\themes\Wikitten\layout\layout.ejs:1 >> 1| <%- partial('common/head') %> 2| <body> 3|     <div id="container"> 4|         <%- partial('common/header') %> C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\themes\Wikitten\layout\common\head.ejs:22 20|     %> 21|     <title><% if (title) { %><%= title %> | <% } %><%= config.title %></title> >> 22|     <% 23|        var keywords_content = undefined; 24|        if (page.keywords) { 25|            keywords_content = page.keywords; page.tags.toArray is not a function at eval (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\themes\Wikitten\layout\common\head.ejs:46:41) at head (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\ejs\lib\ejs.js:682:17) at _View._compiledSync (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\hexo\lib\theme\view.js:132:24) at _View.renderSync (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\hexo\lib\theme\view.js:59:25) at Object.partial (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\hexo\lib\plugins\helper\partial.js:34:15) at eval (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\themes\Wikitten\layout\layout.ejs:10:17) at layout (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\ejs\lib\ejs.js:682:17) at _View._compiled (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\hexo\lib\theme\view.js:136:50) at _View.render (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\hexo\lib\theme\view.js:39:17) at C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\hexo\lib\theme\view.js:51:25 at tryCatcher (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\bluebird\js\release\util.js:16:23) at Promise._settlePromiseFromHandler (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\bluebird\js\release\promise.js:547:31) at Promise._settlePromise (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\bluebird\js\release\promise.js:604:18) at Promise._settlePromise0 (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\bluebird\js\release\promise.js:649:10) at Promise._settlePromises (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\bluebird\js\release\promise.js:729:18) at _drainQueueStep (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\bluebird\js\release\async.js:93:12) at _drainQueue (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\bluebird\js\release\async.js:86:9) at Async._drainQueues (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\bluebird\js\release\async.js:102:5) at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Administrator\Desktop\MCinaBoxWiKi\mob\node_modules\bluebird\js\release\async.js:15:14) at processImmediate (internal/timers.js:461:21) { path: 'C:\\Users\\Administrator\\Desktop\\MCinaBoxWiKi\\mob\\themes\\Wikitten\\layout\\layout.ejs' }

<h3>Site Config.yml</h3>

# Hexo Configuration
## Source: https://github.com/hexojs/hexo/

# Site
title: MCinaBox Wiki
subtitle: ''
description: ''
keywords:
author: MCinaBox Wiki
language: zh-CN
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://mcinaboxwiki.ml
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:
# Extensions
## Themes: https://hexo.io/themes/
theme: Wikitten

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repository: https://github.com/XiaMoHuaHuo-CN/mcinaboxwiki.git
  branch: master

<h3>theme config.yml</h3>

# Menus
menu:
  AOF群组-QQ: /QQqun
  AOF群组-Discord: https://discord.gg/bZjGNPqvDU
# Customize
customize:
    logo:
        enabled: true
        width: 40
        height: 40
        url: https://mcinabox.top/src/ico.png
    profile:
        enabled: false # Whether to show profile bar
        avatar: # css/images/avatar.png
        author: MCinabox
        author_title: Designer & Programmer
        follow: https://github.com/AOF-Dev/MCinabox
    highlight: monokai
    sidebar: left # sidebar position, options: left, right
    category_perExpand: false # enable article categories list per expanding
    thumbnail: true # enable posts thumbnail, options: true, false
    favicon: https://mcinabox.top/src/ico.png # path to favicon
    default_index_file: index.md # if this, it will display at site index instead of default index page
    social_links:
        github: https://github.com/AOF-Dev/MCinabox
        rss: /atom.xml
    social_link_tooltip: true # enable the social link tooltip, options: true, false

# Widgets
widgets: # default use category only
    - category
    # - recent_posts
    # - archive
    # - tag
    # - tagcloud
    # - links
    
# Excerpt 
## Enable will truncate auto_excerpt.lines rows in post head to replace excerpt.
auto_excerpt:
    enable: true
    lines: 5

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# History version 
history_control: # make you wiki has history version control in page
    enable: true
    server_link: https://github.com # recommend use GitHub https://github.com
    user: AOF-Dev
    repertory: Wiki-site
    branch: writing

# Comment
comment:
    disqus: # enter disqus shortname here
    duoshuo: # enter duoshuo shortname here
    youyan: # enter youyan uid here

# Share
share: default # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    lightgallery: true # options: true, false
    justifiedgallery: true # options: true, false
    mathjax: true # options: true, false - to enable use Mathjax in your article
    google_analytics: # enter the tracking ID for your Google Analytics
    google_site_verification: # enter Google site verification code
    baidu_analytics: # enter Baidu Analytics hash key
    busuanzi_count: true # options: true, false - to enable busuanzi site pv statistics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
    links:

Hexo and Plugin version

hexo 5.4.0
plugin 5.4.0

package.json

{
  "name": "hexo-theme-Wikitten",
  "version": "0.1.2",
  "private": true,
  "description": "A personal wiki imitate Wikitten style for Hexo",
  "keywords": [
    "hexo",
    "theme",
    "wiki",
    "personal"
  ],
  "license": "MIT",
  "hexo": {
    "version": "3.6.0"
  },
  "dependencies": {
    "hexo": "^3.6.0",
    "hexo-autonofollow": "^1.0.1",
    "hexo-directory-category": "^1.0.5",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-json-content": "^3.0.1",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-renderer-stylus": "^0.3.3"
  }
}

Others
This is a wiki for MCinaBox,but I can't render it now.

**Comment by XiaMoHuaHuo-CN** [comment]
已经解决，原因是不在_post的文件夹中的文件有tag标签
