### ISSUE TITLE
hexo g error

### ISSUE THREAD

**Issue by duwei19961021** [hexojs/hexo#4703]
## Check List

Please check followings before submitting a new issue.

- [ ] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [ ] I have already searched existing issues and they are not help to me
- [ ] I examined error or warning messages and it's difficult to solve
- [ ] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [ ] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Question
when i run hexo g,and happend a error, and i never modify config. tow weeks ago, it's healthy,but yestoday,it's error.
(node:14746) ExperimentalWarning: The fs.promises API is experimental
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError: Cannot read property 'name' of null
    at mapTags (/Users/duwei/devops/node_modules/hexo-generator-json-content/dist/main.js:87:40)
    at Array.map (<anonymous>)
    at isIgnored (/Users/duwei/devops/node_modules/hexo-generator-json-content/dist/main.js:76:44)
    at site.pages.filter (/Users/duwei/devops/node_modules/hexo-generator-json-content/dist/main.js:218:53)
    at _Query.filter (/Users/duwei/devops/node_modules/warehouse/lib/query.js:286:11)
    at Hexo.hexo.extend.generator.register (/Users/duwei/devops/node_modules/hexo-generator-json-content/dist/main.js:218:35)
    at Hexo.tryCatcher (/Users/duwei/devops/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Users/duwei/devops/node_modules/bluebird/js/release/method.js:15:34)
    at Promise.map.key (/Users/duwei/devops/node_modules/hexo/lib/hexo/index.js:390:22)
    at tryCatcher (/Users/duwei/devops/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/Users/duwei/devops/node_modules/bluebird/js/release/map.js:68:38)
    at MappingPromiseArray.PromiseArray._iterate (/Users/duwei/devops/node_modules/bluebird/js/release/promise_array.js:115:31)
    at MappingPromiseArray.init (/Users/duwei/devops/node_modules/bluebird/js/release/promise_array.js:79:10)
    at MappingPromiseArray._asyncInit (/Users/duwei/devops/node_modules/bluebird/js/release/map.js:37:10)
    at _drainQueueStep (/Users/duwei/devops/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/Users/duwei/devops/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/duwei/devops/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/duwei/devops/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

## Environment & Settings

**Node.js & npm version**

```
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

**Comment by duwei19961021** [comment]
i try move _posts/*.md file to other directory, and run hexo g，but it's also error

**Comment by stevenjoezhang** [comment]
Hello, please open an issue here: https://github.com/alexbruno/hexo-generator-json-content/issues

**Comment by duwei19961021** [comment]
> Hello, please open an issue here: https://github.com/alexbruno/hexo-generator-json-content/issues

ok
