### ISSUE TITLE
My hexo has some wrong

### ISSUE THREAD

**Issue by kuailekai** [hexojs/hexo#4719]
When I run the `hexo server`,there is some wrong
```
ERROR {
  err: C:\Users\Administrator\kuailelkai\myblog\node_modules\marked\src\marked.js:158
            const prevRenderer = extensions.renderers?.[ext.name];
                                                      ^

  SyntaxError: Unexpected token '.'
      at wrapSafe (internal/modules/cjs/loader.js:915:16)
      at Module._compile (internal/modules/cjs/loader.js:963:27)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
      at Module.load (internal/modules/cjs/loader.js:863:32)
      at Function.Module._load (internal/modules/cjs/loader.js:708:14)
      at Module.require (internal/modules/cjs/loader.js:887:19)
      at require (internal/modules/cjs/helpers.js:74:18)
      at Object.<anonymous> (C:\Users\Administrator\kuailelkai\myblog\node_modules\hexo-renderer-marked\lib\renderer.js:3:16)
      at Module._compile (internal/modules/cjs/loader.js:999:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
      at Module.load (internal/modules/cjs/loader.js:863:32)
      at Function.Module._load (internal/modules/cjs/loader.js:708:14)
      at Module.require (internal/modules/cjs/loader.js:887:19)
      at req (C:\Users\Administrator\kuailelkai\myblog\node_modules\hexo\lib\hexo\index.js:292:23)
      at C:\Users\Administrator\kuailelkai\myblog\node_modules\hexo-renderer-marked\index.js:5:18
      at C:\Users\Administrator\kuailelkai\myblog\node_modules\hexo\lib\hexo\index.js:305:14
      at tryCatcher (C:\Users\Administrator\kuailelkai\myblog\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (C:\Users\Administrator\kuailelkai\myblog\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (C:\Users\Administrator\kuailelkai\myblog\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (C:\Users\Administrator\kuailelkai\myblog\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (C:\Users\Administrator\kuailelkai\myblog\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (C:\Users\Administrator\kuailelkai\myblog\node_modules\bluebird\js\release\async.js:93:12)
} 
```

**Comment by stevenjoezhang** [comment]
It's fixed in https://github.com/markedjs/marked/pull/2109
Run `npm install` again to resolve the issue

**Comment by kuailekai** [comment]
I run `npm install`,but it still has some wrong
