### ISSUE TITLE
hexo g 

### ISSUE THREAD

**Issue by czj-cofi** [hexojs/hexo#4722]
Process failed: %s _config.yml
FATAL {
  **err: TypeError: Cannot read property 'js' of undefined**
      at Hexo.<anonymous> (E:\blog\czj\themes\shoka\scripts\generaters\script.js:24:29)
      at Hexo.tryCatcher (E:\blog\czj\node_modules\bluebird\js\release\util.js:16:23)
      at Hexo.<anonymous> (E:\blog\czj\node_modules\bluebird\js\release\method.js:15:34)
      at E:\blog\czj\node_modules\hexo\lib\hexo\index.js:405:22
      at tryCatcher (E:\blog\czj\node_modules\bluebird\js\release\util.js:16:23)
      at MappingPromiseArray._promiseFulfilled (E:\blog\czj\node_modules\bluebird\js\release\map.js:68:38)
      at MappingPromiseArray.PromiseArray._iterate (E:\blog\czj\node_modules\bluebird\js\release\promise_array.js:115:31)
      at MappingPromiseArray.init (E:\blog\czj\node_modules\bluebird\js\release\promise_array.js:79:10)
      at MappingPromiseArray._asyncInit (E:\blog\czj\node_modules\bluebird\js\release\map.js:37:10)
      at _drainQueueStep (E:\blog\czj\node_modules\bluebird\js\release\async.js:97:12)
      at _drainQueue (E:\blog\czj\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (E:\blog\czj\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (E:\blog\czj\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:462:21)

**Comment by stevenjoezhang** [comment]
https://github.com/amehime/hexo-theme-shoka/blob/master/scripts/generaters/script.js#L24

Please open an issue here: https://github.com/amehime/hexo-theme-shoka/issues
