### ISSUE TITLE
In a hexo markdown article, if the code block "```code```" identifier is used at the beginning of a paragraph, the article rendering error

### ISSUE THREAD

**Issue by kuole-o** [hexojs/hexo#4741]
## Check List

Please check followings before submitting a new issue.

- [x ] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Expected behavior
Normal hexo g and hexo server

## Actual behavior
Report an error

```
INFO  Start processing
FATAL {
  err: Error [Nunjucks Error]: _posts/我的Blog美化日记.md [Line 126, Column 4] unknown block tag: endfolding
      =====               Context Dump               =====
      === (line number probably different from source) ===
    121 | <h2 id="文章页局部html代码不渲染"><a href="#文章页局部html代码不渲染" class="headerlink" title="文章页局部html代码不渲染"></a>文章页局部
html代码不渲染</h2><p>md文章页，部分内容不想经过 Hexo 渲染，则包一层<code>raw</code>标签： </p>
    122 | <!--code￼13-->
    123 | 
    124 | <h2 id="自定义页面添加分享按钮"><a href="#自定义页面添加分享按钮" class="headerlink" title="自定义页面添加分享按钮"></a>自定义页面添加分
享按钮</h2><p>在需要的<code>md</code>文件页面，增加以下代码（目前还没找到自定义页面直接使用post模板的方法。自定义模板布局也好大一堆报错。Hexo不能 
像Hugo一样，非常简单的定义模板或复用模板，有点烦躁。）：  </p>
    125 | <!--code￼14-->
    126 | {% endfolding %}
    127 | 
    128 | 
    129 | <h2 id="自定义页面添加赞赏"><a href="#自定义页面添加赞赏" class="headerlink" title="自定义页面添加赞赏"></a>自定义页面添加赞赏</h2><p>同
上原因，自己手动添加主题的打赏功能按钮。其中<code>css</code>部分，是因为我给全局图片说明文字增加了一个下标，打赏的图下，又不想出现那个符号。  </p>    130 | {% folding blue, 文章md文件插入此处代码 %}
    131 | <!--code￼15-->
      =====             Context Dump Ends            =====
      at formatNunjucksError (E:\src\butterfly\node_modules\hexo\lib\extend\tag.js:171:13)
      at E:\src\butterfly\node_modules\hexo\lib\extend\tag.js:246:36
      at tryCatcher (E:\src\butterfly\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (E:\src\butterfly\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (E:\src\butterfly\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromises (E:\src\butterfly\node_modules\bluebird\js\release\promise.js:725:18)
      at _drainQueueStep (E:\src\butterfly\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (E:\src\butterfly\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (E:\src\butterfly\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (E:\src\butterfly\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:462:21) {
    line: 126,
    location: '\x1B[35m_posts/我的Blog美化日记.md\x1B[39m [Line 126, Column 4]',
    type: 'unknown block tag: endfolding'
  }
} Something's wrong. Maybe you can find the solution here: %s https://hexo.io/docs/troubleshooting.html
INFO  Catch you later
```

## How to reproduce?

* Step1：Create a new article md
* Step2：Copy the content of the attached "bug.txt" file to the newly created .md file.   
* Step3：Execute hexo g or hexo s command

## Is the problem still there under "Safe mode"?

Yes, when I remove the folding and link plug-ins in md, the problem remains. It seems to be a problem with md rendering。

## Environment & Settings

**Node.js & npm version(`node -v && npm -v`)**

```
v14.16.1
6.14.12
```

**Your site `_config.yml`** (Optional)

```yaml
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
hexo-site@0.0.0 E:\work\Git\butterfly
+-- -@0.0.1
+-- @babel/core@7.14.6
+-- @babel/preset-env@7.14.7
+-- @babel/preset-react@7.14.5
+-- aplayer@1.10.1
+-- gulp@4.0.2
+-- gulp-babel@8.0.0
+-- gulp-clean-css@4.3.0
+-- gulp-html-minifier-terser@6.0.1
+-- gulp-htmlclean@2.7.22
+-- gulp-imagemin@7.1.0
+-- gulp-terser@2.0.1
+-- gulp-uglify@3.0.2
+-- hexo@5.4.0
+-- hexo-abbrlink@2.2.1
+-- hexo-autonofollow@1.0.1
+-- hexo-blog-encrypt@3.1.6
+-- hexo-browsersync@0.3.0
+-- hexo-butterfly-douban@1.2.4
+-- hexo-butterfly-swiper@1.0.3
+-- hexo-deploy-tencentcloud-cdn@0.0.3
+-- hexo-deployer-git@3.0.0
+-- hexo-filter-gitcalendar@1.0.6
+-- hexo-filter-nofollow@2.0.2
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-feed@3.0.0
+-- hexo-generator-index@2.0.0
+-- hexo-generator-random@1.0.2
+-- hexo-generator-search@2.4.3
+-- hexo-generator-sitemap@2.1.0
+-- hexo-generator-tag@1.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-jade@0.5.0
+-- hexo-renderer-marked@4.0.0
+-- hexo-renderer-pug@2.0.0
+-- hexo-renderer-stylus@2.0.1
+-- hexo-server@2.0.0
+-- hexo-tag-aplayer@3.0.4
+-- hexo-theme-butterfly@3.8.1
+-- hexo-theme-landscape@0.0.3
+-- hexo-wordcount@6.0.1
+-- nib@1.1.2
+-- object-assign@4.1.1
`-- workbox-build@6.1.5

npm ERR! missing: stylus@0.54.5, required by nib@1.1.2
```

**Your package.json `package.json`**

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "5.4.0"
  },
  "dependencies": {
    "-": "0.0.1",
    "aplayer": "^1.10.1",
    "gulp-html-minifier-terser": "^6.0.1",
    "hexo": "^5.4.0",
    "hexo-abbrlink": "^2.2.1",
    "hexo-autonofollow": "^1.0.1",
    "hexo-blog-encrypt": "^3.1.6",
    "hexo-browsersync": "^0.3.0",
    "hexo-butterfly-douban": "^1.2.4",
    "hexo-butterfly-swiper": "^1.0.3",
    "hexo-deploy-tencentcloud-cdn": "0.0.3",
    "hexo-deployer-git": "^3.0.0",
    "hexo-filter-gitcalendar": "^1.0.6",
    "hexo-filter-nofollow": "^2.0.2",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^3.0.0",
    "hexo-generator-index": "^2.0.0",
    "hexo-generator-random": "^1.0.2",
    "hexo-generator-search": "^2.4.3",
    "hexo-generator-sitemap": "^2.1.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-jade": "^0.5.0",
    "hexo-renderer-marked": "^4.0.0",
    "hexo-renderer-pug": "^2.0.0",
    "hexo-renderer-stylus": "^2.0.1",
    "hexo-server": "^2.0.0",
    "hexo-tag-aplayer": "^3.0.4",
    "hexo-theme-butterfly": "^3.8.1",
    "hexo-theme-landscape": "^0.0.3",
    "hexo-wordcount": "^6.0.1",
    "nib": "^1.1.2",
    "object-assign": "^4.1.1"
  },
  "devDependencies": {
    "@babel/core": "^7.14.6",
    "@babel/preset-env": "^7.14.7",
    "@babel/preset-react": "^7.14.5",
    "gulp": "^4.0.2",
    "gulp-babel": "^8.0.0",
    "gulp-clean-css": "^4.3.0",
    "gulp-htmlclean": "^2.7.22",
    "gulp-imagemin": "^7.1.0",
    "gulp-terser": "^2.0.1",
    "gulp-uglify": "^3.0.2",
    "workbox-build": "^6.1.5"
  }
}
```

## Others

When I added two characters "其中" before the sentence "```data-sites```的值" in the text content in the attached "bug.txt" file, the problem disappeared.
![image](https://user-images.githubusercontent.com/63436555/126416552-b2adcb0a-ac63-4119-8436-9f6ab8009492.png)

**Comment by SukkaW** [comment]
Would you mind pasting your original markdown source here?

**Comment by kuole-o** [comment]
> 你介意在这里粘贴你的原始降价源吗？

Sorry, I can’t reproduce this bug at the moment

**Comment by stevenjoezhang** [comment]
This bug should have been fixed in https://github.com/hexojs/hexo/pull/4780
Feel free to re-open if it is still outstanding.
