### ISSUE TITLE
Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency

### ISSUE THREAD

**Issue by kuole-o** [hexojs/hexo#4742]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Expected behavior
Normal hexo g and hexo server

## Actual behavior
Report an error

```
PS E:\work\Git\butterfly> hexo server
INFO  Validating config
INFO  
  ===================================================================

      #####  #    # ##### ##### ###### #####  ###### #      #   #
      #    # #    #   #     #   #      #    # #      #       # #
      #####  #    #   #     #   #####  #    # #####  #        #
      #    # #    #   #     #   #      #####  #      #        #
      #    # #    #   #     #   #      #   #  #      #        #
      #####   ####    #     #   ###### #    # #      ######   #

                            3.8.1
  ===================================================================
[Browsersync] Access URLs:
 ----------------------------------
          UI: http://localhost:3001
 ----------------------------------
 UI External: http://localhost:3001
 ----------------------------------
INFO  Start processing
INFO  hexo-blog-encrypt: encrypting "多级彩色标题测试" based on the password configured in Front-matter with theme: default.INFO  111 movies have been loaded in 13337 ms
INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
(node:17148) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17148) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:17148) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
(node:17148) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(node:17148) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:17148) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
```

## How to reproduce?

* Step1：
After each execution of the hexo server command, an error occurs when accessing http://localhost:4000/. After deploying to the production environment, there will also be error messages in the console, which is consistent with the local debugging errors. It seems that it is a problem with the "lib" plug-in

## Is the problem still there under "Safe mode"?

Yes

## Environment & Settings

**Node.js & npm version(`node -v && npm -v`)**

```
v14.16.1
6.14.12
```

**Your site `_config.yml`** (Optional)

```yaml
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
hexo-site@0.0.0 E:\work\Git\butterfly
+-- -@0.0.1
+-- @babel/core@7.14.6
+-- @babel/preset-env@7.14.7
+-- @babel/preset-react@7.14.5
+-- aplayer@1.10.1
+-- gulp@4.0.2
+-- gulp-babel@8.0.0
+-- gulp-clean-css@4.3.0
+-- gulp-html-minifier-terser@6.0.1
+-- gulp-htmlclean@2.7.22
+-- gulp-imagemin@7.1.0
+-- gulp-terser@2.0.1
+-- gulp-uglify@3.0.2
+-- hexo@5.4.0
+-- hexo-abbrlink@2.2.1
+-- hexo-autonofollow@1.0.1
+-- hexo-blog-encrypt@3.1.6
+-- hexo-browsersync@0.3.0
+-- hexo-butterfly-douban@1.2.4
+-- hexo-butterfly-swiper@1.0.3
+-- hexo-deploy-tencentcloud-cdn@0.0.3
+-- hexo-deployer-git@3.0.0
+-- hexo-filter-gitcalendar@1.0.6
+-- hexo-filter-nofollow@2.0.2
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-feed@3.0.0
+-- hexo-generator-index@2.0.0
+-- hexo-generator-random@1.0.2
+-- hexo-generator-search@2.4.3
+-- hexo-generator-sitemap@2.1.0
+-- hexo-generator-tag@1.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-jade@0.5.0
+-- hexo-renderer-marked@4.0.0
+-- hexo-renderer-pug@2.0.0
+-- hexo-renderer-stylus@2.0.1
+-- hexo-server@2.0.0
+-- hexo-tag-aplayer@3.0.4
+-- hexo-theme-butterfly@3.8.1
+-- hexo-theme-landscape@0.0.3
+-- hexo-wordcount@6.0.1
+-- nib@1.1.2
+-- object-assign@4.1.1
`-- workbox-build@6.1.5

npm ERR! missing: stylus@0.54.5, required by nib@1.1.2
```

**Your package.json `package.json`**

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "5.4.0"
  },
  "dependencies": {
    "-": "0.0.1",
    "aplayer": "^1.10.1",
    "gulp-html-minifier-terser": "^6.0.1",
    "hexo": "^5.4.0",
    "hexo-abbrlink": "^2.2.1",
    "hexo-autonofollow": "^1.0.1",
    "hexo-blog-encrypt": "^3.1.6",
    "hexo-browsersync": "^0.3.0",
    "hexo-butterfly-douban": "^1.2.4",
    "hexo-butterfly-swiper": "^1.0.3",
    "hexo-deploy-tencentcloud-cdn": "0.0.3",
    "hexo-deployer-git": "^3.0.0",
    "hexo-filter-gitcalendar": "^1.0.6",
    "hexo-filter-nofollow": "^2.0.2",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^3.0.0",
    "hexo-generator-index": "^2.0.0",
    "hexo-generator-random": "^1.0.2",
    "hexo-generator-search": "^2.4.3",
    "hexo-generator-sitemap": "^2.1.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-jade": "^0.5.0",
    "hexo-renderer-marked": "^4.0.0",
    "hexo-renderer-pug": "^2.0.0",
    "hexo-renderer-stylus": "^2.0.1",
    "hexo-server": "^2.0.0",
    "hexo-tag-aplayer": "^3.0.4",
    "hexo-theme-butterfly": "^3.8.1",
    "hexo-theme-landscape": "^0.0.3",
    "hexo-wordcount": "^6.0.1",
    "nib": "^1.1.2",
    "object-assign": "^4.1.1"
  },
  "devDependencies": {
    "@babel/core": "^7.14.6",
    "@babel/preset-env": "^7.14.7",
    "@babel/preset-react": "^7.14.5",
    "gulp": "^4.0.2",
    "gulp-babel": "^8.0.0",
    "gulp-clean-css": "^4.3.0",
    "gulp-htmlclean": "^2.7.22",
    "gulp-imagemin": "^7.1.0",
    "gulp-terser": "^2.0.1",
    "gulp-uglify": "^3.0.2",
    "workbox-build": "^6.1.5"
  }
}
```

## Others

```
INFO  Start processing
INFO  111 movies have been loaded in 12923 ms
INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
(node:31568) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:650:11)
    at Object.get (internal/modules/cjs/loader.js:664:5)
    at Boolean.Node [as constructor] (E:\work\Git\butterfly\node_modules\nib\node_modules\stylus\lib\nodes\node.js:44:23)   
    at new Boolean (E:\work\Git\butterfly\node_modules\nib\node_modules\stylus\lib\nodes\boolean.js:23:8)
    at Object.<anonymous> (E:\work\Git\butterfly\node_modules\nib\node_modules\stylus\lib\nodes\index.js:57:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (E:\work\Git\butterfly\node_modules\nib\node_modules\stylus\lib\lexer.js:13:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (E:\work\Git\butterfly\node_modules\nib\node_modules\stylus\lib\parser.js:11:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
(node:31568) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:650:11)
    at Object.get (internal/modules/cjs/loader.js:664:5)
    at Boolean.Node [as constructor] (E:\work\Git\butterfly\node_modules\nib\node_modules\stylus\lib\nodes\node.js:45:23)   
    at new Boolean (E:\work\Git\butterfly\node_modules\nib\node_modules\stylus\lib\nodes\boolean.js:23:8)
    at Object.<anonymous> (E:\work\Git\butterfly\node_modules\nib\node_modules\stylus\lib\nodes\index.js:57:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (E:\work\Git\butterfly\node_modules\nib\node_modules\stylus\lib\lexer.js:13:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (E:\work\Git\butterfly\node_modules\nib\node_modules\stylus\lib\parser.js:11:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
(node:31568) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:650:11)
    at Object.get (internal/modules/cjs/loader.js:664:5)
    at Boolean.Node [as constructor] (E:\work\Git\butterfly\node_modules\nib\node_modules\stylus\lib\nodes\node.js:46:25)   
    at new Boolean (E:\work\Git\butterfly\node_modules\nib\node_modules\stylus\lib\nodes\boolean.js:23:8)
    at Object.<anonymous> (E:\work\Git\butterfly\node_modules\nib\node_modules\stylus\lib\nodes\index.js:57:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (E:\work\Git\butterfly\node_modules\nib\node_modules\stylus\lib\lexer.js:13:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (E:\work\Git\butterfly\node_modules\nib\node_modules\stylus\lib\parser.js:11:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
(node:31568) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:650:11)
    at Object.get (internal/modules/cjs/loader.js:664:5)
    at Boolean.Node [as constructor] (E:\work\Git\butterfly\node_modules\nib\node_modules\stylus\lib\nodes\node.js:44:23)   
    at new Boolean (E:\work\Git\butterfly\node_modules\nib\node_modules\stylus\lib\nodes\boolean.js:23:8)
    at Object.<anonymous> (E:\work\Git\butterfly\node_modules\nib\node_modules\stylus\lib\nodes\index.js:58:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (E:\work\Git\butterfly\node_modules\nib\node_modules\stylus\lib\lexer.js:13:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (E:\work\Git\butterfly\node_modules\nib\node_modules\stylus\lib\parser.js:11:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
(node:31568) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:650:11)
    at Object.get (internal/modules/cjs/loader.js:664:5)
    at Boolean.Node [as constructor] (E:\work\Git\butterfly\node_modules\nib\node_modules\stylus\lib\nodes\node.js:45:23)   
    at new Boolean (E:\work\Git\butterfly\node_modules\nib\node_modules\stylus\lib\nodes\boolean.js:23:8)
    at Object.<anonymous> (E:\work\Git\butterfly\node_modules\nib\node_modules\stylus\lib\nodes\index.js:58:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (E:\work\Git\butterfly\node_modules\nib\node_modules\stylus\lib\lexer.js:13:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (E:\work\Git\butterfly\node_modules\nib\node_modules\stylus\lib\parser.js:11:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
(node:31568) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:650:11)
    at Object.get (internal/modules/cjs/loader.js:664:5)
    at Boolean.Node [as constructor] (E:\work\Git\butterfly\node_modules\nib\node_modules\stylus\lib\nodes\node.js:46:25)   
    at new Boolean (E:\work\Git\butterfly\node_modules\nib\node_modules\stylus\lib\nodes\boolean.js:23:8)
    at Object.<anonymous> (E:\work\Git\butterfly\node_modules\nib\node_modules\stylus\lib\nodes\index.js:58:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (E:\work\Git\butterfly\node_modules\nib\node_modules\stylus\lib\lexer.js:13:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (E:\work\Git\butterfly\node_modules\nib\node_modules\stylus\lib\parser.js:11:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
```

**Comment by kuole-o** [comment]
Sorry this is a duplicate question
