### ISSUE TITLE
err: TypeError: Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by shenqizhi** [hexojs/hexo#4751]
Hi all, 

When I run the command `hexo new <title>`，it will show the below error:

```
FATAL {
  err: TypeError: Cannot read property 'startsWith' of undefined
      at D:\blog_matery\node_modules\hexo\lib\hexo\post.js:143:42
      at tryCatcher (D:\blog_matery\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (D:\blog_matery\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (D:\blog_matery\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (D:\blog_matery\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (D:\blog_matery\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (D:\blog_matery\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (D:\blog_matery\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (D:\blog_matery\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (D:\blog_matery\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (node:internal/timers:464:21)
} Something's wrong. Maybe you can find the solution here: %s https://hexo.io/docs/troubleshooting.html
```

My env:

```
$ node -v
v16.6.1

$ npm -v
7.20.3

$ hexo v
INFO  Validating config
hexo: 5.4.0
hexo-cli: 4.3.0
os: win32 10.0.19042
node: 16.6.1
v8: 9.2.230.21-node.19
uv: 1.41.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.17.1
modules: 93
nghttp2: 1.42.0
napi: 8
llhttp: 6.0.2
openssl: 1.1.1k+quic
cldr: 39.0
icu: 69.1
tz: 2021a
unicode: 13.0
ngtcp2: 0.1.0-DEV
nghttp3: 0.1.0-DEV
```

I have look for answers from issue page & google, but failed. Could someone help me to fix this issue?

**Comment by knight0707** [comment]
I encounter the same error today, not fixed yet!

**Comment by stevenjoezhang** [comment]
See https://github.com/hexojs/hexo/blob/b65a5623b7f7b539b48bf6ebdab73885841a120f/lib/hexo/post.js#L143

**Comment by shenqizhi** [comment]
@stevenjoezhang 

Share the `post.js` and the three files in scaffolds for you. Feel free to contact me if you need any help.


[post.js.txt](https://github.com/hexojs/hexo/files/7322412/post.js.txt)

[draft.md](https://github.com/hexojs/hexo/files/7322445/draft.md)
[page.md](https://github.com/hexojs/hexo/files/7322446/page.md)
[post.md](https://github.com/hexojs/hexo/files/7322447/post.md)
