### ISSUE TITLE
Getting Unhandled rejection WarehouseError: ID `source/image/...` has been used error.

### ISSUE THREAD

**Issue by siraisisatoru** [hexojs/hexo#4762]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Expected behavior

Hello. recently I try to build my customized image minimization script for more flexible functions. Then it comes with the solution using `imagemin` lib and the solution mentioned in [here](https://github.com/alexlibby/hexo-tag-webp/issues/1#issue-937135102). The script was running fine in my project. But one day I plan to add a watermark feature and seems `imagemin` doesn't have a plugin for that. Therefore I choose to change the image processing lib to `sharp`. 

The logic for both of them is the same as following:
1. insert a tag in `.md` file -> 2. script take that tag and convert image to smaller ones and store in the separate folder -> 3. return the html string for display.

For step 2, I do the following to avoid duplicate generation:
- check the file exists or not
  - if exists skip generate
- check the destination folder exists or not
  - if not, generate the folder using `fs.mkdirSync(moveToP, { recursive: true });` then continue
- pass the original image path to the lib and do the processing
- after processing, the image will be generated to the destination folder.

<details>
  <summary>The complete code has been attached as follows:</summary>
  
```js
"use strict";

const sharp = require("sharp");
const path = require("path");
const fs = require("hexo-fs");
const md5 = require("js-md5");

var sizeOf = require("image-size");

var webpSettings = {
  quality: 70
};

function getimagFunc(args) {
  const originPic = args[0];
  const dimensions = sizeOf("./source/" + originPic);

  // console.log(dimensions);
  webpSettings.width = dimensions.orientation == 1 ? dimensions.width : dimensions.height;
  webpSettings.height = dimensions.orientation == 1 ? dimensions.height : dimensions.width;

  const inputImageAspectRatio = webpSettings.width / webpSettings.height;

  var imagFunc = {
    method: 6,
    quality: webpSettings.quality
  };

  if (args[1]) {
    if (args[1].indexOf(":") < 0) {
      // first element is not ratio => self and the following arg is weight and height
      imagFunc.resize = { width: Number(args[1]), height: Number(args[2]) };
    } else {
      var picRatio = args[1].split(":").map(Number);
      picRatio = picRatio[0] / picRatio[1];
      let ratioW = webpSettings.width;
      let ratioH = webpSettings.height;
      if (inputImageAspectRatio > picRatio) {
        ratioW = webpSettings.height * picRatio;
      } else if (inputImageAspectRatio < picRatio) {
        ratioH = webpSettings.width / picRatio;
      }
      const shiftArr = [(webpSettings.width - ratioW) * 0.5, (webpSettings.height - ratioH) * 0.5];

      imagFunc.crop = {
        x: parseInt(shiftArr[0]),
        y: parseInt(shiftArr[1]),
        width: ratioW,
        height: ratioH
      };
    }
  }
  if (args[2] && args[3]) {
    imagFunc.resize = { width: Number(args[2]), height: Number(args[3]) };
  }
  return imagFunc;
}

function picProcess(args) {
  const fancybox = args[0].toUpperCase() === "FANCYBOX";
  if (fancybox) {
    args.shift();
  }
  const originPic = path.parse(args[0]);
  var argsPar = [...args];
  argsPar.shift();
  argsPar = argsPar.join(" ");
  const parMD5 = md5.hex(argsPar).slice(0, 9);
  const oFilename = "./source" + args[0];
  var moveToP = "./source/image" + originPic.dir + "/";
  moveToP = moveToP.replace("/post_image", "");
  const finalP = moveToP + originPic.name + "_" + parMD5 + ".webp";
  const finalPjpg = moveToP + originPic.name + "_" + parMD5 + ".jpg";
  console.log(finalP)

  if (!fs.existsSync(finalP) || !fs.existsSync(finalPjpg)) {
    if (!fs.existsSync(moveToP)) {
      fs.mkdirsSync(moveToP, { recursive: true });
    }

    if (fs.existsSync(moveToP)) {
      const imagFunc = getimagFunc(args);
      var sharpData = sharp(oFilename);
      sharpData.rotate();

      if (imagFunc.crop) {
         sharpData.extract({ left: imagFunc.crop.x, top: imagFunc.crop.y, width: imagFunc.crop.width, height: imagFunc.crop.height });
      }
      if (imagFunc.resize) {
         sharpData.resize({ width: imagFunc.resize.width, height: imagFunc.resize.height });
      }

      sharpData
        .webp({ quality: 1 })
        .toFile(finalP)
        .then(info => {console.log(info)})
        .catch(err => { });
      sharpData
        .jpeg({ quality: 25, mozjpeg: true })
        .toFile(finalPjpg)
        .then(info => {console.log(info)})
        .catch(err => { });
    } else {
      // the folder does not exists at all
      console.log("the folder never exists")
    }
  }
  if (!fancybox) {
    return `<picture><source type="image/webp" srcset=${finalP.replace("./source", "")}>
    <img src=${finalPjpg.replace("./source", "")} class="nofancybox"> </picture>`;
  } else {
    return `<img src=${finalPjpg.replace("./source", "")} class="fancybox">`;
  }
}

hexo.extend.tag.register("webp", function (args) {
  return picProcess(args);
});

hexo.extend.helper.register("webp_helper", function (args) {
  args = args.split(" ");
  return picProcess(args);
});

```
</details>

Assuming I have a folder structure as follows:

    .
    ├── ...
    ├── source
    │   ├── post_image
    │   │        └──a
    │   │            └── IMG_0001.JPG
    │   └── image
    │       └──a
    │           ├── IMG_0001_abcdefghi.jpg
    │           └── IMG_0001_abcdefghi.webp
    └── ...

The `image` folder gonna be generated by the script and `post_image` is the original folder containing original image files. 

## Actual behavior

When there DOES NOT need to generate new folders by `fs.mkdirSync(moveToP, { recursive: true });`, then no error occurs at all.
(for example, `/image/a/` already exsits and does not need to generate the folder programmatically)
When there NEED to generate new folders then I got the following error:
(for example, `/image/` does not exist and need to generate the folder programmatically)

<details>
  <summary>ERROR</summary>
  
Unhandled rejection WarehouseError: ID `source/image/a/IMG_0639_db17f7e1b.jpg` has been used
at new WarehouseError (/Users/abc/dev/testing_blog/node_modules/warehouse/lib/error.js:14:11)
at _Model._insertOne (/Users/abc/dev/testing_blog/node_modules/warehouse/lib/model.js:153:29)
at /Users/abc/dev/testing_blog/node_modules/warehouse/lib/model.js:179:63
at tryCatcher (/Users/abc/dev/testing_blog/node_modules/bluebird/js/release/util.js:16:23)
at /Users/abc/dev/testing_blog/node_modules/bluebird/js/release/using.js:185:26
at tryCatcher (/Users/abc/dev/testing_blog/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/Users/abc/dev/testing_blog/node_modules/bluebird/js/release/promise.js:547:31)
at Promise._settlePromise (/Users/abc/dev/testing_blog/node_modules/bluebird/js/release/promise.js:604:18)
at Promise._settlePromise0 (/Users/abc/dev/testing_blog/node_modules/bluebird/js/release/promise.js:649:10)
at Promise._settlePromises (/Users/abc/dev/testing_blog/node_modules/bluebird/js/release/promise.js:729:18)
at Promise._fulfill (/Users/abc/dev/testing_blog/node_modules/bluebird/js/release/promise.js:673:18)
at PromiseArray._resolve (/Users/abc/dev/testing_blog/node_modules/bluebird/js/release/promise_array.js:127:19)
at PromiseArray._promiseFulfilled (/Users/abc/dev/testing_blog/node_modules/bluebird/js/release/promise_array.js:145:14)
at Promise._settlePromise (/Users/abc/dev/testing_blog/node_modules/bluebird/js/release/promise.js:609:26)
at Promise._settlePromise0 (/Users/abc/dev/testing_blog/node_modules/bluebird/js/release/promise.js:649:10)
at Promise._settlePromises (/Users/abc/dev/testing_blog/node_modules/bluebird/js/release/promise.js:729:18)
at _drainQueueStep (/Users/abc/dev/testing_blog/node_modules/bluebird/js/release/async.js:93:12)
at _drainQueue (/Users/abc/dev/testing_blog/node_modules/bluebird/js/release/async.js:86:9)
at Async._drainQueues (/Users/abc/dev/testing_blog/node_modules/bluebird/js/release/async.js:102:5)
at Immediate.Async.drainQueues [as _onImmediate] (/Users/abc/dev/testing_blog/node_modules/bluebird/js/release/async.js:15:14)
at processImmediate (internal/timers.js:462:21)
</details>

Another observation is the error seems only occur once for each new folder (I mean one of the files in the new folder will trigger this error, not all new image files.) newly generated programmatically.

## How to reproduce?

mentioned above.

## Is the problem still there under "Safe mode"?

The problem seems related to how HEXO generated the database using Warehouse lib. The point of this issue is the customize image processing lib encounter error.

## Environment & Settings

**Node.js & npm version(`node -v && npm -v`)**

```
node -v
v14.17.0
npm -v
7.16.0
```

**Your site `_config.yml`** (Optional) and Your theme `_config.yml`** (Optional)

All settings are the default values which same as by `hexo init` command

**Hexo and Plugin version(`npm ls --depth 0`)**

```
hexo-site@0.0.0 /Users/ufobenson/dev/testing_blog
├── hexo-generator-archive@1.0.0
├── hexo-generator-category@1.0.0
├── hexo-generator-index@2.0.0
├── hexo-generator-tag@1.0.0
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-marked@4.1.0
├── hexo-renderer-stylus@2.0.1
├── hexo-server@2.0.0
├── hexo-theme-landscape@0.0.3
├── hexo@5.4.0
├── image-size@1.0.0
├── js-md5@0.7.3
└── sharp@0.29.0
```

**Your package.json `package.json`**

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "5.4.0"
  },
  "dependencies": {
    "hexo": "^5.0.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^2.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^4.0.0",
    "hexo-renderer-stylus": "^2.0.0",
    "hexo-server": "^2.0.0",
    "hexo-theme-landscape": "^0.0.3",
    "image-size": "^1.0.0",
    "js-md5": "^0.7.3",
    "sharp": "^0.29.0"
  }
}

```

## Others

I am facing this error for a half month and after tons of googling still stuck. Please someone can give some hints that may trigger the error. Am I make some mistakes in terms of file generation? But how does the `imagemin` one works fine?

**Comment by siraisisatoru** [comment]
After posting this issue, I continue to try someone's lib related to `Sharp` and finally I found one for [adding watermark to the image](https://github.com/SpiritLingPub/hexo-images-watermark). Then I do quite a lot of modifications base on his/her code and works like a charm.
Although I try to modify my original code, the error still exists. By comparing with the existing lib, it seems the answer is probably related to the `await` and `async` functions. Since I am new to node.js and HEXO, I encounter this issue without knowing how does `await` and `async` functions work.
Since my own modified lib is functioning fine, I will not need further help with this issue. But it will be helpful if someone can explain how this error can be solved.
HEXO admins can close this issue if needed.
