### ISSUE TITLE
Compile blank pages during workflow deployment

### ISSUE THREAD

**Issue by yltx** [hexojs/hexo#5235]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

I tried to use github action to complete automatic deployment.

Here is my workflow file:

```yml
name: Hexo Auto Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  GIT_USER: yltx
  GIT_EMAIL: 2326439151@qq.com
  GIT_DEPLOY_REPO: yltx/yltx.github.io
  GIT_DEPLOY_BRANCH: master
  GIT_SOURCE_REPO: git@github.com:yltx/yltx.github.io.git
  
jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    strategy:
      matrix:
        os: [ubuntu-22.10]
        node_version: [18.x]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Checkout deploy repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.GIT_DEPLOY_REPO }}
          ref: ${{ env.GIT_DEPLOY_BRANCH }}
          path: .deploy_git
      
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
        
      - name: Configuration environment
        env:
          HEXO_DEPLOY_PRI: ${{ secrets.HEXO_DEPLOY_PRI }}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL
          
      - name: Install Dependencies
        run: |
          npm install hexo-cli -g
          npm install
          git clone https://github.com/theme-next/theme-next-bookmark.git source/lib/bookmark
          npm install theme-next/hexo-next-tag
      
      - name: Deploy Hexo
        run: |
          hexo cl
          hexo g -d
```

This worked good before I update my blog to hexo 7.But now it generated blank pages:

```
INFO  Validating config
INFO  Validating config
INFO  Start processing
INFO  Files loaded in 1.26 s
WARN  No layout: Games/index.html
WARN  No layout: Visit-map/index.html
WARN  No layout: categories/index.html
WARN  No layout: about/index.html
WARN  No layout: schedule/index.html
WARN  No layout: sitemap/index.html
WARN  No layout: tags/index.html
WARN  No layout: 2022/01/21/TypeScript从入门到入土/index.html
WARN  No layout: 2021/01/28/CSP-S-NOIP-2020游记：如何优雅地爆零/index.html
WARN  No layout: 2019/09/01/浅谈树链剖分/index.html
WARN  No layout: 2019/08/23/题解-CF[12](https://github.com/yltx/blog/actions/runs/5303424214/jobs/9599035876#step:7:13)07F-【Remainder-Problem】/index.html
WARN  No layout: 2019/08/23/题解-CF1207C-【Gas-Pipeline】/index.html
WARN  No layout: 2019/08/23/题解-CF1207B-【Square-Filling】/index.html
WARN  No layout: 2019/08/23/题解-CF1207A-【There-Are-Two-Types-Of-Burgers】/index.html
WARN  No layout: 2019/08/21/题解-CF1204C-【Anna-Svyatoslav-and-Maps】/index.html
WARN  No layout: 2019/08/21/题解-CF1204B-【Mislove-Has-Lost-an-Array】/index.html
WARN  No layout: 2019/08/21/题解-CF1204A-【BowWow-and-the-Timetable】/index.html
WARN  No layout: 2019/08/19/题解-CF1206A-【Choose-Two-Numbers】/index.html
WARN  No layout: 2019/08/19/题解-CF1205A-1206C-【Almost-Equal】/index.html
WARN  No layout: 2019/08/19/题解-CF1206B-【Make-Product-Equal-One】/index.html
WARN  No layout: 2019/08/14/题解-SP11814-【EKO-Eko】/index.html
WARN  No layout: 2019/08/14/题解-CF1200B-【Block-Adventure】/index.html
WARN  No layout: 2019/08/14/题解-CF580E-【Kefa-and-Watch】/index.html
WARN  No layout: 2019/08/14/题解-CF312A-【Whose-sentence-is-it-】/index.html
WARN  No layout: 2019/08/14/题解-CF317A-【Perfect-Pair】/index.html
WARN  No layout: 2019/08/14/题解-P5497-【-LnOI2019SP-龟速单项式变换-SMT-】/index.html
WARN  No layout: 2019/08/06/题解-P1801-【黑匣子-NOI导刊2010提高（06）】/index.html
WARN  No layout: 2019/08/03/睡前读物：我为何而OI/index.html
WARN  No layout: 2019/07/29/题解-P[13](https://github.com/yltx/blog/actions/runs/5303424214/jobs/9599035876#step:7:14)35-【-NOI2013-小Q的修炼】/index.html
WARN  No layout: 2019/07/16/某谷讲师语录/index.html
WARN  No layout: 2019/04/22/题解-P5315-【头像上传】/index.html
WARN  No layout: 2019/04/22/题解-CF493A-【Vasya-and-Football】/index.html
WARN  No layout: 2019/04/22/题解-CF201A-【Clear-Symmetry】/index.html
WARN  No layout: 2019/04/22/题解-CF168A-【Wizards-and-Demonstration】/index.html
WARN  No layout: 2019/04/22/题解-CF224A-【Parallelepiped】/index.html
WARN  No layout: 2019/04/22/题解-CF887B-【Cubes-for-Masha】/index.html
WARN  No layout: 2019/04/22/题解-CF1043C-【Smallest-Word】/index.html
WARN  No layout: 2019/03/17/题解-CF341E-【Candies-Game】/index.html
WARN  No layout: 2019/03/17/真正的IO优化/index.html
WARN  No layout: 2019/03/17/模板/index.html
WARN  No layout: 2019/03/03/题解-P3377-【【模板】左偏树（可并堆）】/index.html
WARN  No layout: 2019/02/24/题解-P1638-【逛画展】/index.html
WARN  No layout: 2019/02/10/题解-CF660C-【Hard-Process】/index.html
WARN  No layout: 2019/02/10/题解-UVA11366-【Circle-of-Debt】/index.html
WARN  No layout: 2019/01/22/那些年离我们而去的Oier们/index.html
WARN  No layout: 2019/01/18/博客搭建食用指北/index.html
WARN  No layout: 2019/01/17/题解-P[14](https://github.com/yltx/blog/actions/runs/5303424214/jobs/9599035876#step:7:15)82-【Cantor表（升级版）】/index.html
WARN  No layout: 2019/01/17/题解-P1138-【第k小整数】/index.html
WARN  No layout: 2019/01/17/题解-P1897-【电梯里的爱情】/index.html
WARN  No layout: 2019/01/17/题解-P1304-【哥德巴赫猜想】/index.html
WARN  No layout: 2019/01/17/题解-P1190-【接水问题】/index.html
WARN  No layout: 2019/01/17/题解-P2524-【Uim的情人节礼物·其之弐】/index.html
WARN  No layout: 2019/01/17/题解-P1165-【日志分析】/index.html
WARN  No layout: 2019/01/17/题解-P3397-【地毯】/index.html
WARN  No layout: 2019/01/17/题解-P1403-【[AHOI2005]约数研究】/index.html
WARN  No layout: 2019/01/17/题解-P1610-【鸿山洞的灯】/index.html
WARN  No layout: 2019/01/17/题解-P1734-【最大约数和】/index.html
WARN  No layout: 2019/01/17/题解-P2660-【zzc 种田】/index.html
WARN  No layout: 2019/01/17/题解-P1917-【三子棋Ⅱ】/index.html
WARN  No layout: 2019/01/17/题解-P2640-【神秘磁石】/index.html
WARN  No layout: 2019/01/17/题解-P1[15](https://github.com/yltx/blog/actions/runs/5303424214/jobs/9599035876#step:7:16)7-【组合的输出】/index.html
WARN  No layout: 2019/01/17/题解-P1115-【最大子段和】/index.html
WARN  No layout: 2019/01/17/题解-P1868-【饥饿的奶牛】/index.html
WARN  No layout: 2019/01/17/题解-P1130-【红牌】/index.html
WARN  No layout: 2019/01/17/题解-P1571-【眼红的Medusa】/index.html
WARN  No layout: 2019/01/17/题解-P2374-【搬运工】/index.html
WARN  No layout: 2019/01/17/题解-P2005-【A÷B Problem Ⅱ】/index.html
WARN  No layout: 2019/01/17/题解-P1096-【Hanoi双塔问题】/index.html
WARN  No layout: 2019/01/17/题解-SP3273-【ORDERSET - Order statistic set】/index.html
WARN  No layout: 2019/01/17/题解-CF908A-【New Year and Counting Cards】/index.html
WARN  No layout: 2019/01/17/题解-CF870A-【Search for Pretty Integers】/index.html
WARN  No layout: 2019/01/17/题解-CF514A-【Chewbacca and Number】/index.html
WARN  No layout: 2019/01/17/题解-CF519A-【A and B and Chess】/index.html
WARN  No layout: 2019/01/17/题解-CF932A-【Palindromic Supersequence】/index.html
WARN  No layout: 2019/01/17/题解-P1244-【青蛙过河】/index.html
WARN  No layout: 2019/01/17/题解-P4327-【[COCI2006-2007 Contest1] Okviri】/index.html
WARN  No layout: 2019/01/17/题解-CF518A-【Vitaly and String】/index.html
WARN  No layout: 2019/01/17/题解-CF839A-【Arya and Bran】/index.html
WARN  No layout: 2019/01/[16](https://github.com/yltx/blog/actions/runs/5303424214/jobs/9599035876#step:7:17)/题解-CF935A-【Fafa and his Company】/index.html
WARN  No layout: 2019/01/16/题解-CF962A-【Equator】/index.html
WARN  No layout: 2019/01/16/题解-CF659D-【Bicycle Race】/index.html
WARN  No layout: 2019/01/16/题解-CF119A-【Epic Game】/index.html
WARN  No layout: 2019/01/16/题解-CF911A-【Nearest Minimums】/index.html
WARN  No layout: 2019/01/16/题解-CF816A-【Karen and Morning】/index.html
WARN  No layout: 2019/01/16/题解-CF546A-【Soldier and Bananas】/index.html
WARN  No layout: 2019/01/16/题解-P4470-【[BJWC2018]售票】/index.html
WARN  No layout: 2019/01/16/题解-P1451-【求细胞数量】/index.html
WARN  No layout: 2019/01/16/题解-P3692-【夏幻的考试】/index.html
WARN  No layout: 2019/01/16/题解-CF36A-【Extra-terrestrial Intelligence】/index.html
WARN  No layout: 2019/01/16/题解-CF228A-【Is your horseshoe on the other hoof？】/index.html
WARN  No layout: 2019/01/16/题解-CF977A-【Wrong Subtraction】/index.html
WARN  No layout: 2019/01/12/题解-CF723A-【The New Year Meeting Friends】/index.html
WARN  No layout: 2019/01/12/题解-P[17](https://github.com/yltx/blog/actions/runs/5303424214/jobs/9599035876#step:7:18)40-【Diamond A&B(1)】/index.html
WARN  No layout: 2019/01/12/题解-P2152-【[SDOI2009]SuperGCD】/index.html
WARN  No layout: 2019/01/12/题解-P4711-【「化学」相对分子质量】/index.html
WARN  No layout: 2019/01/12/题解-P2682-【土豆田】/index.html
WARN  No layout: 2019/01/12/题解-P1721-【[NOI2016]国王饮水记】/index.html
WARN  No layout: 2019/01/12/题解-P1983-【车站分级】/index.html
WARN  No layout: 2019/01/12/题解-P4212-【外太空旅行】/index.html
WARN  No layout: 2019/01/12/题解-P4907-【A换B problem】/index.html
WARN  No layout: 2019/01/12/题解-P5003-【跳舞的线-乱拐弯】/index.html
WARN  No layout: 2019/01/12/题解-P3386-【【模板】二分图匹配】/index.html
WARN  No layout: 2019/01/12/题解-P5019-【铺设道路】/index.html
WARN  No layout: 2019/01/12/solution-P4432
WARN  No layout: 2019/01/12/题解-P19[18](https://github.com/yltx/blog/actions/runs/5303424214/jobs/9599035876#step:7:19)-【保龄球】/index.html
WARN  No layout: 20[19](https://github.com/yltx/blog/actions/runs/5303424214/jobs/9599035876#step:7:20)/01/12/题解-CF479A-【Expression】/index.html
WARN  No layout: [20](https://github.com/yltx/blog/actions/runs/5303424214/jobs/9599035876#step:7:21)19/01/12/省赛之旅/index.html
WARN  No layout: 2019/01/12/NOIP2018颓废之路/index.html
WARN  No layout: archives/index.html
WARN  No layout: archives/page/2/index.html
WARN  No layout: archives/page/3/index.html
WARN  No layout: archives/page/4/index.html
WARN  No layout: archives/page/5/index.html
WARN  No layout: archives/page/6/index.html
WARN  No layout: archives/page/7/index.html
WARN  No layout: archives/page/8/index.html
WARN  No layout: archives/page/9/index.html
WARN  No layout: archives/page/10/index.html
WARN  No layout: archives/page/11/index.html
WARN  No layout: archives/2019/index.html
WARN  No layout: archives/2019/page/2/index.html
WARN  No layout: archives/2019/page/3/index.html
WARN  No layout: archives/2019/page/4/index.html
WARN  No layout: archives/2019/page/5/index.html
WARN  No layout: archives/2019/page/6/index.html
WARN  No layout: archives/2019/page/7/index.html
WARN  No layout: archives/2019/page/8/index.html
WARN  No layout: archives/2019/page/9/index.html
WARN  No layout: archives/2019/page/10/index.html
WARN  No layout: archives/2019/01/index.html
WARN  No layout: archives/2019/01/page/2/index.html
WARN  No layout: archives/2019/01/page/3/index.html
WARN  No layout: archives/2019/01/page/4/index.html
WARN  No layout: archives/2019/01/page/5/index.html
WARN  No layout: archives/2019/01/page/6/index.html
WARN  No layout: archives/2019/01/page/7/index.html
WARN  No layout: archives/2019/02/index.html
WARN  No layout: archives/2019/03/index.html
WARN  No layout: archives/2019/04/index.html
WARN  No layout: archives/2019/07/index.html
WARN  No layout: archives/2019/08/index.html
WARN  No layout: archives/2019/08/page/2/index.html
WARN  No layout: archives/2019/09/index.html
WARN  No layout: archives/20[21](https://github.com/yltx/blog/actions/runs/5303424214/jobs/9599035876#step:7:22)/index.html
WARN  No layout: archives/2021/01/index.html
WARN  No layout: archives/20[22](https://github.com/yltx/blog/actions/runs/5303424214/jobs/9599035876#step:7:23)/index.html
WARN  No layout: archives/2022/01/index.html
WARN  No layout: index.html
WARN  No layout: page/2/index.html
WARN  No layout: page/3/index.html
WARN  No layout: page/4/index.html
WARN  No layout: page/5/index.html
WARN  No layout: page/6/index.html
WARN  No layout: page/7/index.html
WARN  No layout: page/8/index.html
WARN  No layout: page/9/index.html
WARN  No layout: page/10/index.html
WARN  No layout: page/11/index.html
WARN  No layout: tags/游记/index.html
WARN  No layout: tags/TypeScript/index.html
WARN  No layout: tags/技术/index.html
WARN  No layout: tags/洛谷/index.html
WARN  No layout: tags/洛谷/page/2/index.html
WARN  No layout: tags/洛谷/page/3/index.html
WARN  No layout: tags/洛谷/page/4/index.html
WARN  No layout: tags/洛谷/page/5/index.html
WARN  No layout: tags/其他/index.html
WARN  No layout: tags/模板/index.html
WARN  No layout: tags/算法/index.html
WARN  No layout: tags/题解/index.html
WARN  No layout: tags/题解/page/2/index.html
WARN  No layout: tags/题解/page/3/index.html
WARN  No layout: tags/题解/page/4/index.html
WARN  No layout: tags/题解/page/5/index.html
WARN  No layout: tags/题解/page/6/index.html
WARN  No layout: tags/题解/page/7/index.html
WARN  No layout: tags/题解/page/8/index.html
WARN  No layout: tags/题解/page/9/index.html
WARN  No layout: tags/CF/index.html
WARN  No layout: tags/CF/page/2/index.html
WARN  No layout: tags/CF/page/3/index.html
WARN  No layout: tags/CF/page/4/index.html
WARN  No layout: tags/SPOJ/index.html
WARN  No layout: tags/UVA/index.html
```

And there is a worning:

```
[Build on node 18.x and ubuntu-22.10](https://github.com/yltx/blog/actions/runs/5303424214/jobs/9599035876#step:14:11)
The process '/usr/bin/git' failed with exit code 128
```

What's up? I think it's not a problem with my blog,because it can work well on my own computer.

**Comment by stevenjoezhang** [comment]
Did you install the theme on workflow environment?

**Comment by yltx** [comment]
> Did you install the theme on workflow environment?

I added `git clone https://github.com/theme-next/hexo-theme-next themes/next` to the yml and now it gets this error:

```
INFO  Validating config
INFO  Validating config
INFO  Start processing
INFO  Files loaded in 1.38 s
ERROR 
Template render error: (/home/runner/work/blog/blog/themes/next/layout/page.swig)
  Template render error: (/home/runner/work/blog/blog/themes/next/layout/page.swig) [Line 36, Column 23]
  Template render error: (/home/runner/work/blog/blog/themes/next/layout/page.swig) [Line 54, Column 17]
  Template render error: (/home/runner/work/blog/blog/themes/next/layout/page.swig)
  Template render error: (/home/runner/work/blog/blog/themes/next/layout/_partials/head/head-unique.swig) [Line 10, Column 23]
  Template render error: (/home/runner/work/blog/blog/themes/next/layout/page.swig) [Line 3, Column 3]
  Template render error: (/home/runner/work/blog/blog/themes/next/layout/page.swig)
  Template render error: (/home/runner/work/blog/blog/themes/next/layout/_partials/header/index.swig) [Line 6, Column 15]
  Template render error: (/home/runner/work/blog/blog/themes/next/layout/page.swig)
  Template render error: (/home/runner/work/blog/blog/themes/next/layout/_partials/header/sub-menu.swig) [Line 2, Column 29]
  Template render error: (/home/runner/work/blog/blog/themes/next/layout/page.swig)
  Template render error: (/home/runner/work/blog/blog/themes/next/layout/_partials/header/sub-menu.swig)
  Template render error: (/home/runner/work/blog/blog/themes/next/layout/page.swig) [Line 17, Column 3]
  Template render error: (/home/runner/work/blog/blog/themes/next/layout/page.swig) [Line 19, Column 3]
  Template render error: (/home/runner/work/blog/blog/themes/next/layout/page.swig)
  Template render error: (/home/runner/work/blog/blog/themes/next/layout/_partials/page/page-header.swig) [Line 4, Column 15]
  Template render error: (/home/runner/work/blog/blog/themes/next/layout/page.swig)
  Template render error: (/home/runner/work/blog/blog/themes/next/layout/_partials/page/page-header.swig)
  Template render error: (/home/runner/work/blog/blog/themes/next/layout/_partials/page/breadcrumb.swig)
  Template render error: (/home/runner/work/blog/blog/themes/next/layout/page.swig)
  Template render error: (/home/runner/work/blog/blog/themes/next/layout/_partials/page/breadcrumb.swig)
  Template render error: (/home/runner/work/blog/blog/themes/next/layout/page.swig)
  Template render error: (/home/runner/work/blog/blog/themes/next/layout/_partials/comments.swig) [Line 3, Column 14]
  Template render error: (/home/runner/work/blog/blog/themes/next/layout/page.swig)
  Template render error: (/home/runner/work/blog/blog/themes/next/layout/_partials/languages.swig)
  Template render error: (/home/runner/work/blog/blog/themes/next/layout/page.swig)
  Template render error: (/home/runner/work/blog/blog/themes/next/layout/_third-party/math/index.swig) [Line 4, Column 16]
  Template render error: (/home/runner/work/blog/blog/themes/next/layout/page.swig)
  Template render error: (/home/runner/work/blog/blog/themes/next/layout/_third-party/quicklink.swig) [Line 1, Column 65]
  Template render error: (/home/runner/work/blog/blog/themes/next/layout/inject/bodyEnd/waline.swig) [Line 6, Column 15]
  Error: Unable to call `next_data`, which is undefined or falsey
    at Object._prettifyError (/home/runner/work/blog/blog/node_modules/nunjucks/src/lib.js:32:11)
    at /home/runner/work/blog/blog/node_modules/nunjucks/src/environment.js:464:19
    at Template.root [as rootRenderFunc] (eval at _compile (/home/runner/work/blog/blog/node_modules/nunjucks/src/environment.js:527:18), <anonymous>:45:3)
    at Template.render (/home/runner/work/blog/blog/node_modules/nunjucks/src/environment.js:454:10)
    at /home/runner/work/blog/blog/themes/next/scripts/renderer.js:32:29
    at _View._compiled (/home/runner/work/blog/blog/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/home/runner/work/blog/blog/node_modules/hexo/lib/theme/view.js:39:17)
    at /home/runner/work/blog/blog/node_modules/hexo/lib/hexo/index.js:64:21
    at tryCatcher (/home/runner/work/blog/blog/node_modules/bluebird/js/release/util.js:16:23)
    at /home/runner/work/blog/blog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/runner/work/blog/blog/node_modules/hexo/lib/hexo/router.js:47:5)
    at Readable.read (node:internal/streams/readable:496:[12](https://github.com/yltx/blog/actions/runs/5408874408/jobs/9828372344#step:7:13))
    at resume_ (node:internal/streams/readable:999:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:[21](https://github.com/yltx/blog/actions/runs/5408874408/jobs/9828372344#step:7:22))
```

**Comment by renbaoshuo** [comment]
I tried to use `hexo@7.0.0-rc1` in [renbaoshuo/hexo-for-oiers](https://github.com/renbaoshuo/hexo-for-oiers), which using GitHub Actions to build the site, however, it just works as well as before. Here is logs: https://github.com/renbaoshuo/hexo-for-oiers/actions/runs/5409300619/jobs/9829263304

Coule you please give a minium reproduction in order to find the real problem of your issue?

**Comment by yltx** [comment]
> I tried to use `hexo@7.0.0-rc1` in [renbaoshuo/hexo-for-oiers](https://github.com/renbaoshuo/hexo-for-oiers), which using GitHub Actions to build the site, however, it just works as well as before. Here is log: https://github.com/renbaoshuo/hexo-for-oiers/actions/runs/5409300619/jobs/9829263304
> 
> Coule you please give a minium reproduction in order to find the real problem of your issue?

ok you can check your qq later.
