### ISSUE TITLE
hexo-plugins在windows下运行hexo s命令时出错

### ISSUE THREAD

**Issue by skyoung** [hexojs/hexo#604]
我使用了hexo-render-pandoc这个plugin，用hexo s进行watch的时候报错，当我删除plugin时就没有问题。

具体报错如下：
```
C:\Users\skyoung\AppData\Roaming\npm\node_modules\hexo\node_modules\async\lib\as
ync.js:23
            if (called) throw new Error("Callback was already called.");
                              ^
Error: Callback was already called.
    at C:\Users\skyoung\AppData\Roaming\npm\node_modules\hexo\node_modules\async
\lib\async.js:23:31
    at Domain.<anonymous> (C:\Users\skyoung\AppData\Roaming\npm\node_modules\hex
o\lib\box\index.js:115:12)
    at Domain.EventEmitter.emit (events.js:95:17)
    at ChildProcess.EventEmitter.emit (events.js:70:21)
    at Process.ChildProcess._handle.onexit (child_process.js:795:12)
```

望能抽时间看一下这个问题，谢谢。

**Comment by Xuanwo** [comment]
@skyoung Still have the problem?

**Comment by leesei** [comment]
Please open new issue if the problem persists with latest version.
