### ISSUE TITLE
hexo generate error

### ISSUE THREAD

**Issue by 2hu12** [hexojs/hexo#645]
```
root@raspberrypi:/home/pi/hexo# hexo generate
[error] HexoError: Process failed: _posts/2014-05-26-before-getting-busy.md
TypeError: Cannot read property 'length' of null
    at isEndWith (/usr/local/lib/node_modules/hexo/lib/model/schema.js:9:17)
    at Object.permalinkGetter (/usr/local/lib/node_modules/hexo/lib/model/schema.js:15:17)
    at Model._applyGetter (/usr/local/lib/node_modules/hexo/node_modules/warehouse/lib/model.js:240:24)
    at Model.get.Model.findById (/usr/local/lib/node_modules/hexo/node_modules/warehouse/lib/model.js:299:19)
    at /usr/local/lib/node_modules/hexo/node_modules/warehouse/lib/model.js:483:20
    at Object.async.eachSeries (/usr/local/lib/node_modules/hexo/node_modules/warehouse/node_modules/async/lib/async.js:130:20)
    at Model._save (/usr/local/lib/node_modules/hexo/node_modules/warehouse/lib/model.js:475:9)
    at Model.insert (/usr/local/lib/node_modules/hexo/node_modules/warehouse/lib/model.js:522:8)
    at /usr/local/lib/node_modules/hexo/lib/model/hooks/post.js:58:11
    at Array.forEach (native)
```

**Comment by zzz6519003** [comment]
i've been the same error, the way i fix it is modify _config.yml  change to `url: /`
