### ISSUE TITLE
BUG反馈：某特定文件生成失败

### ISSUE THREAD

**Issue by Xuanwo** [hexojs/hexo#720]
报错信息如下

```
E:\文档\Blog> hexo g
[error] HexoError: Process failed: _posts/POJ-3194-Equidivisions.md
Error: Unexpected comma on line 27 in file E:\文档\Blog\source\_posts\POJ-3194-Equidivisions.md.
    at Object.exports.throwError (C:\Users\xuanw_000\AppData\Roaming\npm\node_modules\hexo\node_modules\swig\
s:183:9)
    at Object.TokenParser.parseToken (C:\Users\xuanw_000\AppData\Roaming\npm\node_modules\hexo\node_modules\s
ser.js:258:15)
    at C:\Users\xuanw_000\AppData\Roaming\npm\node_modules\hexo\node_modules\swig\lib\parser.js:86:12
    at Object.exports.each (C:\Users\xuanw_000\AppData\Roaming\npm\node_modules\hexo\node_modules\swig\lib\ut
1)
    at Object.TokenParser.parse (C:\Users\xuanw_000\AppData\Roaming\npm\node_modules\hexo\node_modules\swig\l
s:76:11)
    at parseVariable (C:\Users\xuanw_000\AppData\Roaming\npm\node_modules\hexo\node_modules\swig\lib\parser.j
    at C:\Users\xuanw_000\AppData\Roaming\npm\node_modules\hexo\node_modules\swig\lib\parser.js:633:15
    at Object.exports.each (C:\Users\xuanw_000\AppData\Roaming\npm\node_modules\hexo\node_modules\swig\lib\ut
1)
    at Object.exports.parse (C:\Users\xuanw_000\AppData\Roaming\npm\node_modules\hexo\node_modules\swig\lib\p
2:9)
    at parse (C:\Users\xuanw_000\AppData\Roaming\npm\node_modules\hexo\node_modules\swig\lib\swig.js:349:19)
```

Hexo版本信息

```
hexo: 2.7.1
os: Windows_NT 6.2.9200 win32 x64
http_parser: 1.0
node: 0.10.29
v8: 3.14.5.9
ares: 1.9.0-DEV
uv: 0.10.27
zlib: 1.2.3
modules: 11
openssl: 1.0.1h
```

删除这个MD文档之后一切正常，求教是什么原因。

**Comment by zjbztianya** [comment]
ERROR Process failed: _posts/HDU5274-Dylans-loves-tree-树链-剖分.md
我也出现这个问题了。。。但是我代码里头没有{}嵌套啊～～～～

**Comment by zjbztianya** [comment]
文章如下：
title: HDU5274-Dylans loves tree(树链 剖分)
date: 2015-06-22 19:48:35
tags: 树链剖分
categories:数据结构
mathjax:true
---
###题意###
Dylans有一棵$N$个点的树。每个点有点权。树上节点标号为$1$∼$N$。
他得到了$Q$个询问，形式如下：
①$0 \ x \ y$：把第$x$个点的点权修改为$y$。
②$1 \ x \ y$：对于$x∼y$路径上的每一种点权，是否都出现偶数次？
如果是偶数次就输出"-1",否则输出出现奇数次的权值
保证每次询问的路径上最多只有一种点权的出现次数是奇数次。

$1\le N,Q\le 100000$, 点权$A[i]∈N$，且都 $\le 100000$
###题解###
裸树链剖分,如果路径上的$XOR$值为$0$，则说明路径上的每一种点权都出现偶数次，不为$0$则$XOR$就是出现奇数次的点权。有个坑点就是点权$0$出现了奇数次，为了处理这个，只需要把点权全部加$1$，答案减一即可。
###代码###
```
#pragma warning(disable : 4786)
#pragma comment(linker, "/STACK:1024000000,1024000000")
#include <iostream>
#include <algorithm>
#include <cstdio>
#include <cstring>
#include <utility>
#include <vector>
#include <queue>
#include <map>
#include <deque>
#include <cmath>
#include <stack>
#include <string>
#include <set>
#include <sstream>
#include <cstdlib>
using namespace std;
#define  INF 0x3f3f3f3f
#define  maxn 111111
#define lson l,m,s<<1
#define rson m+1,r,s<<1|1
typedef long long LL;
struct node
{
    int to,next;
};
node edge[maxn << 1];
int head[maxn], tot;
int top[maxn];//top[v]表示v所在的重链的顶端节点
int fa[maxn]; //父亲节点
int dep[maxn];//深度
int sz[maxn];//sz[v]表示以v为根的子树的节点数
int id[maxn];//id[v]表示v与其父亲节点的连边在线段树中的位置
int son[maxn];//重儿子
int pos;
int xorv[maxn<<2];
int num[maxn],a[maxn<<2];
void init()
{
    tot =pos=0;
    memset(head, -1, sizeof(head));
    memset(son, -1, sizeof(son));
}
void add_edge(int u, int v)
{
    edge[tot].to = v;
    edge[tot].next = head[u];
    head[u]=tot++;
}
void dfs_1(int u, int pre, int d)
{
    fa[u] = pre, dep[u] = d, sz[u] = 1;
    for (int i = head[u]; i != -1; i = edge[i].next)
    {
        int v = edge[i].to;
        if (v==pre) continue;
        dfs_1(v, u, d + 1);
        sz[u] += sz[v];
        if (son[u] == -1 || sz[son[u]] < sz[v]) son[u] = v;
    }
}
void dfs_2(int u, int tp)
{
    top[u] = tp;
    id[u] = pos++;
    if (son[u] != -1) dfs_2(son[u], tp);
    for (int i = head[u]; i != -1; i = edge[i].next)
    {
        int v = edge[i].to;
        if (v == fa[u] || v == son[u]) continue;
        dfs_2(v, v);
    }
}
void pushup(int s)
{
    xorv[s] = xorv[s << 1]^xorv[s << 1 | 1];
}
void build(int l, int r, int s)
{
    if (l == r)
    {
        xorv[s]=num[r];
        return;
    }
    int m = (l + r) >> 1;
    build(lson);
    build(rson);
    pushup(s);
}
void update(int p, int v, int l, int r, int s)
{
    if (l == r)
    {
        xorv[s]= v;
        return;
    }
    int m = (l + r) >> 1;
    if (p <= m) update(p, v, lson);
    else update(p, v, rson);
    pushup(s);
}
int query(int ql, int qr, int l, int r, int s)
{
    if (ql <= l&&r <= qr) return xorv[s];
    int m = (l + r) >> 1,ret=0;
    if (ql <= m) ret ^=query(ql, qr, lson);
    if (qr > m) ret ^=query(ql, qr, rson);
    return ret;
}
int get_xor(int u, int v)
{
    int f1 = top[u], f2 = top[v],ret=0;
    while (f1!=f2)
    {
        if (dep[f1] < dep[f2])
        {
            swap(u, v);
            swap(f1, f2);
        }
        ret ^=query(id[f1], id[u], 0, pos - 1, 1);
        u = fa[f1], f1 = top[u];
    }
    if (dep[u] > dep[v])swap(u, v);
    ret ^= query(id[u], id[v], 0, pos - 1, 1);
    return ret;
}
int main()
{
#ifndef ONLINE_JUDGE
    //freopen("in.txt", "r", stdin);
    //freopen("out.txt","w",stdout);
#endif
    int T;
    scanf("%d", &T);
    while (T--)
    {
        int n,q;
        scanf("%d%d", &n,&q);
        init();
        for (int i = 1; i < n; i++)
        {
            int u, v;
            scanf("%d%d", &u, &v);
            add_edge(u, v);
            add_edge(v, u);
        }
        dfs_1(1,0,1);
        dfs_2(1,1);
        for (int i = 1; i <= n; i++)
        {
            int x;
            scanf("%d",&x);
            num[id[i]] = x+1;
        }
        build(0, n-1, 1);
        while(q--)
        {
            int op,x,y;
            scanf("%d%d%d",&op,&x,&y);
            if(op==0)
            {
                update(id[x],y+1,0,n-1,1);
            }
            else
            {
                int ans=get_xor(x,y);
                if(ans==0) printf("-1\n");
                else printf("%d\n",ans-1);
            }
        }
    }
    return 0;
}
```

**Comment by Xuanwo** [comment]
`categories:数据结构`少了一个空格
