### ISSUE TITLE
更新hexo后无法运行

### ISSUE THREAD

**Issue by meowtech** [hexojs/hexo#760]
**代码如下**

```
hexo s --debug
[debug] 09:24:12.294 Config file loaded from /home/jeffrey/blog/_config.yml
[debug] 09:24:12.311 Version info checked successfully
[debug] 09:24:12.393 Processed: draft.md (7ms)
[debug] 09:24:12.393 Processed: link.md (8ms)
[debug] 09:24:12.395 Processed: page.md (10ms)
[debug] 09:24:12.395 Processed: diary.md (10ms)
[debug] 09:24:12.396 Processed: photo.md (10ms)
[debug] 09:24:12.396 Processed: post.md (10ms)
[debug] 09:24:12.396 Processed: video.md (10ms)
[debug] 09:24:12.530 Plugin loaded successfully: hexo-generator-feed
[debug] 09:24:12.554 Plugin loaded successfully: hexo-generator-sitemap
[debug] 09:24:13.861 Plugin loaded successfully: hexo-migrator-wordpress
[debug] 09:24:13.951 Plugin loaded successfully: hexo-renderer-ejs
[debug] 09:24:14.895 Plugin loaded successfully: hexo-renderer-jade
[debug] 09:24:14.995 Plugin loaded successfully: hexo-renderer-less
[debug] 09:24:15.110 Plugin loaded successfully: hexo-renderer-marked
[debug] 09:24:15.748 Plugin loaded successfully: hexo-renderer-stylus
[debug] 09:24:15.792 Plugin loaded successfully: hexo-tag-bootstrap
[debug] 09:24:15.827 Script load successfully: fancybox.js
[error] 09:24:15.828 TypeError: Cannot read property 'format' of null
TypeError: Cannot read property 'format' of null
    at morgan (/usr/local/lib/node_modules/hexo/node_modules/morgan/index.js:36:21)
    at module.exports (/usr/local/lib/node_modules/hexo/lib/plugins/filter/middlewares/logger.js:11:13)
    at /usr/local/lib/node_modules/hexo/lib/extend/filter.js:141:25
    at b (domain.js:183:18)
    at Domain.run (domain.js:123:23)
    at /usr/local/lib/node_modules/hexo/lib/extend/filter.js:140:9
    at Array.forEach (native)
    at Filter.apply (/usr/local/lib/node_modules/hexo/lib/extend/filter.js:137:10)
    at module.exports (/usr/local/lib/node_modules/hexo/lib/plugins/console/server.js:26:22)
    at /usr/local/lib/node_modules/hexo/lib/core/index.js:227:7


```

**求解救**

**Comment by cs-sun** [comment]
时区设置问题
