### ISSUE TITLE
hexo 2.8.3 deploy fail, Error: spawn ENOENT

### ISSUE THREAD

**Issue by commerlee** [hexojs/hexo#846]
![2014-09-17_224311](https://cloud.githubusercontent.com/assets/3616438/4305423/345b85a2-3e79-11e4-86c0-3bb2fda59c31.gif)

_config.yml
deploy:
  type: github
  repo: https://github.com/commerlee/blog.git

hexo version is 2.8.3

help me!!

**Comment by 5104020942** [comment]
may be you just try to get git.

**Comment by vincent927** [comment]
I got a same problem
```
[root@ecs hexo]# hexo d
INFO  Deploying: git
INFO  Clearing .deploy_git folder...
INFO  Copying files from public folder...
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: spawn ENOMEM
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at Object.exports.spawn (child_process.js:385:9)
    at spawn (/data/www/hexo/node_modules/.4.0.0@cross-spawn/index.js:17:18)
    at /data/www/hexo/node_modules/.0.6.0@hexo-util/lib/spawn.js:19:16
    at Promise._execute (/data/www/hexo/node_modules/.3.4.1@bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/data/www/hexo/node_modules/.3.4.1@bluebird/js/release/promise.js:475:18)
    at new Promise (/data/www/hexo/node_modules/.3.4.1@bluebird/js/release/promise.js:77:14)
    at promiseSpawn (/data/www/hexo/node_modules/.0.6.0@hexo-util/lib/spawn.js:18:10)
    at git (/data/www/hexo/node_modules/.0.2.0@hexo-deployer-git/lib/deployer.js:49:12)
    at push (/data/www/hexo/node_modules/.0.2.0@hexo-deployer-git/lib/deployer.js:74:12)
    at /data/www/hexo/node_modules/.0.2.0@hexo-deployer-git/lib/deployer.js:97:12
    at tryCatcher (/data/www/hexo/node_modules/.3.4.1@bluebird/js/release/util.js:16:23)
```

My _config.yml

```
deploy:
  type: git
  repo: git@github.com:vincent927/vincent927.github.io.git
  branch: master
```

How to fix it ?

**Comment by strongSoda** [comment]
Hey I am getting this problem in hexo-admin 

![hexo](https://user-images.githubusercontent.com/30754328/42136578-c3cc2a3a-7d7b-11e8-8459-52c1ba607cfb.PNG)

**Comment by tcrowe** [comment]
Under deploy `type: git` and not github 😊
