### ISSUE TITLE
hexo deploy 不成功

### ISSUE THREAD

**Issue by fionalee1412** [hexojs/hexo#856]
[info] Start deploying: github
[info] Clearing .deploy folder...
[info] Copying files from public folder...
[error] Error: spawn ENOENT
Error: spawn ENOENT
    at errnoException (child_process.js:1000:11)
    at Process.ChildProcess._handle.onexit (child_process.js:791:34)

[error] Error: spawn ENOENT
Error: spawn ENOENT
    at errnoException (child_process.js:1000:11)
    at Process.ChildProcess._handle.onexit (child_process.js:791:34)

[error] Error: spawn ENOENT
Error: spawn ENOENT
    at errnoException (child_process.js:1000:11)
    at Process.ChildProcess._handle.onexit (child_process.js:791:34)

[info] Deploy done: github

试了很多办法还是不成功

**Comment by Xuanwo** [comment]
请问现在还有问题么？
