### ISSUE TITLE
use layout:false for a static html, error when generate

### ISSUE THREAD

**Issue by pedant** [hexojs/hexo#888]
based in V2.8.3
```
Error: Unexpected colon on line 1659 in file abc.html.
    at Object.exports.throwError (xx\node_modules\hexo\node_modules\swig\lib\utils.js:183:9)
    at Object.TokenParser.parseToken(xx\node_modules\hexo\node_modules\swig\lib\parser.js:319:15)
    at xx\node_modules\hexo\node_modules\swig\lib\parser.js:86:12
    at Object.exports.each (xx\node_modules\hexo\node_modules\swig\lib\utils.js:45:11)
    at Object.TokenParser.parse (xx\node_modules\hexo\node_modules\swig\lib\parser.js:76:11)
    at parseVariable (xx\node_modules\hexo\node_modules\swig\lib\parser.js:486:18)
    at xx\node_modules\hexo\node_modules\swig\lib\parser.js:633:15
    at Object.exports.each (xx\node_modules\hexo\node_modules\swig\lib\utils.js:45:11)
    at Object.exports.parse (xx\node_modules\hexo\node_modules\swig\lib\parser.js:622:9)
    at parse (xx\node_modules\hexo\node_modules\swig\lib\swig.js:342:19)
```

**Comment by leesei** [comment]
You have to try using [`{% raw %}`](https://hexo.io/docs/tag-plugins.html#Raw) to escape `{{`.
You can also use `skip_render` in Hexo 3.
