### ISSUE TITLE
安裝hexo報錯

### ISSUE THREAD

**Issue by mingmings** [hexojs/hexo#892]
```
➜  ~  nvm ls
    v0.10.33
->   v0.11.0

➜  ~  nvm --version
0.17.3

➜  ~  npm --version
2.1.5

➜  ~  sudo npm --registry=https://registry.npm.taobao.org install hexo

> fsevents@0.2.0 install /Users/playcrab/node_modules/hexo/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
../node_modules/nan/nan.h:406:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../node_modules/nan/nan.h:141:71: note: expanded from macro 'NAN_INLINE'
# define NAN_INLINE(declarator) inline __attribute__((always_inline)) declarator
                                                                      ^
../node_modules/nan/nan.h:427:26: error: no member named 'Use' in 'node::Buffer'
    return node::Buffer::Use(data, size);
           ~~~~~~~~~~~~~~^
../node_modules/nan/nan.h:451:57: error: too many arguments to function call, expected at most 3, have 4
      , v8::Context::New(nan_isolate, extensions, tmpl, obj)
        ~~~~~~~~~~~~~~~~                                ^~~
/Users/playcrab/.node-gyp/0.11.0/deps/v8/include/v8.h:3871:3: note: 'New' declared here
  static Persistent<Context> New(
  ^
In file included from ../fsevents.cc:6:
../node_modules/nan/nan.h:728:5: error: no member named 'Reset' in 'v8::Persistent<v8::Object>'
    NanAssignPersistent(v8::Object, handle, obj);
    ^                               ~~~~~~
../node_modules/nan/nan.h:305:56: note: expanded from macro 'NanAssignPersistent'
# define NanAssignPersistent(type, handle, obj) handle.Reset(nan_isolate, obj)
                                                       ^
../node_modules/nan/nan.h:734:5: error: no member named 'Reset' in 'v8::Persistent<v8::Object>'
    NanAssignPersistent(v8::Object, handle, obj);
    ^                               ~~~~~~
../node_modules/nan/nan.h:305:56: note: expanded from macro 'NanAssignPersistent'
# define NanAssignPersistent(type, handle, obj) handle.Reset(nan_isolate, obj)
                                                       ^
../node_modules/nan/nan.h:740:12: warning: 'Dispose' is deprecated [-Wdeprecated-declarations]
    handle.Dispose();
           ^
/Users/playcrab/.node-gyp/0.11.0/deps/v8/include/v8.h:404:22: note: 'Dispose' has been explicitly marked deprecated here
  V8_DEPRECATED(void Dispose());
                     ^
/Users/playcrab/.node-gyp/0.11.0/deps/v8/include/v8.h:88:35: note: expanded from macro 'V8_DEPRECATED'
#define V8_DEPRECATED(declarator) declarator __attribute__ ((deprecated))
                                  ^
../fsevents.cc:54:12: error: no type named 'FunctionCallbackInfo' in namespace 'v8'
    static NAN_METHOD(New);
           ^~~~~~~~~~~~~~~
../node_modules/nan/nan.h:678:55: note: expanded from macro 'NAN_METHOD'
#define NAN_METHOD(name) _NAN_METHOD_RETURN_TYPE name(_NAN_METHOD_ARGS)
                                                      ^~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:223:27: note: expanded from macro '_NAN_METHOD_ARGS'
# define _NAN_METHOD_ARGS _NAN_METHOD_ARGS_TYPE args
                          ^~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:222:42: note: expanded from macro '_NAN_METHOD_ARGS_TYPE'
# define _NAN_METHOD_ARGS_TYPE const v8::FunctionCallbackInfo<v8::Value>&
                                     ~~~~^
../fsevents.cc:54:12: error: expected ')'
../node_modules/nan/nan.h:678:55: note: expanded from macro 'NAN_METHOD'
#define NAN_METHOD(name) _NAN_METHOD_RETURN_TYPE name(_NAN_METHOD_ARGS)
                                                      ^
../node_modules/nan/nan.h:223:27: note: expanded from macro '_NAN_METHOD_ARGS'
# define _NAN_METHOD_ARGS _NAN_METHOD_ARGS_TYPE args
                          ^
../node_modules/nan/nan.h:222:62: note: expanded from macro '_NAN_METHOD_ARGS_TYPE'
# define _NAN_METHOD_ARGS_TYPE const v8::FunctionCallbackInfo<v8::Value>&
                                                             ^
../fsevents.cc:54:12: note: to match this '('
../node_modules/nan/nan.h:678:54: note: expanded from macro 'NAN_METHOD'
#define NAN_METHOD(name) _NAN_METHOD_RETURN_TYPE name(_NAN_METHOD_ARGS)
                                                     ^
../fsevents.cc:55:12: error: no type named 'FunctionCallbackInfo' in namespace 'v8'
    static NAN_METHOD(Stop);
           ^~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:678:55: note: expanded from macro 'NAN_METHOD'
#define NAN_METHOD(name) _NAN_METHOD_RETURN_TYPE name(_NAN_METHOD_ARGS)
                                                      ^~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:223:27: note: expanded from macro '_NAN_METHOD_ARGS'
# define _NAN_METHOD_ARGS _NAN_METHOD_ARGS_TYPE args
                          ^~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:222:42: note: expanded from macro '_NAN_METHOD_ARGS_TYPE'
# define _NAN_METHOD_ARGS_TYPE const v8::FunctionCallbackInfo<v8::Value>&
                                     ~~~~^
../fsevents.cc:55:12: error: expected ')'
../node_modules/nan/nan.h:678:55: note: expanded from macro 'NAN_METHOD'
#define NAN_METHOD(name) _NAN_METHOD_RETURN_TYPE name(_NAN_METHOD_ARGS)
                                                      ^
../node_modules/nan/nan.h:223:27: note: expanded from macro '_NAN_METHOD_ARGS'
# define _NAN_METHOD_ARGS _NAN_METHOD_ARGS_TYPE args
                          ^
../node_modules/nan/nan.h:222:62: note: expanded from macro '_NAN_METHOD_ARGS_TYPE'
# define _NAN_METHOD_ARGS_TYPE const v8::FunctionCallbackInfo<v8::Value>&
                                                             ^
../fsevents.cc:55:12: note: to match this '('
../node_modules/nan/nan.h:678:54: note: expanded from macro 'NAN_METHOD'
#define NAN_METHOD(name) _NAN_METHOD_RETURN_TYPE name(_NAN_METHOD_ARGS)
                                                     ^
../fsevents.cc:56:12: error: no type named 'FunctionCallbackInfo' in namespace 'v8'
    static NAN_METHOD(Start);
           ^~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:678:55: note: expanded from macro 'NAN_METHOD'
#define NAN_METHOD(name) _NAN_METHOD_RETURN_TYPE name(_NAN_METHOD_ARGS)
                                                      ^~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:223:27: note: expanded from macro '_NAN_METHOD_ARGS'
# define _NAN_METHOD_ARGS _NAN_METHOD_ARGS_TYPE args
                          ^~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:222:42: note: expanded from macro '_NAN_METHOD_ARGS_TYPE'
# define _NAN_METHOD_ARGS_TYPE const v8::FunctionCallbackInfo<v8::Value>&
                                     ~~~~^
../fsevents.cc:56:12: error: expected ')'
../node_modules/nan/nan.h:678:55: note: expanded from macro 'NAN_METHOD'
#define NAN_METHOD(name) _NAN_METHOD_RETURN_TYPE name(_NAN_METHOD_ARGS)
                                                      ^
../node_modules/nan/nan.h:223:27: note: expanded from macro '_NAN_METHOD_ARGS'
# define _NAN_METHOD_ARGS _NAN_METHOD_ARGS_TYPE args
                          ^
../node_modules/nan/nan.h:222:62: note: expanded from macro '_NAN_METHOD_ARGS_TYPE'
# define _NAN_METHOD_ARGS_TYPE const v8::FunctionCallbackInfo<v8::Value>&
                                                             ^
../fsevents.cc:56:12: note: to match this '('
../node_modules/nan/nan.h:678:54: note: expanded from macro 'NAN_METHOD'
#define NAN_METHOD(name) _NAN_METHOD_RETURN_TYPE name(_NAN_METHOD_ARGS)
                                                     ^
In file included from ../fsevents.cc:83:
../src/methods.cc:17:1: error: no type named 'FunctionCallbackInfo' in namespace 'v8'
NAN_METHOD(FSEvents::New) {
^~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:678:55: note: expanded from macro 'NAN_METHOD'
#define NAN_METHOD(name) _NAN_METHOD_RETURN_TYPE name(_NAN_METHOD_ARGS)
                                                      ^~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:223:27: note: expanded from macro '_NAN_METHOD_ARGS'
# define _NAN_METHOD_ARGS _NAN_METHOD_ARGS_TYPE args
                          ^~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:222:42: note: expanded from macro '_NAN_METHOD_ARGS_TYPE'
# define _NAN_METHOD_ARGS_TYPE const v8::FunctionCallbackInfo<v8::Value>&
                                     ~~~~^
In file included from ../fsevents.cc:83:
../src/methods.cc:17:1: error: expected ')'
../node_modules/nan/nan.h:678:55: note: expanded from macro 'NAN_METHOD'
#define NAN_METHOD(name) _NAN_METHOD_RETURN_TYPE name(_NAN_METHOD_ARGS)
                                                      ^
../node_modules/nan/nan.h:223:27: note: expanded from macro '_NAN_METHOD_ARGS'
# define _NAN_METHOD_ARGS _NAN_METHOD_ARGS_TYPE args
                          ^
../node_modules/nan/nan.h:222:62: note: expanded from macro '_NAN_METHOD_ARGS_TYPE'
# define _NAN_METHOD_ARGS_TYPE const v8::FunctionCallbackInfo<v8::Value>&
                                                             ^
../src/methods.cc:17:1: note: to match this '('
../node_modules/nan/nan.h:678:54: note: expanded from macro 'NAN_METHOD'
#define NAN_METHOD(name) _NAN_METHOD_RETURN_TYPE name(_NAN_METHOD_ARGS)
                                                     ^
In file included from ../fsevents.cc:83:
../src/methods.cc:20:32: error: use of undeclared identifier 'args'
  char* path = NanFromV8String(args[0], Nan::UTF8, NULL, NULL, 0, v8::String::NO_OPTIONS);
                               ^
../src/methods.cc:21:43: error: use of undeclared identifier 'args'
  NanCallback *callback = new NanCallback(args[1].As<v8::Function>());
                                          ^
../src/methods.cc:21:66: error: expected '(' for function-style cast or type construction
  NanCallback *callback = new NanCallback(args[1].As<v8::Function>());
                                                     ~~~~~~~~~~~~^
../src/methods.cc:21:68: error: expected expression
  NanCallback *callback = new NanCallback(args[1].As<v8::Function>());
                                                                   ^
../src/methods.cc:24:13: error: use of undeclared identifier 'args'
  fse->Wrap(args.This());
            ^
../src/methods.cc:26:3: error: use of undeclared identifier 'args'
  NanReturnValue(args.This());
  ^
../node_modules/nan/nan.h:301:39: note: expanded from macro 'NanReturnValue'
# define NanReturnValue(value) return args.GetReturnValue().Set(value)
                                      ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/playcrab/.nvm/v0.11.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:757:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/Users/playcrab/.nvm/v0.11.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/playcrab/node_modules/hexo/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v0.11.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm WARN optional dep failed, continuing fsevents@0.2.0
hexo@2.8.3 node_modules/hexo
├── strip-indent@0.1.3
├── hexo-front-matter@0.0.4
├── sprintf-js@0.0.7
├── colors@0.6.2
├── graceful-fs@3.0.4
├── minimist@0.2.0
├── mime@1.2.11
├── async@0.9.0
├── warehouse@0.2.2 (async@0.7.0)
├── morgan@1.4.1 (basic-auth@1.0.0, depd@1.0.0, on-finished@2.1.1, debug@2.1.0)
├── connect@3.3.1 (utils-merge@1.0.0, parseurl@1.3.0, debug@2.1.0, finalhandler@0.3.2)
├── compression@1.2.0 (on-headers@1.0.0, vary@1.0.0, bytes@1.0.0, debug@2.1.0, compressible@2.0.1, accepts@1.1.2)
├── serve-static@1.7.1 (utils-merge@1.0.0, escape-html@1.0.1, parseurl@1.3.0, send@0.10.1)
├── highlight.js@8.1.0
├── lodash@2.4.1
├── moment@2.8.3
├── cheerio@0.17.0 (entities@1.1.1, dom-serializer@0.0.1, CSSselect@0.4.1, htmlparser2@3.7.3)
├── swig@1.4.1 (optimist@0.6.1, uglify-js@2.4.15)
├── chokidar@0.8.2 (recursive-readdir@0.0.2)
└── js-yaml@3.2.2 (esprima@1.0.4, argparse@0.1.15)
```

一直沒有注意到別人也出現了這樣的錯誤，對nodejs剛開始接觸，不太明白其中報錯的緣由在哪裡，請問這是那裡出的問題呢？

**Comment by pavelbinar** [comment]
I am getting same error:

```
/Users/pavelbinar/.node-gyp/0.11.13/deps/v8/include/v8.h:1441:8: note: 'IsSymbol' declared here
  bool IsSymbol() const;
       ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/pavelbinar/.nvm/v0.11.13/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1046:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/Users/pavelbinar/.nvm/v0.11.13/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/pavelbinar/.nvm/v0.11.13/lib/node_modules/hexo/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v0.11.13
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok
npm WARN optional dep failed, continuing fsevents@0.2.0
/Users/pavelbinar/.nvm/v0.11.13/bin/hexo -> /Users/pavelbinar/.nvm/v0.11.13/lib/node_modules/hexo/bin/hexo
npm WARN unmet dependency /Users/pavelbinar/.nvm/v0.11.13/lib/node_modules/stream-adventure/node_modules/trumpet/node_modules/html-tokenize requires readable-stream@'~1.0.27-1' but will load
npm WARN unmet dependency /Users/pavelbinar/.nvm/v0.11.13/lib/node_modules/stream-adventure/node_modules/trumpet/node_modules/readable-stream,
npm WARN unmet dependency which is version 1.1.13-1
npm WARN unmet dependency /Users/pavelbinar/.nvm/v0.11.13/lib/node_modules/verb-cli/node_modules/plasma/node_modules/expander requires lodash@'~2.2.1' but will load
npm WARN unmet dependency /Users/pavelbinar/.nvm/v0.11.13/lib/node_modules/verb-cli/node_modules/lodash,
npm WARN unmet dependency which is version 2.4.1
hexo@2.8.3 /Users/pavelbinar/.nvm/v0.11.13/lib/node_modules/hexo
```

**Comment by tommy351** [comment]
Try to use Node 0.10.x instead.

**Comment by pavelbinar** [comment]
Yes, that worked. Thanks.

**Comment by haifengkao** [comment]
I have the same problem with Node 0.12.0. Why does this problem occur?
