### ISSUE TITLE
Advanced get_posts query

### ISSUE THREAD

**Issue by nxfifteen** [hexojs/hexo#981]
Is it possible to use the get_posts helper function to return all posts that are not in a category? I've attempted to use:
`get_posts({count: 14, orderby: "date", order: -1, query:{categories: 'Diary', operator: 'not'}})` and
`get_posts({count: 14, orderby: "date", order: -1, query:{categories: 'Diary', operator: '!='}})` or
`get_posts({count: 14, orderby: "date", order: -1, query:{categories: 'Diary', operator: '<>'}})` 
but it returns no posts instead?

I've also noticed from pull #950 that the get_posts helper has been removed. Is it being replaced by anything else or will there be no way to get a subset of posts once this has gone?

**Comment by tommy351** [comment]
`get_posts` helper was removed in 3.0 since it's too complicated. You can try this:

``` js
site.categories.find({name: 'Diary'}).posts.sort('date', -1).limit(14)
```

**Comment by nxfifteen** [comment]
Sorry for the delayed reply.

I've tried using the `site.categories.find({name: 'Diary'}).posts.sort('date', -1).limit(14)` on the site just now to see how it would work, but with version 2.8.3 the error returned is:
"Cannot call method 'sort' of undefined"

Would this code only work after upgrading to version 3, or am I doing something wrong?

**Comment by tommy351** [comment]
In Hexo 2, you have to populate the posts first.

``` js
site.categories.find({name: 'Diary'}).populate('posts').posts.sort('date', -1).limit(14)
```

**Comment by fuzzy31u** [comment]
Hello,
I tried code above in Hexo 3.0.0, but I got this error,

`
Unhandled rejection PopulationError: /path/to/themes/air/layout/index.ejs:20
    18| <% }); %>
    19| 
 >> 20| <%= site.categories.find({name: 'Diary'}).populate('posts') %>
    21| 

model is required
    at Schema._parsePopulate (/path/to/node_modules/hexo/node_modules/warehouse/lib/schema.js:795:15)
    at Query.populate (/path/to/node_modules/hexo/node_modules/warehouse/lib/query.js:450:28)
    at eval (eval at <anonymous> (/path/to/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:913)
    at eval (eval at <anonymous> (/path/to/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:977)
    at /path/to/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:255:15
    at Object.exports.render (/path/to/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:293:13)
    at Hexo.<anonymous> (/path/to/node_modules/hexo-renderer-ejs/index.js:5:14)
    at Hexo.tryCatcher (/path/to/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
    at Hexo.<anonymous> (/path/to/node_modules/hexo/node_modules/bluebird/js/main/method.js:15:34)
    at /path/to/node_modules/hexo/lib/hexo/render.js:51:21
    at tryCatcher (/path/to/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/path/to/node_modules/hexo/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/path/to/node_modules/hexo/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromiseAtPostResolution (/path/to/node_modules/hexo/node_modules/bluebird/js/main/promise.js:224:10)
    at Async._drainQueue (/path/to/node_modules/hexo/node_modules/bluebird/js/main/async.js:84:12)
    at Async._drainQueues (/path/to/node_modules/hexo/node_modules/bluebird/js/main/async.js:89:10)
    at Async.drainQueues (/path/to/node_modules/hexo/node_modules/bluebird/js/main/async.js:14:14)
    at process._tickCallback (node.js:355:11)
`

How can I list posts per categores?

Best,

**Comment by ianrose** [comment]
@tommy351 I followed the 2.x.x migration to 3.0 docs. Before updating I was using `get_posts` to display posts from certain categories. Here is a link of my theme in v2.8.3 with `get_posts` working https://github.com/ianrose/ianrose-source/blob/master/themes/ianrose-theme/layout/index.ejs#L13-L30

After upgrading to v3.0 I tried to use `site.categories.find({name: 'notes'}).posts.sort('date', -1).limit(14)` and am getting the error `Cannot call method 'sort' of undefined`

The v3.0 index.ejs with the offending code:
https://github.com/ianrose/ianrose-source/blob/hexo-3/themes/ianrose-theme/layout/index.ejs#L11

My latest package.json:
https://github.com/ianrose/ianrose-source/blob/hexo-3/package.json#L9

**Comment by LouisBarranqueiro** [comment]
@ianrose 
@nxfifteen 
The function ```find``` doesn't work, you have to use ```findOne```. It works fine on my project.
I opened an issue to report this :  [issue#1174](https://github.com/hexojs/hexo/issues/1174)

**Comment by ianrose** [comment]
@LouisBarranqueiro thanks for the tip, updated and now working:

```ejs
<%site.categories.findOne({name: 'articles'}).posts.sort('date', -1).limit(14).each(function(post) {%>
  <%- partial('partials/entry-post', {post: post, index: true}) %>
<% })%>
```

**Comment by antonellisantos** [comment]
How can I search only posts publicated after a specific date? I tried to use "$gte" but it returns an error.

**Comment by crimx** [comment]
@nxfifteen @tommy351 Just curious, where can I find these APIs? like `findOne` and `limit` etc. Didn't see them at the API pages.
