### ISSUE TITLE
Cannot read property 'marked' of undefined

### ISSUE THREAD

**Issue by ricardojmendez** [hexojs/hexo#988]
I've just started getting the following error when attempting to run _hexo server_:

	TypeError: Cannot read property 'marked' of undefined
	    at module.exports (/path/to/hexo-site-repo/node_modules/hexo-renderer-marked/lib/renderer.js:53:17)
	    at /usr/local/lib/node_modules/hexo/lib/extend/renderer.js:78:38
	    at b (domain.js:183:18)
	    at Domain.run (domain.js:123:23)
	    at store.(anonymous function) (/usr/local/lib/node_modules/hexo/lib/extend/renderer.js:77:9)
	    at /usr/local/lib/node_modules/hexo/lib/core/render.js:96:9
	    at fn (/usr/local/lib/node_modules/hexo/node_modules/async/lib/async.js:641:34)
	    at Object._onImmediate (/usr/local/lib/node_modules/hexo/node_modules/async/lib/async.js:557:34)
	    at processImmediate [as _immediateCallback] (timers.js:345:15)

I thought hexo might be having issues with a particular markdown document I was working on, but the error appears after stashing it.  I keep everything under version control, and reverting to known good develop or master branches and doing a _hexo clean_ does not help with the problem.  I have not updated nor installed any plugins.

The environment is:

hexo: 2.8.3
os: Darwin 14.0.0 darwin x64
http_parser: 1.0
node: 0.10.33
v8: 3.14.5.9
ares: 1.9.0-DEV
uv: 0.10.29
zlib: 1.2.3
modules: 11
openssl: 1.0.1j

Any ideas?

**Comment by tommy351** [comment]
DId you install version 0.2 of hexo-renderer-marked? Please install ver 0.1 instead.

``` bash
npm install hexo-renderer-marked@0.1 --save
```

**Comment by ricardojmendez** [comment]
Hi tommy351,

Thanks for the pointer. I had just been able to work around it by moving node_modules elsewhere and re-running npm_install.

I wasn't aware I had installed any updates, but looking at the package.json for marked it is indeed 0.2.3. I also just noticed that node_modules is on .gitignore so it would not have showed up on the diff nor be affected by my switching branches.

Cheers!
