### ISSUE TITLE
hexo generate error

### ISSUE THREAD

**Issue by dorafmon** [hexojs/hexo#990]
```
TypeError: Cannot read property 'marked' of undefined
    at module.exports (/Users/bobfang/Dropbox/github.io/node_modules/hexo-renderer-marked/lib/renderer.js:53:17)
    at /usr/local/lib/node_modules/hexo/lib/extend/renderer.js:78:38
    at b (domain.js:183:18)
    at Domain.run (domain.js:123:23)
    at store.(anonymous function) (/usr/local/lib/node_modules/hexo/lib/extend/renderer.js:77:9)
    at /usr/local/lib/node_modules/hexo/lib/core/render.js:96:9
    at fn (/usr/local/lib/node_modules/hexo/node_modules/async/lib/async.js:641:34)
    at Object._onImmediate (/usr/local/lib/node_modules/hexo/node_modules/async/lib/async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:345:15)
```

**Comment by tommy351** [comment]
ref #988

**Comment by dorafmon** [comment]
Solved!
