### ISSUE TITLE
Hexo代码块解析bug

### ISSUE THREAD

**Issue by Andrew-liu** [hexojs/hexo#998]
当在```代码块中加入Django模板tag, 上传的时候会出现如下bug

```
[error] HexoError: Process failed: _posts/test-hexo-bug.md
Error: Unexpected colon on line 65 in file /Users/andrew_liu/Andrew-liu.github.io/source/_posts/test-hexo-bug.md.
    at Object.exports.throwError (/usr/local/lib/node_modules/hexo/node_modules/swig/lib/utils.js:183:9)
    at Object.TokenParser.parseToken (/usr/local/lib/node_modules/hexo/node_modules/swig/lib/parser.js:319:15)
    at /usr/local/lib/node_modules/hexo/node_modules/swig/lib/parser.js:86:12
    at Object.exports.each (/usr/local/lib/node_modules/hexo/node_modules/swig/lib/utils.js:45:11)
    at Object.TokenParser.parse (/usr/local/lib/node_modules/hexo/node_modules/swig/lib/parser.js:76:11)
    at parseVariable (/usr/local/lib/node_modules/hexo/node_modules/swig/lib/parser.js:486:18)
    at /usr/local/lib/node_modules/hexo/node_modules/swig/lib/parser.js:633:15
    at Object.exports.each (/usr/local/lib/node_modules/hexo/node_modules/swig/lib/utils.js:45:11)
    at Object.exports.parse (/usr/local/lib/node_modules/hexo/node_modules/swig/lib/parser.js:622:9)
    at parse (/usr/local/lib/node_modules/hexo/node_modules/swig/lib/swig.js:343:19)
```

**Comment by iissnan** [comment]
Try to wrap your Django template code into `{% raw %}{% endraw  %}` block.

```
{% raw %}

Your code here.

{% endraw %}
```

**Comment by ftsqh** [comment]
只要在代码块里出现``}``的时候就会出现这个问题
